### ISSUE TITLE
Doors do not save

### ISSUE THREAD

**Issue by blindsighter314** [FPtje/DarkRP#1130]
I know you have gotten this error before but please Im despereate. Also I have a bit more info than the other reports.
I have updated darkrp completley and have wiped my server twice but this error keeps coming back, I cant afford another restart. Door groups and jail positions never save and sometimes the server will rendomly crash with this error.

[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:33: attempt to index local 'doorData' (a nil value)
1. addKeysDoorTeam - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:33
2. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:344
3. query - gamemodes/darkrp/gamemode/libraries/database.lua:145
4. setUpTeamOwnableDoors - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:337
5. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:152
6. commit - gamemodes/darkrp/gamemode/libraries/database.lua:59
7. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:149
8. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:81
9. unknown - gamemodes/darkrp/gamemode/libraries/database.lua:3

I heard its because my files are curropt but I dont know what keeps curropting them or how I can fix it. Nobody has found a fix for this yet and I really need answers please.

**Comment by zarzwour** [comment]
Didn't work please help
