### ISSUE TITLE
fadmin lua error (kickban)

### ISSUE THREAD

**Issue by JohnAtPG** [FPtje/DarkRP#114]
Random error I found in logs.

Lua Error: 
[ERROR] ...darkrp/gamemode/fadmin/playeractions/kickban/sv_init.lua:62: bad key to string index (number expected, got string)
1. error - [C]:-1
   1. __index - lua/includes/extensions/string.lua:265
   2. unknown - ...darkrp/gamemode/fadmin/playeractions/kickban/sv_init.lua:62

and this one:

Lua Error: ERROR: Hook 'getMySQLBans' Failed: ...darkrp/gamemode/fadmin/playeractions/kickban/sv_init.lua:239: bad key to string index (number expected, got string)

Lua Error: Removing Hook 'getMySQLBans'

**Comment by RareHyperIon** [comment]
i have that error
---------------------------------------------------------------------------------------------------------------
**[ERROR] addons/darkrp_packs/gamemodes/darkrp/gamemode/modules/fadmin/fadmin/playeractions/kickban/sv_init.lua:211: attempt to index local 'args' (a nil value)
  1. callback - addons/darkrp_packs/gamemodes/darkrp/gamemode/modules/fadmin/fadmin/playeractions/kickban/sv_init.lua:211
   2. unknown - addons/darkrp_packs/gamemodes/darkrp/gamemode/modules/fadmin/fadmin/commands/sv_concommands.lua:19
    3. unknown - lua/includes/modules/concommand.lua:54**
---------------------------------------------------------------------------------------------------------------
no one has ever joined my server but me and my two friends and i banned me self by accident and i could not use fadmin unban steamid its weird and i merged my DarkRP addons so i cant get the plugin as new so can someone get the fixed codes for this please? and btw i dont have garrysmod/data/FAdmin/bans.txt. for some reason but im still banned i used the listid im not banned by that i even checked banned users .cfg and nothing to see for that idk whats going on but i bet its something to do with the fadmin plugin so please send me the fixed code :(
