### ISSUE TITLE
[Bug] FAdmin Immunity

### ISSUE THREAD

**Issue by MuteTM** [FPtje/DarkRP#1159]
### Description of the problem

Immunity levels do not affect teleportation of the target, godding and granting/revoking noclip.

![Image](http://cloud-4.steampowered.com/ugc/450653374364688257/C3E0CDF591502D8BC9565CC5C720A1AEB267AC6E/1024x768.resizedimage)
### How I can make the problem happen again

Give someone a higher immunity level and target them. I have an immunity of 100, the player who took the screenshot had immunity of 75.

**Comment by lex2606** [comment]
Sorry, but can I remake this? I read your code many times and I can't find how. I need this, because some admins can teleport me when I busy.

**Comment by FPtje** [comment]
In DarkRP that's desired behaviour

**Comment by lex2606** [comment]
But I need to restrict it.

**Comment by FPtje** [comment]
Sorry, tough luck
