### ISSUE TITLE
Can't Set Job Spawns and Switch Jobs on the spot

### ISSUE THREAD

**Issue by Semajnad** [FPtje/DarkRP#1179]
Hello, I have read some reports of this, however I believe my issue is slightly different?
### Description of the problem

When I use /setspawn mayor' it says "Mayor's spawn position created" but when I set myself to mayor I don't go there?

Also, when I do switch jobs, I switch on the spot, I don't even go to a custom spawn?
### How I can make the problem happen again

'/setspawn mayor', then choose Mayor in the F4 menu.
### Error log pastebin links

("lua_errors_server.txt", "clientside_errors.txt")
No error logs generated?

**Comment by lukemason1** [comment]
This is not the problem i am having, the problem i am having is it says the job does not exist ?

i have tried looking into what you said semajnad and i have tried getting the spawns away but it still comes up saying that the job does not exist ???

**Comment by lukemason1** [comment]
never mind i now know what the problem was, for people who do not know what the problem was.

where it says command in the job which you created, you type that in your /setspawn (command)

**Comment by rocky123xo** [comment]
Is it possible to set a spawn for all jobs? Instead of for each job individually?

**Comment by Zeroinn** [comment]
I'm having the same issue except i've done everything i should have (i think)

[settings.txt](https://github.com/FPtje/DarkRP/files/1081257/settings.txt)
