### ISSUE TITLE
DarkRP SWEPS are "PRINT NAME", F4 menu job changing does not work, No tools in the tools menu

### ISSUE THREAD

**Issue by ghost** [FPtje/DarkRP#1538]
The DarkRP SWEPS are named "PRINT NAME", There's no tools in the tools menu except for custom ones, the F4 menu only allows you to purchase enteties but no ammo and shipments and weapons, non-ownable doors cannot be edited. The only way to change jobs and buy guns/shipments is "/"job"" and "/buyshipment".

The server is connected to a MySQL database. It looks like some tables are not being created/updated.

**Comment by EpicKiing** [comment]
How can I add a lot of addons without getting this error?

**Comment by HDG-MrDeeJay** [comment]
You don't.

Garry's Mod cannot handle lots of addons, especially in a server 
environment.

If you must have lots of addons, consider culling useless addons, such 
as addons that add or remove death effects, or that act as an annoying 
reminder of NLR. You may also consider removing excess weaponry. Try to 
aim for (at the most) 30 guns, with a healthy balance of handguns, SMGs, 
and assault rifles. Minimize use of Snipers and explosives. Lastly, if 
you have any experience in LUA, you may want to consider merging tools 
together where they usually are used together. Examples of merged tools 
include the Colourmator (The colour tool + the material tool in one swep).

Remember to take things out that don't get used. Does nobody buy that 
special weapon that costs $2 billion? Remove it, save the resources for 
something else.

Each little bit adds up, and ultimately if you can run a content rich 
server using as little amount of addons as possible, your player base 
will show it.

**Comment by HDG-MrDeeJay** [comment]
For those receiving this notification via email, this is not a double post. Just fixing formatting cause github fucks up email formatting really hard.

You don't.

Garry's Mod cannot handle lots of addons, especially in a server environment.

If you must have lots of addons, consider culling useless addons, such as addons that add or remove death effects, or that act as an annoying reminder of NLR. You may also consider removing excess weaponry. Try to aim for (at the most) 30 guns, with a healthy balance of handguns, SMGs, 
and assault rifles. Minimize use of Snipers and explosives. Lastly, if you have any experience in LUA, you may want to consider merging tools together where they usually are used together. Examples of merged tools include the Colourmator (The colour tool + the material tool in one swep).

Remember to take things out that don't get used. Does nobody buy that special weapon that costs $2 billion? Remove it, save the resources for something else.

Each little bit adds up, and ultimately if you can run a content rich server using as little amount of addons as possible, your player base will show it.

**Comment by CodedNil** [comment]
A little late but another way to cut down on serverside addons is not install playermodels/clientsided addons on the server, only in resource.AddWorkshop(). Server doesnt need playermodels at all.

**Comment by HDG-MrDeeJay** [comment]
You sure? I thought the server needed it for hitbox detection

**Comment by CodedNil** [comment]
Been running a server for a long time without the server having anything clientonly, working pretty much perfectly, hitboxes are probally just a square for all models, or maybe hitbox detection is just clientsided.

**Comment by HDG-MrDeeJay** [comment]
Odd, well that would explain why hitboxs suck on TTT
