### ISSUE TITLE
Pocket issue [pocket/sv_int.lua:260]

### ISSUE THREAD

**Issue by Codingale** [FPtje/DarkRP#1737]
So our server randomly started saying this, no modifications to the pocket code or really anything.

Makes the server lag and time out. Can provide more info upon request.

```
[ERROR] gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:260: attempt to index field 'darkRPPocket' (a nil value) 
1. func - gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:260 
    2. unknown - lua/includes/modules/net.lua:32
```

Code around Line 260:
260 is the if not part where it's indexing darkRPPocket with item.

```lua

util.AddNetworkString("DarkRP_spawnPocket")
net.Receive("DarkRP_spawnPocket", function(len, ply)
	local item = net.ReadFloat()
	if not ply.darkRPPocket[item] then return end 
	ply:dropPocketItem(item)
end)

```

**Comment by Codingale** [comment]
I was half asleep while making this so sorry for the quality... or lack there of.  I'll be updating to the latest commit and checking if it resolves itself.

**Comment by Bo98** [comment]
Could be a similar issue to #1628 where DarkRPVars on the ply object disappeared and could be happening with the pocket.

**Comment by FPtje** [comment]
I think it's someone sending a faulty message to the server.

2015-01-01 21:58 GMT+01:00 Bo Anderson <notifications@github.com>:

**Comment by Codingale** [comment]
Wow I did the same hotfix... So it should be good?

**Comment by FPtje** [comment]
You are not to do hotfixes. I do them, you update. Get rid of the modifications you made in the DarkRP core files and put them in the darkrpmod addon.

**Comment by Codingale** [comment]
Yeah but the error was out of hand, don't worry I even yelled at the server owner for modifying the core job files instead of the darkrpmodification addon.
