### ISSUE TITLE
Seeing entites as world props,

### ISSUE THREAD

**Issue by OgeGhost** [FPtje/DarkRP#1738]
Okay so, First I have a addon called " Healthstations " and some reason recently every time server reloads or server goes down it deletes all the health stations placed and same for permanent text screens. Permanent text screens won't save anymore

**Comment by FiG-Scorn** [comment]
Take these issues up with the addons' respective developers first, if you haven't already, it may be how they are making their entities spawn.

**Comment by jaw20** [comment]
This recently happened with an update of darkrp so this isn't an addon problem as they worked before.

**Comment by FPtje** [comment]
You're going to have to come with proof that it's me. I can't do anything with the information you've given me.
