### ISSUE TITLE
DarkRP F4 Menu Is A Gray Box

### ISSUE THREAD

**Issue by Joshlisher14** [FPtje/DarkRP#1741]
When i open up my F4 menu it is just a big gray box and when i open the console it says:

[ERROR] gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:99: attempt to compare number with nil
  1. canGetJob - gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:99
   2. setDarkRPItem - gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:117
    3. fillData - gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:357
     4. Init - gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:326
      5. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
       6. F4MenuTabs - gamemodes/darkrp/gamemode/modules/f4menu/cl_init.lua:59
        7. generateTabs - gamemodes/darkrp/gamemode/modules/f4menu/cl_frame.lua:176
         8. openF4Menu - gamemodes/darkrp/gamemode/modules/f4menu/cl_init.lua:12
          9. Call - gamemodes/darkrp/gamemode/modules/f4menu/cl_init.lua:24
           10. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:46

[ERROR] gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:303: attempt to call field 'PerformLayout' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:303

**Comment by Bo98** [comment]
One of your jobs is missing a required "admin" field. You should have an earlier message about a corrupt job.

**Comment by Joshlisher14** [comment]
What am i looking for exactly?

**Comment by Joshlisher14** [comment]
Dont worry, i got it. it was admin = 0, from a job

**Comment by Joshlisher14** [comment]
Ah, now I'm getting:

[ERROR] gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:303: attempt to call field 'PerformLayout' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:303

**Comment by Joshlisher14** [comment]
And
 ] Warning: Unhandled usermessage '_Notify'
] SWEP:SetWeaponHoldType - ActIndex[ "" ] isn't set! (defaulting to normal)

**Comment by FiG-Scorn** [comment]
Any mods, addons, weapon packs, etc that you are using? I have been doubting falco's claims of fixing actindex errors...

**Comment by Joshlisher14** [comment]
Too many addons to list sorry

**Comment by stapler2025** [comment]
Then don't expect help if you can't be bothered.

**Comment by Joshlisher14** [comment]
dude i have at least 100+

**Comment by Joshlisher14** [comment]
and the doors have no text on them

**Comment by Bo98** [comment]
Some addon is causing issues. The errors shown are impossible in vanilla DarkRP.

For example, there is no line with SetWeaponHoldType in DarkRP.

**Comment by FiG-Scorn** [comment]
100+ addons?!? Theres your problem mate, no server needs that many addons.

Cut down to about 60 and see how things run. Target addons that are mostly LUA based
