### ISSUE TITLE
Players cant buy doors

### ISSUE THREAD

**Issue by TheUnknownGamer9** [FPtje/DarkRP#1742]
Hello,

Today my players on my darkrp server cannot buy doors. When they hover over the door, they cannot see the f2 message to buy the door. They also cannot see who owns what doors. This problem started occuring yesterday. I dont know what caused this issue. There are no errors in the console. I do not know how to fix this. Can someone please help me?

Thanks

**Comment by FiG-Scorn** [comment]
Are you running any custom addons? And have you attempted to restart or 
update your copy of DarkRP?

**Comment by TheUnknownGamer9** [comment]
I'm using darkrpmodification for darkrp 2.5. But this was working before, i restarted the server to change a config for an addon, and now players cant see the hud to buy doors. Would reinstalling darkrp help/fix this problem?

**Comment by FiG-Scorn** [comment]
I dont think so, it may have something to do with this config you mentioned.

(although a re-install never hurt anyone)

**Comment by TheUnknownGamer9** [comment]
I'll try to reinstall the darkrp gamemode and ill get back to you.

**Comment by TheUnknownGamer9** [comment]
Reinstalling the darkrp gamemode did not fix my solution.

**Comment by FiG-Scorn** [comment]
Then undo any config changes you made.

**Comment by TheUnknownGamer9** [comment]
Could it be a map issue?

**Comment by FiG-Scorn** [comment]
Did the error start occuring when you changed the map?

**Comment by FPtje** [comment]
Works fine for me.

**Comment by TheUnknownGamer9** [comment]
The issue was in darkrpmodification under disabled_defaults. Where i set the hud to true. I changed it to false and it works now. Thank you for your help.
