### ISSUE TITLE
FAdmin Invalid Arguements

### ISSUE THREAD

**Issue by AceTheGmodGeek** [FPtje/DarkRP#1744]
When I click TAB and click Edit Groups, whenever I try and move any permission with a rp_blank for example rp_doorManipulation and I move it over to allow and it says Invalid Arguements

**Comment by FPtje** [comment]
Sorry, works fine for me
http://i.imgur.com/84egisI.jpg

**Comment by FPtje** [comment]
Does your custom group have spaces in its name?

**Comment by AceTheGmodGeek** [comment]
Nope? Ill show a screenshot though

**Comment by AceTheGmodGeek** [comment]
http://puu.sh/e4qQf/f26c46f732.jpg

**Comment by AceTheGmodGeek** [comment]
http://puu.sh/e4rdH/01de5d7a82.jpg

**Comment by AceTheGmodGeek** [comment]
Where is FAdmin stored? Should I try redownloading darkrp if FAdmin is in it?
