### ISSUE TITLE
FAdmin Error

### ISSUE THREAD

**Issue by AceTheGmodGeek** [FPtje/DarkRP#1745]
Everytime I add permission from tab, so I can use rp_doorManipulaiton, It states http://puu.sh/e4rdH/01de5d7a82.jpg (Invalid Arguements) This happens every time I add anything with rp_   I have no spaces capitals or any other stuff, no symbols

**Comment by AceTheGmodGeek** [comment]
Atleast, Is there any other way I can make it so only ___ can use the door?

**Comment by FiG-Scorn** [comment]
you dont need to make a second issue about it, we still get email alerts 
for closed issues.
