### ISSUE TITLE
Entity removal on owner's disconnect

### ISSUE THREAD

**Issue by Geoxxx** [FPtje/DarkRP#1746]
I'm going to explain my issue in a short way, whenever a player buys a entity, as example, a money printer with the F4 menu, the entity wouldn't dissapear when the owner of it disconnects.

I've done some research on the issue before, but I can't seem to follow the solutions to the issues.

I'm not sure wether these entities lack a line of code or if it's just the current version of the gamemode I have, but as you may already see, I have no idea what is causing it to not work properly.

**Comment by FPtje** [comment]
Not a help forum. Forum.darkrp.com
