### ISSUE TITLE
Yellow Jobs

### ISSUE THREAD

**Issue by Aceman9622** [FPtje/DarkRP#1748]
When I start my server, the extra jobs that I setup in the master file have the yellow color on the tab menu rather than the original colors I set it.  When I update one little thing to the jobs.lua, the server fixes the jobs file.  The jobs in the core files seem to be doing perfectly fine.  Should I just attempt to move the jobs in the jobs.lua (MASTER JOBS) into the jobsrelated.lua (CORE JOBS)?

Any solution?

**Comment by NamefuI** [comment]
No, you should not edit DarkRP's core files at all.. You're doing something wrong and it is not DarkRP's issue because it works for me perfectly fine.

**Comment by FPtje** [comment]
This is not a help forum

**Comment by Aceman9622** [comment]
FPtje, why can't you make a simple answer?  I don't care if it isn't a help forum, a simple,"Hey, just do "this" "this" and "this."  I think that is fucking rude to just close an issue that can easily be handled including for other people to look at later on.  I mean, I'm pretty sure you're not fucking busy if you can reply to these issues in the issue board. 

(Conclusion: Just answer the fucking question.  Tired of,"This isn't a place to ask questions." Well, make it for this one time.)

**Comment by Neosinos** [comment]
Oooor you could just visit the official DarkRP forum to ask for help
instead of spamming developers of DarkRP with nonsense they don't care
about since it's YOUR issue.

Am Donnerstag, 8. Januar 2015 schrieb Ace :

**Comment by FPtje** [comment]
Here's a fucking simple answer:
1. go to forum.darkrp.com
2. Make a god damn thread 
3. Fuck off from this site

Half the issues on this god damn issue tracker are from idiots like you who fail to read the guidelines on posting issues. I'm not making an exception for you.

**Comment by Bo98** [comment]
Just curious about this:

> Tired of,"This isn't a place to ask questions."

This implies you already knew that this isn't a place to ask questions. To get tired of something means you must've seen it a number of times. Why ask here anyway may I ask?

**Comment by FiG-Scorn** [comment]
Because 99% of all DarkRP server owners are pompous self righteous 
preteens with a superiority complex, therefor they think the rules don't 
apply to them and that Falco will be "Their bestest friend ever".

I'm sure I can quote Silvesta or w/e his name is.

**Comment by FPtje** [comment]
What did sylvesta say again?

**Comment by FiG-Scorn** [comment]
Something about life aint all sunshine and rainbows.

I may have my actors mixed up.

**Comment by Noiwex** [comment]
Why do I keep seeing this Nathan guy everywhere

**Comment by FiG-Scorn** [comment]
I'm FiG-Scorn, or as my email address announces me as, "Nathan"

**Comment by FPtje** [comment]
He posts a lot

**Comment by NamefuI** [comment]
I see you everywhere indeed, you're a DarkRP addict..

**Comment by FiG-Scorn** [comment]
nah, just get email alerts for everything, used to be an active 
developer/server owner before moving onto other projects.
