### ISSUE TITLE
Default Laws

### ISSUE THREAD

**Issue by RickyBGamez** [FPtje/DarkRP#1749]
So I edited the core files [keep reading] to remove the default laws, because I couldn't find them under DarkRP-Mods. If I am blind, and they're in there, just let me know, otherwise I say you should allow people to remove the default laws.

**Comment by Bo98** [comment]
GM.Config.DefaultLaws

??

**Comment by FPtje** [comment]
Stopped reading at the [Keep reading] bit.

**Comment by FPtje** [comment]
Bo gave answer.

**Comment by FiG-Scorn** [comment]
You lasted longer than me Falco. I stopped at core.

**Comment by FPtje** [comment]
Hahahaha

2015-01-10 0:53 GMT+01:00 Nathan Davies-Lee <notifications@github.com>:

**Comment by stapler2025** [comment]
I lost it at edited, I saw the message preview and knew exactly where this
was going.

**Comment by FPtje** [comment]
Now waiting for a random guy to come in saying he didn't even start reading, haha

**Comment by FiG-Scorn** [comment]
Well perhaps said random guy already has.

But then how would he know what to reply with.

**Comment by FPtje** [comment]
That would be a joke, and it would have been hilarious had you not ruined it, haha

**Comment by FiG-Scorn** [comment]
Eh, not drugged enough to understand jokes atm sorry.

Gimme a few hours and I'll get it

**Comment by stapler2025** [comment]
What's darkrp?

**Comment by RickyBGamez** [comment]
Bruh, I couldn't find that setting -.- I searched up "Default" and didn't find it.
