### ISSUE TITLE
Problem with my New DarkRP

### ISSUE THREAD

**Issue by FireFIGHTER** [FPtje/DarkRP#1750]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_util.lua:195: attempt to index field 'Access' (a nil value)
  1. hasDarkRPPrivilege - gamemodes/darkrp/gamemode/modules/base/sh_util.lua:195
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:89
    3. AdminLog - gamemodes/darkrp/gamemode/modules/logging/sv_logging.lua:4
     4. log - gamemodes/darkrp/gamemode/modules/logging/sv_logging.lua:21
      5. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:812

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/cl_fadmin_darkrp.lua:4: attempt to index field 'ScoreBoard' (a nil value)
  1. v - gamemodes/darkrp/gamemode/modules/fadmin/cl_fadmin_darkrp.lua:4
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/sh_fadmin_darkrp.lua:98

[Fire@FIGHTER :]|2|STEAM_0:0:19362112] Lua Error:
Couldn't include file 'pp\sh_settings.lua' (File not found) (@gamemodes/darkrp/gamemode/modules/fpp/cl_fpp.lua (line 1))

[Fire@FIGHTER :]|2|STEAM_0:0:19362112] Lua Error:
Couldn't include file 'pp\client\menu.lua' (File not found) (@gamemodes/darkrp/gamemode/modules/fpp/cl_fpp.lua (line 2))

[Fire@FIGHTER :]|2|STEAM_0:0:19362112] Lua Error:
Couldn't include file 'pp\client\hud.lua' (File not found) (@gamemodes/darkrp/gamemode/modules/fpp/cl_fpp.lua (line 3))

[Fire@FIGHTER :]|2|STEAM_0:0:19362112] Lua Error:
Couldn't include file 'pp\client\buddies.lua' (File not found) (@gamemodes/darkrp/gamemode/modules/fpp/cl_fpp.lua (line 4))

[Fire@FIGHTER :]|2|STEAM_0:0:19362112] Lua Error:
Couldn't include file 'pp\client\ownability.lua' (File not found) (@gamemodes/darkrp/gamemode/modules/fpp/cl_fpp.lua (line 5))

[Fire@FIGHTER :]|2|STEAM_0:0:19362112] Lua Error:

can anyone help me with that problem pls?

**Comment by FPtje** [comment]
Not a help forum.

**Comment by FiG-Scorn** [comment]
File not found?

**Comment by FireFIGHTER** [comment]
@FiG-Scorn  i installed last day darkRP but idk why File not found....

**Comment by FireFIGHTER** [comment]
@FiG-Scorn  If you mean i must darkrp reinstall?

**Comment by FiG-Scorn** [comment]
@FireFIGHTER Then you didn't upload it fully. FTP clients sometimes miss files because reasons.

Delete DarkRP from your server.

**Comment by FiG-Scorn** [comment]
Then reinstall it

**Comment by FPtje** [comment]
https://github.com/FPtje/Falcos-Prop-protection/issues/90#issuecomment-57061511

**Comment by FPtje** [comment]
Still not a help forum though

2015-01-10 16:39 GMT+01:00 Nathan Davies-Lee <notifications@github.com>:

**Comment by FiG-Scorn** [comment]
Yeah, i guess.
