### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by AceTheGmodGeek** [FPtje/DarkRP#1751]
I deleted Darkrp and readded it but now its not working
(I deleted it while server was online, I forgot it was online until I finished.)
All the Adverts like the server adverts still work only players cant chat

**Comment by FiG-Scorn** [comment]
Not a help forum.
Forum.darkrp.com

also if there are errors in the console, you may want to put them here.

**Comment by AceTheGmodGeek** [comment]
There arent any errors

**Comment by FiG-Scorn** [comment]
Then off to http://forum.darkrp.com/
