### ISSUE TITLE
/dropweapon leaves SWEP model mid-air and a console error

### ISSUE THREAD

**Issue by ludalex** [FPtje/DarkRP#1752]
I have M9K Weapons on my server.
Latest version of DarkRP from master.

When I try to drop a M9K Swep, as well as any DarkRP/HL2 sweps, weapon worldmodel with a "Count: 0" text remains mid air, unable to be picked up:
![](http://i.imgur.com/rNM0cYB.jpg)
 The "real" weapon though, drops on the floor able to be picked up.
Here's the error that occurs:
```
[ERROR] gamemodes/darkrp/entities/weapons/weapon_cs_base2/sv_commands.lua:26: attempt to call method 'SetWeaponClass' (a nil value)
  1. dropDRPWeapon - gamemodes/darkrp/entities/weapons/weapon_cs_base2/sv_commands.lua:26
   2. unknown - gamemodes/darkrp/entities/weapons/weapon_cs_base2/sv_commands.lua:64

Timer Failed! [Simple][@gamemodes/darkrp/entities/weapons/weapon_cs_base2/sv_commands.lua (line 62)]
```

**Comment by FPtje** [comment]
Looks like a user inflicted error. The error cannot happen with stock code and I cannot reproduce it.
This is not a help forum.
Please go to forum.darkrp.com

**Comment by FiG-Scorn** [comment]
When i first read this i thought of the money song
