### ISSUE TITLE
My Dark RP server's Dark RP (Utitlity) guns are gone

### ISSUE THREAD

**Issue by GrayAreaRP** [FPtje/DarkRP#1753]
When the player joins they don't get pockets and keys e.g. They dont appear in the menu as shown below so you cant spawn them in
![2015-01-13_00001](https://cloud.githubusercontent.com/assets/10521188/5728266/df022fb2-9b60-11e4-9a1a-0e50b7b7131b.jpg)
You cant use FAdmin to spawn them in.
Also they are still listed under each job e.g Civil Protection
![2015-01-13_00003](https://cloud.githubusercontent.com/assets/10521188/5728308/365255bc-9b61-11e4-9bc9-35aa2fcc1e61.jpg)
The Files are all in the Dark RP weapons folder
![folders](https://cloud.githubusercontent.com/assets/10521188/5728352/82a2a282-9b61-11e4-97a1-f05f7a1c6c92.png)
The Default weapons code is still there
![default weapons](https://cloud.githubusercontent.com/assets/10521188/5728995/b4adf68c-9b66-11e4-996a-29c01c0e3496.png)
sbox_weapons is set to 1
Please respond and if this is in the wrong area please move it not delete it.
Thanks ~Rory Sinclair and all the members of Gray Area RP

**Comment by FPtje** [comment]
This is not a help forum.
forum.darkrp.com

**Comment by GrayAreaRP-Fluttershy** [comment]
Oh

**Comment by FPtje** [comment]
Can I ask you a simple question?
Did you notice the link to the [contributing guidelines](https://github.com/FPtje/DarkRP/blob/master/CONTRIBUTING.md) when creating your issue?
