### ISSUE TITLE
[unable to spawn cars / npcs] config is setten up.

### ISSUE THREAD

**Issue by jonas13362** [FPtje/DarkRP#1754]
Hello ,

I putted "2" for admin or higher and it says i have to look the spawning of vehicles has been disabled Please see DARKRP settings but i turned it on 2 so it should work? it worked in 2.5.0.

Greetings

**Comment by FPtje** [comment]
Not a help forum.

**Comment by Bo98** [comment]
What's with the increase in support requests here?

**Comment by FPtje** [comment]
No idea, but I'm going fucking mad

**Comment by Bo98** [comment]
I can't view it but does the "referring sites" part of

https://github.com/FPtje/DarkRP/graphs/traffic

show anything?

I haven't seen a screenshot of one on a popular repo so I have no idea if it's any use at all.

**Comment by Bo98** [comment]
I think it might only show domains so probably not.

**Comment by FPtje** [comment]
http://i.imgur.com/U8cLAIM.png
I'll see what I can do on the wiki.

**Comment by Bo98** [comment]
wow, who's posting adf.ly links?

**Comment by FPtje** [comment]
It's some youtube video.

**Comment by Bo98** [comment]
Perhaps not making "Bug Report" first in the wiki will help? Workshop download should be first IMO.

**Comment by FPtje** [comment]
Well it used to be even worse. I changed it today.

2015-01-14 21:34 GMT+01:00 Bo Anderson <notifications@github.com>:

**Comment by Bo98** [comment]
Yeah I noticed. Just seems odd for "Bug Report" to come before download.
