### ISSUE TITLE
A problem keeping me from playing any DarkRP servers

### ISSUE THREAD

**Issue by JohnWasHere** [FPtje/DarkRP#1756]
For some reason every DarkRP server I play on the f4 doesn't work. When I press f4 on the servers it just jerks my screen flashes the props window and pisses me off. Please help I cant play on anything DarkRP until this works. Yes I have tried to use the commands to replace the glitch but most servers I play on banned the /jobs command. Please help once again and thank you for reading this.

**Comment by Devul** [comment]
Do you run on a laptop, a friend used to have a laptop with F-X- keys that didn't work.

Type bind f4 in console, tell me if that says "f4" = "gm_showspare2"

A fix to your problem, bind gm_showspare2 onto a unused key.

**Comment by FPtje** [comment]
Not a help forum
