### ISSUE TITLE
Everyone can see the logs

### ISSUE THREAD

**Issue by NamefuI** [FPtje/DarkRP#1757]
I have a problem where everyone on the server can see the logs, even regular users with no rp_viewlog priviledge.
I'm not sure if that's my issue, but it happened on two of my different servers.

**Comment by FPtje** [comment]
Is anyone else having this issue?

**Comment by NamefuI** [comment]
Could you try to solve the issue please?

**Comment by HDG-MrDeeJay** [comment]
You haven't given him much to work on man, give him time.

**Comment by NamefuI** [comment]
Okay

**Comment by FPtje** [comment]
I'm sorry, I can't reproduce this. I cannot see the logs when I'm a user in my server. Please head to Forum.darkrp.com.
