### ISSUE TITLE
Shipment Merging

### ISSUE THREAD

**Issue by McSniper1215** [FPtje/DarkRP#1758]
So people keep merging shipments and I hate it when they do that. Its hard to explain why I hate it. How can I stop people from merging shipments?

**Comment by FPtje** [comment]
With the CanProperty hook or the disabled properties DarkRP setting if you add it. This is not a help forum.

**Comment by HDG-MrDeeJay** [comment]
I'm begining to wonder why people keep asking for help here when you 
frequently say "this is not a help forum"... its like they switch T for 
W in the word "not".
