### ISSUE TITLE
People spawning props while arrested

### ISSUE THREAD

**Issue by therealbenny** [FPtje/DarkRP#1759]
It's as simple as that, no lua errors or anything. I have *not* changed the base code and only have added jobs and entities.

**Comment by HDG-MrDeeJay** [comment]
I didn't think DarkRP prevented prop spawning?

**Comment by FPtje** [comment]
Where's your god damn Rainbow Dash, FiG-Scorn? I don't even recognize you like that. It's only because of the email I got that I know it's you.

**Comment by HDG-MrDeeJay** [comment]
Changed my name, got a repository that is associated with my mates 
community and im too lazy to make another account.

Besides, FiG has been dead for years.

And sporting a pony avatar in public only fuels unnecisary shitstorms in 
my first hand experience.

**Comment by therealbenny** [comment]
oh I was spooked for a moment

**Comment by FPtje** [comment]
Your name didn't get any better.
Also, it works for me. This means you have an addon that returns true in the `PlayerSpawnProp`.
Not a help forum.

**Comment by HDG-MrDeeJay** [comment]
>Your name didn't get any better.

My name was selected because of a long story that nobody wants to hear.
That and I got tired of being known as Scorn, the dreaded former-admin 
of a server that all staff of another fear.

**Comment by Bo98** [comment]
When's the next name change?

**Comment by HDG-MrDeeJay** [comment]
Hopefully not for a while, I'm kinda attached to this name. Lol 
thunderbird thinks I want to add an attachment.

**Comment by therealbenny** [comment]
thank you for pointing out what the issue could've been, after a long search I found the culprit! It was URS' prop limit feature.

**Comment by Noiwex** [comment]
Lol, garbage

**Comment by FPtje** [comment]
Please link me to URS

**Comment by FPtje** [comment]
Found it

**Comment by therealbenny** [comment]
Thanks again for the assistance.

**Comment by FPtje** [comment]
Another guy in the FPP repository has the same problem with people being able to spawn blocked props.

**Comment by therealbenny** [comment]
Then I definitely think it was best to remove URS. Does FPP have any prop limit like things included with it?
