### ISSUE TITLE
[FIXED] darkrp problem

### ISSUE THREAD

**Issue by darkrpdoesntwork** [FPtje/DarkRP#1761]
[FIXED]

**Comment by Nigley** [comment]
I also have issues with this, could really use a fix.

**Comment by darkrpdoesntwork** [comment]
i know he cant fix this gamemode, he must spend more time for this i think. i am trying to use dropmoney but it doesnt work yes, i think problem is with darkrp functions, falco you have to recompile it into c

**Comment by darkrpdoesntwork** [comment]
and why cant i put modification folder into the darkrp gamemode, I DONT WANT TO RUN IT FROM ADDONS OMG

**Comment by Nigley** [comment]
I have a problem with my potatoes too: http://puu.sh/eYU7H/113099617b.jpg

**Comment by darkrpdoesntwork** [comment]
i also haev problem with workshop script for fspectate it says me not admin, http://gyazo.com/4a0206de4cc98a0700f60d24562159af

**Comment by HDG-MrDeeJay** [comment]
The b8 is strong
