### ISSUE TITLE
Inventory/pocket !

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#1762]
I've update yesturday and now my addon create me this error ...

[ERROR] addons/ezinventory/lua/weapons/pocket/shared.lua:81: attempt to call method 'OpenInventory' (a nil value) 1. unknown - addons/ezinventory/lua/weapons/pocket/shared.lua:81

How can i fix it ?

**Comment by FPtje** [comment]
not a help forum.

**Comment by Mika32150** [comment]
This is since your update guy... Do you remove 'OpenInventory'  ?

**Comment by FPtje** [comment]
Nope, and I never created it either.
