### ISSUE TITLE
entityvars.lua

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/DarkRP#1763]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:196: Tried to use a NULL entity!
1. SteamName - [C]:-1
2. Nick - gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:196
3. unknown - lua/autorun/init.lua:28

**Comment by FPtje** [comment]
That's an error in your `lua/autorun/init.lua`.

**Comment by NLGBrian** [comment]
how to fix

**Comment by FPtje** [comment]
Not a help forum.
