### ISSUE TITLE
fout

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/DarkRP#1764]
[ERROR] gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:260: attempt to index field 'darkRPPocket' (a nil value)
1. func - gamemodes/darkrp/entities/weapons/pocket/sv_init.lua:260
2. unknown - lua/includes/modules/net.lua:

**Comment by FPtje** [comment]
That error is impossible. What are you even doing!?

**Comment by NLGBrian** [comment]
i deleted deaglelogs, i've added some custom fields to my server..

**Comment by FPtje** [comment]
And by adding custom fields you mean what exactly? Editing core files?

**Comment by NLGBrian** [comment]
nederlands..

**Comment by NLGBrian** [comment]
Heb me job file ge edit...

**Comment by NLGBrian** [comment]
Moet je me .lua file hebbe c;

**Comment by FPtje** [comment]
Just because you know I'm Dutch doesn't mean you can speak Dutch. This is a god damn bug tracker. You're acting like you're retarded and like I'm your buddy who uses this god damn site solely to help Dutch people unfuck the bullshit they caused. Fuck off.

**Comment by NLGBrian** [comment]
>.< 

best developer ever..

**Comment by HDG-MrDeeJay** [comment]
The next thing out of his mouth better be Ich bin retarded.

**Comment by FPtje** [comment]
That's German you idiot.

2015-01-25 20:23 GMT+01:00 Nathan Davies-Lee <notifications@github.com>:

**Comment by HDG-MrDeeJay** [comment]
Yeah, I realised about 2 seconds after clicking send.

God damn it I hate AM. Worst 12 hours of the day.

**Comment by NamefuI** [comment]
FPtje you've got some nerve, you're a tough boy. I like that.
