### ISSUE TITLE
Citizens can buy guns (Bug)

### ISSUE THREAD

**Issue by Gamerzcrafted** [FPtje/DarkRP#1765]
GM.Config.restrictbuypistol 			= true
^^^^^^^^
thats set to true but citizens can still buy ALL weapons heres my shipments file
http://pastebin.com/pcpmAtxL|
Jobs http://pastebin.com/zNCgXr2w

**Comment by HDG-MrDeeJay** [comment]
This sounds like a request for help more than a bug, seeing how every 
DarkRP server I know doesn't have this problem (provided they updated 
any time in the past 3 months).

I think you may get a better answer from the DarkRP forums, 
forum.darkrp.com (if I remembered the link correctly. There is a url to 
it at DarkRP.com)

**Comment by Gamerzcrafted** [comment]
It seems to be a bug because I have went through ALL of my files and there is nothing wrong with them

**Comment by HDG-MrDeeJay** [comment]
Are you using any lua scripts from Coderhire, the Workshop, or 
ScriptFodder that alter or replace core gamemode files?

**Comment by Gamerzcrafted** [comment]
My plugins

BlurGamers Anti Prop Kill
BlurGamers Chat Tags
BlurGamers Crash Recover
BlurGamers Keypad Crackers
BlurGamers Printers
BlurGamers Radio
BlurGamers Theater
BlurGamers Weather
DarkRP Bank Robbery System
dlogs
Expertise
NLRSphere
vectorhud

If you need anything from these ask (like sample codes)

**Comment by Gamerzcrafted** [comment]
didnt mean to close

**Comment by Gamerzcrafted** [comment]
I am moving all the addons out (execpt darkrpmod and ULX)

**Comment by Gamerzcrafted** [comment]
Yes nvm one of the plugins is messing with it will test all of them
