### ISSUE TITLE
Is this my fault?

### ISSUE THREAD

**Issue by pappaesso** [FPtje/DarkRP#1766]
[Esso [dBs]|5|STEAM_0:0:350061] Lua Error:

[DarkRP] gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:80: attempt to index local 'DarkRPVar' (a nil value)
1. readNetDarkRPVar - gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:80
2. func - gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:66
3. unknown - lua/includes/modules/net.lua:32

[Esso [dBs]|5|STEAM_0:0:350061] Lua Error:

[DarkRP] gamemodes/darkrp/gamemode/libraries/simplerr.lua:379: bad argument #1 to 'CompileString' (string expected, got nil)
1. CompileString - [C]:-1
2. inc - gamemodes/darkrp/gamemode/libraries/simplerr.lua:379
3. doInclude - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:32
4. unknown - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:43
5. include - [C]:-1
6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:34

**********************************************************
I only edit files in the DarkRPmodification-master addon.
After these errors my edits don't show in the F4 menu...
Thank you for a great gamemode.

**Comment by pappaesso** [comment]
It happened when I switched from using Steam workshop DarkRP gamemode to my server host's mod package. My host states this:
"DarkRP Gamemode
This will install DarkRP directly from the github repository."
I did this around 09.30 CET.

**Comment by pappaesso** [comment]
I'll try reinstalling the server to see if I can reproduce the issue.

**Comment by FPtje** [comment]
I just pushed an update, see if that gives you a different error. I don't understand what's happening. Basically `darkrp_config/disabled_defaults.lua` apparently exists, but it cannot be read.

**Comment by biorisk2** [comment]
I will re-install and try, I uploaded a copy 30 minutes ago and got the same error.

**Comment by biorisk2** [comment]
[ERROR] gamemodes/darkrp/gamemode/libraries/simplerr.lua:380: bad argument #1 to 'CompileString' (string expected, got nil)
  1. CompileString - [C]:-1
   2. inc - gamemodes/darkrp/gamemode/libraries/simplerr.lua:380
    3. doInclude - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:32
     4. unknown - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:43
      5. include - [C]:-1
       6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:34

**Comment by pappaesso** [comment]
No anti Lua stealer addon (I don't know what it is).

**Comment by pappaesso** [comment]
My reinstall will take app. 15 minutes more. Clean install, just darkRP.

**Comment by pappaesso** [comment]
Ok so I downloaded your darkrp-master at 12:22 CET and added that to my reinstalled Garrys mod server. Then I downloaded darkrp-modification addon (I didn't edit any files in there) and restarted the server and got:

[DarkRP] gamemodes/darkrp/gamemode/libraries/simplerr.lua:380: bad argument #1 to 'CompileString' (string expected, got nil)
1. CompileString - [C]:-1
2. inc - gamemodes/darkrp/gamemode/libraries/simplerr.lua:380
3. doInclude - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:32
4. unknown - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:43
5. include - [C]:-1
6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:34

**Comment by Bo98** [comment]
Is it just happening clientside?

**Comment by pappaesso** [comment]
And by "my reinstalled Garrys mod server" I mean a clean unedited Gmod server, just to be super clear.

**Comment by pappaesso** [comment]
The above is copied from the server console... sry I might not understand you.

This is from server console right at spawn:

ServerLog: Esso [dBs] (STEAM_0:0:350061) Attempted to pick up a gmod_tool
ServerLog: Esso [dBs] (STEAM_0:0:350061) Attempted to pick up a pocket
ServerLog: Esso [dBs] (STEAM_0:0:350061) Attempted to pick up a weapon_physgun
[Esso [dBs]|2|STEAM_0:0:350061] Lua Error:

[DarkRP] gamemodes/darkrp/gamemode/libraries/simplerr.lua:380: bad argument #1 to 'CompileString' (string expected, got nil)
1. CompileString - [C]:-1
2. inc - gamemodes/darkrp/gamemode/libraries/simplerr.lua:380
3. doInclude - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:32
4. unknown - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:43
5. include - [C]:-1
6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:34

**Comment by pappaesso** [comment]
This is from my client console:


PREP OK
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: gm_construct/flatgrass). This wastes perf for no benefit.
clientside lua startup!
Requesting texture value from var "$dummyvar" which is not a texture value (material: NULL material)
TEST [gamemodes/darkrp/gamemode/libraries/disjointset.lua][gamemodes/darkrp/gamemode/libraries/simplerr.lua]
TEST [gamemodes/darkrp/gamemode/libraries/fn.lua][gamemodes/darkrp/gamemode/libraries/simplerr.lua]
TEST [gamemodes/darkrp/gamemode/libraries/interfaceloader.lua][gamemodes/darkrp/gamemode/libraries/simplerr.lua]
TEST [gamemodes/darkrp/gamemode/libraries/modificationloader.lua][gamemodes/darkrp/gamemode/libraries/simplerr.lua]
TEST [gamemodes/darkrp/gamemode/libraries/simplerr.lua][gamemodes/darkrp/gamemode/libraries/simplerr.lua]
FOUND IN ADDON [248302805]
TEST [gamemodes/darkrp/gamemode/libraries/disjointset.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/fn.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/interfaceloader.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/modificationloader.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
FOUND IN ADDON [248302805]
TEST [gamemodes/darkrp/gamemode/libraries/simplerr.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/disjointset.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/fn.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/interfaceloader.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/libraries/modificationloader.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
FOUND IN ADDON [248302805]
TEST [gamemodes/darkrp/gamemode/libraries/simplerr.lua][gamemodes/darkrp/gamemode/libraries/modificationloader.lua]
TEST [gamemodes/darkrp/gamemode/cl_init.lua][gamemodes/darkrp/gamemode/cl_init.lua]
FOUND IN ADDON [248302805]
TEST [gamemodes/darkrp/gamemode/init.lua][gamemodes/darkrp/gamemode/cl_init.lua]

[DarkRP] gamemodes/darkrp/gamemode/libraries/simplerr.lua:380: bad argument #1 to 'CompileString' (string expected, got nil)
  1. CompileString - [C]:-1
   2. inc - gamemodes/darkrp/gamemode/libraries/simplerr.lua:380
    3. doInclude - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:32
     4. unknown - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:43
      5. include - [C]:-1
       6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:34

Failed to load custom font file 'c:/program files/steam/steamapps/common/garrysmod/garrysmod/resource/fonts/ds-digii.ttf'
Failed to load custom font file 'c:/program files/steam/steamapps/common/garrysmod/garrysmod/resource/fonts/lcd.ttf'
Failed to load custom font file 'c:/program files/steam/steamapps/common/garrysmod/garrysmod/resource/fonts/mrb.ttf'
Compact freed 1585152 bytes
Redownloading all lightmaps

**Comment by pappaesso** [comment]
On a lua-knowledge level of 1 to 5 I guess I'm on 0.2 so if you want me to try something be very clear about what and how.

**Comment by Partixel** [comment]
Same error on my server, error started occuring after the simplerr commits

**Comment by NxRE** [comment]
Is there a way to fix this?

**Comment by pappaesso** [comment]
Guess it depends on how good you know lua.. I can't, don't know enough.
And you could go look for an older version... me, I'll just wait.

**Comment by FPtje** [comment]
I'm working on it

2015-02-01 18:28 GMT+01:00 pappaesso <notifications@github.com>:

**Comment by NxRE** [comment]
Thanks.

**Comment by FPtje** [comment]
Looks like an unsolvable issue for now. I've reverted the entire simplerr thing.

**Comment by swyzen** [comment]
Hey - I just installed a money printer addon and restarted my server, then this same issue occured.

It looks like it's not detecting anything from darkrpmodification folder. When I installed the addon, all I did was put in an addon folder and added some stuff in entities.lua . Was there recently a darkrp update that could have caused this or is it something else?

**Comment by HDG-MrDeeJay** [comment]
Are you sure your directory is correctly readable for your addons?

Worst case scenario, you can chmod it to 777 for full unrestricted 
access, however 755 is probably all you may need. Some server providers 
fuck up permissions sometimes because reasons

**Comment by sggamer** [comment]
It's not the provider. It's happening on multiple servers I'm sure across multiple hosts. So what I have tried was fresh install of server. The second I add darkrpmodification folder to addons the errors start and I can't edit or change anything with it on. I literally had to resort to using gamemode for now until it is repaired.

**Comment by swyzen** [comment]
sggamer - just download an updated darkrp manually. fptje fixed it in the newest version.
