### ISSUE TITLE
Random Issue?

### ISSUE THREAD

**Issue by KasperGMOD** [FPtje/DarkRP#1767]
I went on my server and got this error, no idea what it's from, I don't think it's from my side? I updated DarkRP just now from github, still the same error.

[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:80: attempt to index local 'DarkRPVar' (a nil value)
  1. readNetDarkRPVar - gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:80
   2. func - gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:34
    3. unknown - lua/includes/modules/net.lua:32

**Comment by HDG-MrDeeJay** [comment]
See #1766, its the same first error, may not be just you.
