### ISSUE TITLE
Add a way to configure FAdmin in-game that isn't through the scoreboard

### ISSUE THREAD

**Issue by RhapsodySL** [FPtje/DarkRP#1770]
Right now, if you use a custom scoreboard, it's entirely impossible to configure FAdmin in-game.. As far as I can tell looking through the code, there's no commands to access those menus. That's why I'm suggesting making FAdmin configurable from somewhere else, or at least add console commands to open the proper menus. I know I can configure it on the FTP of my server, but this makes it significantly harder since the built-in utility gives me all the info I need.

**Comment by FPtje** [comment]
+FAdmin_menu
