### ISSUE TITLE
error with darkrp

### ISSUE THREAD

**Issue by l-Rocky-l** [FPtje/DarkRP#1774]
[ERROR] addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:694: table index is nil
  1. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:694
   2. include - [C]:-1
    3. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:111
     4. fn - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:119
      5. unknown - addons/ulib/lua/ulib/shared/hook.lua:184

Our servers hitman dont have the press e on me for a hit

**Comment by FPtje** [comment]
Not a help forum
