### ISSUE TITLE
Error with certain weapons

### ISSUE THREAD

**Issue by sam501** [FPtje/DarkRP#1781]
Happens with this weapon pack: http://steamcommunity.com/sharedfiles/filedetails/?id=247684400

Error:
```
[ERROR] attempt to call a table value

Timer Failed! [Simple][@gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua (line 433)]
```

Reproduced by:
```
download darkrp from github, put in gamemodes/ (meaning I am using default settings)
single player
map aim_ag_texture2
kill a player using any weapon from that weapon pack
error produced after babygod is over for the victim
```

I also can't place hits on players using a bot I force set his job to, haven't tested that too far.

**Comment by HDG-MrDeeJay** [comment]
For the guns, you may find its just a shitty fucking addon, just a quick 
look at it and I already don't want to look at the code.

To make matters worse, you are in single player according to your steps 
to reproduce, and you are using a map that wasn't designed for DarkRP.

**Comment by Bo98** [comment]
That looks like the GMod metatable corruption bug. Is this reproducible 100% of the time?

**Comment by HDG-MrDeeJay** [comment]
Uh, mind telling me more about this metatable corruption bug? It may 
explain some issues I've been noticing on my servers where IsPlayer() 
doesn't seem to be a valid function for an entity...

**Comment by FPtje** [comment]
I'll believe Bo in metatable corruption.
