### ISSUE TITLE
Wire Forcer / Grabber not working on Shipments / Printers

### ISSUE THREAD

**Issue by r0wi3** [FPtje/DarkRP#1782]
Hello,

When I try to pick up printers with my forcer it just simply doesnt nor it grabs it.

I've read that you disabled that cause of duplication but is there a way you could readd that ?

I got a good reason and that is because Server Owners simply can block the tools from Users and that only trusted staff or donator can use it, Never had I ever dealt with any problems like that before so could you readd that so it is possible again ?

**Comment by FPtje** [comment]
Allow the things in the FPP Gravgun settings. I think that was it.
