### ISSUE TITLE
2.6.0 broke my server

### ISSUE THREAD

**Issue by swyzen** [FPtje/DarkRP#1785]
Yo, I updated to 2.6.0 and my server borke due to an SVN issue (init.lua got corrupted with some random symbols) and I got rid of that and it fixed the main problem.

But now, people spawn as unassigned, and none of my entities or shipments or ammo are there, just the default money printer. 

No, I didn't edit any core gamemode files.

The entities and jobs were working just fine before the update.

Thanks

**Comment by swyzen** [comment]
The fancy new error system shows that a random job is configured incorrectly, something about its playermodel, but that's never been a problem before and it works/has worked just fine.

**Comment by swyzen** [comment]
keeps saying random shipments have broken models and it disables absolutely everything.. seriously. didnt have a problem witht his before..

**Comment by swyzen** [comment]
jk all fixed

**Comment by HDG-MrDeeJay** [comment]
1. You are an idiot. If something is corrupt, don't modify it, reinstall it.
2...
 >No, I didn't edit any core gamemode files.
The only way that jobs would ever screw up that bad is if you fucked 
with core files, or completely shat all over the custom jobs file. Same 
with entities. Didn't Falco add some detection against that? IDK, i've 
been playing too much CS:GO lately.
3. What the fuck is 2.6.0? Last I checked, we were still on 2.5.1, 
unless I missed a memo.

And so, without further delay, you are henceforth known as a pinhead and 
I bid thee adieu.

**Comment by FPtje** [comment]
2.6.0 was released yesterday.

**Comment by HDG-MrDeeJay** [comment]
Ah. Yesterday was a Wednesday right?

**Comment by FPtje** [comment]
no

2015-02-15 20:41 GMT+01:00 Nathan Davies-Lee <notifications@github.com>:

**Comment by HDG-MrDeeJay** [comment]
Goodie, that means I don't have to look like im looking for work today.

**Comment by OperationLegend** [comment]
How did you fix it? I have the same problem

**Comment by swyzen** [comment]
Just change the models of everything that comes up as an error to something generic, restart the server then see what else has an error and just keep doing that till it's fixed.
