### ISSUE TITLE
[Suggestion] Job Category

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#1789]
How about actually creating a new Job Field where Server Owners can set their own Category?

eg
```lua
     TEAM_PIRATE = DarkRP.createJob("Pirate", { -- That's TEAM_PIRATE (Used for like AddCustomDoorgroup or Add to only that group to a door. Also, never use the same TEAM_)
        color = Color(80, 5, 255, 0), -- Chat / Scoreboard Color
        model = "models/player/swat.mdl", -- Model; to add multiple use  {"models/../model1.mdl","models/../model2.mld},  NOTE the extra comma after the bracket.
        description = [[Description.]], --Description for Job.
        weapons = {"med_kit"}, -- Weapons for a job. Seperate them with a "," eg: "med_kid", "armor_kit" always finish the last one without a ","
        command = "pirate", --Chat command for job. Don't use the same as another teams.
        max = 5, -- Maximum amount of players for this job.
        salary = 200, -- The salary they get paid.
        admin = 0, -- Requires Admin? 1 for yes, 0 for no.
        vote = true, -- Do they need to vote? true for yes, false for no.
        hasLicense = true, -- Do they have a license for weapons?
        category = {"pirates"}, -- Custom Job Category
     })
```

For one simple reason;
This is how server owners could make their custom Menus / NPCs only list categorys there instead of hardcoded teams. For example; I could place a government NPC which will list government Jobs - or make a own Tab in my custom F4 Menu. With this way I could easily list all jobs in this category (of course if you also supply the field with a linked hook, otherwise its pointless). So, since I can now create all types of custom categorys I would never ever need to change the coding in the NPC or the F4 Menu, I just simply need to change the category of the jobs. I could even assign multiple categories if a job should show up somewhere else too.

Not only this, but also such a function would make it a lot easier to actually get job categorys in a custom F4 Menu without hardcoding every TEAM_XY in it.

Opinions? I hope you'll get what I mean, even though I expressed it weird.

**Comment by HDG-MrDeeJay** [comment]
I think this is a great idea, the issues involved in making your own job 
tab, and hiding jobs from the old one, i think this option will be 
great. Also, given its just a field in the job, it would not create any 
backwards compatibility issues. My only concern is how to index all the 
categories. Create them after we have indexed all jobs? I don't think 
so. Perhaps something like DarkRP.createJobCategory("vip") and 
DarkRP.removeJobCategory("vip") could be viable options, just like 
making a team hitman.

Then these categories can be further enhanced, with a custom check.

 >DarkRP.createJobCategory("vip",function(ply) return 
ply:IsUserGroup("vip") or ply:IsAdmin() end)

You could then theoretically have VIP job tabs that only appear when you 
are VIP.

Thats my opinion on the matter

**Comment by HDG-MrDeeJay** [comment]
For you guys receiving this as an email, I reposted cause markdown.

I think this is a great idea, the issues involved in making your own job 
tab, and hiding jobs from the old one, i think this option will be 
great. Also, given its just a field in the job, it would not create any 
backwards compatibility issues. My only concern is how to index all the 
categories. Create them after we have indexed all jobs? I don't think 
so. Perhaps something like DarkRP.createJobCategory("vip") and 
DarkRP.removeJobCategory("vip") could be viable options, just like 
making a team hitman.

Then these categories can be further enhanced, with a custom check.

```lua
DarkRP.createJobCategory1("vip", function(ply) 
    allowed = ply:IsUserGroup("vip") or ply:IsAdmin()
    return allowed,"You do not have access to the VIP jobs tab because you are not a VIP."
end)
```

You could then theoretically have VIP job tabs that only appear when you 
are VIP.

Thats my opinion on the matter

**Comment by FPtje** [comment]
I don't see it. The menu has one jobs tab, one entities tab, one vehicles
tab, one shipments tab etc. You want to be able to have a tab for O e half
of the jobs, one tab for another half?

Substitute job with shipment/entity/vehicle/... And you've got equally well
argumented feature requests for basically f4 menu tab explosion.

Not to mention this is a shitton of work.

**Comment by HDG-MrDeeJay** [comment]
Then organise the jobs tab itself. Put them under different categories, 
sorta like if I tag my friends as CS:GO buddies in Steam.

**Comment by stapler2025** [comment]
So, category headers?

**Comment by HDG-MrDeeJay** [comment]
yeah that

**Comment by Neosinos** [comment]
It wouldnt only be to make a seperate Tab. It's for people who have custom
F4 Menus and wan't to make their own way of structure. Or for people who
use NPCs to get Jobs. Or for other menus where you could may implement the
jobs - this would make such a huge improvement in terms of freedom. I could
simply create a government menu and list all government jobs there with
ease and without me hardcoding all the jobs into the menu.

This is nothing which would change the default DarkRP in any way - its just
a new way for people to customize their server without again touching core
files or hardcoding things.

2015-02-17 8:34 GMT+01:00 Nathan Davies-Lee <notifications@github.com>:

**Comment by FPtje** [comment]
You can already add arbitrary fields in jobs and have custom scripts use
them.

**Comment by Neosinos** [comment]
This is still not the actual point of it. As you can read from the other
people who contributed in this Suggestion theres loads of stuff more you
could do with this kind of thing. In my opinion one of the hugest
improvements if you actually wan't the users of DarkRP have freedom about
the structure of their job system. Except you wan't to force them to only
use it the way you like it, but then don't blame people if they try it with
other stupid ways which could may break stuff.

2015-02-18 9:43 GMT+01:00 Falco Peijnenburg <notifications@github.com>:

**Comment by FPtje** [comment]
I'm just saying that you don't need *me* when you want to implement this in
a custom F4 menu. This was a counterargument to your previous post. Whether
it should be in the default F4 menu is a different discussion, namely the
one held before your previous post.

**Comment by Neosinos** [comment]
No, I don't need this to implement it. But it would be a super easy
solution. Otherwise the only thing I could do is to have a stupid stupid
and non-transparent solution.

2015-02-18 10:04 GMT+01:00 Falco Peijnenburg <notifications@github.com>:

**Comment by FPtje** [comment]
Whatever I implement will affect the default F4 menu only. The only benefit
other F4 menus will have is that "category" will be a default and
established field.

2015-02-18 10:15 GMT+01:00 Marcel Leonhard <notifications@github.com>:

**Comment by FPtje** [comment]
Also, 

> I could even assign multiple categories if a job should show up somewhere else too.

Say you have a job "Cleaner" under categories `{"Citizen", "Poor"}`, would you want that job to appear in the F4 menu twice? That is, once for either category? I'm not sure whether we'd really want that, because  it begs the questions  *"Why are there two cleaner jobs?"* and *"Hold on, is the citizen cleaner different from the Poor cleaner?"*

**Comment by HDG-MrDeeJay** [comment]
So in the end the way I perceive it to be, with some help from both of you guys, is that you can categorize jobs with headers in the list. The header color can change according to a value in an array (color), much like how jobs allow you to change their color, or change their button text/color. We first list all jobs that have a category, then put all remaining jobs into a core-added category, that is yet to be named ("Unsorted", "Default", or "Non-Categorized" (that was spell checked) ?).

The end result is that server owners can bypass this "Extra job tab for VIP shit" thinking, and have high priority jobs at the top of the list. The way I perceive creating these tabs is like this, something similar to jobs.lua... (Excuse my style of commenting code, ive picked up a few bad habits.)

```lua
DarkRP.createCategory("Military", {
    color = Color(255,0,0,255), --(( Red ))
    sortOrder = 1, --(( We should load this early. Anything with a higher sort order will be loaded below this.))
    customCheck = function(ply)
        local rank = {"trusted","donator","admin","superadmin"} --((Normally this would be defined elsewhere, such as the head of the file. That way it doesn't interfere with DarkRP and it doesn't have to be redefined every 5 seconds.))
        for _,v in pairs(rank) do
            if ply:GetNWString("usergroup") == v then return true else return false end --((NWString > IsUsergroup. I believe the latter is ULX only, whereas NWString supports FAdmin, as well as ULX as ULX and FAdmin _TRY_ to work in harmony most of the time))
        end
    end,
})
```

**Comment by FPtje** [comment]
And about the multiple categories per job?

**Comment by FPtje** [comment]
Oh, you discarded that idea. I only read the email at first. 

What does the customCheck mean and how is it related to a job's customCheck?

**Comment by HDG-MrDeeJay** [comment]
customCheck is used to decide whether the category is hidden or not. If 
for whatever reason you would like a function that decides whether the 
damn thing exists or not. Otherwise it wudnt be vry costumzable n wudnt 
fet in wif my costum servar.

On that note, as an optional idea, we can make the categories 
collapsable, and add a key to that category named "collapsed", Boolean.

**Comment by FPtje** [comment]
The customCheck in all other cases means "can you have it". It decides
whether you can have a job, shipments, entity or whatever. It was unclear
enough that I had to ask for it. A better name would be "hidden" if Marcel
means what you said.

**Comment by HDG-MrDeeJay** [comment]
Yeah sorry I wasn't being precise. I pictured the customCheck to be, in more possibilities than others, to be "Grayed out" of sorts... perhaps with a message saying "You cannot select these jobs because X reason", ( I was 50/50 on this to a point that I didn't include CustomCheckFailMsg )

hidden is probably a better word, however its simple 1 word variable gives the impression that it isn't a function (if you think about it), so maybe hiddenCheck?

Of course, separating this from collapsed, where the category is visible, but the contents are moved out of sight to reduce vertical space used when not looking in that category.

**Comment by FPtje** [comment]
Replying to your first paragraph: What if for job X, its category's
customCheck returns false, but the job's customCheck returns true? Have the
category override the job? What then if it's the other way around?

You can define rules about that, but it would make things complicated for
end users. I'd rather have it so that a category makes no judgement about
whether people can become jobs that have this category. In that sense a
"hidden" check is much better because it applies to the category itself
only.

**Comment by HDG-MrDeeJay** [comment]
@FPtje Yeah, that's probably better then.

**Comment by kulcris** [comment]
I too would love this to be implemented, i love using the default f4 menu but sometimes things get cluttered to the point that it is hard to find what you are looking for, 
if this does get implemented could you add it to entities as well, for example i have 6 different money printers and about 20 upgrades, having those in a different sub category then my ammo crates would make everything look so much better

**Comment by FPtje** [comment]
I was afraid people would ask this.

**Comment by Steffion** [comment]
You could just sort the jobs yourself? Just add all 'gangster' related jobs next to each other. Same with printer upgrades.

**Comment by Neosinos** [comment]
It's about Categorys which can be listed somewhere else rather then just
the F4 menu plus Categorys which can be opened/closed as well as hundreds
of other options of easier design structure and better overview. You didnt
get the point Steffion.

And Falco, why are you afraid? Cause it's a lot of work? Yeah - it is, but
it's something which really advances the experience of DarkRP, and as you
can see loads of other users would like this feature too.

Am Sonntag, 15. März 2015 schrieb Steffion :

**Comment by FPtje** [comment]
I meant that I suspected it. The "afraid" wording was more like "yeah this
is a logical step, and I did expect the request, but effort" :v

2015-03-15 19:42 GMT+01:00 Marcel Leonhard <notifications@github.com>:

**Comment by kulcris** [comment]
that is not the point, if there are lots of jobs, collapsible categories would make looking for a job easy, 

example, 
i wana be a cop
 scroll scroll scroll oh i must have missed it
scroll scroll scroll, there it is

with categories
i wana be a cop
scroll click 
what kind of cop do i want to be
click

**Comment by FPtje** [comment]
Fuck derma

**Comment by HDG-MrDeeJay** [comment]
I already have those words engraved in my gravestone

**Comment by FPtje** [comment]
http://wiki.darkrp.com/index.php/DarkRP:Categories

**Comment by HDG-MrDeeJay** [comment]
Remind me to send you a carton of beer.

One day...

**Comment by FPtje** [comment]
I don't like the taste of beer.

**Comment by HDG-MrDeeJay** [comment]
good. Neither do i.

**Comment by Neosinos** [comment]
Beer is lovely, try Kölsch. Love this one, more lighter then most others.

Thanks for that Falco, finally :) Though I havent checked the Documentation
yet, but I'm sure it should be great.

Am Samstag, 21. März 2015 schrieb Nathan Davies-Lee :

**Comment by HDG-MrDeeJay** [comment]
Euch, give me a bottle of Vodka any day.

**Comment by FPtje** [comment]
Ouzo fan here

**Comment by kulcris** [comment]
local customFiles = {
	"darkrp_customthings/categories.lua",

it doesnt load custom categories

**Comment by kulcris** [comment]
modificationloader.lua in corefiles

**Comment by kulcris** [comment]
once i added that it loaded perfectly

**Comment by FPtje** [comment]
Whoops

**Comment by kulcris** [comment]
lol story of my life, other then that this update was a hit for me and my server :+1:

**Comment by kulcris** [comment]
also one more small suggestion if category == nil then category == "other"

**Comment by FPtje** [comment]
that's already the case

**Comment by kulcris** [comment]
Oh I have a few entities that don't show up on the go at all that are
defined inside another addon instead of in the entities.lua

**Comment by FPtje** [comment]
Fixed in latest

**Comment by kulcris** [comment]
Thanks again :beers: Cheers
