### ISSUE TITLE
Language module issue

### ISSUE THREAD

**Issue by ArankHawk** [FPtje/DarkRP#1791]
I made a Chinese language file for DarkRP.
But in game some strings show the original English strings.
For example:
```lua
hear_noone = "沒人聽得見你%s!",

talk = "文字交談",
speak = "語音交談",
```
In game it shows , '沒人聽得見你talk!'

**Comment by FPtje** [comment]
Tell me when you have other translating issues!

**Comment by ArankHawk** [comment]
Thank you!
I will check other translating issues out!
