### ISSUE TITLE
Corrupt Team ( No problems before updating to the version of darkrp with simplerr )

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1795]
[ERROR] A runtime error has occurred in "[C]" on line -1.
The best help I can give you is this:

Corrupt team: OMOH!
The model must either be a table of correct model strings or a single correct model string.

Hints:
	- This error could happens when the model does not exist on the server.
	- Are you sure the model path is right?
	- Is the model from an addon that is not properly installed?

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. [C] on line -1
	2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 413
	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80
	4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 119
	5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 127
	6. addons/ulib/lua/ulib/shared/hook.lua on line 183
------- End of Simplerr error -------

The relevant job.lua info:

TEAM_OMOH = DarkRP.createJob("OMOH", {
	color = Color(255, 51, 0, 255),
	model = "models/omonru/riot/riot_ru.mdl",
	description = [[Your duty is to protect the Town from Armed Criminals. You should stay in the PD until backup is needed. Do everything you can to keep the Town safe.]],
	weapons = {"cw_g4p_usp40", "cw_ar15", "riot_shield"},
	command = "omoh",
	max = 4,
	salary = 600,
	admin = 0,
	vote = true,
	hasLicense = true,
	info = {owner = "Server", tier = "staff"},
	group = {main = "police"}
})

**Comment by Bo98** [comment]
Do you have a link to the addon that contains "models/omonru/riot/riot_ru.mdl"?

**Comment by Partixel** [comment]
Uh, it's an addon on the workshop, I'll get the link..

**Comment by HDG-MrDeeJay** [comment]
Is your server fetching this addon on startup via a workshop collection? 
Lately there has been some issues with the Dedicated Server not fetching 
the workshop addons correctly. See the comments of #1794 for a more 
detailed post by FPtje regarding the matter.

**Comment by FPtje** [comment]
I'll throw it on that. Workshopper is also having issues.

**Comment by HDG-MrDeeJay** [comment]
@Partixel 
>The model isn't on the server though, not sure why it would need to be on the server?

In order for the server to calculate the hitboxes and physics, the model needs to be on the server. This is why money and weapons float when CS:S isn't mounted; because the model's aren't available, so you can't hit trace them, you can't calculate physics for them, they don't exist.

**Comment by Partixel** [comment]
Welp, okay. Why were they working fine before hand?

**Comment by HDG-MrDeeJay** [comment]
Because garry and bugs go hand in hand.

**Comment by Bo98** [comment]
DarkRP never checked if a model was valid before, that's why.

**Comment by Partixel** [comment]
I meant, it was _working_ before, no errors at all.
