### ISSUE TITLE
Suddenly an error while nothing has changed

### ISSUE THREAD

**Issue by MichaelSwag** [FPtje/DarkRP#1797]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:351: attempt to call field 'doorIndexToEnt' (a nil value)
1. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:351
2. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:291
3. setUpNonOwnableDoors - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:347
4. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:152
5. tableExists - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:375
6. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:181
7. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:186
8. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:150
9. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:85
10. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:156

Timer Failed! [Simple][@gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua (line 154)]

**Comment by Bo98** [comment]
Do you have the doorsystem module disabled? Or do you have any additional errors on server start?

**Comment by MichaelSwag** [comment]
No i have only installed a reskin for the doorsystem
and here are the console logs: http://pastebin.com/9nnGCmjp

**Comment by FPtje** [comment]
This error can't be DarkRP's fault. The function is defined.

**Comment by MichaelSwag** [comment]
How can i fix it then? or whats the problem i have no addons that connect with mysql or something

**Comment by HDG-MrDeeJay** [comment]
perhaps you can try removing the reskin.

**Comment by FPtje** [comment]
I honestly have no idea how you managed to remove that function. The best
guess I can give you is that you disabled the doorsystem module in the
disabled_defaults.

2015-02-21 11:27 GMT+01:00 MichaelSwag <notifications@github.com>:

**Comment by MichaelSwag** [comment]
But do poeple cant own doors then?

**Comment by HDG-MrDeeJay** [comment]
what

**Comment by MichaelSwag** [comment]
Thank you it will probably be the door system reskin I think because I've never seen a server that uses the
i gonna test it right now

**Comment by MichaelSwag** [comment]
Thanks for ur help guys its working now!
