### ISSUE TITLE
cl_init errors

### ISSUE THREAD

**Issue by icarusfoundyou** [FPtje/DarkRP#18]
On the initial load of the server:
[Player] Lua Error:
Couldn't include file 'darkrp\gamemode\cl_init.lua' (File not found) (<nowhere>)

[Player] Lua Error:
Couldn't Load Init Script: 'darkrp/gamemode/cl_init.lua'

If I do a changelevel then this error doesn't appear and it works fine.

**Comment by Brandino480** [comment]
That seems to fix the problem, I tried it as well. Very strange fix. Still, it does the job.
