### ISSUE TITLE
Command to disable FAdmin scoreboard

### ISSUE THREAD

**Issue by FPtje** [FPtje/DarkRP#1801]
because people don't know how to remove hooks.

**Comment by Bo98** [comment]
Make sure it doesn't turn into FAdmin_IsScoreboard v2.0. Servers forced that to 0 on clients and it was an archived concommand.

**Comment by HDG-MrDeeJay** [comment]
You really shouldn't tell people to remove hooks, else you get shit like 
that really popular votemenu for TTT that everyone paid for from 
coderhire, that removes EVERY FUCKING HUD HOOK. Yeah, even the chat 
hook. Just so he can localize them.

**Comment by FPtje** [comment]
Some people can't do anything right.

**Comment by HDG-MrDeeJay** [comment]
Tell me about it. The amount of shitheads that get their works published under the guise of being good...

we got maps with clipped walls where you got nodraw'd brushes where you can see the entire map.
We got scripts that remove hooks that they shouldn't and that is the only time they localize shit.
We got people who don't make their own derma skins AT ALL. Ever.

Back in my day, we used to code our own wiremods. There was none of this coderhire shit, it was all garrysmod.org and the wiki.

**Comment by FPtje** [comment]
Fuck convars
```
FAdmin.SetGlobalSetting("FAdmin", true)
```
