### ISSUE TITLE
Update to DarkRP 2.6 - Erorrs with some modules

### ISSUE THREAD

**Issue by GmodLua** [FPtje/DarkRP#1802]
Hey,

I recently updated from 2.5 to 2.6 and since then, I've been getting the following errors in my web console;

Couldn't include file 'sh_config.lua' (File not found) (@addons/darkrpmodification/lua/darkrp_modules/tcb_motd/sv_motd.lua (line 9))

Couldn't include file 'sh_config.lua' (File not found) (@addons/darkrpmodification/lua/darkrp_modules/shud/sv_shud.lua (line 8))

I never had this issue previously so assuming it's something that has been changed on your end?

**Comment by Bo98** [comment]
How recently? There was a problem with relative paths which should be fixed as of a week ago.

**Comment by FPtje** [comment]
Yup

**Comment by GmodLua** [comment]
Recently as in this morning so around 4 hours ago.. I'm now also getting this error;

[ERROR] A runtime error has occurred in "addons/ulx/lua/ulx/modules/sban.lua" on line 143.
The best help I can give you is this:

Attempt to call Name/Nick/GetName on a non-existing player!

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/ulx/lua/ulx/modules/sban.lua on line 143
	2. addons/ulx/lua/ulx/modules/sban.lua on line 195
	3. addons/ulx/lua/ulx/modules/sban.lua on line 136
	4. addons/ulx/lua/ulx/modules/sban_mysql.lua on line 106
	5. [C] on line -1
	6. addons/ulib/lua/ulib/shared/hook.lua on line 183
------- End of Simplerr error -------

[ERROR] A runtime error has occurred in "addons/ulx/lua/ulx/modules/sban.lua" on line 143.
The best help I can give you is this:

Attempt to call Name/Nick/GetName on a non-existing player!

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/ulx/lua/ulx/modules/sban.lua on line 143
	2. addons/ulx/lua/ulx/modules/sban.lua on line 195
	3. addons/ulx/lua/ulx/modules/sban.lua on line 136
	4. addons/ulx/lua/ulx/modules/sban_mysql.lua on line 106
	5. [C] on line -1
	6. addons/ulib/lua/ulib/shared/hook.lua on line 183
------- End of Simplerr error -------

**Comment by FPtje** [comment]
What part of this:
```
The responsibility for this error lies with (the authors of) one (or more) of these files:
1. addons/ulx/lua/ulx/modules/sban.lua on line 143
2. addons/ulx/lua/ulx/modules/sban.lua on line 195
3. addons/ulx/lua/ulx/modules/sban.lua on line 136
4. addons/ulx/lua/ulx/modules/sban_mysql.lua on line 106
```
do you not understand? Is it the word "responsibility"?

**Comment by HDG-MrDeeJay** [comment]
Nah, its the part where he doesn't know how to read.

**Comment by GmodLua** [comment]
I'm sorry that your new "update" has broken people's servers.

I have made life easier by removing it from darkrp
