### ISSUE TITLE
Job Vote not working

### ISSUE THREAD

**Issue by MichaelSwag** [FPtje/DarkRP#1803]
Hello if i vote for a job like Civil Protection then do it say vote created but it dont display to other players.

**Comment by HDG-MrDeeJay** [comment]
This dont happen on darkrp default. You broke it. http://forum.darkrp.com/

**Comment by MichaelSwag** [comment]
Can i find it there or do i need to create a new Thread

**Comment by HDG-MrDeeJay** [comment]
create new thread, that way it will be top of the forum and everyone 
will see it

For those receiving this via Email, the pain... THE PAIN

**Comment by FPtje** [comment]
Not a help forum.

**Comment by MichaelSwag** [comment]
Fixed (not updated config)
