### ISSUE TITLE
[Help] Restricting what jobs can place hits.

### ISSUE THREAD

**Issue by Icee2199** [FPtje/DarkRP#1805]
Hello.

I created a module in darkrpmodification/modules.

In this module, I created a file named "sh_restricthit.lua". This file contained the following code:

```
hook.Add("canRequestHit", "bbb", function(hitman, customer, target, price) if customer.DarkRPVars.job == "Citizen" then return 0,"You cannot place hits as a citizen!" end end)
```

When the server is run, a citizen can still place hits. Why is this?

Any help is greatly appriciated.

Thanks,

Icee2199

**Comment by HDG-MrDeeJay** [comment]
Not a help forum. forum.darkrp.com

**Comment by HDG-MrDeeJay** [comment]
And to make matters worse...

 >then return 0

doesn't this return true?
