### ISSUE TITLE
DarkRP 2.6.0 - Issues

### ISSUE THREAD

**Issue by Apache-64** [FPtje/DarkRP#1807]
DarkRP.createEntity("Water", {
	ent = "eml_water",
	model = "models/props_junk/garbage_plasticbottle003a.mdl",
	price = 50,
	max = 3,
	cmd = "buywater",
	allowed = {TEAM_METHCOOK},
})

There are 2 Lua problems!
	Please check your console for more information!
[ERROR] A runtime error has occurred in "[C]" on line -1.
The best help I can give you is this:

Corrupt entity: Water!
The model of the entity must be a valid model.

Hints:
	- This error could happens when the model does not exist on the server.
	- Are you sure the model path is right?
	- Is the model from an addon that is not properly installed?

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. [C] on line -1
	2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 412
	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80
	4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 119
	5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 127
	6. addons/ulib/lua/ulib/shared/hook.lua on line 183
------- End of Simplerr error -------

gamemodes/darkrp/gamemode/libraries/simplerr.lua:462: [ERROR] A runtime error has occurred in "[C]" on line -1.
The best help I can give you is this:

Corrupt entity: Water!
The model of the entity must be a valid model.

Hints:
	- This error could happens when the model does not exist on the server.
	- Are you sure the model path is right?
	- Is the model from an addon that is not properly installed?

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. [C] on line -1
	2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 412
	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80
	4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 119
	5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 127
	6. addons/ulib/lua/ulib/shared/hook.lua on line 183
------- End of Simplerr error -------

My whole server was fine until i updated to DarkRP 2.6. 
It's not really an bad error either and it's causing real problems, can't you possibly make a config so you can enable/disable the Simplerr Error debug checker

Thank you for your time

- Apache64

**Comment by Apache-64** [comment]
Problem fixed - The model is custom and Not in Garry's Mod it's self... Although, i was still wondering if you could add the config for the error debug checker, That'd be great for the noobies like myself.

Thank you.

**Comment by FPtje** [comment]
Simplerr should simply not make mistakes in its judgement. Was the model
really wrong or did Simplerr lie? What addon is this model from?

**Comment by Apache-64** [comment]
DarkRP.createEntity("Water", {
	ent = "eml_water",
	model = "models/props/cs_office/water_bottle.mdl",
	price = 50,
	max = 3,
	cmd = "buywater",
	allowed = {TEAM_METHCOOK},
})


It's a garry'smod Default prop and it's causing me lua errors again ._.

**Comment by HDG-MrDeeJay** [comment]
Yeah its clear that model checks dont work.

**Comment by Apache-64** [comment]
Well is there any fix's for it ? :z

**Comment by HDG-MrDeeJay** [comment]
Not that I'm aware of.

**Comment by FPtje** [comment]
Shit should be fixed
