### ISSUE TITLE
FAdmin Jail

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1808]
You can glitch outside of the FAdmin jail.
I would suggest to freeze players inside of it or check if a player got outside the jail and port him back in the jail to prevent this.

**Comment by FPtje** [comment]
And you're not going to tell me how?

**Comment by HDG-MrDeeJay** [comment]
I thought FAdmin already checked if someone did a naughty and got out of jail...

**Comment by HDG-MrDeeJay** [comment]
Wait no, that was s ULX. My mistake.

**Comment by deinemudda32** [comment]
You can glitch out by sleeping in some jails, either with some custom sweps and the unstuck command I'm using.
