### ISSUE TITLE
How do I grab a job color from the jobs.lua tables.

### ISSUE THREAD

**Issue by austin1346** [FPtje/DarkRP#1809]
I'm creating a HUD for my server, and I need to figure out how to return a player job color from the table. I'm not very fluent in Lua, but I know some stuff. Thanks in advance.

**Comment by HDG-MrDeeJay** [comment]
It's nice to know that you are interested in creating unique content for DarkRP. Unfortunately, the GitHub issue tracker is reserved for _*Bug Reports*_ and _*Feature Requests*_ only. As your issue contains neither of those things, the issue will be closed shortly by @FPtje 

For further assistance with your problem, I advise you create a thread at http://forum.darkrp.com/. You may also find the answer to your problem within DarkRP's Wiki, which can be found by going to http://wiki.darkrp.com/.

**Comment by FPtje** [comment]
Not a help forum.
