### ISSUE TITLE
weapons cant be unrestricted

### ISSUE THREAD

**Issue by xXthatNAVYguyXx** [FPtje/DarkRP#1811]
I have the ability from the settings menu to restrict weapons by rank but cannot unrestrict. I do not believe I am missing a setting somewhere. It seems it is uploaded to a mysql database. Is there a fix for this?

**Comment by xXthatNAVYguyXx** [comment]
I did try using the restrict button as a toggle

**Comment by FPtje** [comment]
What setting in what menu?

**Comment by xXthatNAVYguyXx** [comment]
the server settings menu in fadmin

**Comment by xXthatNAVYguyXx** [comment]
and it is the restrict weapons setting there

**Comment by xXthatNAVYguyXx** [comment]
Is there any other information you would like me to provide for you? There are no errors, there just simply doesn't appear to be a way to toggle weapon restrictions on a given rank
