### ISSUE TITLE
Friend can't open doors or pick up money.

### ISSUE THREAD

**Issue by austin1346** [FPtje/DarkRP#1812]
My friend can buy, sell, add owner, lock, and unlock doors. His E key is in fact bound to the use key, He also can't pick up Dark RP money. I haven't done anything with the money models or the door system module. Everyone else can use their E key properly. On a side note, he can pick up guns that are on the ground, but the guns have nothing to do with the doors, it's just proof that his E key has no problems with it. If anyone has any ideas please let me know, thanks. Or if you need more info, please ask.

**Comment by HDG-MrDeeJay** [comment]
Not a help forum.

http://forum.darkrp.com/
