### ISSUE TITLE
sv.db Mysql lite Error?

### ISSUE THREAD

**Issue by SgtVal** [FPtje/DarkRP#1815]
Lua Error: [ERROR] gamemodes/methrp/gamemode/libraries/mysqlite/mysqlite.lua:128: attempt to index local 'query' (a nil value) 1. query - gamemodes/methrp/gamemode/libraries/mysqlite/mysqlite.lua:128 2. SetUserGroup - gamemodes/methrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:87 3. fn - lua/includes/extensions/player_auth.lua:90 4. unknown - addons/ulib/lua/ulib/shared/hook.lua:184 5. oldUID - [C]:-1 6. UniqueID - gamemodes/methrp/gamemode/modules/workarounds/sh_workarounds.lua:175 7. echoToAdmins - addons/ulx/lua/ulx/log.lua:164 8. fn - addons/ulx/lua/ulx/log.lua:203 9. unknown - addons/ulib/lua/ulib/shared/hook.lua:184

15:38:07 Lua Error: [ERROR] gamemodes/methrp/gamemode/libraries/mysqlite/mysqlite.lua:166: attempt to index local 'query' (a nil value) 1. queryValue - gamemodes/methrp/gamemode/libraries/mysqlite/mysqlite.lua:166 2. fn - gamemodes/methrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:212 3. unknown - addons/ulib/lua/ulib/shared/hook.lua:184
15:38:07 Lua Error: [ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value 1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23 2. unknown - addons/ulib/lua/ulib/shared/hook.lua:184

When this happen every becomes those black block guys and server is pretty much unplayable any idea why this is happening?

**Comment by FPtje** [comment]
`gamemodes/methrp`

all support dropped.
