### ISSUE TITLE
Elite F4 How To Add Job Levels

### ISSUE THREAD

**Issue by BasonTaylor** [FPtje/DarkRP#1817]
Well I Keep Getting people come up to me asking what Level is all The Jobs Is There A way to make it say Some were the levels?
http://gyazo.com/696f52fc423eebbb1381f7129c4b168b

**Comment by FPtje** [comment]
Not a help forum. Especially not for other mods.

**Comment by BasonTaylor** [comment]
oh im sorry did not notic e
