### ISSUE TITLE
Gmod Update

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1818]
Not much of an issue but thought you might like to know:

"Removed addons.txt and gamemodes.txt as they were not used" @ http://www.garrysmod.com/updates/

**Comment by Partixel** [comment]
This would also make @15cbef69e0fb0bfd4278a6b5cd2f92096c96d26b useless

**Comment by Partixel** [comment]
I misread that didn't I? >.< ( Refers to the gmod gamemodes.txt and addons.txt )

**Comment by FPtje** [comment]
yes
