### ISSUE TITLE
Model issue - Shipments

### ISSUE THREAD

**Issue by Apache-64** [FPtje/DarkRP#1819]
Hello there, I've just updated to the DarkRP 2.6.0 and the M9K Shipments are having a model error. I overchecked it over 900 times and there is no error to be seen, But i still get an error in the console.

 [ERROR] A runtime error has occurred in "[C]" on line -1. The best help I can give you is this: Corrupt shipment: SPAS 12! The model of the shipment must be a valid model. Hints: - This error could happens when the model does not exist on the server. - Are you sure the model path is right? - Is the model from an addon that is not properly installed? The responsibility for this error lies with (the authors of) one (or more) of these files: 1. [C] on line -1 2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 412 3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80 4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 119 5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 127 6. addons/ulib/lua/ulib/shared/hook.lua on line 184 ------- End of Simplerr error ------- 1. error - [C]:-1

**Comment by Apache-64** [comment]
/*---------------------------------------------------------------------------
DarkRP custom shipments and guns
---------------------------------------------------------------------------

This file contains your custom shipments and guns.
This file should also contain shipments and guns from DarkRP that you edited.

Note: If you want to edit a default DarkRP shipment, first disable it in darkrp_config/disabled_defaults.lua
	Once youve done that, copy and paste the shipment to this file and edit it.



--DarkRP.createShipment("AK47 Shipment", {
  --  model = "models/weapons/w_ak47_m9k.mdl",
   -- entity = "m9k_ak74",
    --price = 3500,
    --amount = 10,
    --seperate = false,
    --pricesep = 1500,
    --noship = false,
    --allowed = {TEAM_GUN}
--})




The default shipments and guns can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/addentities.lua

For examples and explanation please visit this wiki page:
http://wiki.darkrp.com/index.php/DarkRP:CustomShipmentFields


Add shipments and guns under the following line:
---------------------------------------------------------------------------*/
DarkRP.createShipment("Colt Python", {
    model = "models/weapons/w_colt_python.mdl",
    entity = "m9k_coltpython",
    price = 7000,
    amount = 10,
    separate = true,
    pricesep = 750,
    noship = false,
    allowed = {TEAM_GUN}
})

    DarkRP.createShipment("Desert Eagle", {
        model = "models/weapons/w_tcom_deagle.mdl",
        entity = "m9k_deagle",
        price = 3500,
        amount = 10,
        separate = true,
        pricesep = 400,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Glock 18", {
        model = "models/weapons/w_dmg_glock.mdl",
        entity = "m9k_glock",
        price = 3500,
        amount = 10,
        separate = true,
        pricesep = 400,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("HK45C", {
        model = "models/weapons/w_hk45c.mdl",
        entity = "m9k_hk45",
        price = 2500,
        amount = 10,
        separate = true,
        pricesep = 300,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("P08 Luger", {
        model = "models/weapons/w_luger_p08.mdl",
        entity = "m9k_luger",
        price = 2500,
        amount = 10,
        separate = true,
        pricesep = 300,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("S&W Model 500", {
        model = "models/weapons/w_sw_model_500.mdl",
        entity = "m9k_model500",
        price = 7000,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("S&W Model 627", {
        model = "models/weapons/w_sw_model_627.mdl",
        entity = "m9k_model627",
        price = 7000,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("SIG Sauer P229R", {
        model = "models/weapons/w_sig_229r.mdl",
        entity = "m9k_sig_p229r",
        price = 1500,
        amount = 10,
        separate = true,
        pricesep = 0,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Bizon PP19", { -- M9K Submachine Guns
        model = "models/weapons/w_pp19_bizon.mdl",
        entity = "m9k_bizonp19",
        price = 5500,
        amount = 10,
        separate = true,
        pricesep = 600,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("AAC Honey Badger", {
        model = "models/weapons/w_aac_honeybadger.mdl",
        entity = "m9k_honeybadger",
        price = 10000,
        amount = 10,
        separate = true,
        pricesep = 1200,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("KAC PDW", {
        model = "models/weapons/w_kac_pdw.mdl",
        entity = "m9k_kac_pdw",
        price = 7000,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Magpul PDR", {
        model = "models/weapons/w_magpul_pdr.mdl",
        entity = "m9k_magpulpdr",
        price = 12500,
        amount = 10,
        separate = true,
        pricesep = 1350,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("HK MP5", {
        model = "models/weapons/w_hk_mp5.mdl",
        entity = "m9k_mp5",
        price = 5000,
        amount = 10,
        separate = true,
        pricesep = 550,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("MP5SD", {
        model = "models/weapons/w_hk_mp5sd.mdl",
        entity = "m9k_mp5sd",
        price = 5000,
        amount = 10,
        separate = true,
        pricesep = 600,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("HK MP7", {
        model = "models/weapons/w_mp7_silenced.mdl",
        entity = "m9k_mp7",
        price = 5500,
        amount = 10,
        separate = true,
        pricesep = 600,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("MP9", {
        model = "models/weapons/w_brugger_thomet_mp9.mdl",
        entity = "m9k_mp9",
        price = 4500,
        amount = 10,
        separate = true,
        pricesep = 500,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("KRISS Vector", {
        model = "models/weapons/w_kriss_vector.mdl",
        entity = "m9k_vector",
        price = 12000,
        amount = 10,
        separate = true,
        pricesep = 1250,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("ACR", { -- M9K Assault Rifles
        model = "models/weapons/w_masada_acr.mdl",
        entity = "m9k_acr",
        price = 20000,
        amount = 10,
        separate = true,
        pricesep = 2200,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("AK-47", {
        model = "models/weapons/w_ak47_m9k.mdl",
        entity = "m9k_ak47",
        price = 6500,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("AK-74", {
        model = "models/weapons/w_tct_ak47.mdl",
        entity = "m9k_ak74",
        price = 6500,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("AMD 65", {
        model = "models/weapons/w_amd_65.mdl",
        entity = "m9k_amd65",
        price = 7000,
        amount = 10,
        separate = true,
        pricesep = 800,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("AN-94", {
        model = "models/weapons/w_rif_an_94.mdl",
        entity = "m9k_an94",
        price = 25000,
        amount = 10,
        separate = true,
        pricesep = 2700,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Steyr AUG A3", {
        model = "models/weapons/w_auga3.mdl",
        entity = "m9k_auga3",
        price = 7000,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("F2000", {
        model = "models/weapons/w_fn_f2000.mdl",
        entity = "m9k_f2000",
        price = 12000,
        amount = 10,
        separate = true,
        pricesep = 1250,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("FN FAL", {
        model = "models/weapons/w_fn_fal.mdl",
        entity = "m9k_fal",
        price = 6500,
        amount = 10,
        separate = true,
        pricesep = 700,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("FAMAS", {
        model = "models/weapons/w_tct_famas.mdl",
        entity = "m9k_famas",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 900,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("HK G3A3", {
        model = "models/weapons/w_hk_g3.mdl",
        entity = "m9k_g3a3",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("G36", {
        model = "models/weapons/w_hk_g36c.mdl",
        entity = "m9k_g36",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("L85", {
        model = "models/weapons/w_l85a2.mdl",
        entity = "m9k_l85",
        price = 6500,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("M4A1 Iron", {
        model = "models/weapons/w_m4a1_iron.mdl",
        entity = "m9k_m4a1",
        price = 6500,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("M14", {
        model = "models/weapons/w_snip_m14sp.mdl",
        entity = "m9k_m14sp",
        price = 10000,
        amount = 10,
        separate = true,
        pricesep = 1100,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("M16A4 ACOG", {
        model = "models/weapons/w_dmg_m16ag.mdl",
        entity = "m9k_m16a4_acog",
        price = 6500,
        amount = 10,
        separate = true,
        pricesep = 750,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("HK 416", {
        model = "models/weapons/w_hk_416.mdl",
        entity = "m9k_m416",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("SCAR", {
        model = "models/weapons/w_fn_scar_h.mdl",
        entity = "m9k_scar",
        price = 8500,
        amount = 10,
        separate = true,
        pricesep = 950,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("TAR-21", {
        model = "models/weapons/w_imi_tar21.mdl",
        entity = "m9k_tar21",
        price = 8000,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("AS VAL", {
        model = "models/weapons/w_dmg_vally.mdl",
        entity = "m9k_val",
        price = 15000,
        amount = 10,
        separate = true,
        pricesep = 1550,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("SR-3M Vikhr", {
        model = "models/weapons/w_dmg_vikhr.mdl",
        entity = "m9k_vikhr",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_GUN}
    })

     DarkRP.createShipment("Double Barrel Shotgun", {
        model = "models/weapons/w_double_barrel_shotgun.mdl",
        entity = "m9k_dbarrel",
        price = 25000,
        amount = 10,
        separate = true,
        pricesep = 2600,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Ithaca M37", {
        model = "models/weapons/w_ithaca_m37.mdl",
        entity = "m9k_ithacam37",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 800,
        noship = false,
        allowed = {TEAM_BLACK}
    })
 
    DarkRP.createShipment("Benelli M3", {
        model = "models/weapons/w_benelli_m3.mdl",
        entity = "m9k_m3",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 800,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("Mossberg 590", {
        model = "models/weapons/w_mossberg_590.mdl",
        entity = "m9k_mossberg590",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 800,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("Remington 870", {
        model = "models/weapons/w_remington_870_tact.mdl",
        entity = "m9k_remington870",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 800,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("SPAS 12", {
        model = "models/weapons/w_spas_12.mdl",
        entity = "m9k_spas12",
        price = 20000,
        amount = 10,
        separate = true,
        pricesep = 2500,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Striker 12", {
        model = "models/weapons/w_striker_12g.mdl",
        entity = "m9k_striker12",
        price = 7500,
        amount = 10,
        separate = true,
        pricesep = 850,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("USAS", {
        model = "models/weapons/w_usas_12.mdl",
        entity = "m9k_usas",
        price = 25000,
        amount = 10,
        separate = true,
        pricesep = 2700,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("AI AW50", { -- M9K Sniper Rifles
        model = "models/weapons/w_acc_int_aw50.mdl",
        entity = "m9k_aw50",
        price = 25000,
        amount = 10,
        separate = true,
        pricesep = 2700,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("Barret M82", {
        model = "models/weapons/w_barret_m82.mdl",
        entity = "m9k_barret_m82",
        price = 24000,
        amount = 10,
        separate = true,
        pricesep = 2500,
        noship = false,
        allowed = {TEAM_GUN}
    })

    DarkRP.createShipment("Intervention", {
        model = "models/weapons/w_snip_int.mdl",
        entity = "m9k_intervention",
        price = 15000,
        amount = 10,
        separate = true,
        pricesep = 1600,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("M24", {
        model = "models/weapons/w_snip_m24_6.mdl",
        entity = "m9k_m24",
        price = 22000,
        amount = 10,
        separate = true,
        pricesep = 2400,
        noship = false,
        allowed = {TEAM_BLACK}
    })

    DarkRP.createShipment("PSG-1", {
        model = "models/weapons/w_hk_psg1.mdl",
        entity = "m9k_psg1",
        price = 11000,
        amount = 10,
        separate = true,
        pricesep = 1200,
        noship = false,
        allowed = {TEAM_BLACK}
    })
    
    DarkRP.createShipment("HK SL8", {
        model = "models/weapons/w_hk_sl8.mdl",
        entity = "m9k_sl8",
        price = 17000,
        amount = 10,
        separate = true,
        pricesep = 1800,
        noship = false,
        allowed = {TEAM_BLACK}
	})

    DarkRP.createShipment("Dragunov SVU", {
        model = "models/weapons/w_dragunov_svu.mdl",
        entity = "m9k_svu",
        price = 26500,
        amount = 10,
        separate = true,
        pricesep = 4500,
        noship = false,
        allowed = {TEAM_GUN}
    })

That's my shipment code...

**Comment by FPtje** [comment]
Not a help forum
Not the latest  version of DarkRP.
