### ISSUE TITLE
DarkRP F4 HUD

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/DarkRP#1821]
ehm f4 is f#@$# up .. and more shizzle things, what shall we do. 

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:242: table index is nil
1. removeCustomEntity - gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:242
2. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:232

**Comment by FPtje** [comment]
No it's not.

**Comment by NLGBrian** [comment]
how to fix F4 menu?

**Comment by HDG-MrDeeJay** [comment]
by asking for help at the help forums.

Pro tip: You are not currently at the help forums.

Extra pro tip: There is a link somewhere to the help forums. Find it 
yourself.
