### ISSUE TITLE
DarkRP Regular F4 Menu, giving errors.

### ISSUE THREAD

**Issue by ImDesire** [FPtje/DarkRP#1822]
I'm using a fresh install of DarkRP 2.6, whenever I open the F4 menu, I get these 2 errors.

[ERROR] gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:154: bad argument #1 to 'SetText' (string expected, got nil)
  1. SetText - [C]:-1
   2. setDarkRPItem - gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:154
    3. generateButtons - gamemodes/darkrp/gamemode/modules/f4menu/cl_entitiestab.lua:245
     4. Init - gamemodes/darkrp/gamemode/modules/f4menu/cl_entitiestab.lua:8
      5. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
       6. F4MenuTabs - gamemodes/darkrp/gamemode/modules/f4menu/cl_init.lua:73
        7. generateTabs - gamemodes/darkrp/gamemode/modules/f4menu/cl_frame.lua:176
         8. openF4Menu - gamemodes/darkrp/gamemode/modules/f4menu/cl_init.lua:12
          9. Call - gamemodes/darkrp/gamemode/modules/f4menu/cl_init.lua:24
           10. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:46

and this

[ERROR] gamemodes/darkrp/gamemode/modules/f4menu/cl_entitiestab.lua:265: attempt to call field 'PerformLayout' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/f4menu/cl_entitiestab.lua:265

Any ideas what it could be ;o?

**Comment by Kefta** [comment]
Do you have any custom items or entities?

**Comment by FPtje** [comment]
Error not possible in the latest DarkRP because custom entities are checked for validity.
