### ISSUE TITLE
Disabling only the scoreboard

### ISSUE THREAD

**Issue by roastt** [FPtje/DarkRP#1824]
I have my own scoreboard I would like to use and I want it so no one can see Fadmin scoreboard, but I still want FAdmin. 

FAdmin_OverrideScoreboard doesn't seem to work.

**Comment by deinemudda32** [comment]
Disable it via DarkRPmodifcation.
https://github.com/FPtje/darkrpmodification
Also not a helpforum. FPtje said that multiple times, so just close this.

**Comment by FPtje** [comment]
not a help forum.

**Comment by roastt** [comment]
No thats disabling FADMIN though, you loose the groups that method. And Falco the issue is FAdmin_OverrideScoreboard does nothing!

**Comment by Steffion** [comment]
Try changing the ConVar 'FAdmin_IsScoreboard' to 0.

**Comment by roastt** [comment]
In the update that command is no longer valid, I used to have a script that made that command run if it was < 0. But now its been taken out :(
