### ISSUE TITLE
Infinte ammo bug

### ISSUE THREAD

**Issue by roastt** [FPtje/DarkRP#1825]
[ERROR] gamemodes/darkrp/entities/entities/spawned_weapon/init.lua:30: attempt to perform arithmetic on local 'amount' (a nil value)
1. DecreaseAmount - gamemodes/darkrp/entities/entities/spawned_weapon/init.lua:30
2. unknown - gamemodes/darkrp/entities/entities/spawned_weapon/init.lua:82

When you drop a gun on the floor it says "nil" on and you can pick up unlimited amount.

**Comment by FPtje** [comment]
user error

**Comment by roastt** [comment]
But I haven't changed core files?

**Comment by FPtje** [comment]
The error is impossible.

**Comment by roastt** [comment]
Ok I have installed a brand new DarkRP and haven't touched anything, apart from removing default entities and jobs. And the same bug occurs, it may not be your problem but if you could kick me in the right direction that would be great.

**Comment by FPtje** [comment]
which weapons?

2015-03-14 14:44 GMT+01:00 roastt <notifications@github.com>:

**Comment by roastt** [comment]
All weapons glitch, I am using M9K weapons. And if you're asking about the guns I remove, I remove all jobs apart from Citizen and ALL entities and ammo (since I have my own in DarkRP mod)

**Comment by FPtje** [comment]
Does it happen with weapons dropped from shipments or only for weapons
dropped by players?


2015-03-14 14:48 GMT+01:00 roastt <notifications@github.com>:

**Comment by roastt** [comment]
Both, there are no errors now but the gun still has "nil" on it.

**Comment by roastt** [comment]
Shipments spawn bugged and then when you destroy the box they look like this:

http://gyazo.com/ac7c5c1c30a8dfe2c6e9dc57a0f69063
http://gyazo.com/4852e193c65e5538e04dff71263a663e

Ive been running DarkRP for 2 years now, never seen this.

**Comment by FPtje** [comment]
I don't have this issue.

2015-03-14 14:50 GMT+01:00 roastt <notifications@github.com>:

**Comment by roastt** [comment]
Ok then it must be an addon I will check all and report back to you; just in case other people report this error to you.
