### ISSUE TITLE
Errors in doorsystem

### ISSUE THREAD

**Issue by KLNorthdegree** [FPtje/DarkRP#1827]
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:65: attempt to perform arithmetic on field 'OwnedNumz' (a nil value)
  1. keysOwn - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:65
   2. callback - gamemodes/darkrp/gamemode/modules/base/sv_purchasing.lua:310
    3. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:156
     4. unknown - lua/includes/modules/concommand.lua:54

Just spawned a TDMcar which I have added in the vehicles.lua using the darkrpmodification-addon.

**Comment by KLNorthdegree** [comment]
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:68: attempt to index field 'Ownedz' (a nil value)
  1. keysOwn - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:68
   2. unknown - addons/derpinv/lua/autorun/server/drpinv.lua:1200
    3. unknown - lua/includes/modules/concommand.lua:54

**Comment by FPtje** [comment]
I really think you have an addon that's conflicting with DarkRP.

Run this in the **SERVER RCON** console:
```
lua_run print([[hooks]]) for k,v in pairs(hook.GetTable().PlayerInitialSpawn) do print([[initialSpawn]], k, v(player.GetAll()[1])) end
```

It should print something, tell me what it prints.

**Comment by KLNorthdegree** [comment]
Well, thanks for this useful command. :)

Now i just figured out a error in my own Plugin. I'll fix it and then test it again.

**Comment by FPtje** [comment]
It's probably more useful to me than to you. It doesn't change anything on
your server. It just prints info.

**Comment by KLNorthdegree** [comment]
Well, it is useful for me too, as I never realized that the server complained about a mistake in my addon. It seems to be fixed now.
