### ISSUE TITLE
Locked Variable on Vehicles

### ISSUE THREAD

**Issue by KLNorthdegree** [FPtje/DarkRP#1830]
I dont know if it is really a bug or just a addon overwriting it, but if i Lock/Unlock a Door the "locked" variable is setting normally to false/true.

But if i lock a vehicle the Variable "locked" remains false.

Before Locking:
```
DoorData:
		owner	=	2
FPPCanTouch	=	31
FPPCanTouchWhy	=	70676
FPPOwner	=	Player [1][KL | Kartoffel_Kater]
Locked	=	false
PickLevel	=	1
VC_LastRenderedL:
VC_LhtSzOffset_D	=	1
VC_Lht_CarBrght	=	0.48078684012095
VC_Lht_ChkT	=	328.06942749023
VC_Lht_DstCheck	=	69.871397452833
VC_Lht_DstCheckMult	=	1
VC_Lht_DstCheck_B	=	true
VC_Model	=	models/tdmcars/bug_eb110.mdl
```

After Locking:
```
DoorData:
		owner	=	2
FPPCanTouch	=	31
FPPCanTouchWhy	=	70676
FPPOwner	=	Player [1][KL | Kartoffel_Kater]
Locked	=	false
PickLevel	=	1
VC_LastRenderedL:
VC_LhtSzOffset_D	=	1
VC_Lht_CarBrght	=	0.48078684012095
VC_Lht_ChkT	=	329.58050537109
VC_Lht_DstCheck	=	69.871397452833
VC_Lht_DstCheckMult	=	1
VC_Lht_DstCheck_B	=	true
VC_Model	=	models/tdmcars/bug_eb110.mdl
```

However, the Vehicle is locked.

**Comment by Bo98** [comment]
Is the Locked variable even from DarkRP?

There's ent:isLocked() for checking if an entity is locked.

**Comment by KLNorthdegree** [comment]
This went to the wrong tab. Sorry.

Anyway, is there a way to check if a door is locked clientside?

**Comment by Bo98** [comment]
You'll have to network it unfortunately. DarkRP takes it from the entity's save table which only has the locked field serverside.
