### ISSUE TITLE
zombie invasion

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1833]
I would suggest to remove zombies if the zombies are gone.
Or a timer.

**Comment by stapler2025** [comment]
Do it yourself?

**Comment by deinemudda32** [comment]
Its a suggestion, not only for myself.
Either I don't like to modify DarkRP via DarkRPModification too much.
As when Updates are coming out, I should update my modified files too to fix things up.

**Comment by HDG-MrDeeJay** [comment]
There are literally hundreds of keypad packs out there. Simply download 
one from the workshop.

I couldn't type DIY large enough if i tried.

**Comment by deinemudda32** [comment]
Yea I have one already, but I meant DarkRP could include one themself.
Even this is the wrong issue.

**Comment by HDG-MrDeeJay** [comment]
I don't think falco will do this. It's a new feature that imo darkrp 
could particularly go without.

That and money printers.

**Comment by Bo98** [comment]
Keypad issue is #1834, not this one.

**Comment by FPtje** [comment]
Zombies gone means zombies stopped coming. It can be very unsatisfactory when you're shooting them and they suddenly disappear in front of your eyes.

**Comment by deinemudda32** [comment]
I know what it means, but some zombies like stucking in walls or spawning on wrong points.

**Comment by FPtje** [comment]
Why not solve that problem instead?

**Comment by deinemudda32** [comment]
It costs more work and effort as just setting up a timer.

**Comment by HDG-MrDeeJay** [comment]
Then here is an easy solution that has worked for countless servers 
across the eons.

Give players guns, and say go zombie hunting.

Players are crafty: they will find a way to kill a zombie thats hard to 
kill.

**Comment by deinemudda32** [comment]
Oh before I forget it, the antlions attack the zombies, so they are useless.

**Comment by HDG-MrDeeJay** [comment]
It takes like 5 seconds to find npc_antlion in the code, highlight it, 
and press backspace.

CTRL+F is your friend.

**Comment by deinemudda32** [comment]
I don't edit core files unless its really important.
Even not in darkrpmodification

**Comment by FPtje** [comment]
How about I solve those two issues

**Comment by stapler2025** [comment]
Darkrpmod isn't a fucking core file you twat.. You're SUPPOSED to edit shit
there for that exact reason.

**Comment by HDG-MrDeeJay** [comment]
Don't bother... he doesn't understand a shit of what he needs to do, he 
wants changes to shit that he should probably do himself, given that 
they are only going to benefit a small number of servers in comparison 
to the thousands of others that don't even use Zombies.

IMO zombies should've disappeared somewhere between 2.4.3 and 2.5.1

**Comment by HDG-MrDeeJay** [comment]
and also...

>I don't edit core files unless its really important.
>Even not in darkrpmodification 

This is where I step out through that door with a revolver shoved into my mouth.

**Comment by FPtje** [comment]
Nevertheless, zombies shouldn't be attacking one another. You should be
able to add combine NPCs too without them attacking the zombies.

**Comment by deinemudda32** [comment]
Really, guys?
You think Im too stupid to delete one word?
I don't just want this for me.
And yeah, I think too zombies are useless, but I try to use every function DarkRP comes with.
Even zombies, cause some "Custom fake scriptfodder/coderhire" servers arent better than that actually.
You cant say I'm lazy without really knowing, I'm not lazy for 100%.
I don't report 80% of the things I don't like in DarkRP, because always some folks appear and say "Youre too stupid to do it youreself, aint you?".
But this is important enough for me to report it.
I wish I could speak perfectly english, then I would answer with a standard facepunch sentence, but sorry.
Just please stop flaming about me being lazy.

**Comment by HDG-MrDeeJay** [comment]
Never said you were lazy. I just said you were ignorant.

But seriously, the darkrp modification addon is there for you to modify. 
Don't hesitate to change shit in it.

As for the npc relations, I thought that was intentional, i swear the 
file assigned relations to the npc's that spawned....

**Comment by deinemudda32** [comment]
When DarkRP gets an update every day, I cant modify very much. :/

**Comment by FPtje** [comment]
My task for DarkRP is to maintain it. That includes fixing bugs that exist
in the code. Zombies attacking one another is a bug. Zombies spawning in
walls is a bug. Bugs should be fixed. Also, grass is usually green.

**Comment by FPtje** [comment]
Also, you can always edit darkrpmod, even if DarkRP updates every 10 minutes.

**Comment by HDG-MrDeeJay** [comment]
>Also, grass is usually green.

It's blue on Planet Namek
![http://i.ytimg.com/vi/qd9fyQfzzxk/maxresdefault.jpg](http://i.ytimg.com/vi/qd9fyQfzzxk/maxresdefault.jpg)

**Comment by deinemudda32** [comment]
FPtje I didnt mean I cannot, I meant I will have to update the modified files and I don't have time to do that every day..

**Comment by stapler2025** [comment]
Darkrpmod rarely changes..

**Comment by Bo98** [comment]
It shouldn't be required to use DarkRPModification to fix bugs though.

**Comment by deinemudda32** [comment]
Thank you!

**Comment by FPtje** [comment]
Guys, there isn't even a config option to set the zombie NPCs. You were yelling at this guy for literally no reason

**Comment by HDG-MrDeeJay** [comment]
i know there isnt. You have to do it manually.

**Comment by FPtje** [comment]
I'm removing it. Reasons:
- Shit code: inefficient, shit interface and hard to maintain
- Not customisable, and a lot of work to make it customisable. You can't even have it on by default
- Very few people use it
- Other people probably want to make a zombie mod that's much better and can do a lot more

Download darkrpmod version here:

http://www.solidfiles.com/d/58925261e9/zombies.zip

**Comment by HDG-MrDeeJay** [comment]
Two words...

Called it.

**Comment by FPtje** [comment]
Two more words: anal cavity

You didn't call it, you voiced your original opinion.

**Comment by stapler2025** [comment]
RIP zombies, 2015
