### ISSUE TITLE
Keypad + Cracker [Suggestion]

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1834]
Probably add a keypad and cracker to DarkRP default as ther is a Keypadchecker so manually add the Keypad via Workshop is pretty sucking.

**Comment by FPtje** [comment]
Lock pick

**Comment by deinemudda32** [comment]
I dont think that Lock Picks are Keypads or can crack Keypads :P

**Comment by FPtje** [comment]
They can open fading doors directly. I'm not adding third parties addons to DarkRP by default.

**Comment by deinemudda32** [comment]
Hm okay. Well it was worth a try.
