### ISSUE TITLE
weapon license

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1836]
I would suggest to add a option for the license, so players don't loose it on jobchange or death.

**Comment by HDG-MrDeeJay** [comment]
thats stupid. Breaks RP.

**Comment by deinemudda32** [comment]
Some servers want more than "stupid" RP.
Some users doesnt want to buy a weapon license every 10 minutes.

**Comment by HDG-MrDeeJay** [comment]
Its not stupid RP.

After death, you are a new you. You have no recollection of your 
previous life. Therefor the mayors office would choose to revoke your 
license.

After a job change, your circumstances change, and you would need to be 
re-evaluated for a license.

It's not DarkRP's fault your staff don't moderate the prices for gun 
licenses.

**Comment by deinemudda32** [comment]
It costs $1000.
Easy cash, but the mayor doesnt want to give out every 10 minutes 64 gunlicenses on a 64 slot server.
Therefore no one uses them.
If you die and lost everything, Why keep youre money, name, props, base, entities?

**Comment by HDG-MrDeeJay** [comment]
Good point.

Falco, make an update please that removes all money, resets your name, 
deletes all your props, unowns all your doors, and removes all your 
entities immediately after death. This way server's can enforce NLR 
easier because its hard to moderate a server and tell people what they 
can and cannot do.

**Comment by HDG-MrDeeJay** [comment]
Also $1000 is a ridiculous price for a gun license.

Application fees for a firearms license in NSW Australia costs around 
$65. $1000 is a far cry from that, unless of course your in-game economy 
is fucked and everybody walks around with 20 million dollars in their 
pockets.

**Comment by deinemudda32** [comment]
Something have to stay to not let the children "ragequit".

I just want to bring back the roleplay on my server.
by the way on disconnect of course it should disguise.

**Comment by HDG-MrDeeJay** [comment]
Now you aren't making any sense.

You want RP, yet you want people to keep their gun license permanently.

*One of these things is not like the other, one of these things just doesn't belong...*

**Comment by deinemudda32** [comment]
Not permamently as I said, it should disguise on disconnect.

I want to actually roleplay but not the standard way.
I want a additional way, permanent cars, permanent weapons and of course permanent money.
So users have to work for something and doesnt loose everything on death.
A option for this is required if the function should be used, im sure alot would use it.

**Comment by FPtje** [comment]
DarkRP does not inherently enforce or even condone NLR. In fact I hate NLR
with a passion. This seems like a reasonable idea, but if people don't lose
their licenses when changing job or dying, when will they? Are you sure you
want it to be a "join, buy once and keep for the rest of the playtime"
thing or should there be a different mechanism for losing licenses? Maybe
mayors should be able to revoke licenses.

**Comment by deinemudda32** [comment]
I like the idea of FTtje.
On Arresting licenses could be revoked.

**Comment by FPtje** [comment]
On arrest? Good idea, I'll have to look to see if that doesn't already
happen though.

**Comment by FPtje** [comment]
On arrest is already done. Players already don't lose their license on death. A config option was added to have the license revoked on job change. It's on by default.

**Comment by deinemudda32** [comment]
Thank you :).

**Comment by HDG-MrDeeJay** [comment]
roleplay is dead -_- ill send the memo to second life dedvelopers

**Comment by deinemudda32** [comment]
you spoke that wrong.
right is "roleplay is born"

**Comment by HDG-MrDeeJay** [comment]
nope, pretty sure i spelt dead correctly.

**Comment by FPtje** [comment]
Stop whining, you massive cunt. I added a god damn config option so that makes it so people don't lose their licenses on job change. By default the behaviour is exactly the same as before. Deal with it.
