### ISSUE TITLE
Hitman issues

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1838]
I would suggest to remove the function to give hits on youreself and get hits from other persons which can accept hits or make a option for that.

I tried around with the canRequestHit hook and it can't target "target" its Invalid in all cases as I could seen.

**Comment by HDG-MrDeeJay** [comment]
The hook works fine for me. You must be using it wrong. I can limit CPs 
and hitmen from placing hits, i can limit a customer from placing a hit 
on themselves... i can do all sorts of things.

**Comment by deinemudda32** [comment]
I get an error, that "target" is nil.
Even the hook seems to be calling twice.
On pressing E on a hitman and on requesting a hit, as I get an error if someone opens the gui of the hitman, but if someone requests a hit, I get none and it works the way I wanted it.

Nvm then, lets concentrate about the suggestion I made beside the report :)
I can ask in the forums either about the hooks.

**Comment by FPtje** [comment]
```
if hitman == customer then return false, DarkRP.getPhrase("hitman_no_self_order") end
```
