### ISSUE TITLE
FAdmin scoreboard

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1840]
The FAdmin scoreboard seems to have some problems.
I experienced alot of stuff with it, so far.

- If my server laggs (or my computer, I dont know exactly) and I open the scoreboard multiple times It can get stucked and you only see the player columns, till you again press TAB to open the scoreboard

- If you click on a player column, you can see the profile pic which is often not displayed perfectly.
alot of the profile pics you can only see 25% of the pic itself.

- I suddenly had a issue where I opened a player column, closed it and the profile picture staid on my screen till I disconnected

Thats all I experienced. I hope it can be fixed.

**Comment by FPtje** [comment]
The middle issue's been fixed, but I can't reproduce the other ones. Check for errors.

**Comment by HDG-MrDeeJay** [comment]
The last issue may be a recurring issue from as way back as 2.4.3 and before, do you mean when you see their entire info like when you click their name? If so, then you may be describing the same bug I experienced from server to server back then.

**Comment by deinemudda32** [comment]
With player column I mean the profile information, yea if you click on a name.

**Comment by HDG-MrDeeJay** [comment]
Then yeah, thats been an issue since forever, i guess people just didn't 
pay enough attention to it (or never knew how to get into that section 
of the scoreboard, you'd be surprised how many idiots play gmod)

**Comment by FPtje** [comment]
So you click on a name, open the profile info page and the avatar stays?
Are you sure that's not from the time when the avatar image was a html
element?

**Comment by deinemudda32** [comment]
The issue last appears ago 2 weeks.

**Comment by FPtje** [comment]
Well I changed it a bit. Try now.

**Comment by HDG-MrDeeJay** [comment]
Nah the avatar would be offset and surrounded by missing textures.

I wouldn't be surprised if it was back when it was a HTML element. Back 
then I didn't know my arrays from my strings.

**Comment by FPtje** [comment]
It was an html element because there was a bug with the normal avatar
image.

**Comment by deinemudda32** [comment]
Btw the bug that you spawn with invisible physics gun and if you change to grav gun that the game crashs, is this a DarkRP Bug?

**Comment by Bo98** [comment]
GMod bug.

**Comment by deinemudda32** [comment]
Are they planning a fix for the crashs and servercrashs?
I dont know actually, I wrote severall issues.

**Comment by Bo98** [comment]
Yes though I don't know an ETA.
