### ISSUE TITLE
Couldn't Load Init Script: 'darkrp/gamemode/cl_init.lua

### ISSUE THREAD

**Issue by tray5050** [FPtje/DarkRP#1842]
I get this error when i start my server (only addon is darkrpmodifcation)

[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:998: invalid order function for sorting
1. sort - [C]:-1
2. mergeCategories - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:998
3. fn - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:1008
4. Run - addons/ulib/lua/ulib/shared/hook.lua:179
5. fn - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:142
6. Run - addons/ulib/lua/ulib/shared/hook.lua:179
7. unknown - gamemodes/darkrp/gamemode/init.lua:81

Couldn't Load Init Script: 'darkrp/gamemode/init.lua'

**Comment by FPtje** [comment]
I have no idea how you manged to get that issue, but congrats. It should be fixed.

**Comment by LucasTea** [comment]
I have the same issue.
I only get this error in consol : Couldn't Load Init Script: 'darkrp/gamemode/init.lua'
It exits since a Server restart without any changes.

**Comment by Bo98** [comment]
99% of the time this is the result of an earlier Lua error when the server is starting. If you need help, try ask https://forum.darkrp.com.

**Comment by skyisland-minecraft** [comment]
J'ai ce probléme : 
[ERROR] Couldn't Load Init Script: 'darkrp/gamemode/cl_init.lua'

et donc aucun de mes métier ne s'affiche et mon chat ne s'affiche pas
