### ISSUE TITLE
Cant add any jobs anymore on the 2.6 beta. 

### ISSUE THREAD

**Issue by AVAST4894** [FPtje/DarkRP#1843]
Jobs doesnt work anymore because darkrpmodification is reported unknown.
please upload a version of 2.5 too.

**Comment by FPtje** [comment]
What on earth do you mean by "darkrpmod reported unknown"?

**Comment by HDG-MrDeeJay** [comment]
took the words right out of my mouth

**Comment by AVAST4894** [comment]
when i start the server it says that darkrpmodification is [TYPE:!UNKNOWN]

**Comment by AVAST4894** [comment]
The thing i want to say is: It wont load anything that you add in DarkRP modification

**Comment by AVAST4894** [comment]
FPtje?

**Comment by FPtje** [comment]
Autorefresh is not supported anymore. Change level
