### ISSUE TITLE
AFK: Invincible

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1845]
Players can die if they are AFK. I would turn that off.
Like godmode the player. I really often get a issue, that I die will in AFK Mode and respawn without the balck screen but with the red text on my screen.

**Comment by HDG-MrDeeJay** [comment]
This can be easily abused, for instance binds that toggle afk when you 
are being attacked.

This is something thats best left to administrators to personally deal 
with, or delaying any god mode so you have to be afk for a while (10 
seconds) before god mode applies.

**Comment by deinemudda32** [comment]
Ok the point is that you are alive and have 4 red sentences on youre hud which says youre afk.
Thats the actual problem.

**Comment by FPtje** [comment]
I don't know which version of AFK you're running, but the official version runs `ply:KillSilent()`.

**Comment by Neosinos** [comment]
When was this change made? On 2.5.1 you were able to respawn AFK. If you
went AFK and died for some reason, when you respawned you were still in AFK
mode. So you had to use /afk again and get respawned. Also, you always took
the job slot you were in for the whole amount of AFK time.

Actually, if this is still the same, why not set the player back to the
default job; and when he gets back from AFK, you could check if the job he
was in is still available - if it is, set him. If it isn't, tell him so and
leave the default job active.

Am Dienstag, 24. März 2015 schrieb Falco Peijnenburg :

**Comment by deinemudda32** [comment]
Agree

**Comment by FPtje** [comment]
It kills and locks the player. There's no "dying" in hindsight, there's no "respawning". You die and you're frozen until you stop being AFK.
