### ISSUE TITLE
[ERROR] Lua is unable to understand file.

### ISSUE THREAD

**Issue by untrainAssassin** [FPtje/DarkRP#1848]
DarkRP.createEntity("Apple Seeds", {
	ent = "fs_apple_seeds",
	model = "models/props_lab/box01a.mdl",
	price = 100,
	max = 4,
	cmd = "buyappleseeds",
})
everything is correct but it tells me that there's a problem it's in the 
darkrpmodification-master\lua\darkrp_customthings\entities.lua

**Comment by untrainAssassin** [comment]
[ERROR] Lua is unable to understand file "darkrp_customthings/entities.lua" because its author made a mistake around line number 20.
The best help I can give you is this:

Right before the 'DarkRP', Lua expected to read an '='-sign, but it didn't.

**Comment by deinemudda32** [comment]
You are unable to understand.
delete the ","  after buyappleseeds...

**Comment by untrainAssassin** [comment]
That's really weird because I always had that code and it worked.

**Comment by untrainAssassin** [comment]
But thank you very much

**Comment by untrainAssassin** [comment]
So i did that
DarkRP.createEntity("Apple Seeds", {
	ent = "fs_apple_seeds",
	model = "models/props_lab/box01a.mdl",
	price = 100,
	max = 4,
	cmd = "buyappleseeds"
})
still get the same error I think it's a bug.

**Comment by untrainAssassin** [comment]
I've done all the main things wipe the server reinstall both of the add ons darkrp and darkrpmodification

**Comment by deinemudda32** [comment]
Does the ent exists?
Does the model exists?
where did you put this?
More information then.

**Comment by untrainAssassin** [comment]
I have this https://scriptfodder.com/scripts/view/744 I did exactly what it says on that.

**Comment by FPtje** [comment]
This is not a help forum. I'm not the author of your files.

**Comment by untrainAssassin** [comment]
when I had 2.6.0 it worked but now it doesn't

**Comment by untrainAssassin** [comment]
I honestly thought it was a bug I have everything there and my folder but it consistently says that Eerror.

**Comment by FPtje** [comment]
Syntax errors are your fault. DarkRP updates cannot cause them in other
files.
