### ISSUE TITLE
Disconnect: Entities

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1849]
If you set "ent_remove_delay" to we say 120 and a player has 10 entities(max entities of the group) disconnects and reconnects within the time.
The player has his items back working, but this time spawns another 10 ones and now owns 20.

I would suggest to get the info from the entity (the previous owner) if the owner disconnects, so if he reconnects within the time, the maximum amount of entitys gets set automatically to the actual amount.

**Comment by FPtje** [comment]
This works fine on my server with all the default things.
Reproduction attempt steps:
- Create dedicated server
- Join
- Spawn two money printers (max)
- Rejoined
- Tried to spawn another money printer
- Get "limit reached" message"
