### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1850]
I would suggest to add the weapon names + descriptions to thetranslation module, so every owner can decide their own weapon name without editing it via darkrp modification.

Removes 100% of the pain I feel if a update for entities came out :)

**Comment by FPtje** [comment]
You've got good reasons for wanting to change weapon names and descriptions, but you'd have equally good reasons to edit the instructions, contact, clip size?, model, slot or the category even.

I like your idea, but I'd much rather generalise it to more than just the name and description.

**Comment by FPtje** [comment]
![2015-03-26_21-02-17](https://cloud.githubusercontent.com/assets/1202014/6855776/70e9a5b8-d3fb-11e4-983f-f7f50ff813d9.png)

**Comment by FPtje** [comment]
Here, I put a new default module in the darkrpmod.
Check it out:
https://github.com/FPtje/darkrpmodification/tree/master/lua/darkrp_modules/weaponsettings

**Comment by deinemudda32** [comment]
Nicely done
