### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by advancedrazor** [FPtje/DarkRP#1852]
I would like a option for disable just some logging features but not all, as some are useful tho.

**Comment by FPtje** [comment]
I don't want a config hell.

**Comment by advancedrazor** [comment]
Just because you dont want it?

Many want it, and I love DarkRP also.
This feature is normally main for every gamemode that has its own admin system.

**Comment by FPtje** [comment]
The DarkRP logging system is basic and provides basic functionality. Being
able to set every logging option in the config file makes it bloated. It'll
make the config file even larger and most people wouldn't even use it.

There are specialised logging mods that can be super fancy if you want to.
Use those.

**Comment by advancedrazor** [comment]
Its not basic, its perfectly for DarkRP.
Additionally you could let the user setup the "config" in the fadmin interface.
I didnt ever read something about FAdmin in the config file also.

**Comment by FPtje** [comment]
Are you talking about FAdmin logging or DarkRP logging?

**Comment by advancedrazor** [comment]
FAdmin normally logs things like Hit accepted or spawned prop

**Comment by FPtje** [comment]
I know what my own admin mod does, I was asking whether you were talking
about FAdmin logging or DarkRP logging.

**Comment by Neosinos** [comment]
How about not making a config option? Just console commands you can
auto-load in your server.cfg

Am Donnerstag, 26. März 2015 schrieb Razor Glaze :

**Comment by FPtje** [comment]
That's even worse

**Comment by advancedrazor** [comment]
I just dont like that it logs double.
DarkRP + ULX.
It pretty spamms my console.
And DarkRP doesnt log tool uses etc. so I would like to disable some things, but no Config for that.
Even Hitaccepts etc. is logged, which are quite important for servers, to look after RDMs etc.

**Comment by Neosinos** [comment]
Then disable ULX Logging / Console Output / Echo.

Am Donnerstag, 26. März 2015 schrieb Razor Glaze :

**Comment by FPtje** [comment]
FAdmin would mostly log the same things as ulx. DarkRP logs the hits.

In conclusion I still don't know whether you're talking about FAdmin
logging or DarkRP logging.

**Comment by advancedrazor** [comment]
Then Im talking about FAdmin.

**Comment by FPtje** [comment]
You can remove FAdmin's logging hooks in a darkrpmod module.

**Comment by advancedrazor** [comment]
And why not a config for this?
would make things easier to setup etc.

**Comment by FPtje** [comment]
Because FAdmin doesn't really have config options. Also because one way to
do things is enough.

**Comment by advancedrazor** [comment]
Not for guys which wants things actually fast done.
Not looking in the internet for the hooks, blocking them in an autorun file or whatever.
An easy Config setting would make that easier, especially for serverowners, cause they doesnt have to search 20 hours for this and can begin with the work directly

**Comment by FPtje** [comment]
FAdmin has no config settings. I'd have to make a special config file
*just* for
logging. That or I'd have to make a new ui with tick boxes and all that
crap. That ui can be abused by (super)admins who would abuse off the
records and I don't want to make a config file specifically for logging.

2015-03-26 9:28 GMT+01:00 Razor Glaze <notifications@github.com>:

**Comment by advancedrazor** [comment]
If youre afraid that superadmins are abusing something.
Then disable that they can change every single setting of Falcos Prop Protection.
Or really make a config file, which would solve all the abusing problems magically.

**Comment by HDG-MrDeeJay** [comment]
How about this.

Add a hook to the logging system, that allows an addon to control what 
is logged and where its logged to. Then this becomes DIY to anyone who 
wants a bloated log system.

**Comment by FPtje** [comment]
Great idea, Nathan. Luckily, that's already there.

**Comment by HDG-MrDeeJay** [comment]
Oh that is simply wonderful.

Gives me all the more reason to completely ignore the rest of my emails 
for this issue.

**Comment by advancedrazor** [comment]
I dont think youre guys are any help in this point. so I just do it myself.

**Comment by HDG-MrDeeJay** [comment]
"Do it yourself" I think is what everyone was going for here.

**Comment by FPtje** [comment]
Yes,in the darkrpmod like I explained.
