### ISSUE TITLE
Weapon Lua Error

### ISSUE THREAD

**Issue by kevinandre98** [FPtje/DarkRP#1853]
[ERROR] gamemodes/darkrp/entities/weapons/weapon_cs_base2/shared.lua:383: attempt to call method 'SendLua' (a nil value)
  1. SetIronsights - gamemodes/darkrp/entities/weapons/weapon_cs_base2/shared.lua:383
   2. unknown - gamemodes/darkrp/entities/weapons/ls_sniper/shared.lua:89

Happens on changing to the PUMP SHOTGUN SWEP after having a different darkrp weapon

**Comment by Partixel** [comment]
Works fine for me.
