### ISSUE TITLE
sh_chatcommands:43 attempted to index a nil value

### ISSUE THREAD

**Issue by g390013** [FPtje/DarkRP#1854]
[ERROR] gamemodes/darkrp/modules/chat/sh_chatcommands.lua:43: attempted to index a nil value
1. unknown - gamemodes/darkrp/gamemode/modules/chat/sh_chatcommands.lua:43
2. finish - gamemodes/darkrp/gamemodes/libraries/interfaceloader.lua:157
3. unknown - gamemodes/darkrp/gamemode/init.lua:79

This appeared after the last update

**Comment by g390013** [comment]
Couldn't Load Init Script: 'darkrp/gamemode/init.lua'

**Comment by FPtje** [comment]
Bad install. Don't use filezilla.

**Comment by g390013** [comment]
I have this on localhost and updated with SVN.

**Comment by FPtje** [comment]
I don't.
