### ISSUE TITLE
Default HUD always visible? 

### ISSUE THREAD

**Issue by Swagrenade** [FPtje/DarkRP#1856]
For some reason the default HUD is visible over my custom HUD. I have this in my code:

local hideHUDElements = {

	["DarkRP_HUD"] = false,

	["DarkRP_EntityDisplay"] = false,

	["DarkRP_ZombieInfo"] = false,

	["DarkRP_LocalPlayerHUD"] = true,

	["DarkRP_Hungermod"] = false,

	["DarkRP_Agenda"] = false,
	
	["CHudHealth"] = true,
	
	["CHudBattery"] = true,
	
	["CHudSuitPower"] = true
}

But it still shows over my custom HUD. 

This has been happening since the darkrp update and therefore I believe it has something to do with this?

**Comment by Partixel** [comment]
["DarkRP_HUD"] = true,

**Comment by FPtje** [comment]
yup, works for me.
