### ISSUE TITLE
FPP

### ISSUE THREAD

**Issue by dan2735** [FPtje/DarkRP#1857]
It seems that FPP is no longer stopping proppushing / prop ghosting. Any ideas?

**Comment by HDG-MrDeeJay** [comment]
Because it never did?

**Comment by FPtje** [comment]
It used to in like 2010. I'm like the daddy of all retarded prop kill prevention scripts. It's a mistake I regret dearly.

**Comment by HDG-MrDeeJay** [comment]
Damnit falco you are the reason I cant shove a washing machine down the 
throats of whinging 12 year old admins.

**Comment by FPtje** [comment]
Sry
