### ISSUE TITLE
GetNWInt returning 0

### ISSUE THREAD

**Issue by Kamshak** [FPtje/DarkRP#1858]
Short disclaimer: I am not 100% certain this is caused by DarkRP. It did however begin to happen with the newest DarkRP version. Unfortunately i do not know which commit started the problem. 

With a recent update of DarkRP clientside GetNWInt doesn't return the number set but instead 0 consistently. GetNWInt serverside returns the correct number. Setting it again on the server or waiting for an extended period of time does not fix the problem.

Does anyone have any idea what could cause this problem? Was anything changed that could affect NWVars lately?

**Comment by HDG-MrDeeJay** [comment]
My friends TTT server encountered a similar issue recently, have you 
tried re-installing your copy of the Garry's Mod server instance? That 
seemed to work for me (Exact same thing with NWInt)

**Comment by FPtje** [comment]
Update your server.
