### ISSUE TITLE
Warning: Unhandled usermessage '_Notify'

### ISSUE THREAD

**Issue by JohnOakman** [FPtje/DarkRP#1860]
Here is the problem.
The nofitication doesn't want to appear and instead of appear it say in the console:
"Warning: Unhandled usermessage '_Notify'"
I'm running the darkrp on a Dedicated Server, in 2.6.0 and the latest version of GMOD.

Help please.

**Comment by Partixel** [comment]
Update to the latest version and test

**Comment by FPtje** [comment]
bad install

**Comment by JohnOakman** [comment]
i have downloaded and installed the latest version and same error.

**Comment by FPtje** [comment]
Did you use filezilla?

**Comment by JohnOakman** [comment]
No, It is actually installed on my computer for developpment

**Comment by FPtje** [comment]
The code that prevents this error from happening is in
modules/hud/cl_hud.lua line 373

This is not my problem.

**Comment by JohnOakman** [comment]
THX I FIX IT !
