### ISSUE TITLE
/setspawns (TEAM_NAME) does not save upon restart

### ISSUE THREAD

**Issue by snakescater** [FPtje/DarkRP#1862]
My server was broken on the beta, now running the non beta and lots is fixed, there are still a few bugs i would like to through out there.

1. /setspawn (TEAM_NAME) does not save upon restart, it does say spawn set but will not save.

2. Fadmin cannot make/edit groups gets spammed with this: [ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:243: attempt to index field 'user' (a nil value)
  1. DoClick - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:243
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_controls.lua:299

**Comment by FPtje** [comment]
Cannot reproduce.

**Comment by FPtje** [comment]
Also, you somehow removed the "user" usergroup.

**Comment by snakescater** [comment]
How would I go about fixing this? My server auto updated to 2.6.1 beta, then to 2.6.1 and now the spawns/Fadmin does not work
