### ISSUE TITLE
[Solved] Jail door - Unlock

### ISSUE THREAD

**Issue by EpicKiing** [FPtje/DarkRP#1863]
I have a problem on my DarkRP server on the latest version. When I lock the jail door and then restart the server, the door get unlock and I don't want that, I want jail's doors to be locked on a restart. My map is Rockford and I'm french, so sorry for mistakes.

**Comment by Bo98** [comment]
Aim at the door and type `rp_lock` into the console. Normal locking with the keys does not save but the `rp_lock` command does.

**Comment by EpicKiing** [comment]
Omg thank you, is there a website or something with all these tricks/commands?

**Comment by Bo98** [comment]
There is a console commands page on the wiki but it is incomplete:

http://wiki.darkrp.com/index.php/DarkRP:Console_Commands

I'll update it with the missing commands tomorrow.

**Comment by EpicKiing** [comment]
Thank you
