### ISSUE TITLE
CanDropOnDeath

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1864]
I would like a config for CanDropOnDeath not just CanDrop.
Even a Hook for CanDropOnDeath would be neat.
As some weapons should be dropped but not be loosen if we say Ammo is nil like a rocket launcher from M9K.
I changed a CVar so M9K Specialties Weapons like IED Detonator are stripped on Nil ammo.
But the timer need 0.5 seconds, to let time to play the animation fo the deploying of somthin.
So I would like a new hook or a config option to restrict that.

**Comment by FPtje** [comment]
I think it's easier for both you and me if you just disable "drop weapon on death" and make your own.

**Comment by HDG-MrDeeJay** [comment]
Am i the only one who finds his engrish impossibru to read?
