### ISSUE TITLE
Pocket & WorldProps

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#1866]
Shouldn't / Aren't World Props blocked by default in the Pocket? At least on my Install they are not, also not on a clean one for testing purposes.

So when people take small WorldProps in their Pocket, as soon as they release them again they will stay on the spawned place. You can't delete them anymore, and they are also nocollided. Its like simply the draw of the model stays there. In huge amounts, this can also lagg servers.

Anybody else can confirm this?

**Comment by CodedNil** [comment]
Never seen this before, you have a specific model that does this?
