### ISSUE TITLE
ULX Ranks Overwriting FAdmin

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#1867]
Is this supposed to be this way? Shouldnt they adapt instead of Overwriting themselves? eg if its something different then user, then adapt - otherwise overwrite.

**Comment by FPtje** [comment]
Intended behaviour.

**Comment by Neosinos** [comment]
Why is it intended? Why not let them Co-Exist? Or let the Server Owner choose if FAdmin should overwrite ULX, or ULX should overwrite FAdmin? The second suggestion would really be a giant enhancement.

**Comment by HDG-MrDeeJay** [comment]
I really dont see what the problem is with the current behaviour, what 
am I missing here?

**Comment by FPtje** [comment]
All intercompatibility is on hold until CAMI is a thing.

**Comment by HDG-MrDeeJay** [comment]
And why does this sound familiar... reminds me of something that was 
used to "revolutionize prop protection" and ended up being a big 
headache for wire because they refused to use it and IsSuperAdmin() 
correctly...
