### ISSUE TITLE
/me Global(?)

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#1868]
Calling 'ply:ConCommand( "say /me touches his nippples" )' this will be shown global. Shouldnt /me in terms of Roleplay only show in local chat?

**Comment by Partixel** [comment]
I can see why you wouldn't want that in global chat.

You naughty boy.

**Comment by HDG-MrDeeJay** [comment]
The question more so is why are you calling that particular phrase in 
concommand? Bit homo-erotic given the age and sex of most Garry's Mod 
players, especially in DarkRP...

**Comment by FPtje** [comment]
Well turn off GAMEMODE.Config.alltalk

**Comment by FPtje** [comment]
It was ULX.

**Comment by Neosinos** [comment]
Yep. My bad. Fucking stupid I didnt think of ULX confronting with it.

2015-03-30 17:47 GMT+02:00 Falco Peijnenburg <notifications@github.com>:

**Comment by HDG-MrDeeJay** [comment]
Hang on gang, there's still a mystery to be solved here!

Why the fuck would you wand that to be forced upon a user? What sort of 
RP server are you running? If its a brothel, can I buy VIP lol.

**Comment by Neosinos** [comment]
Maybeeee... It's a secret :3
Thahaha :D

Am Montag, 30. März 2015 schrieb Nathan Davies-Lee :

**Comment by FPtje** [comment]
There's a thing in DarkRP that's supposed to remove the ULX /me hook. ULib broke their hook system, so the hook isn't being removed anymore.
