### ISSUE TITLE
Workaround / Developer Asskick

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#1875]
So, I am not completly sure if this Dev is a Idiot and needs a Asskick for telling people to edit Core Files to get his Addon fully working - or maybe there just isnt any other way?

I guess the easiest way would be to simply add the RPName as a Module which should be able to get disabled in the DisabledDefaults?

Quote:
>How to disable the rpname command ("/rpname")
>Go to "darkrp\gamemode\modules\base" and edit the file "sv_entityvars.lua"
>change this line "concommand.Add("rp_setname", setRPName)" to "-->concommand.Add("rp_setname", setRPName)" (line 147)
>change those lines (172, 173, 174) "DarkRP.defineChatCommand("rpname", RPName)
>DarkRP.defineChatCommand("name", RPName)
>DarkRP.defineChatCommand("nick", RPName)"
>to
>"--DarkRP.defineChatCommand("rpname", RPName)
>--DarkRP.defineChatCommand("name", RPName)
>--DarkRP.defineChatCommand("nick", RPName)"
>thats it.
>Script: https://scriptfodder.com/scripts/view/1062

**Comment by FPtje** [comment]
You're a god damn idiot. Not just because you're unaware of and couldn't find these two REALLY basic functions:
http://wiki.darkrp.com/index.php/Functions/DarkRP/Shared/removeChatCommand
http://wiki.garrysmod.com/page/concommand/Remove

But also because you have me on friends and you know my stance of "if editing the core files is the only way to do something it's my responsibility". You should have asked BEFORE telling them to edit core files.

**Comment by HDG-MrDeeJay** [comment]
"Go to "darkrp\gamemode\modules\base" and edit the file "sv_entityvars.lua""

He is a fuckwit and a half. And to make matters worse, he is selling his 
addon. For money. This is why ScriptFodder is a bad thing.

**Comment by Neosinos** [comment]
Falco. I am NOT the Developer. I've just seen this on SF and reported it,
so you can give him an Asskick for telling Customers to edit Corefiles.

Am Freitag, 3. April 2015 schrieb Falco Peijnenburg :

**Comment by HDG-MrDeeJay** [comment]
Woah falco, wrong conclusion.

He said someone was selling it on scriptfodder and telling people to do 
this. Not that he was doing it.

**Comment by FPtje** [comment]
Sorry for that. What a massive cunt.

**Comment by Partixel** [comment]
Lol'd. Some guy that bought my addon said this, I feel like it is so relevant:

"Okay, pissed off now. So basicly i go out and buy this addon, thinking its gonna be dope af, but its broken af.... I cannot use it with my server for some reason now. It only works if i am not using jobrelated.lua if i use / customize that file, the entire fucking server breaks,"

**Comment by HDG-MrDeeJay** [comment]
Scriptfodder is a cancerous stain on the garry's mod community. It isn't 
even original, which makes it worse than coderhire. Kids that would have 
once learned how to make cool gamemodes like LightRP and Deathmatch etc 
nowadays just throw their mummy's and daddy's credit card at strangers 
on the net to make their shit for them, or worse, buy prefab code to do 
it all for them.

**Comment by Partixel** [comment]
*cough* And DarkRP *cough*

**Comment by FPtje** [comment]
This is about one cunt who happened to sell his body juices on
scriptfodder. If it wasn't for scriptfodder he would have spread it
somewhere else. It could as well have been the workshop or even
garrysmod.org.

The medium is irrelevant.

2015-04-03 10:57 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
I would buy your body juices from scriptfodder, FPtje, ;)

**Comment by FPtje** [comment]
You'll have to buy me a bunch of jars first.

2015-04-03 11:00 GMT+02:00 Partixel <notifications@github.com>:

**Comment by Partixel** [comment]
Crap, you're right! I didn't think about storage.

**Comment by HDG-MrDeeJay** [comment]
ew

**Comment by CodedNil** [comment]
http://sementank.com/sementanks.htm
