### ISSUE TITLE
Using a stacked spawned_weapon with stored ammo does not deduct the ammo

### ISSUE THREAD

**Issue by UselessGhost** [FPtje/DarkRP#1876]
Although this isn't an issue in stock DarkRP because there's no situation that can be created where a stacked spawned_weapon can exist with stored ammo, certain addons can cause this specific scenario.

Due to this, if a player finds a way to merge two weapons that have ammo on them into a stack, they can essentially get infinite ammo.

**Comment by FPtje** [comment]
I'm not sure what you mean. Give me the steps to reproduce.

**Comment by UselessGhost** [comment]
local ent = ents.Create( "spawned_weapon" )
    ent:SetWeaponClass( "weapon_cs_ak472" )
    ent:Setamount( 10 )
    ent:SetPos( Entity( 1 ):GetPos() )
    ent.ammoadd = 100
    ent:Spawn()

The spawned weapon will give you the 100 pieces of ammunition every time you try to pick up the gun.

**Comment by HDG-MrDeeJay** [comment]
So basically, you can multiply the ammo in one gun by throwing it in a 
stack? Damn.

**Comment by FPtje** [comment]
That behaviour makes sense unless the gun is not removed when you pick it
up. Guns can have ammo in their clips and they can come with some ammo
"lying around" so to speak.

**Comment by UselessGhost** [comment]
The problem is exactly that though, the gun ISN'T removed when it's in a stack, you can use it multiple times and receive the ammo every time.

**Comment by FPtje** [comment]
The addons that do the merging edit the `ammoadd`. They should think of this when they do that. This is wanted behaviour because of shipments. When you shoot a shipment, it drops all the guns. Each gun then gives you a certain amount of ammo.

Other mods should be more intelligent, tell them there's such thing as an average.
