### ISSUE TITLE
Cannot connect to remote MySQL database

### ISSUE THREAD

**Issue by HybridFox** [FPtje/DarkRP#1880]
When i try to use a remote MySQL database for my DarkRP i get a weird error,
somehow when i input an IP and not the standard 127.0.0.1 i get this weird error

```
gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:333: Connection failed! Access denied for user 'xxxxxxxxxxxx_felix'@'%' to database 'xxxxxxxxxxxx_darkrp'
```

Somehow my IP becomes a %.
This is my mysql.lua from DarkModification http://pastebin.com/pXqfC3yW

MySQL OO is setup correctly since other addons can connect to the DB

**Comment by MStruntze** [comment]
And you're sure that your MySQL permissions are set up to allow non-localhost connections?

**Comment by HybridFox** [comment]
Like i said, other addons can connect succesfully (more precisly UGB) as you can see here http://prntscr.com/6pzyw5

**Comment by FPtje** [comment]
Not a help forum

**Comment by HybridFox** [comment]
I am not asking for help, i am reporting this as a bug since the script isnt using the IP i gave.

**Comment by MStruntze** [comment]
It wouldn't return Access denied if it tried to connect to %.

**Comment by HybridFox** [comment]
I'm 100% sure i'm using the correct data. And it wouldnt make sense to use % instead of the actual IP since when i use 127.0.0.1 it returns that.

**Comment by FPtje** [comment]
DarkRP can't throw that error unless the MySQL library says the password is wrong.

**Comment by HybridFox** [comment]
I Agree, But why does it say "%" instead of my IP i gave?

**Comment by FPtje** [comment]
Ask the maintainer or MySQLOO. MySQLite is just passing on the error.

**Comment by HybridFox** [comment]
Anyway, i'm using a local MySQL Database now and that seems to be working
