### ISSUE TITLE
spawned_shipment

### ISSUE THREAD

**Issue by legitdood** [FPtje/DarkRP#1882]
I've made use for some other entities in my modified version of DarkRP, I would like to disable the default spawned_shipment entity, and copy the source code over into a new spawned_shipment entity in my modificationsmaster folder so that I can allow the /createshipment command to work for other entities such as drugs and tools.

Could you add a way to disable the default spawned_shipment entity in the disabled_defaults file please?

Thanks.

**Comment by HDG-MrDeeJay** [comment]
isn't there an option to specify what entity you wish to use for shipments?

**Comment by FPtje** [comment]
http://wiki.darkrp.com/index.php/DarkRP:CustomShipmentFields

shipmentClass
