### ISSUE TITLE
Category not registering my jobs???

### ISSUE THREAD

**Issue by Salkio** [FPtje/DarkRP#1887]
Good day,
Just to start off i have not touched any of the DarkRP core files. All the editing of the jobs i have done in the mod folder. In the category's file in the mod folder i have put my job category's when i start up my server is says that the job "Hit man" has an invalid category "VIP". And im 100% sure i have put VIP as a category.
Please help
Thanks

**Comment by FPtje** [comment]
Not a help forum.

**Comment by Salkio** [comment]
Oh sorry about that. I clicked on help and it redirected me to here. Where can i post this?
Sorry about this :P

**Comment by FPtje** [comment]
forum.darkrp.com

Which help button did you click exactly?

**Comment by Salkio** [comment]
Thank you.
I clicked the one on github top middle of the screen to the right and when i clicked that it said FPtji can help you more than Githelp support rather submit a support ticket here and i click here and it sent me here xD.

**Comment by Salkio** [comment]
Cool posted my issue. Please could you the professional take a look at it?
Im really mind boggled in this error.

**Comment by HDG-MrDeeJay** [comment]
I assume you mean github support. And why the fuck would they send help 
requests here instead of the forum or the website?

**Comment by Bo98** [comment]
GitHub doesn't know every repository's support URL. The blue message box at https://github.com/contact is autogenerated from the last repository you viewed.

**Comment by HDG-MrDeeJay** [comment]
well that explains a lot. Guess we need bigger text to tell people to 
FUCK OFF TO THE FORUMS IF YOUR ISSUE CONTAINS THE WORD "help"
