### ISSUE TITLE
Categories seem to be buggy

### ISSUE THREAD

**Issue by ImDesire** [FPtje/DarkRP#1895]
If I have a category like this 

DarkRP.createCategory{
name = "Submachine Guns", 
categorises = "shipments", 
startExpanded = false, 
color = Color(0, 0, 255, 255),
sortOrder = 1, 
}

and all my weapons like this,

DarkRP.createShipment("UZI", {
    model = "models/weapons/w_uzi_imi.mdl",
    entity = "m9k_uzi",
    price = 6000,
    amount = 10,
    category = "Submachine Guns",
    separate = true,
    pricesep = 1400,
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

It doesn't allow the last category = "Submachine Guns",

-- Explanation go to the last shipment code

DarkRP.createShipment("Bizon PP19", { -- M9K Submachine
    model = "models/weapons/w_pp19_bizon.mdl",
    entity = "m9k_bizonp19",
    price = 6500,
    amount = 10,
    separate = true,
    pricesep = 1500,
    noship = false,
    allowed = {TEAM_GUN},
	category = "Submachine Guns",
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("AAC Honey Badger", {
    model = "models/weapons/w_aac_honeybadger.mdl",
    entity = "m9k_honeybadger",
    price = 7000,
    amount = 10,
    separate = true,
    pricesep = 1750,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("KAC PDW", {
    model = "models/weapons/w_kac_pdw.mdl",
    entity = "m9k_kac_pdw",
    price = 6500,
    amount = 10,
    separate = true,
    pricesep = 1500,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("Magpul PDR", {
    model = "models/weapons/w_magpul_pdr.mdl",
    entity = "m9k_magpulpdr",
    price = 6200,
    amount = 10,
    separate = true,
    pricesep = 1400,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("HK MP5", {
    model = "models/weapons/w_hk_mp5.mdl",
    entity = "m9k_mp5",
    price = 6500,
    amount = 10,
    separate = true,
    pricesep = 1500,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("MP5SD", {
    model = "models/weapons/w_hk_mp5sd.mdl",
    entity = "m9k_mp5sd",
    price = 6750,
    amount = 10,
    separate = true,
    pricesep = 1600,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("HK MP7", {
    model = "models/weapons/w_mp7_silenced.mdl",
    entity = "m9k_mp7",
    price = 7000,
    amount = 10,
    separate = true,
    pricesep = 1750,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("MP9", {
    model = "models/weapons/w_brugger_thomet_mp9.mdl",
    entity = "m9k_mp9",
    price = 7300,
    amount = 10,
    separate = true,
    pricesep = 1800,
	category = "Submachine Guns",
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("MP40", {
    model = "models/weapons/w_mp40smg.mdl",
    entity = "m9k_mp40",
    price = 7000,
    amount = 10,
    separate = true,
    pricesep = 1750,
	category = "Submachine Guns",
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("FN P90", {
    model = "models/weapons/w_fn_p90.mdl",
    entity = "m9k_smgp90",
    price = 7000,
    amount = 10,
    separate = true,
    pricesep = 1750,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("STEN", {
    model = "models/weapons/w_sten.mdl",
    entity = "m9k_sten",
    price = 6900,
    amount = 10,
    separate = true,
    pricesep = 1600,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("TEC-9", {
    model = "models/weapons/w_intratec_tec9.mdl",
    entity = "m9k_tec9",
    price = 5700,
    amount = 10,
    separate = true,
    pricesep = 1400,
	category = "Submachine Guns",
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("Tommy Gun", {
    model = "models/weapons/w_tommy_gun.mdl",
    entity = "m9k_thompson",
    price = 7000,
    amount = 10,
	category = "Submachine Guns",
    separate = true,
    pricesep = 1750,
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("HK UMP45", {
    model = "models/weapons/w_hk_ump45.mdl",
    entity = "m9k_ump45",
    price = 7000,
    amount = 10,
    separate = true,
    pricesep = 1750,
    noship = false,
	category = "Submachine Guns",
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("HK USC", {
    model = "models/weapons/w_hk_usc.mdl",
    entity = "m9k_usc",
    price = 7200,
    amount = 10,
	category = "Submachine Guns",
    separate = true,
    pricesep = 1800,
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

DarkRP.createShipment("UZI", {
    model = "models/weapons/w_uzi_imi.mdl",
    entity = "m9k_uzi",
    price = 6000,
    amount = 10,
	category = "Submachine Guns", -- If I have this as something else, all the other weapons works properly within the category, if it's proper like the rest it breaks.
    separate = true,
    pricesep = 1400,
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})

**Comment by FPtje** [comment]
Not a help forum.
