### ISSUE TITLE
attempt to call method 'SetLastOwner'

### ISSUE THREAD

**Issue by Munchh** [FPtje/DarkRP#1899]
[ERROR] gamemodes/darkrp/entities/weapons/weapon_cs_base2/shared.lua:113: attemp
t to call method 'SetLastOwner' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/weapon_cs_base2/shared.lua:113

Seems to appear when you become CP and specifically is breaking the agenda, I updated my DarkRP last night and it's been happening since, 0 edits to core files.

**Comment by FPtje** [comment]
https://github.com/FPtje/DarkRP/blob/master/entities/weapons/weapon_cs_base2/shared.lua#L97

Cannot reproduce and error should be impossible.
Probably a bad install.
