### ISSUE TITLE
entites dont spawn

### ISSUE THREAD

**Issue by TheUnknownGamer9** [FPtje/DarkRP#1900]
Hello,

I have added custom entities to my darkrp server, when ever I try to go buy them, i get "/buymoneyprinter" in chat. 

Here is the entity :

DarkRP.createEntity("Money Printer", {
    ent = "ng_money_printer",
    model = "models/props_c17/consolebox01a.mdl",
    price = 5000,
    max = 2,
    cmd = "moneyprinter"
})

Please help me! <3

- Aciri

**Comment by FPtje** [comment]
Not a help forum
