### ISSUE TITLE
A way to add buttons to the key menu

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1902]
e.g at line 169 of [DarkRP/entities/weapons/keys/cl_menu.lua]( https://github.com/FPtje/DarkRP/blob/master/entities/weapons/keys/cl_menu.lua) add this:
hook.Run("HUDDrawKeyMenu", ent, Frame)

I'm not making this a pull request because I have no idea how your hookStub system works :( ( plz dont shout at me bb )

**Comment by Partixel** [comment]
I know this could be done by overwriting the DarkRP functions but the reason I would prefer if DarkRP had this is because custom F2 menus could then add support for it built in.

**Comment by HDG-MrDeeJay** [comment]
Something I thought would be a great idea.

But I think, you /should/ consider doing the PR yourself. The only way 
to learn how the stubs work is by working with them.

**Comment by Partixel** [comment]
I know I /should/ but I assume I'll fuck it up somehow and get shouted at

**Comment by HDG-MrDeeJay** [comment]
you know what they say about assuming things.

it makes an ASS out of U and ME

In this case, more you than me.

**Comment by Partixel** [comment]
As far as I can see, no other weapon has hookStubs so I have no idea what to base it off of.

**Comment by Partixel** [comment]
Fork it, I'll make a pr.

**Comment by Partixel** [comment]
#1903
