### ISSUE TITLE
Add a way to cap the amount of money anyone on the server can have at once

### ISSUE THREAD

**Issue by RhapsodySL** [FPtje/DarkRP#1904]
If they try to pick up money and that amount puts them over the limit, notify them and don't delete the money entity. If their payday puts them over the limit, don't do the payday. Ideally, it should be implemented in a way where compatibility is preserved with addons that directly give the player money.

**Comment by Bo98** [comment]
http://wiki.darkrp.com/index.php/Hooks/Server/playerWalletChanged

**Comment by RhapsodySL** [comment]
I'm aware this isn't a help forum, but since this is already closed and here, I'll post it here;

I'm using the following code in lua/autorun/server, but it doesn't appear to be working.

local limit = 4500000
hook.Add("PlayerWalletChanged", "WalletCap", function(ply, amount, total) 
    return math.Min(total + amount, limit) -- Return the minimum between the changed total and the limit
end)

**Comment by Bo98** [comment]
Lowercase P in playerWalletChanged.
