### ISSUE TITLE
Ugly unarrest/arrest stick issue

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1907]
I have an ugly issue with the 2 sticks.
If I equip a arrest stick while having a unarrest stick in my equipment, press SecondaryFire, switch Weapon and press again SecondaryFire, SecondaryFire on all weapons is switching the sticks from unarrest to arrest.

**Comment by FPtje** [comment]
@Bo98 should have fixed this in latest. Workshop version has not been uploaded yet.

**Comment by deinemudda32** [comment]
I am up to date.
Happens in the new versions too.

**Comment by Bo98** [comment]
ffs

Does ply:GetActiveWeapon() always return arrest_stick/unarrest_stick or something?

**Comment by Bo98** [comment]
Is this on singleplayer, a listen server or a dedicated server?

**Comment by deinemudda32** [comment]
listen server.

**Comment by Bo98** [comment]
Which addons? I've not managed to reproduce this on a listen server yet.

**Comment by deinemudda32** [comment]
M9Kweapons and more. but not other weapons which modifies weapons
