### ISSUE TITLE
Global Spawnpoint?

### ISSUE THREAD

**Issue by rocky123xo** [FPtje/DarkRP#1908]
I know it's possible to set job-specific spawnpoints using /setspawn <jobname>, but is it possible to just set several global spawnpoints, that are used by all jobs? I'd like all players to spawn in the same area, that is different from the map's default. It's a pain in the butt to set and add spawns for 30+ jobs.

**Comment by FPtje** [comment]
Falls beyond the scope of the gamemode. 
This should lie with map makers or other addons.
