### ISSUE TITLE
Having issues with an addon due to a recent beta update.

### ISSUE THREAD

**Issue by yatooma25** [FPtje/DarkRP#1916]
I own a sever hosted by NFO. I mounted DarkRP using their automatic system, which means the files are all updated by SVN. Recently, we noticed that we are using a beta version. Shortly after that, our NPC Car Dealer stopped working. I know what you're already thinking... it's not the addon. I came onto github and checked the recent updates about 3 days later. When I looked, there was an update that said "3 days ago". I understand that the Car Dealer is considered "Outdated", but we cannot downgrade our current version of DarkRP. The Car Dealer works when it is respawned, however if you rejoin or join after it's been spawned, you cannot "use" it. I'm also attempting to get in contact with the car dealer developer. I don't know if what's causing this is a bug in the beta update, or if something just messed up on our end. There are no script errors, and as stated before, it works fine unless you rejoin. I can't seem to see what files were modified when this started. If this is a beta issue, I hope it can be fixed and will resolve problems for others. If it's a problem on my end, could you tell me what files were modified so I can try to downgrade them? If so, thank you.

Link to the car dealer addon:
https://scriptfodder.com/scripts/view/126
Issue broken down:
The NPC car dealer entity cannot be "used" after players rejoin.

**Comment by FPtje** [comment]
I'm not the author of that car dealer. 
I have no access to that car dealer. 
I have no technical specification of a bug. 
I have no direct means to reproduce anything here. 

This report is invalid. Talk to the author of the car dealer. Have HIM report any bugs to me.

**Comment by yatooma25** [comment]
Could you at least tell me what files may have been modified 3-5 days ago that may have caused this car dealer to stop functioning correctly? I understand you deal with a lot of bullshit and idiots on a daily basis, but I really need to get this problem solved soon and i'm 100% sure it is being caused by DarkRP. This is something neither me, or the developer of the car dealer can remedy on our own without said information.

**Comment by Bo98** [comment]
Very little has changed in the past 3-5 days, nothing that should break any car dealer addons.
