### ISSUE TITLE
allowed = {TEAM_GUN}, Broken for separate weapons

### ISSUE THREAD

**Issue by OMGLent** [FPtje/DarkRP#1919]
DarkRP.createShipment("HK USP", {
    model = "models/weapons/w_pist_fokkususp.mdl",
    entity = "m9k_usp",
    price = 500,
    amount = 1,
    separate = true,
    pricesep = 500,
    noship = true,
    allowed = {TEAM_LIGHTDEALER}
})

What I attempted to use tried multiple settings.

allowed = {TEAM_} < Fails to detect this for separate weapons and instead shows and allows the purchase of separate weapons on all classes.

**Comment by FPtje** [comment]
Still not a help forum
