### ISSUE TITLE
DarkRP Modules don't take the language

### ISSUE THREAD

**Issue by BigBrainAFK** [FPtje/DarkRP#1921]
Hello,

so I've made a German translation via the darkrpmodification folder. The problem is that DarkRP modules like hitmenu and afk won't use the German language i provide. They still use the English language and yes I added "gmod_language 'de'" to my server.cfg.

**Comment by FPtje** [comment]
![2015-05-01_17-03-16](https://cloud.githubusercontent.com/assets/1202014/7431966/07e4fdac-f024-11e4-8327-8c2ec7f1b051.png)

Works for me. The hitman text on the player is a config option rather than a language thing.

**Comment by BigBrainAFK** [comment]
just write it into the english.lua because even if you write it in a e.g.: german.lua and declare it as "de" it just fucks up so just replace everything in english.lua

**Comment by deinemudda32** [comment]
You copied my trick :D

**Comment by BigBrainAFK** [comment]
and i know your server and would love it to be dev over there

**Comment by deinemudda32** [comment]
Im nothing against the project of bigger coders :).
You can contact me on steam, I always accept everyone.

**Comment by Bo98** [comment]
`gmod_language` is clientside concommand remember - it is the language you set the game too. That may be why it wasn't working for you.

**Comment by deinemudda32** [comment]
yea and I set it to "de", but not working.
