### ISSUE TITLE
Bug Darkrp Notify

### ISSUE THREAD

**Issue by NahimBlack** [FPtje/DarkRP#1922]
For almost one day on my server there is no notification as 'Monsieur has found 100$'

Can you help me? darkrp my server is 2.6.1

**Comment by HDG-MrDeeJay** [comment]
Perhaps that for because nobody money pickup for day one?

**Comment by FPtje** [comment]
I don't understand this bug report.

**Comment by HDG-MrDeeJay** [comment]
Hence why i replied in google translate's version of english.
