### ISSUE TITLE
dark rp server needs an admin

### ISSUE THREAD

**Issue by forc3ful** [FPtje/DarkRP#1923]
there is people on the dark rp server rdming, and job abuseing someone need to get on and ban them.
please and thank you

**Comment by HDG-MrDeeJay** [comment]
You are officially retarded.

Get out.

**Comment by stapler2025** [comment]
Oh god my sides

**Comment by Colefrick** [comment]
Oh. My God.... Kill it...With FIRE.

Leave the bug section alone unless you want to report a BUG!

**Comment by HDG-MrDeeJay** [comment]
Guys, cmon... this is someone's child. Surely someone loves him.

...



...

Maybe not.

**Comment by FPtje** [comment]
Not a help forum.
