### ISSUE TITLE
file.* Functions broken

### ISSUE THREAD

**Issue by 00875** [FPtje/DarkRP#1924]
Some times (for example: after 10 minutes of running server) file functions brokes. 
L 05/05/2015 - 17:47:43: Lua Error: 
[ERROR] addons/pony_player_models/lua/ppm/cache.lua:72: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. LoadFromCache - addons/pony_player_models/lua/ppm/cache.lua:72
     4. func - addons/pony_player_models/lua/ppm/cache.lua:236
      5. unknown - lua/includes/modules/net.lua:32

L 05/05/2015 - 17:48:11: Lua Error: 
[ERROR] addons/ulib/lua/ulib/shared/util.lua:112: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. fileAppend - addons/ulib/lua/ulib/shared/util.lua:112
     4. logWriteln - addons/ulx/lua/ulx/log.lua:157
      5. logString - addons/ulx/lua/ulx/log.lua:150
       6. v - addons/ulx/lua/ulx/log.lua:175
        7. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:93
And for end:
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/logging/sv_init.lua:29: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. Log - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/logging/sv_init.lua:29
     4. fn - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/logging/sv_init.lua:34
      5. Call - addons/ulib/lua/ulib/shared/hook.lua:108
       6. unknown - gamemodes/sandbox/gamemode/commands.lua:693
        7. unknown - lua/includes/modules/concommand.lua:54

All errors are related to file.* functions. This is only happens on my DarkRP server. All other server are working fine.
When this happens, all are Freemans and no money or job (wallet are nil too)
I tried to delete data folder and recreate it, but it's not help.

**Comment by FPtje** [comment]
*"This only happens on my DarkRP server"* is no evidence that DarkRP is the cause of the issue.
No other evidence is given, and given the other errors you're having, it's extremely unlikely that this is an issue caused by DarkRP.

**Comment by 00875** [comment]
https://github.com/Nayruden/Ulysses/commit/c666ef8baf2e46a9b51cb8fbd2c1423e98819d13

This can give you some information

**Comment by HDG-MrDeeJay** [comment]
>pony player models

Oh boy, another copy of MLSRP's idea.

**Comment by 00875** [comment]
I don't know. In past everything works PERFECT. But after Gmod update all broken.

**Comment by FPtje** [comment]
That ULib commit has little to do with anything DarkRP does.

**Comment by HDG-MrDeeJay** [comment]
Gmod update? There has been no update since 9/3/2015

**Comment by 00875** [comment]
![2015-05-05_18-07_c-users-roboderpy-appdata-loc](https://cloud.githubusercontent.com/assets/6339511/7471465/9d0dc42e-f351-11e4-9935-bc24c7c058db.jpg)
I have no idea

**Comment by HDG-MrDeeJay** [comment]
Well its clear the issue starts with pony player models. May I recommend something?

Uninstall it, and see if the issue persists.

**Comment by HDG-MrDeeJay** [comment]
Literally takes 2 seconds to realise thats the first problem and should be removed.

**Comment by 00875** [comment]
Uninstalled, now i will test

**Comment by 00875** [comment]
![2015-05-05_18-14_c-users-roboderpy-appdata-loc](https://cloud.githubusercontent.com/assets/6339511/7471553/a7413e02-f352-11e4-92fb-c304695730e8.jpg)

85: if not file.Exists("braxnet/atm/players/"..ply:UniqueID()..".txt", "DATA") then

**Comment by FPtje** [comment]
Also, your DarkRP cannot be up to date. Errors refer to lines that cannot have these errors:

```
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/logging/sv_init.lua:29: bad key to string index (number expected, got string)
```

**Comment by 00875** [comment]
I updated today darkrp to latest!
![2015-05-05_18-16_garry s mod](https://cloud.githubusercontent.com/assets/6339511/7471571/d85ec400-f352-11e4-9aa4-e74f3e0fd031.jpg)

**Comment by FPtje** [comment]
More also: it looks like you're reporting the error of some brax_atm thing. This is the DarkRP repository, not the "brax_atm" repository.

**Comment by 00875** [comment]
Brax_ATM are writed by me, but when i wrote these thing, all works right

**Comment by FPtje** [comment]
Surely you would know how to properly report a bug if you knew how to code. The file.* functions aren't even from DarkRP. They're GMod functions.

**Comment by HDG-MrDeeJay** [comment]
Now you see why I changed my avatar Falco.

**Comment by 00875** [comment]
Resolved. New file API broke file searching in folder, where are MANY files
