### ISSUE TITLE
canArrest hook call

### ISSUE THREAD

**Issue by PwndKilled** [FPtje/DarkRP#1925]
Hey, I was wishing for a fix with the canArrest hook only be called if the guy is successfully arrested.

Because i'm using a system that use it, but it's called even when you need a warrant to arrest the person.

I was thinking about adding a hook OnArrest called when the guy is successfully arrested.

Sincerely,

**Comment by Bo98** [comment]
http://wiki.darkrp.com/index.php/Hooks/Server/playerArrested
