### ISSUE TITLE
Sticks

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1933]
If I have both Sticks in my player equipment and then press Primary Fire with what ever weapon, even if its not a un/arrest stick, then the weapon changes to one of the sticks.

**Comment by FPtje** [comment]
@Bo98 Fixed this issue long ago. Update to the latest DarkRP.

**Comment by deinemudda32** [comment]
I did already.

**Comment by FPtje** [comment]
Cannot reproduce.
![2015-05-18_10-44-02](https://cloud.githubusercontent.com/assets/1202014/7677270/e361907e-fd4a-11e4-8951-c4f575cb5665.jpg)

**Comment by Bo98** [comment]
What's with the colour of the stick?

**Comment by FPtje** [comment]
That's the stunstick

**Comment by Bo98** [comment]
Looks half black.

**Comment by FPtje** [comment]
Looked fine in game

**Comment by deinemudda32** [comment]
It worked with M9K Weapons

**Comment by FPtje** [comment]
It works fine without M9K weapons, what are you talking about?

**Comment by deinemudda32** [comment]
the bug worked with aiming with a m9k weapon.

**Comment by HDG-MrDeeJay** [comment]
thats an m9k bug.

**Comment by Bo98** [comment]
I still can't reproduce this with M9K.

**Comment by HDG-MrDeeJay** [comment]
its more related to arrest/unarrest iirc.

I was on a server the other day. No idea what version of DarkRP they had 
(ie repo date), but sometimes using the RMB button would whip out your 
arrest stick, and the only way to fix was to switch to unarrest, switch 
a few times until it properly switched, and then fixed

**Comment by deinemudda32** [comment]
It isnt a bug from M9K. 
M9K doesnt have a function for Secondary Fire, probably thats it.

**Comment by Bo98** [comment]
If anybody has or finds a server with `sv_allowcslua 1`, I'll jump on and see if I can find what's happening.

**Comment by HDG-MrDeeJay** [comment]
i dont have a server with this bug occuring.

Perhaps use a bypasser? i was on a server last night, Azure gaming, that 
had this bug.

**Comment by HDG-MrDeeJay** [comment]
thats the one.

**Comment by Bo98** [comment]
Also will find out what my ping is like connecting to the opposite side of the planet.

**Comment by HDG-MrDeeJay** [comment]
US is 200-350 west to east. Euro is 350-400.

**Comment by Bo98** [comment]
Wow a server without 10TB of downloads.

**Comment by HDG-MrDeeJay** [comment]
Shocking, isn't it?

**Comment by FPtje** [comment]
It's bananas.

**Comment by Bo98** [comment]
"Welcome to Community Name Here" is the first thing I see when I join.

**Comment by HDG-MrDeeJay** [comment]
"Please insert an RP name"

use something trolly. Enforced RP names deserve not even a slight bit of 
respect.

**Comment by FPtje** [comment]
Does it have an anti prop kill?

**Comment by HDG-MrDeeJay** [comment]
Yes, some shitty one that ghosts props.

**Comment by FPtje** [comment]
God damnit, it was almost perfect.

**Comment by HDG-MrDeeJay** [comment]
they block a lot of tools that I would otherwise consider needed for 
construction...


... as superadmin only...

Pls share bypass falco.

**Comment by Bo98** [comment]
This server is outdated. I applied 93738df and it started working.

**Comment by Bo98** [comment]
During the time I've been in the console I have earned $100,000 for "guarding" the bank vault.

**Comment by HDG-MrDeeJay** [comment]
Welcome to DarkRP in 2015.

**Comment by deinemudda32** [comment]
Even after the update the issue doesnt seem to be fixed.
How about just calling the functions if you use SecondaryFire with the actual sticks?

**Comment by Bo98** [comment]
The sticks don't use SecondaryFire for prediction purposes.

Switching weapons should be done on the client before sending to the server so it can call the Deploy method clientside. When SecondaryFire was used before it used ply:SwitchWeapon which only works serverside. It was changed to use CUserCmd:SelectWeapon which is the clientside equivalent. However to get the CUserCmd you need to hook into a hook like StartCommand. This is what the sticks do now. This meant that any setup in SWEP:Deploy was predicted correctly and so you don't have to wait \<ping\>ms for the server to tell you what to do. It's noticeable on laggy connections.

Unfortunately, StartCommand is a GM hook so it has to be added with hook.Add and is therefor also called when the weapons are not equipped. This hook _should_ be removed when the SWEP is holstered. However, SWEP:Holster is not always called clientside for some reason so I therefor added a check to both of the hooks in these cases:

https://github.com/FPtje/DarkRP/blob/master/entities/weapons/arrest_stick/shared.lua#L134-Lundefined

The _only_ ways I can see it possible for this bug to exist for you is if:

* The checks aren't there for you (please check BOTH arrest_stick and unarrest_stick to verify).
* ply:GetActiveWeapon() always returns arrest_stick or unarrest_stick for you which sounds incredibly broken.
* Two weapons have the same entity index. This should be impossible.
