### ISSUE TITLE
[F1 HTML] Receiving console spam and game lag

### ISSUE THREAD

**Issue by Nightcaper** [FPtje/DarkRP#1938]
Upon opening up the F1 menu to view commands I don't know or have forgotten, the wiki page to the right on the F1 menu doesn't load, and my console gets spammed with the following error:
```
[HTML] Unsafe JavaScript attempt to access frame with URL http://wiki.darkrp.com/index.php/Main_Page from frame with URL http://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-5606524894067150&format=160x600&output=html&h=600&slotname=2922845129&adk=579779506&w=160&lmt=1431535146&flash=17.0.0&url=http%3A%2F%2Fwiki.darkrp.com%2Findex.php%2FMain_Page&dt=1432353954809&bpp=2156&shv=r20150519&cbv=r20150521&saldr=aa&prev_fmts=728x90%2C728x90&correlator=8565071423489&frm=20&ga_vid=132019990.1432353957&ga_sid=1432353957&ga_hid=73803169&ga_fc=0&u_tz=-300&u_his=2&u_java=0&u_h=960&u_w=1280&u_ah=930&u_aw=1280&u_cd=32&u_nplug=15&u_nmime=71&dff=sans-serif&dfs=16&adx=0&ady=727&biw=496&bih=534&eid=575144603%2C317150304&oid=3&rx=0&eae=0&fc=24&brdim=0%2C0%2C0%2C0%2C1280%2C0%2C0%2C0%2C513%2C551&vis=1&rsz=o%7C%7Ca%7C&abl=NA&ppjl=t&fu=1024&bc=1&ifi=3&xpc=xGl9p9vqCh&p=http%3A//wiki.darkrp.com&dtd=3435. Domains, protocols and ports must match.
```

Eventually the wiki page loads and the error spam ceases, but it's quite a large annoyance. If there's no intention of fixing this in the near future, is there a way that I can disable the HTML page from trying to load on the F1 menu without messing with the gamemode itself? Thanks for reading my issue report, very flexible gamemode!

**Comment by 00875** [comment]
This is GMod issue, not the DarkRP.

**Comment by Nightcaper** [comment]
Fair enough, I apologize for putting an issue in Issues that was not a fault of DarkRP, and I hope I did not waste anyone's time.


However, while this is closed, could my question be answered regarding how to disable the HTML panel? I'd really appreciate it! If my question isn't answered here, no problem, I'll go on the forums.

**Comment by FPtje** [comment]
@00875 was wrong. It's fixed now.

**Comment by Bo98** [comment]
The console spam thing has been fixed in the latest version if that was the reason why you were wanting to disable it.
