### ISSUE TITLE
Sticks again!!

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1940]
I changed from stick to weapon.
My weapon got colored white.

**Comment by HDG-MrDeeJay** [comment]
imho the sticks need a ground-up redesign/rewrite. They are prone to 
failure and last i checked there were 8 or 9 config vars for them that 
half of them didnt even use.

Perhaps a new one that *CAN* prevent batton rushing via a simple config 
menu.

perhaps we can also find a better way to material shit now with 
submaterials.

**Comment by FPtje** [comment]
Cannot reproduce, need a better description.

**Comment by Bo98** [comment]
It's almost as if ply:GetActiveWeapon() is broken for you.

**Comment by 00875** [comment]
@deinemudda32 Do you use SharkeYe (or something what use view.origin)?
Do your Gmod is freeze when you change weapon?
Did you see this issue when on server are no plugins installed?
Is you using Forked DarkRP (modified core files or something)?
@FPtje cannot do everything until you tell all what i described.

**Comment by HDG-MrDeeJay** [comment]
Am I the only one who doesn't understand this?

**Comment by deinemudda32** [comment]
No I dont understand it too.

**Comment by 00875** [comment]
![2015-05-28_00008](https://cloud.githubusercontent.com/assets/6339511/7851128/2f583e16-0515-11e5-9b91-9655a64852ac.jpg)
...
@deinemudda32 told this happens

**Comment by deinemudda32** [comment]
wow, you made it.
Congrats!

**Comment by HDG-MrDeeJay** [comment]
Ah. The material effect is applying to weapons that it shouldn't be 
applying to.

How the fuck?

**Comment by Bo98** [comment]
> This is VERY rare bug

Agreed. I have yet to reproduce it but I made pull request with a blind fix in attempt to make what should be impossible even more impossible: #1941.
