### ISSUE TITLE
DarkRP 2.6.1 Shipments not showing

### ISSUE THREAD

**Issue by AceTheGmodGeek** [FPtje/DarkRP#1942]
I have shipments for gun dealers, but im having errors when i updated to 2.6.1 AddCustomShipment("KRISS Vector Single", "models/weapons/w_kriss_vector.mdl", "m9k_vector", 2500, 1, false, 123, false, {TEAM_GUNDEALER})
[ERROR] A runtime error has occurred in "your custom shipments" on line -1.
The best help I can give you is this:

Hints:
- Make sure the category is created with DarkRP.createCategory.
- The category name is case sensitive!
- Categories must be created before DarkRP finished loading.

The responsibility for this error lies with (the authors of) one (or more) of these files:
your custom shipments
------- End of Simplerr error -------

**Comment by FPtje** [comment]
forum.darkrp.com

**Comment by HDG-MrDeeJay** [comment]
No, not even the forums falco. He needs help reading.

Goto http://readingeggs.com.au/
