### ISSUE TITLE
Error when player ( bot ) is kicked as soon as it is created

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1943]
Code to reproduce error:

```lua
local placeholder = player.CreateNextBot( "placeholder" )

placeholder:Kick( )
```

**Comment by Partixel** [comment]
I would paste the error here but I can't copy the error from the console and it's easy enough to repo :(

**Comment by HDG-MrDeeJay** [comment]
Why would this have anything to do with DarkRP?

**Comment by Partixel** [comment]
The error is in FAdmin

**Comment by HDG-MrDeeJay** [comment]
Probably should have opened with that.

**Comment by Partixel** [comment]
Attempt to use NULL entity at line 59 of fadmin/access/sh_shared.lua

**Comment by Partixel** [comment]
I was planning on editting the main one once I had written down the error manually, you replied to quickly qq

**Comment by HDG-MrDeeJay** [comment]
I tend to do a lot of things too quickly.

**Comment by Partixel** [comment]
The error also occurs if you try to kick the bot in the "PlayerInitialSpawn" hook that is ran for the bot

**Comment by Partixel** [comment]
![image](https://cloud.githubusercontent.com/assets/2728862/7899310/fc482240-0715-11e5-9c57-3512ed331c4b.png)
