### ISSUE TITLE
FAdmin + MySQL = Fuckup

### ISSUE THREAD

**Issue by HazardZ** [FPtje/DarkRP#1944]
Without MySQL, superadmin has access to everything. With MySQL, superadmin has only access to certain DarkRP commands and most of the FAdmin commands in general does not work. But "FAdmin setroot <root>" works but is useless so is "FAdmin setaccess".

MySQL creates all tables needed, it writes them too but why FAdmin commands stops working, i do not know. This happens even on newest release of DarkRP, nothing edited but connected to MySQL.

This error comes up when i use the command "FAdmin addgroup" --- http://i.imgur.com/TlUjuFD.png.

And when i try to edit the accesses for all the current groups through the UI ingame, this happens (same to many other commands through console) --- http://i.imgur.com/pMM0NBY.png

**Comment by HazardZ** [comment]
But using ULX with DarkRP is just fine though. All cammonds through ulx works well.

**Comment by FPtje** [comment]
You're using the command wrong.

**Comment by 00875** [comment]
lol. I have too 'Admins are SuperAdmins'. But it very easy to fix by changing groups.
