### ISSUE TITLE
Last Update : Table doesn't contain any valid entities!

### ISSUE THREAD

**Issue by Sachha** [FPtje/DarkRP#1945]
Hi, I have this errors : 

gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:99: Table doesn't contain any valid entities!

and

gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:152: Table doesn't contain any valid entities!

Since the last update : http://www.garrysmod.com/2015/06/01/15-06-01/

**Comment by FPtje** [comment]
Fixed in the gmod update after that.
http://facepunch.com/showthread.php?t=1450721&p=47852133&viewfull=1#post47852133
