### ISSUE TITLE
 Issue with new Garry's Mod Update.

### ISSUE THREAD

**Issue by OMGLent** [FPtje/DarkRP#1946]
You're probably already aware that a new Garry's mod update has been release. I installed it on my server and have been getting non stop lua errors spamming my client console all of witch regard DarkRP functions.

-- Examples

[ERROR] addons/customhq-radio/lua/autorun/client/cl_init.lua:29: attempt to call method 'isCP' (a nil value)
  1. v - addons/customhq-radio/lua/autorun/client/cl_init.lua:29
   2. unknown - lua/includes/modules/hook

[ERROR] addons/teamsradion/lua/radio/client/cl_teamradio.lua:94: attempt to call method 'getJobTable' (a nil value)
  1. v - addons/teamsradion/lua/radio/client/cl_teamradio.lua:94
   2. unknown - lua/includes/modules/hook.lua:84

-- Examples end

**Comment by FPtje** [comment]
Update your server again.

**Comment by HDG-MrDeeJay** [comment]
When will they ever pull off a clean update without having to quickfix shit?

**Comment by FPtje** [comment]
Not when no one tests the updates

**Comment by HDG-MrDeeJay** [comment]
Wait what? Legit nobody tests them?

**Comment by HDG-MrDeeJay** [comment]
Falco, you know if the update is stable yet or they got any patching 
left to do? Cautious on whether I should go ahead with the update just 
to update again in 5 minutes.

**Comment by FPtje** [comment]
You don't know whether the water is cold until your balls are in it. Go try it out you lazy cock.

**Comment by HDG-MrDeeJay** [comment]
I love you too.

**Comment by OMGLent** [comment]
Mee too

**Comment by Devul** [comment]
I tested on the newst update with a blank DarkRP copy.

Only issue I encountered is the F4 tabs (excluding Jobs) not loading its categories.

**Comment by FPtje** [comment]
Known issue, GMod problem.
