### ISSUE TITLE
Can't See Ammo

### ISSUE THREAD

**Issue by roastt** [FPtje/DarkRP#1947]
Can't see ammo on F4 but can still purchase it, no errors.

DarkRP.createCategory{
    name = "Other", -- The name of the category.
    categorises = "ammo", -- What it categorises. MUST be one of "jobs", "entities", "shipments", "weapons", "vehicles", "ammo".
    startExpanded = true, -- Whether the category is expanded when you open the F4 menu.
    color = Color(0, 107, 0, 255), -- The color of the category header.
    canSee = function(ply) return true end, -- OPTIONAL: whether the player can see this category AND EVERYTHING IN IT.
    sortOrder = 100, -- OPTIONAL: With this you can decide where your category is. Low numbers to put it on top, high numbers to put it on the bottom. It's 100 by default.
}

DarkRP.createAmmoType("ar2", {
	name = "Rifle ammo",
	model = "models/Items/BoxMRounds.mdl",
	price = 80,
	amountGiven = 30,
	category = "Other"
})

**Comment by FPtje** [comment]
forum.darkrp.com

**Comment by roastt** [comment]
oh come on, Ive been trying to fix this for the last 2 hours, Ive lost playercount and ive got an exam in 2 hours! Please help me dude.... I have no idea what is causing this!

**Comment by HDG-MrDeeJay** [comment]
custom f4 menu?

**Comment by roastt** [comment]
Nope changed to default one for this reason

**Comment by FPtje** [comment]
nmfp, revert your changes and think before directly editing files on a live server next time.
This is not a help forum.

**Comment by roastt** [comment]
Ive done that, I just updated to 2.6.1 today and it just broke everything.

**Comment by roastt** [comment]
Ive done that, I just updated to 2.6.1 today and it just broke everything.

**Comment by roastt** [comment]
I spoke to some of my server owning friends, they seem to be having the same problem! Sorry if I am bothering you.

**Comment by FPtje** [comment]
You're right and GMod is to blame.
http://facepunch.com/showthread.php?t=1450721&p=47853493&viewfull=1#post47853493

**Comment by roastt** [comment]
Yes Ive been reading the thread, I won't be able to reply for a while now. But good luck fixing it, gmod really annoys me sometimes..

**Comment by FPtje** [comment]
Don't wish me good luck, I'm out of this pile of crap! Rather, wish me luck
on my Agda homework!

**Comment by roastt** [comment]
God damn! Aha, well for now im telling my players to review the F1 menu and search for what they need. But A fix would be real nice, but do your more important work first.

**Comment by roastt** [comment]
Is it best I wait for you to fix it or should I use a hot fix (if one is released)

**Comment by FPtje** [comment]
ah, god damnit. You people want a god damn hotfix.

**Comment by FPtje** [comment]
Understandable of course.

**Comment by roastt** [comment]
Well the newer DarkRP players will join and be like "erhhh derp no money printers or guyns fuk dis server", where as older ones use the commands. If I could help you, trust me.. I would.

**Comment by roastt** [comment]
So that workaround should fix it?

**Comment by FPtje** [comment]
Works for me

**Comment by Noiwex** [comment]
Stop sending people to fucking forum, jesus.

**Comment by FPtje** [comment]
You can come here and suck my dick instead if you want.

**Comment by roastt** [comment]
![well](http://i3.kym-cdn.com/photos/images/newsfeed/000/353/279/e31.jpg)

**Comment by roastt** [comment]
Also I think weapons and shipments tab is broken, the same fix applies?

**Comment by FPtje** [comment]
I thought they all worked after the fix

**Comment by roastt** [comment]
They do, my bad. Thanks!

**Comment by HDG-MrDeeJay** [comment]
Wtf falco, my net goes down for 5 hours and in that time a guy manages 
to ask another guy to suck him off via github wth man jeez.

**Comment by wiox** [comment]
:clock10:

**Comment by Deagler** [comment]
x

**Comment by FPtje** [comment]
Jesus christ fuck off already
