### ISSUE TITLE
Recent update error

### ISSUE THREAD

**Issue by Munchh** [FPtje/DarkRP#1948]
[ERROR] gamemodes/darkrp/entities/entities/darkrp_laws/init.lua:10: attempt to call field 'Copy' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/init.lua:10

**Comment by FPtje** [comment]
I honestly doubt they removed table.Copy.

**Comment by HDG-MrDeeJay** [comment]
They didn't. Otherwise my TTT server would be having a shit fit because 
of our weapon code.
