### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/DarkRP#1949]
[ERROR] lua/autorun/server/sv_chatfuncs.lua:152: Tried to use a NULL entity!
1. Send - [C]:-1
2. TellPlayer - lua/autorun/server/sv_chatfuncs.lua:152
3. fn - lua/autorun/server/sv_chatfuncs.lua:174
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

The Wallet resets every restart, & the scoreboard is screwed up. also im a black dude with no bones im that T man 

http://imgur.com/ATr3rK2

pls help ;(

**Comment by 00875** [comment]
sv_chatfuncs.lua is not in DarkRP repository. Some of your addons broke your server.

**Comment by NLGBrian** [comment]
so what to do ^-^

**Comment by HDG-MrDeeJay** [comment]
Its not DarkRP. So go complain to the right people.

You can find out by opening the file the error lists, a lot of shithead 
developers feel the need to title their turds.
