### ISSUE TITLE
Door system doesn't work!

### ISSUE THREAD

**Issue by xpuska513** [FPtje/DarkRP#1951]
After GMOD update i updated a DarkRP gamemode but, i have this error:
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:152: Table doesn't contain any valid entities!
  1. Send - [C]:-1
   2. updateDoorData - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:152
    3. setKeysNonOwnable - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:18
     4. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:354
      5. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:291
       6. setUpNonOwnableDoors - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:347
        7. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:152
         8. tableExists - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:375
          9. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:181
           10. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:186
            11. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:150
             12. Call - gamemodes/darkrp/gamemodeTimer Failed! [Simple][@gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua (line 154)]

And door groups gonna clear after restart.
P.s I'm very bad in englishD:

**Comment by MStruntze** [comment]
Update your server
