### ISSUE TITLE
Categories Glich

### ISSUE THREAD

**Issue by EncryptedGenesis** [FPtje/DarkRP#1953]
I tried the darkrp forums but it seems this might be a Darkrp glitch. I already did the fix of #1937 
I am trying to make categories for two jobs that have access to shipments. One is a gun dealer and the other a salesman. I am using this for the canSee
/***********************************************
General Salesman
***********************************************/
DarkRP.createCategory{
    name = "Health",
    categorises = "shipments",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = function(ply) return ply:Team() == TEAM_GENERAL end,
    sortOrder = 1,
}

DarkRP.createCategory{
    name = "Locksmith",
    categorises = "shipments",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = function(ply) return ply:Team() == TEAM_GENERAL end,
    sortOrder = 2,
}

/***********************************************
Shipments
***********************************************/

DarkRP.createCategory{
    name = "Pistols",
    categorises = "shipments",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = function(ply) return ply:Team() == TEAM_GUN end, 
    sortOrder = 1,
}

DarkRP.createCategory{
    name = "Rifles",
    categorises = "shipments",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = function(ply) return ply:Team() == TEAM_GUN end, 
    sortOrder = 5,
}

DarkRP.createCategory{
    name = "Shotguns/Snipers/Submachine Guns",
    categorises = "shipments",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = function(ply) return ply:Team() == TEAM_GUN end,
    sortOrder = 225,
}
Gun Dealer has these categories created.
![ss 2015-05-31 at 03 41 04](https://cloud.githubusercontent.com/assets/12679997/7949358/58bc4958-094a-11e5-8aca-9ea9dc1fe2c4.png)

The salesman still has the rifles and any other categories that I add to the gun dealer.
![ss 2015-05-31 at 03 42 00](https://cloud.githubusercontent.com/assets/12679997/7949362/60505f06-094a-11e5-816b-2875753e5142.png)

**Comment by FPtje** [comment]
The only odd thing I see here is that the salesman can see the rifles category. You probably haven't disabled the DarkRP default rifles category.
