### ISSUE TITLE
Edit FAdmin Groups is not fixed for me....

### ISSUE THREAD

**Issue by Lion5** [FPtje/DarkRP#1954]
I downloaded The new darkrp after where it was fixed but the problem is still there.... i looked in the fadmin files and there are the same from the fixed darkrp....
here are some images from the problem

http://imgur.com/e4D2ZnK
http://imgur.com/nB2fX7J

I restarted my server a few times but it doesnt work

**Comment by FPtje** [comment]
Something is messed up in your database.
