### ISSUE TITLE
Error stuntick

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#1957]
[ERROR] gamemodes/darkrp/entities/weapons/stunstick/shared.lua:92: attempt to index local 'attachment' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/stunstick/shared.lua:92

**Comment by Bo98** [comment]
What player model are you using when you get this?

**Comment by LordiAnders** [comment]
@Bo98 
You need to make sure that the attachment is valid first
Just make a basic if statement that checks if the attachment variable is valid before proceeding

If you dont do this, some custom playermodels, and even in rare cases, this may generate errors

**Comment by Bo98** [comment]
I realise this but I'm interesting in what other player models are using as weapon animation attachments or whether animations simply don't work with them.

**Comment by TylerGeorges** [comment]
By the way, it's referring to this line:
```local pos = attachment.Pos + (attachment.Ang:Up() * 16) + (attachment.Ang:Right() * -3) + attachment.Ang:Forward() * 4```

**Comment by 00875** [comment]
Has no errors with custom and default playermodels

**Comment by TylerGeorges** [comment]
It might just be on @matiasg90 's server. Would be easier if we had an answer to @Bo98 's question.

**Comment by 00875** [comment]
@TylerGeorges Custom = Ponys

**Comment by matiasg90** [comment]
Custom model pack
http://steamcommunity.com/sharedfiles/filedetails/?id=427328410

![errores](https://cloud.githubusercontent.com/assets/9421841/7974489/7fe81c3e-0a38-11e5-925c-1270a2adf4a2.jpg)
super spam errors 500kb

**Comment by TylerGeorges** [comment]
Will this do?:
```
function SWEP:DrawWorldModel()
	self:DrawModel()
	local attachment = self:GetOwner():GetAttachment(self:GetOwner():LookupAttachment("anim_attachment_rh"))
	local pos = attachment.Pos + (attachment.Ang:Up() * 16) + (attachment.Ang:Right() * -3) + attachment.Ang:Forward() * 4
	if attachment:IsValid()
		if CurTime() <= self:GetLastReload() + 0.1 then
			cam.Start3D(EyePos(), EyeAngles())
				render.SetMaterial(Material("sprites/light_glow02_add"))
				render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
			cam.End3D()
		end
	end
end
```

This is the original function:
```
function SWEP:DrawWorldModel()
	self:DrawModel()
	if CurTime() <= self:GetLastReload() + 0.1 then
		local attachment = self:GetOwner():GetAttachment(self:GetOwner():LookupAttachment("anim_attachment_rh"))
		local pos = attachment.Pos + (attachment.Ang:Up() * 16) + (attachment.Ang:Right() * -3) + attachment.Ang:Forward() * 4
		cam.Start3D(EyePos(), EyeAngles())
			render.SetMaterial(Material("sprites/light_glow02_add"))
			render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
		cam.End3D()
	end
end
```

If this fixes it, I'll make a pull request.

**Comment by matiasg90** [comment]
I found the playermodel causing the error

![poli](https://cloud.githubusercontent.com/assets/9421841/7974586/ca5c0c48-0a39-11e5-9fd6-9bd0ba0a566a.jpg)

**Comment by TylerGeorges** [comment]
Do the animations still work? I think it's just something wrong with the playermodel.

**Comment by matiasg90** [comment]
9 months ago I use the playermodel and mistakes never happened.
I do not fix your code

**Comment by TylerGeorges** [comment]
"I do not fix your code"? I don't understand what you mean by that.

**Comment by 00875** [comment]
Huh. If attachment is nil, pos will fail again before you do IsValid()

**Comment by 00875** [comment]
@TylerGeorges code will fail because you doing IsValid() after error 'local pos ='

**Comment by TylerGeorges** [comment]
@00875 Should I put the `pos` variable inside the `CurTime() <= self:GetLastReload() + 0.1` if statement?

**Comment by matiasg90** [comment]
temporary solution :/

function SWEP:DrawWorldModel()
	self:DrawModel()
	if CurTime() <= self:GetLastReload() + 0.1 then
		local attachment = self:GetOwner():GetAttachment(self:GetOwner():LookupAttachment("anim_attachment_rh"))
	--	local pos = attachment.Pos + (attachment.Ang:Up() * 16) + (attachment.Ang:Right() * -3) + attachment.Ang:Forward() * 4
		cam.Start3D(EyePos(), EyeAngles())
			render.SetMaterial(Material("sprites/light_glow02_add"))
		--	render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
		cam.End3D()
	end
end

**Comment by 00875** [comment]
```
function SWEP:DrawWorldModel()
	self:DrawModel()
	if CurTime() <= self:GetLastReload() + 0.1 then
		local attachment = self:GetOwner():GetAttachment(self:GetOwner():LookupAttachment("anim_attachment_rh"))
		if attachment != nil then
			local pos = attachment.Pos + (attachment.Ang:Up() * 16) + (attachment.Ang:Right() * -3) + attachment.Ang:Forward() * 4
			cam.Start3D(EyePos(), EyeAngles())
				render.SetMaterial(Material("sprites/light_glow02_add"))
				render.DrawSprite(pos, 32, 32, Color(255, 255, 255))
			cam.End3D()
		end
	end
end
```

**Comment by Bo98** [comment]
@matiasg90 Could you tell me specifically which model in that pack causes the issue in case there's an attachment I'm missing.
