### ISSUE TITLE
DarkRP 2.6.1 causes all addons on my server to crash

### ISSUE THREAD

**Issue by Hemebru** [FPtje/DarkRP#1959]
Ok, so after I updated to DarkRP 2.6.1 from DarkRP 2.6.0, ALL my plugins (workshop and in addons folder) keep crashing and giving me a spam of error msgs flooding the console. When I join the server, nothing works, Im just there in the map I use and I can only walk around, nothing else. Can't open doors, f4 menu, etc.

Some example error messages in console:

[ERROR] addons/simpleweather/lua/simpleweather/sv_daynight.lua:213: attempt to call field 'Round' (a nil value)
1. DayNightThink - addons/simpleweather/lua/simpleweather/sv_daynight.lua:213
2. fn - addons/simpleweather/lua/simpleweather/sv_init.lua:71
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:108

[ERROR] gamemodes/darkrp/entities/entities/darkrp_laws/init.lua:10: attempt to call field 'Copy' (a nil value)
1. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/init.lua:10

[ERROR] gamemodes/base/entities/entities/env_skypaint.lua:18: attempt to call method 'NetworkVar' (a nil value)
1. unknown - gamemodes/base/entities/entities/env_skypaint.lua:18
2. Create - [C]:-1
3. fn - addons/simpleweather/lua/simpleweather/sv_daynight.lua:153
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:108

[ERROR] addons/simpleweather/lua/simpleweather/sv_daynight.lua:161: attempt to call method 'SetStarTexture' (a nil value)
1. fn - addons/simpleweather/lua/simpleweather/sv_daynight.lua:161
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:108

[Wiremod] lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:64: attempt to call field 'Inherit' (a nil value)
1. NewObject - lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:64
2. unknown - lua/entities/gmod_wire_egp/lib/objects/3dtracker.lua:2
3. include - [C]:-1
4. unknown - lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:81
5. include - [C]:-1
6. Initialize - lua/entities/gmod_wire_egp/lib/init.lua:14
7. unknown - lua/entities/gmod_wire_egp/lib/init.lua:18
8. include - [C]:-1
9. unknown - lua/entities/gmod_wire_egp/shared.lua:13
10. include - [C]:-1
11. unknown - lua/entities/gmod_wire_egp/init.lua:3

[Wiremod] lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:64: attempt to call field 'Inherit' (a nil value)
1. NewObject - lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:64
2. unknown - lua/entities/gmod_wire_egp/lib/objects/box.lua:2
3. include - [C]:-1
4. unknown - lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:81
5. include - [C]:-1
6. Initialize - lua/entities/gmod_wire_egp/lib/init.lua:14
7. unknown - lua/entities/gmod_wire_egp/lib/init.lua:18
8. include - [C]:-1
9. unknown - lua/entities/gmod_wire_egp/shared.lua:13
10. include - [C]:-1
11. unknown - lua/entities/gmod_wire_egp/init.lua:3

AND MANY MORE!!!

Can you please fix this, and in the mean time, send me the DarkRP 2.6.0 ZIP file? I can't find that anywhere and I'm loosing all my players due to this.

Regards,

**Comment by FPtje** [comment]
Ha! Not before you prove that the update to 2.6.1 caused everything.

**Comment by Bo98** [comment]
Likely is because of hitting a Lua file limit or something (ie. not DarkRP's fault).

Or an outdated anti-cheat addon.

**Comment by Hemebru** [comment]
The server was PERFECT before the update. It was running fine and a player told me about this new update, so when I updated DarkRP using the TCadmin panel, this error happened, and I also tried to use the github zip which doesn't change the result. FPtje, could you at least give me the DarkRP 2.6.0 zip? It might not be the update, but I want to make sure if what you are saying is correct.

**Comment by Hemebru** [comment]
@FPtje ^^

**Comment by Hemebru** [comment]
@Bo98 I use no anti-cheat addon, and I only have 14 addons and 40 addons in the workshop, which is nothing compared to other servers...

**Comment by FPtje** [comment]
That's no proof that I'm responsible. I'm not giving you anything.

**Comment by Hemebru** [comment]
@FPtje Other servers still have the darkrp 2.6.0 file, and its not hidden or anything, why can't you give it to me? Please? Im loosing all my players and I need to try everything to fix it.

**Comment by Hemebru** [comment]
@FPtje And I'm only asking for the darkrp.zip file, (2.6.0) version. You have the 2.4.3 version available, why not 2.6.0?

**Comment by FPtje** [comment]
Shit isn't backwards compatible with 2.4.3. Shit is with all later versions

**Comment by Hemebru** [comment]
@FPtje What harm would giving me the 2.6.0 zip do? All I need to do is test my server if it works, and then if it does, keep it, and if not, remove addons. Please be willing to help, I really appreciate how you have created DarkRP, but I want to continue using it.

**Comment by FPtje** [comment]
I don't have it and generating it is a waste of my time because the chance that it's actually DarkRP doing this is very small. You say updating to DarkRP did it. I highly doubt it and say it's more likely that you did something else and blamed everything on DarkRP.

**Comment by Hemebru** [comment]
@FPtje What good would blaming DarkRP do for me? All I know is that i've simply updated to DarkRP 2.6.1 and need your help for the 2.6.0 file and since you don't have it, then alright, thank you for your help....

**Comment by FPtje** [comment]
What good it does for you? Very simple: you use it to push the responsibility of breaking your server to me. You ask me to solve it for you by giving you an older version. 

That's bullshit and I won't take responsibility until it's been proven that I am responsible.

**Comment by Bo98** [comment]
Here's a nice simple way of seeing if any earlier errors are causing the ones you are posting:

https://github.com/FPtje/DarkRP/blob/master/HELP/Problem%20in%20DarkRP.txt#L49-L58

Post the pastebin links here

**Comment by FPtje** [comment]
Here's a picture of the latest DarkRP:
![2015-06-04_16-52-56](https://cloud.githubusercontent.com/assets/1202014/7986835/42d48e52-0ada-11e5-9cc2-7b83aa800135.jpg)
