### ISSUE TITLE
Prop Spawning Doesnt Work

### ISSUE THREAD

**Issue by Lion5** [FPtje/DarkRP#1960]
I want to spawn a prop but it doesnt spawn nothing and if i check the console there is nothing there.
I can use the tools or i can spawn guns, Other players on my server too... they just cant spawn props. If i want to spawn an entitie it works but i cant remove it....  i rejoined and restarted the server but nothing works.... i hope you can help me... 
ps... i checked the settings and the max propspawning is on 400

-Lion

**Comment by FPtje** [comment]
![2015-06-04_16-52-56](https://cloud.githubusercontent.com/assets/1202014/7986838/49cb26e4-0ada-11e5-9ad5-34f53103f915.jpg)

I can. Not DarkRP's fault.

**Comment by Lion5** [comment]
i dont know why it dont works i have the same configs and addons i everytime have but this time it doesnt work...

**Comment by FPtje** [comment]
Not a help forum

**Comment by Lion5** [comment]
i googled the problem and someone in the forum said "Open the admin settings and check if the prop spawning is eneabled" Hwo can i see the settings?

**Comment by FPtje** [comment]
Still not a help forum.

**Comment by Lion5** [comment]
can you give me a link to the help forum?

**Comment by FPtje** [comment]
http://forum.darkrp.com/

**Comment by Lion5** [comment]
thank you
