### ISSUE TITLE
Ammo / Vehicles / Food don't have category / sortOrder

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1968]
http://wiki.darkrp.com/index.php/DarkRP:Vehicles
http://wiki.darkrp.com/index.php/DarkRP:Ammo
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/hungermod/sh_init.lua#L33

**Comment by Bo98** [comment]
Reminds me to document food on the wiki.

**Comment by Partixel** [comment]
Also, the ammo wiki page isn't use table syntax, it's using arguments which I assume are deprecated

**Comment by Bo98** [comment]
It is, yes.

**Comment by FPtje** [comment]
They all have the default "Other" category. Documentation is a different problem.

Get documenting you li'l minions, yes

**Comment by Partixel** [comment]
Actually, Food has no category code at the moment

**Comment by Partixel** [comment]
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/hungermod/sh_init.lua#5
createFood doesn't add them to a category

**Comment by Partixel** [comment]
Food also doesn't have the default "Other" category as far as I can tell
