### ISSUE TITLE
No way to remove Entities / AmmoTypes / Shipments / GroupChat / Foods

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1969]

**Comment by FPtje** [comment]
Why do you want to remove these things?

**Comment by Partixel** [comment]
For my DarkRP editor GUI

**Comment by Partixel** [comment]
![image](https://cloud.githubusercontent.com/assets/2728862/8011909/d8467de4-0bb4-11e5-91ae-8ee4cf71f3c4.png)

**Comment by Partixel** [comment]
( The error is because the entity doesn't have a unique command )

**Comment by FPtje** [comment]
I remember solving this issue with someone who made an editor just like that. What happened since last time?

**Comment by Partixel** [comment]
It was me, you only made the remove function for jobs to make sure it worked

**Comment by Partixel** [comment]
Or something like that.

**Comment by Partixel** [comment]
Also need a remove function for GroupChat and Food

**Comment by Partixel** [comment]
A get function for the local functions would also suffice in these cases btw.

**Comment by FPtje** [comment]
Tested to the point where I confirmed they all remove things. I found out that removeJob didn't remove the chat commands. It now does. Check for bugs like that, they're easy to miss.

**Comment by Partixel** [comment]
Alright, thank you!

**Comment by Partixel** [comment]
Okay, removeEntity doesn't remove the entities command

**Comment by Partixel** [comment]
Nvm, I think I fked up :)

**Comment by Partixel** [comment]
Nvm again, I think I was right the first time, it's not removing the command.

I've got this:

```lua
for i, v in pairs(DarkRPEntities or { }) do
	DarkRP.removeEntity(i)
end
```

which removes all entities ( I checked it works ) yet when I create a new entity it errors as its command isn't unique

**Comment by Partixel** [comment]
Also, removeGroupChat doesn't decrement groupChatNumber:

```lua
local groupChatNumber = 0
```

**Comment by Partixel** [comment]
You get notifications after this is closed right? Or am I talking to myself?

**Comment by Bo98** [comment]
I get the notifications.

**Comment by Partixel** [comment]
Great, just the person I need! :P

**Comment by FPtje** [comment]
`groupChatNumber` isn't relevant for anything but the disabled defaults. It would be hard to figure out when it should decrement and when it shouldn't. I'm not touching `groupChatNumber`.

removeEntity *does* remove the commands, but it doesn't unregister them with the unique checker.

**Comment by Partixel** [comment]
Alrighty, is that something I would have to do on my end or is that something on your end?

**Comment by Partixel** [comment]
Nice, thanks a lot!
