### ISSUE TITLE
Error to do with configs

### ISSUE THREAD

**Issue by deadmonstor** [FPtje/DarkRP#1971]
[ERROR] gamemodes/darkrp/gamemode/config/jobrelated.lua:8: attempt to call field 'createJob' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/config/jobrelated.lua:8
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/gamemode/cl_init.lua:40

[ERROR] gamemodes/darkrp/gamemode/config/addentities.lua:1: attempt to call field 'createShipment' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/config/addentities.lua:1
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/gamemode/cl_init.lua:41

[ERROR] gamemodes/darkrp/gamemode/config/ammotypes.lua:31: attempt to call field 'createAmmoType' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/config/ammotypes.lua:31
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/gamemode/cl_init.lua:42

[ERROR] gamemodes/darkrp/entities/entities/darkrp_laws/shared.lua:10: attempt to call field 'declareChatCommand' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/shared.lua:10
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:1

[ERROR] gamemodes/darkrp/entities/entities/letter/shared.lua:12: attempt to call field 'declareChatCommand' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/letter/shared.lua:12
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/letter/cl_init.lua:1

[ERROR] gamemodes/darkrp/entities/entities/spawned_shipment/shared.lua:15: attempt to call field 'declareChatCommand' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/spawned_shipment/shared.lua:15
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/spawned_shipment/cl_init.lua:1

[ERROR] gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:34: attempt to call field 'textWrap' (a nil value)
  1. addLaw - gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:34
   2. func - gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:71
    3. Foldl - gamemodes/darkrp/gamemode/libraries/fn.lua:280
     4. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:71

Timer Failed! [Simple][@gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua (line 70)]

[ERROR] Unauthed player
  1. query - [C]:-1
   2. refresh - addons/ulx/lua/ulx/xgui/commands.lua:299
    3. unknown - addons/ulx/lua/ulx/xgui/commands.lua:388
     4. include - [C]:-1
      5. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:110
        7. fn - addons/ulib/lua/ulib/cl_init.lua:48
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by FPtje** [comment]
You messed up.

Not a help forum.
