### ISSUE TITLE
net.ReadType(net.ReadUInt(8)) should be removed

### ISSUE THREAD

**Issue by meepdarknessmeep** [FPtje/DarkRP#1974]
in quite a few instances, you do net.ReadType(net.ReadUInt(8))

this should however be removed since you use net.WriteType, which should figure out which type it is by itself, and not let the user guess how it writes it on the other side.

you should change all instaces of 
```
net.ReadType(net.ReadUInt(8))
```

to 
```
net.ReadType()
```

**Comment by FPtje** [comment]
Nitpicking

**Comment by meepdarknessmeep** [comment]
It's not nitpicking, I am rewriting net.Read/WriteType.

I need this to be standard so I can safely do it the right way.

If you don't change this then your gamemode will not work with the net addon, which will optimize a lot of the network functions

**Comment by Bo98** [comment]
Not against this, but do remember that the net.ReadType parameter only became optional in the last update so there will be quite a lot of addons out there with the same code.

**Comment by FPtje** [comment]
So I wasn't even wrong in doing this.

**Comment by meepdarknessmeep** [comment]
You weren't before the update, but now that it does it automatically and you are not getting the type of the var any differently... you should probably change it

**Comment by FPtje** [comment]
If you are to remake the `net.*Type` functions, why don't you make them backwards compatible? I don't see how you should make everyone else except for yourself responsible for the changes **you** want to make.

**Comment by meepdarknessmeep** [comment]
How am I supposed to make it backwards compatible if I don't write a uint of 8 bits to the message?

**Comment by meepdarknessmeep** [comment]
I've put this on facepunch: 
http://facepunch.com/showthread.php?t=1450721&p=47913460&viewfull=1#post47913460

**Comment by FPtje** [comment]
One really good idea is not changing those functions. The last update gave enough trouble when it broke backwards compatibility. 

You'll fucking kill gmod if **every** update breaks addons. Also, this is not a DarkRP specific issue. Go to the next update thread.

**Comment by Jitterclick** [comment]
-rep bad at lua and fat ppl play darkrp

**Comment by HDG-MrDeeJay** [comment]
Not sure if retarded or just trolling.

**Comment by Jitterclick** [comment]
Not sure if Facepunch has even tried to fix your problems or no? Am i right? Garry is a fat lazy fuck who plays too much fucking rust that fat oaf

**Comment by Jitterclick** [comment]
And don't be nice to the assholes at face punch, they deserve all the hate they can get.
Bad dev team

**Comment by HDG-MrDeeJay** [comment]
Are you just going to shitpost or are you gonna tell us something we 
don't know?

**Comment by Jitterclick** [comment]
So you agee Facepunch are assholes, including Rocketboy?

**Comment by HDG-MrDeeJay** [comment]
No, I agree you are a shit head.

**Comment by Jitterclick** [comment]
I are you are a shit head aswell. So another dickrider or fatass? What a Snowdog?

**Comment by HDG-MrDeeJay** [comment]
Nope, another dickhead in my ignore list.

**Comment by Jitterclick** [comment]
Bye Bye you must be fat or something picking on teenagers on git hub

**Comment by FPtje** [comment]
Fucked off

**Comment by Bo98** [comment]
Sounds like someone got their issue closes at Facepunch/garrysmod-issues

**Comment by HDG-MrDeeJay** [comment]
Nah, its just a fan boy right off the hipster train.

**Comment by Bo98** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/2098#issuecomment-112230568
