### ISSUE TITLE
Hitman Prices

### ISSUE THREAD

**Issue by McSniper1215** [FPtje/DarkRP#1977]
Seems as if hitmen can set prices over the limit that I set on darkrpmodifications/lua/config/settings.lua

Some are running around asking for 5,000,000

(2.5.1)

**Comment by deinemudda32** [comment]
Doesnt work for me.
(2.6.1)

**Comment by Partixel** [comment]
You aren't using the latest version so what do you expect FPtje to do?

**Comment by FPtje** [comment]
There's one thing I can do:
