### ISSUE TITLE
Foods don't have categories

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#1978]
Foods don't have categories

@ https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/hungermod/sh_init.lua#L5

**Comment by HDG-MrDeeJay** [comment]
Descriptions help...

**Comment by Partixel** [comment]
Well, is the title not enough? Foods don't have categories

**Comment by HDG-MrDeeJay** [comment]
its just i feel like I'm the only one who used that bug report template.

**Comment by Partixel** [comment]
I normally use it but this title kinda does explain the entire issue in detail

**Comment by FPtje** [comment]
Foods don't need categories imo.
