### ISSUE TITLE
The Sticks bug

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1981]
I updated to the newest version of DarkRP and the bug which is causing the player to switch to unarrest and arrest batton still exists.
It doesnt only happen on M9K Weapons that was unfortunately a wrong given information.

**Comment by HDG-MrDeeJay** [comment]
It wasn't "wrong", just simply not the entire truth.

Unfortunately, it was also all we were aware of at the time.

Just manually switch to whichever batton you dont have out, then 
quickswitch a few times, and it breaks the bug for now.

**Comment by Bo98** [comment]
You are the only person I am aware that has this bug after it was meant to have been fixed. Is it possible that you can setup a server with sv_allowcslua 1 so I can see if I can find what's up?

Or if you know another server IP that has an issue that you know is using the latest.

**Comment by MStruntze** [comment]
I seem to be having the same issue and my server has the latest updates to the stunstick and related.

It only happens sometimes but it's hell if you are unlucky as it happens continuously no matter what weapon you right click with.

**Comment by FPtje** [comment]
What do you mean "latest update with stunstick and related"? Do you need
the song?

**Comment by MStruntze** [comment]
No! I don't modify core files, I just mean that it's a few days since we applied the latest update, but as far as I remember the fixes to the stunstick were applied to our server (hope that makes sense).
I'll make 100% sure my server is fully up to date and report back if it still occurs.

**Comment by Bo98** [comment]
This line should be in both arrest_stick/shared.lua (line 134) and unarrest_stick/shared.lua (line 92).

https://github.com/FPtje/DarkRP/blob/master/entities/weapons/unarrest_stick/shared.lua#L92

Please double check if this is the case. It should have stopped this from happening

**Comment by MStruntze** [comment]
I can confirm that the line matches the one in the version I'm running.

**Comment by MStruntze** [comment]
It always switches to the unarrest stick when the issue occurs, if that's any help.

**Comment by Bo98** [comment]
Means it's happening in the arrest_stick.
