### ISSUE TITLE
Player spawning random and Frozen

### ISSUE THREAD

**Issue by Hodasboy** [FPtje/DarkRP#1983]
Hey,

We have got some issues with spawning for example after 10 minutes gameplay and 1 death you start to spawn on your death spot and Frozen (Any job taken). only way to get back moving is using ULX commands Freeze and Unfreeze. DarkRP itself doesn't give any errors on Console logs when starting server (watched carefully Web console when started to see every line it loaded).

**Comment by FPtje** [comment]
not a help forum.
