### ISSUE TITLE
Setting new spawns for ALL jobs

### ISSUE THREAD

**Issue by RhapsodySL** [FPtje/DarkRP#1989]
I'm requesting a feature to set new spawn points for all jobs, instead of just one job. Sometimes map spawnpoints are unsuitable, let it be by map design or what the server owner wants. If you have a lot of jobs, it's tedious to set them for each job. I'd like to have a feature to set custom spawn points that aren't job specific.

Alternatively, is there a utility I can use to do this already?

**Comment by HDG-MrDeeJay** [comment]
I think there is a way but it isn't easy.

There should be an easy way.

**Comment by FPtje** [comment]
This is beyond the scope of DarkRP.

**Comment by RhapsodySL** [comment]
Can you at least point me towards the code that's used for the spawn positions in DarkRP a so I can try to do it myself?

**Comment by HDG-MrDeeJay** [comment]
Dont modify core files.

**Comment by RhapsodySL** [comment]
I have no intention to. I was going to use the code and make it into an addon.

**Comment by FPtje** [comment]
How hard can it be to use PlayerSpawn and ply:SetPos?

**Comment by RhapsodySL** [comment]
For someone with no lua experience who wanted to experiment with it to see if I could somehow manage it? Very difficult.

**Comment by HDG-MrDeeJay** [comment]
Therefor what hope did you have of turning it into an addon in the first 
place?

**Comment by RhapsodySL** [comment]
Little, but I wanted to try and at least see where the code was. I don't think it matters what I can do or both, I'm just asking where that particular section of code is.

**Comment by gamingreaper1234** [comment]
Here is a piece of code I got from ChatGPT to help with this. You place it in the int.lua If you don't have one, you can just make one, then drop this script 

C:\Users\pruit\Desktop\gmod_server_2\steamapps\common\GarrysModDS\garrysmod\addons\darkrpmodification\lua\darkrp_customthings\init.lua
--------------------------------Spawn Code---------------------------------------------
local baseSpawnEnt = nil

hook.Add("PlayerInitialSpawn", "CreateSharedSpawnOnce", function()
    if not IsValid(baseSpawnEnt) then
        baseSpawnEnt = ents.Create("info_player_start")
        baseSpawnEnt:SetPos(baseSpawnPos)
        baseSpawnEnt:SetAngles(baseSpawnAng)
        baseSpawnEnt:Spawn()
    end
end)

hook.Add("PlayerSelectSpawn", "UnifiedSpawnWithOffset", function(ply)
    if IsValid(baseSpawnEnt) then
        -- Clone the position with a small random offset
        local clone = ents.Create("info_player_start")
        local offset = Vector(math.Rand(-32, 32), math.Rand(-32, 32), 0)
        clone:SetPos(baseSpawnEnt:GetPos() + offset)
        clone:SetAngles(baseSpawnEnt:GetAngles())
        clone:Spawn()
        return clone
    end
end)
----------------------------------------------------------------------------------------

**Comment by RhapsodySL** [comment]
Ten years late, but let me whip out my time machine and I'm sure the dickhead I was ten years ago will be overjoyed with your AI-generated code

**Comment by FPtje** [comment]
I'm surprised at the code spit out by the Ai. It's not how I would do it, but at a glance it looks like it should hypothetically work
