### ISSUE TITLE
ACT_VM_DEPLOY Animations for the weapons

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1991]
Lockpick, Stunstick, other Sticks doesnt have an Deploy animation.
Would be good to add though.

**Comment by Bo98** [comment]
IIRC when I redid the stick animations there was no deploy one for the model. I will recheck this though.

**Comment by FPtje** [comment]
The lockpick does have a deploy animation. The stunsticks don't because I really like the quick switching between the two arrest sticks.
