### ISSUE TITLE
AAAA HELP FADMIN IS DIED

### ISSUE THREAD

**Issue by Skyborder** [FPtje/DarkRP#1993]
Can you me Help?

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/serversettings/cl_init.lua:16: bad argument #1 to 'KeyValuesToTable' (string expected, got no value)

KeyValuesToTable - [C]:-1
    DoClick - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/serversettings/cl_init.lua:16
    unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_controls.lua:299

**Comment by deinemudda32** [comment]
"Can you me Help?"
Really?

**Comment by Skyborder** [comment]
No
I have the Anticheat QUAK and have this Remove,..
Is Perfekt :dancer: 

Danke dennoch Ute

**Comment by deinemudda32** [comment]
Better watch youre english.
And never use QUAC Anticheat. Awful coded.

**Comment by FPtje** [comment]
not a help forum.
