### ISSUE TITLE
F4 Menu Not Showing Up

### ISSUE THREAD

**Issue by th3reddevil** [FPtje/DarkRP#1994]
Whenever my users or I open up my F4 menu, I get this error:
attempt to index local 'modelView' (a nil value)
on line 270 of my F4 menu.
Here's the text on like 270:
modelView:SetSize(modelPanel:GetWide(), modelPanel:GetTall())

Please help me!

**Comment by FPtje** [comment]
Not a help forum

**Comment by HDG-MrDeeJay** [comment]
Well, use your head mate.

modelView doesn't exist, or is nil. Thats the problem, when it gets to 
L270, the developer expected modelView to contain an array of function, 
but it didn't.

Please consider taking a crash course on how to lua.1

**Comment by Partixel** [comment]
Also, posting the entire error would help
