### ISSUE TITLE
FPP is messing up --GMOD--

### ISSUE THREAD

**Issue by Desoros** [FPtje/DarkRP#1995]
http://gyazo.com/faa956b7704defc7cd0bb52a7fc0ad24
I've been having a problem, I can have the physgun protection off, then I can move everything, which I don't want. When I have the physgun protection on, I can't move anything. I'm writing my own DarkRP server and I've been trying to get FPP to work for hours now. I don't know if it's because I have an outdated version or what, but I really need some assistance on this one.

**Comment by FPtje** [comment]
Bad configuration, not a help forum

**Comment by Desoros** [comment]
I don't understand where I'm supposed to go with this

**Comment by HDG-MrDeeJay** [comment]
the help forum. It's linked in the repository's "README.MD" file, 
visable if you scroll down

**Comment by Bo98** [comment]
You are also told before you create an issue you know:

https://youtu.be/WmUBpZuizHI
