### ISSUE TITLE
DarkRP Can't connect to MySQL Server

### ISSUE THREAD

**Issue by Mateshi** [FPtje/DarkRP#1997]
I can't connect on MySQL of my server , or on MySQL on my PC

![mysql](https://cloud.githubusercontent.com/assets/13014256/8302136/711de8bc-1994-11e5-9e14-3f8e67fb1464.jpg)

(And , gmsv_mysqloo is installed correctly)

![sql](https://cloud.githubusercontent.com/assets/13014256/8302194/f65926fe-1994-11e5-88b6-f04c06495095.jpg)

![sql 2](https://cloud.githubusercontent.com/assets/13014256/8302195/f8ae42d6-1994-11e5-8483-bee360d062d0.jpg)

**Comment by FPtje** [comment]
Not a help forum.
