### ISSUE TITLE
Door Opening + ConCommand

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#1998]
There should be a delay for for closing and opening doors with the keys, because most of the players are abusing it.
Either they abuse the doors, with often pressing e to keep the door closed.
There should be a delay for opening and closing doors without the keys also.

**Comment by FPtje** [comment]
Immediate locking is a wilful decision because it's REALLY annoying if you think a door is locked, you walk away and find it isn't locked because you should have been looking at it longer.

Opening and closing doors is a map thing.
