### ISSUE TITLE
Big Error

### ISSUE THREAD

**Issue by 123op4u** [FPtje/DarkRP#1999]
[Black_MG|2|STEAM_0:1:75119282] Lua Error:
 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:296: attempt to call field 'declareChatCommand' (a nil value)
  1. declareTeamCommands - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:296
   2. unknown - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:657
 
Noone Can Do Chat Commands Noone Can Become A Job Noone Can Do Anything.
Except Shooting And Walking Only Thing Available.
Please Help Me.

**Comment by FPtje** [comment]
Not a help forum.
