### ISSUE TITLE
Happy Birthday DarkRP

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [FPtje/DarkRP#2000]
I warned you I would have my revenge Falco. (re #1000 )

**Comment by LennyPenny** [comment]
huh

**Comment by HDG-MrDeeJay** [comment]
A few years ago, Falco stole the 1000th issue when I was searching for a 
cool PR to do.

I swore revenge when he cheated, so here it is. Issue number 2000. Taken 
by me.

**Comment by Authorjames** [comment]
2000 is not special
3000 is
and 5000
and 7500
and 10000
you get it

**Comment by wiox** [comment]
i don't get it

**Comment by HDG-MrDeeJay** [comment]
Its not the number that is most significant here.

It's the fact I swore revenge.

**Comment by FPtje** [comment]
I cheated again.

**Comment by HDG-MrDeeJay** [comment]
Its under my name. It still counts as my issue

**Comment by FPtje** [comment]
You're just saying that.

**Comment by HDG-MrDeeJay** [comment]
nope

**Comment by Partixel** [comment]
You can't beat cheaters, every body knows that.

**Comment by HDG-MrDeeJay** [comment]
Some things do beat cheaters.

Among those things stand Time and Boredom.

**Comment by FPtje** [comment]
Further cheats can be explored.
