### ISSUE TITLE
[DarkRP]Random spawning and loading Freeman model

### ISSUE THREAD

**Issue by ars899** [FPtje/DarkRP#2003]
I spawn in unknow place of the map and i have a default model of Freeman. When i changing my job, same thing.
in console lua errors- 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:266: attempt to call method 'KeyPress' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:266

please help me!

**Comment by FPtje** [comment]
Not a help forum.
