### ISSUE TITLE
HTML repeatedly sends JavaScript "Unsafe JavaScript attempt to access frame" when F1 is pressed.

### ISSUE THREAD

**Issue by hydrochloric** [FPtje/DarkRP#2004]
When F1 is pressed, the error in [this pastebin](http://pastebin.com/yr0JTAjY) is sent to the console very often, and caused a significant FPS drop. This error was reproducible.

**Comment by HDG-MrDeeJay** [comment]
The only solution I have is more of a "sweep under the rug" issue, I'd 
do a pull request but I don't have access to my original code. I did 
some hacky overrides iirc.

As a temporary fix, you can try changing the f1 page to something 
simpler, maybe your community's website. There's a config var for it.

**Comment by HDG-MrDeeJay** [comment]
Wait, Falco, does the F1 menu completely load the html panel every time 
you press F1? Or does it remain active in the background?

**Comment by Bo98** [comment]
As for the "error", it was meant to have been silenced in 6135426. Are you using the latest DarkRP?

**Comment by FPtje** [comment]
He isn't
