### ISSUE TITLE
Darkrp Job Issue

### ISSUE THREAD

**Issue by TheCrazyGamer89** [FPtje/DarkRP#2005]
Ok, so i disabled all the default jobs so i can customize all the jobs from scratch. I put my custom jobs in: garrysmod/addons/darkrpmodification/lua/darkrp_customthings/jobs.lua and i put my custom categories in: garrysmod/addons/darkrpmodification/lua/darkrp_customthings/categories.lua . I made a new citizen, i replaced the default job with the new citizen job. I launch my server, and there are no jobs, the only thing is the joining server thing.

**Comment by FPtje** [comment]
Not a help forum

**Comment by HDG-MrDeeJay** [comment]
I wonder if we can get github to make the forum link flash in rainbow 
colors and do a mexican wave.

**Comment by Partixel** [comment]
People would just think you're really happy for gay marriage

**Comment by HDG-MrDeeJay** [comment]
when really we just want people to notice the forum.

**Comment by Partixel** [comment]
Exactly. And besides, every body knows that these guys can't read, else they wouldn't be posting here in the first place.

**Comment by HDG-MrDeeJay** [comment]
Welcome to Garry's Mod. May Satan have mercy on your soul.
