### ISSUE TITLE
Playerscale for specific maps

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#2007]
Instead or in advance to the ability for a global playerscale it would be very handy to set the scales specific for certain maps.

Some maps almost requiere to change the scale, but if you do this globally it could may have negative effects on other maps.

**Comment by FPtje** [comment]
Why in DarkRP though and not a third party addon?

**Comment by Neosinos** [comment]
Sorry, just seen this yet.
Uhm quite simple - because DarkRP added Playerscales some time ago - so if you add something, why not improve it? Usually when you add something you want it to work the best way it can - otherwise if you dont need it you drop it, like the Zombie Mod.
