### ISSUE TITLE
Darkrp jail not working! Help!

### ISSUE THREAD

**Issue by Creeperlover234** [FPtje/DarkRP#2009]
On my server when someone gets arrested the jail time does not appear the time still work but they will not get there weapons back and nor will they respawn! So then I must slay them for them to get out because I have suicide disabled on my server. Please help this bug is so annoying! Here is a screenshot while waiting for the 120 seconds to go through: http://imgur.com/6Bgkj3w (Also notice how there is no jail time at the bottom)

this is after I waited 120 seconds: http://imgur.com/Yb5O0Qr

Please help any help is appreciated!

**Comment by FPtje** [comment]
not a help forum. It's some HUD. Go to forum.darkrp.com to get more help.
