### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MainFighter** [FPtje/DarkRP#2010]
Posted this on the forums too but its more of a DarkRP issue I think.

Hello,

DarkRP is spitting out this error in the console a lot.

L 07/04/2015 - 21:47:03: Lua Error:
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:210: table index is nil
1. removeCustomEntity - gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:210
2. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:225

It also seems to link up with a problem I'm having with props falling threw the map and bouncing around, like the physics of all entities, props, players and everything goes insane.
I'm not certain if this error is causing the physics to go crazy though.

Thanks in advanced.

**Comment by FPtje** [comment]
Looks like bad configuration, as if an entity doesn't have its `cmd` field set or something.

**Comment by MainFighter** [comment]
Dunno,

I don't think I have done anything wrong with my config?
http://pastebin.com/t4GaMpPf

**Comment by FPtje** [comment]
Well when does it happen?

**Comment by MainFighter** [comment]
At random by the looks of it... 
I can't really narrow it down to anything when I tried.

Also could it be caused by the printers I am using, they add the entities threw a addon that doesn't go into darkrpmodification at all.

They are being added through the addon that has the file path to where the DarkRP.createEntity's are located
customizablemoneyprinters
|_ lua
    |_ darkrp_modules
        |_ customizablemoneyprinters
             |_ sh_init.lua

http://pastebin.com/ebd0H9rq
Thats the contents of the file.

**Comment by FPtje** [comment]
Run this in the **server** console every now and then:
```lua
lua_run for k,v in pairs(ent.GetAll()) do if v.DarkRPItem and not v.DarkRPItem.cmd then print("OFFENDING ENTITY", v, v:GetClass(), v.DarkRPItem) PrintTable(v.DarkRPItem) end end
```

As soon as it prints something, post it here.

**Comment by MainFighter** [comment]
Just ran it in the console and it returned the following:

L 07/05/2015 - 06:32:27: Lua Error:

[ERROR] lua_run:1: attempted to index global 'ent' (a nil value)
1. unknown - lua_run:1

[ERROR] lua_run:1: attempted to index global 'ent' (a nil value)
1. unknown - lua_run:1

[ERROR] lua_run:1: attempted to index global 'ent' (a nil value)
1. unknown - lua_run:1

**Comment by FPtje** [comment]
Damnit, error in the code. Use this instead:
```lua
for k,v in pairs(ents.GetAll()) do if v.DarkRPItem and not v.DarkRPItem.cmd then print("OFFENDING ENTITY", v, v:GetClass(), v.DarkRPItem) PrintTable(v.DarkRPItem) end end
```
This always happens.

**Comment by MainFighter** [comment]
It kinda just freezes the console and doesn't return anything besides the following:

> for k,v in pairs(ents.GetAll()) do if v.DarkRPItem and not v.DarkRPItem.cmd then print("OFFENDING ENTITY", v, v:GetClass(), v.DarkRPItem) PrintTable(v.DarkRPItem) end end...

Is that what its supposed to do?

**Comment by FPtje** [comment]
print any entities that should trigger the error.

**Comment by MainFighter** [comment]
Ok so its not printing anything.

Do I just wait for an error or something?

**Comment by FPtje** [comment]
the error happens when it's too late: when the entity has been removed. Run this instead, it should give a different error when it happens:
```lua
lua_run hook.Add("EntityRemoved", "anus", function(v) if v.DarkRPItem and not v.DarkRPItem.cmd then error(string.format("OFFENDING ENTITY: %s (%s)", v:GetClass(), tostring(v.DarkRPItem.cmd or "SHIT"))) end end)
```

**Comment by MainFighter** [comment]
Still nothing...

Um, one thing I did think of, could it be ServerGuard conflicting with DarkRP in some way?

**Comment by FPtje** [comment]
You have to wait for the error to happen with that code. Run again when the
server restarts.

**Comment by MainFighter** [comment]
Ah ok, I'll wait then.

I'll reply if something happens.

**Comment by MainFighter** [comment]
Got the following error, 3 times in a row.

L 07/05/2015 - 08:37:53: Lua Error: 
[ERROR] lua_run:1: OFFENDING ENTITY: spawned_shipment (SHIT)
  1. error - [C]:-1
   2. v - lua_run:1
    3. unknown - lua/includes/modules/hook.lua:84

Also another thing quickly I want to ask about.
In this here https://github.com/ThrivingVentures/ServerGuard/issues/152 do you know how to fix that? Or isn't it fixable.

**Comment by FPtje** [comment]
Some addon is setting the `DarkRPItem` of a shipment to the shipment table. That's what causing the error. I wouldn't have known that if you didn't debug it. Thanks.

The other error is not my problem. That's why I said:

> Don't ask me

in the other issue. That kind of issue is typically caused by some bug in an addon doing shit with the `PhysicsCollide` hook. DarkRP doesn't do anything with the `PhysicsCollide` hook, so please take that issue somewhere else.

**Comment by MainFighter** [comment]
Ok, I just thought it might have been colliding with DarkRP or something.

Anyway, how would I get around fixing the error?

**Comment by FPtje** [comment]
Simply update DarkRP.

**Comment by MainFighter** [comment]
Ok, cool thanks. :)
