### ISSUE TITLE
FA Admin Bug

### ISSUE THREAD

**Issue by PERPGamer** [FPtje/DarkRP#2011]
So when I go to add  rp_doorManipulation to the groups developer and owner it gives me this error: invalid arguments. I am running on the newest version of darkrp and haven't messed with any of it's code.  (picture http://i.imgur.com/MywsySG.jpg ) so I am thinking that it happens for everyone and not a bug on my side.

**Comment by FPtje** [comment]
I'm sorry, I can't reproduce the issue.
![2015-07-06_16-09-51](https://cloud.githubusercontent.com/assets/1202014/8524117/7b177af8-23f9-11e5-8458-2ca7c343ebbd.png)
Make sure you have the latest version of DarkRP. I remember fixing something similar quite a while ago.
