### ISSUE TITLE
Errors that should be errorNoHalt

### ISSUE THREAD

**Issue by Partixel** [FPtje/DarkRP#2013]
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/base/sh_createitems.lua#L1071

and

https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/base/sh_createitems.lua#L1038

Reasons:

1. Would allow the user to find more then one of these types of errors at once, where as at the moment you must fix the first error, run it again, fix the next error, run it again, fix the next error, etc
2. This prevents any valid jobs / entities / etc from being created if they are after the problematic one
3. The item could default to the "Other" category if it can't find the one it is set to instead of erroring and preventing the rest of the script from running

**Comment by FPtje** [comment]
Will lead to a spam of the same error for every entity that has a non-existing category.

**Comment by Partixel** [comment]
But they will eventually error anyway if the user fixes one?

**Comment by Partixel** [comment]
Could you not have a bool that is set to true once it errors so the script can continue running without spamming the errors? It seems a bit stupid to halt the entire script just because it is an invalid category that can easily be set to "Other"

**Comment by Bo98** [comment]
> Could you not have a bool that is set to true

The answer to everything.

https://github.com/FPtje/DarkRP/search?q=add+config+option&type=Issues&utf8=✓

**Comment by Partixel** [comment]
I didn't mean a bool in that way, I meant a local one, that when something would error gets set to true and then would prevent future invalid categories from printing the error

**Comment by Partixel** [comment]
local doErr = false

if not doErr then
doErr = true
errorhere
end

**Comment by FPtje** [comment]
That's basically what the error function does. It halts execution.

**Comment by Partixel** [comment]
The way I'm suggesting is, it will only print the error the first time via errorNoHalt so that the rest of the script is allowed to run but the error isn't spammed

**Comment by Partixel** [comment]
I can make a pr to show you what I mean because I'm obviously not great at explaining things

**Comment by FPtje** [comment]
In generic sense I was most worried about the error state DarkRP is in after that error occurs. When not halting execution, the custom item will be created and registered. After that other custom items can be added as well. It looks like everything about the custom item will still work, except for the category. We'd have to be very careful that suit doesn't start erroring in totally different places.

**Comment by Partixel** [comment]
Would defaulting to "Other" in this case not solve any potential errors?
