### ISSUE TITLE
DarkRP Issue

### ISSUE THREAD

**Issue by nichlasholm** [FPtje/DarkRP#2014]
I have this problem on my server:

[ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua" on line 20.
The best help I can give you is this:
 
Corrupt team: Citizen!
This job does not have a unique command.
 
Hints:
	- There must be some other job that has the same command.
	- Fix this by changing the 'command' of your job to something else.
 
The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 20
	2. [C] on line -1
	3. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 131
	4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 142
	5. gamemodes/darkrp/gamemode/cl_init.lua on line 47
------- End of Simplerr error -------
 
  1. error - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/libraries/simplerr.lua:467
    3. error - gamemodes/darkrp/gamemode/libraries/fn.lua:80
     4. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:615
      5. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:20
       6. doInclude - [C]:-1
        7. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:131
         8. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:142
          9. unknown - gamemodes/darkrp/gamemode/cl_init.lua:47

- I dont know how to fix it, i cant find the error.... Please help me

**Comment by Velkon** [comment]
Can you not read?

**Comment by FPtje** [comment]
Not a help forum
