### ISSUE TITLE
hideHUDElements doesn't seem to work

### ISSUE THREAD

**Issue by NamefuI** [FPtje/DarkRP#2017]
hideHUDElements doesn't seem to work, when I set e.g. DarkRP_Hungermod or DarkRP_Agenda to true, it doesn't hide the hungermod bar nor the agenda. And yes, I did everything properly, I pasted the code correctly from cl_hudreplacement.lua

**Comment by fruitwasp** [comment]
Paste the code you pasted. In what file did you put the code in?

**Comment by NamefuI** [comment]
It's actually the cl_hudreplacement.lua file in darkrpmodification/darkrp_modules
http://pastebin.com/wsGYSbMT

**Comment by fruitwasp** [comment]
Can't reproduce. Head over to the forums for help.

**Comment by FPtje** [comment]
Thanks for trying it.
