### ISSUE TITLE
IsSuperAdmin inconsistency on listen server

### ISSUE THREAD

**Issue by SimonSchick** [FPtje/DarkRP#2025]
Clean install, no other addons.

Listen server(2 slots) with LocalPlayer being host:
(Please excuse the varying player id, was always me)
````
lua_run print(Player(39):GetUserGroup())...
admin
lua_run_cl print(LocalPlayer():GetUserGroup())
admin
lua_run print(Player(39):IsSuperAdmin())...
true
lua_run_cl print(LocalPlayer():IsSuperAdmin())
false
````

In the single player session with no changes:

````
lua_run print(Player(41):GetUserGroup())...
user
lua_run_cl print(LocalPlayer():GetUserGroup())
user
print(Player(41):IsSuperAdmin())...
true
lua_run_cl print(LocalPlayer():IsSuperAdmin())
true
````

I check the source and see that you overwrote IsSuperAdmin, can you please look into this?

**Comment by Bo98** [comment]
Does ply:IsListenServerHost() only work serverside or something?

**Comment by SimonSchick** [comment]
````
] lua_run_cl print(LocalPlayer():IsListenServerHost())

[ERROR] LuaCmd:1: attempt to call method 'IsListenServerHost' (a nil value)
  1. unknown - LuaCmd:1
````

**Comment by SimonSchick** [comment]
Accidently closed, please ignore.

**Comment by Bo98** [comment]
I'll go fix the wiki then.

That'll also be the reason this is happening. FAdmin's IsSuperAdmin will always return true for the listen server host but it doesn't clientside as it can't detect for it right now.

**Comment by SimonSchick** [comment]
Couldn't you work around this by signaling the client that he's the listen server host?

I know it's not ideal, but still better than the current situation.

**Comment by xaviergmail** [comment]
http://wiki.garrysmod.com/page/game/IsDedicated  and EntIndex 1?

**Comment by SimonSchick** [comment]
````
print(not game.IsDedicated() and Player(3):EntIndex() == 1)
true
````

Assuming the index being 1 for the host is always true, this seems like a good solution.

**Comment by FPtje** [comment]
The first player is always EntIndex 1, even on dedicated server.

**Comment by FPtje** [comment]
Also, game.IsDedicated always seems to return false on the client.
