### ISSUE TITLE
What block HUD on gmod_camera?

### ISSUE THREAD

**Issue by gmodmania** [FPtje/DarkRP#2027]
On previous versions darkrp hud doesn't block on gmod_camera, now its blocked, where block code is?
Thanks!

**Comment by FPtje** [comment]
Not a help forum.

**Comment by gmodmania** [comment]
You code this shit gamemode not me!

**Comment by HDG-MrDeeJay** [comment]
Kid, if you can't figure it out yourself, or are too stupid to read, 
then just get off your computer now and never turn it on again. You 
would be doing the world a favor cunt.

**Comment by Bo98** [comment]
https://www.youtube.com/watch?v=WmUBpZuizHI

**Comment by HDG-MrDeeJay** [comment]
![Image: How to read in 144p](http://i.gyazo.com/3e3d377eafe936002606b5b84fba645c.png)

Even in 144p and without my glasses, I can still see clear as crystal that @gmodmania is a fucknut
