### ISSUE TITLE
Shipments Not Working

### ISSUE THREAD

**Issue by AutoJukebox** [FPtje/DarkRP#2028]
So i decided to add shipments to my darkrp server and they don't seem to show up and my shipments tab is greyed out and i get no errors...

I have NOT edited any core files so i'm not sure what's causing it.

here's my shipments.lua
http://pastebin.com/y3umpELV

**Comment by FPtje** [comment]
Not a help forum

**Comment by AutoJukebox** [comment]
Well since i just updated to 2.6.1 it has to be a DarkRP issue....

**Comment by FPtje** [comment]
DarkRP still works here.
