### ISSUE TITLE
onOOCMessage + onPrivateMessage + onLocalMessage hooks

### ISSUE THREAD

**Issue by meepdarknessmeep** [FPtje/DarkRP#2029]
This would be a great addition (hopefully clientside, and only works when they are in the vicinity)

This would be great for filtering things in chatboxes automatically and no hacky things

**Comment by FPtje** [comment]
Why should I call three hooks within the existing chat hooks?

**Comment by meepdarknessmeep** [comment]
So we can filter specific messages differently, like if we want to filter ooc clientside we could do it easily with a button in a chatbox

**Comment by FPtje** [comment]
The chat hooks you need are there. No need to make more hooks for specific chat commands.

**Comment by sirsavary** [comment]
Would it be possible to get a "type" parameter on the chat hook? So we can tell what type of chat it is (ooc, advert, private message, local area).

**Comment by FPtje** [comment]
Not clientside, the client doesn't have that information.

**Comment by meepdarknessmeep** [comment]
Could you make it have the information?

**Comment by FPtje** [comment]
No, that information is redundant.

**Comment by meepdarknessmeep** [comment]
How is it redundant? Having text saying (OOC) could mean more than just it being a message from another person in OOC chat. Is there another way to know if a message is OOC? If there is I would gladly like to know.

**Comment by FPtje** [comment]
The server sends what the client should show in chat. Sure, that contains the text "(OOC)" and the name of the player, but the client doesn't need the extra knowledge that the message came from the specific OOC chat command. That extra knowledge is therefore redundant.

**Comment by meepdarknessmeep** [comment]
It's not redundant if the client has no idea if it's OOC or not...
Anyways, is there a way to hook serverside for OOC, PM, local, etc messages?

**Comment by FPtje** [comment]
It **is** redundant because the client **does not have to know**.

There is a hook now.

**Comment by FPtje** [comment]
http://wiki.darkrp.com/index.php/Hooks/Server/onChatCommand

**Comment by meepdarknessmeep** [comment]
Well that's more helpful, thanks.
