### ISSUE TITLE
DarkRP.createVote oversight and backwards compatibility

### ISSUE THREAD

**Issue by Bo98** [FPtje/DarkRP#2030]
Way too long to paste into Steam chat:

DarkRP.createVote has a parameter for the "target" but does not have one for the "source". The demote system makes up for it using the extrainfo table:

https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/jobs/sv_jobs.lua#L301

However most uses of the target internally in the vote system would be much more suited for either the person who initiated the vote or both the source and target:

https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/voting/sv_votes.lua#L90-L98

The language strings associated refer to the person who initiated the vote rather than the target:

https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/language/sh_english.lua#L330 (The target of a demote vote really is the loser of the vote)

It will make even less sense with a canStartVote hook that I was in the middle of adding:

```lua
local canStart, callSuccess, message = hook.Call("canStartVote", DarkRP.hooks, newvote)
if not canStart then
	if callSuccess then
		newvote:callback(1)
	else
		DarkRP.notify(target, 1, 4, message or DarkRP.getPhrase("unable", DarkRP.getPhrase("create_vote_for_job"), ""))
		newvote:fail()
	end
	return
end
```
The target does not need to know that the vote could not be created - that is for the initiator who would, under the current system, be unaware of it because they are never told. This is confusing behaviour for both players.

A few possible options:

* Switch the purpose of the target parameter to be the source
  - Breaks/changes the functionality of DarkRP.destroyVotesWithEnt
  - Confusion over the naming of "target" in the returned vote info table in both DarkRP.createVote and the callback functions.
    * Renaming would break backwards compatibility
* Add a source/initiator parameter to DarkRP.createVote
  - It doesn't make sense for it to be after "extraInfo"
    * Could say that the order is already weird with excludeVoters being stuck between the success and fail callbacks.
  - Required parameters should be before the optional parameters
  - What about backwards compatibility? Default to the bad behaviour of target?
    * Would force the parameter to be optional which would leave the bad behaviour go by unnoticed.
* Look for it in the extraInfo table
  - It doesn't match the design of everything else. Extra info should be extra info, not required info.
  - Again with the defaulting.
* Create a new function and deprecating the old one
  - DarkRP.createVote is probably the best name?
  - If using the same implementation, the parameter should be enforced to prevent it defaulting to the old behaviour.
* Keeping the existing one but converting to a table based format (like DarkRP.createJob), **enforcing the requirement for a source/initiator field** and deprecating the old method
  - Possible clashes with the metatable function naming
  - Not enforcing the field in the new table format would let it default to the old, bad behaviour.

After this is done the vote module could even be expanded so the votes are not tied to a specific target. Currently if you want to create a vote with a generic question, you cannot without associating it with a target player. With the current implementation you could get a way with setting the target to anyone here, but the vote will be cancelled with calls to DarkRP.destroyVotesWithEnt which may not be what everyone wants.

I believe the problem originated back when voting system was only about one person - the job voting system. Now that this is not necessarily the case, the voting system needs to be adapted to be suitable for votes involving more than one party.

Just wanted an opinion on it before doing anything.

**Comment by FPtje** [comment]
I'd say look for it in the `extraInfo` table and default to target (option 3). It looks like I wasn't being amazing at designing software when I wrote that piece fo shit. Looks like I found out that I need the source later and just threw it in the extraInfo table as to not break backwards compatibility

Generic votes use target as the source instead of the extrainfo table. That's cheeki breeki, but it looks like option 3 has already been chosen.

**Comment by Bo98** [comment]
Would a small note in the extraInfo parameter suffice as far as documentation goes?

**Comment by FPtje** [comment]
sure

**Comment by Bo98** [comment]
Just realised it's documented as typeless (any type). Should I always check for a table and not Player type in case someone used it as a second target or something?

**Comment by FPtje** [comment]
always table
