### ISSUE TITLE
custom spawns messing up

### ISSUE THREAD

**Issue by NateDaBeast** [FPtje/DarkRP#2033]
So for some reason my custom spawns have broke.

Originally I set the spawns up on the map and for some reason they stopped working so I thought it was a bug so I just re did the custom spawns.

But now it happened again after I uploaded a new jobs.lua file and the jobs are I guess you could say switched up now.

As in my server is Star Wars Themed and the default job "Clone Recruit" should spawn in the training room on the map, but spawns in the engineering room.

Where are the custom spawns are saved too ?
Do you know what the problem is ?

**Comment by FPtje** [comment]
That just happens when you change jobs.

**Comment by NateDaBeast** [comment]
but it's not when people change jobs. just as soon as you join the game with the default job being in a total different place it puts you in a different place were another job spawns in.

Where could i find where the custom spawns are saved too ?
Or fix this problem..

**Comment by HDG-MrDeeJay** [comment]
When you set the custom spawns, DarkRP indexes them by the order in 
which they appear in the jobs file. If you are a fucking moron and add 
new jobs to the top of the file, each job gets punted further along in 
the queue, and the custom spawns are not updated to account for your 
terrible standards for job insertion.

If you don't want this to happen again: Add new jobs to the BOTTOM of 
your file EVERY TIME. If shit starts to get unorganized, lock the server 
for an hour, re-sort your jobs, and reset custom spawns.

Also, just to add, this isn't a help forum. http://forum.darkrp.com

**Comment by deadlyshot02** [comment]
Holy shit, this guy asks a simple quesiton in the ISSUES tab (were it should be), and 2 jerks start insulting him for no reason without even helping, wtf xD? Are you on your period guys?
