### ISSUE TITLE
RE: custom spawns messing up

### ISSUE THREAD

**Issue by NateDaBeast** [FPtje/DarkRP#2034]
Since you closed the issue Imagine you dont see the replies.

So continuing on how you said "This just happens when you change jobs"

I find this false because even with just joining the game and getting the default job you still don't spawn in the correct place.

So, do you know what could still be causing this

OR

Where are the custom spawns are saved too in the server files or whatever

**Comment by Partixel** [comment]
He does see the replies

**Comment by FPtje** [comment]
Not a help forum. 

By changing jobs I meant changing the jobs in the lua file.
