### ISSUE TITLE
Suggestion: Gun Lab

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2035]
Suggestion:
As the gunlab defaults sells a DarkRP standard weapon I would suggest to add a config value to change these gun to a different as none server to date is using standard DarkRP weapons and Im really not in the mood to change 2 lines of code every gun lab update.(did it so far, but forget to update to newest version(if there is one)).

**Comment by HDG-MrDeeJay** [comment]
I second this. Perhaps include the ability for the gun dealer to select 
a weapon, like pick a gun from a table of guns in the config or 
something, you could even turn it into a new like "jobs.lua" file, make 
a "gunlabs.lua" where you can add guns to it and specify the min/max 
price to each.

But that of course would be a ground up rewrite to the gunlab.

**Comment by deinemudda32** [comment]
Thats an better Idea, but its much difficultier to do.

**Comment by HDG-MrDeeJay** [comment]
Well not really I imagine. It's just that it would need some sort of GUI and I suck total horse shit when it comes to derma.

**Comment by deinemudda32** [comment]
Derma looks actually awfully.(the standard look of it).
Reminds me of windows xp.

**Comment by HDG-MrDeeJay** [comment]
Why do you think Falco took all that time to reskin it? Plus if you take the time to do it, it isn't that hard to reskin derma.

At least that's what my community's owner says.

**Comment by deinemudda32** [comment]
DarkRP Theme uses Derma functinos as far as I can see.
I suck at clientside stuff like HUDs so Its a pain in the ass to reskin it.

**Comment by HDG-MrDeeJay** [comment]
Oh huds are easy. It's just a pain in the ass to position shit using one screen, constantly alt tabbing and shit.

I just suck at making nice derma windows.

**Comment by FPtje** [comment]
Fuck this shit I'm taking the easy way out.

**Comment by HDG-MrDeeJay** [comment]
I'd call you lazy, but then again this is DarkRP... why bother creating 
anything nice when you already have Coderh-I mean Scriptfodder?

**Comment by deinemudda32** [comment]
Never buy something off scriptfodder, because creating something youreself is easier than buying shit from scriptfodder.
2 hours finding a beginner mistake is more disgusting than writing 50 lines of code.

**Comment by HDG-MrDeeJay** [comment]
Nah, sometimes you find real gems on there, but most of the time its utter shit.

Especially anything made by penguin or has p_ in its addon name. His DarkRP f4 menu is shit, his ULX Ban reason on disconnect doesn't work, his darkrp hud causes massive frame drop and his scoreboard is worse than garry's!

**Comment by deinemudda32** [comment]
You know DLogs?
Worst shit, I had to rescript the whole shit to get it even working.

**Comment by HDG-MrDeeJay** [comment]
Man that was heaps broken, I had to rescript half of it too. In the end when I realised I had rewrote half of it just to get it working, I deleted it and said to the owner and admins on the server that they would just "have to admin like we did in the stone ages: With effort."

**Comment by deinemudda32** [comment]
Actually I deleted 30% of all functions ^^, just because I could never fix em all.

**Comment by HDG-MrDeeJay** [comment]
I remember there was some shit in the unarrest/arrest logging functions 
that caused them to error out before players were given their loadouts 
and speed back. I rewrote that 5 times because some other coder kept 
reverting it saying "Oh there was an update so I just replaced it all"

**Comment by deinemudda32** [comment]
It was the sh_getweapon.lua.
If you have no weapons and you get arrested -> lua error, cause nil weapons.

**Comment by FPtje** [comment]
By the way guys, did you eat breakfast this morning?

**Comment by deinemudda32** [comment]
Nah.

**Comment by HDG-MrDeeJay** [comment]
Does a coffee with choc drinking powder and too much sugar count?

**Comment by deinemudda32** [comment]
I just took the sugar.

**Comment by HDG-MrDeeJay** [comment]
Hahaha RIP liquid breakfast's

**Comment by FPtje** [comment]
Jesus christ you cocks, breakfast is the most important meal of the day!

**Comment by deinemudda32** [comment]
Not if you slepd 2 hours.

**Comment by HDG-MrDeeJay** [comment]
Yes, and it requires approximately 1 cup of cereal and 2 cups of milk.

Both of which are not regularly stocked in my house because I'd rather 
sit in front of my computer all day and farm my money printers while 
KOSing anyone who comes within 5 feet of my base

**Comment by FPtje** [comment]
Cereal is good enough I reckon. I had 3 double sandwiches with peanut butter today.

**Comment by deinemudda32** [comment]
And I have to update my server.

**Comment by HDG-MrDeeJay** [comment]
I can't have sandwiches in the morning. I've been eating these 
sandwiches where its peanut butter, cheese, and mayonnaise... but now 
that I'm about twice the weight of the average autistic mlp fan, i kinda 
cant have them anymore.

Gotta have cruskets.

**Comment by deinemudda32** [comment]
I have autism.. ._.

**Comment by HDG-MrDeeJay** [comment]
So do I, which gives me a right to bag out on it.

**Comment by FPtje** [comment]
why the fuck would you put mayonaise on a sandwich? Sandwiches are healthy if you don't put god damn mayonaise on them.

**Comment by HDG-MrDeeJay** [comment]
It tasted nice. And there was this cool cartoon character on TV that always ate mayonnaise, he was so awesome he was a cow and a chicken merged together and he walked on his teats.

**Comment by FPtje** [comment]
what show is that? It wasn't this was it?
https://www.youtube.com/watch?v=oQJqQNzeg4A

**Comment by deinemudda32** [comment]
I go search a doctor.

**Comment by HDG-MrDeeJay** [comment]
Nah falco, it was something else. Bit more modern. The show involved an island of mutants and there were two absolute moron mutants and a town of intelligent mutants and a platypus.

The evil guy was this penguin ape and a cat octapus called Octocat

**Comment by HDG-MrDeeJay** [comment]
AH! It was called Spliced!

**Comment by FPtje** [comment]
just looked at the intro and I've never seen it before. Looks like a good premise for a show.

**Comment by deinemudda32** [comment]
I am gonna work on another M9K Rewrite (Which actually should work) ;).
I will open a new issue for a new issue. That sounded well.. weird.

**Comment by FPtje** [comment]
not just weird, I don't know what the fuck you're saying.

**Comment by HDG-MrDeeJay** [comment]
Well it certainly was entertaining growing up. Especially the mayo episode.

https://www.youtube.com/watch?v=sw1F7A0LcoE

But anyway, was fun chatting, i gotta go now. Good luck with ur M9k rewrite

**Comment by Bo98** [comment]
> a cat octapus called Octocat

GitHub?

(https://github.com/logos)

**Comment by HDG-MrDeeJay** [comment]
>GitHub?

No. 
![Image of Octocat](http://vignette4.wikia.nocookie.net/spliced/images/6/61/Octocat.png/revision/latest?cb=20120608015003)

**Comment by FPtje** [comment]
That episode is fucking amazing.

**Comment by HDG-MrDeeJay** [comment]
So is a lot of them. There's one where the bird on the 2 legged rhino's ass starts using telepathy to talk to and control other mutants. Pretty fucking crazy man.

**Comment by deinemudda32** [comment]
How old are you? :D That seems like a disney kids show.

**Comment by HDG-MrDeeJay** [comment]
I'm 20 years old. I'm positive Falco is older than me.

**Comment by deinemudda32** [comment]
Then Im 4 years yonger than you and not understanding why you'd watch this.
Nevermind.

**Comment by FPtje** [comment]
I'm 22.

**Comment by deinemudda32** [comment]
Wow. I feel a little bit young.

**Comment by Bo98** [comment]
Don't worry, I'm here.

**Comment by FPtje** [comment]
Are you really from 98, @Bo98?

**Comment by Bo98** [comment]
Yep.

**Comment by deinemudda32** [comment]
Brother?

**Comment by NamefuI** [comment]
What has this conversation turned into?

**Comment by HDG-MrDeeJay** [comment]
Something dead.

**Comment by NamefuI** [comment]
I'm talking about your casual conversation about breakfast :P

**Comment by HDG-MrDeeJay** [comment]
Oh that, well Falco asked if we had breakfast, and I answered.

**Comment by SnabbSpelare** [comment]
What the hell is all this shit? I necroed this mofo!
