### ISSUE TITLE
Suggestion: Mute Voicechat(Chat is as I can see already handled) on Death

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2036]
Suggestion:
I would suggest to add Voicemute to the current ChatMute function as every little 12 year old kid is whining on death.
Its a good feeling to kill a kiddy and mute it at the same time.

**Comment by FPtje** [comment]
Chat doesn't get muted when you die, and neither should voice.

**Comment by deinemudda32** [comment]
GM.Config.deadtalk = false...

**Comment by HDG-MrDeeJay** [comment]
I second this too. Or at least add a disclaimer in really small fine print.

Warning: Fineprint may not be available in your local areas. Disclaimers 
may vary. See your local admin for proper cancer intake advice.Cancer 
may not be terminal.

**Comment by FPtje** [comment]
shush

**Comment by HDG-MrDeeJay** [comment]
k

**Comment by deinemudda32** [comment]
Thank You :)
