### ISSUE TITLE
FAdmin

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2037]
I dont like that moderators are teleporting me as owner to a specified place.
I would suggest to use the immunity to dont let that happen.

Example:
Owner: Immunity 2 | Moderator: Immunity 1
 Moderator cannot target Owner but Owner can target Moderator

**Comment by HDG-MrDeeJay** [comment]
I'm certain this has been suggested and denied before.

Immunity doesn't affect teleporting, and so it shouldn't.

**Comment by deinemudda32** [comment]
Oh well, should I close it?

**Comment by HDG-MrDeeJay** [comment]
Probably...

**Comment by deinemudda32** [comment]
Sorry, for bothering :)

**Comment by HDG-MrDeeJay** [comment]
If you want to read more about it, its #1159 when it was last suggested.
