### ISSUE TITLE
Group Chat not working for Custom Teams?

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2039]
A few days ago I was made aware that Group Chats weren't working. The Changeling faction (Gangsters in Stock DarkRP's terms) wanted to raid the PD. They wanted to use Group Chat to co-ordinate their attack with each other, however they couldn't see each other's Group Chats, except if they're in the same Team. None of my Teams are named after the Stock DarkRP Jobs (there is no TEAM_MAYOR, TEAM_MOBBOSS etc.).

Tested with other Chat Groups, including the Royal Guards (CPs in Stock DarkRP terms), all of which weren't working either. Previously these had been working without issue, but I've only just become aware of this issue now and I'm unsure what the cause is. I thought it might've been Addons conflicting, so I removed any suspects, no dice.

However, I had a look in `disabled_defaults.lua` and changed the following...
```lua
DarkRP.disabledDefaults["groupchat"] = {
	[1] = true, -- Police group chat (mayor, cp, chief and/or your custom CP teams)
	[2] = true, -- Group chat between gangsters and the mobboss
}
```
...to `false` to re-enable them. This fixed jobs classed as CPs from being unable to see each other's Group Chats, so the Royal Guards and Prince/Princess (Mayor) now work fine, however Gangster-like jobs and other custom ones still don't work.

Here's a snippet of the Group Chats for the Royal Guard and Changeling factions:
```lua
GAMEMODE:AddGroupChat(TEAM_PRINCESS, TEAM_HEIR, TEAM_CAPTAIN, TEAM_ELITE, TEAM_QUARTERMASTER, TEAM_ROYALMEDIC, TEAM_GUARD)
GAMEMODE:AddGroupChat(TEAM_QUEEN, TEAM_ASSASSIN, TEAM_CHANGELINGMEDIC, TEAM_CHANGELING, TEAM_HR_CM)
```
Previously, they were:
```lua
DarkRP.createGroupChat(TEAM_PRINCESS, TEAM_HEIR, TEAM_CAPTAIN, TEAM_ELITE, TEAM_QUARTERMASTER, TEAM_ROYALMEDIC, TEAM_GUARD)
DarkRP.createGroupChat(TEAM_QUEEN, TEAM_ASSASSIN, TEAM_CHANGELINGMEDIC, TEAM_CHANGELING, TEAM_HR_CM)
```
But I reverted them to `GAMEMODE:AddGroupChat` to see if that would've fixed it, but it's exactly the same.

There's possibly something on my end conflicting, but I've not been able to find it if it is. My Group Chats use to work without issue entirely before too. My Server uses the Workshop version of DarkRP.

**Comment by FPtje** [comment]
This bug must have been there for ages

**Comment by Hazbelll** [comment]
Ah, so it is an issue with DarkRP then? I appended a "?" onto the end of the title as I had just asked another Server Owner to confirm if their Group Chats were working, which they said they do, both CP and Gangster-related jobs. Both however use the Stock DarkRP Team names on their Server, with extra, custom-made Teams added on.

**Comment by FPtje** [comment]
The problem is that DarkRP doesn't deal well with overlapping group chats. DarkRP has the following group chat:
```
People from the same team will always hear you
```

If you add the following group chat AFTER that default one:
```
The princesses can see the royal guards' and royal night guards' chat
```
(where "after" is arbitrary and decided by whether you are lucky or not)

the "same team" one will be looked at, but the other one won't. 

All jibber jabber, but I'm working on a fix.

**Comment by Hazbelll** [comment]
Makes sense. Thanks for the explanation and quick fix. Now I'm off to get the majority of my Server's content out of the Recycle Bin now that's settled..

**Comment by Hazbelll** [comment]
Tested fix, can confirm it works. Thanks again!
