### ISSUE TITLE
FPP Default Blocked re-added on every Server Restart

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2040]
Not sure if this is a bug or by design.

Basically, every time the Server gets restarted, the following will be re-added to their respective types on next startup, even when removed manually in-game or not present in the MySQLite/MySQL tables:
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/fpp/sv_fpp.lua#L23

From Line 23 down to the last line at 40. A few of those things I'd like to remove, but as they keep getting re-added on each Server Restart, my Admins cannot Physgun them (didn't set Physgun to ignore Blacklist for Admins because they can then Physgun Doors, prop_dynamics etc.), but I did set the Toolgun to ignore the Blacklist for Admins so they can at least remove anything needed in that list, but it's still a messy workaround.

**Comment by FPtje** [comment]
These things are not meant to be picked up. If you really hate it, you can make a DarkRPMod module that sets `FPP.Blocked[type][classname]` to nil.

**Comment by Hazbelll** [comment]
Understandable for such entities like `"chatindicator"`, `"fadmin_jail"`, `"meteor"` etc. but then things like `"darkrp_cheque"`, `"letter"`, `"money_printer"`, `"spawned_shipment"`, `"spawned_weapon"` etc. I see no harm in being picked up.

Yes, we don't want the Users to be able to pick these things up, Spawn them or Toolgun them, however these are owned by "World", therefore they cannot unless set in FPP so anyone can touch World Entities, which is then down to the Server Operator if they really want that or not. Even then Admins can "abuse" the ability to manipulate such entities, but that's up to the Senior Administration to deal with and is no different than having the Blacklist ignored entirely.

My reasoning is that such entities should perhaps be placed into the Blacklists once, just like the default blocked models are, then left up to the Server Operators whether they wish to remove them or not. However I respect if you don't agree with that and I'll instead do as you suggested.

**Comment by FPtje** [comment]
Alright, this shit is now only stored on first start, or when updating.

It might be that shit still resets when you're running MySQL. Please run this command in the SERVER console when that happens:
```
lua_run sql.Query("DELETE FROM FPP_BLOCKED1")
```

Apparently FPP loads shit from the SQLite database before the MySQL database, the cheeky bastard.

**Comment by FPtje** [comment]
I'll wait a couple of days before I upload this to the workshop. It's a pretty big update.

**Comment by Hazbelll** [comment]
Oh Falco, I could kiss you right now. Thank you kindly for taking the time to do this. I'll be sure to test it out and report back if I find any anomalies at all.
