### ISSUE TITLE
DarkRP buyfood Console Command Error

### ISSUE THREAD

**Issue by Neosinos** [FPtje/DarkRP#2042]
Its nonsense. But I guess it still shouldnt drop an error. Using DarkRP buyfood in Server Console drops this;

```lua
[ERROR] gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:154: attempt to index
  1. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:154
   2. unknown - lua/includes/modules/concommand.lua:54
```

**Comment by NamefuI** [comment]
It works fine for me, are you sure you've got hungermod enabled?

**Comment by FPtje** [comment]
![2015-07-28_10-12-27](https://cloud.githubusercontent.com/assets/1202014/8926597/4209d75a-3511-11e5-9437-375e1c7427aa.png)

**Comment by Bo98** [comment]
Think he's talking about dedicated server console (i.e. when ply is invalid).

**Comment by FPtje** [comment]
Even then the console is still an entity. The error is incomplete (missing which variable would be a non-table value) and I can't see what can go wrong in this code:

```lua
local function ConCommand(ply, _, args)
	if not args[1] then return end

	local cmd = string.lower(args[1])
	local arg = table.concat(args, ' ', 2)
	local tbl = DarkRP.getChatCommand(cmd)
	local time = CurTime()

	if not tbl then return end

	ply.DrpCommandDelays = ply.DrpCommandDelays or {}

	if tbl.delay and ply.DrpCommandDelays[cmd] and ply.DrpCommandDelays[cmd] > time - tbl.delay then -- line 154
		return
	end

        ....
```
tbl is a valid table, because `DarkRP.getChatCommand` only returns either nil or table, and nil is ruled out.

If `ply` couldn't be indexed, it would have been line 152 that errored. 
`ply.DrpCommandDelays` must be a table unless some other addon sets it to a non-table value.
`ply.DrpCommandDelays[cmd]` Is not being indexed on line 154, so that can't be the error either.

**Comment by Neosinos** [comment]
Simply only wrote 'DarkRP buyfood' in the dedi server console and this
error pops up. As said its nonsense, but its still a error.

Am Dienstag, 28. Juli 2015 schrieb Falco Peijnenburg :

**Comment by Bo98** [comment]
You apparently cannot write to a NULL entity unless it is the world entity (the real ent index 0).

```lua
> local a = Entity(8745) a.test = 0 print(a.test)...
nil

> local a = Entity(0) a.test = 0 print(a.test)...
0
```

This seems to be because the GetTable() returns no value:

```lua
> local a = Entity(8745) print(a:GetTable())...


> local a = Entity(0) print(a:GetTable())...
table: 0xe5c8c7e8
```

**Comment by FPtje** [comment]
Still, the console in a concommand callback should not be NULL.

**Comment by Bo98** [comment]
What should it be? It's been NULL since forever.

**Comment by FPtje** [comment]
I distinctly recall it being `Entity(0)`
