### ISSUE TITLE
FAdmin GUI Elements visible to Ranks without Necessary Privileges

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2043]
Confirmed to be an issue with two other Server communities I do Dev work for, plus my own. All Servers using Workshop DarkRP - latest release.

At random, members in ranks that don't have the `SetAccess` privilege will have the "Set access" FAdmin button appear for them in the Scoreboard. Luckily, it's purely cosmetic. I asked the Operator who had it visible for them on my Server to try setting themselves to the admin rank; "No access".

I set myself to operator to see if I'd have the button visible, but I didn't. I tried `/setaccess Hazbelll superadmin`; "No access". I asked my other staff on at the time to verify if they had the button visible, all of which said they didn't. I asked a few users too, same thing. I checked the FAdmin Rank privileges and they were all configured correctly. Only superadmin had SetAccess assigned to them.

As far as I can tell, this only happens to random members in the "operator" rank (comes as standard with ULX), but that's only based off reports received from members who could see the button. The operator rank has one too in FAdmin, inheriting from user, less immunity than an admin, all set up correctly and not been an issue at all until today.

**Comment by Hazbelll** [comment]
Updated the title. Just gotten further reports that various other GUI elements are visible for the operator rank. They see doors like you would with the `rp_doormanipulation` privilege and the "Add to/Remove from FPP blocked models" entries in the context menu of props you see if your rank inherits from superadmin.

As with the Set access button appearing when it shouldn't, all of these issues are purely cosmetic. They cannot change door ownership or add/remove models to/from FPP.

**Comment by FPtje** [comment]
Something is marking your players as superadmin clientside.

**Comment by Hazbelll** [comment]
I haven't added or changed anything that could cause that. Can't say the same for the other two communities however, although their symptoms were identical. As far as I can tell, this only happens to 1 or 2 players at random and is very rare. Unsure if from playing on the server in 1 session for so long or from first joining causes it, or even something else entirely. I've been unable to replicate it. Considering in all cases it's merely cosmetic (ranks can't touch things they shouldn't touch), it's not too big of a deal either.

My Server's been around since November last year though and it has only recently become a thing, so I'm stumped. FAdmin and ULX are set up correctly, always have been and I've got nothing else that toys with ranks.

**Comment by FPtje** [comment]
> I haven't added or changed anything that could cause that.

I have, though. Fixed now.

**Comment by Hazbelll** [comment]
Many thanks as always.
