### ISSUE TITLE
Admin chat command still says adminhelp

### ISSUE THREAD

**Issue by NamefuI** [FPtje/DarkRP#2044]
So the /adminhelp command is actually for the Admin chat, which is kind of confusing, it should be changed to /adminchat or /toadmins or /achat
Also regular users shouldn't be able to use it, it should be restried to admins and superadmins

**Comment by FPtje** [comment]
/adminhelp and /// are actually command for users to request help from the admins.

Like @ in ULX.

**Comment by NamefuI** [comment]
So why does it say Admin chat then? It's more useful to make admins communicate with each other.

**Comment by FPtje** [comment]
because you chat to the admins

**Comment by NamefuI** [comment]
Cmon baby, make it an actual admin chat, eh

**Comment by HDG-MrDeeJay** [comment]
Admins can use /adminhelp and /// to chat to admins.

It already is what you want it to be.

**Comment by NamefuI** [comment]
I still don't want regular players to use it. I guess I'll just edit the DarkRP module (no, I won't modify core files). Thanks anyways.

**Comment by FPtje** [comment]
Great idea, make it so players cannot message admins without the rest of the server knowing!

Great way to prevent any and all drama!

**Comment by NamefuI** [comment]
There's so many admin report scripts

**Comment by HDG-MrDeeJay** [comment]
There's so many reasons to prevent players from contacting admins for 
support using any and all approaches, especially the default one that 
comes with darkrp incase your genericadminmod doesnt exist.

And opposite day isn't a real event that takes place today..

**Comment by NamefuI** [comment]
I tried copying the module over to darkrpmodifcation and editing it, but it didn't work, so I just edited core files. Ahh, it feels so good.

**Comment by Neosinos** [comment]
http://corefiles.DarkRP.eu/

Am Donnerstag, 30. Juli 2015 schrieb Matthew Nameful :

**Comment by FPtje** [comment]
Oh yeah, be proud of it like an emo is proud of cutting themself.

**Comment by Partixel** [comment]
I listen to that song on repeat.

**Comment by LetsRaceBwoi** [comment]
@Partixel you're not the only one.

**Comment by HDG-MrDeeJay** [comment]
i want to see a rock remix.

Suppose I should get on with learning the guitar.

**Comment by LetsRaceBwoi** [comment]
or the FL studio?

**Comment by HDG-MrDeeJay** [comment]
Real music is played with hands, not buttons.

**Comment by FPtje** [comment]
> Real music is played with hands, not buttons.

Are you implying I was doing "something" with my hands while recording the vocals for that song? I mean I'm not denying nor confirming anything, but that suggestion is a bit of a stretch.

**Comment by FPtje** [comment]
To be clear: the vocals were recorded separately from the piano.

**Comment by LetsRaceBwoi** [comment]
FL Studio is a DAW.  You have to click buttons to make music in it unlike a piano where you use your hands to play the keys.  He wasn't implying anything :)

**Comment by FPtje** [comment]
I know what FL studio is, and I know that you can record shit it with an actual keyboard using physical midi cable.

I just used my keyboard, my phone's mic and audacit because I was too lazy to get FL studio. 

Also, if you don't use your hand to click buttons, what *do* you use?

**Comment by LetsRaceBwoi** [comment]
I know.

I use my fingers to click buttons...

**Comment by HDG-MrDeeJay** [comment]
I use my penis.

**Comment by LetsRaceBwoi** [comment]
ok.
