### ISSUE TITLE
Windows Lua Refresh Issue

### ISSUE THREAD

**Issue by Alig96** [FPtje/DarkRP#2047]
Unhandled Lua Refresh: [NAME:darkrp_modules/properties/sv_properties.lua] [TYPE: !UKNOWN]

Making an addon is a pain with this. Anything I can do to solve this?

**Comment by FPtje** [comment]
Not a help forum

**Comment by Alig96** [comment]
No I'm creating an addon, but the addon isn't re-loading after each change so I have to restart the map to make any changes

**Comment by FPtje** [comment]
#NoSimplerr# in a comment in the file. Now go to the help forum for further
help question. forum.darkrp.com.

**Comment by Alig96** [comment]
I thought it was a bug which is why I posted it, sorry! Thanks that worked.
