### ISSUE TITLE
errer

### ISSUE THREAD

**Issue by neithque** [FPtje/DarkRP#2049]
19:17:10 Lua Error: [ERROR] gamemodes/base/gamemode/player.lua:205: bad argument #1 to 'WriteString' (string expected, got no value) 1. WriteString - [C]:-1 2. PlayerDeath - gamemodes/base/gamemode/player.lua:205 3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:399

 also, i am using mysql with darkrp, sometimes for some players money resets to 20,000. It is rare but it happened on at least 10 occasions past year. Is this a problem with darkrp?

**Comment by FPtje** [comment]
Something is calling PlayerDeath with an inflictor that causes GetClass to return no value in the Base gamemode. That error is therefore from both sides outside the scope of DarkRP. I can't help you.

**Comment by FPtje** [comment]
And for the money resetting: I simply don't know, I don't have enough information.
