### ISSUE TITLE
Keys replaced by extra baton + right click issue

### ISSUE THREAD

**Issue by PtGaming** [FPtje/DarkRP#2055]
I'm fairly sure that this is unique to only our server, but just in case I'll report it anyway. We have an issue that sometimes players/admins spawn without keys. And instead a pistol that has taken the material and colour of a baton. It also acts like a baton. Only difference is it has no animation and a different model.

![2015-08-08_00008](https://cloud.githubusercontent.com/assets/5671141/9152003/675e184c-3e10-11e5-88d2-27351ece8d9d.jpg)
![2015-08-08_00009](https://cloud.githubusercontent.com/assets/5671141/9152004/6ca6418a-3e10-11e5-82a3-3903c3d085bb.jpg)
![2015-08-08_00010](https://cloud.githubusercontent.com/assets/5671141/9152008/6e90edce-3e10-11e5-81b5-6e4d4924b87f.jpg)

There is another issue that sometimes when we right click, our weapon is swapped out for an arrest/unarrest baton. Even when we're building, using a physgun. Trying to freeze a prop will occasionally swap the physgun for a baton and not even freeze the prop!
Unfortunately I have no screenshots to provide for this issue.

**Comment by NamefuI** [comment]
This is not a help forum and it's an issue caused by the server's developers, not DarkRP's developers. Post this issue on the respective forums of the community, not here.

**Comment by Bo98** [comment]
> There is another issue that sometimes when we right click, our weapon is swapped out for an arrest/unarrest baton.

You must be using an outdated DarkRP. This has been fixed already.
