### ISSUE TITLE
Entity meshs

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2056]
Suggestions:
Microwave: Explosion should do damage.

Money, Weapons, Ammo should be destroyable or there should be a config option for it atleast.
They should even show physic  on getting shot.

I don't want this changes for minge.
I want this changes, because users are fucking around with the rp items like shooting 100 mags on a money entity just to show a user where it lie.

**Comment by HDG-MrDeeJay** [comment]
Why shouldn't the explosion do damage? It exploded, it should damage people.

Besides, I thought you could change the [default money entity](https://github.com/FPtje/darkrpmodification/blob/master/lua/darkrp_config/settings.lua#L280), as well as the [weapons shipment class](http://wiki.darkrp.com/index.php/DarkRP:CustomShipmentFields) along with functions such as [ENTITY:OnTakeDamage(dmg)](http://wiki.garrysmod.com/page/ENTITY/OnTakeDamage) to do what you want.

**Comment by deinemudda32** [comment]
The Microwave doesnt do any damage. I meant it should do damage.

I dont want to modify core entities of DarkRP, because if some update appears I have to modify the shit every time again. Its just a thing which should exist.

**Comment by HDG-MrDeeJay** [comment]
Let me repeat myself. _Why_ *shouldn't* the explosion do damage? The keywords there are "why shouldn't".

Explain why the microwave shouldn't do damage to things around it when it blows up in a ball of destructive flames.

**Comment by HDG-MrDeeJay** [comment]
[You can also get away with replacing the microwave entities without ever touching the core files.](https://github.com/FPtje/darkrpmodification/blob/master/lua/darkrp_config/disabled_defaults.lua)

**Comment by deinemudda32** [comment]
The microwave at its current state doesnt damage anything.
The explosion is just a created effect. it doesnt even draw a scorch!

For youre last comment -> "I dont want to modify core entities of DarkRP, because if some update appears I have to modify the shit every time again. Its just a thing which should exist."

**Comment by HDG-MrDeeJay** [comment]
Oh, i see what you mean by the microwave. Derp, need my glasses. I guess I need to learn to read.

And like I said, replacing the entities without modifying existing files is easy. The modification addon is updated sparingly, and provides you with everything you need to disable any default entity. After that, you add a new entity into the modification addon, with a new name and your preferred features. For instance, if you use the OnTakeDamage function in your new entity to tally the amount of damage received, then tell it to remove itself if the damage exceeds a certain amount, and then tell your config to use your new entity instead of the default one... well you get the picture surely. Modifying core features without touching a core file, and without irritating Falco.

**Comment by deinemudda32** [comment]
Im very bad in speaking proffessional english.
To be completly clear.
I use the DarkRP Modification Addon, but I don't want to modify DarkRP Files, as if a update is released I have to update the file over and over.
I just dont have the time for that and I only want to change some physics things and add a damaging explosion to the microwave.
Thats not worth the trouble.

**Comment by HDG-MrDeeJay** [comment]
I'll be completely clear.

Replacing and disabling a default DarkRP entity is a FEATURE of DarkRP 
2.5+. Just be aware that once you replace the entity, the replacement 
entity is YOUR RESPONSIBILITY, not Falco's.

**Comment by deinemudda32** [comment]
I DON'T WANT TO EDIT THE ENTITIES AS THEY ARE NOT MINE!
I made several entities, but I don't want to change the DarkRP Entities, just because 1 simple line needs to be changed. I just was going to ask, if this line could get be changed or if you could add a config line as these functions are nearly very important 1. for the gameplay and 2. for the realisms.
Everyone is complaining about "RP is not that real!", but a microwave which doesnt deal damage on explode is completly real or entities which doesnt get physics damage.

**Comment by deinemudda32** [comment]
Whats about adding some dmginfo:physics to weapon entities or shipments ;)?

**Comment by FPtje** [comment]
Weapons and ammo shouldn't be destroyed on shot, they're too expensive for that.

And I don't know wtf you mean by "dmginfo:physics"

**Comment by deinemudda32** [comment]
I mean adding physics(not destroying) as youre right with the expensive part.
I meant TakePhysicsDamage()

**Comment by FPtje** [comment]
The blas function should take care of that.

**Comment by deinemudda32** [comment]
But it doesnt collide with bullets.

**Comment by FPtje** [comment]
Updating the physics engine is not my business. I don't know what you mean.

**Comment by deinemudda32** [comment]
function ENT:OnTakeDamage(dmginfo)
	self:TakePhysicsDamage(dmginfo)
end

**Comment by FPtje** [comment]
Right, I should have understood that earlier. Sorry about that.

**Comment by deinemudda32** [comment]
What about the guns etc.?
Too valueable?

**Comment by FPtje** [comment]
No, too lazy.

**Comment by deinemudda32** [comment]
So I guess it wont be added?

**Comment by FPtje** [comment]
shaddap

**Comment by deinemudda32** [comment]
oh well, thanks ;)

**Comment by LetsRaceBwoi** [comment]
the notifications... lmao
