### ISSUE TITLE
Loose money per percentage of current money

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2057]
I would suggest to add a config option to loose money on death by percentage.

**Comment by HDG-MrDeeJay** [comment]
[There's a hook for that.](http://wiki.garrysmod.com/page/GM/PlayerDeath)
[There's even a DarkRP function too!](http://wiki.darkrp.com/index.php/Functions/Player/Server/addMoney)
[And if you need any further help, there is even a forum dedicated to that.](forum.darkrp.com)

**Comment by deinemudda32** [comment]
I mean a config option, because its something that alot of players would want.
I myself could do this easily as this is some beginner shit.

**Comment by HDG-MrDeeJay** [comment]
I have never seen a DarkRP server use the drop money on death option, not since 2.5. Why would people want a percentage system if they don't want the money to drop in the first place?

**Comment by deinemudda32** [comment]
In this point youre completly wrong.
I only know servers myself, were the money actually drops.
I mean I want people playing some roleplay, not playing GTA Online.

**Comment by FPtje** [comment]
This is a diy thing.

**Comment by deinemudda32** [comment]
Okay, its just an idea.
