### ISSUE TITLE
Shipments

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2058]
If you press E on a shipment, then it creates a "spawned_weapon" entity, but some folks like me have the "durgz" mod enabled on the server.
So would it be possible to add a new argument to the shipment table for adding a custom entity that spawns above the shipment like the normal spawned weapon.

**Comment by HDG-MrDeeJay** [comment]
I'm writing a PR now for this

**Comment by HDG-MrDeeJay** [comment]
I was going to make a PR for this, but the amount of seemingly unrelated shit that needs changing just to add that field is incredible. This is a job for someone skilled and experienced like Bo98 or Falco, not me.
