### ISSUE TITLE
Serverside error

### ISSUE THREAD

**Issue by P4sca1** [FPtje/DarkRP#2059]
[ERROR] gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:78: attempt to index a string value with bad key ('x' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. SetPos - gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:78
     4. fn - addons/hitmanmenu2.1/lua/entities/hitmanphone/init.lua:73
      5. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

**Comment by FPtje** [comment]
Your hitman menu is retarded.

**Comment by Bo98** [comment]
Honestly the SetPos workaround could probably be removed now that it is fixed in GMod.

**Comment by FPtje** [comment]
I know, I already removed it in sublime, I've yet to commit it.
