### ISSUE TITLE
jail

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2060]
In jail, weapons should be stripped by default, prop spawning and tool using disabled

**Comment by FPtje** [comment]
Are you waiting for me to close your other issues before making new ones?

**Comment by deinemudda32** [comment]
A user complained :D

**Comment by FPtje** [comment]
Also, this is something you broke on your server. DarkRP already does all of these things

**Comment by deinemudda32** [comment]
Weapons doenst get stripped.
It only does block Spawns, not Toolgun shit etc.

**Comment by FPtje** [comment]
Bull fucking shit, you broke that

**Comment by deinemudda32** [comment]
I was wrong with Propspawns and Toolgun, Sorry. Didnt saw shared jail file.

But the weapons are a common problem.

**Comment by FPtje** [comment]
For fuck's sake I'll make a god damn screenshot when I'm done eating my
dinner.

**Comment by FPtje** [comment]
![2015-08-11_18-37-28](https://cloud.githubusercontent.com/assets/1202014/9203538/15133c76-4058-11e5-85bf-023acb030dd7.jpg)
Here you go you stubborn cock

**Comment by LetsRaceBwoi** [comment]
weapons do get stripped.  you probably broke darkrp, well done

**Comment by deinemudda32** [comment]
I meant the FAdmin Jail.

**Comment by FPtje** [comment]
Jesus Christ

**Comment by LetsRaceBwoi** [comment]
you never said fadmin jail

**Comment by deinemudda32** [comment]
Oh thanks for the reply, Mr. Obivious.
Yea next time Im gonna add a f before the Jail.

**Comment by deinemudda32** [comment]
By the way in Jail you can spawn props xD

**Comment by FPtje** [comment]
Again, that's you breaking shit. In FAdmin jail you cannot spawn props.

Unless of course you have an addon that returns true in `PlayerSpawnProp` before FAdmin gets to say no.

**Comment by deinemudda32** [comment]
In this case I actually meant the real jail.

**Comment by FPtje** [comment]
FOR FUCK'S SAKE

**Comment by FPtje** [comment]
HAVE A GOD DAMN SCREENSHOT FOR THE NORMAL JAIL

![2015-08-12_18-57-51](https://cloud.githubusercontent.com/assets/1202014/9230692/16c6973a-4124-11e5-9162-992b1a68f7e7.jpg)

**Comment by FPtje** [comment]
HAVE ANOTHER ONE FOR THE FADMIN JAIL
![2015-08-12_18-55-28](https://cloud.githubusercontent.com/assets/1202014/9230697/1fb09d96-4124-11e5-89ea-9ad2d8b9c525.jpg)


TELL ME, DO YOU SEE CANAL BARS?

**Comment by FPtje** [comment]
CANAL BARS FOR REFERENCE

![2015-08-12_19-00-33](https://cloud.githubusercontent.com/assets/1202014/9230767/73825d06-4124-11e5-8707-e06989727d73.jpg)

**Comment by deinemudda32** [comment]
Sorry, I had an outdated version of RP on my singleplayer game.

So
 
Jail -> Sleep Abuse

FJail -> Weapons


 :D

**Comment by FPtje** [comment]
You -> the inability to fucking communicate

**Comment by deinemudda32** [comment]
Asberger's Fault. Blame it, not me, okay me, but not it.

**Comment by FPtje** [comment]
I'd rather blame language barriers. Work on your English, seriously. Aren't you German? English is important, but even moreso for the internationally focussed country Germany is.

**Comment by deinemudda32** [comment]
I really try to, but I don't get the Grammar part.

**Comment by LetsRaceBwoi** [comment]
rude...

**Comment by deinemudda32** [comment]
Youre comments are rude.
They are posted nonsense.
Whats rude about it?

**Comment by LetsRaceBwoi** [comment]
i was defending you but now you can please just go.  there are probably no problems here and it's likely all on your server's end

**Comment by deinemudda32** [comment]
Oh I thought you were against me too.
Then, sorry and thanks.
In the internet its difficult to recognise who you mean, if you just write "rude...".

**Comment by HDG-MrDeeJay** [comment]
Dont you dare use aspergers as an excuse.

Also dont mind me, I'm just waking up and replying to some messages. 
Especially the fucked up ones like this one.

**Comment by deinemudda32** [comment]
Obviously i was trying to make a Bad joke you didnt understood.
