### ISSUE TITLE
Spawning as Joining/Connecting

### ISSUE THREAD

**Issue by konrad2503** [FPtje/DarkRP#2061]
### Description of the problem
Spawning as "Joining / Connecting"
Money got not saved
Money = ""

### How I can make the problem happen again
Just join a fresh installed DEDICATED Linux Server with darkrp with the NEWEST Update from Facepunchh

### Error log pastebin links
There was no Clientside Errors or Serverside Error

**Comment by FPtje** [comment]
Friend of mine had aWarn break everything.

DarkRP works fine for me.

**Comment by konrad2503** [comment]
I said Fresh install of DarkRP so no addons no other shit just darkrp!

**Comment by FPtje** [comment]
It still works fine for me.

**Comment by konrad2503** [comment]
Hmm do u have linux dedicated server? and the newest shitty update from faceshit?

**Comment by FPtje** [comment]
No and yes.

**Comment by LetsRaceBwoi** [comment]
yes and yes.  ubuntu 12.04, confirmed working

**Comment by konrad2503** [comment]
ok closed it was a little bug filezilla which not remove the directory just the visible directories!

**Comment by LetsRaceBwoi** [comment]
exactly.
