### ISSUE TITLE
stun sound on primary attack on dead players and spectators etc.

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2062]
the title explains.
primarty attack on a player which is dead makes noise

**Comment by FPtje** [comment]
Of course it does, that's how you taunt people and laugh over their corpse.

**Comment by deinemudda32** [comment]
I didnt mean ragdolls. I meant dead players!
With dead I mean the player hull of the dead player.

**Comment by FPtje** [comment]
That's close enough to the ragdoll usually. You can't use the ragdoll because that's rendered clientside.

**Comment by deinemudda32** [comment]
Well it sucks, because some users are abusing it to make noise.
And if you hit a clientside ragdoll, im 99.999% sure it does a sound too, because ragdolls are lieing usually on the ground.

**Comment by FPtje** [comment]
Death ragdolls don't exist on the server, so no, it doesn't make a noise.

**Comment by deinemudda32** [comment]
Im really stupid in talking, I should begin to make pushs..

It just sucks, that you can hit dead player hulls and no if a player got killed the corpe is usually never at the same spot!

**Comment by FPtje** [comment]
I don't get the "know if a player got killed" bit, but that last bit is a decent argument.

**Comment by deinemudda32** [comment]
With good grammar ->
No, if a Player got killed, then the Corpse is usually not a the same spot as the player hull!

**Comment by FPtje** [comment]
That is much clearer, thank you. Please for the love of god keep that grammar up.

**Comment by deinemudda32** [comment]
I'll try.
