### ISSUE TITLE
Workarounds

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2063]
I would suggest to remove the Workaround from line 107 - 119 as it doesnt work.
The Workaround is useless, because the Issue only appears if Player 1. spawns in the Map and Player 2. spawns on the Same Place, then Player 1. dies.

These Workarounds are just stupid, why should you fix other peoples stuff in a gamemodes file.

**Comment by FPtje** [comment]
> why should you fix other peoples stuff in a gamemodes file

Because the incompetence of other people is too often blamed on me
Because a released map cannot really be edited without a lot of hassle
Because it works in changing the way people think about how they make shit

**Comment by FPtje** [comment]
The workaround was removed because indeed it doesn't work perfectly, because no one uses the map anymore and because it could conflict with addons that don't want the player to be alive on first spawn.

**Comment by deinemudda32** [comment]
I just wanted to mention the conflict.
In fact I use this map and never had this sort of thing, except my server was full of players.

The DoorS Tool is not anymore used either ;)

**Comment by FPtje** [comment]
It probably still is.

**Comment by deinemudda32** [comment]
it broke like 4 versions ago, so I guess no.

**Comment by FPtje** [comment]
Some cunt will revive it.

**Comment by deinemudda32** [comment]
It was a shitty tool which noone did really use, except some shitty sandbox servers and its nothing for DarkRP.

**Comment by FPtje** [comment]
> It was a shitty tool which noone did really use

 I've seen plenty of servers use it

> its nothing for DarkRP

That's your opinion and I don't give a fuck about it, nor should any server owner.

**Comment by deinemudda32** [comment]
I just don't understand why anybody should add the function to spawn Doors, when DarkRP already has thousand of doors.

**Comment by FPtje** [comment]
That's your inability to acknowledge the existence of gm_construct,
gm_flatgrass, gm_bigcity and the idea that it might be nice for custom
bases to have doors as well.

**Comment by deinemudda32** [comment]
Yea as I said, Sandbox Servers.

**Comment by FPtje** [comment]
also, the inability to acknowledge the base of DarkRP.

**Comment by deinemudda32** [comment]
Well our opinions are different in this case.

**Comment by FPtje** [comment]
There's not much of an opionion about what DarkRP's base gamemode is.

**Comment by deinemudda32** [comment]
I didn't mean that, but DarkRP usually doesn't take place on GM_Construct or GM_Flatgrass.

**Comment by deinemudda32** [comment]
Oh and If I have more suggestions about DarkRP should I create 1 issue per ticket or a ticket with more issues, as it could suck to get thousands of notifications the whole day.

**Comment by FPtje** [comment]
Yes it fucking does
![2015-08-12_18-56-39](https://cloud.githubusercontent.com/assets/1202014/9230729/3fcf1cd8-4124-11e5-9b5d-84a2e0b40736.png)

What are you going to do now, tell me those servers are doing everything wrong or something?

**Comment by deinemudda32** [comment]
I just have to admit, youre right.

**Comment by NamefuI** [comment]
These servers are running on gm_ maps because they're test servers

**Comment by deinemudda32** [comment]
I know, but I didnt wanted to argue with him.

**Comment by Bo98** [comment]
BuildRP (runs DarkRP gamemode) servers exists and commonly use flatgrass/construct/bigcity. I've never played on one before though so I don't know what it's like.

**Comment by deinemudda32** [comment]
I'll try to connect tomorow :D

**Comment by HDG-MrDeeJay** [comment]
making a base of blast doors.

I may revive it.
