### ISSUE TITLE
Microwave - sorry

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2064]
The microwave doesnt draw a scorch.

local explosion = ents.Create("env_explosion")
explosion:SetPos(self:GetPos())
explosion:SetKeyValue("iMagnitude", "20")
explosion:Spawn()
explosion:Activate()
explosion:Fire("Explode", 0, 0)
local shake = ents.Create("env_shake")
shake:SetPos(self:GetPos())
shake:SetKeyValue("amplitude", "512")
shake:SetKeyValue("radius", "256")
shake:SetKeyValue("duration", "1.5")
shake:SetKeyValue("frequency", "255")
shake:SetKeyValue("spawnflags", "4")
shake:Spawn()
shake:Activate()
shake:Fire("StartShake", "", 0)

just add this instead of the Blast and Effect and it draws one.
(I like the shake!)

**Comment by FPtje** [comment]
I'd rather stick with the thing I implemented yesterday. Less code, less entity spawning, less hassle and less of a trace after a microwave is gone.
