### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/DarkRP#2069]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:380: attempt to perform arithmetic on field 'LastVoteCop' (a nil value)
  1. callback - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:380
   2. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:8
    3. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:162
     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by NLGBrian** [comment]
also the HP 25000

**Comment by NLGBrian** [comment]
when starting

**Comment by FPtje** [comment]
What is HP 25000?

**Comment by NLGBrian** [comment]
The health of the players

**Comment by FPtje** [comment]
and you blame that on DarkRP?

**Comment by FPtje** [comment]
Also, do you have AWarn?

**Comment by NLGBrian** [comment]
nope.
