### ISSUE TITLE
DarkRP - Ulx

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2073]
Since the update of DarkRP with FAdmin related things, players who get set a rank by the ULX Admin Mod, loose their rank after Reconnection, but in FAdmin the rank still stays.

**Comment by FPtje** [comment]
Yes, it's up to @Nayruden to implement CAMI now.

**Comment by deinemudda32** [comment]
Then probably tell him.

**Comment by FPtje** [comment]
https://github.com/Nayruden/Ulysses/issues/497

**Comment by deinemudda32** [comment]
Now im the proud user of old DarkRP Versions.

**Comment by FPtje** [comment]
I'll see if I can temporarily revert that one line that fixes this.
