### ISSUE TITLE
Pocketed Shipments do not Inherit Custom Model (Still)

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2076]
This issue still persists: https://github.com/FPtje/DarkRP/issues/2065

Shipments that get pocketed and then dropped still use the default shipment model ("models/items/item_item_crate.mdl") rather than the custom one.

Using Workshop version of DarkRP, fully updated. If you require a sample Shipment of mine or anything else, I'll be happy to oblige.

**Comment by FPtje** [comment]
Yeah, workshop hasn't been updated yet

**Comment by Hazbelll** [comment]
Oh yeah, my mistake. I saw the changes made in https://github.com/FPtje/DarkRP/commit/8163c9c54d2066b8b6368002ac485af5086a3d64 merged into the Workshop branch, so automatically assumed it had been pushed to Workshop itself by now.

My fault for not actually checking the Workshop page. Oops, my apologies.
