### ISSUE TITLE
requiresCook not working correctly

### ISSUE THREAD

**Issue by JRODISME** [FPtje/DarkRP#2077]
I've enabled hungermod and added food under darkrp_customthings/food.lua. For each item I've set requiresCook = false however when a user that isn't a cook attempts to buy the food it returns the message "You are unable to /buyfood. Cooks only."

Also this may be related: When a food item has requiresCook set to true it doesn't show up under the food tab regardless of whether the user is a cook or not.

**Comment by JRODISME** [comment]
In fact scratch that first part. Nobody can buy item food items regardless of whether they are a cook or not. Simple throws the cooks only error message.

**Comment by FPtje** [comment]
```lua
DarkRP.createFood("DICKS", {
	model = "models/props_junk/watermelon01.mdl",
	energy = 20,
	price = 20,
	requiresCook = false
})
```
Gives this (can buy as citizen):
http://i.imgur.com/psQXRWO.jpg

```lua
DarkRP.createFood("DICKS", {
	model = "models/props_junk/watermelon01.mdl",
	energy = 20,
	price = 20,
	requiresCook = true
})
```
Gives this (can't buy as citizen):
http://i.imgur.com/nESBK5H.png
and this (**can** buy with cook):
http://i.imgur.com/gSJ2ecv.jpg

This all works as intended. I can't reproduce what you're describing, sorry.

This is the logic used in DarkRP by the way:
```lua
if (v.requiresCook == nil or v.requiresCook == true) and not ply:isCook() then
	-- Tell the player that they can't buy it and end the purchase of food
end
```

Which basically says "if `requiresCook` is not filled in or when it's set to `true` AND the player is not a cook", you cannot buy the food.

**Comment by JRODISME** [comment]
Ah I see why, I didn't disable the default food under disabled_defaults.lua. I'll just leave that there for anyone else that may be encountering the issue. Apologies for wasting your time with such a silly issue.
