### ISSUE TITLE
CAMI Error?

### ISSUE THREAD

**Issue by MainFighter** [FPtje/DarkRP#2080]
Just updated my server to the latest DarkRP version and we are getting the following error in console:

[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/sh_settings.lua:104: attempt to index global 'CAMI' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/fpp/pp/sh_settings.lua:104
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/gamemode/modules/fpp/cl_fpp.lua:1
     4. include - [C]:-1
      5. LoadModules - gamemodes/darkrp/gamemode/cl_init.lua:22
       6. unknown - gamemodes/darkrp/gamemode/cl_init.lua:37

and also I no longer have access to the FPP settings even though before I did.

Using ServerGuard with the highest rank being "founder" because that is the default, I'm guessing that has something to do with at least the permission error.

**Comment by fruitwasp** [comment]
Another error, same issue:

```
[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:38: attempt to index global 'CAMI' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:38
```
