### ISSUE TITLE
Possibility of adding a New FAdmin Privilege based off rp_doormanipulation?

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2081]
When a rank has the `rp_doormanipulation` command, one of the permissions it grants is to let you remove owners of a door (Edit door group > None) so it reverts back to being unowned. This is very useful at times when dealing with troublemakers and the sort.

However, it also grants other permissions on doors that you may not want a rank to necessarily have, like setting permanent door ownerships. This means `rp_doormanipulation` can only really be assigned to higher ranks that you can trust with such power, in hope they never fiddle with anything they shouldn't, however this still voids the [Principle of Least Privilege] (https://en.wikipedia.org/wiki/Principle_of_least_privilege).

Would it be possible to provide us a way of assigning ranks only the ability of overriding door ownerships of players? A new FAdmin privilege or something? It would be greatly appreciated.

**Comment by FPtje** [comment]
You can make a door unownable, owned by teams or some other quality you define in the custom Lua file, but there's no concept of permanent door ownership in DarkRP.  All these things are door ownership manipulation. 

The only "permanent" thing someone with that priv can do is door groups or door teams. Do you really not want admins to be allowed to do that?

**Comment by Hazbelll** [comment]
That's what I was referring to with the "permanent" thing. The ability to assign doors to Door Groups or Door Teams.

If I want Admins to be able to assign Door Groups or Teams, I will give them the `rp_doormanipulation` privilege in FAdmin so they can do so. However, if I don't want them to be able to do that, but I do want them to force unown doors that players may purchase and own themselves, there's currently no way to do so.
