### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by Fuzzik** [FPtje/DarkRP#2085]
I was gonna put out a PR to fix a few uses of [deprecated functions](http://wiki.garrysmod.com/page/Category:Deprecated_Functions), but I can't sync to remote for some damn reason. Anywho, there are quite a few uses of deprecated functions in DarkRP, some of which can be remedied with a simple find and replace like "util.tobool to tobool", "ValidPanel to IsValid", and "SetDrawBackground to SetPaintBackground". Changing these wouldn't affect gameplay at all, it's just nitpicking from a code standpoint and I thought I'd bring it to attention.

**Comment by Bo98** [comment]
I've already done this but haven't sent a pull request yet.

**Comment by FPtje** [comment]
You're quick to make prs, that local keys function I simply forgot to
remove

**Comment by FPtje** [comment]
Oh wait I misread it

**Comment by FPtje** [comment]
Anyway I'll wait for the pull request.
