### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MainFighter** [FPtje/DarkRP#2087]
Hello,

The new release 2.6.2 I have been testing it and both servers I have had it on the server after like one reboot the server will crash when a user gets to the sending client info part of the loading.

No error messages no nothing just dies.

Main

**Comment by FPtje** [comment]
Game crashes are almost never caused by the gamemode. Especially the ones on join. I'm sorry. Thanks for testing anyway.

**Comment by MainFighter** [comment]
Well, It really can't be anything but DarkRP...
I've been through the process of installing DarkRP 2.6.2 on a clean new server
Start the game running the gamemode the issue happens
Revert to DarkRP 2.6.1 or whatever it has no issues

**Comment by MainFighter** [comment]
Read this one https://github.com/FPtje/DarkRP/issues/2088 it has a lot more detail on whats going on.

**Comment by FPtje** [comment]
I just tested this on my listen server and asked @Bo98 to try it on his dedicated server. Neither of us can reproduce it. Without a way to reproduce it, I can't confirm or fix anything.

**Comment by MainFighter** [comment]
I have no idea what is causing it because they are all clean dedicated servers.

**Comment by MainFighter** [comment]
I'll do it again now just to check...

**Comment by Bo98** [comment]
Any map in particular in case that matters?

**Comment by MainFighter** [comment]
I swear it just wants to make a lier out of me... I can't replicate it now.
I have no idea. I will do some more testing to see if I can get it to crash or anything.
I really gotta get some sleep, so I'm gonna get some. Night (Its like 5am in aussie haven't slept)
Anyway, sorry for the trouble.

**Comment by Bo98** [comment]
Did you ever encounter the issue again?

**Comment by MainFighter** [comment]
I haven't really had much time to do much with it but from the time I have it hasn't had the issue again. May have just been something wrong on my side.
