### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MainFighter** [FPtje/DarkRP#2088]
Hello,

Repost here but you closed it before I could explain properly so I will explain in detail

I installed DarkRP 2.6.2 Beta on a test server just to take a look.
First boot was fine then after the 2 or 3 restart/map change the server just crashes when a player joins the server and gets to the Sending Client Info part.

I am 99% sure this is being caused by DarkRP 2.6.2 Beta because its a clean newly installed server that hasn't been touched besides installing the gamemode.

So I install the 2.6.2 version and run it, the bug happens.
Switch it to sandbox the server has no issues.
Switch it back to DarkRP 2.6.2 it still has the connecting crashing issue.
I deleted the 2.6.2 and reverted to 2.6.1 the one before the beta and the server now works fine no issues.

So I have no idea how this could possibly be being caused by anything but DarkRP 2.6.2 Beta

There are no error messages or anything when the server goes down. The console just halts and refuses to do anything.

Does it on Ubuntu 14.04 x64, Windows 10 Pro x64 and Windows 2008 R2 Standard x64.

Main

**Comment by FPtje** [comment]
Don't repost, post in the old issue.

**Comment by MainFighter** [comment]
Well, this is a kinda important bug that I have been able to replicated on different computers/servers running completely different operating system that are running clean installs of the GMOD server.

It is still happening with my test server that I have local on my machine now and on my home server.
