### ISSUE TITLE
DarkRP Shipments

### ISSUE THREAD

**Issue by imLiaMxo** [FPtje/DarkRP#2089]
How do you enable Wire Grabber  to pickup a shipment?

**Comment by stapler2025** [comment]
By not asking on github

**Comment by imLiaMxo** [comment]
I've been told it's the DarkRP Gamemode. I've tried other places.

**Comment by stapler2025** [comment]
forum.darkrp.com

**Comment by imLiaMxo** [comment]
Tried.  Nobody replied.
