### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by coleski123** [FPtje/DarkRP#2094]
Hello my name is cole and i recently downloaded your newest version of DarkRP onto my server when ever i type in a rp_ command the server console tells me it is an unknown command and im using the commands like rp_arrest and rp_setmoney and then the server freezes and then tells me there is a connection problem........i switched back the version before this versom and the commands and the server seem to work just fine........Thanks Cole

**Comment by NamefuI** [comment]
rp_command has been removed

**Comment by HDG-MrDeeJay** [comment]
Then what pray tell will we use for TellAll?

**Comment by NamefuI** [comment]
use the power of your mind

**Comment by HDG-MrDeeJay** [comment]
Lets assume im a 12 year old.

My mind is telling me a few things, which include: My expensive keyboard 
and mouse have nice shiny colors on them, my totally custom server is 
the best one ever and im not a squeaker.

So for the 12 year olds in the room, please tell us the replacement 
commands.

If you wont do it for me, do it for OP.

**Comment by NamefuI** [comment]
rp_commands was replaced with a CAMI priviledge, don't ask me how it works, I don't use DarkRP anymore.

**Comment by FPtje** [comment]
The console motd tells you to look in f1.

**Comment by coleski123** [comment]
Thats not what i mean i was not really using the command rp_command......i ment if i used any rp_.......commands it crashed my server.....thats what i meant guys

**Comment by FPtje** [comment]
I tested a lot of rp_ commands before I changed them to DarkRP commands, and none of them crashed me.

Not like server crashes with reasonable uses of Lua should ever be my responsibility anyway.
