### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2095]
[ERROR] gamemodes/darkrp/entities/entities/spawned_food/init.lua:21: attempt to index field 'foodItem' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/spawned_food/init.lua:21

**Comment by FPtje** [comment]
Where's the rest of the damn stack trace!?

**Comment by deinemudda32** [comment]
Appeared in my console 6 times.
Dunno why.
I always report lua errors caused by DarkRP, cause I never have any lua errors in my console :P

**Comment by Bo98** [comment]
Since ENT:Use isn't called in Lua there probably isn't any further stack trace.

**Comment by FPtje** [comment]
Do you have your own way of spawning food?

**Comment by deinemudda32** [comment]
No

**Comment by FPtje** [comment]
Did you upload an unpacked zip of DarkRP through FileZilla?

**Comment by deinemudda32** [comment]
Yea im overwriting the old version with that.

**Comment by FPtje** [comment]
Safe to assume and bet that FileZilla failed to upload sv_hungermod.lua and hid the error away in a tab so you wouldn't see it.

Stop using FileZilla.
