### ISSUE TITLE
Console Commands for RP

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2096]
The console commands for admins and superadmins arent working anymore.
Just the Chat Commands.
I can no longer support Money by set by console :/.
Even Unarrest and Arrest is not included anymore.

**Comment by FPtje** [comment]
Yes, I moved them. Every singly chat command is also a concommand. 
Chat command: /dropmoney 10
concommand: DarkRP dropmoney 10

I decided that it's bullshit to have both a chat command, a concommand and then another concommand. Search the F1 menu.

**Comment by FPtje** [comment]
And read the god damn MOTD next time, it tells you about it.

**Comment by deinemudda32** [comment]
I already searched for an info, but considering to read the modt was too crazy for me.
