### ISSUE TITLE
Jail positions

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2097]
I'm for it to add /setjailpos as alias of /addjailpos, because setjailpos is more typical for commands and is easier to recognize.

**Comment by FPtje** [comment]
Then you'd have no command to reset all jailpositions and create a new one

**Comment by deinemudda32** [comment]
/setjailpos doesn't exist as command.
I meant it should be added as a alias, means same function.

**Comment by deinemudda32** [comment]
Oh by the way /jailpos and /addjailpos are the same commands.
Means you can't have more then 1 jailpos.

/jailpos
[DarkRP] You have removed all jail positions and you have added a new one here.
/setjailpos
[DarkRP] You have removed all jail positions and you have added a new one here.

**Comment by FPtje** [comment]
Fixed
