### ISSUE TITLE
Commands in general

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2098]
Commands should print errors as example in chat, for the noob in us.

Even I would suggest to add a function for displaying the use of a command by printing the usage globally in the chat, that would prevent admin abuse.

**Comment by FPtje** [comment]
Commands show errors in notifications. Chat is for chatting. Usage of most commands is shown in console.

**Comment by deinemudda32** [comment]
I meant usage of chat commands should print the error in chat, cause 60% of users are iritated elsewhere.

And the Idea to print the Usage of Chat Commands in the Global Chat hows that?

**Comment by FPtje** [comment]
Usage of chat commands prints the error in a notification on the screen. You're pulling that 60% out of your ass. 

And what the fuck is with the sudden capitalisation of every word? Go home, you're drunk

**Comment by deinemudda32** [comment]
I'm sorry for my bad english.

If you use a chat command you get nothing printed on youre screen.
