### ISSUE TITLE
[HELP] Unable to Assign Permissions to New Usergroups in ULX

### ISSUE THREAD

**Issue by deraphel** [FPtje/DarkRP#2099]
Everytime I try to make a new ULX group that inherits permissions from any other group other than superadmin, admin, the group defaults to inherit from user, automatically. For example, if I made a group called Owner that inherits permissions from a group called Head Admin, the Owner inherits from User all of a sudden, giving it no permissions. Then, when I try to move myself to the Owner usergroup, it makes me unable to chat or anything. Also, any group is able to inherit from Super Admin without errors.

Serverside/Clientside Lua Error
http://pastebin.com/H3yQaSCM

**Comment by jeje031** [comment]
Resolv ?

**Comment by NotSoSuper** [comment]
Disable fadmin or make corresponding groups with both of the which is
fucking stupid.

**Comment by jeje031** [comment]
Thank you for the answer but if it's me you stupid deals I ask you, I'll tell you calm down because this site in order to support and not to insult it at any time ...

**Comment by BillyOnWiiUIn144p** [comment]
But this isn't a help forum

**Comment by LetsRaceBwoi** [comment]
i think the readme.md text needs to be even bigger somehow @FPtje
