### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2101]
You should consider to add brackets for every command which influences a player like set money so this would work:

DarkRP setmoney "Sey Hay" 1000

this now gives an error, even withouth brackets.

**Comment by FPtje** [comment]
I can't, it would break the API.
Chat command callbacks are called with just the whole rest of the string as single argument. To make the DarkRP compatible with that, I have to turn the list of strings into a single string by concatenating it with spaces in between.

Once that's done, the information you ask for is lost.

**Comment by deinemudda32** [comment]
How about adding support for SteamIDs or UserIDs.
Id like to make a script to integrate ulx support for the commands, but that doesnt work without any id of the player I could use.

**Comment by FPtje** [comment]
Routing your ulx things through the chat command is a horrendous idea. Create plain ULX commands and call the necessary functions directly without using the chat commands.

It's like posting a letter to your mom in the same house to ask her to make you a sandwich. Just ask her directly.

**Comment by deinemudda32** [comment]
I know I just want to make things easier for my admins tho.

**Comment by FPtje** [comment]
This is about your coding, not about your admins.
