### ISSUE TITLE
Editing DarkRP script (config) with lua refresh will cause Server mess up

### ISSUE THREAD

**Issue by 00875** [FPtje/DarkRP#2107]
![2015-08-28_16-01_ponyrp rc 0 19 undefeated](https://cloud.githubusercontent.com/assets/6339511/9542843/712b7e6c-4d9e-11e5-91da-2fb4b39e8a49.jpg)
Then it will spam this:
![2015-08-28_16-01_ponyrp rc 0 19 undefeated 2](https://cloud.githubusercontent.com/assets/6339511/9542849/7c201904-4d9e-11e5-89fd-e387258913cf.jpg)
Then it will crash my addons
![2015-08-28_16-02_ponyrp rc 0 19 welcome](https://cloud.githubusercontent.com/assets/6339511/9542868/a0c72e50-4d9e-11e5-9540-dbc986c7f89c.jpg)

And as i see in my code:
![2015-08-28_16-07_f-srv-gm_darkrp-garrysmod-add](https://cloud.githubusercontent.com/assets/6339511/9542911/efda7600-4d9e-11e5-90f8-0035de609c05.jpg)
I think what cause this:
If player got 'unathed' (ULX/ULib like), then it will spam errors.
Also this breaks ALL addons what use IsAdmin (like IDE).

This is CAMI bug i think (because there is no bug was before i updated to 2.6.2).

**Comment by FPtje** [comment]
For the first error: some cunt is calling `FAdmin.Access.AddGroup` with a boolean for the admin parameter. No code in DarkRP sets the value of .ADMIN to a boolean.

**Comment by FPtje** [comment]
oh it's the same for all errors

**Comment by 00875** [comment]
I was on 2.6.1, editing and refreshing ENTRIE GAMEMODE CODE don't break anything. On 2.6.2 on reloading gamemode there are errors. I restarted map, all works again.

**Comment by FPtje** [comment]
WHO IS CALLING FADMIN.ACCESS.ADDGROUP WITH A BOOLEAN AS ADMIN PARAMETER?

**Comment by 00875** [comment]
I DON'T KNOW! I ONLY CALLS ply:IsAdmin() !!1

**Comment by FPtje** [comment]
Debug that shit

**Comment by 00875** [comment]
What the shit it was. There is no issue anymore (it dissapears).

**Comment by 00875** [comment]
![2015-08-28_17-06_garry s mod](https://cloud.githubusercontent.com/assets/6339511/9543942/23e2bd6a-4da7-11e5-88e0-69823cd4e75e.jpg)

![2015-08-28_17-06_ponyrp rc 0 19 - eat t](https://cloud.githubusercontent.com/assets/6339511/9543945/26141c28-4da7-11e5-8bb7-87119bcfab9c.jpg)
HahaHA! Should i send it to ULib repository?

**Comment by FPtje** [comment]
That one should indeed go to ulx
