### ISSUE TITLE
FAdmin lua error

### ISSUE THREAD

**Issue by WGHydrogen** [FPtje/DarkRP#2109]
When you create a new FAdmin group, it throws an error. Doesn't break anything thou

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:170: Tried to use a NULL entity!
  1. Send - [C]:-1
   2. SendGroups - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:170
    3. callback - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:124
     4. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/commands/sv_concommands.lua:19
      5. unknown - lua/includes/modules/concommand.lua:54

**Comment by FPtje** [comment]
You're definitely not running the latest version. These lines can't have that error. Also, I can't reproduce any errors on creating groups.
