### ISSUE TITLE
DarkRP Door Groups

### ISSUE THREAD

**Issue by CyanRawr** [FPtje/DarkRP#2110]
When you try to add jobs to the door groups via the F2 menu it will continue to say it is unowned.

**Comment by FPtje** [comment]
![2015-08-29_21-42-49](https://cloud.githubusercontent.com/assets/1202014/9563982/f5d53614-4e96-11e5-9993-eaa243a72bab.jpg)

Cannot reproduce. It even still saves.

**Comment by CyanRawr** [comment]
i mean when you add jobs individually.

**Comment by FPtje** [comment]
Could you be fucking clearer next time?
Also, still works for me.
