### ISSUE TITLE
Food error still happens

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2111]
[ERROR] gamemodes/darkrp/entities/entities/spawned_food/init.lua:21: attempt to index field 'foodItem' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/spawned_food/init.lua:21

Still hapens, dunno why.
I reuploaded DarkRP thousands of times. Didnt fix it at all.

**Comment by Bo98** [comment]
Really does sounds like an addon spawning food in its own way. Run this:

```lua
lua_run local f = ents.Create function ents.Create(class, ...) if class == "spawned_food" then debug.Trace() end return f(class,...) end
```

and spawn the food that causes the error (double-check by trying to eat it). A stack trace will be printed to console BEFORE the error.

**Comment by deinemudda32** [comment]
I dont have such a addon which can spawn food.

**Comment by FPtje** [comment]
duplicate issue.
