### ISSUE TITLE
/buy and /buyshipment works for everyone

### ISSUE THREAD

**Issue by icecafe** [FPtje/DarkRP#2120]
even if /buy for gun dealer only is enabled.

Fix for this?

**Comment by Bo98** [comment]
Are you setting the allowed field in your shipments?

[Like this](https://github.com/FPtje/DarkRP/blob/master/gamemode/config/addentities.lua#L9)

**Comment by FPtje** [comment]
![2015-08-31_12-58-08](https://cloud.githubusercontent.com/assets/1202014/9577315/f6c2ebd0-4fdf-11e5-86f1-83cd0d5f372b.png)
Unable to reproduce.
