### ISSUE TITLE
Cami error?

### ISSUE THREAD

**Issue by kulcris** [FPtje/DarkRP#2124]
[ERROR] gamemodes/zombierp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:40: attempt to index global 'CAMI' (a nil value)
  1. callback - gamemodes/zombierp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:40
   2. query - gamemodes/zombierp/gamemode/libraries/mysqlite/mysqlite.lua:300
    3. callback - gamemodes/zombierp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:25
     4. query - gamemodes/zombierp/gamemode/libraries/mysqlite/mysqlite.lua:300
      5. fn - gamemodes/zombierp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:13
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:179
        7. unknown - gamemodes/zombierp/gamemode/libraries/mysqlite/mysqlite.lua:161

Happens on restart randomly, thought maybe it was ulx doing but this is the first error im finding in my logs.

most of the info is not sent to the client properly, models are the grey dev model, money salary and f4 menu does not work. 

a simple restart normally fixes the issue

**Comment by kulcris** [comment]
[ERROR] gamemodes/zombierp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:9: attempt to index global 'CAMI' (a nil value)
  1. func - gamemodes/zombierp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:9
   2. unknown - lua/includes/extensions/net.lua:32


This is clientside

**Comment by 00875** [comment]
You are using outdated version of DarkRP. Download latest trunk of DarkRP.

**Comment by kulcris** [comment]
using the workshop version

**Comment by 00875** [comment]
Workshop Version is outdated. Download latest trunk.

**Comment by FPtje** [comment]
Cannot reproduce with the workshop version.

**Comment by kulcris** [comment]
Seems to have fixed when I updated to latest version might have been
another add on that updated. I had extracted the workshop version though
since the 2.6.1 download is not in versions. That might be it as well.
