### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Rorky** [FPtje/DarkRP#2125]
Ok I have just installed DarkRP onto my server about 5 times and remade the server 5 times i have came to the conclusion that DarkRP has been making my server crash every 5-20 minutes. I am saying this because I was on my server just walking around on sandbox with only one addon ULX and people joined there were like 10 random people on and there was no issue then i added DarkRP with ULX after that my gmod server went down and when i removed DarkRP it was fixed Please Help Me Thank You

-Rorky

**Comment by 00875** [comment]
Not a help forum.
