### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by kulcris** [FPtje/DarkRP#2126]
after installing the latest trunk of darkrp people on my server are unable to run while holding a weapon (m9k weapons) it worked perfectly before i updated darkrp. 

No console errors, cant find anyone else reporting the same issue. holding weapons like the stunstick allow you to run normally so it has to be a conflict between m9k and darkrp though i cant imagine what it would be. you move slower than you would while just walking (almost like you are in ironsights)

**Comment by NamefuI** [comment]
I think that the function changing a player's speed has been changed, maybe that's why. M9K weapons aren't made for DarkRP anyways, the developer said it himself. I've no idea why people use this pack.

**Comment by FPtje** [comment]
Jesus Christ don't blame m9k for potential bugs in DarkRP

**Comment by Bo98** [comment]
The changes with player speed should make it MORE compatible with addons than before. What happened before is DarkRP repeatedly called ply:SetWalkSpeed and ply:SetRunSpeed whenever it needed to change the speed (like the ironsights with the default DarkRP weapons). This broke any custom speeds set by addons unless they used a DarkRP specific hook. The new method now sets the default hooks using the above player functions, leaving the opportunity open for temporary speed changes to the default GMod move hooks which do not save the value and get rid of the default. This improves compatibility across gamemodes and allows jobs to have their own speeds without the need of extra hooks. It also fixed player classes speed variables being useless.

This should not have affected M9K though but I will check this. DarkRP only tweaks the player speed on spawn, on job change, on ironsights change (default DarkRP weapons) and on arrest/unarrest. The method of setting the speed _on spawn_ is almost identical to what it was before and this should be the only thing that should have an affect on M9K.

**Comment by Bo98** [comment]
But hey, maybe I missed something,
