### ISSUE TITLE
Add an Option to Automatically Clear RP Names from Database

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2127]
Would it be possible to add some optional automated way to clear all the RP names players have assigned themselves from the respective table holding them via SQLite/MySQL? Either in-game on a specific basis, purging the whole thing or both?

It can become problematic after some time, as players come and go, but the name they use sticks. Currently, RP Names are held in the table forever, unless someone tampers with them manually, either by forcing someone's RP name (only possible if they're on the Server at the time) or by editing the table directly (assuming someone's around when needed who has access to it - most communities I imagine, only allow one or two people such access. In my case, it's only me).

Someone else might wish to use the same name, but can't, so we have to go into the database and remove it ourselves on request if the player who's taken it isn't on. It can make sense to optionally automate the process too, as it keeps availability open.

In the event the removal process is automated and a player does come on who had an RP name, but now doesn't, they just have to simply run one command to set it back, much like a custom job name. If it's now been taken by someone else and they're not on, if we can override names of those not in-game, then we can do that for them too. Bit of a "first come, first served" basis.

**Comment by 00875** [comment]
Command to super admins what runnes query UPDATE darkrp_player SET rpname = NULL

**Comment by HDG-MrDeeJay** [comment]
@00875 ```UPDATE darkrp_player SET rpname = NULL WHERE ...```

Im sure you dont want to delete EVERY rpname at once

**Comment by 00875** [comment]
If clear names of players what inactive, there is needed table what counts player time

**Comment by HDG-MrDeeJay** [comment]
What?

**Comment by 00875** [comment]
I talk by myself. I told to you: to delete only inactive players DarkRP is needed the table what hold 'laat seen' time of players

**Comment by FPtje** [comment]
To keep track of how long players have been playing, when they were last seen and then have a config option to cull old players' rp name data (but not money data) seems to me like a lot of effort with little gain.

I can however make a "darkrp freeRPName" command.
