### ISSUE TITLE
ULX + DarkRP 2.6.2 + Custom Ranks = server crash

### ISSUE THREAD

**Issue by DaBiGBoSs** [FPtje/DarkRP#2129]
When any player is set to a custom rank, the server crashes when they connect or disconnect.
When connecting they will reach the sending client info portion and the server will crash right after that.
When disconnecting it crashes immediately when they leave. ULX ranks users, admins, and superadmins do not have this problem as far as I know.

I do not know how to fix this and it is making my server unplayable because it crashes. I would really appreciate any fixes you might have. If you need I can send you whatever file I have on my server. I also had the server "reinstalled" and tried it again so it is not just a 1 time thing apparently. I would be interested if you guys are also experiencing this issue or know what the problem is.

Also, in ULX Forums, they claimed that it's a problem from the gamemode, and i can agree with it because i tested it on sandbox and it's working fine.

I can't find any link to download DarkRP 2.6.1 anywhere, if you could give me a direct download link, i can test if this problem is happening on the older version.

I disabled FAdmin and the problem still occurs.....

Edit #1: there isn't any Lua error in my console

**Comment by FPtje** [comment]
![2015-09-02_12-11-54](https://cloud.githubusercontent.com/assets/1202014/9628523/d98e7682-516b-11e5-994d-1c06512497a6.png)

Just rejoined my own server. Cannot reproduce.

**Comment by DaBiGBoSs** [comment]
Alright, here's how to reproduce it:

1st way is:
Get in the server, create a custom rank, add your self in this rank and then reconnect.
The server will "freeze"

2nd way is:
Get in the server, create a custom rank, add your self in this rank and then try to buy a door.
Your game client will crash

**Comment by FPtje** [comment]
Both means of reproduction don't freeze or crash anything for me.

**Comment by DaBiGBoSs** [comment]
Which DarkRP gamemode version do use to reproduce the problem? i used the latest version on the github

**Comment by FPtje** [comment]
Me too.

**Comment by DaBiGBoSs** [comment]
Can i add you on steam/skype and show u the problem? i can't find any fix and there are other people who got the exact same problem with me.. i can give you some direct links with people who posted about this problem on the ULX forums..

**Comment by FPtje** [comment]
Follow this guide: http://forum.darkrp.com/threads/darkrp-bug.5979/#post-23721

**Comment by DaBiGBoSs** [comment]
i will try to use the Workshop version of DarkRP and then extract the files with GMAD, i will inform you for the results! :) Thank you!

**Comment by FPtje** [comment]
That's not what the guide says.

**Comment by DaBiGBoSs** [comment]
I didn't understand what is this "git bisect" and how to use it... i've readed the whole post and someone suggested to use the workshop version..... If you got some free time, can you explain to me what is this? Also, it's my first time owning a GMod server and i got some basic knowledge with coding....

**Comment by DaBiGBoSs** [comment]
I fixed the bug :) I also created a post on the ULX Forum on how to fix it :) thanks for your help! 

http://forums.ulyssesmod.net/index.php?topic=8920.msg45562#msg45562

**Comment by Bo98** [comment]
It's not a proper fix as DarkRP 2.6.2 will be the Workshop version in the future. But by then hopefully the bug is fixed.

I just managed to reproduce a client freeze on pressing F2 that might be related which I'm looking into.

**Comment by DaBiGBoSs** [comment]
Yeah i know but untill the DarkRP 2.6.2 is stable, people who got the same bug can use this solution to temporary fix it :)

Also, thank you guys for giving us DarkRP, i really love this gamemode, from my 900h of GMod, i wasted like 450-550 on DarkRP and i still love to play on this gamemode! :)

Keep up the good work <3

**Comment by FPtje** [comment]
No one ever noticed that I put a download for 2.6.1 in the releases section

**Comment by DaBiGBoSs** [comment]
i don't see it o.O 

http://prntscr.com/8btpv5

**Comment by Bo98** [comment]
Pre 2.6.2 beta = 2.6.1. Maybe it needs that clarification.

**Comment by DaBiGBoSs** [comment]
Yeap.... you should change it :P

**Comment by DaBiGBoSs** [comment]
By the way, i like how this issue turned out to something like a chatbox... lol

**Comment by Bo98** [comment]
If you can, try the latest version of DarkRP again. I've fixed the issue I had with my client freezing on pressing F2 which may be the same issue as what you're experiencing.

**Comment by DaBiGBoSs** [comment]
I will try it in maybe 1-2 hours :) i will tell you the results :)

**Comment by georgewilliam1** [comment]
I am having the same problem, Users join the server and then it crashes. Is there a fix??

**Comment by FPtje** [comment]
There was, a god damn month ago. Update.

**Comment by georgewilliam1** [comment]
Mine is still coming up with the same error ? Could you link me to the newest version?

**Comment by FPtje** [comment]
You're on its official website. Go look for the "download zip" button.

**Comment by georgewilliam1** [comment]
Sorry didn't mean to cause an uproar

**Comment by georgewilliam1** [comment]
I have asked the host and they say it may be a attack on the server but they are not 100% sure. I have also updated the DarkRP. Where do I get an updated version of modification
