### ISSUE TITLE
A few people are crashing when pressing F2 or using keys -> r

### ISSUE THREAD

**Issue by CyberTechnologyInc** [FPtje/DarkRP#2130]
As the title says, people are crashing. They crash even when not even pointing at a door and doing either of those things. There's also no errors, because we have to restart our entire PC because GMOD completely freezes and overlays everything (even when trying to lock the PC using windows + L) Also we can hear the same sound playing on some kind of loop. 
Any ideas on the reason?

**Comment by FPtje** [comment]
Duplicate issue.
