### ISSUE TITLE
Jail positions not working

### ISSUE THREAD

**Issue by oOSpeedhackerOo** [FPtje/DarkRP#2132]
I lately started a DarkRP Server. Now I am trying to add jail positions to the map i recently put on my Server. I use the command "/jailpos" to make my first jail position. So far so good. 
(there is also this message popping up saying "You have removed all jail positions and you have added a new one here")
But every time I use the command "/addjailpos" it deletes the old jail position and creates a new one with the same message as if I use "/jailpos".
Normally it should say something like "You have added one extra jail position" and it should create a new jail position.....but it doesn't.

**Comment by Bo98** [comment]
Are you using the very latest version?

**Comment by oOSpeedhackerOo** [comment]
yes

**Comment by NamefuI** [comment]
I can't recreate it, are you sure you're doing it right? Did you download the latest trunk from github? (not workshop)

**Comment by oOSpeedhackerOo** [comment]
yes.....i am sure

**Comment by NamefuI** [comment]
Well, it works for me and I have the newest version of DarkRP. Go to the DarkRP forums, they'll help you.

**Comment by oOSpeedhackerOo** [comment]
can you give me the link to the newest trunk so i can check again?

**Comment by NamefuI** [comment]
https://github.com/FPtje/DarkRP/archive/master.zip

**Comment by oOSpeedhackerOo** [comment]
yeah thats the same one as i have

**Comment by NamefuI** [comment]
Yeah, go to the DarkRP forums.

**Comment by oOSpeedhackerOo** [comment]
k

**Comment by FPtje** [comment]
Works for me.
