### ISSUE TITLE
How Do I Add Hitman Jobs?

### ISSUE THREAD

**Issue by SlayerPlays** [FPtje/DarkRP#2142]
I change DarkRP.addHitman from (TEAM_MOB) to (TEAM_HITMAN)

**Comment by FPtje** [comment]
Not a help forum.

**Comment by AMD-NICK** [comment]
jobs.lua
The end of file:
--[[---------------------------------------------------------------------------
Jobs that are hitmen (enables the hitman menu)
---------------------------------------------------------------------------]]
DarkRP.addHitmanTeam(TEAM_HITMAN)

**Comment by SlayerPlays** [comment]
i did that it didnt work

**Comment by AMD-NICK** [comment]
Is hitman module enabled?
disabled_defaults.lua
Must be like this: ["hitmenu"]          = false,
