### ISSUE TITLE
ulx fadmin new group

### ISSUE THREAD

**Issue by kulcris** [FPtje/DarkRP#2144]
Add a group called "mod" in ulx give them spectate (not sure if spectate is required)
add a player to the group and have them spectate a player
have them move forwards to leave spectate
server crashes.
Any time that player joins the server the server will crash
fadmin group "mod" doesnt exist but it adds the player to the group in the database 
by deleting the user's "mod" status in the fadmin part of sv.db the player is allowed to join without the server crashing

seems fadmin doesn't recognize the group created by ulx (latest of both ulx/ulib and fadmin)

**Comment by FPtje** [comment]
Try the latest DarkRP. An infinite loop crash was fixed in it. Also, you're describing ulx spectate.
