### ISSUE TITLE
[question / issue] Did you remove darkrp console commands?

### ISSUE THREAD

**Issue by LightMagic** [FPtje/DarkRP#2145]
i'v noticed I can't do things like rp_setmoney for the test server if you removed this feature will their be a new feature to replace this?

**Comment by Velkon** [comment]
no

**Comment by LightMagic** [comment]
"no"
No it was not removed or no they wont add a new feature for it? 10/10 comment

**Comment by aStonedPenguin** [comment]
yes

**Comment by xaviergmail** [comment]
maybe

**Comment by HDG-MrDeeJay** [comment]
i dont know

**Comment by FPtje** [comment]
Read th3 DarkRP motd

**Comment by Velkon** [comment]
ok

**Comment by LightMagic** [comment]
I feel stupid for asking this, but what is the DarkRP motd, and can you link me to it?

**Comment by FPtje** [comment]
Look in the console after you join a DarkRP server
