### ISSUE TITLE
Problem with last update

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#2146]
[ERROR] lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)
  1. Parse - lua/includes/modules/markup.lua:245
   2. PrintWeaponInfo - gamemodes/base/entities/weapons/weapon_base/cl_init.lua:80
    3. unknown - gamemodes/base/entities/weapons/weapon_base/cl_init.lua:56

**Comment by Bo98** [comment]
Isn't a DarkRP bug.

Update your anti-cheat addon if you have one.

Otherwise, `garrysmod/lua/includes/init.lua` didn't update correctly for you.
