### ISSUE TITLE
Can't Use anything

### ISSUE THREAD

**Issue by DaBiGBoSs** [FPtje/DarkRP#2150]
Hello, it's me again...

Today i started my server after updating my GMod game and once i was in, i couldn't use anything, doors were not opening, there wasn't that handle animation and players couldn't pickup weapons/money...

I updated my server files but still no fix....

I also updated to the latest DarkRP version and it's still not working...

The previous time i had my server on, everything was working fine...

**Comment by 00875** [comment]
Not a help forum. Everything works fine for me. FPtje cannot reproduce.
13 Сен 2015 г. 5:15 пользователь "DaBiGBoSs" <notifications@github.com>
написал:

**Comment by HDG-MrDeeJay** [comment]
Who the fuck let you talk for Falco?

**Comment by DaBiGBoSs** [comment]
lol...

**Comment by 00875** [comment]
All works for me. So, no one can reproduce it.

**Comment by HDG-MrDeeJay** [comment]
No, that mean's you cannot reproduce it. And given your history with LUA 
*cough*your recent pull request*cough* I sincerely doubt your ability to 
reproduce any bug.

How about we wait for Falco to say he can't reproduce something before 
you say he can't.

**Comment by HDG-MrDeeJay** [comment]
No, that mean's you cannot reproduce it. And given your history with LUA *cough*your recent pull request*cough* I sincerely doubt your ability to reproduce any bug.

How about we wait for Falco to say he can't reproduce something before you say he can't.

**Comment by DaBiGBoSs** [comment]
@HDG-MrDeeJay Do you have the same problem? :/

**Comment by HDG-MrDeeJay** [comment]
Sorry email recipients for the double post, my email'd response didn't make it to github on my end until I posted it by hand.

Anyway, on topic now, @DaBiGBoSs is there anything else you can tell us about your server? Are there any unusual errors or prints to your console, or to your server's console? Is CS:S mounted? Do you have any addons?

If you have a bunch of addons, start removing them one by one, restarting each time until you have either solved the issue, or ran out of addons.

**Comment by Bo98** [comment]
Most importantly, does it happen in Sandbox? This screams of some sort of model issue and not a gamemode specific one.

**Comment by 00875** [comment]
So, @HDG-MrDeeJay asking you right. Doors on rp_bangclaw is using CS:S, money models too.

**Comment by HDG-MrDeeJay** [comment]
@00875 When did he say he was using bangclaw? The only two matches for "bangclaw" (now 3) are in your post and mine

**Comment by 00875** [comment]
Some of doors on some maps (example: Bangclaw) are using CS:S Models.

**Comment by HDG-MrDeeJay** [comment]
I thought the doors all used HL2 models and textures, given CS:S has virtually no doors, but HL2 has hundreds of them

**Comment by Bo98** [comment]
There's some from EP2 but probably not in this case.

**Comment by DaBiGBoSs** [comment]
Alright, sorry for not replying earlier..

My server is using RP_Downtown_Altered and i got CS:S mounted....

**Comment by 00875** [comment]
Can you walk through doors/props/weapons/money?

**Comment by DaBiGBoSs** [comment]
Nope :/

Should i post the server IP here? so you can test it...?

**Comment by 00875** [comment]
No. you don't need to post ip. If you can't, there is no problem with mounting CS:S

**Comment by DaBiGBoSs** [comment]
FIXED: arcbank was messing up with the server....
