### ISSUE TITLE
Voicechat

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2153]
If someone is behind a Prop/Entity or whatever, you can abuse the voicechat to find out who is behind the Prop/Entity as it tells you who is hearing you, even if he is behind a wall.

**Comment by aStonedPenguin** [comment]
this is game breaking!!!

**Comment by FrikenCanadiansEH** [comment]
Totally wasn't intended

**Comment by notcake** [comment]
i blame robotboy

**Comment by FPtje** [comment]
This is a side effect of intended behaviour. There's not much I can do about this except changing the behaviour in such way that it either lies to the player on who can hear them or make it so people can't hear you through props. The latter will make it practically impossible to talk to one another.
