### ISSUE TITLE
Unable to "Disallow Ownership" on Doors

### ISSUE THREAD

**Issue by stapler2025** [FPtje/DarkRP#2154]
As the title says, I (nor any of my admins/superadmins) can F2 or use keys on a door to disallow ownership.

We can buy and sell the door, rename it, add owners, remove owners etc.  If the door has owners and we click "disallow ownership" it just removes the owners from the doors.

No addons currently affect the door system in any way, nor are any errors printed clientside/serverside.

**Comment by FPtje** [comment]
Set the privileges in you favourite CAMI supported admins mod.

**Comment by stapler2025** [comment]
http://i.imgur.com/leeFDsf.png

On Sun, Sep 13, 2015 at 1:49 PM, Falco Peijnenburg <notifications@github.com

**Comment by FPtje** [comment]
https://github.com/Nayruden/Ulysses/issues/516

Running the command manually should work. The menu doesn't show the option because it doesn't know you have the privs.

**Comment by stapler2025** [comment]
What's the manual command to disallow ownership?  I feel like I should know
this but my brain is failing me.

On Sun, Sep 13, 2015 at 2:04 PM, Falco Peijnenburg <notifications@github.com

**Comment by stapler2025** [comment]
Just gave that a shot and it's still not letting us set doors to unownable
:(  Would be nice for the folks over at ULX to fix their shit.

**Comment by Bo98** [comment]
Odd as the command is serverside but the ULX bug should only affect clientside (F2/keys menu).

What does the door say after you set it to unknownable? Just the normal message of press F2 to buy?

**Comment by stapler2025** [comment]
Indeed.

If the door is bought, it resets to "Press F2 etc"

**Comment by stapler2025** [comment]
Just gave it a shot again, /toggleownable just seems to unown a door rather
than actually making it unownable.

**Comment by Velkon** [comment]
ok

**Comment by kulcris** [comment]
if you run the latest "STABLE" version of ulx (doesnt have cami yet) it should work fine (just wait for ulx to update)
