### ISSUE TITLE
darkrp commands

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2156]
# I have noticed that with the latest update some commands have changed.

darkrp setmoney  "NICKNAME" 50000
the use of quotation marks does not work for user names with spaces.

###### "Invalid argument"

As with all commands can not use quotation marks.

**Comment by FPtje** [comment]
I might have to break some backwards compatibility to fix this. I'll look into this.

**Comment by FPtje** [comment]
Turns out I didn't have to break backwards compatibility.
