### ISSUE TITLE
Disabled Stock HUD + Enabled HungerMod = Lua Error

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2157]
In `disabled_defaults.lua`, if you disable the stock HUD by setting the following:
```lua
["hud"]              = true,
```
Then the following Lua error will occur as the ConVar `HudW` was never created in `cl_hud.lua` of the Stock HUD:
```
[DarkRP] gamemodes/darkrp/gamemode/modules/hungermod/cl_init.lua:55: attempt to index a nil value
  1. unknown - gamemodes/darkrp/gamemode/modules/hungermod/cl_init.lua:55

Timer Failed! [Simple][@gamemodes/darkrp/gamemode/modules/hungermod/cl_init.lua (line 57)]
```

**Comment by HDG-MrDeeJay** [comment]
nice find

**Comment by 00875** [comment]
Just need to disable HungerMod HUD when default HUD is disabled.

**Comment by fruitwasp** [comment]
That's a solution, but not the best, @00875. I think hungermod should check whether the default hud is disabled or not.

**Comment by HDG-MrDeeJay** [comment]
Or perhaps not rely on it all together.

**Comment by HDG-MrDeeJay** [comment]
I mean, hungermod is a module! It should work flawlessly with and 
without other modules, including the HUD.

**Comment by 00875** [comment]
HungerMod's HUD is a module for default HUD. It is designed for it.

**Comment by fruitwasp** [comment]
+1 @HDG-MrDeeJay
