### ISSUE TITLE
ammo y shipment error

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2158]
I use the default menu f4 darkrp
You can not buy ammunition or weapons seller
I get the message

[DarkRP] **This ammo is unavailable**
[DarkRP] **This ammo is unavailable**

[DarkRP] **This shipment is unavailable**
[DarkRP] **This ammo is unavailable**

This happened with the last update
https://i.gyazo.com/fd9d488b7b3664e35a49e55236bb5631.png

**Comment by FPtje** [comment]
Fixed in latest.

**Comment by matiasg90** [comment]
[DarkRP] This shipment is unavailable
Continues ..
you can not buy weapons from the menu f4

**Comment by SiglakS** [comment]
yes but it happens again :/
