### ISSUE TITLE
privilegies CAMI

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2159]
I was testing the privileges from ULX, and apparently not working properly.
I notified that do not have access, but it's just a visual message.
It seems as if it works backwards.

say /setmoney "M a" 1
[DarkRP] You don't have the right privileges to perform this action
[DarkRP] You set M a t i a s ^^'s money to $1.

video:
https://www.youtube.com/watch?v=6axUs1TwDNY

**Comment by FPtje** [comment]
https://github.com/Nayruden/Ulysses/issues/505
