### ISSUE TITLE
bad argument #1 to 'SetTeam' (number 

### ISSUE THREAD

**Issue by konrad2503** [FPtje/DarkRP#2163]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:294: bad argument #1 to 'SetTeam' (number expected, got nil)
  1. SetTeam - [C]:-1
   2. v - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:294
    3. unknown - lua/includes/modules/hook.lua:84

at spawn

**Comment by konrad2503** [comment]
after a second download from github i have


[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:244: attempt to index global 'MySQLite' (a nil value)
  1. retrievePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:244
   2. restorePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:312
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:570


[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502: bad argument #1 to 'SetModel' (string expected, got nil)
  1. SetModel - [C]:-1
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:668

**Comment by FPtje** [comment]
The only SetTeam in sv_gamemode_functions  is on line 534. MySQLite not existing is a sign of a bad install.

**Comment by konrad2503** [comment]
Hmm i just cloned the gamemode .. no bad install :-P

**Comment by FPtje** [comment]
I can't fix errors that are impossible

**Comment by konrad2503** [comment]
hmm i am having a dedicated server there it w0rkz but on my client it doenst work ... i ust wanna test my ferriswheel ticketmachine which throws 0 errorz

**Comment by FPtje** [comment]
I have a listen server and it w000000rks for both my serv0r and my client
yes I cannot help anyone with bugs that I cannot reproduce z0r

**Comment by konrad2503** [comment]
what do u think can i do(without reinstalling gmod :-P)

**Comment by FPtje** [comment]
I don't know, judging by your SetTeam error I don't think it's my latest
version of DarkRP you're running

**Comment by konrad2503** [comment]
i think its a bugging base gamemode

**Comment by konrad2503** [comment]
and yes i did a update (git client) so no old version is installed!

**Comment by HDG-MrDeeJay** [comment]
Well if reinstalling DarkRP didnt fix the issue, and it isn't an 
addon... I may sound crazy but have you tried reinstalling garrys mod?

**Comment by konrad2503** [comment]
i had reinstalled gmod now it throws the same err0r

**Comment by FPtje** [comment]
MySQLite being nil says MySQLite isn't loading.

**Comment by konrad2503** [comment]
what is mysql lite i never had activated that fe4tur3

**Comment by HDG-MrDeeJay** [comment]
MySQLite is the feature that stores your player's wallets and shit.

It provides the ability to store to either the Garry's Mod built-in 
database, or a remote database using MySQL.

If it wasn't activated, DarkRP wouldn't work.

**Comment by FPtje** [comment]
How about we try to blame this one on filezilla: check on your server to
see if DarkRP <https://github.com/FPtje/DarkRP>/gamemode
<https://github.com/FPtje/DarkRP/tree/master/gamemode>/libraries
<https://github.com/FPtje/DarkRP/tree/master/gamemode/libraries>/mysqlite
<https://github.com/FPtje/DarkRP/tree/master/gamemode/libraries/mysqlite>/MySQLite.lua
exists.  If it doesn't exist, then you can blame filezilla. If it does
exist, look for earlier errors in console.

That is of course assuming you used filezilla

**Comment by konrad2503** [comment]
hmm that would say that gmod makes shit

**Comment by konrad2503** [comment]
okay that files exists
scr33n: http://prntscr.com/8gy5dw

**Comment by FPtje** [comment]
What were you saying about dedicated server?

**Comment by konrad2503** [comment]
no its a listen server the dedicated works but i want to test it clientside, last saturday tha shit workz but now it doenst want to w0rk!

**Comment by konrad2503** [comment]
Thats all what i have http://prntscr.com/8gy83a

**Comment by HDG-MrDeeJay** [comment]
That's it. I've lost hope in this fucking game.

**Comment by FPtje** [comment]
I just tested again. It works for me. You broke it, so you will have to fix
it. This is not a help forum.
