### ISSUE TITLE
The last update kill some chat and console commands

### ISSUE THREAD

**Issue by AMD-NICK** [FPtje/DarkRP#2166]
So. Yesterday I was update my darkrp to fresh version and got nonworking chat commands.

> ] rp_setmoney amd 40000000
This command has been deprecated. Please use 'DarkRP setmoney' or '/setmoney' instead.
> ] DarkRP setmoney amd 40000000
Некорретный аргумент! *(uncorrect argument)*
> ] DarkRP setmoney 40000000
Не найден 4 *(not found 4)*
> ] DarkRP setmoney _AMD_ 40000000
Некорретный аргумент! *(uncorrect argument)*
> ] DarkRP setmoney AMD 40000000
Некорретный аргумент! *(uncorrect argument)*
> ] say /setmoney amd 40000000
Некорретный аргумент! *(uncorrect argument)*

Also some commands like /warrant <nick> stopped working too and now they visible for all players on the server
![image](https://cloud.githubusercontent.com/assets/9200174/9998064/35afb882-6098-11e5-904f-90f48db3d96a.png)

How can I fix it?

### More examples:
> ] rp_arrest amd
This command has been deprecated. Please use 'DarkRP forcearrest' or '/forcearrest' instead.
> ] say /forcearrest amd
_AMD_: /forcearrest amd

**Comment by IVogel** [comment]
I have this problem too

**Comment by FPtje** [comment]
Looks like you're missing stuff. Everything works fine here. If you're running the workshop version, try restarting (updating)

![2015-09-21_19-31-55](https://cloud.githubusercontent.com/assets/1202014/9999640/b2def95e-6097-11e5-9a54-ea8d7b1cd14b.png)

**Comment by AMD-NICK** [comment]
Maybe something in darkrpmodification cause this problem?

modules folder:
![image](https://cloud.githubusercontent.com/assets/9200174/10000140/01a79bbc-60a3-11e5-9205-4892fc3d9f74.png)

**Comment by FPtje** [comment]
Not that I know of.

**Comment by 00875** [comment]
![2015-09-22_08-02_garry s mod](https://cloud.githubusercontent.com/assets/6339511/10008995/53e81c5a-6100-11e5-8790-c60a4f863524.jpg)

**Comment by AMD-NICK** [comment]
@00875 В папке /darkrpmodification/modules я удалил модуль chat (его там может и не быть, просто я делал изменения) и заменил чистым из обновленного darkrp. Все заработало.

**Comment by 00875** [comment]
@AMD-NICK /forcearrest is not existing command.
