### ISSUE TITLE
fadmin jail must force player exit his vehicle

### ISSUE THREAD

**Issue by 00875** [FPtje/DarkRP#2167]
When being in vehicle and calling fadmin jail, you will still be in vehicle.
![2015-09-22_00016](https://cloud.githubusercontent.com/assets/6339511/10021535/a34d50ea-6172-11e5-9447-51df68d306b5.jpg)
Also player can enter vehicle when he is in jail.

**Comment by FPtje** [comment]
Weird that no one reported this before.

**Comment by HDG-MrDeeJay** [comment]
More people prefer to use ULX's jail.

Personally I just like leaving minges to hang at spawn.
