### ISSUE TITLE
Category canSee issue

### ISSUE THREAD

**Issue by pittm8** [FPtje/DarkRP#2173]
Basically the Cansee works so it hides the Categories from the other job roles yet, when you join the server as a citizen they see all the tabs and can buy from them, once bought from them and close F4 it goes away.

   canSee = function(ply) return ply:Team() == TEAM_DRUG end,

**Comment by FPtje** [comment]
Works for me
![2015-09-24_17-32-20](https://cloud.githubusercontent.com/assets/1202014/10077812/437f8acc-62e2-11e5-9a4d-dfdeec5707bb.jpg)

**Comment by pittm8** [comment]
Sorry I made a mistake with what I said, it happens with the weapon tab. So any weapon that is set to be seen only by 1 job everyone can see when you spawn and click weapons.
