### ISSUE TITLE
DARKRP FATAL ERROR

### ISSUE THREAD

**Issue by DARKRPISSHITFIXTHISUPDATE** [FPtje/DarkRP#2177]
hello i ran darkrp on this server and it not work anymore, i get this sandbox ugly interface but people can press f4 and get good job why you made this shitty mod i will never donate to this shitty mod when it doesnt work without issues all servers i see have same issue, can you make proper mod and i can not connect this? https://scriptfodder.com/scripts/view/1656 why you break api on this shitty darkrp, why you have remove networkvariables you idiot it works better with them

i do this
I PUT NOT IN AND IT WORKS BETTER WHY NOT ADD IT IN!!!!!
if not string.find(contents, "#NoSimplerr#") then include(path) return true end

do you know how to code? 

i give u ffix plis accept
https://github.com/FPtje/DarkRP/pull/2174

add me on steam or skype we wil communicate

translated by google translate

also i understand no touch files https://github.com/FPtje/DarkRP/pull/2175

i fix autorefresh https://github.com/FPtje/DarkRP/pull/2176
much better autorefresh, autorefresh is enabled, must be bug.

**Comment by HDG-MrDeeJay** [comment]
i google translated this

fuck off

**Comment by DARKRPISSHITFIXTHISUPDATE** [comment]
fix shitty mod

**Comment by HDG-MrDeeJay** [comment]
ur face is a shitty mod

you cant code kid stop flailing your arms over your keyboard.

@FPtje pls ban

**Comment by DARKRPISSHITFIXTHISUPDATE** [comment]
go sell your shitty mods for money somewhere else greeedy bastard i get for free

**Comment by HDG-MrDeeJay** [comment]
i dont charge money for mods lol if ur gonna troll get ur facts straight first ya nimrod haha

**Comment by DARKRPISSHITFIXTHISUPDATE** [comment]
i want falco to fix mod so i can host server free

**Comment by HDG-MrDeeJay** [comment]
but mod is fix.

you are kebab and must be removed.

**Comment by SwadicalRag** [comment]
stop feeding the trolls, @HDG-MrDeeJay 
block and move on.

**Comment by HDG-MrDeeJay** [comment]
@SwadicalRag Aww, but I'm extremely bored.

**Comment by DARKRPISSHITFIXTHISUPDATE** [comment]
you are shit

**Comment by SwadicalRag** [comment]
![spam](http://i.imgur.com/PGjNOl1.png)

![meme](http://i.imgur.com/Vvm8clD.png)

**Comment by DARKRPISSHITFIXTHISUPDATE** [comment]
u dont now code so u have issue, i now god coding

**Comment by HDG-MrDeeJay** [comment]
@SwadicalRag where can i get my hands on something like that

**Comment by deinemudda32** [comment]
Poor World.
Im nobody who agrees on killing out of mercy, but in this case its different.

**Comment by SwadicalRag** [comment]
@HDG-MrDeeJay since you asked, steam://friends/joinchat/103582791439031144
