### ISSUE TITLE
CanDropWeaponOnDie Hook for DarkRP

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2179]
I would suggest to add a hook for dropping weapons on death which can return false or true.

**Comment by FPtje** [comment]
I would suggest disabling the DarkRP weapon dropping and creating your own.

**Comment by deinemudda32** [comment]
Its much difficultier than just adding a hook for dropping weapons on death and I surely won't rewrite a whole system just to add one simple function which already should be implemented.

**Comment by Bo98** [comment]
Is it a per job thing?

**Comment by deinemudda32** [comment]
No its a Dont drop weapons without ammo thing.

**Comment by Bo98** [comment]
You might be able to use the canDropWeapon hook with a ply:Alive() check.

**Comment by deinemudda32** [comment]
The hook is not ran at death.

**Comment by Bo98** [comment]
Should be:

https://github.com/FPtje/DarkRP/blob/08ec28abe2f5aed8870380bd02e8e14ecaac7529/gamemode/modules/base/sv_gamemode_functions.lua#L385

**Comment by FPtje** [comment]
One could argue for any arbitrary setting to have a hook. Watch:

- `GM.Config.allowrpnames` - Make a hook that decides who gets to have an RP name
- `GM.Config.copscanunweld` - A hook that decides which cops can unweld
- `GM.Config.droppocketarrest` - same as the one requested in this issue
- `GM.Config.revokeLicenseOnJobChange` 
etc.

**Comment by HDG-MrDeeJay** [comment]
How about, instead of making 100 million hooks for config settings, how 
about we allow the config settings to take fuctions as well as their 
standard "true/false/int/crap" shit.

Retards that don't know how to lua shouldn't notice a change, while 
people who want to be so cool with their custom DarkRP server can have a 
config of functions.


No seriously, tell me why this shouldn't happen.

**Comment by FPtje** [comment]
Because mods would set config options to functions and end users would
complain to me about their config options not working.
