### ISSUE TITLE
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502: bad argument #1 to 'SetModel' (string expected, got nil)

### ISSUE THREAD

**Issue by unown294** [FPtje/DarkRP#2180]
Ok i just created a new darkrp server using the addon dirrectly off of the forums here. Everything was working 100% like it should until we tried arresting someone. The jailpos command was suppose to put them in the jail but worked only once and then there on after repeatively sends people to spawns for player that are spread all over the map. I have a picture of the full error and im open to any solutions

**Comment by meepdarknessmeep** [comment]
very thorough and helps us a lot

**Comment by unown294** [comment]
Im converting the image with the error it will be a few minutes

**Comment by unown294** [comment]
![20150928_172255](https://cloud.githubusercontent.com/assets/14893440/10171884/e8d6a326-66a1-11e5-9a39-ff6a13f8138e.jpg)

**Comment by Bo98** [comment]
Looks like you screwed up one of your jobs. Restart and check out for an error to point you to it.

> off of the forums here

This is not the forum. This is a bug tracker. Go to http://forum.darkrp.com

**Comment by unown294** [comment]
This is like this everytime i restart the server regardless of what i do. I am ranked superadmin so i have access to all the tool to set the jailpos and i have had success with setting the jailpos but whether there not truely saving or there one time uses i dont know. I havent edited any jobs as of now and we were in the process of doing it but didnt add any other jobs into the server because fixing this is a priority

**Comment by FPtje** [comment]
He's not the first with this error.

**Comment by Bo98** [comment]
Good point since a mistake in the jobs should never make it this far as it never would add the job.

**Comment by FPtje** [comment]
And why only on arrest?

@unown294 can you post the FULL server log? I want to see if there are any other errors, e.g. on startup.

**Comment by unown294** [comment]
I can but it will be after 5pm. That when ill be able to get the logs as im currently not near the machine

**Comment by unown294** [comment]
Is there anything else you would need

**Comment by unown294** [comment]
And to answer the question about the arrest i cant say for sure. As it only happens when you try to arrest someone and it appear normal by displaying the "xxxx has been jailed for 120 seconds" and then they get sent to spawn and that error shows up and when you un arrest them it replyies with "playername: spawn"

**Comment by FPtje** [comment]
So he sent me the logs in a docx file. It doesn't show errors on startup, but it does show that it doesn't happen only on arrest. It happens on different kinds of spawns.

**Comment by Bo98** [comment]
Does the equipping of job weapons work correctly on spawn?

**Comment by deinemudda32** [comment]
Same here ;)

**Comment by FPtje** [comment]
Why don't you, @deinemudda32 and @unown294 compare addons?

**Comment by deinemudda32** [comment]
I guess he has less.
He should name every single one and I can say If I have it or not.

**Comment by deinemudda32** [comment]
Thats very strange that error, even cause I never modified any Models on PlayerSpawn or PlayerInitialSpawn :P.

**Comment by FPtje** [comment]
Also, run this in the server and give me the results:
```lua
lua_run for k, v in pairs(RPExtraTeams) do print(v.name, v.model) if istable(v.model) then PrintTable(model) end end
```

**Comment by deinemudda32** [comment]
Lua Error.
Says my Citizen Job is broken.

**Comment by unown294** [comment]
Let me try this

**Comment by FPtje** [comment]
It shouldn't be saying your citizen job is broken, DarkRP code itself does that.

**Comment by deinemudda32** [comment]
I get an lua error after the Citizen Table got read. Means it says its broken.

**Comment by FPtje** [comment]
Jesus christ give me the error already

**Comment by deinemudda32** [comment]
Citizen       table: 0xe98e7258
L 09/30/2015 - 15:49:46: Lua Error: 
[ERROR] lua/includes/extensions/table.lua:711: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:711
    3. PrintTable - lua/includes/util.lua:42
     4. unknown - lua_run:1

**Comment by FPtje** [comment]
Alright, my bad. I've updated the line of code. Run again.

**Comment by unown294** [comment]
A sent a separate email with a picture of the error in it

**Comment by deinemudda32** [comment]
oh you tried to display a non valid table.

**Comment by deinemudda32** [comment]
No error at all.
Do I have to sent the output?

**Comment by FPtje** [comment]
YES, GOD DAMNIT

**Comment by deinemudda32** [comment]
Yea maybe I should've not asked.

**Comment by deinemudda32** [comment]
PrintTable(v.model) end end
> for k, v in pairs(RPExtraTeams) do print(v.name, v.model) if istable(v.model) then PrintTable(v.model) end end...
Citizen       table: 0xe98e7258
1       =       models/player/Group01/Female_01.mdl
2       =       models/player/Group01/Female_02.mdl
3       =       models/player/Group01/Female_03.mdl
4       =       models/player/Group01/Female_04.mdl
5       =       models/player/Group01/Female_06.mdl
6       =       models/player/group01/male_01.mdl
7       =       models/player/Group01/Male_02.mdl
8       =       models/player/Group01/male_03.mdl
9       =       models/player/Group01/Male_04.mdl
10      =       models/player/Group01/Male_05.mdl
11      =       models/player/Group01/Male_06.mdl
12      =       models/player/Group01/Male_07.mdl
13      =       models/player/Group01/Male_08.mdl
14      =       models/player/Group01/Male_09.mdl
Priest       models/player/magnusson.mdl
Control    table: 0xea2edfa0
1       =       models/player/alyx.mdl
Security        table: 0xea2f95d8
1       =       models/player/odessa.mdl
Police       table: 0xea2127a8
1       =       models/player/police.mdl
2       =       models/player/police_fem.mdl
S.W.A.T models/player/swat.mdl
S.W.A.T Sniper  models/player/riot.mdl
S.W.A.T Leader  models/player/urban.mdl
Weapon Dealer   models/player/monk.mdl
Blackmarket Dealer     models/player/barney.mdl
Drug Dealer   models/player/soldier_stripped.mdl
Car-Men   models/player/hostage/hostage_03.mdl
Miner        models/player/eli.mdl
Anus models/player/smith.mdl
Farmer  models/player/p2_chell.mdl
Cook    models/player/mossman.mdl
Hitman  models/player/leet.mdl
Gangster        table: 0xe9a01550
1       =       models/player/Group03/Female_01.mdl
2       =       models/player/Group03/Female_02.mdl
3       =       models/player/Group03/Female_03.mdl
4       =       models/player/Group03/Female_04.mdl
5       =       models/player/Group03/Female_06.mdl
6       =       models/player/group03/male_01.mdl
7       =       models/player/Group03/Male_02.mdl
8       =       models/player/Group03/male_03.mdl
9       =       models/player/Group03/Male_04.mdl
10      =       models/player/Group03/Male_05.mdl
11      =       models/player/Group03/Male_06.mdl
12      =       models/player/Group03/Male_07.mdl
13      =       models/player/Group03/Male_08.mdl
14      =       models/player/Group03/Male_09.mdl
Gangster Boss   models/player/gman_high.mdl
Rebell  models/player/phoenix.mdl
Rebell Boss   models/player/guerilla.mdl
Thief   models/player/arctic.mdl
Banker  models/player/hostage/hostage_01.mdl
Medic   models/player/kleiner.mdl
Lawyer  models/player/hostage/hostage_04.mdl
Taxi-Driver    models/player/hostage/hostage_02.mdl
Chief   models/player/combine_soldier_prisonguard.mdl
Jail Guard      models/player/combine_soldier.mdl
Mayor  models/player/breen.mdl
Hobo    models/player/corpse1.mdl
Hobo King       models/player/zombie_fast.mdl
Terrorist       models/jessev92/player/misc/osamabl1.mdl
Admin on Duty   models/player/combine_super_soldier.mdl
Owner on Duty   table: 0xe9894758
1       =       models/player/Lich_King_WoW_masked.mdl
2       =       models/player/Lich_King_WoW_maskless.mdl

**Comment by FPtje** [comment]
I approve of the "Anus" job. Other than that I don't see anything wrong with your jobs.

Is it possible in your server for players to have jobs that don't exist? (e.g. joining/connecting or something)

**Comment by deinemudda32** [comment]
The error only shows on playerinitialspawn or playerspawn( I dont know exactly ).

Original Jobs are in german, I translated them for this case. I didnt know a word and was too lazy to translate it with google translate ;P.

Even its not possible to have non existing Jobs.
Joining/Connecting is autoalligned on Join as far as I know. When Player is spawned -> Citizen. Normally.

**Comment by FPtje** [comment]
You **translated** the output!? What the fuck!? Give me the original output, unchanged.

**Comment by deinemudda32** [comment]
Im not that stupid.
I just changed the NAMES! nothing else.

**Comment by FPtje** [comment]
How is translating the output of a Lua command not stupid?

**Comment by deinemudda32** [comment]
Possibly of courtesy, who the hell wants to read German jobname as a Briton, Dutch or what you are?

**Comment by FPtje** [comment]
I care about an unmodified output. Other than that I don't give a shit about jobs. I'm saying you shouldn't modify the damn output of a command to translate it. Also, don't underestimate my German.

**Comment by deinemudda32** [comment]
lua_run for k, v in pairs(RPExtraTeams) do print(v.name, v.model) if istable(v.model) then PrintTable(v.model) end end
> for k, v in pairs(RPExtraTeams) do print(v.name, v.model) if istable(v.model) then PrintTable(v.model) end end...
Einwohner       table: 0xe98e7258
1       =       models/player/Group01/Female_01.mdl
2       =       models/player/Group01/Female_02.mdl
3       =       models/player/Group01/Female_03.mdl
4       =       models/player/Group01/Female_04.mdl
5       =       models/player/Group01/Female_06.mdl
6       =       models/player/group01/male_01.mdl
7       =       models/player/Group01/Male_02.mdl
8       =       models/player/Group01/male_03.mdl
9       =       models/player/Group01/Male_04.mdl
10      =       models/player/Group01/Male_05.mdl
11      =       models/player/Group01/Male_06.mdl
12      =       models/player/Group01/Male_07.mdl
13      =       models/player/Group01/Male_08.mdl
14      =       models/player/Group01/Male_09.mdl
Priester        models/player/magnusson.mdl
Zoll    table: 0xea2edfa0
1       =       models/player/alyx.mdl
Security        table: 0xea2f95d8
1       =       models/player/odessa.mdl
Polizist        table: 0xea2127a8
1       =       models/player/police.mdl
2       =       models/player/police_fem.mdl
S.W.A.T models/player/swat.mdl
S.W.A.T Sniper  models/player/riot.mdl
S.W.A.T Leader  models/player/urban.mdl
Waffen Dealer   models/player/monk.mdl
Schwarzmarkt Dealer     models/player/barney.mdl
Drogen Dealer   models/player/soldier_stripped.mdl
Mechatroniker   models/player/hostage/hostage_03.mdl
Bergmann        models/player/eli.mdl
Öl Raffinerist models/player/smith.mdl
Farmer  models/player/p2_chell.mdl
Koch    models/player/mossman.mdl
Hitman  models/player/leet.mdl
Gangster        table: 0xe9a01550
1       =       models/player/Group03/Female_01.mdl
2       =       models/player/Group03/Female_02.mdl
3       =       models/player/Group03/Female_03.mdl
4       =       models/player/Group03/Female_04.mdl
5       =       models/player/Group03/Female_06.mdl
6       =       models/player/group03/male_01.mdl
7       =       models/player/Group03/Male_02.mdl
8       =       models/player/Group03/male_03.mdl
9       =       models/player/Group03/Male_04.mdl
10      =       models/player/Group03/Male_05.mdl
11      =       models/player/Group03/Male_06.mdl
12      =       models/player/Group03/Male_07.mdl
13      =       models/player/Group03/Male_08.mdl
14      =       models/player/Group03/Male_09.mdl
Gangster Boss   models/player/gman_high.mdl
Rebell  models/player/phoenix.mdl
Rebellen Boss   models/player/guerilla.mdl
Dieb    models/player/arctic.mdl
Meisterdieb     models/player/arctic.mdl
Banker  models/player/hostage/hostage_01.mdl
Arzt    models/player/kleiner.mdl
Anwalt  models/player/hostage/hostage_04.mdl
Taxi-Fahrer     models/player/hostage/hostage_02.mdl
Chief   models/player/combine_soldier_prisonguard.mdl
Jail Guard      models/player/combine_soldier.mdl
Bürgermeister  models/player/breen.mdl
Hobo    models/player/corpse1.mdl
Hobo King       models/player/zombie_fast.mdl
Terrorist       models/jessev92/player/misc/osamabl1.mdl
Admin on Duty   models/player/combine_super_soldier.mdl
Owner on Duty   table: 0xe9894758
1       =       models/player/Lich_King_WoW_masked.mdl
2       =       models/player/Lich_King_WoW_maskless.mdl


Here is the Same Shit just in German for our princess over there.

**Comment by FPtje** [comment]
"Öl Raffinerist"? That's not an Anus! 

You lied!

**Comment by deinemudda32** [comment]
"I didnt know the word for "Zoll" and was too lazy to translate it with google translate ;P."
My text you probably didnt read :(.

(Yea actually it was Öl Raffinerist, but its not that different)

**Comment by unown294** [comment]
Also question for you falco, what part of the code line did i write
incorrectly?

**Comment by FPtje** [comment]
"PrintTable" instead of "PrintTable".

**Comment by deinemudda32** [comment]
I don't see any differences :P

**Comment by FPtje** [comment]
I have trouble misspelling things, even if I want to. It was "PrintTabel"

**Comment by unown294** [comment]
Oh shit your right i see the mistake. Just goes to show how easy you can
screw up sometimes

**Comment by unown294** [comment]
I wrote PrintTabel

**Comment by unown294** [comment]
Instead of PrintTable

**Comment by deinemudda32** [comment]
3 Messages in 1 Minute. Respect.

**Comment by FPtje** [comment]
Not when you actually *copy paste* things.

**Comment by unown294** [comment]
Well i read the message off my phone and typed into the server machine

**Comment by unown294** [comment]
Trying to load the internet off that machine is just tedious. It not a desk
top computer it an actual rack server

**Comment by deinemudda32** [comment]
So how about finding a solution for this Error.
I really want to watch Breaking Bad for now :) while eating Chips.

**Comment by Bo98** [comment]
An answer to this would be interesting:

> Does the equipping of job weapons (not default ones) work correctly on spawn when the error happens?

That would narrow it down to a job table problem or something specific to models.

**Comment by deinemudda32** [comment]
Yea it does as far as I know.
Cause I never got a guy complaining about he has no weapons.

**Comment by FPtje** [comment]
What do weapons have to do with the error anyway? The error is SetModel getting a nil value.

**Comment by Bo98** [comment]
Default weapons would still equip. I'm referring to weapons _specific_ to the job.

**Comment by deinemudda32** [comment]
Yea they do.

**Comment by deinemudda32** [comment]
As far as I can see its not a Error which is breaking Code.

**Comment by Bo98** [comment]
@FPtje If your theory of another method of getting your team set is true then it would likely affect weapons too.

**Comment by unown294** [comment]
So what happens is when you have the job that give you the red stick of
wonderful arrest it function as normal except on where it sends them. 2% of
the time it send them to the jail. And the other 98% of the time they get
sent to the various spawn point across the map

**Comment by FPtje** [comment]
That's not surprising. That's caused by the error.

**Comment by deinemudda32** [comment]
It doesnt only happens on arrest.

**Comment by unown294** [comment]
Well that what give me error that i posted about originally

**Comment by FPtje** [comment]
```
lua_run PrintTable(hook.GetTable().PlayerSetModel)

lua_run PrintTable(hook.GetTable().PlayerSpawn)
```

Run these two.

**Comment by deinemudda32** [comment]
k, Boss

**Comment by deinemudda32** [comment]
FAdmin_God      =       function: 0xe989b188
FAdmin_Log      =       function: 0xe990ae38
FAdmin_jail     =       function: 0xe98d1150
GhostMode       =       function: 0xe9bdcb08
HMPlayerSpawn   =       function: 0xe9b9e3e8
Knockout        =       function: 0xea1901c8
Loadout_BEModuleHook    =       function: 0xe9a387d8
Oil_SetOil      =       function: 0xe9bd5f18
Tazer   =       function: 0xe9c50320
ULXRagdollSpawnCheck    =       function: 0xea1bfdb0
UTeamSpawnAuth  =       function: 0xe9a09be8
drug_sober_up_cmd_spawn =       function: 0xe9b2bca0
r_playerspawn   =       function: 0xe39d8f18

**Comment by deinemudda32** [comment]
[ERROR] lua/includes/extensions/table.lua:711: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:711
    3. PrintTable - lua/includes/util.lua:42
     4. unknown - lua_run:1

SETMODEL

**Comment by FPtje** [comment]
Alright, this GhostMode thing, do both @deinemudda32 and @unown294 have it installed?

**Comment by unown294** [comment]
Ghostmode?

Well that what give me error that i posted about originally

**Comment by deinemudda32** [comment]
Im checking the Hook.

**Comment by FPtje** [comment]
So you both have that mod?

**Comment by deinemudda32** [comment]
Can't be it.
Just runs if CheckGhost Bool is true, and that does only happen if a player died.

**Comment by FrikenCanadiansEH** [comment]
Remove it and see what happens

**Comment by deinemudda32** [comment]
The Error only shows up every 3-4 Hours, I cant let retarted Guys play for 3-4 Hours without an NLR Modification.
AND DOUBLE ALSO I rewrote huge parts of the script including this function. -_-

**Comment by deinemudda32** [comment]
All it does is adding a NLR Zone, nothing different.

**Comment by FrikenCanadiansEH** [comment]
Hmm I wonder what you could do hmm..... Remove the bloody addon for lie 5 minutes and see if the issue persists if it doesn't then you have a problem, If it does come  back

**Comment by deinemudda32** [comment]
I already wrote that the Error doesnt appear every 5 minutes.

**Comment by FrikenCanadiansEH** [comment]
Just because that's how your NLR system works, Doesn't mean that the addon itself can't be causing an issue

**Comment by unown294** [comment]
I cant check it till 5pm. Im currently not at my house

**Comment by deinemudda32** [comment]
You mean the folder itself is creating the Error or What the Fuck?

**Comment by FrikenCanadiansEH** [comment]
*Facepalm* How about you just do as I asked and see if it works? Not like it will hurt to remove something temporarily

**Comment by deinemudda32** [comment]
You can give youreself two Facepalms for not enabling youre Brain.
What did I just told you? WHAT?

**Comment by FPtje** [comment]
He is Brain.

**Comment by deinemudda32** [comment]
We just ask the Issue Creator if he have the same Addon.
We currently dont know if this is really it. I will cooperate when it makes sense.

**Comment by FrikenCanadiansEH** [comment]
I will destroy your server with my superpowers :>

**Comment by deinemudda32** [comment]
Oh no, I have such a Costum Server with bought scriptfodder addons and abusive admins.
You want to be Admins, just 10$.

**Comment by FrikenCanadiansEH** [comment]
@deinemudda32 Ironically this is your server and I can see more as to why people flame on DarkRP owners

**Comment by deinemudda32** [comment]
Ironically you never was on my server and dont know anything.
I put alot of work in it.

**Comment by deinemudda32** [comment]
Not everyone is as in the books :)

**Comment by FPtje** [comment]
The books of DarkRP. Now out in your local fucking drama store.

Shut the fuck up and get back to business.

**Comment by deinemudda32** [comment]
Right, Right.

Did you find anything out?

**Comment by FPtje** [comment]
No.

**Comment by deinemudda32** [comment]
Is there a way I can display a Server Error for Clients too.
So I would know when the Error appears.

**Comment by FPtje** [comment]
Not that easily, no.

You can add a PlayerSetModel hook and print `ply:getJobTable()`, `ply:Team()` and `ply:getPreferredModel(ply:Team())`. Then, the next time the error occurs, we can look at that data and see how the error occurs.

**Comment by deinemudda32** [comment]
Good idea.

**Comment by deinemudda32** [comment]
hook.Add("PlayerSetModel", "TEST_DARKRP", function(ply)
     ply:getJobTable()
     ply:Team()
     ply:getPreferredModel(ply:Team())
end)

Would that work?

**Comment by FPtje** [comment]
Do I look like a god damn instance of GMod to you? Run it yourself!

**Comment by FPtje** [comment]
Also, **print** the damn results

**Comment by deinemudda32** [comment]
I already deleted it, before you can comment.
I knew your response :)

**Comment by FPtje** [comment]
```
hook.Add("PlayerSetModel", "TEST_DARKRP", function(ply)
    print(ply:getJobTable())
    print(ply:Team())
    print(ply:getPreferredModel(ply:Team()))
end)
```
Working not guaranteed.

**Comment by deinemudda32** [comment]
Yea yea. I got that already.

**Comment by deinemudda32** [comment]
I GOT IT!

**Comment by deinemudda32** [comment]
Arrest someone, Reconnect him -> ERROR :dancer:

**Comment by deinemudda32** [comment]
Output is 0, nil and ERROR

**Comment by HDG-MrDeeJay** [comment]
Oh god, 89 unread emails.

**Comment by Bo98** [comment]
glhf

**Comment by HDG-MrDeeJay** [comment]
Oh I'm already through them, I read them all (give or take) before replying.

**Comment by deinemudda32** [comment]
You got lucky. I had to hear the iPhone message sound for now 2 hours.

**Comment by FrikenCanadiansEH** [comment]
@deinemudda32 You wouldn't have to hear it if you knew how to manage your own server

**Comment by meepdarknessmeep** [comment]
I HAVE 100 NEW FUCKING EMAILS BECAUSE OF THIS 
FUCK OFF

**Comment by deinemudda32** [comment]
Who are you to tell me how to manage my server?

**Comment by HDG-MrDeeJay** [comment]
@deinemudda32 Nobody. Ignore him.

**Comment by FrikenCanadiansEH** [comment]
@HDG-MrDeeJay Rude, @deinemudda32 Someone who is sick and tired of DarkRP owners hosting a server yet not knowing how to fix the issue themselves,

**Comment by deinemudda32** [comment]
Its obivously not my Error.

**Comment by HDG-MrDeeJay** [comment]
@FrikenCanadiansEH Tbh you are the one on the attack path here.

@meepdarknessmeep and anyone else: ![Unsubscribe](https://i.gyazo.com/56f35b18a0c586e1a8031c74ab946b8c.png)

**Comment by meepdarknessmeep** [comment]
who are you telling me to hit a button on this very page?!

**Comment by deinemudda32** [comment]
Damn it guys, show some respect.

**Comment by SwadicalRag** [comment]
@meepdarknessmeep Nobody, ignore him.

**Comment by HDG-MrDeeJay** [comment]
Nobody. It's free advice, take it or leave it.

Speaking of leaving, toodles!

**Comment by FrikenCanadiansEH** [comment]
Well from what I can see I'm not having any issues with my latest version of DarkRP, So I can only assume it has to do with the scripts you decided to install

@HDG-MrDeeJay  True to a point

**Comment by deinemudda32** [comment]
A alot people now are having this issue and Im just trying to help resolve it.
I am not the Issue Creator either.
You do not have any right to punish me.

**Comment by HDG-MrDeeJay** [comment]
_Yeah guys, cmon this is getting off-topic._

**Comment by FrikenCanadiansEH** [comment]
@deinemudda32  How am I punishing you? One other person seems to have the same issues as you but has the same addon installed too

**Comment by deinemudda32** [comment]
Who said he has the same Addon?

**Comment by FrikenCanadiansEH** [comment]
He himself? He kind of implied it?

**Comment by deinemudda32** [comment]
I dont think so, as the Error makes no sense regarding to this script

**Comment by deinemudda32** [comment]
I already checked everything, the Addon isnt creating the Error.

**Comment by FrikenCanadiansEH** [comment]
Did you do as I said and removed it and restarted and tried arresting again?

**Comment by deinemudda32** [comment]
Well okay, now that we know how to reproduce it, I can try it.

**Comment by deinemudda32** [comment]
Error still happening.

**Comment by unown294** [comment]
Oh for fuck sakes both of you quit your bitchin and actual help out in
solving this issue.

**Comment by deinemudda32** [comment]
We are trying to resolve the Issue and Yeah I wasnt trying to offend anyone.

**Comment by SwadicalRag** [comment]
![meme](http://images.rapgenius.com/497sj3akr8x20317bwdmu0vd5.960x720x1.jpg)

**Comment by unown294** [comment]
I mean falco is taking the time to help us fix the problem. So instead of
fighting about your server help him in trying to fix this main issue

**Comment by deinemudda32** [comment]
We are not fighting about my server, we are fighting about if i am a good owner :D

**Comment by unown294** [comment]
Ok this is for posting about issues not how good of a server owner you are

**Comment by unown294** [comment]
Also can someone recomment the stuff you all have been typing in the console

**Comment by unown294** [comment]
Ive lost track in the sea of comments

**Comment by deinemudda32** [comment]
I made tests and found out when the Error is happening, while you called that Finding out how good of a server owner I am.

The Error happens when someone is arrested and reconnects while Arrested.

**Comment by unown294** [comment]
Ill need to see if get that same error to

**Comment by unown294** [comment]
So we found the solution. Every class had to have its own individual spawn for a jailpos which i didnt know as the instruction for setting it say only use it one time but we fixed it with just switching to each class and setting a jail pos for each class. If i happen to get more line:502 errors ill send em your way as im happy to help with giving refernce material on a mod that keeps on getting better. Thank you for the time you took to help me falco and may i say you do a fantastic job of coding.

**Comment by HDG-MrDeeJay** [comment]
Isn't jailpos non-class specific?

**Comment by deinemudda32** [comment]
Yea it is.

**Comment by FPtje** [comment]
Bug reproduced.

**Comment by FPtje** [comment]
Thanks @deinemudda32 for finding the damn bug.

**Comment by Bo98** [comment]
Doesn't really explain the issue the reporter of this issue had though.

**Comment by deinemudda32** [comment]
Just drop the topic, please :P

**Comment by FPtje** [comment]
It happens when a player has its model set with an invalid job.

**Comment by maissani** [comment]
I experience the same issue : 
 
Full Stack of errors: 
ServerLog: Chipsy (STEAM_0:1:95815826) is Authed
L 10/31/2015 - 14:06:30: Chipsy (STEAM_0:1:95815826) is Authed
[CAC] 320:47.338 PlayerInformation:Load : Cannot handle version 0 files. Current version is 1.

ServerLog: Chipsy (STEAM_0:1:95815826) Spawned for the first time
L 10/31/2015 - 14:06:30: Chipsy (STEAM_0:1:95815826) Spawned for the first time
L 10/31/2015 - 14:06:30: Lua Error: 
[ERROR] addons/emining/lua/autorun/core.lua:63: attempt to index local 'Data' (a nil value)
  1. LoadSkills - addons/emining/lua/autorun/core.lua:63
   2. fn - addons/emining/lua/autorun/core.lua:43
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179



[ERROR] addons/emining/lua/autorun/core.lua:63: attempt to index local 'Data' (a nil value)
  1. LoadSkills - addons/emining/lua/autorun/core.lua:63
   2. fn - addons/emining/lua/autorun/core.lua:43
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179


[ERROR] addons/emining/lua/autorun/core.lua:63: attempt to index local 'Data' (a nil value)
  1. LoadSkills - addons/emining/lua/autorun/core.lua:63
   2. fn - addons/emining/lua/autorun/core.lua:43
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

ServerLog: Chipsy (STEAM_0:1:95815826) Spawned
L 10/31/2015 - 14:06:30: Chipsy (STEAM_0:1:95815826) Spawned
L 10/31/2015 - 14:06:30: Lua Error: 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502: bad argument #1 to 'SetModel' (string expected, got nil)
  1. SetModel - [C]:-1
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:668



[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502: bad argument #1 to 'SetModel' (string expected, got nil)
  1. SetModel - [C]:-1
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:668


[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502: bad argument #1 to 'SetModel' (string expected, got nil)
  1. SetModel - [C]:-1
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:502
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:668

**Comment by deinemudda32** [comment]
Then update DarkRP.

**Comment by maissani** [comment]
I am on thé last version of darkrp, with the last commited change.
