### ISSUE TITLE
Make a file in a darkrp module folder to be included first

### ISSUE THREAD

**Issue by fruitwasp** [FPtje/DarkRP#2181]
In the current situation you do not know what file is included first. I would like this to be possible.

**Comment by FPtje** [comment]
You do know. Shared first, then server/client.

**Comment by fruitwasp** [comment]
You do not know the order of the server or client files.

**Comment by FPtje** [comment]
Yes you do, they are sorted by name. If you're not sure of that you can still make a subfolder and do all the including and AddCSLuaFiling yourself.
