### ISSUE TITLE
Unarrest not relocating people

### ISSUE THREAD

**Issue by unown294** [FPtje/DarkRP#2182]
So i have a little nit picky issue that i can describe but has no errors whats so ever. So when you get arrested you end up in the jail for x amount of time or until someone unarrest you. So when someone or the time runs out that unarrest you it doesnt send them to a new location and just either leaves them in place still stuck in jail or if they were out side the jail for some reason it does it on the spot. Now there are no

**Comment by unown294** [comment]
- issues or error popping up in console so the code is functioning like it should but it doesnt do the task we need it to do which is get them out of jail if they correctly got arrested and were sent there. Now if anyone know how to change this please let me know asap as it been bugging me for the last week that ive spent trying to fix it

**Comment by FPtje** [comment]
Works for me.

**Comment by unown294** [comment]
Yes i know it works but im asking about how the location it is suppose to
send people i change because it fails to do that on my version of darkrp

**Comment by unown294** [comment]
The function of unarresting people isnt broke. What im bothered by is how it does not relocate them to say spawn and ends up leaving them in the jail.

**Comment by unown294** [comment]
Im having the similair issue as when you were solving the issue #405

**Comment by FPtje** [comment]
That's exactly what I'm saying works for me

**Comment by unown294** [comment]
Well its not for me

**Comment by FPtje** [comment]
There can be a bunch of things in your server that break it. Ranging from shitty addons that fuck shit up to you simply having the telefromjail setting set to false.

This issue is invalid until you prove that I'm responsible for it.

**Comment by unown294** [comment]
I never said you were responsible. I only ask for either how it should work
or is there something in the lua that i have to change to make it do what i
originally stated.

**Comment by unown294** [comment]
I thought i clearly stated all i wanted was help or suggestions to if i was doing something wrong

**Comment by FPtje** [comment]
This is not a god damn help forum.

forum.darkrp.com

**Comment by unown294** [comment]
The what is it

**Comment by meepdarknessmeep** [comment]
github

**Comment by unown294** [comment]
Again what the meaning of the issues tab if it not for solving issues people have

**Comment by FPtje** [comment]
Your inability to understand the purpose of big trackers does not excuse
your persistence after being told to go elsewhere. Fuck off.

**Comment by meepdarknessmeep** [comment]
this is for issues reguarding the gamemode - not reguarding you

**Comment by unown294** [comment]
It is in regards to the gamemode. But it pointless to ask the person who
made the mode it self for such a simple answer and instead go "oh no he
posted on the wrong place let me not try to help him with his issue and be
a dick about it

**Comment by FPtje** [comment]
I have every right and reason to be a dick. You failed to read the contribution guidelines and persisted even when I told you to go elsewhere.

Your persistence in demanding help demonstrates that you do not understand kind words.

**Comment by unown294** [comment]
Have a fuckin fabulous day falco

**Comment by unown294** [comment]
Thanks for no help in such a simple matter

**Comment by FPtje** [comment]
Goodbye

**Comment by HDG-MrDeeJay** [comment]
Wow what a fucking grade A retard
