### ISSUE TITLE
DarkRP job.lua problem

### ISSUE THREAD

**Issue by eldor1274** [FPtje/DarkRP#2183]
I am having a lot of problems with this file.
   --[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------
This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.
Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
	Once you've done that, copy and paste the job to this file and edit it.
The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua
For examples and explanation please visit this wiki page:
http://wiki.darkrp.com/index.php/DarkRP:CustomJobFields
Add jobs under the following line:
---------------------------------------------------------------------------]]

TEAM_THIEF = DarkRP.createJob("Thief", {
    color = Color(153,153,51, 255),
    model = "models/player/group03/male_02.mdl",
    description = [[You are a thief, rob people, lockpick their house and steal their plants and legal printers.]],
    weapons = {"lockpick"}, -- You may wanna find a pickpocket swep and add it here.
    command = "thief",
    max = 6,
    salary = 65,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Thief",
})

TEAM_SWAT = DarkRP.createJob("Swat", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/01AR_combine_soldier01.mdl"},
    description = [[The protector of every citizen that lives in the city.
        You have the power to arrest criminals and protect innocents.
        Hit a player with your arrest baton to put them in jail.
        Bash a player with a stunstick and they may learn to obey the law.
        The Battering Ram can break down the door of a criminal, with a warrant for their arrest.
        The Battering Ram can also unfreeze frozen props (if enabled).
        Type /wanted <name> to alert the public to the presence of a criminal.]],
    weapons = {"arrest_stick", "unarrest_stick", "m9k_ak47", "stunstick", "door_ram", "weaponchecker", "handcuffs", "m9k_spas12"},
    command = "Swat",
    max = 4,
    salary = 85,
    admin = 0,
    vote = true,
    hasLicense = true,
    category = "Civil Protection",
})

TEAM_MD = DarkRP.createJob("Mayors Daughter", {
    color = Color(255,100,100,255),
    model = "models/player/alyx.mdl",
    description = [[You are the mayors daughter, walk around with your dad
                just chill around. But be careful, you never know when somebody
                is waiting to kidnap you!]],
    weapons = {},
    command = "mayorsdaughter",
    max = 1,
    salary = 80,
    admin = 0,
    vote = false,
    hasLicense = false
})

TEAM_SPECIALFORCES = DarkRP.createJob("Special Air Services", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/01AR_combine_soldier01mdl"},
   description = [[You are called in as a last resort, If the thugs and criminals take over you are called in. Don't fuck this up.]],
   weapons = {"m9k_knife","m9k_m416","m9k_m92beretta","m9k_m61_frag","laserpointer"},
   command = "SAS",
   max = 2,
   salary = 100,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizen",
})

TEAM_GERMANEXTRIMIST = DarkRP.createJob("German Extrimist", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/dod_german.mdl"},
   description = [[You are a German Extremist. Practically a Nazi. Kidnap Jews kill them]],
   weapons = {"weapon_fists","m9k_luger"},
   command = "German",
   max = 5,
   salary = 5,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizen",
})

TEAM_AMERICANEXTRIMIST = DarkRP.createJob("American", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/dod_american.mdl"},
   description = [[You are an American. You believe that you are still in the world war II. Stop the germans and protect the jews]],
   weapons = {"weapon_fists","m9k_colt1911"},
   command = "American",
   max = 5,
   salary = 10,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizen",
})

TEAM_STRIPPER = DarkRP.createJob("NuttySlut", {
   color = Color(232, 29, 29, 255),
   model = {"models/player/p2_chell.mdl"},
   description = [[Pole Stripping Massacre]],
   weapons = {"weapon_fists"},
   command = "Strip",
   max = 2,
   salary = 10,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   -- CustomCheck
   medic = true,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizens",
})

TEAM_MEDIC = DarkRP.createJob("Rouge Medic", {
   color = Color(110, 200, 206, 255),
   model = {"models/player/anon/anon.mdl"},
   description = [[]],
   weapons = {"weapon_medkit", "weapon_fists", "brax_crowbar"},
   command = "medicrouge",
   max = 3,
   salary = 30,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   -- CustomCheck
   medic = true,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Other",
})

TEAM_BANKER = DarkRP.createJob("Banker", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/magnusson.mdl"},
   description = [[Set up shop in the bank and get paid to look after other peoples property. look after it even if it is illegal]],
   weapons = {"weapon_fists"},
   command = "Banker",
   max = 2,
   salary = 50,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizen",
})

TEAM_POLICESNIPER = DarkRP.createJob("Police Sniper", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/riot.mdl"},
   description = [[Provide long range support for the police and swat]],
   weapons = {"m9k_m14sp","m9k_remington7615p"},
   command = "Sniper",
   max = 2,
   salary = 80,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civil Protection",
})

TEAM_HEAVYSWAT = DarkRP.createJob("Heavy Swat", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/01AR_combine_soldier01.mdl"},
   description = [[For those sticky situations were the swat need a little bit of help]],
   weapons = {"m9k_m249lmg","m9k_m29satan"},
   command = "Heavy",
   max = 2,
   salary = 70,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civil Protection",
})

TEAM_TERMINATOR = DarkRP.createJob("Terminator", {
   color = Color(234, 95, 128, 255),
   model = {"models/player/arnold_schwarzenegger.mdl"},
   description = [[You are here to save the world! or destroy it...]],
   weapons = {"m9k_minigun"},
   command = "Terminator",
   max = 2,
   salary = 100,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = false,
})

TEAM_FBI = DarkRP.createJob("FBI Agent", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/urban.mdl"},
   description = [[You are above the Swat and police. You are called in for the situations the Swat cant handle]],
   weapons = {"m9k_m416","m9k_hk45","m9k_intervention"},
   command = "FBI",
   max = 4,
   salary = 500,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civil Protection",
})

TEAM_PRIEST = DarkRP.createJob("Priest", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/Barney.mdl"},
   description = [[Start a church of your own religion. Attend the Marriage ceremonys that are hosted at a church. ]],
   weapons = {},
   command = "Priest",
   max = 4,
   salary = 40,
   admin = 0,
   vote = true,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizens",
})

TEAM_BOUNTY = AddExtraTeam("Bounty Hunter", {
	color = Color(125, 125, 256, 252),
	model = "models/Agent_47/agent_47.mdl",
	description = [[As a bounty hunter its your job to find wanted players and
	take them down to the station.
	
	SALARYL:50]],
	weapons = {"hl2_combo_fists", "m9k_scoped_taurus"},
	command = "bounty",
	max = 1,
	salary = 50,
	admin = 0,
	vote = false,
     hasLicense = true
})

TEAM_FIGHT = AddExtraTeam("Fight Club Manager", {
	color = Color(125, 125, 200, 255),
	model = "models/player/Group01/male_02.mdl",
	description = [[As a fight club manager you can set up your fight club
	on any state you buy. Both players must agree to the fight clubs terms
	before any pvp fights occur.
	
	SALARYL:45]],
	weapons = {"hl2_combo_fists"},
	command = "fight",
	max = 1,
	salary = 45,
	admin = 0,
	vote = false,
	hasLicense = false
})

TEAM_SS = DarkRP.createJob("Secret Service", {
    color = Color(100, 20, 20, 255),
    model = "models/player/smith.mdl",
    description = [[You are responsible for protecting the mayor.
    Take care of the old fellow, he is vanuarable to terrorists all the time! Before he enters a room, you need to make sure its secure.]],
    weapons = {"m9k_mp7", "stunstick", "weaponchecker"},
    command = "ss",
    max = 2,
    salary = 65,
    admin = 0,
    vote = true,
    hasLicense = false,
    category = "Civil Protection",
        ammo = {
        ["pistol"] = 60,
    }, 
    
})

TEAM_PROTHIEF = AddExtraTeam("Pro Thief", {
	color = Color(111, 199, 175, 255),
	model = "models/player/group01/cookies114.mdl",
	description = [[Your are a pro thief, Brake into peoples homes
and places of business to piss them off!
Take what you can and run!
You may not shoot people in there own only in robbery.
homes or places of business. only in robbery.
to shoot you!. 
	
	SALARY:60]],
	weapons = {"fastkeypad_cracker", "fastlockpick", "hl2_combo_fists", "rp_pickpocket"},
	command = "prothief",
	max = 3,
	salary = 60,
	admin = 0,
	vote = false,
	category = "Thief",
     hasLicense = false
})

TEAM_NINJA = AddExtraTeam("Ninja", {
	color = Color(255, 93, 0, 255),
	model = "models/player/charple.mdl",
	description = [[As a ninja you can jump from building
	to building with you grapling hook. But be careful
	because grapling hook is not leagel. 
	
	SALARY:90]],
	weapons = {"hl2_combo_fists", "spiderman's_swep", "m9k_damascus"},
	command = "ninja",
	max = 2,
	salary = 65,
	admin = 0,
	vote = false,
     hasLicense = false
})

TEAM_ADMIN = AddExtraTeam("Admin On Duty", {
	color = Color(100, 100, 100, 255),
	model = {
	"Models/player/hobo387/XEbatman.mdl",
	},
	description = [[Help people]],
	weapons = {"hl2_combo_fists"},
	command = "admin",
	max = 3,
	salary = 1000,
	admin = 0,
	vote = false,
	hasLicense = true,
     category = "Staff",     
     customCheck = function(ply)
                  return ply:IsSuperAdmin() or ply:IsUserGroup("admin") or ply:IsUserGroup("sadmingolddonator") or ply:IsUserGroup("developer") or ply:IsUserGroup("headadmin") or ply:IsUserGroup("junioradmin") or ply:IsUserGroup("trialadmingolddonator") 
        end
})

TEAM_OWNER = DarkRP.createJob("Owner", {
   color = Color(255, 183, 0, 255),
   model = {"models/player/miku.mdl"},
   description = [[You are the owner FIX SHIT.]],
   weapons = {},
   command = "Owner",
   max = 3,
   salary = 1000,
   admin = 2,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = true,
   mayor = true,
   hobo = false,
   cook = false,
   category = "Staff",
})

--
[[---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------]]
GAMEMODE.DefaultTeam = TEAM_CITIZEN

--[[---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------]]
GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = true,
	[TEAM_CHIEF] = true,
	[TEAM_MAYOR] = true,
}

--[[---------------------------------------------------------------------------
Jobs that are hitmen (enables the hitman menu)
---------------------------------------------------------------------------]]
DarkRP.addHitmanTeam(TEAM_HITMAN)
 
And these problems pop up: [ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua" on line 423.
The best help I can give you is this:

Something is being called like it is a function, but in reality it is a number.

Hints:
	- You are doing something(<otherstuff>). The 'something' here is not a function.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 423
	2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80
	3. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 137
	4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 148
	5. gamemodes/darkrp/gamemode/init.lua on line 82
------- End of Simplerr error -------

**Comment by HDG-MrDeeJay** [comment]
HOLY MOTHER OF FUCK can you please use pastebin?

**Comment by HDG-MrDeeJay** [comment]
Also wtf extremist jobs? Is this an ISIS recruitment server?

**Comment by HDG-MrDeeJay** [comment]
For anyone attempting to debug his shitty issue, line 423 appears to be a few lines after the end of TEAM_OWNER.

**Comment by HDG-MrDeeJay** [comment]
Found your shitty problem.

![Original](https://i.gyazo.com/22789efbf9960396ca7a9e71f41df591.png)
should be
![Fixed](https://i.gyazo.com/6ca3f5d132c452d2476eec69a07863dd.png)

**Comment by HDG-MrDeeJay** [comment]
And next time when you screw up your jobs, fuck off to forum.darkrp.com

**Comment by eldor1274** [comment]
Listen u cunt I needed help I wasnt sure what happend you fucker just help
and stfu idc what u think dumb ass.

**Comment by BillyOnWiiUIn144p** [comment]
judging by your spectacular language choices I'd say you are clearly very intelligent

**Comment by LetsRaceBwoi** [comment]
what a sore asshole.  you can't even respond nicely to the guy that fixed the problem that you'd had for, well, probably 3-4 hours because you're that fucking dumb.

**Comment by FPtje** [comment]
Why the fuck did this cunt even bothered with a 3 month old shit issue?

**Comment by BillyOnWiiUIn144p** [comment]
Apparently he got the email late...?
![Email](http://i.imgur.com/w596g44.png)

**Comment by LetsRaceBwoi** [comment]
or he's just a faggot
