### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2185]
I would suggest to add damage to the "Sleeping Player"-Ragdoll, because in alot of cases the command is abused to get no damage, falldamage etc.

**Comment by FPtje** [comment]
That's already being done.

**Comment by FPtje** [comment]
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/sleep/sv_sleep.lua#L166

**Comment by deinemudda32** [comment]
Sorry, thought it didnt get a change, but you proofed I was wrong.
