### ISSUE TITLE
Money for arresting players

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2187]
I know its easy to do myself, but I think this should be added to enhance the gameplay as cop in DarkRP general.

**Comment by TylerGeorges** [comment]
This'll only encourage constant RDA.

I'll make it, but I'm not sure it'll get accepted.

**Comment by deinemudda32** [comment]
RDA'er mostly arent Wanting players.

**Comment by TylerGeorges** [comment]
Actually, I might need to add a config to toggle weather players can receive money for arresting.

**Comment by FPtje** [comment]
Yeah, like drop money on death did. Nonsense.
