### ISSUE TITLE
weird things in door display

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2190]
sometimes a door is for sell, but it shows you: 
"Owner: "

if a user is behind a door and you take a look at the door, it doesnt display text at all.

thats such messed up, I literally cant really explain it.

**Comment by HDG-MrDeeJay** [comment]
This sounds like two separate bugs, and the first one involves the owner 
of the door disconnecting with co-owners that have purchased access to 
the door. It's been present since 2.4.3 and has been difficult to reproduce.

**Comment by deinemudda32** [comment]
yea these two are different.

maybe instead of using tables.
Use a Draw hook for checking if the status is valid.

**Comment by FPtje** [comment]
I can't reproduce the other issue.

**Comment by 00875** [comment]
![2015-09-30_00019](https://cloud.githubusercontent.com/assets/6339511/10449312/f4a8cbb8-71bc-11e5-8a45-d262faa2ff18.jpg)
Eh...

**Comment by Bo98** [comment]
While looking at an affected door, try running this (in client console) and paste the output here:

```lua
lua_run_cl local d = LocalPlayer():GetEyeTrace().Entity print("isKeysOwned: ", d:isKeysOwned(), "\ncoOwners: ", table.GetFirstValue(d:getKeysCoOwners() or {}), "\ndoorTeams: ", d:getKeysDoorTeams(), "\ndoorGroups: ", d:getKeysDoorGroup())
```

**Comment by 00875** [comment]
![2015-10-13_15-24_h-srv-gm_darkrp-garrysmod-add](https://cloud.githubusercontent.com/assets/6339511/10449545/7ec65094-71be-11e5-8bd4-3d5f9b04696d.jpg)
There are already

**Comment by FPtje** [comment]
That's not the official DarkRP hud. You've given proof that something is broken in your own DrawOwnableInfo.

**Comment by Bo98** [comment]
I mean running that command I posted will print out some values so we can find out what part of the door system is breaking rather than just "something to do with owning".

**Comment by 00875** [comment]
DrawOwnableInfo running your original function but in different way

**Comment by 00875** [comment]
![2015-10-13_00001](https://cloud.githubusercontent.com/assets/6339511/10449608/e1ca0992-71be-11e5-814e-48a932dd8994.jpg)
Screenshot from current game.

**Comment by Bo98** [comment]
When it happens again, run the command I gave and it will print some values in the console. It doesn't impact the door in any way but merely for debugging what the issue is.

**Comment by deinemudda32** [comment]
I have the same problem, and well I dont have some modification for it.
