### ISSUE TITLE
Suggestion received money hook

### ISSUE THREAD

**Issue by kulcris** [FPtje/DarkRP#2194]
Add a hook to tell when someone recieved money (be it from killing an npc or money printer)

playerrecievedmoney(ply, amount)

with a way to alter the amount received before they receive it

**Comment by Bo98** [comment]
http://wiki.darkrp.com/index.php/Hooks/Server/playerWalletChanged

**Comment by kulcris** [comment]
oh derp thanks

**Comment by kulcris** [comment]
any way to check if the money is from a picking it up from a ground or "given"?

**Comment by AMD-NICK** [comment]
@kulcris 

local function MoneyDroped(sum)
	if sum < 0 then return true
	end
end

**Comment by kulcris** [comment]
sorry i would like to create a percentage boost to money gained by players of a certain group.
BUT i do not want money pickup up off the ground to be boosted due to the likelyhood that someone will just drop money and pick it back up in order to abuse the boost.
