### ISSUE TITLE
Door issues(again)

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2195]
I have weird issues again.

Some doors say: owned by "".
Some doors have titles but are sold.

Happend as I connected to the server, the doors were previously owned but then all sold.

**Comment by FPtje** [comment]
You should know by now that I need a specific means of reproduction. Failure to adhere to these standards will have your issues closed each god damn time.

**Comment by deinemudda32** [comment]
I dont know a way to reproduce, they just exist.

**Comment by deinemudda32** [comment]
I found out a way.

Add a co-owner to a door with title.
Disconnect, co-owner sells door -> Title bug.

**Comment by FPtje** [comment]
![2015-10-15_22-16-40](https://cloud.githubusercontent.com/assets/1202014/10526376/ce9b8f6c-738a-11e5-9647-32591f04990d.jpg)
![2015-10-15_22-16-43](https://cloud.githubusercontent.com/assets/1202014/10526378/cfedf864-738a-11e5-96ac-82e661ec0db1.jpg)
![2015-10-15_22-17-55](https://cloud.githubusercontent.com/assets/1202014/10526379/d133a9da-738a-11e5-8368-5da22793db3f.jpg)
![2015-10-15_22-18-17](https://cloud.githubusercontent.com/assets/1202014/10526380/d24c7004-738a-11e5-9c8b-757a78a5a02a.jpg)
bot selling:
![2015-10-15_22-18-46](https://cloud.githubusercontent.com/assets/1202014/10526383/d46f99ce-738a-11e5-8393-70253ed2b308.jpg)
bot kicked:
![2015-10-15_22-18-58](https://cloud.githubusercontent.com/assets/1202014/10526386/d5f455fa-738a-11e5-972e-3976aff6659c.jpg)

Neither issue is reproduced.

Kicking the bot while it still co-owns the door also works as expected. But not reproduced.

**Comment by deinemudda32** [comment]
No the owner has to disconnect, not the co-owner.

**Comment by deinemudda32** [comment]
Only works on dedicated servers, however.

**Comment by FPtje** [comment]
> Then co-owner disconnects -> Owned by: "" bug.

> Then co-owner disconnects -> Owned by: "" bug.

## Then co-owner disconnects -> Owned by: "" bug.

# "co-owner"

**Comment by deinemudda32** [comment]
I meant owner, sorry. 
Yea I give myself a dumb :/

**Comment by FPtje** [comment]
Next time report issues properly and be clear. You're pissing me off.

**Comment by deinemudda32** [comment]
Yea..
