### ISSUE TITLE
DarkRP logs stop working at random times

### ISSUE THREAD

**Issue by Devul** [FPtje/DarkRP#2197]
My server uses DarkRP's logs to log all actions, but for a strange reason logs stop working after random times. It works after server restart, but for 10-20 minutes. And then sometimes it comes back on to working again, and then randomly stops again. 

I'm not sure if this is just me, but it could be an issue other people are having. It's why I put this issue up.

I created a module to insert logs into a table every time a log is given to the player. Could that be the culprit?

Here's the code just to be safe.

```lua
hook.Add("DarkRPLogPrinted", "log", function(log, colour)
	if logsTotal > 1000 then
		table.remove(logs, 1)
		logsTotal = logsTotal - 1
	end

	if colour == Color(255, 255, 255, 255) then colour = Color(0, 0, 0, 255) end

	table.insert(logs, {
		log = log,
		colour = colour,
		time = os.date("%H:%M:%S")
	})
	logsTotal = logsTotal + 1

	if IsValid(viewFrame) then viewFrame.logView:Refresh() end
	if IsValid(fruitConsole) then
		if string.find(log, "damage") and not GetConVar("fruit_console_showdamagelogs"):GetBool() then return end

		fruitConsole.text:InsertColorChange( colour.r, colour.g, colour.b, 255 ) fruitConsole.text:AppendText( log )
	end
end)
```

**Comment by FPtje** [comment]
I'm not going to chase ghosts. I need errors, ways to reproduce, etc. 

For all I know you have an addon with some hook that returns a value.

**Comment by Devul** [comment]
I have no errors. To reproduce you simply log stuff.

I have no addons that return with the DarkRPLogPrinted hook. I made sure of that.
