### ISSUE TITLE
Odd shipments issue

### ISSUE THREAD

**Issue by jeep70** [FPtje/DarkRP#2199]
I am putting together a FA:S 2 server, but there is an odd issue with shipments. Only the individual weapons actually appear in the menu, and not any of the shipments. I can fix this by creating another separate shipment with individual weapons disabled, and disable shipments on it's counterpart (making two createShipments, one for the shipment, and one for the individual weapon). I can leave all the rest of them as both the shipment and the individual gun in one.
shipments.lua: http://hastebin.com/urovalibog.lua
categories.lua (if it matters): http://hastebin.com/cenefayute.lua

**Comment by FPtje** [comment]
Well yes, you set separate to true.

**Comment by FPtje** [comment]
Also, this is not a help forum. Please go to forum.darkrp.com
