### ISSUE TITLE
I cant drop money

### ISSUE THREAD

**Issue by Doctorcz** [FPtje/DarkRP#2201]
I have CSS mounted but if i do /dropmoney (amount) it will remove (amount) from wallet but it will not drop on floor (DARKRP 2.5)
Please help

**Comment by FPtje** [comment]
not a help forum.

Also, you're probably lying and/or wrong about CSS being mounted.
http://mounted.darkrp.eu/

forum.darkrp.com

**Comment by Doctorcz** [comment]
i figured this out (reinstalled gamemode)
