### ISSUE TITLE
Microwave + Druglab

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2202]
Microwave:
The microwaves food price is defined in the config as GM.Config.microwavefoodcost = X.

However I tested around and the defined price is never used.
It always takes 80% of the price as food price.

Screenshot: http://puu.sh/kVKov/9e894ba6a7.jpg

Tested on newest version.(just darkrpmodification)

Druglab:
The druglab doesnt have a price for the drugs set up its automatically some "random" price defined in the entity.

**Comment by FPtje** [comment]
Yes, because you're the owner of the microwave.

```lua
function ENT:SalePrice(activator)
    local owner = self:Getowning_ent()

    if activator == owner then
        if self.allowed and type(self.allowed) == "table" and table.HasValue(self.allowed, activator:Team()) then
            return math.ceil(self:Getprice() * 0.8)
        else
            return math.ceil(self:Getprice() * 0.9)
        end
    else
        return self:Getprice()
    end
end
```

**Comment by deinemudda32** [comment]
For what is the config option GM.Config.microwavefoodcost then?

**Comment by FPtje** [comment]
The initial price, returned by `self:Getprice()` in the code above.
