### ISSUE TITLE
Taxes

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2207]
Would be good if there would be some Hook to prevent Selling Doors/Vehicles by Taxes.

Like playerSellVehicle hook.

**Comment by FPtje** [comment]
http://wiki.darkrp.com/index.php/Hooks/Shared/canBuyVehicle
http://wiki.darkrp.com/index.php/Hooks/Server/playerBuyDoor

After all this god damn time you've been around, you *still* are unable to search the wiki?

**Comment by FPtje** [comment]
http://wiki.darkrp.com/index.php/Hooks/Server/playerSellDoor
http://wiki.darkrp.com/index.php/Hooks/Server/playerSellVehicle

**Comment by deinemudda32** [comment]
Doesnt work if the Door is sold by taxes.

**Comment by FPtje** [comment]
so you want a property tax hook

**Comment by deinemudda32** [comment]
Yea ^^
