### ISSUE TITLE
Hook canForcesellproperty

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2208]
Hook should be called on forcing the player to sell all his doors, which he cannot prevent.

I originally wanted the Tax hook being able to prevent selling a few doors.

**Comment by deinemudda32** [comment]
Hook name is not that good.

**Comment by FPtje** [comment]
Did you not read the wiki page?

http://wiki.darkrp.com/index.php/Hooks/Server/canPropertyTax

Return false, god damnit.

**Comment by deinemudda32** [comment]
But it cant return false for mabye 1 of 5 doors.
It just can return false for everything

**Comment by FPtje** [comment]
return false and tax shit yourself.

**Comment by FPtje** [comment]
I'm not going to make a hook to cater to your incompetence

**Comment by deinemudda32** [comment]
I just thought it would be easier that way.
But its your decision, as always.
