### ISSUE TITLE
Shipments.Lua isn't working correctly

### ISSUE THREAD

**Issue by Hodasboy** [FPtje/DarkRP#2210]
Hey, I've tried to put some shipments like M9K weapons + some kevlars in to shipments.lua but I always get This shipment is unavaible. I used same method as in 2.6.1 but now in 2.6.2 (up-to-date with Github) this issue came up. I've tried with customAddShipment and DarkRP.createShipment methods but both gives the same issue. Items do show in F4 menu as should but not purchasable. If I put weapon in entities.lua then it works but cannot be stored in inventory with out being shipment.

Here's link to my Shipments.Lua file: http://paste.ee/p/MEAnl

I put them inside --[[ --]] to avoid them being in-game until they work.

As when it comes to errors I havent seen any in console. this is the only thing that comes up: "[DarkRP] This shipment is unavailable"

**Comment by immibis** [comment]
Let me save FPtje a few seconds:

This is not a help forum.

**Comment by FPtje** [comment]
Not a help forum.

**Comment by FPtje** [comment]
Wait, I'll look at it to make sure it's not a bug.

**Comment by FPtje** [comment]
I tried a couple and it works for me.
