### ISSUE TITLE
AFK, again

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2215]
Go AFK.
Job-Payment = 0$ (Hobo)

Get out of AFK.
Jop-Payment = 0$ (Citizen)

Be hobo.
Job-Payment = 0$

Switch to citizen again.
Jop-Payment = 35$

**Comment by deinemudda32** [comment]
I noticed that sometimes people dont get afk demoted at all.

**Comment by FPtje** [comment]
Why the fuck are you not saying that you have to force someone to switch teams while AFK.

That's the most important god damn part of the fucking bug. I've spent ages trying to go AFK as a citizen AND hobo and back.
