### ISSUE TITLE
Scoreboard Bugs

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2222]
The SteamID is not fully shown on my Display.

Just shows: STEAM_0...

-

If you open the scoreboard and rapidly close it again, all player columns stay on the screen while everything else of the scoreboard is hidden.

If you reopen the scoreboard, the issue is fixed.

hint: mostly lags in such situations.

**Comment by FPtje** [comment]
I cannot reproduce the column thing

**Comment by deinemudda32** [comment]
I cannot either.
It happens randomly.
