### ISSUE TITLE
cl_entityvars.lua error

### ISSUE THREAD

**Issue by DarkWolfInsanity** [FPtje/DarkRP#2223]
[ERROR] gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:16: attempt to call global 'Player' (a table value)
  1. RetrievePlayerVar - gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:16
   2. func - gamemodes/darkrp/gamemode/modules/base/cl_entityvars.lua:67
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by FPtje** [comment]
Same as your other issue.
