### ISSUE TITLE
sh_doors.lua error

### ISSUE THREAD

**Issue by DarkWolfInsanity** [FPtje/DarkRP#2224]
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sh_doors.lua:38: attempt to call global 'Player' (a table value)
  1. getDoorOwner - gamemodes/darkrp/gamemode/modules/doorsystem/sh_doors.lua:38
   2. isKeysOwned - gamemodes/darkrp/gamemode/modules/doorsystem/sh_doors.lua:29
    3. drawOwnableInfo - gamemodes/darkrp/gamemode/modules/doorsystem/cl_doors.lua:17
     4. DrawEntityDisplay - gamemodes/darkrp/gamemode/modules/hud/cl_hud.lua:351
      5. unknown - gamemodes/darkrp/gamemode/modules/hud/cl_hud.lua:405

**Comment by FPtje** [comment]
Conflicting addon.

**Comment by FPtje** [comment]
An addon made by a cunt, you can be sure of that.

**Comment by DarkWolfInsanity** [comment]
Thank you. I checked around by deleting addons and it strangely turned out to be the handcuffs one. :+1:
