### ISSUE TITLE
Setting has mislabled values.

### ISSUE THREAD

**Issue by Lovemaxwell** [FPtje/DarkRP#2225]
Could the setting 

"-- adminweapons - Who can spawn weapons: 0: admins only, 1: supadmins only, 2: no one
GM.Config.adminweapons                  = 1"

be fixed to have the same description as every other "Value" setting? As it is now, it is a bit confusing .
Also DarkRPModification has the same issue.

**Comment by FPtje** [comment]
Not without suddenly changing behaviour on every DarkRP server.

**Comment by FPtje** [comment]
The change would make it so suddenly admins can spawn weapons. I don't want that.

**Comment by Velkon** [comment]
I suggest you change it

**Comment by Velkon** [comment]
I would'nt mind being able to spawn weapons on my server

**Comment by Lovemaxwell** [comment]
What I am talking about is all other "Value settings" are done like this: 
"-- adminvehicles - Whether or not vehicles should be admin only. 0 = everyone, 1 = admin or higher, 2 = superadmin or higher, 3 = rcon only
GM.Config.adminvehicles                 = 3"

Could the setting text/description be changed to make it "easier" to understand?

**Comment by HDG-MrDeeJay** [comment]
If it was changed, the amount of server owners that would come here 
complaining that their admins are suddently able to get guns when they 
weren't before will skyrocket.

**Comment by Lovemaxwell** [comment]
I meant change the colons to equal signs, I should have specified

**Comment by fruitwasp** [comment]
You know he wants you to edit the description, right?

**Comment by fruitwasp** [comment]
Simply ```0 = everyone``` instead of ```0: everyone```
