### ISSUE TITLE
canBuyShipment broken?

### ISSUE THREAD

**Issue by xxx0365** [FPtje/DarkRP#2227]
returns "suppressMessage", "message" and "price" as nil

Sorry for the lack of information. I dont know what else to say.

**Comment by FPtje** [comment]
that means there's some hook that doesn't return a value for these things. The default DarkRP hook always returns suppressMessage, message and price when the it decides that players can *not* buy shipments. It does *not* return those things when it decides a player *can*. 

Why are you calling the hook anyway?

**Comment by FPtje** [comment]
Also, this is how DarkRP uses the hook:

```lua
local function canBuyShipment(ship)
    local ply = LocalPlayer()

    if not table.HasValue(ship.allowed, ply:Team()) then return false, true end
    if ship.customCheck and not ship.customCheck(ply) then return false, true end

    local canbuy, suppress, message, price = hook.Call("canBuyShipment", nil, ply, ship)
    local cost = price or ship.getPrice and ship.getPrice(ply, ship.price) or ship.price

    if not ply:canAfford(cost) then return false, false, message, cost end

    if canbuy == false then
        return false, suppress, message, cost
    end

    return true, nil, message, cost
end
```
