### ISSUE TITLE
Got an Error message after an update.

### ISSUE THREAD

**Issue by filipok911** [FPtje/DarkRP#2229]
[ERROR] gamemodes/darkrp/gamemode/libraries/fn.lua:80: malformed pattern (missing ']')
  1. unknown - [C]:-1
   2. f - gamemodes/darkrp/gamemode/libraries/fn.lua:80
    3. unknown - gamemodes/darkrp/gamemode/libraries/fn.lua:210
     4. SearchFormat - gamemodes/darkrp/gamemode/libraries/fn.lua:80
      5. OnChange - addons/athena_f1_menu/lua/athena/cl/cl_main.lua:916
       6. OnTextChanged - lua/vgui/dtextentry.lua:209
        7. unknown - addons/athena_f1_menu/lua/athena/cl/cl_searchbox.lua:52

**Comment by Bo98** [comment]
It's caused by your custom F1 menu addon ("athena_f1_menu").
