### ISSUE TITLE
Server giving people a lot of money

### ISSUE THREAD

**Issue by StrandedHeart** [FPtje/DarkRP#2231]
Hello,

Yes I have posted this on the Forums but I did not get any useful assistance. There is this bug within my server where everyone gets given mass amounts of money. I believe it has something to do with the salary time changing or the salary amount changing while the server is up.

It started recently and I have not installed anything before 72 hours of me noticing this bug. I have tried a full server restart but that has not helped. The money just keeps coming.

I am considering a complete server re build but I really don't want it to come to that.

Any help would be greatly appreciated.

**Comment by FPtje** [comment]
Not a help forum.
