### ISSUE TITLE
Min amount job.

### ISSUE THREAD

**Issue by Quadol** [FPtje/DarkRP#2233]
Hi. In job.max I use percentage's way, but this way doesn't give me 1 slot in start. How I can fix that? Example, I use 7% (max = 0.07), this way add 1 slot every 15 players, but before 15 players amount slots equal to 0. I want to fix that. Sorry for grammar and lexical errors - English is not mine language. Thank for your help.

**Comment by FPtje** [comment]
This is the behavior people have come to expect. Encode it in the customCheck.

```
customCheck = function() return team.NumPlayers(YOURTEAM) == 0 or (team.NumPlayers(YOURTEAM) + 1) / #player.GetAll() > max end
```

**Comment by Quadol** [comment]
Thank for the code, but it's doesn't work. I put that in TEAM_HOBO, and change "YOURTEAM" to "TEAM_HOBO", but all the same I can't take the Hobo's job. Slots equel to 0/0.

**Comment by Quadol** [comment]
And when amount players equel to 15 plyers, I can take this job, but that create lua-errors:
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/config/jobrelated.lua" on line 144.
The best help I can give you is this:

A comparison is being made between a nil and a number. This is not possible.

Hints:
	- This error usually occurs when two incompatible things are being compared.
	- 'Comparison' in this context means one of <, >, <=, >= (smaller than, greater than, etc.)

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/gamemode/config/jobrelated.lua on line 144
	2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80
	3. gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua on line 95
	4. gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua on line 137
	5. gamemodes/darkrp/gamemode/modules/f4menu/cl_categories.lua on line 54
	6. gamemodes/darkrp/gamemode/modules/f4menu/cl_categories.lua on line 120
	7. gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua on line 208
	8. gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua on line 347
	9. gamemodes/darkrp/gamemode/modules/f4menu/cl_frame.lua on line 133
	10. gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua on line 131
------- End of Simplerr error -------

  1. error - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/libraries/simplerr.lua:467
    3. customCheck - gamemodes/darkrp/gamemode/libraries/fn.lua:80
     4. canGetJob - gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:95
      5. Refresh - gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:137
       6. Refresh - gamemodes/darkrp/gamemode/modules/f4menu/cl_categories.lua:54
        7. Refresh - gamemodes/darkrp/gamemode/modules/f4menu/cl_categories.lua:120
         8. Refresh - gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:208
          9. Refresh - gamemodes/darkrp/gamemode/modules/f4menu/cl_jobstab.lua:347
           10. Refresh - gamemodes/darkrp/gamemode/modules/f4menu/cl_frame.lua:133
            11. unknown - gamemodes/darkrp/gamemode/modules/f4menu/cl_menuitem.lua:131

**Comment by Quadol** [comment]
Line 144 it's your code.

**Comment by FPtje** [comment]
Updated comment with fixed code, still untested. 

Note that this is not a help forum. Please go to forum.darkrp.com for further help.

**Comment by Quadol** [comment]
I know what this is not a help forum, but there no one answered me. :( P.S. This's code also don't work. I go to a  forum. Thanks for your help.
