### ISSUE TITLE
Add Option to Log FAdmin into Native Server Logs

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2238]
Would it be possible to implement an option to FAdmin to save its logs to [Source's Native Log Files] (http://wiki.garrysmod.com/page/Global/ServerLog) in the `/logs/` directory instead of to text files in the `/data/` directory?

This can be useful to those who like to use Source's own logging system for their logs rather than having various addons save their own logs into different text files, keeping things consistent and tidy. Source's own logging system also captures events that can't normally be captured via logging systems through Lua, such as engine errors.

**Comment by Bo98** [comment]
It already does this?

https://github.com/FPtje/DarkRP/blob/e19e0066dc666f20327945f2f4392436f1807006/gamemode/modules/fadmin/fadmin/logging/sv_init.lua#L24

**Comment by Hazbelll** [comment]
It does, but will also log things into text files in the `/data/` directory along with it. I'm asking if it would be possible to have it only log to one **or** the other, not both or neither.

**Comment by FPtje** [comment]
This request is too specific. I don't want to make another convar for *"Log to the source native logs instead of text files stored in data/FAdmin"*. No one but you would use it.

```lua
local old = FAdmin.Log

function FAdmin.Log(txt, prevent)
    ServerLog(text .. "\n")
end
```

**Comment by Hazbelll** [comment]
True. Only a minority would make use of it, considering logging is mostly an afterthought to a lot, but figured a ConVar or config option somewhere would've been of use to those who like to control where their logs get stored (or how many times).

I'll just override the function as suggested, thanks.
