### ISSUE TITLE
REQUEST: Allow DeriveGamemode("darkrp")

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2244]
Hi Falco & all,

I am making a gamemode based on DarkRP. I do not want to edit the DarkRP itself because I want to keep it up-to-date with SVN.

The problem is:
```lua
function GM:PlayerBindPress(ply, bind, pressed)
    self.BaseClass:PlayerBindPress(ply, bind, pressed) -- PROBLEM

    local bnd = string.match(string.lower(bind), "gm_[a-z]+[12]?")
    if bnd and FKeyBinds[bnd] then
        hook.Call(FKeyBinds[bnd], GAMEMODE)
    end

    if not self.Config.deadvoice and not ply:Alive() and string.find(string.lower(bind), "voicerecord") then return true end
end
```

When you use `self.BaseClass` on the DarkRP, it means that you use the GM from Sandbox.
But as I use a gamemode derived from the DarkRP, a problem happens: `self.BaseClass` means DarkRP instead of Sandbox.
Every call of GM or GAMEMODE methods using `self.BaseClass` are translated to the wrong GAMEMODE.

My solution is:
Replace any `self.BaseClass` in GM / GAMEMODE methods by something like `FindSandboxGamemode()`.

The function `FindSandboxGamemode()` is shared and will find the GM / GAMEMODE from Sandbox. I will put an example later.

If you prefer, I can make a pull request and fix it myself.

**Comment by willox** [comment]
The proper solution is to use DEFINE_BASECLASS and the BaseClass upvalue rather than something like 'FindSandboxGamemode'.

**Comment by FPtje** [comment]
There's this guy called Giraffen (A.K.A. Braxen) who has a gamemode derived from DarkRP, in the way you describe. I've resolved similar issues with him before. Changing stuff to use DEFINE_BASECLASS might fuck shit up for him, he and I would have to look together to minimise breaking changes.

Either way, really good choice to create your gamemode this way. Thanks for thinking about the core files!

**Comment by EstevanTH** [comment]
Currently I do not really understand how to use `DEFINE_BASECLASS()`. I have seen it in SENTs and SWEPs but it looks weird to me in gamemodes, especially when deriving.

There is something that I do not really understand with the `BaseClass` GM field. As displayed on [GM Structure](http://wiki.garrysmod.com/page/Structures/GM), it should be automatically translated when I use `DeriveGamemode()`. In my case it does not seem to.

I'll fix each failing feature by copying or hacking.

For reference, here is how I derived DarkRP:
*shared.lua*
```lua
GM.Name = "University RP"
GM.Author = "Mohamed RACHID"
GM.Website = "gmod-games.thouvest.ovh"
-- GM.TeamBased = true

if !universityrp_derived then
	universityrp_derived = true
	DeriveGamemode( "darkrp" )
end
```
*init.lua*
```lua
AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile( "shared.lua" )

include( "shared.lua" )
```
*cl_init.lua*
```lua
include( "shared.lua" )

-- [hidden] fixed GM:PlayerBindPress() using self.BaseClass.BaseClass:PlayerBindPress(ply, bind, pressed)
```

**Comment by willox** [comment]
self.BaseClass can't automatically be correct because self is always an instance of the MAIN gamemode, not any sub-gamemodes.

```lua
DEFINE_BASECLASS( x )
```
evaluates to
```lua
local BaseClass = baseclass.Get( x )
```

It also does some other stuff (SWEP.Base = x, ENT.Base = x).

**Comment by EstevanTH** [comment]
Thanks William!

Check this out, Falco! Of course it is not tested, I just used my inspiration.
```lua
local SANDBOX
function GM:FindSandboxGamemode()
	if SANDBOX then
		return SANDBOX
	else
		local parent = self
		for i=0,255 do
			if parent.BaseClass then
				if parent.BaseClass.Folder == "gamemodes/sandbox" then
					SANDBOX = parent.BaseClass
					return SANDBOX
				end
			end
			parent = parent.BaseClass
			if !parent then
				SANDBOX = self.BaseClass -- if DarkRP is not Sandbox-based
				return SANDBOX
			end
		end
		SANDBOX = self.BaseClass -- huge deriving loop
		return SANDBOX
	end
end
```

**Comment by FPtje** [comment]
I'd rather prevent that with `DEFINE_BASECLASS`

**Comment by EstevanTH** [comment]
For information, I modified my deriving code. Here's my solution:

```lua
if !universityrp_derived then
	universityrp_derived = true
	DeriveGamemode( "darkrp" )
	
	hook.Add( "PostGamemodeLoaded", "TranslateDarkrpMethod", function()
		local function TranslateDarkrpMethod( MethodName )
			local old_MethodName = GAMEMODE[MethodName]
			GAMEMODE[MethodName] = function( self, ... )
				old_MethodName( self.BaseClass, ... )
			end
		end
		
		if CLIENT then
			TranslateDarkrpMethod( "PlayerBindPress" )
		else
			
		end
	end )
end
```

**Comment by MrBrax** [comment]
function GM:PlayerBindPress( ... )
        self.BaseClass:PlayerBindPress( ... )
    end
this is how i made the bind work

**Comment by FPtje** [comment]
Latest version contains fixes. @MrBrax your workarounds should still work, but you can remove them.

I'll upload a dummy derived gamemode.

**Comment by FPtje** [comment]
https://github.com/FPtje/DarkRP/releases/tag/derived

**Comment by HDG-MrDeeJay** [comment]
Does this mean we get a new corefiles song?

**Comment by FPtje** [comment]
The old one still applies, this is just a way to make a gamemode based on DarkRP

**Comment by EstevanTH** [comment]
Hello, I just noticed something that is dangerous when derivating a gamemode:
[DarkRP/blob/derived/gamemode/modules/base/sv_gamemode_functions.lua](https://github.com/FPtje/DarkRP/blob/derived/gamemode/modules/base/sv_gamemode_functions.lua)
```lua
timer.Simple(0.1, function()
    if not InitPostEntityCalled then
        GAMEMODE:InitPostEntity()
    end
end)
```

This makes `GAMEMODE:InitPostEntity()` being called with Lua live-refresh.
Do you know why this piece of code has been added?

**Comment by Bo98** [comment]
#168.

Not convinced if it's really needed anymore as you can break DarkRP in so many other ways (like enabling MySQL but not installing a MySQL module).

**Comment by FPtje** [comment]
I am, DarkRP breaks when another addon breaks in InitPostEntity. That piece of code prevents me from being blamed for other people's fuck ups. 

@EstevanTH Why is it dangerous?

**Comment by EstevanTH** [comment]
It's dangerous because I use `GM:InitPostEntity()` and `GM:PostCleanupMap()` in my derived gamemode to spawn things such as desks, video projectors, projector screens. :innocent:
And each time I changed one little thing of the gamemode, it respawned everything! :anguished:

**Comment by FPtje** [comment]
Good point

**Comment by EstevanTH** [comment]
Oh no, the update has not been put to the *derived* tag! :dizzy_face:
The modification seems good though. :smiley:

**Comment by FPtje** [comment]
I can't push things to tags. The derived tag is just there to abuse the releases system to have a download. Don't tell Github about this little secret.

**Comment by EstevanTH** [comment]
Huh, that's so sad. :sob: So in the end, the *derived* tag will get updates only sometimes, is that right?

**Comment by FPtje** [comment]
never if it's up to me. I might replace the download in the releases tag, but I don't give a shit otherwise.
