### ISSUE TITLE
Move admin notifications back to the console

### ISSUE THREAD

**Issue by TheEMP** [FPtje/DarkRP#2245]
Can the fadmin notifications be moved back to the console or can we at least have a setting that can be added to make them follow old behavior? The reasoning behind it is simple the information has no need to be cluttering up the chat box, it just creates clutter. The console is great because the information is there only when you need it instead of having it pointlessly broadcasted to everyones chat. This is one of the reasons why I only use FAdmin on DarkRP(+a few other gamemodes).

**Comment by Bo98** [comment]
`FAdmin_ShowChatNotifications 0`?

**Comment by TheEMP** [comment]
That only makes things worse because then there are no admin notifications at all. What Im asking for is a way to change the chat logs back into console logs. I could detour the message myself but that to me seems hacky and Im sure Im not the only one who likes seeing the admin logs only in the console.

**Comment by HDG-MrDeeJay** [comment]
+1

**Comment by FPtje** [comment]
I actually agree that this stuff shouldn't clutter chat. I added it because it's been requested several times before, and because the point was made that admins want to see who teleports to whom when someone calls for help. 

That, and the bottom notifications aren't amazing either. Besides console, people need some acknowledgement of their actions. Previously it was the notification.

**Comment by HDG-MrDeeJay** [comment]
Chat is a ULX thing. Each admin system generally has its own way of 
doing things, and I liked the way FAdmin's notifications worked. Not too 
much clutter, and you could always see what was just displayed in 
console, unless there was some crazy error spam.

Perhaps, and I'm not sure if anyone would agree with me, but if there 
was a "notification log" option in the FAdmin menu / scoreboard, to see 
past notifications? Would it be too hard to cache them into an array of, 
say, the last 50 messages, only to be saved for that session only? Kinda 
like the vanilla TTT damage logs.
