### ISSUE TITLE
Anyone else getting baton/stunstick errors?

### ISSUE THREAD

**Issue by alotlikebirds** [FPtje/DarkRP#2252]
[ERROR] gamemodes/darkrp/entities/weapons/stick_base/shared.lua:54: attempt to call field 'SetupDataTables' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/stick_base/shared.lua:54

[ERROR] gamemodes/darkrp/entities/weapons/stick_base/shared.lua:54: attempt to call field 'SetupDataTables' (a nil value)
  1. SetupDataTables - gamemodes/darkrp/entities/weapons/stick_base/shared.lua:54
   2. unknown - gamemodes/darkrp/entities/weapons/stunstick/shared.lua:44

[ERROR] gamemodes/darkrp/entities/weapons/stick_base/shared.lua:97: attempt to call method 'SetSeqIdling' (a nil value)
  1. ResetStick - gamemodes/darkrp/entities/weapons/stick_base/shared.lua:97
   2. unknown - gamemodes/darkrp/entities/weapons/stick_base/shared.lua:104

**Comment by Bo98** [comment]
You probably have too many addons.

**Comment by alotlikebirds** [comment]
weird its the only errors im getting are from the stunstick/batons and battering ram


[ERROR] gamemodes/darkrp/entities/weapons/door_ram/shared.lua:214: attempt to call method 'GetTotalUsedMagCount' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/door_ram/shared.lua:214

**Comment by alotlikebirds** [comment]
Checking my logs right now

**Comment by Bo98** [comment]
It happens if weapon_cs_base2 is not loading properly. Most times this is because of too many addons that's tipping you over the Lua file limit.

If you need help go to http://forum.darkrp.com as GitHub is for bug reports.

**Comment by alotlikebirds** [comment]
No I don't need help, just seeing if its only me encountering this error.

**Comment by alotlikebirds** [comment]
Ok theres nothing on my logs, i know i havent hit the lua limit since this is a new occuring error for me so im going to remove my modules one by one and see if i can pin point the cause.
