### ISSUE TITLE
DarkRP log printing issues

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2256]
After the most recent update (I've only noticed it today, DarkRP is up to date) pretty much all [DarkRP]-prefixed prints to the console seems to be newlined incorrectly.
Examples:
![ConsoleSnippet](http://puu.sh/m4NzM/20f4bf05f4.png)
![ConsoleSnippet](http://puu.sh/m4NAu/7a5383e63f.png)
![ConsoleSnippet](http://puu.sh/m4NMq/adea572c4a.png)

**Comment by FPtje** [comment]
![2015-12-22_18-46-16](https://cloud.githubusercontent.com/assets/1202014/11961945/523d9f82-a8dc-11e5-87d3-34162edd2976.png)

Cannot reproduce. Very odd issue too. Almost looks like a concurrency problem.

**Comment by meepdarknessmeep** [comment]
you are a child pornographer? why would you put yourself as a rp_cp?
that's illegal u know

**Comment by FPtje** [comment]
child protection

**Comment by MStruntze** [comment]
Alright, I'll see if it happens after a restart.

**Comment by FPtje** [comment]
That's irrelevant. I need a specific way to reproduce it. Otherwise I can do nothing other than blame everyone but me.

Not that I like blaming everyone but me, but that'll actually be all I can do.

**Comment by LetsRaceBwoi** [comment]
@meepdarknessmeep bit immature...
@MStruntze you don't understand - clear instructions need to be given otherwise @FPtje can't actually solve the issue for you.  steps to reproduce the bug/glitch/whatever the fuck this is, otherwise nobody's going to fix it.

**Comment by FPtje** [comment]
That's what I said, was I not clear enough?

**Comment by notcake** [comment]
I bet he's fucked with the multicore convars just because.

**Comment by meepdarknessmeep** [comment]
@LetsRaceBwoi wtf is your problem this is a place of worship don't call me immature

**Comment by FPtje** [comment]
Locking because people on the glua chat are conjuring up SJW like comments to post here.

Locking to be ahead of them :)
