### ISSUE TITLE
My Garry's Mod Server is lagging really hard and is spamming alot in console. Please Help!!!!!

### ISSUE THREAD

**Issue by TheNooblycores** [FPtje/DarkRP#2258]
Every time the server gets above 15 players, It will lag really hard for no reason.
It will constantly spam this in console:

Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!
Attempted to create unknown entity type event_falling!
NULL Ent in GiveNamedItem!

I dont know what this does and i have done some testing but i still cant find out what addon or other type of this this relates to.

Here are some extra details about my server if any of this can help:

Name: NoobArmyRP
IP: 76.164.218.133:27085
Website: http://noobarmyrp.com
Steam addon collection: http://steamcommunity.com/sharedfile.../?id=570399659
Map: rp_evocity_v33x
Gamemode: DarkRP 2.6.2
Screenshots of ALL addons: http://imgur.com/gallery/R3Luj

Again I really need help and I don't know what the cause of this is. Please help me ASAP

Steam Profile: http://steamcommunity.com/profiles/76561198102403039/

EDIT: I also get this error:

[ERROR] gamemodes/base/gamemode/player.lua:205: bad argument #1 to 'WriteString' (string expected, got no value)
1. WriteString - [C]:-1
2. PlayerDeath - gamemodes/base/gamemode/player.lua:205
3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:406

**Comment by HDG-MrDeeJay** [comment]
the help forum is over at forum.darkrp.com

**Comment by TheNooblycores** [comment]
srry

**Comment by TheNooblycores** [comment]
ill move it
