### ISSUE TITLE
GM.Config.disallowClientsideScripts

### ISSUE THREAD

**Issue by colthrax** [FPtje/DarkRP#2259]
The game breaks when I change GM.Config.disallowClientsideScripts  to true, while running the server on linux, works just fine on windows.

**Comment by notcake** [comment]
Have you tried turning it off and on again?

**Comment by colthrax** [comment]
Tried doing that for 2-3 days now, posting here is my last resort. I tried every addon incase it breaks something. removing one at the time. and then adding one at the time.

**Comment by FPtje** [comment]
"game breaks" is always an invalid bug report.

**Comment by colthrax** [comment]
I did not mean the game breaks, I ment that the gamemode breaks.

**Comment by colthrax** [comment]
Everything stopps working inside darkrp, it won't load anything from it.

**Comment by FPtje** [comment]
We're still no step further here.

**Comment by notcake** [comment]
I'd recommend taking a rest and drinking plenty of fluids for a week.

**Comment by meepdarknessmeep** [comment]
im eating food leave me alone cack

**Comment by colthrax** [comment]
This is not a problem coming from my side, as I have had more people try it out. So this is a real issue. you can not disable clientside scripting while running darkrp on linux.

**Comment by MStruntze** [comment]
Yes you can.

**Comment by colthrax** [comment]
You 100% sure about that, with the latest version of darkrp?

**Comment by FPtje** [comment]
You're asking him to prove shitty now? How about you isolate the code and
report a bug to the gmod devs with a minimal set of code to reproduce it?

**Comment by colthrax** [comment]
How am I going to do that, when I have no idea to?

**Comment by FPtje** [comment]
I just looked at the code. Setting that variable to true only prevents some code from being run. Specifically, this code:

```lua

local function fuckQAC()
    local netRecs = {"Debug1", "Debug2", "checksaum", "gcontrol_vars", "control_vars", "QUACK_QUACK_MOTHER_FUCKER"}
    for k,v in pairs(netRecs) do
        net.Receivers[v] = fn.Id
    end
end


function GM:InitPostEntity()
    game.ConsoleCommand("sv_allowcslua 1\n")
    timer.Simple(1, fuckQAC)
end
```

Good luck trying to prove that NOT running the above code breaks Linux servers, and not Windows servers. 


I'm telling you, this is not your problem.

**Comment by colthrax** [comment]
I'm not that good in english, but I tried setting sv_allowclua 0 in the console. after reconnecting to the server it no longer works. Not so sure it's darkrp anymore. will try on gmod only. Sorry for wasting ya time :s
