### ISSUE TITLE
GM.Config.disallowClientsideScripts (Again)

### ISSUE THREAD

**Issue by colthrax** [FPtje/DarkRP#2260]
Not sure if you read comments from closed issues, but I did not mean that the game breaks. The gamemode breaks, it spams the console with errors from everything when I switch that to true.

Incase this is not a vaild issue, close it again (Won't repopen it)

**Comment by FPtje** [comment]
Jesus christ you impatient cock, you didn't even wait a fucking minute to see if I responded

**Comment by colthrax** [comment]
I've never used github before, and I've spent 2 days with the same issue.

**Comment by meepdarknessmeep** [comment]
please go to the darkrp forums for more help ty!!

**Comment by colthrax** [comment]
Will do, thanks.

**Comment by colthrax** [comment]
one more thing, I just installed a fresh gmod server and added darkrp. after that I switched it to true and it breaks. Not sure there is something someone can help me with.
