### ISSUE TITLE
It says 21 lua errors in console every time a player joins the server.

### ISSUE THREAD

**Issue by TheNooblycores** [FPtje/DarkRP#2264]
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/libraries/fn.lua" on line 80.
The best help I can give you is this:

Attempt to call Name/Nick/GetName on a non-existing player!

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/gamemode/libraries/fn.lua on line 80
	2. gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua on line 105
	3. addons/farm_system/lua/entities/fs_box/init.lua on line 117
------- End of Simplerr error -------

It says 21 lua errors in console every time a player joins the server.

I don't know what this means, someone please help.

**Comment by HDG-MrDeeJay** [comment]
The responsibility for this error lies with (the authors of) one (or 
more) of these files:
1 gamemodes/darkrp/gamemode/libraries/fnlua on line 80
2 gamemodes/darkrp/gamemode/modules/base/sh_entityvarslua on line 105
3 addons/farm_system/lua/entities/fs_box/initlua on line 117

3 addons/farm_system/lua/entities/fs_box/initlua on line 117

Read next time, instead of posting crap. Is it that hard to see it says 
"ADDONS FARM SYSTEM" and "THE ERROR LIES WITH THIS FILE"

**Comment by HDG-MrDeeJay** [comment]
And also the stupidity you've shown by asking for help in an issue tracker, when over 100 people before you have been told the exact same thing: Fuck off and go ask for HELP on forum.darkrp.com

**Comment by HDG-MrDeeJay** [comment]
And FYI, that is the only help you will get here. Normally falco just posts "not a help forum" and closes the issue, if someone hasn't already done it for him.

Honestly, some people just shouldn't be given a computer, given their illiteracy.

**Comment by TheNooblycores** [comment]
Jesus, sorry for ruining your day, edgy ass bitch

**Comment by FPtje** [comment]
The top error mentions DarkRP, so one could be mistaken to think DarkRP is at fault. Nevertheless, it isn't.

**Comment by HDG-MrDeeJay** [comment]
I'd spend the time to write a foolproof way of understanding it, but alas there's no such thing as fool proof. Simplerr already shows that.

**Comment by Codingale** [comment]
Just want to comment, Starfall/E2 can cause this way too much if someone poorly codes an E2 or Starfall chip on a connect event and tries getting the Nick too soon. Sometimes the entity will be valid other times it will not be. 

It is quite annoying more than helpful, it keeps an annoying pop-up in the lower right for 120 seconds.
