### ISSUE TITLE
Server inputting double commands when typed once

### ISSUE THREAD

**Issue by methyltrichloride** [FPtje/DarkRP#2265]
I type for example /addmoney methyl 50 once and the server doubles the command and gives me 100 instead of 50. It has been doing that with the previous 3 servers I've owned too (Linux & Windows). Even a clean version of both with no addons still does it! I have the latest version of both Darkrp and darkpmodications. My server currently running Linux Debian. Any idea why this is happening?

http://i.imgur.com/FuMo83Z.jpg

**Comment by FPtje** [comment]
Cannot reproduce. The fact that you get that `_Notify` error message shows there's some serious stuff going wrong at your side.

**Comment by Bo98** [comment]
The _Notify thing happens if you disable the HUD module.

**Comment by methyltrichloride** [comment]
After hours of searching I managed reproduce the double commands issue. I disabled only FAdmin in darkrpmodification and the issue started.

**Comment by FPtje** [comment]
Cannot reproduce even with FAdmin disabled.
