### ISSUE TITLE
bad argument #1 to 'SetModel'

### ISSUE THREAD

**Issue by ChibbyHD** [FPtje/DarkRP#2266]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:504: bad argument #1 to 'SetModel' (string expected, got nil)
  1. SetModel - [C]:-1
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:504
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:670

**Comment by FPtje** [comment]
#2180

**Comment by ChibbyHD** [comment]
The problem was Uclip!
https://github.com/TeamUlysses/uclip

**Comment by ChibbyHD** [comment]
Nevermind, the problem went away then came back again...
