### ISSUE TITLE
Toggle FAdmin messages

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2267]
I just hate them.
Everyone on my server too.

Could there be a function to remove them?

**Comment by FPtje** [comment]
FAdmin_ShowChatNotifications

**Comment by deinemudda32** [comment]
Thats clientside.
Isnt there any serverside change?

**Comment by FPtje** [comment]
No

**Comment by SwadicalRag** [comment]
I don't understand why you don't want to modify the file locally @deinemudda32. Why does this have to be addressed by @FPtje?

It's not too hard to change the file yourself.

If you don't want to change the file, there are other ways to do it, like changing the convar on the client yourself.

If you don't want to resort to cvar forcing, you can also use the debug lib to your advantage

```lua
local function grabUV(name,fn)
    local idx = 1
    local uvname,uv = debug.getupvalue(idx)
    while uvname ~= nil do
        if uvname == name then return uv end
        idx = idx + 1
        uvname,uv = debug.getupvalue(idx)
    end
    error("Could not get the upvalue "..name)
end

local FAdmin_Notification_Name = "FAdmin_Notification"

if net.Receivers[FAdmin_Notification_Name] then
    local showNotification = grabUV("showNotification",net.Receivers[FAdmin_Notification_Name])
    local showChat = grabUV("showNotification",showNotification)
    showChat.GetBool = function() return false end
end
```

So why bother @FPtje?

**Comment by FPtje** [comment]
Why do you as a server owner want to decide in which way clients get their notifications?

**Comment by FPtje** [comment]
Also, no core files are to be edited. Swad already knows this, but listen to the song nonetheless 
http://corefiles.darkrp.eu

**Comment by deinemudda32** [comment]
The admins themself asked me to change it, but I can't as its clientside and using a clientside timer / hook to force it, is too hacky for me.
I just don't want my chatbox spammed with useless information.
The console is okay, and this little notifications on the botton and in the console was okay too, but chat notifications are maybe going too far.

Maybe just add a privelege, where you can setup who can see the messages.

I know the song aleardy, FPtje.

**Comment by FPtje** [comment]
> **I** don't want **my** ...

Sounds to me like a personal setting. That's why it actually is a personal setting.

**Comment by deinemudda32** [comment]
That was an example. I just brought up a few arguments, but If you don't want to change the way FAdmin works right now, then its okay.
