### ISSUE TITLE
FAdmin privileges broken.

### ISSUE THREAD

**Issue by Skashh** [FPtje/DarkRP#2270]
With most privileges when you click the arrow to change them it will just say privilege added/removed but when you try it with the privileges that have DarkRP_ infront of them such as DarkRP_ChangeDoorSettings it says invalid arguments.

**Comment by notcake** [comment]
Check your privilege

**Comment by zerfgog** [comment]
Have you tried checking your privilege?

**Comment by aStonedPenguin** [comment]
DarkRP is sexist

**Comment by Skashh** [comment]
Holy shit yes. I'm not that dumb, it won't switch over to the other side because of "invalid arguments". Like even if I try to switch it over it shows that its on the other side but when I check again its back on the available privileges side.

**Comment by aStonedPenguin** [comment]
But have you tried checking your privilege?

**Comment by Skashh** [comment]
I'm answering anything saying to fucking check my privileges.

**Comment by zerfgog** [comment]
What you don't understand is I'd catch a grenade for ya.

**Comment by aStonedPenguin** [comment]
Have you tried DarkRP Facepunch edition? https://github.com/aStonedPenguin/fprp

**Comment by zerfgog** [comment]
Throw my hand on a blade for ya.

**Comment by Skashh** [comment]
Why the fuck are you guys commenting. <3

**Comment by zerfgog** [comment]
I'd jump in front of a train for ya.

**Comment by HDG-MrDeeJay** [comment]
Don't mind the cheap seats. They'll boo and heckle but in the end they all have autism and all still live with their mothers.

**Comment by BillyOnWiiUIn144p** [comment]
oh my

**Comment by Skashh** [comment]
...

**Comment by FPtje** [comment]
Works fine for me.
![2016-01-04_16-53-31](https://cloud.githubusercontent.com/assets/1202014/12093535/c99bdff4-b303-11e5-9524-76eabde01276.png)
