### ISSUE TITLE
Add a Method to Retrieve a Player's Time Left on a Team Ban

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2273]
Would it be possible to provide a way to check how much time is left on a player's ban from a specified team?

https://github.com/FPtje/DarkRP/blob/e19e0066dc666f20327945f2f4392436f1807006/gamemode/modules/jobs/sv_jobs.lua#L190

You could change the teamBan function's timer there from [timer.Simple](http://wiki.garrysmod.com/page/timer/Simple) to [timer.Create](http://wiki.garrysmod.com/page/timer/Create), the string identifier being unique to the player in question and then anyone wanting to get their time can use [timer.TimeLeft](http://wiki.garrysmod.com/page/timer/TimeLeft) to retrieve it.

There's probably more elegant ways to achieve this though (perhaps one already exists that I've overlooked?).

**Comment by Bo98** [comment]
> then anyone wanting to get their time can use [timer.TimeLeft](http://wiki.garrysmod.com/page/timer/TimeLeft) to retrieve it

While that's probably the way to implement it, I would suggest a function is added to return it instead of people relying on undocumented internal timer naming.

**Comment by Hazbelll** [comment]
@Bo98 Yeah, that's true. On that note, it would be nice if the notification given to a player if they attempt to switch to a team that they have a temporary ban on stated how much time was left on their ban from it.
Unless if we add a custom hook to [playerCanChangeTeam](http://wiki.darkrp.com/index.php/Hooks/Server/playerCanChangeTeam) would achieve the same result. I don't know if it would get called before or after DarkRP's own for when they're team banned.

**Comment by Bo98** [comment]
> it would be nice if the notification given to a player if they attempt to switch to a team that they have a temporary ban on stated how much time was left

Yeah, it currently notifies you on the anti-spam timer so it would be good to have it for the temp ban.

> Unless if we add a custom hook to [playerCanChangeTeam](http://wiki.darkrp.com/index.php/Hooks/Server/playerCanChangeTeam) would achieve the same result. I don't know if it would get called before or after DarkRP's own for when they're team banned

All of DarkRP's checks are run before this hook is called. DarkRP's checks in this particular case are not in a GM/DarkRP.hooks function like some other hooks are.

**Comment by Hazbelll** [comment]
Ah right, thanks for clarifying.
But yeah, it would be nice if player's were told how much time was left on their ban if they try to change to said job. Most usually interpret the current notification as "You're permanently banned from this job" and fret over it.

**Comment by Hazbelll** [comment]
@FPtje Thanks Falco, but as discussed with @Bo98, would it also be possible to have the "banned/demoted" notification sent to the player when attempting to change to a job they have a ban from to instead state how much time is left on their ban from that team (if temporary)?
