### ISSUE TITLE
Possible Bug in Jobs Table regarding PlayerCanPickupWeapon

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2274]
If you return false for `PlayerCanPickupWeapon` in a job's table, they will not receive any weapons when given their loadout for that job, including the default weapons and weapons given specifically to that job. If you manually pick up any of these weapons after the initial loadout however, they will successfully be picked up whilst any other weapons cannot be.

I believe the expected behaviour is supposed to be that default and job-specific weapons are given on loadout, but no other weapons can be picked up (least weapons that aren't default or specific to that job)?

**Comment by FPtje** [comment]
Returning false in PlayerCanPickupWeapon means you can't pick up the weapon. Regardless whether it is a job weapon, whether it is on spawn or whether the player is dancing the hoki-poki in a tutu. Your confusion is due to a bug in adminCopWeapons, that ALWAYS allowed admins to pick up weapons if that option was on.

**Comment by Hazbelll** [comment]
I don't have `adminCopWeapons` enabled though, and I was still able to pick up weapons. I considered maybe something else might've been conflicting with it based on that though. I have `license` enabled (you need a gun license to pick up weapons) and I tried re-testing with the player receiving a gun license automatically. Now I'm unable to pick up any weapon at all, default, job-specific, etc. probably as it's now not returning anything when checking if the weapon in question doesn't require a license or so, but I'm not 100% on that.

Anyway, it seems `license` also conflicts with `PlayerCanPickupWeapon`. Thanks for clarifying the functionality of `PlayerCanPickupWeapon` in the jobs table though. I was hoping to get away with just returning false, but oh well!

**Comment by FPtje** [comment]
can you look at the `PlayerCanPickupWeapon` hooks?

**Comment by Hazbelll** [comment]
```
] lua_run PrintTable(hook.GetTable().PlayerCanPickupWeapon)
> PrintTable(hook.GetTable().PlayerCanPickupWeapon)...
FAdmin_NerfPickupWeapon	=	function: 0x34bf8d78
```
`FAdmin_NerfPickupWeapon` is a custom hook of mine for a self-made FAdmin module. The function it executes is:
```lua
local function FAdmin_NerfPickupWeapon(ply, wep)
	if ply:FAdmin_GetGlobal("FAdmin_nerfed") then
		return false
	end
end
hook.Add("PlayerCanPickupWeapon", "FAdmin_NerfPickupWeapon", FAdmin_NerfPickupWeapon)
```
I removed the hook and re-tested. Same issue.
