### ISSUE TITLE
Include more Chat Commands into the Auto-Complete beside the Chatbox

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2275]
Would it be possible to include the chat commands of DarkRP, such as `/admintellall`, `/forceunown`, `/freerpname`, etc. to the auto-complete list that appears beside the chat box, already populated with all FAdmin commands? Likewise, can the general chat commands also show up in the list, such as `/me`, `/ooc`, `/splitshipment` etc. least the much less well known ones or custom-defined ones by Server Communities. Perhaps they can specify what the autocomplete should look-up per-argument?

This could be of good use to both the users, for easily being able to find chat commands they can use (without having to look through the Help Menu) or if the Server they're on has defined its own, custom chat commands that are unique to it, as well as the admins as they're able to see what DarkRP chat commands there are, without having to look them up online if they forget or are unaware.

**Comment by FPtje** [comment]
Autocomplete and lookup is what the f1 menu is for. I don't feel like making a common system for FAdmin and DarkRP chat commands. I'd have to find some new thing for the f1 menu to do.

**Comment by Hazbelll** [comment]
The F1 menu by no means would be made redundant, as this is where players need to look if they wish to know what each command actually does.
Plus with the addition of the HTML panel on the right-side, server communities can add further value to the F1 menu. I use it on mine for a quick reference guide on various things for my users.

But I respect if you wish not to implement a common system for the chat commands. Thank you anyway.
