### ISSUE TITLE
Precache Models of Vehicles on Server Startup

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2277]
All entity types in DarkRP have their models precached on Server Startup, except vehicles. Could this please be altered so they get precached too?
As of now, they don't get precached until a player first purchases one (even then it'll only precache the model of the specific vehicle that player purchased).

**Comment by FPtje** [comment]
Entities aren't precached at all, and neither are any of the actual guns. Only the shipment model (the box) and the player models are precached.

Why do you want them precached anyway? The more you precache on server start, the longer it will take to start the server. Having models cached on the first time they're spawned can be well workable. Unless of course vehicles are terrible and take ages to load for the first time.

**Comment by Hazbelll** [comment]
Oh yeah, my mistake. It's been a while since I last checked what got precached on startup or not. That pretty much nulls my request now, oops.

Because when I thought everything was precached on startup but vehicles, I thought it would be beneficial to finish the job. Useful, considering GMod **still** suffers from the 2048 model precache limitation that will instantly crash a server once hit.

I've written a script that makes use of the [gm_stringtable module](https://github.com/glua/gm_stringtable) to check what models are precached as the server runs, and then prevent players from spawning/toolgunning models that aren't already precached and notify them that they cannot spawn anything new once it's been hit, rather than let the server just crash and everyone looses everything. They can continue to spawn models (and entities that use those) that are precached however.

It's by no means an elegant workaround, it's hacky at best. As I thought everything was precached on startup but vehicles, I thought I'd ask those get precached too. Since they're not, I'll instead workaround those myself. Server startup time isn't so much an issue, since on first startup in the OS runtime, they all get cached into RAM thereafter anyway, so it's much faster (at least on Windows).

Sorry for the misunderstanding!

**Comment by FPtje** [comment]
In that case I'll leave it at that for now.

**Comment by Bo98** [comment]
> GMod still suffers from the 2048 model precache limitation

It's getting raised to 4096 in the next update btw.

**Comment by FPtje** [comment]
Yup, it is.

Precaching remains a tradeoff, though. Do you push as much as possible to server start or should one accept some hickups when the model is spawned for the first time?

**Comment by Hazbelll** [comment]
@Bo98 It is!? Oh thank goodness for that! It's not a perfect solution, but it's a lot better than it currently stands.

@FPtje I gladly accept some hiccups when the model is spawned for the first time, but I don't accept it crashing the Server once the model precache limit has been hit.

My Server gets quite busy during its peak hours (between 30 - 50 players) and I dislike putting strict limits on what players may spawn or not for usage in building, and they appreciate that, but likewise, I have to tradeoff with that aswell, and ironically put *very* strict restrictions in-place once the model precache gets hit.

Luckily, it only happens once or twice a day at most. I have the Server restart itself fresh for a new day at its most quiet times (0 - 10 players) at 6AM GMT +1.

**Comment by FPtje** [comment]
@Hazbelll Yes, it is, it should have been increased long ago, but due to a bug it remained 2048.

**Comment by Hazbelll** [comment]
@FPtje At least having it raised now will give us more headroom. I get requests to add various prop packs and vehicles to my Server from users, but I sadly have to reject them all, unless I can swap it out for something already on the Server, otherwise the issue is just going to get more and more apparent.

Garry was [looking into solving the issue with dynamic caching](https://github.com/Facepunch/garrysmod-issues/issues/56#issuecomment-19101831), but that was 3 years ago and nothing was said about it until this day.

**Comment by Bo98** [comment]
That would about when Garry stopped working on GMod.

**Comment by HDG-MrDeeJay** [comment]
Don't worry guys, all this shit will be in the new gmod :-)

**Comment by Hazbelll** [comment]
@Bo98 But nobody else picked up on it after he did. Or did they?

**Comment by Bo98** [comment]
On that issue, no.

**Comment by Hazbelll** [comment]
Would be grand if somebody did.

**Comment by Iamgoofball** [comment]
looks like the model precache limit increase got put in today
http://www.garrysmod.com/2016/01/19/january-2016-update/
