### ISSUE TITLE
Negative money

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#2278]
Hey, 

I've an addon for fine player, when they are in negative (-450$) after disconnect/reconnect they are in positive...

Possible to fix negative money saving ?

Thx,

**Comment by notcake** [comment]
Please don't fix this Falco, it's part of the charm of DarkRP.
It lets me violate conservation of ~~energy~~ money and take advantage of banking addons ~~made by Rocketm~~ that are buggy.
Do you really want to destroy this DarkRP game mechanic?

**Comment by FPtje** [comment]
Fix the god damn fining addon. I'm not responsible for their fuckups.
