### ISSUE TITLE
Team Demote Time not shown for /vote* in Notification

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2279]
When a player gets temporarily banned from a team, their attempts to switch back to it with `/*` will show how long they're banned from it in the notification given, as expected.
However, if the team requires a vote and the player uses the `/vote*` command, the time will not be shown in the notification.

**Comment by FPtje** [comment]
god damnit

**Comment by Hazbelll** [comment]
Yeah, sorry I'm being such a pest here as of late. I'm working on a new, major update for my Server, so I'm running into different things, haha.
