### ISSUE TITLE
How do i fix these LUA Errors?

### ISSUE THREAD

**Issue by DivineSouls83** [FPtje/DarkRP#2286]
Ok so I was on my server seeing if the levels would show up and these LUA errors popped up and I don't know how to fix them! So can any help me fix them? Heres the screenshot link that I took with gyazo: https://gyazo.com/be884b62b464c00cab81c6b99c061303

**Comment by stapler2025** [comment]
Contact the author of the fucking level system.

Goddamn it's not hard to read lua errors.

**Comment by DivineSouls83** [comment]
The thing is I don't know who the author is

**Comment by DivineSouls83** [comment]
Nvm found him

**Comment by stapler2025** [comment]
https://www.google.com/search?q=darkrp+leveling+system&oq=darkrp+level

google

is

hard

**Comment by DivineSouls83** [comment]
I got it thnx for link :)

**Comment by Kefta** [comment]
@FPtje You can close this?

**Comment by FPtje** [comment]
Not a God damn help forum.

**Comment by FPtje** [comment]
god damnit wrong issue number again. I'm getting the fuck old.
