### ISSUE TITLE
Any possibility of creating agendas involving a given job more than once?

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2288]
Hello Falco!

I'm on my way to prepare my University RP when I figured out that I cannot re-use a job in agendas!
See what I wanted to do (almost self-explanatory):
```lua
AddAgenda("Education agenda", TEAM_UNIVERSITY_DIRECTOR, {TEAM_TEACHER_TRAINEE, TEAM_TEACHER_UNIVERSAL, TEAM_TEACHER_SCIENCE, TEAM_TEACHER_TECHNOLOGY})
AddAgenda("Security's agenda", TEAM_UNIVERSITY_DIRECTOR, {TEAM_UNIVERSITY_SECURITY})
AddAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF, TEAM_POLICE_STAFF}, {TEAM_POLICE})
AddAgenda("Christmas agenda", TEAM_MAYOR, {TEAM_SANTA})
AddAgenda("Medical agenda", {TEAM_MEDIC, TEAM_AMBULANCE}, {TEAM_MEDIC, TEAM_AMBULANCE})
```

I guess that it's possible to make a function that returns all agendas for a given player, then the necessary code to display (and edit them, which may be more difficult).
Do you think you can do something or should I rather get busy and make my own custom addon?

By the way I got a problem with the "Medical agenda": the third argument must be a non-empty table while all teams are meant to be able to edit it. My code as given above seems to work. May you change this behavior?

Thanks for reading!
Love,

[Momo :heart:](http://steamcommunity.com/profiles/76561198080131369/myworkshopfiles/?appid=4000&p=1&numperpage=30)

**Comment by FPtje** [comment]
Agendas cannot have overlapping teams. When the agenda owner would set the agenda text, it would become ambiguous as to which agenda shot should be added. 

Each team has ONE agenda linked to it. I can look at the restrictions and the restriction thing you mentioned.

**Comment by EstevanTH** [comment]
Okay thanks, I'll make my own system then. :smiley:

Thanks for your time! :smile:

**Comment by FPtje** [comment]
https://facepunch.com/showthread.php?t=1499567&p=49515677#post49515677

**Comment by EstevanTH** [comment]
Ouch, that an amazing work on your library! :open_mouth:
Thanks for your great work, I really appreciate it. :heart:
