### ISSUE TITLE
Corrupt Mayor?

### ISSUE THREAD

**Issue by expgamersinau** [FPtje/DarkRP#2289]
https://gyazo.com/79ea47a6eb5b538d00176f0487342b75
Not sure what's going on.

**Comment by stapler2025** [comment]
Reading is hard.

"This job does not have a unique command."


IT TELLS YOU THE PROBLEM.

**Comment by HDG-MrDeeJay** [comment]
what is a unique command? does it stop hackers from killing me?

**Comment by expgamersinau** [comment]
But it does, it's using default mayor and that.

**Comment by HDG-MrDeeJay** [comment]
Translation: "It's unique, it's only used on TWO jobs"

**Comment by FPtje** [comment]
Not a help forum
