### ISSUE TITLE
Download 2.6.1 version

### ISSUE THREAD

**Issue by Somedeos** [FPtje/DarkRP#2290]
Hello sorry to bother you, I would download 2.6.1 version darkrp because with 2.6.2 version with those windows 10 and a recent graphics card we have a crash with menus escape I finally think its just there because of 2.6.1 we have no problem

**Comment by Neosinos** [comment]
For once after a decade I'm looking into my Github mails, and what I see is
horrible.
Please use http://forum.darkrp.com/ - Github is for bugs, not for help -
this is not a bug, this is your fault.

2016-01-12 11:52 GMT+01:00 Somedeos <notifications@github.com>:
