### ISSUE TITLE
Custom spawns that are not job related

### ISSUE THREAD

**Issue by kulcris** [FPtje/DarkRP#2291]
i need to be able to set the spawn of a player that doesnt have a specific job to a certain location. is there any way to do this without a bunch of hacky timers to tp the player to the new location?

Sorry not really an issue just a need for developing an addon for darkrp

**Comment by kulcris** [comment]
or possibly a new hook to tell when darkrp has set the players position

**Comment by kulcris** [comment]
i have no idea how to actually do this with github but this is basically what i need

https://github.com/FPtje/DarkRP/compare/master@%7B1day%7D...kulcris:master#diff-83bcce15642562f9a0a8436b17fce01f

**Comment by kulcris** [comment]
https://github.com/FPtje/DarkRP/pull/2292

**Comment by FPtje** [comment]
http://wiki.garrysmod.com/page/GM/PlayerSelectSpawn

**Comment by Bo98** [comment]
@FPtje 

https://github.com/FPtje/DarkRP/blob/16dd617469f170364127f60b89e0d7174d3bc55b/gamemode/modules/base/sv_gamemode_functions.lua#L684

and similarly in police/sv_init.lua

**Comment by kulcris** [comment]
so is there an issue with me using http://wiki.garrysmod.com/page/GM/PlayerSelectSpawn?

bc i have tried multiple ways but darkrp seems to setpos after i do, i can make a simple timer but it still seems to randomly spawn me in the wrong spot

**Comment by Bo98** [comment]
Yes, DarkRP currently ignores hooks and only listens to its own GM function. Falco reopened the issue to remind him to fix it.

**Comment by kulcris** [comment]
cool, thanks for clarifying

**Comment by kulcris** [comment]
rofl didnt even have to change anything and it just works, thanks so much for doing this

**Comment by kulcris** [comment]
ok some how i was using old code that had a faulty timer setpos, how would i go about using  this to allow for custom spawns? i have tried once again to return in playerspawn and playerselectspawn hooks but the gamemode hooks still get called first causing me to spawn and then change location (half the time failing to change location)

**Comment by kulcris** [comment]
ok nevermind, it appears to not work on certain maps though for some reason, as if maybe the spawn point entitites are different

**Comment by kulcris** [comment]
info_player_start positions are allowed to be overwritten but info_player_terrorist are not

**Comment by kulcris** [comment]
.,..... im an idiot, i was only checking for info_player_start, changed my check to info_player_* and it started working O.o, thanks again for adding this, il stop spamming this thing now
