### ISSUE TITLE
Request for hook call right before arrest

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2295]
Hi.
I'd find it very useful if we could have a hook that gets called right before arrest() is called on the player when using the arrest baton. I'm aware of the canArrest hook but too many things can go wrong after that for it to be reliable.

**Comment by FPtje** [comment]
`playerArrested` is already called before the var is set. Having another hook call goes too far.

**Comment by MStruntze** [comment]
Is it called before that player is stripped?

**Comment by FPtje** [comment]
Before the player is ejected from the vehicle, before the value in the table is set, before the notification is sent out, before the action is logged and before the player is respawned.
