### ISSUE TITLE
HUD replacement

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2296]
If I want to keep the normal hud but replace the agenda and arrested notification for example, its not possible.

I only can remove the whole hud or the hud I want to keep.

Would it be possible to add more functions to remove specific HUD modules or to disable them completly at all?

**Comment by FPtje** [comment]
HUDShouldDraw

**Comment by deinemudda32** [comment]
Is there any documentation on how to use it for this specific situation?

**Comment by FPtje** [comment]
Yes, the default hud replacement in DarkRPModification

**Comment by FPtje** [comment]
Also this is not a help forum

**Comment by deinemudda32** [comment]
I can't remove the Arrested and Lockdown text.
Yeah the agenda was a wrong, there is a config function for that.

**Comment by FPtje** [comment]
Arrest is a PrintMessage, and so is lockdown's

**Comment by deinemudda32** [comment]
I meant this:
http://puu.sh/my65c/1a17ee00e2.png
and this:
http://puu.sh/my67V/395730a268.png
