### ISSUE TITLE
Converting to mysql

### ISSUE THREAD

**Issue by gmanc2** [FPtje/DarkRP#2297]
I'm using this program http://www.easyfrom.net/download/ to try to trasnfer the sv.db over to a mysql file so I can conver to mysql. That being said I am constantly getting this error which leads me to belive that the way its compliled is non convertable. Any suggestions

Error
-----------------------------
Creating table 'darkrp_player' ...
Create table 'darkrp_player' failed!
ERROR 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key
CREATE TABLE `darkrp_player` (`uid` BIGINT NOT NULL AUTO_INCREMENT,
`rpname` VARCHAR(45),
`salary` INT NOT NULL DEFAULT 45,
`wallet` INT NOT NULL,
PRIMARY KEY(`rpname`,`uid`))
-----------------------------

**Comment by FPtje** [comment]
Why the fuck are you asking me about some external bullshit program that I have nothing to do with? 

Not only is this not a help forum, this is for DarkRP bugs, not for bugs in external database conversion tools. 

Go away.
