### ISSUE TITLE
DarkRP switches Hostname for MySQL connection

### ISSUE THREAD

**Issue by Prawx** [FPtje/DarkRP#2298]
When using mysqloo and darkrpmodification on a clean, newly installed version of the latest DarkRP, with 100% perfect settings mysql.lua, I'm getting this error in the console upon joining the server:

gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:346: Connection failed! Access denied for user 'root'@'104.243.44.250' (using password: YES)
Trying again in 5 seconds.

and then it keeps repeating.
it does not connect to the database, and the database hasn't had any tables created in it at all whatsoever.

The reason I think this is a bug is because my hostname in mysql.lua is set to 158.69.194.12, yet the error from the console is using the IP 104.243.44.250. 
158.69.194.12 is the mysql host i am trying to connect to, yet it displays the other one, which leads me to believe that that is the reason it's not properly connecting to the database.
That IP is very similar to my darkrp server's IP, which is 104.243.44.254, so i'm not sure if that has something to do with it.

This database is running off my VPS with LAMP and phpMyAdmin, and the server IP is whitelisted to be able to access the server. I don't believe I've made any mistakes. I think this could possibly be a bug..

**Comment by FPtje** [comment]
Are you sure there's no other addon trying to connect to the other ip? DarkRP doesn't just make up ip addresses to try to connect to.

**Comment by Prawx** [comment]
I don't have any other addons. darkrpmodification is the only addon on this freshly installed server. I'm not sure why it's happening. One thing I noticed is that if I put a random IP that is completely wrong in the hostname, it does not change the IP in the console like it would with the correct IP.

**Comment by Prawx** [comment]
Hey man, I'm not sure why it was changing out the IP in the error, which is what really confused me, but after doing some digging, I realized the default user in my phpMyAdmin simply didn't have the privileges to edit the database. Sorry to waste your time, though I'm glad I figured it out, and possibly helped people who have a similar problem in the futurure. You can go ahead and close this thread now, I apologize.
