### ISSUE TITLE
CustomJobFields Bug or Documentation Error?

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#2299]
The [CustomJobFields](http://wiki.darkrp.com/index.php/DarkRP:CustomJobFields) page on the DarkRP Wiki states the following:
>-- The following fields are OPTIONAL. If you do not need them, or do not need to change them from their defaults, REMOVE them.

Listed under said optional fields is `candemote = false,`, in which the explination for the field states:
>candemote (boolean)
Can people who have this job be demoted? By default hobo's and citizens cannot be demoted because it has no use to demote them.

With the example Job Table having a value of false for the field, and the explination for it stating that by default, hobo's and citizens cannot be demoted (citizens implying, any job that isn't designated as being a Mayor, Chief, Medic, Cook or Hobo), one would expect that `candemote` does not have to be specified in a Job's table unless for whatever reason, you want players to be able to demote others in that Job.

This isn't the case however. If `candemote` isn't manually defined in a Job's table, any player may freely demote anyone in that Job, even if the job is designated as being a Hobo. If you add `candemote = false,` to a Job's table though, then players will actually be unable to demote others in that job.

I'm unsure if that's how it's supposed to be or whether it's a bug. If it's the former, then the documentation on the Wiki is incorrect (or misleading). Although the fix is simple, I'd thought it would be worth bringing to your attention.

**Comment by FPtje** [comment]
updated documentation

**Comment by Hazbelll** [comment]
Thanks.
