### ISSUE TITLE
Return Type Inconsistency

### ISSUE THREAD

**Issue by Flumadiddle** [FPtje/DarkRP#2302]
For the hook [onChatCommand](http://wiki.darkrp.com/index.php/Hooks/Server/onChatCommand), there are some inconsistencies for the return type of 'arguments'. Expected should be a string, but some commands return a table.

For an example, the command: "/advert buying things" returns 'buying things' as a string for arguments, but the command: "/warrant bob printers" returns {"bob", "printers"} as a table.

**Comment by mhupfauer** [comment]
The example with the /warrant command makes more sense to be a tbl instead of a string. (name of player to warrant, reason).

**Comment by Flumadiddle** [comment]
Yeah, makes sense. Not that big of a deal, but wiki just threw me off.
I'll just typecheck args then.

**Comment by FPtje** [comment]
I'll update the wiki later, but when I do, the arguments field should say this:

```
The arguments of the chat command, given either as one string or a table of strings. That depends on whether the command is declared to use table arguments.
```
