### ISSUE TITLE
Attempt to index local 'jobTable'...

### ISSUE THREAD

**Issue by SeaLife** [FPtje/DarkRP#2306]
Hey, after updating darkrp to the newest DarkRP commit i got this error:

```
14:04:40 [ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:468: attempt to index local 'jobTable' (a nil value)
           1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:468
            2. Give - [C]:-1
             3. fn - addons/darkrpmodification/lua/autorun/server/sv_donator.lua:7
              4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
```

```
sv_donator.lua:7


...
ply:Give("weapon_physgun")
...
```

(Only happens on PlayerInitialSpawn)

**Comment by FPtje** [comment]
see the third function: `addons/darkrpmodification/lua/autorun/server/sv_donator.lua`

You're calling `PlayerCanPickupWeapon` before the gamemode set the job.

**Comment by Bo98** [comment]
You should be calling `ply:Give` no earlier than the `PlayerLoadout` hook.

It also doesn't make much sense to only give a weapon on _first_ spawn like you are.

**Comment by SeaLife** [comment]
I just use 4 hooks to loadout donator stuff...

```
hook.Add("PlayerLoadout", "DonatorSpawnLoadout", donatorSpawn)
hook.Add("PlayerInitialSpawn", "DonatorSpawnLoadoutInit", donatorSpawn)
hook.Add("PlayerSpawn", "DonatorSpawn", donatorSpawn)
hook.Add("OnPlayerChangedTeam", "DonatorSpawnChangeTeam", function(ply, t1, t2) timer.Simple(2, function() donatorSpawn(ply) end) end)
```

I had to add the player-initial-spawn cause in a earlier version of darkrp it did not work properly on first spawn without this...

**Comment by FPtje** [comment]
Well then remove it if it's fixed now.

**Comment by Bo98** [comment]
PlayerLoadout should be the _only_ one required out of those four. If not, report it as a bug.
