### ISSUE TITLE
Bug/miss-configuration with info above player's head

### ISSUE THREAD

**Issue by DaBiGBoSs** [FPtje/DarkRP#2307]
Hello, i recently noticed a bug/miss-configuration on my server which shows the player info above the head even if u are really far away

Pics:
http://prntscr.com/9udwkn

http://prntscr.com/9udxa3

i really need some help, i can provide any info you want. It's a really annoying problem and i don't know where i should post for help...

Thank you!

**Comment by Bo98** [comment]
> i don't know where i should post for help

http://forum.darkrp.com
