### ISSUE TITLE
PlayerSay hook call twice after auto refresh

### ISSUE THREAD

**Issue by toriato** [FPtje/DarkRP#2308]
It work fine with sandbox, but darkrp doesn't work :(

## Code (Serverside)
    hook.Add("PlayerSay", "Veryuniquehookname", function (ply, text, isTeam)
    	local ChatTable = {text, isTeam}
    
    	PrintTable(ChatTable)
    end)

## Before
    1       =       asdf
    2       =       false
    ServerLog: "NiceName<2><STEAM_0:0:XXXXXX><Citizen>" say "asdf"

## After
    1       =       asf
    2       =       false
    1       =       asf
    2       =       false
    ServerLog: "NiceName<2><STEAM_0:0:XXXXXX><Citizen>" say "asf"

**Comment by FPtje** [comment]
After autorefresh of what?

**Comment by MrBrax** [comment]
`if GAMEMODE and GAMEMODE.OldChatHooks then GAMEMODE.OldChatHooks["ChatTest"] = nil end
hook.Add("PlayerSay", "ChatTest", func)`

**Comment by toriato** [comment]
After save changed .lua file

**Comment by FPtje** [comment]
Oh for fuck's sake, WHICH Lua file? Your own? A darkrpmod mod?  Heaven
forbid, DarkRP itself?

**Comment by toriato** [comment]
Own addon file, /addons/asdf/lua/autorun/server/asdf.lua 
Sorry

**Comment by toriato** [comment]
Thanks MrBrax your code work,
and sorry for FPTje it was my fault

**Comment by FPtje** [comment]
Doesn't seem like it, considering what brax said.

**Comment by MrBrax** [comment]
It won't hurt the "ecosystem", since it only triggers on an autorefresh. On a dev system that's a working solution, i have it all over the place. Could also be done with replacing the function in the oldchathooks instead of removing it.

**Comment by FPtje** [comment]
It's still undesirable behaviour.

**Comment by MrBrax** [comment]
That DarkRP removes all the PlayerSay hooks on boot? I guess.

**Comment by FPtje** [comment]
No it has to, to make local chat compatible with the chat hooks. Otherwise, the chat hooks that would modify what someone said, would make everything global.

**Comment by FPtje** [comment]
Would you look at that elegant solution.
