### ISSUE TITLE
Weapon collision crashes

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2309]
I know this isn't really a bug regarding darkrp, but it is an issue I think that should be adressed.

It has come to my attention that when buying multiple shipments and ejecting them one by one, then stacking them into a huge pile of weapons (preferably on a prop) and jumping or smashing a prop at them causes major server chokes depending on the amount of weapons.
I've been looking into the different collision group, but it can be concluded that no collision group can correct this issue.

Therefore I suggest that maybe weapons should stack on touch of the same type like they do when a shipment is destroyed to maybe help this problem?

**Comment by FPtje** [comment]
You mean the merging of spawned_weapon?

**Comment by MStruntze** [comment]
Correct.
