### ISSUE TITLE
placelaws (again)

### ISSUE THREAD

**Issue by ChibbyHD** [FPtje/DarkRP#2314]
Please add a section into darkrp modification that allows adding of groups to placelaws.
Superadmin should be able to spawn the laws without being mayor! (:

Reply "Yes, but if a superadmin wants to place a lawboard permanently he should not have to switch over to mayor."

But whatever i'll modify core files.

**Comment by Bo98** [comment]
You can post in closed issues.

Anyway, there's already a hook you can use for this: http://wiki.darkrp.com/index.php/Hooks/Server/canEditLaws

**Comment by BillyOnWiiUIn144p** [comment]
o h m y, please don't edit core files, it'll _kill_ me!!

if you want a permanent lawboard use Lua

**Comment by BillyOnWiiUIn144p** [comment]
local pos = Vector(0,0,0)
local ang = Angle(0,0,0)
local l = ents.Create('darkrp_laws')
l:SetPos(pos)
l:SetAngles(ang)
l:Spawn()

**Comment by BillyOnWiiUIn144p** [comment]
![do this](http://i.imgur.com/HwHrhSr.png)

or even this
