### ISSUE TITLE
Problems FADMIN

### ISSUE THREAD

**Issue by jeje031** [FPtje/DarkRP#2317]
Hello, 

my error is : 

[DarkRP] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/messaging/cl_init.lua:178: attempt to index local 'notification' (a nil value)
  1. func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/messaging/cl_init.lua:178
   2. unknown - lua/includes/extensions/net.lua:32

How to solve ?

**Comment by jeje031** [comment]
and another problems : 

[DarkRP] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/messaging/cl_init.lua:178: attempt to index local 'notification' (a nil value)
  1. func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/messaging/cl_init.lua:178
   2. unknown - lua/includes/extensions/net.lua:32


                                DarkRP_SetLicense       =       true
                                DarkRP_SetMoney =       true
                                FPP_Cleanup     =       true
                                FPP_Settings    =       true
                                FSpectate       =       true
                                FSpectateTeleport       =       true
                                Freeze  =       true
                                God     =       true
                                Ignite  =       true
                                Jail    =       true
                                Kick    =       true
                                Logging =       true
                                Message =       true
                                Noclip  =       true
                                PickUpPlayers   =       true
                                RCon    =       true
                                Ragdoll =       true
                                Restrict        =       true
                                SeeAdmins       =       true
                                ServerSetting   =       true
                                SetAccess       =       true
                                SetHealth       =       true
                                SetNoclip       =       true
                                SetTeam =       true
                                Slap    =       true
                                Slay    =       true
                                StripWeapons    =       true
                                Teleport        =       true
                                UnBan   =       true
                                Voicemute       =       true
                                changelevel     =       true
                                giveweapon      =       true
                immunity        =       100
user:
                ADMIN   =       0
                PRIVS:
                                Message =       true
                                SeeAdmins       =       true
                immunity        =       10

**Comment by FPtje** [comment]
Cannot reproduce.
