### ISSUE TITLE
Error when add permission

### ISSUE THREAD

**Issue by theo33500** [FPtje/DarkRP#2318]
Sorry for my bad english. I am french

When i want tu add these privileges:

- DarkRP_AdminCommands
- DarkRP_ChangeDoorSettings
- DarkRP_GetAdminWeapons
- DarkRP_GetJob_cp
- DarkRP_GetJob_mayor
- DarkRP_SeeEvents
- DarkRP_SetDoorOwner
- DarkRP_SetLicense
- DarkRP_SetMoney

I have an Invalid argument

Thanks for your help

**Comment by FPtje** [comment]
Cannot reproduce.
