### ISSUE TITLE
Stun stick and evilmelon's bridge

### ISSUE THREAD

**Issue by AMD-NICK** [FPtje/DarkRP#2319]
https://www.youtube.com/watch?v=gyBwDBrIe1U

**Comment by Bo98** [comment]
wtf

**Comment by MrBrax** [comment]
wtf +1

**Comment by Hazbelll** [comment]
Good times, I had so much fun doing this on back on evilmelon.

**Comment by FPtje** [comment]
Please next time tell me that you have to hit the thing IN THE MIDDLE. I spent way longer than necessary to figure that out.

**Comment by AMD-NICK** [comment]
Ok
