### ISSUE TITLE
Lua Error: [ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:110: attempt to index local 'jobTable' (a nil value) 1. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:110 

### ISSUE THREAD

**Issue by AvexGitHub** [FPtje/DarkRP#2322]
Recently this error has been happening to me and when I spawn. I spawn as a job like "Joining/Connecting" and I'm a grey figure. Please tell me whats wrong cause it messed up the spawn and everything in rp_downtown_v4c_v2.

**Comment by alotlikebirds** [comment]
Either you have a broken addon, your jobs.lua has an error, or something is causing conflict.

**Comment by FPtje** [comment]
Yeah, you're ignoring other errors.
