### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2323]
Theres no translation for voting/cl_voting.lua line 42. "Time"

**Comment by Bo98** [comment]
Note that a language entry already exists for "Time:" so that can just be used:

https://github.com/FPtje/DarkRP/blob/e19e0066dc666f20327945f2f4392436f1807006/gamemode/modules/language/sh_english.lua#L455

**Comment by FPtje** [comment]
yes
