### ISSUE TITLE
darkrp mysql issue with ulx/ulib

### ISSUE THREAD

**Issue by alotlikebirds** [FPtje/DarkRP#2324]
When you have darkrp set up to mysql ulx resets fadmins ranks back to user randomly after a server restart(Sometimes your rank persists, sometimes youre user). After 4 days of debugging my server, I've narrowed it down to ulx/ulib. Having darkrp set up to SQLite while using ulx/ulib works flawlessly, but when darkrp is set to mySQL this bug occurs. There are no error on the server nor the database, so it took me a long time to find out the cause, but if you can have ulx/ulib working with darkrp using SQLite why wouldn't it work when its set to mySQL? I am running the latest github for both ulx/ulib and darkrp. I've tested this on a clean slate, fresh darkrp, and fresh ulx/ulib. I opened up a thread about this on the forum but no one replied. Btw I'm using tmysql4.

**Comment by FPtje** [comment]
Your argument doesn't convince me tat FAdmin is the cause of the issue.

**Comment by alotlikebirds** [comment]
I spoke to team ulysses, they told me to speak to you about this.

**Comment by FPtje** [comment]
I can't do shit with "sometimes ranks reset"

**Comment by githubfuckedmyoldaccount** [comment]
you could test it yourself, this happens to me too.

**Comment by alotlikebirds** [comment]
The player group change happens on initial spawn. I can look at my database, see that I am superadmin, start the server, still superadmin, join the server still superadmin, and than spawn and im set to user. On both the server and database. If i removed ulx/ulib it never happens. Its only when you have ulx/ulib installed. Also it works perfectly on SQLite. This only happens when using mySQL with either mysqloo and tmysql4.

**Comment by Partixel** [comment]
> Its only when you have ulx/ulib installed
Then it's a problem with ulx / ulib

**Comment by FPtje** [comment]
I had some kind of epiphany yesterday and I'm going on a wild guess that this may be it. Try it out.

**Comment by alotlikebirds** [comment]
omg hahaha so drunk ill trybit in the morning, thanks for the help falco ill let you knownhow iy goes

**Comment by alotlikebirds** [comment]
Worked perfectly.
