### ISSUE TITLE
Performance: client Chat recipients polling uses Vector:Distance() instead of Vector:DistToSqr()

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2327]
Hey Falco,
I just spotted a small performance issue while modding the so-hard-to-mod client chat recipients polling. For me it's not a problem though.

[darkrp\gamemode\modules\chat\cl_chatlisteners.lua](https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/chat/cl_chatlisteners.lua)
In `local function loadChatReceivers()` you declared polling functions that use [`Vector:Distance()`](http://wiki.garrysmod.com/page/Vector/Distance) while it's easily possible to use [`Vector:DistToSqr()`](http://wiki.garrysmod.com/page/Vector/DistToSqr) instead.

Thanks for your great work every time you do something! :heart:

**Comment by EstevanTH** [comment]
Oh also I missed something else: you check the position of the players instead of their eyes position.
[Entity:EyePos()](http://wiki.garrysmod.com/page/Entity/EyePos)

**Comment by 00875** [comment]
EyePos() returning an position of player eye view in the world (player position vector + player view height). It is safe to use.

**Comment by FPtje** [comment]
I don't see why I should. For distance calculations it doesn't make a difference.

**Comment by EstevanTH** [comment]
On the wiki it's displayed that using a square distance is more efficient because calculating square roots is an expensive process; the method `Vector:DistToSqr()` would not exist otherwise.
If I follow this rule, I would use square distances here, especially in this situation where the distance is calculated for each player on each client Think (if I properly read the Lua code).

I have not benchmarked `Vector:Distance()` and `Vector:DistToSqr()` myself though.

**Comment by Bo98** [comment]
Falco was probably talking about how choosing between Entity:GetPos() and Entity:EyePos() shouldn't make much a difference for distance calculations.

**Comment by EstevanTH** [comment]
Oh well oops. :sweat_smile: And I agree, eyes and feet are the same for distances. :stuck_out_tongue_closed_eyes:

**Comment by EstevanTH** [comment]
Thanks Falco! :heart:
