### ISSUE TITLE
clean up server remove npcs

### ISSUE THREAD

**Issue by Driven49** [FPtje/DarkRP#2328]
Hi,

There are 2 days I updated Darkrp and now I notice that when Clean Up Server, it removes all npcs present on the map.
It's annoying to the gameplay because npcs are removed as the car dealer and other ...

I also in the server logs a great message following the clean up but I will avoid the post it will be too ...

I did not know or write so I do here.
Thank you.

**Comment by FPtje** [comment]
Those NPCs should have been coded to be recreated on server cleanup.
