### ISSUE TITLE
On spawning default druglab, model is an error, doesn't work, lua error

### ISSUE THREAD

**Issue by solsane** [FPtje/DarkRP#2330]
[DarkRP] gamemodes/darkrp/entities/entities/lab_base/init.lua:16: Tried to use a NULL physics object!
  1. Wake - [C]:-1
   2. Initialize - gamemodes/darkrp/entities/entities/lab_base/init.lua:16
    3. unknown - gamemodes/darkrp/entities/entities/drug_lab/init.lua:11
     4. Spawn - [C]:-1
      5. defaultSpawn - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:363
       6. callback - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:414
        7. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
         8. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:255
          9. unknown - lua/includes/modules/concommand.lua:54

**Comment by FPtje** [comment]
Cannot reproduce.
