### ISSUE TITLE
attempt to index local 'jobTable' <a nil value>

### ISSUE THREAD

**Issue by Pepin123** [FPtje/DarkRP#2331]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_function.lua:239: attempt to index local 'jobTable' <a nil value>
    1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:239

 
I was messing around with ulx, with teams, and when giving a team a certain color this error out puts when opening f4 menu, after removing the team it goes back to normal, also i've noticed that when the team is in, this darkrp job (mayor) that needs people to change from does not show up on f4 menu
NeedToChangeFrom = {TEAM_PCHIEF, TEAM_POLICE, TEAM_CIVILIAN},

**Comment by FPtje** [comment]
I should make getJobTable throw a fancy error. I see that kind of error way too often.

**Comment by Pepin123** [comment]
Oh so this is common haha, ah well lol.

**Comment by FPtje** [comment]
Oh you broke something yourself. Someone is in your server without a valid job. The point is that I see errors caused by that on GitHub too often. This means I should try to have it throw a clear error message about what the issue is.
