### ISSUE TITLE
DarkRP Job error

### ISSUE THREAD

**Issue by badcompany** [FPtje/DarkRP#2332]
`[ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua" on line 94.
The best help I can give you is this:

bad argument #1 to 'pairs' (table expected, got nil)

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 94
	2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	4. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	5. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	6. gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua on line 46
	7. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 278
	8. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 17
	9. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 78
	10. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 142
------- End of Simplerr error -------`

**Comment by FPtje** [comment]
Not a help forum

**Comment by HDG-MrDeeJay** [comment]
its like he didnt even read

The responsibility for this error lies with (the authors of) one (or more) of these files:
1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 94


aka whoever last changed the jobs file is a smeghead.

**Comment by badcompany** [comment]
Lol your funny @HDG-MrDeeJay, BTW this was closed so what was the point in posting a comment? was it just to make your small self of steam feel better?

**Comment by badcompany** [comment]
also btw you can see where i put "------ LINE 94" go ahead and let me know what the issue is if your the smart man around here.. BTW i've already fixed the issue


```
TEAM_PO` = DarkRP.createJob("Police Officer", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/police_fem.mdl", "models/player/police.mdl"},
     description = [[The protector of every citizen that lives in the city.    ---------- LINE 94 
        You have the power to arrest criminals and protect innocents.   
        Hit a player with your arrest baton to put them in jail.
        Bash a player with a stunstick and they may learn to obey the law.
        The Battering Ram can break down the door of a criminal, with a warrant for their arrest.
        The Battering Ram can also unfreeze frozen props (if enabled).
        Type /wanted <name> to alert the public to the presence of a criminal.]],
    weapons = {"arrest_stick", "unarrest_stick", "m9k_usp", "stunstick", "door_ram", "weaponchecker"},
    command = "po",
    max = 4,
    salary = 60,
    admin = 0,
    vote = true,
    hasLicense = true,
    category = "Government Officials",
	PlayerLoadout = function(ply) -- this line is added. Remember a comma at the end of above line if it is not there.
		ply:SetArmor(50)
	end,
})
```

**Comment by FPtje** [comment]
Fuck off you imbecile. Go brag about fixing your dumb ass fuck up somewhere else.

**Comment by badcompany** [comment]
Hey telling me to go fuck off isn't the way to go! i've left this go when you closed it! @HDG-MrDeeJay was the one who wanted to comment! all i was doing is showing him maybe he shouldn't comment unless he knows the facts.

I wasn't doing this to piss you off and i wasn't doing this to brag @FPtje

**Comment by FPtje** [comment]
Unlike you he actually understand Lua. He knows the god damn facts. He knows that you made a syntax error. He knows how to identify and solve syntax errors because that's the most basic kind of error you can fucking make. Everything he said was true. The error literally stated that **you** are responsible, the fact that you posted that shit here means that you didn't understand that part of the error.
