### ISSUE TITLE
Pocket Inventory doesn't shift items down - Pocket can't drop items if there's a gap in the table

### ISSUE THREAD

**Issue by R4K0** [FPtje/DarkRP#2333]
Detailed here - http://forum.darkrp.com/threads/coding-a-crafting-system.7108/

Basically Inventory doesn't shift itself down - If you take out item no. 4 out of 7 items - the 4th slot will stay empty, and new items won't fill out that one - they will just add 8th, 9th 10th 11th item and so on.
#edit I have no idea how it works dou - They might or might not fill out the 4 slot - Look into it yourself, I'm too dumb for this - Thanks

How to reproduce: Spawn 5 entities, pocket them, drop first 3 using the R menu or using external script with the function ply:removePocketItem(index) (like I do) - quit the R menu, try to drop the rest of the items clicking right mouse button - The pocket won't see the items and it won't let you open R menu, because it thinks that the Pocket table is empty, because it met gap at the beginning.

Conclussion: As long as slot 1 is not empty - shit will work.
Solution? I have no idea, I'm just a beginner. Maybe you're using ipairs instead of pairs? Maybe try to drop the items using the highest index going down?

**Comment by FPtje** [comment]
You're right in that the pocket doesn't move items up or down as you remove other items. It shouldn't because items in the pocket are identified by their index. Scripts remember "oh, the item I put in the pocket is as index 3". There is, however, a bug in right click, which uses #tbl. #tbl requires the keys to start at 1, which they don't in your example.

**Comment by R4K0** [comment]
Is it going to be fixed anytime soon? Sounds like it is something to do with glua itself.
From what I hear, I'd fix it by adding do in pairs loop, count them up using before executing drop function, and use that number for the rest of the checks and so on.
As I am just a beginner, I'm not even going to try to fix it, never done sweps or things like that :)

Also, I think it would be somehow useful to add another function to the DarkRP which would move all the keys down, so they get in order. Maybe even function that would let you pick the index, or move the existing value to another index. This way, script devs could save their pocket entities at, lets say - 40,41,42,43[...] index for easier reference to it for later

I'll just wait for the fix, thanks for the reply, goodluck and have a nice day ;)

**Comment by FPtje** [comment]
I broke my laptop this morning. When I will be available to fix this shit is unknown.

**Comment by R4K0** [comment]
Oh, you've forgotten to apply it to the pocket menu when we press R - Dropping works, but without slots 1 and 2 we can't open the menu!

Thanks for a quick fix dou, everything works perfect but this! :+1:
