### ISSUE TITLE
Too many LUA errors messing up server

### ISSUE THREAD

**Issue by MoofinMan** [FPtje/DarkRP#2340]
The responsibility for this error lies with (the authors of) one (or more) of these files:
1. addons/darkrpmodification-master/lua/darkrp_customthings/entities.lua on line 125
2. [C] on line -1
3. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 137
4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 148
5. gamemodes/darkrp/gamemode/cl_init.lua on line 53
------- End of Simplerr error -------

1. error - [C]:-1
2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:467
3. createEntity - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:666
4. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/entities.lua:125
5. doInclude - [C]:-1
6. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:137
7. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:148
8. unknown - gamemodes/darkrp/gamemode/cl_init.lua:53

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:239: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:239

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:239: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:239

**Comment by MoofinMan** [comment]
I have fixed the FIRST error in the entities section

**Comment by FPtje** [comment]
Not a help forum
