### ISSUE TITLE
FAdmin ULX Compatibility

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2341]
ULX and FAdmin do conflict with ranks.
If you remove users from ulx, they arent removed from fadmin, but if you add someone to a ulx group, he gets access to fadmin too.

**Comment by FPtje** [comment]
Sounds like ULX' fault too. Am I right in saying that "removing" users from ULX means they get the rank "user"? They need to run CAMI.SignalUserGroupChanged not only when somenoe gets a rank **other** than user, but when they get the rank user itself too.
