### ISSUE TITLE
DarkRP Door Groups not saving on server restart...

### ISSUE THREAD

**Issue by whij** [FPtje/DarkRP#2343]
Hey,

i get no errors...
the door groups do set but when i restart the server, they go back to unowned. idk if this is a darkrp issue but as of the recent update its been happening. 

Thanks - Whij

**Comment by MStruntze** [comment]
[A fix to this was pushed less than 24 hours ago](https://github.com/FPtje/DarkRP/commit/a012a573317dcdc93d6d4b4539c8d98ff8b627b4) - are you sure you're running the latest version?

**Comment by FPtje** [comment]
I am

**Comment by FPtje** [comment]
Sure that he's not

**Comment by whij** [comment]
Yes sorry i was not using the newest update, my bad :) keep up the support guys :D
