### ISSUE TITLE
Option to disable mayor approval of warrants

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2344]
Would be great with either a config option or a hook to bypass mayor approvals of warrants.

**Comment by HDG-MrDeeJay** [comment]
I believe a better alternative would be to specify a job that authorizes 
warrants, in a similar manner to specifying hitmen etc. This would 
permit server owners to not only disable the feature all-together, but 
also specify alternative jobs, for example, a police dispatch job, or a 
judge...

This would work best in practice if you would add weight to each job 
that can "approve" warrants, and whoever has the most weight gets asked 
to approve it. And naturally, if no players with specified jobs are 
active, the warrant automatically goes through as it would if there was 
no mayor.

**Comment by Bo98** [comment]
@HDG-MrDeeJay 

```lua
    mayor = true,
```

as a job field

**Comment by HDG-MrDeeJay** [comment]
No more emails before I properly wake up then... :P

**Comment by BillyOnWiiUIn144p** [comment]
They'd be able to place lawboards as well.

**Comment by FPtje** [comment]
returning nil for the second return value of `canRequestWarrant` now makes sure no notification is sent.

Just return false there and roll your own.
