### ISSUE TITLE
FAdmin errors

### ISSUE THREAD

**Issue by halfwire** [FPtje/DarkRP#2345]
I think FAdmin is broken, because I just installed a clean DarkRP gamemode and addon onto my server. I also reset my sv.db. My superadmin group doesnt start with many permissions, so I cannot edit, add, or delete groups or do almost anything in FAdmin, even as a superadmin. I try to create a group in rcon, but it comes up with this error:

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:191: attempt to index a nil value
  1. callback - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:191
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/commands/sv_concommands.lua:19
    3. unknown - lua/includes/modules/concommand.lua:54

I dont know what is going on, any solutions?

**Comment by FPtje** [comment]
Looks like you broke something yourself. Please head to forum.darkrp.com.

**Comment by FPtje** [comment]
Also, look for earlier errors (on server startup) and post those on the forums.

**Comment by halfwire** [comment]
@FPtje  I don't understand how it could be me, I have a fresh install of DarkRP. and that error pops up and says its in the gamemode folder that I haven't edited at all. There are no errors in my startup either.

**Comment by Bo98** [comment]
> I try to create a group in rcon

Post the exact command you are trying.
