### ISSUE TITLE
FAdmin problems, please look into this.

### ISSUE THREAD

**Issue by halfwire** [FPtje/DarkRP#2346]
This doesnt have to do with ulx, as i do not have ulx. I have the SAME problem as this:

https://github.com/FPtje/DarkRP/issues/2342

It isnt me, I reinstalled a clean version of DarkRP and its erroring from a file in the gamemode itself..

**Comment by TontonBa** [comment]
Yep, i tried too, but nothing even with the older versions..
i have friends who have no prob with that but i have even if i did the exact same things..

So i decide to put a "Commands" tab in the F4 menu and put in the "ban, kick, freeze..." things ..

**Comment by Bo98** [comment]
@halfwire Run the same commands as FPtje did in that issue and post the output here.

**Comment by FPtje** [comment]
"erroring from the gamemode itself"

I see no errors posted here, nor in that other thread.

Also, I cannot reproduce the problem without ULX. @TeamUlysses

On clean join:
![hl2_2016-02-26_22-49-49](https://cloud.githubusercontent.com/assets/1202014/13366425/64a98680-dcdb-11e5-8f82-3d54a0ff9600.png)

From Player 3's perspective (after being set superadmin):
![hl2_2016-02-26_22-50-09](https://cloud.githubusercontent.com/assets/1202014/13366432/6d43f4b0-dcdb-11e5-8a92-72afb61ead3c.png)

Everything works for me without ULX.

I don't have enough information to reproduce any bug.

**Comment by TontonBa** [comment]
[](http://www.noelshack.com/2016-08-1456523983-fadmin.png)

That's what i get .. frsh install, all up to date..

**Comment by FPtje** [comment]
Of course you don't have access!!! Fuck, if people who joined your server could FAdmin setroot themselves then it wouldn't be much of a safe admin mod, would it? Run it through **rcon**.

**Comment by TontonBa** [comment]
I did! it set me superadmin but i have have not a single command in tab menu!

**Comment by FPtje** [comment]
Not in the screenshot you didn't!

**Comment by TontonBa** [comment]
Let's start from the begining.

Fisrt, i installed darkrp mode then add the addons,
Then i connected to the server, i did not touch any file,
I checked the tab menu and it seems all good,
After that i set me as superadmin, normaly it added the command on tab menu and let me set other player ranks ect..
But no, i have setaccess, ban from job, unbanform job, mute/unmute, spectate
When i try set access i get "no access!"

So tried with ULX, everything is good, i'm superadmin, i can run commands but tab menu still same..



Sorry if i can't explain you everything in a good english but i'm trying to do my best..

**Comment by FPtje** [comment]
I understand that that's really annoying, but I cannot reproduce the problem. If I can't make myself have the problem, then I cannot fix it. I need more information.

**Comment by TontonBa** [comment]
You already did an amazing job and still doing it!

I'll try do get every single information i can and make an update.

Thanks a lot!
