### ISSUE TITLE
suggestion for adding vehicles

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [FPtje/DarkRP#2348]
http://wiki.darkrp.com/index.php/DarkRP:Vehicles

We have nothing there in the terms of adjusting skins or bodygroups on spawn. Even if we had a function there, sorta like customcheck, but for the ent to be spawned.

Idk im drunk atm, but i know i need a function there or something

**Comment by Bo98** [comment]
There's onBought but it's not documented for some reason.

It also doesn't have a validation check but that isn't specific to vehicles.

**Comment by FPtje** [comment]
yeah, use onBought

**Comment by HDG-MrDeeJay** [comment]
> yeah, use onBought

> There's onBought but it's not documented for some reason.

I'll use onBought when I see it documented.

**Comment by Bo98** [comment]
Done, 3 days later.
