### ISSUE TITLE
Split DarkRP into "DarkRP Framework" and Example DarkRP schema"

### ISSUE THREAD

**Issue by lavnart** [FPtje/DarkRP#2350]
Since all job-related privileges can be added to custom jobs, it is now possible to move all default content (jobs, shipments, entities, etc.) to darkrpmodification-like addon. Most server owners don't use default content at all, and it will ease maintenance of gamemode. It'll be still possible to derive a schema from default one, or use it as reference. Serously, having stuff hardcoded into gamemode, and having only way to disable it is via another lua config file sucks.

**Comment by FPtje** [comment]
It doesn't suck. It's good design. It allows you to modify the gamemode without touching its files. DarkRP has a modular design, pretty much anything can be disabled and/or modified. You can already go to the releases section and download an example "derived" gamemode.
