### ISSUE TITLE
Test issue. 

### ISSUE THREAD

**Issue by FPtje** [FPtje/DarkRP#2352]
[//]: # (Github is not the place to ask for help or just to ask questions.)
[//]: # (That's what the forums (http://forum.darkrp.com/) are for instead.)

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This issue exists to test the template. There are comments in the template and I want to know whether they end up in the final issue.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
like by posting this issue rite

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

```lua
anus.lua:0 attempt to index finger (anal value)
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
FPtje fix `anus.lua` pls

**Comment by FPtje** [comment]
They don't, this is fucking amazing.

**Comment by xaviergmail** [comment]
Yes, Falco, anus.lua is broken beyond repair. Needs a full rewrite.

**Comment by FPtje** [comment]
I can't, it has already been pushed onto the master branch.

**Comment by xaviergmail** [comment]
Are you sure the master branch wasn't pushed _into_ it instead?

**Comment by FPtje** [comment]
Same thing, different perspective.
