### ISSUE TITLE
Enable to re-use a command of a removed job for a new job

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2353]
### Description of the bug
Hallo Falco en everybody!
I'm making an addon that modifies the job list instantly. It only affects jobs created with it.
I use
```lua
_G[TeamID] = DarkRP.createJob( blablah )
```
and
```lua
local function RemoveDarkRPTeam( TeamID )
	if _G[TeamID] then
		DarkRP.removeJob( _G[TeamID] )
		_G[TeamID] = nil
	end
end
```
The server throws an error when I re-create a job that has been previously removed, because the job command already exists while the matching job has been removed.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Execute this code to add a custom team:
```lua
local TeamID = "TEAM_DEBUGGER"
local command = "debugger"
RemoveDarkRPTeam( TeamID )
_G[TeamID] = DarkRP.createJob( "Debugger", {
	color = Color( 128,128,128 ),
	model = {
		"models/player/Group03/Female_01.mdl",
		"models/player/Group03/Female_02.mdl"
		},
	description = "",
	weapons = {},
	command = command,
	max = 0,
	salary = GAMEMODE.Config.normalsalary,
	admin = 0,
	vote = false,
	hasLicense = true,
	ammo = {},
	sortOrder = nil,
})
```
Then remove it:
```lua
RemoveDarkRPTeam( "TEAM_DEBUGGER" )
```
Then re-add the same job with the same code as previously. You will get an error.

### Lua errors
```
[ERROR] A runtime error has occurred in "addons/job_live_creator/lua/autorun/job_live_creator.lua" on line 148.
The best help I can give you is this:

Corrupt team: Debugger!
This job does not have a unique command.

Hints:
        - There must be some other job that has the same command.
        - Fix this by changing the 'command' of your job to something else.

The responsibility for this error lies with (the authors of) one (or more) of these files:
        1. addons/job_live_creator/lua/autorun/job_live_creator.lua on line 148
        2. lua_run on line 1
------- End of Simplerr error -------

  1. error - [C]:-1
   2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:467
    3. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:471
     4. AddTeam - addons/job_live_creator/lua/autorun/job_live_creator.lua:148
      5. unknown - lua_run:1
```

### Why the developer of DarkRP is responsible for this issue
I guess that the job chat command should be removed when the related job is removed, what do you think?
That would be great to finish my custom-made addon without using a workaround using unique chat commands.

Thanks!
Love, Momo :heart:

**Comment by EstevanTH** [comment]
Sorry, I made a mistake. As the problem is a little of a brainstorming, I did a mistake:
```lua
RemoveDarkRPTeam( "TEAM_DEBUGGER" ) -- this is wrong
RemoveDarkRPTeam( TEAM_DEBUGGER ) -- this works
```

**Comment by HDG-MrDeeJay** [comment]
Was about to say, why you removing a string and not a team?

**Comment by EstevanTH** [comment]
Yeah, in my tests I got confused while my actual code was okay. :sweat_smile:
