### ISSUE TITLE
Access issues

### ISSUE THREAD

**Issue by Sleggie** [FPtje/DarkRP#2354]
I'm a superadmin in ULX and I can't disallow door ownership and I can't set spawns. Any ideas why? Thanks.

**Comment by HDG-MrDeeJay** [comment]
What the real question should be is "what the shit happened to CAMI fixing this?"

**Comment by Bo98** [comment]
@HDG-MrDeeJay Probably using an outdated ULX/ULib. But because it's a superadmin group, it should be backwards compatible.

**Comment by Sleggie** [comment]
Uh... I'm not too sure what you guys mean.

**Comment by Sleggie** [comment]
PS. I am using ULX 3.62 and ULIB 2.52, because the latest builds absolutely break everything on the server...

**Comment by HDG-MrDeeJay** [comment]
If the latest builds break everything on your server, perhaps you should 
look into that problem with TeamUlysses first

**Comment by Sleggie** [comment]
Yeah. Well anyways, the issue goes on :P

**Comment by Bo98** [comment]
Just to double check: what exactly does it say when you try to use /setspawn?

**Comment by Sleggie** [comment]
You need admin privileges in order to /setspawn

**Comment by FPtje** [comment]
You've removed the issue template.
You're using older versions of ULX and ULib.
The latest versions (ULX 3.70d and ULib 2.60d) have CAMI privileges assigned to superadmin and admin by default, as specified in the standard. That means your issue shouldn't occur unless you actively removed those privileges. That or an old version of ULX didn't assign them by default and those settings stayed after updating.

The solution is to manually assign the CAMI privileges to superadmin in !menu.

**Comment by Bo98** [comment]
This is the real issue:

> You need admin privileges in order to /setspawn

That message should not display. It should be "You don't have the right privileges to perform this action". You're using a very old version of DarkRP. Where did you download it?
