### ISSUE TITLE
Could not find (JOb)

### ISSUE THREAD

**Issue by Zortex04** [FPtje/DarkRP#2355]
[//]: # (Github is not the place to ask for help or just to ask questions.)
[//]: # (That's what the forums (http://forum.darkrp.com/) are for instead.)

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Basicly when i kill myself in my custom job it spawns me up in the skybox so basicly i tryed /addspawn /setspawn but both said Could not find Commander 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Kill youreself

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it) Idk if you are but this is a bug cause every other job works??? and the code looks the same too

**Comment by Bo98** [comment]
/addspawn and /setspawn uses the _command_ of the job rather than it's name. Sometimes this is the same but it depends on what you have set it to.

**Comment by FPtje** [comment]
and I thought the comments in the issue template were clear on what kind of issues to post here.

**Comment by Zortex04** [comment]
Ok thanks for saying that but even if i use setspawn or add spawn  i still spawn in the skybox

**Comment by HDG-MrDeeJay** [comment]
http://i.imgur.com/MRVZzPm.png

What could the problem possibly be I wonder?

**Comment by HDG-MrDeeJay** [comment]
Where there is an opportunity to not read, goldfish will... not read.

**Comment by HDG-MrDeeJay** [comment]
Also Zortex, don't sent me direct emails.

![http://i.imgur.com/gYtqxEh.png](http://i.imgur.com/gYtqxEh.png)
