### ISSUE TITLE
Error while setting door perms or setting spawns

### ISSUE THREAD

**Issue by paxoboy** [FPtje/DarkRP#2357]
[//]: # (Github is not the place to ask for help or just to ask questions.)
[//]: # (That's what the forums (http://forum.darkrp.com/) are for instead.)

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I am useing ulx i have added /setspawn or /addspawn but it will not work i have tried this with fadmin as well and removeing fadmin but it dose not work, the doors do not also work by adding a job or a door group or even disableing the ownership

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
I have no idear

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
The responsibility for this error lies with (the authors of) one (or more) of these files:

	1. [C] on line 855

	2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 464

	3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84

	4. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84

	5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 137

	6. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 148

	7. gamemodes/darkrp/gamemode/init.lua on line 86

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because i have freshly downloaded the gamemode but it has errors in the gamemode folders

**Comment by FPtje** [comment]
You're missing half of the error.

**Comment by FPtje** [comment]
Also, what little I can see of that error shows that there's something wrong in your custom stuff. This is your responsibility.

**Comment by Bo98** [comment]
Stack trace looks corrupted too:

> ```1. [C] on line 855```

**Comment by paxoboy** [comment]
I downloaded darkrp freshly to my server and it desplayed the permission error for the doors and stuff do you know anything about that?

**Comment by HDG-MrDeeJay** [comment]
Did you use Filezilla?

**Comment by paxoboy** [comment]
yes

**Comment by HDG-MrDeeJay** [comment]
if you need to be told why, it's clear you haven't read anything on your way to installing DarkRP.

I think there are like 2 or 3 places where you are told Filezilla fucks up when uploading lots of uncompressed files because reasons.

**Comment by HDG-MrDeeJay** [comment]
Oh yeah, I just found where it tells you... You know how when you make a new issue it tells you to read the guidelines for contributing?

https://github.com/FPtje/DarkRP/blob/master/CONTRIBUTING.md

**READ IT YOU FILTHY CUNT**

**Comment by FPtje** [comment]
I don't blame people for not reading the contribution guidelines. It's a small little text when you create an issue and you have to actually click a link to read them. No one ever reads it. It's not being shoved in the face enough. I've always hated the contribution guidelines for that reason. That's why I'm so glad we now have issue templates, which are unavoidable.

**Comment by HDG-MrDeeJay** [comment]
Then we should add the note about FileZilla being trash elsewhere, 
perhaps in the readme.md under a section regarding installation tips 
and/or advice.

To make up for lacking content, you could add the benefits to using SVN 
for installation.

**Comment by FPtje** [comment]
Are we sure that this issue is caused by missing files?

**Comment by Bo98** [comment]
FileZilla isn't as garbage as people make it out to be. The problem with it is that _in the event_ of a failed transfer, it doesn't inform you as clearly as it could.

> Are we sure that this issue is caused by missing files?

Based on the stack trace in the original report, it looks to _not_ be caused by missing files.

**Comment by FPtje** [comment]
Then filezilla cannot be blamed for this issue

**Comment by HDG-MrDeeJay** [comment]
Well I'll go back to the quiet corner.

**Comment by AustinHnn** [comment]
Disable FAdmin?

**Comment by HDG-MrDeeJay** [comment]
That's an even dumber suggestion than "It could be Filezilla"

**Comment by AustinHnn** [comment]
Not really.

**Comment by paxoboy** [comment]
**So i take it there is an issue somewhere inside the script if it is not filezilla**

**Comment by AustinHnn** [comment]
zip the file and try and upload it a different way maybe... Also Disable FAdmin and test it

**Comment by paxoboy** [comment]
Right i have just uploaded darkrp.rar and disabled fadmin ect it still dose not work idk what to do
