### ISSUE TITLE
Cannot Restrict "placelaws" Command!

### ISSUE THREAD

**Issue by Percipience23** [FPtje/DarkRP#2360]
### Description of the bug
So before I start I want to make sure you know, I have already tried both setting the limit of the law boards to zero. This seemed like the easiest fix, without doing extra coding. So I set it to zero, **this worked for awhile until today**. I noticed a Mayor spawned a law board. This was weird simply because the maximum law boards had been set to zero. Now, I shrugged it off, thinking "it's just a bug, lets set the maximum laws boards to five and create a script in .../addons/disableplacelaws/lua/disable/server named "sv_disable.lua". I added the following into that file: http://pastebin.com/XKivuzpe. So I restarted the server, joined, and changed into a Mayor. I could place unlimited law boards. Not only could I still use the command "placelaws", but I was also able to place as many laws boards as I wanted. No errors are in the console. I also have not updated the darkrpmodification addon since the last repository update. I have the gamemode to update using svn, through my server hosting service. This is why I'm posting this on the gamemode's repository, instead of the addon's repository.

### How to make the bug happen
I have no clue what makes the bug happen.

### Lua errors
I see no Lua errors, neither in the server startup logs or client-side, pertaining to DarkRP.

### Why the developer of DarkRP is responsible for this issue
Well, I do not think the cause of the bug is on my part. Simply because this **was** working. I think an update from the DarkRP has caused this. I only say this because this is the only thing that updates automatically through my server.

**Comment by Verideth** [comment]
Try playerinitialspawn hook

**Comment by Bo98** [comment]
> I noticed a Mayor spawned a law board. This was weird simply because the maximum law boards had been set to zero.

Do you happen to have another method of spawning a law board? Was such board removed at any point?

**Comment by Percipience23** [comment]
@Bo98 there is only the /placelaws command. Either way the maximum amount was set to zero, so he shouldn't have been able to.

**Comment by Verideth** [comment]
@Percipience23 you probably messed with the core files.

**Comment by FPtje** [comment]
http://i.imgur.com/W4Ym66h.png

Setting the max to 0 works for me. Perhaps your code is run after Initialize, causing the chat command not to be removed.

More likely is the fact that some other addon is creating the "placelaws" chat command on, say, `InitPostEntity`. This would explain both the max check not working for you AND the `removeChatCommand` not working. 

Either way I cannot reproduce it, which means it's most likely on your side.
