### ISSUE TITLE
Ammo duplicate?

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2362]
[//]: # (Github is not the place to ask for help or just to ask questions.)
[//]: # (That's what the forums (http://forum.darkrp.com/) are for instead.)

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If you merge two weapons with different magazines, then you do not get the full ammo back, instead less or more.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Drop a weapon.(example: 5 ammo)
Drop another weapon.(example: 1 ammo)
Collide each other.
Now it is one weapon with 2 amount.
Collect both.
Less ammo.

Works for shipments too.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Nope.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because spawned_weapon and spawned_shipment is from DarkRP.

**Comment by FPtje** [comment]
The amount of ammo should always be equal or less. It takes the average. This is a design decision.

**Comment by deinemudda32** [comment]
Its actually never equal. Its less and you do not get ammo for the second gun.
