### ISSUE TITLE
Bug lua.

### ISSUE THREAD

**Issue by Aka7tsu4** [FPtje/DarkRP#2365]
03/12/2016 00:18:56: Lua Error: Couldn't Load Init Script 'darkrp/gamemode/init.lua'
Couldn't Load Init Script: 'darkrp/gamemode/init.lua'
03/12/2016 00:18:56: Lua Error 
[ERROR] A runtime error has occurred in "[C]" on line 642.
The best help I can give you is this:
A table is being indexed by something that does not exist (table index is nil).
Hints:
- The thing between square brackets does not exist (is nil).
The responsibility for this error lies with (the authors of) one (or more) of these files:
1. [C] on line 642
2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 458
3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
4. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 137
6. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 148
7. gamemodes/darkrp/gamemode/init.lua on line 86
------- End of Simplerr error -------
1. error - [C]:-1
2. doInclude - gamemodes/darkrp/gamemode/libraries/simplerr.lua:507
3. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:137
4. Call - gamemodes
[ERROR] A runtime error has occurred in "[C]" on line 642.
The best help I can give you is this:
A table is being indexed by something that does not exist (table index is nil).
Hints:
- The thing between square brackets does not exist (is nil).
The responsibility for this error lies with (the authors of) one (or more) of these files:
1. [C] on line 642
2. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 458
3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
4. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 137
6. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 148
7. gamemodes/darkrp/gamemode/init.lua on line 86
------- End of Simplerr error -------
1. error - [C]:-1
2. doInclude - gamemodes/darkrp/gamemode/libraries/simplerr.lua:507
3. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:137
4. Call - gamemodes/darkrp/gamemode/libraries/modificat03/12/2016 00:18:56: Lua Error [AddCSLuaFile] Couldn't find 'weapons/backup/shared.lua' ()

On my server consoles !
When i start the server.

**Comment by AMD-NICK** [comment]
Do you use this mod? 
https://github.com/FPtje/darkrpmodification

**Comment by Aka7tsu4** [comment]
Yes i use it why ?

**Comment by Verideth** [comment]
You probably messed with the core files

**Comment by Aka7tsu4** [comment]
i didn't touch the core files

**Comment by Verideth** [comment]
Did you recently install anything?

**Comment by Verideth** [comment]
Around what time did this error appear?

**Comment by AMD-NICK** [comment]
Have you any addon with folders structure like addons/<addonname>/lua/darkrp_modules ?

**Comment by Aka7tsu4** [comment]
I only changed some jobs and fix some bugs ;_; this error appear in server console
i touch nothing in core files i can see " DONT TOUCH CORE FILES "

**Comment by Aka7tsu4** [comment]
I go look now "AMD-Nick" thanks for the fast help ! <3

**Comment by Bo98** [comment]
This is probably an error in your jobs file but for some reason the error is corrupt and not telling you that. Specifically, it's likely your `GAMEMODE.CivilProtection` section containing a job that does not exist.

**Comment by AMD-NICK** [comment]
Ad try to revert your fixes and see what happens

**Comment by Aka7tsu4** [comment]
Ye bo98. that it's ! thanks so much !

**Comment by Aka7tsu4** [comment]
sorry i think i post it in the wrong section... i'am so dumb x_x

**Comment by Bo98** [comment]
Yeah, next time use http://forum.darkrp.com.

**Comment by Aka7tsu4** [comment]
I know. thank

**Comment by Aka7tsu4** [comment]
i've got a question and want to fix a bug on darkrp, french people use " é à and more more "
And in the TAB (scoreboard) the letters "é" is totally bugged, how to fix it guys ?

**Comment by AMD-NICK** [comment]
not to use French :)

**Comment by Aka7tsu4** [comment]
racist. :(

**Comment by AMD-NICK** [comment]
This problem actual for any language excepting English as I know

**Comment by Aka7tsu4** [comment]
This is the font i think...

**Comment by Bo98** [comment]
I believe there are some font related fixes coming in the next GMod update but I don't know whether it will fix your specific problem or not.

**Comment by AMD-NICK** [comment]
Fonts in gmod is a material. I have this problem with cyrillic too

**Comment by Bo98** [comment]
Cyrillic is definitely supposed to be fixed in the next GMod update.

**Comment by AMD-NICK** [comment]
WOOOW

**Comment by Aka7tsu4** [comment]
Yes ! and the lua refresh on linux ?

**Comment by AMD-NICK** [comment]
yep

**Comment by Bo98** [comment]
Autorefresh doesn't work with DarkRPModification unfortunately on any OS. It loads the files slightly differently than normal so you should get better errors that help you if something goes wrong (which for some reason didn't work properly for you this time). The loading method used however breaks GMod's autorefresh.

**Comment by HDG-MrDeeJay** [comment]
yeah, kinda makes live-updating bugs on a server (such as a 
misconfigured job or a bad config entry) a bitch when you have players.

**Comment by Verideth** [comment]
Are you racially confused?

**Comment by Verideth** [comment]
> bug lua

**Comment by Verideth** [comment]
If you fuck up the jobs don't make an issue

**Comment by FPtje** [comment]
Still, I should investigate why the error is thrown in core files.

**Comment by FPtje** [comment]
The error I get is clear when `GAMEMODE.CivilProtection` contains a nil key. It may be the simplerr update though.

**Comment by Aka7tsu4** [comment]
"If you fuck up the jobs don't make an issue" fuck ye look fptje comments.
