### ISSUE TITLE
Fadmin issues

### ISSUE THREAD

**Issue by Blackheart304** [FPtje/DarkRP#2366]
Got my darkrp server built got everything setup properly went to fadmin and ranked myself to superadmin. Went to change server settings and i dont have any access to server settings at all not sure what to do about this

**Comment by Blackheart304** [comment]
I might also mention i dont have setaccess on any fadmin ranks ? Is this normal

**Comment by FPtje** [comment]
More normal than people removing the template that says hello is to be found on the DarkRP forums.

**Comment by Bo98** [comment]
> hello is to be found

**Comment by Blackheart304** [comment]
Basically there is no way to setaccess through fadmin, I tried everyway i know how and i simply cannot do it. I literally scraped the forum you suggested not a single topic pertains to my issue is there a command to set fadmin rank permission through rcon ?

**Comment by FPtje** [comment]
help*, that was autocorrect.

If you searched the forums and found nothing, you make a thread yourself.

**Comment by Blackheart304** [comment]
Okay i made a thread and posted thanks for the advice http://forum.darkrp.com/threads/fadmin-issues.7340/

**Comment by Blackheart304** [comment]
Well Nobody helped me with this issue so far all i have is fadmin installed and still no rank with the permissions to setaccess, Sorry to bug you again but i really need help im at a loss here. Is there any rcon commands i can use to change the permissions of the ranks ?
