### ISSUE TITLE
Fadmin

### ISSUE THREAD

**Issue by Blackheart304** [FPtje/DarkRP#2369]
So i did everything you said went on the forums but i can not fix the issue of not being able to change permissions for ranks on fadmin, I am at a loss, Is there a list of commands i can get for fadmin that i can run through rcon ?

**Comment by FPtje** [comment]
Not getting help on the forums does not qualify making an issue on the suisse tracker. The issue tracker is for bugs in DarkRP itself, shit for which I am responsible. You've removed the fucking template again which says this explicitly. You're annoying me. Go away.
