### ISSUE TITLE
Fadmin No ranks + Perms Issue

### ISSUE THREAD

**Issue by Zortex04** [FPtje/DarkRP#2371]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible) Basicly (this actully happend before but restarting the server worked but it doesent this time)  darkrp's fadmin  has no ranks at all this time (only user)
Doing fadmin setroot doesent work i still have no perms at all 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Access any fadmin thing that needs permissions

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
When trying to do something that Requires permissions on a person
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:259: attempt to index field 'user' (a nil value)
  1. DoClick - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:259
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_controls.lua:301

when trying to add a rank / change it

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:145: attempt to index a nil value
  1. func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:145
   2. ContinueNewGroup - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:108
    3. Func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:46
     4. DoClick - lua/derma/derma_utils.lua:146
      5. unknown - lua/vgui/dlabel.lua:218

No access!

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I dont know if he is i just want fadmin to work agian idk whats wrong

**Comment by Verideth** [comment]
lol

**Comment by deinemudda32** [comment]
+1

**Comment by FPtje** [comment]
That error is probably not the first error you're getting. Search the server console for errors.

Also, tell me which addons you're running. I'm quite sure that one of them is fucking shit up.

**Comment by Zortex04** [comment]
... thats gonna be alot of addons but none of them is related to fadmin

**Comment by Kefta** [comment]
Do it anyway; you should really pare down your addons or merge them -- having a bunch of different ones is a huge pain in the ass

**Comment by FPtje** [comment]
I really think this is a conflicting addon. I myself can't reproduce this.

**Comment by Kefta** [comment]
#1
