### ISSUE TITLE
Bug when using DarkRP default weapons

### ISSUE THREAD

**Issue by Darklom** [FPtje/DarkRP#2372]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Whenever we use DarkRP weapons, everyone walks extremely slow

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Get a DARKRP default weapon and use it

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None
### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I'm not sure if you're responsible but I really need help.

**Comment by FPtje** [comment]
yes, that's because you're holding the ironsights down.

**Comment by Darklom** [comment]
Actually no.. you can use a battering ram and then switch to any other weapon but you will be stuck walking untill you kill yourself.

**Comment by FPtje** [comment]
I cannot reproduce that issue. That used to be a problem in some ancient version of DarkRP (I'm talking years ago here).

**Comment by Darklom** [comment]
Do you have ANY idea what could be interfering with that?  I have no clue as to what could be causing this issue since nothing should conflict with that.

**Comment by FPtje** [comment]
You could still be running some ancient version of DarkRP, as I mentioned in my previous post.

**Comment by Darklom** [comment]
I defiantly am not, I downloaded it straight from this github as a zip.  How did you end up fixing that issue?

**Comment by Bo98** [comment]
It was probably fixed another way before but nowadays the problem is completely avoided by only making speed changes temporary using the SetupMove hook. The hook gets called continuously and resets between calls. DarkRP checks if a DarkRP weapon is equipped in that hook and sets the speed if it is.

**Comment by Darklom** [comment]
So then Bo98, why do you think it is happening now?

**Comment by FPtje** [comment]
That's not his responsibility to figure out. It doesn't happen to him, it doesn't happen to me. How about YOU figure out why it happens to YOU?
