### ISSUE TITLE
DarkRP Ignoring 'GM.Config.adminsents = 1'?

### ISSUE THREAD

**Issue by mphowarth** [FPtje/DarkRP#2373]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

In the DarkRP configuration, setting GM.Config.adminsents to 1 (admins or higher) does nothing - users can still spawn SENTs. Not sure if this is a bug or not.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Set DarkRP to use GM.Config.adminsents = 1 and try spawn an entity as a user.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Not sure if this is a bug or not.

**Comment by FPtje** [comment]
Works for me, must be a conflicting addon.
