### ISSUE TITLE
Anyone who know Why my F-Admin has Super-ADmin as a user?

### ISSUE THREAD

**Issue by magnus505** [FPtje/DarkRP#2375]
Anyone who know Why my F-Admin has Super-ADmin as a user?

**Comment by Shigbeard** [comment]
omg falco can u just ban people who don't use the template?

**Comment by magnus505** [comment]
@Shigbeard what template? I didnt get any :1234:

**Comment by FPtje** [comment]
When you created this issue, did you see text in the field you asked your question?

**Comment by Shigbeard** [comment]
When you create an issue, you should see this

![Issue template](http://i.imgur.com/X5BwYAp.png)

If you don't get the template, you DEFINITELY SHOULD get the yellow box that tells you to read the guidelines for contributing.

Did you see this template, and that box?

**Comment by FPtje** [comment]
if @magnus505 is right and they **didn't** see the template, **some cunt** at github is to be yelled at with *very* angry words.

**Comment by Shigbeard** [comment]
@FPtje Well I *JUST* took that screenshot, so it works for me.

**Comment by FPtje** [comment]
I see it too, but let me try it on the mobile view.

**Comment by FPtje** [comment]
Yup, the mobile view has the template too.

**Comment by magnus505** [comment]
@FPtje why didnt i get any template?

**Comment by Shigbeard** [comment]
@magnus505 That's what we are trying to find out. Did you create your issue through github using the green "New Issue" button? If so, then @FPtje is right and some fuckwit at github needs bitchslapping.

**Comment by FPtje** [comment]
@magnus505 How did you report the issue? What browser are you using? What OS? Windows? OSX? Android? iOS?

**Comment by magnus505** [comment]
@FPtje Google Chrome, Windows 7. school PC

**Comment by FPtje** [comment]
Click the new issue button and make a screenshot. Post it in this issue.

**Comment by magnus505** [comment]
This is how it looks for me

![nop](https://cloud.githubusercontent.com/assets/7260284/13904098/7af2a19e-ee95-11e5-8457-cf5f962fd293.PNG)

**Comment by FPtje** [comment]
What the fuck

**Comment by magnus505** [comment]
@FPtje What?

**Comment by FPtje** [comment]
Compare your screenshot with @Shigbeard 's and you'll know why I said "what the fuck".

**Comment by magnus505** [comment]
@FPtje Japp now I understand :/

**Comment by FPtje** [comment]
It works on Edge, it works on Internet Explorer, it works on my chrome, why doesn't it work on yours?

**Comment by magnus505** [comment]
@FPtje Maybe some plugin?

**Comment by FPtje** [comment]
Well list your plugins.

**Comment by FPtje** [comment]
Also, please give me your chrome version. Maybe you're running the version from 2006 or some shit.

**Comment by magnus505** [comment]
@FPtje Adblock, Dashlane, Mega, mighttext SMS For Facebook and Gmail, and Ban checker for Steam.

verison 48.0.2564.116

**Comment by FPtje** [comment]
Try updating chrome, the latest is 49.something.

**Comment by magnus505** [comment]
@FPtje  Failed to check for updates: Could not start the update check (error code 3: 0x80080005 - System Level).

**Comment by FPtje** [comment]
Uninstall and reinstall chrome

**Comment by Shigbeard** [comment]
@FPtje @magnus505 for comparison, I'm using Firefox, version 45.0, with addons Adblock Plus, Ghostery, Noscript, some random google translate button, and NoScript.

I also have greasemonkey, but I have no active userscripts for Github.

**Comment by FPtje** [comment]
God damnit shy did you change your name again? I didn't know it was you until I read the email title.

**Comment by Shigbeard** [comment]
Yeah, I had to. HDG's owner started being a twat so I left, and I took the opportunity to remove HDG from my github name.

If you recall, I made a post about it on facepunch...

**Comment by Hazbelll** [comment]
I like how you guys are trying to debug a GitHub issue in the DarkRP repo.

**Comment by FPtje** [comment]
This shit is important to me.
