### ISSUE TITLE
SetAccess not restricted by player immunity

### ISSUE THREAD

**Issue by MrBrax** [FPtje/DarkRP#2376]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Anyone with SetAccess (moderator in this case) can set the group of a player (including themselves) to a higher immunity than their own, making themselves superadmin or anyone else. Isn't this how admins (not superadmins) should make mods out of people?

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Set the SetAccess privilege on a group, see them making themselves superadmin.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No errors, as this is "intended" behavior, or oversight.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Oversight probably, or me not understanding this.

**Comment by FPtje** [comment]
SetAccess is currently a very "dangerous" privilege that entails being able to set access to anything. It may be a good idea to restrict it, yeah.

**Comment by TheEMP** [comment]
Why not change it to a system based off the groups immunity? So a user can only set access to groups lower or equal to his group.

**Comment by FPtje** [comment]
What distinguishes your idea from op's?

**Comment by FPtje** [comment]
Please test with this stuff
