### ISSUE TITLE
attempt to index local 'joobTable'

### ISSUE THREAD

**Issue by TomTheDuck** [FPtje/DarkRP#2380]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # Ok. So i have looked at other threads about this, trust me none of them have worked for me! Whenever i reboot my server now and i log in, i get this error and i spawn in the middle of the sky! Another thing about this is that it doesn't load a database because of it for some reason!
What my console looks like:

https://gyazo.com/026e7127ab0147f8c84f1df53088e150

### How to make the bug happen
[//]: # So i added a HUD and then removed it after this happened... nothing i also removed steamrewards, because it complained about the money, nothing!
[//]: # 

### Lua errors
[//]: # https://gyazo.com/026e7127ab0147f8c84f1df53088e150
[//]: # 

### Why the developer of DarkRP is responsible for this issue
[//]: # Because it seems to be a bug and I am hopeless with LUA
[//]: #

**Comment by Shigbeard** [comment]
Looks like one of your addons could be causing it. Remove your addons and test the server, one addon at a time.

Here's a hint on where to start
![Start here](http://i.imgur.com/MARSxc6.png)

**Comment by TomTheDuck** [comment]
Ok, will give that a test later, thanks!

**Comment by TomTheDuck** [comment]
Ok, so i removed the addon, and by looking back at the error it looks as if it was trying to enable, but couldn't because the job table messed up somehow. Still have the origingal error :/

**Comment by BillyOnWiiUIn144p** [comment]
The DarkRP developer is not responsible for this and this is not a help forum

**Comment by TomTheDuck** [comment]
Ok, will list my jobs below, haven't had an error at all with jobs and i don't touch core files. (I even reinstalled DarkRP)

**Comment by TomTheDuck** [comment]
-- Code generated at: TheCodingBeast.com | DarkRP 2.5 Tools
TEAM_MOD = DarkRP.createJob("Moderator On Duty", {
   color = Color(44, 255, 0, 255),
   model = {"models/elmo.mdl"},
   description = [[You are a mod, get gud and become an Admin]],
   weapons = {},
   command = "mod",
   max = 10,
   salary = 0,
   admin = 1,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   customCheck = function(ply) return CLIENT or ply:IsUserGroup("trial") or ply:IsUserGroup("moderator") or ply:IsUserGroup("trialvip") or ply:IsUserGroup("modvip")  end,
      CustomCheckFailMsg = "This job is not for your group!"
})


-- Code generated at: TheCodingBeast.com | DarkRP 2.5 Tools
TEAM_AOD = DarkRP.createJob("Admin on duty", {
   color = Color(0, 202, 255, 255),
   model = {"models/props_idbs/char/crash_plr.mdl"},
   description = [[Admins use this to do adminy stuff]],
   weapons = {},
   command = "aod",
   max = 10,
   salary = 0,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   customCheck = function(ply) return CLIENT or ply:IsUserGroup("admin") or ply:IsUserGroup("owner") or ply:IsUserGroup("Owner") or ply:IsUserGroup("servermanager") or ply:IsUserGroup("trusted") or ply:IsUserGroup("senior") or ply:IsUserGroup("ultra") or ply:IsUserGroup("head") end,
      CustomCheckFailMsg = "This job is not for your group!"
})


TEAM_CITIZEN = DarkRP.createJob("Citizen", {
	color = Color(20, 150, 20, 255),
	model = {
		"models/player/zelpa/male_04.mdl", "models/player/zelpa/female_01.mdl", "models/player/zelpa/female_02.mdl", "models/player/zelpa/female_03.mdl", "models/player/zelpa/female_04.mdl",  "models/player/zelpa/female_06.mdl", "models/player/zelpa/female_07.mdl",
		"models/player/zelpa/male_01.mdl", "models/player/zelpa/male_02.mdl", "models/player/zelpa/male_03.mdl", "models/player/zelpa/male_05.mdl", "models/player/zelpa/male_06.mdl", "models/player/zelpa/male_07.mdl", "models/player/zelpa/male_08.mdl", "models/player/zelpa/male_09.mdl",
		"models/player/zelpa/male_10.mdl", "models/player/zelpa/male_11.mdl",
	},
	description = [[You are a citizen, you are not any specific job. I dunno cook meth or rob someone or something.]],
	weapons = {},
	command = "citizen",
	max = 0,
	salary = GAMEMODE.Config.normalsalary,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = false,
	skins = {4,5,6}, -- example configuration
	bodygroups = {
		["torso"] = {0,2,3},
		["legs"] = {0,1,2,3,4,5},
		["beanies"] = {0,1,2},
		["glasses"] = {0,1}, -- these are all examples, please don't actually copy-paste them because they might not work.
	} -- check below for playermodels that support this addon, and use the sandbox playermodel selector to check bodygroups.

})

TEAM_POPO = DarkRP.createJob("Police Officer", {
   color = Color(0, 40, 255, 255),
   model = {"models/player/uk_police/uk_police_06.mdl"},
   description = [[You are the POPO stop drugs and that...]],
   weapons = {"m9k_glock"},
   command = "popo",
   max = 5,
   salary = 250,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true, 
   unlockCost = 500 

})

TEAM_EMS = DarkRP.createJob("Paramedic", {
   color = Color(255, 0, 0, 255),
   model = {"models/medic_08_05.mdl"},
   description = [[You are a paramedic, Save some lives!]],
   weapons = {"darkrp_defibrillator"},
   command = "ems",
   max = 4,
   salary = 150,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = true,
   chief = true,
   mayor = false,
   hobo = false,
   cook = false,
   unlockCost = 600 
})

TEAM_CHIEF = DarkRP.createJob("Police Chief", {
   color = Color(0, 56, 255, 255),
   model = {"models/player/uk_police/uk_police_03.mdl"},
   description = [[You are the Police Chief you watch everyone do your work]],
   weapons = {"m9k_mp5"},
   command = "chief",
   max = 1,
   salary = 300,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = true,
   mayor = false,
   hobo = false,
   cook = false,
	requireUnlock = TEAM_POPO,
		unlockCost = 1000 
	})


*Require Unlock, etc is from another addon, just to note i tried removing and reinstalling darkrpmodifictaion*

**Comment by BillyOnWiiUIn144p** [comment]
So you get this error with William's Car Dealer _and_ DarkRP modification removed?

**Comment by TomTheDuck** [comment]
Yep. Tried removing both, even doing a fresh reset of DarkRP :/

**Comment by TomTheDuck** [comment]
Ok! Good and Bad news! After fully restarting the dedicated machine thats used to use srcds, the error is no longer here, however i think darkrp may have had its days. Prometheus reported an error and after looking at it, i noticed it went back to the same file as before! Will reinstall DarkRP *again* and come back and let you guys know!

**Comment by TomTheDuck** [comment]
Nope :/ Didnt work :-1:

**Comment by TomTheDuck** [comment]
Nevermind Fixed it! Just tinkered with sv.db for a bit!

**Comment by FPtje** [comment]
What do you mean you "tinkered" with sv.db? What did you change in it?

**Comment by TomTheDuck** [comment]
Modified a Weapon within the db that was causing a problem, Prometheus had assigned a wepaon that didn't exist to a player, which caused the jobtable to throw a fit

**Comment by FPtje** [comment]
How was the weapon assigned to the player? By that I mean what was the table called in sv.db? Do you link weapons to players with some kind of addon?

**Comment by TomTheDuck** [comment]
Yea Prometheus my donation system assigned a player a broken package and assigned a perma weapon to them, that didn't exist in the files, it was an M9K weapon that was not installed

**Comment by FPtje** [comment]
And that caused an error in DarkRP. Can you get the author of prometheus in here? 

I want them to know they've got a bug in their thing that presents itself in a DarkRP error. With what you just described, they should be able to reproduce the bug and fix it. I'd like to know more technical details as to why DarkRP threw an error. That way I can perhaps make DarkRP more resistant to faulty errors in the future.

**Comment by TomTheDuck** [comment]
Yea sure Left a note asking them to head on over to here!

**Comment by Newjorciks** [comment]
Hey, I am the Lua dev for Prometheus. The issue TomTheDuck had was nothing to do with DarkRP and to be fair I don't see how it was ever caused. The problem he had was that PData of "PrometheusWeapons" (Old weapon system for Prometheus) was for some reason a boolean even though Prometheus wouldn't have inserted a boolean there ever. So the error he had with Prometheus was string.Split yelling that it's getting boolean instead of string. Prometheus does some "fiddling" with DarkRP jobs, more specifically the RPExtraTeams table, but I don't see how it would break anything.

**Comment by FPtje** [comment]
The error implies that the team of the player is not set properly when they first spawn. Perhaps an error in `PlayerInitialSpawn` or `PlayerSpawn` prevents them from being assigned a team. Could that be the case?

**Comment by Newjorciks** [comment]
The old weapon system that the error was in for him is in PlayerLoadout hook. As far as I know he doesn't have an error happening inside the PlayerInitialSpawn or PlayerSpawn hooks? Also that error with the William's Car Dealer is very similar to what Prometheus is getting, I don't know if the error with William's Car Dealer is caused from GetPData returning a boolean, but looking at the error it almost seems like that is happening, so I have a feeling something is messing up the GetPData function on his server? Though that doesn't explain the DarkRP error.

**Comment by FPtje** [comment]
Weird stuff, I can't guess either.
