### ISSUE TITLE
lua error when using /toggleteamownable

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/DarkRP#2381]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Lua error when using the command /toggleteamownable.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
write /toggleteamownable without any args in front of a door.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:35: table index is nil
  1. addKeysDoorTeam - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:35
   2. callback - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:292
    3. fn - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sh_shared.lua:177
     4. Call - addons/ulx/lua/ulib/shared/hook.lua:110
      5. PlayerHasAccess - addons/ulx/lua/ulib/shared/cami_global.lua:370
       6. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:43
        7. RP_PlayerChat - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:78
         8. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:142

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because it is a darkrp command which I did not touch

**Comment by deinemudda32** [comment]
Happens with togglegroupownable too.

**Comment by FPtje** [comment]
Cannot reproduce with `togglegroupownable`, not giving any arguments removes any door group from a door.
