### ISSUE TITLE
Hungermod error

### ISSUE THREAD

**Issue by hulapyk** [FPtje/DarkRP#2387]
### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This issue comes whenever I save any new stuff I made for my server via the cPanel.
I didnt have this issue yesterday tho, so it might be the Gmod update from today, 29/3/16

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
It just appears in my console after I save stuff on my server via the cPanel.

**### Lua errors**
[ERROR] lua/includes/modules/draw.lua:192: bad argument #3 to 'SetDrawColor' (number expected, got nil)
  1. SetDrawColor - [C]:-1
   2. RoundedBox - lua/includes/modules/draw.lua:192
    3. fn - gamemodes/darkrp/gamemode/modules/hungermod/cl_init.lua:74
     4. Run - addons/ulib/lua/ulib/shared/hook.lua:105
      5. HUDPaint - gamemodes/base/gamemode/cl_init.lua:75
       6. HUDPaint - gamemodes/sandbox/gamemode/cl_init.lua:75
        7. unknown - gamemodes/darkrp/gamemode/modules/hud/cl_hud.lua:403

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I haven't touched any of the hungermod files at all, all I have done is enabled it from the darkrpmodification, therefore my best guess is that you guys can fix it ;)

**Comment by Hazbelll** [comment]
Today's GMod update did cause some wacky stuff like that to happen. The update was shortly reverted (back to the last update from February).

Have you updated your Server since?

**Comment by hulapyk** [comment]
Nope, I will try that out and see what happens :)
Thanks! :+1:

**Comment by Hazbelll** [comment]
Was this the issue? Please provide a response if so and close the issue if it's resolved.

**Comment by FPtje** [comment]
I'm going to assume this was the update.
