### ISSUE TITLE
FAdmin is not setting access

### ISSUE THREAD

**Issue by FierDaGamerZ** [FPtje/DarkRP#2388]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
Was working on my DarkRP server and an error consisting of FAdmin setaccess had occurred. I couldn't noclip and noticed I wasn't set to my ulx group through FAdmin, and so I tried to set it in the rcon and console, but ended up with the same errors (listed below).

### How to make the bug happen
It was random, but I had done a lot of work adding entities, shipments, ammo, and jobs, and then after a restart FAdmin had errored up - but I don't think it's due to my additions (which were added through darkrpmodification addon)

### Lua errors
Anytime you try to set FAdmin access using the rcon or console, you get this:

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:315: attempt to call method 'GetUserGroup' (a nil value)
  1. callback - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:315
   2. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/commands/sv_concommands.lua:19
    3. unknown - lua/includes/modules/concommand.lua:54

### Why the developer of DarkRP is responsible for this issue
It seems like an issue with DarkRP, I did not modify original DarkRP files, or mess with FAdmin in the darkrpmodification addon.

**Comment by FierDaGamerZ** [comment]
After a fresh reinstall of the darkpmodification, it is infact a problem with DarkRP and not my changes.

May also be a product of today's update, but I haven't updated my server since last Friday's update.

**Comment by FierDaGamerZ** [comment]
Also to add in, it was working fine before.

**Comment by FPtje** [comment]
![hl2_2016-03-30_09-23-56](https://cloud.githubusercontent.com/assets/1202014/14134699/395b03d6-f659-11e5-8516-485cfe22afe9.png)

Works for me
