### ISSUE TITLE
My Gravity Gun On My Darkrp Server Wont Work

### ISSUE THREAD

**Issue by orbenhamo** [FPtje/DarkRP#2389]
My Gravity Gun Wont Work, And Ive Got CS Mounted.

This Is My  Mount.cfg Folder, Which is in the right place.

//
// Use this file to mount additional paths to the filesystem
// DO NOT add a slash to the end of the filename

 "mountcfg"
 {
  "cstrike" "D:\gmod\cstrike"
 }

Please Help Me, Thats My Last Step Before Publishing My Server

**Comment by FPtje** [comment]
It's not supposed to punt. Assuming that's your problem.
