### ISSUE TITLE
Solved, delete that..

### ISSUE THREAD

**Issue by Aka7tsu4** [FPtje/DarkRP#2391]
Sorry delete that please.

**Comment by Shigbeard** [comment]
"It is the server owner's responsibility to figure out why that player 
has no valid team."

Fucking. Read. Your god damn. Errors.

**Comment by Aka7tsu4** [comment]
Sorry i just wanted help. and don't wanted to be totally Insult be a unknow guys...

**Comment by Shigbeard** [comment]
Well once again, all the help you need can be found at forum.darkrp.com. You should only ever post here if something is completely fucked in DarkRP and it has nothing to do with a custom addon, job, or anything custom you've added on (to verify that its darkrp's fault, remove all your addons and reproduce)

**Comment by Aka7tsu4** [comment]
That's a better comment' nice, thanks for the help i will delete my post then.

**Comment by Shigbeard** [comment]
@Aka7tsu4 you can close the issue using the close button next to comment

**Comment by BillyOnWiiUIn144p** [comment]
Shigberd it's okay, you can vent c:
