### ISSUE TITLE
Lua errors fadmin spectate.

### ISSUE THREAD

**Issue by Aka7tsu4** [FPtje/DarkRP#2393]
[ERROR] gamemodes/darkrp/gamemode/modules/fspectate/sv_init.lua:112: attempt to index global 'FAdmin' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/fspectate/sv_init.lua:112
2. include - [C]:-1
3. unknown - gamemodes/darkrp/gamemode/init.lua:68

I can't spectate players now, and i don't touch core files.
Please don't flame me.

**Comment by FPtje** [comment]
did you disable FAdmin?

**Comment by Aka7tsu4** [comment]
No, i just don't update the fadmin because i got a bug, and i can't give me commands to superadmin

**Comment by Aka7tsu4** [comment]
saying "you can't add privilieges if you don't have this privilieges" sorry i'am french..

**Comment by FPtje** [comment]
You said you didn't edit core files
You also said you "don't update FAdmin"
You can't do that without fucking around with core files.

**Comment by Bo98** [comment]
Your FSpectate file is outdated too.

**Comment by Bo98** [comment]
In fact I'm not sure what on earth is in that file because FSpectate hasn't contained FAdmin references in sv_init.lua since it got moved to modules.
