### ISSUE TITLE
CP team  warrant and wanted

### ISSUE THREAD

**Issue by Aka7tsu4** [FPtje/DarkRP#2394]
CP teams, can wanted, and warrant an other cps.

**Comment by FPtje** [comment]
yes, because other CPs can commit crimes too.

**Comment by Aka7tsu4** [comment]
can you add a options to disable it please ? :)

**Comment by FPtje** [comment]
Code it yourself. The hooks are there.

**Comment by Bo98** [comment]
Specifically, use the canWanted and canRequestWarrant hooks.
