### ISSUE TITLE
/setspawn issu

### ISSUE THREAD

**Issue by BasonTaylor** [FPtje/DarkRP#2395]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (i may have removed the /setspawn command area. i was going through some stuff i fear i have removed the wrong thing. because when i do /setspawn they spawn back at the default spawn. and i am wondering witch file is that in? there are no lua error's)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by BasonTaylor** [comment]
i filled all that in

**Comment by BasonTaylor** [comment]
there is the simple way i did not feel like retyping all of that. sorry...
i may have removed the /setspawn command area. i was going through some stuff i fear i have removed the wrong thing. because when i do /setspawn they spawn back at the default spawn. and i am wondering witch file is that in? there are no lua error's

**Comment by FPtje** [comment]
Setspawn requires a job. It sets the spawn for a job. Not for everyone.

**Comment by BasonTaylor** [comment]
no i know i have been using dark rp for 2 years i know i think i may have deleted the file that the spawn command runs from i just need to locate it

**Comment by BasonTaylor** [comment]
basicly i can do the rest

**Comment by FPtje** [comment]
So you edited core files?

This is what you get, you mad idiot.

Corefiles.darkrp.eu

**Comment by BasonTaylor** [comment]
thank's i try X)

**Comment by BasonTaylor** [comment]
but is the "Corefiles.darkrp.eu" the file?

**Comment by BasonTaylor** [comment]
cant find it in the zip

**Comment by FPtje** [comment]
No, it's a website. Visit it for wisdom.

**Comment by BasonTaylor** [comment]
oh ok thanks sorry for the inconvenience

**Comment by BasonTaylor** [comment]
ah well i see great would have been better for a location but ok well ill see you guys another time i do somthing stupid
