### ISSUE TITLE
Broken chat bubble texture when Fadmin is disabled.

### ISSUE THREAD

**Issue by Jonathan-5** [FPtje/DarkRP#2397]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When Fadmin is disabled, the chat bubble that's above players heads, has a missing texture, it just turns in to a pink and black square
https://gyazo.com/417be8903408a2a802ef85a479a8f9c1

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Disable FADMIN.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No visible errors

**Comment by FPtje** [comment]
that chat bubble from your screenshot does not seem to be anything created by DarkRP. My chat bubble works fine with FAdmin disabled.

![hl2_2016-04-01_17-25-39](https://cloud.githubusercontent.com/assets/1202014/14211564/0ae6767a-f82f-11e5-9460-97a1151d2828.png)

**Comment by Jonathan-5** [comment]
Correct, I didn't notice my friend updated the HUD addon which had several new features which I didn't notice, anyway I solved the problem, thanks for the info :+1:
