### ISSUE TITLE
Error After Updating to 2.6.2

### ISSUE THREAD

**Issue by TEOTKU** [FPtje/DarkRP#2398]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Well not sure exactly. I updated to `2.6.2` and then shit hit the fan. I joined the game and spawned at pos (0,0,0) on rp_evocity_v33x (not necessarily saying that is your fault). Then the next thing is I can't use any of the SWEP's or even see the weapon selector bit. And I also can't use the F4 menu.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

After updating to 2.6.2, joining the server.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

http://pastebin.com/D8k4hAu4

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Well the error is coming from the darkrp core files and like you iterate, I'm not going near them...

**Comment by FPtje** [comment]
You made a bad demote group in the darkrpmod
