### ISSUE TITLE
/hitprice not working with disabled Fadmin

### ISSUE THREAD

**Issue by Jonathan-5** [FPtje/DarkRP#2399]
/hitprice not working with disabled Fadmin
I don't have time to test this and I wont be on anytime soon but I'll just leave this here.

**Comment by FPtje** [comment]
What's with you and having problems with FAdmin being disabled

**Comment by Jonathan-5** [comment]
I don't know hahah but this seems to work with just ulx, ulib, darkrpmodification. I'll continue testing even though I don't have time...

**Comment by FPtje** [comment]
Works fine with me with FAdmin disabled.

**Comment by Jonathan-5** [comment]
A staff member made a mistake and wasted 10 minutes of my life and 10 minutes of yours, I'm terrible sorry :( I'll personally check it next time

**Comment by FPtje** [comment]
Have you seen my April fool's joke by the way?
