### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by thescottgames** [FPtje/DarkRP#2400]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
ok can you send 25$ to my paypal because that how much i lost in refunds for vip and vip+ because of you dumb ass April fools shit and now my server is full of trollers and peaple trying to get peaple to say rdm fail rp nlr 

paypal therealscottgame@gmail.com 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
yes there is a shit ton of lua errors and all the people are the job joining and connection 

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
because you fucking put it in there you dumb ass

**Comment by thescottgames** [comment]
also they said they will report my acount for scament because this go agensted the the things that will not happen to if your a donater

**Comment by thescottgames** [comment]
also now i am vac banned from cs go because a kid traded me a skin for vip and i was vac banned for scamment

**Comment by AlauraLeafLoveless** [comment]
I'm sorry but im laughing my ass off here, if you can't be bothered to read such a simple file you don't deserve to host a gamemode.

**Comment by thescottgames** [comment]
also this is what happens when you try to do any thing 

[ERROR] workshop/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - workshop/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - workshop/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

**Comment by thescottgames** [comment]
also i did read the file im just pissed

**Comment by thescottgames** [comment]
ok im joking about all of this nothing happend but ether way you need to fix this
i reinstalled the dark rp and when i join everything is mested

**Comment by BillyOnWiiUIn144p** [comment]
fucking hell, let me guess, you're British and somewhere between 12-15. the level of autism here is actually slowly killing me. I don't know if there's words to describe how frustrated I am just reading this issue

**Comment by Noiwex** [comment]
kek
