### ISSUE TITLE
base hand error

### ISSUE THREAD

**Issue by tiweb442** [FPtje/DarkRP#2404]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
[ERROR] gamemodes/base/entities/entities/gmod_hands.lua:31: Tried to use a NULL entity!
  1. DeleteOnRemove - [C]:-1
   2. DoSetup - gamemodes/base/entities/entities/gmod_hands.lua:31
    3. SetupHands - lua/includes/extensions/player.lua:225
     4. Call - workshop/gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:525
      5. changeTeam - workshop/gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua:153
       6. callback - workshop/gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:220
        7. createVote - workshop/gamemodes/darkrp/gamemode/modules/voting/sv_votes.lua:106
         8. callback - workshop/gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:215
          9. callback - workshop/gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
           10. unknown - workshop/gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:255
            11. unknown - lua/includes/modules/concommand.lua:54

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
by switching weapon

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/base/entities/entities/gmod_hands.lua:31: Tried to use a NULL entity!
  1. DeleteOnRemove - [C]:-1
   2. DoSetup - gamemodes/base/entities/entities/gmod_hands.lua:31
    3. SetupHands - lua/includes/extensions/player.lua:225
     4. Call - workshop/gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:525
      5. changeTeam - workshop/gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua:153
       6. callback - workshop/gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:220
        7. createVote - workshop/gamemodes/darkrp/gamemode/modules/voting/sv_votes.lua:106
         8. callback - workshop/gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:215
          9. callback - workshop/gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
           10. unknown - workshop/gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:255
            11. unknown - lua/includes/modules/concommand.lua:54

**Comment by Bo98** [comment]
This should only happen if the PlayerSetModel hook was called in PlayerInitialSpawn or something.

Do you have any earlier errors when players joking the server?

**Comment by FPtje** [comment]
Yup, you've gotten in some state that DarkRP itself won't get you in. I'm thinking of some weird SWEP or addon.
