### ISSUE TITLE
Fadmin Banlist

### ISSUE THREAD

**Issue by killerrichard** [FPtje/DarkRP#2405]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Unbanlist empty on the Tab fadmin menu

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

add null steamid to banlist via /ban or use /ban steamid 1 to modify a perm ban without having unban permission 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 33

  1. error - [C]:-1
   2. ReadType - lua/includes/extensions/net.lua:182
    3. ReadTable - lua/includes/extensions/net.lua:124
     4. func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/playeractions/kic
kban/cl_init.lua:346
      5. unknown - lua/includes/extensions/net.lua:32

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

--Kiloka is my second account on github--
thx you again for the fix of my banlist (1800 ban) ^^

**Comment by FPtje** [comment]
Describe how to add "null" to the banlist via /ban. What's the command for adding null?

**Comment by killerrichard** [comment]
I test this, thanks for this fix :)

**Comment by killerrichard** [comment]
work like a charm thx !
