### ISSUE TITLE
Money Being Reset - Conflicting Player Names?

### ISSUE THREAD

**Issue by Flumadiddle** [FPtje/DarkRP#2406]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Player A has the steam name 'John' with about 400k in his wallet.
A new player joins the game for the first time with the steam name 'John' as well.
Player A's wallet is reset.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
^^ Same

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No known Lua errors.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Database related. Pretty sure there are no addons conflicting.

**Comment by MStruntze** [comment]
Names are not used for database indexing

**Comment by NotSoSuper** [comment]
Name of the player doesn't influence the money system at all.

Get better admins.

**Comment by FPtje** [comment]
What are the SteamIDs of the two people you know this happens with?

**Comment by FPtje** [comment]
I can't do anything with this issue. If it's really steam names that causes this, then it must be an addon.
