### ISSUE TITLE
another fucking April Fools shit  

### ISSUE THREAD

**Issue by thescottgames** [FPtje/DarkRP#2407]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
ok wtf is wrong with you with this shit again
when i get in it spams 
var ass = function("hiasshole")

fuction("hiasshole")
if (say)"fuck you" = true

gm_assholyness = "100"

if gm_assholyness = 100 then 1

return

if return = 1 (gm_imaasshole2 = true

if true (say)"well now the code say's your a asshole"

else (say)"well guess not"

end

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
idk you fucking added it

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
no lua errors

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
you put it in there and you should go kiss my ass

FAQ
yes i am from Briton
yes i am 13
yes i have autism 
yes your a gay ass hole and should KYS

DIY("do it yourself"you fucking retarted)
jump off a brige 
get kidnap ed by isis
let the police look at your house and see drugs then go to prison to get ass raped by personers
get a girlfriend then get aids
drink bleach 
fall from a 10 story building
get your dick stuck in a elevator
jump off a brige 
see to many dank meams  
jack off to much because you don't have a girl friend then you balls explode

**Comment by Shigbeard** [comment]
holy shit this issue is cancer

**Comment by AlauraLeafLoveless** [comment]
Dude, go get help seriously, If you can't even read. Or fix your own
problems you don't deserve to host servers.

On Fri, Apr 8, 2016 at 9:41 PM, Nathan Davies-Lee <notifications@github.com>
wrote:

> holy shit this issue is cancer
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FPtje/DarkRP/issues/2407#issuecomment-207686527>
>



-- 
Thanks for emailing me, have a great day and or year.

~Asuna

**Comment by BillyOnWiiUIn144p** [comment]
Jesus christ I guessed correctly

```
yes i am from Briton
yes i am 13
```

please don't embarrass this country. seeing people who can barely speak English from my own country that speaks English natively hurts.

you're probably a northerner?

**Comment by NotSoSuper** [comment]
drink bleach?
