### ISSUE TITLE
it's possible?

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2408]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
you can turn off, you buddies list?
users can take advantage of this option and abuse it
I would like that it can be disabled from the settings.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
I don't know what this is, but it's invalid.

**Comment by Shigbeard** [comment]
It looks like a suggestion to disable and enable the buddy list using a toggle or something

**Comment by FPtje** [comment]
Sure, it does. Does that mean I should make the reasoning up myself?

**Comment by Shigbeard** [comment]
It also appears the reasoning is people forgetting to clear ex-friends from their buddy list.

I honestly can't tell, it's like this particular DarkRP user is 6 years old, thats got to be a record.

**Comment by FPtje** [comment]
that's not taking advantage, that's stupidity.

**Comment by matiasg90** [comment]
I do not speak English, so my misunderstood
specifically, what I meant is what he said.

**Comment by Shigbeard** [comment]
@matiasg90 If you are using Google Translate, Google has a hard time telling nouns, verbs, and adjectives apart from one another.

This is probably where your translation failed.
