### ISSUE TITLE
[req] Unwarrant chatcommand?

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2409]
There's a wanted and unwanted, but why's there no unwarrant? Due to the nature of the weird findPlayer function which targets an incorrect player every second time, an unwarrant chatcommand would be of good use.

**Comment by FPtje** [comment]
oh for fuck's sake the changes I have to make for this 

God damnit why did you ask for this

**Comment by FPtje** [comment]
There you go!

And I want to hear none of the way it works. Cops should be able to revoke warrants on their own. This shit shouldn't go past a mayor like requesting a warrant does. Why? Effort to implement most importantly, but also, people don't like voting, unwarranting is an insignificant action, mayors won't care.

Also, this creates a funny dynamic: good cops requesting a search warrant and getting it past the mayor, with one bad cop removing the search warrant immediately. I've made it so you can't do that while arrested, so the good cops should arrest the bad cop. That is RP and as such very good, yes.
