### ISSUE TITLE
DarkRP.findPlayer is flawed

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2410]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
DarkRP.findPlayer seems to result in weird and incorrect results.
When used in cases like /wanted it can result in incorrect wanted/warrant targets.
This seems to be because it sometimes checks steam names before rp names?

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
A player called Victor on Steam has an rp name of Ronald in-game.
Another guy called Victor in game has a completely random steam name.
Upon making Victor (ingame name) wanted it makes Ronald wanted.
Example: https://gyazo.com/42b6e32d3db8f74d7499a1b4fbfac0c7 where the message is hooked to playerWanted

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
- Not relevant 

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The findPlayer function is a part of DarkRP and is to blame for this I guess?

## Possible solutions
- Prioritize Rp names at all times?
- ~~Make it possible to use steamids if names collide? ULX makes this possible by using $STEAMID~~ you can already do this, my bad.
- Allow quotes for the names to be able to differ names like "Ronald One" and "Ronald Two". fx: /wanted "Ronald One" - which then would use both words instead of only the first one?

**Comment by Bo98** [comment]
No idea why it checks Steam names first. FAdmin.FindPlayer does the opposite.

> * Make it possible to use steamids if names collide?

You already can.

**Comment by MStruntze** [comment]
Yea i just noticed that, my fault.
