### ISSUE TITLE
Lua error when setting first superadmin on vanilla gmod + darkrp (no addons)

### ISSUE THREAD

**Issue by rickyrb** [FPtje/DarkRP#2411]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Unable to set superadmin on a fresh darkrp server with no addons or modifications.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
When using the command to set the first superadmin (server console)
"fadmin setaccess "STEAM:0:1:1122334455 superadmin"

Trying to set a superadmin ingame causes the same lua error.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
http://pastebin.com/A0caTNQc
only lua_errors_server.txt was generated

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I think this is caused after the recent hot fixes and updates by garry, maybe those updates screw some things over, the server im using is just a plain just fresh out of the box on a bracked with windows server 2012, and for the rest SteamCMD and gmod + darkrp installed.

if you could look at it, it would be appreciated, if there is nothing wrong with it, i would gladly take it to the forums and i would deeply apologize for the false report.

**Comment by Shigbeard** [comment]
That doesn't look like a SteamID to me.

**Comment by Bo98** [comment]
Regardless, I can reproduce the bug from the server console.

**Comment by Bo98** [comment]
It's caused by a bad server console check: https://github.com/FPtje/DarkRP/blob/0d2e44709e9c37fbc3f0e1f9fb92c5031b179a1b/gamemode/modules/fadmin/fadmin/access/sv_init.lua#L315 (although calling `:EntIndex()` on the server console "entity" returns 0, it is because it is a NULL entity rather than it representing the worldspawn entity that's returned by `Entity(0)`)
