### ISSUE TITLE
Default F4 Menu Not working + Data loadment problem

### ISSUE THREAD

**Issue by SmzKosTek** [FPtje/DarkRP#2414]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Once I join my server my job is Unassigned and mostly it says that " Your data is not loaded (...) "
Also Default F4 Menu is not working, when I try to press f4 it does not work

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

With data loadment problem... Once joined server / once booted the server
With F4 menu.... You have to try to open Job menu and it doesnt work

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

--Data Loadment--

Did not find any errors in console mostly just this;
"Your data has not yet been loaded."

--F4 Menu--

[DarkRP] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Errors are in DarkRP gamemode content which means that this Might be creators fault.
However with data loadment problem, even with no addons it does not Load the data... Trying to reinstall server and install everything back again doesnt help.

**Comment by FPtje** [comment]
When you break things, DarkRP might eventually error. That error cannot stand on its own. Always look for the earliest error.

**Comment by SmzKosTek** [comment]
Alright So I check the Server console... and I found this;

[ERROR] gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:298: attempt to write a readonly database (DELETE FROM FADMIN_PRIVILEGES WHERE NAME = "user" AND PRIVILEGE = "SetAccess";)
  1. error - [C]:-1
   2. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:298
    3. callback - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:24
     4. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:302
      5. fn - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:14
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:110
        7. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:163

This is the error that pops up on server console when Server is booted.

**Comment by BillyOnWiiUIn144p** [comment]
I mean, it tells you the problem. Your database is read only.

**Comment by BillyOnWiiUIn144p** [comment]
If you're not using MySQL, change the properties of garrysmod/sv.db on your server so that it can be written (turn off Read Only)
