### ISSUE TITLE
Invalid arguments 

### ISSUE THREAD

**Issue by Redtroz** [FPtje/DarkRP#2416]
Sorry for my bad english. I am a Belgian

When i want to add these privileges:

DarkRP_AdminCommands
DarkRP_ChangeDoorSettings
DarkRP_GetAdminWeapons
DarkRP_GetJob_cp
DarkRP_GetJob_mayor
DarkRP_SeeEvents
DarkRP_SetDoorOwner
DarkRP_SetLicense
DarkRP_SetMoney

I have an Invalid argument

Please help!!

**Comment by sweepyoface** [comment]
# (DO NOT REMOVE THIS TEMPLATE.)
# (GITHUB ISSUES ARE **NOT** FOR HELP)
# (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

What about that did you not understand?
