### ISSUE TITLE
Functions/Player/Server/changeTeam with a config string?

### ISSUE THREAD

**Issue by sweepyoface** [FPtje/DarkRP#2417]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

http://wiki.darkrp.com/index.php/Functions/Player/Server/changeTeam does not work with external strings.

`target:changeTeam(TEAM_CITIZEN, true)` works but

`StickConfig.DemoteTeam = "TEAM_CITIZEN"`
`target:changeTeam(StickConfig.DemoteTeam, true)` does not.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Try to do the above.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None, it doesn't echo anything.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

It's a DarkRP function.

**Comment by FPtje** [comment]
Of course! What on earth made you think `TEAM_CITIZEN` is the same as `"TEAM_CITIZEN"`!?

**Comment by sweepyoface** [comment]
Fuck, you got me on that one.

**Comment by sweepyoface** [comment]
How would I convert the job number to the actual TEAM_NAME? Something like

`Stick_SendChat(Player, "This player is already a " .. GAMEMODE.DefaultTeam)` but that just gives me

`This player is already a 1`

**Comment by FPtje** [comment]
`RPExtraTeams[teamnumber]`, though I must stress that this is not a help forum. http://forum.darkrp.com is
