### ISSUE TITLE
Missing Model

### ISSUE THREAD

**Issue by Derkason** [FPtje/DarkRP#2424]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible) 

Everytime I drop money it just floats there as if it didn't exist, the money become non-collided. No errors appear in-game console though in web console errors appear. Unable to roleplay without money being able to /dropmoney..

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

I /dropmoney (any amount) Errors appear

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

Model missing: models/props/cs_assault/money.mdl
 
[ERROR] gamemodes/darkrp/entities/entities/spawned_money/init.lua:17: Tried to use a NULL physics object!
  1. Wake - [C]:-1
   2. unknown - gamemodes/darkrp/entities/entities/spawned_money/init.lua:17
    3. Spawn - [C]:-1
     4. createMoneyBag - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:46
      5. unknown - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:162

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The model doesn't seem to be missing, it all says gamemodes/darkrp.

**Comment by FPtje** [comment]
http://mounted.darkrp.eu

It's been a while!

**Comment by Derkason** [comment]
Okay, thanks, yeah I got a host and I have CS:S and the mountcfg setup so it must be on their end. :( Appreciate the quick response and the laugh that came with it. xD
