### ISSUE TITLE
Darkprp -1 line

### ISSUE THREAD

**Issue by darksky27** [FPtje/DarkRP#2428]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
When i join my server it says there is and error on line -1 and that line does not exist so what do i do?

**Comment by darksky27** [comment]
This is the error

 [ERROR] A runtime error has occurred in "your jobs" on line -1.
The best help I can give you is this:

The category of "nil" ("Other") does not exist!

Hints:
- Make sure the category is created with DarkRP.createCategory.
- The category name is case sensitive!
- Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
your jobs
------- End of Simplerr error -------

**Comment by Shigbeard** [comment]
Read the error and you will find your solution.
