### ISSUE TITLE
DarkRP Issues

### ISSUE THREAD

**Issue by Ructar** [FPtje/DarkRP#2429]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Im trying to make a SWRP Server, and all the jobs and categories but it seems that darkrp just wont load.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
I have no idea.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
https://gyazo.com/45be36b6b2a13cada020c16115da164b

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Hes not. I just need some assistance on why this is caused.

**Comment by Shigbeard** [comment]
Invalid issue.

goto the forums dipshit.
