### ISSUE TITLE
Arresting Issue

### ISSUE THREAD

**Issue by dan2735** [FPtje/DarkRP#2430]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When a player is arrested his weapons do not get stripped and he does not get the unarrest countdown message.  They also do not get unarrested when time is up. They DO get ported to the jail, walk slow, and get the payday missed message.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Get arrested.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None.

`usermessage.Hook("GotArrested", function()
	print("test")
end)`

does nothing.
### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I searched through all my files and there is nothing overriding the arrest functions or usermessages and I am running a clean DarkRP install.

**Comment by FPtje** [comment]
Something is returning true in the player arrested hook. Cannot reproduce.
