### ISSUE TITLE
Variable defined but no declared

### ISSUE THREAD

**Issue by DiablosGamer** [FPtje/DarkRP#2431]
Hi ! I tell you today for your DarkRP 2.7.0 version.
There is this errors : 
05/01/2016 19:51:19: Lua Error Chat command "911" is defined but not declared!
Chat command "911" is defined but not declared!
05/01/2016 19:51:19: Lua Error Chat command "999" is defined but not declared!
Chat command "999" is defined but not declared!
05/01/2016 19:51:19: Lua Error Chat command "000" is defined but not declared!
Chat command "000" is defined but not declared!
05/01/2016 19:51:19: Lua Error Chat command "unwarrant" is defined but not declared!
Chat command "unwarrant" is defined but not declared!
05/01/2016 19:51:19: Lua Error Chat command "policepayment" is defined but not declared!
Chat command "policepayment" is defined but not declared!
05/01/2016 19:51:19: Lua Error Chat command "112" is defined but not declared!
Chat command "112" is defined but not declared!

I know that certain chat commands are because of me, but there is this DarkRP file which creates problem, see here : https://github.com/FPtje/DarkRP/commit/268946734849c3df2d370f01dcad271f5e7b24a9

How fix that ? Thanks by advance!

**Comment by AMD-NICK** [comment]
-_-

**Comment by DiablosGamer** [comment]
Yeah I know that but why this is not directly in the DarkRP ?

**Comment by Bo98** [comment]
It is, check the commit you linked.

Unwarrant is declared here:

https://github.com/FPtje/DarkRP/blob/268946734849c3df2d370f01dcad271f5e7b24a9/gamemode/modules/police/sh_init.lua#L97-103

/policepayment is not a DarkRP command.

**Comment by FPtje** [comment]
This is a problem caused by some kind of customisation.
