### ISSUE TITLE
playerBoughtShipment returns a nil price value

### ISSUE THREAD

**Issue by EmperorOfTheInternet** [FPtje/DarkRP#2433]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[playerBoughtShipment
![untitled](https://cloud.githubusercontent.com/assets/11928956/15060268/8d6de964-12ee-11e6-9a31-a1f48502637b.png)
](http://wiki.darkrp.com/index.php/Hooks/Server/playerBoughtShipment) is returning nil instead of a **price**

### How to make the bug happen
```
hook.Add("playerBoughtShipment", "TestShipment", 	function(ply,entTable,ent,price) 
	print( ply, entTable, ent, price )
end)
```

### Lua errors
It makes shipments in DarkRPG2 or any other addon using it free for the purchaser because it slings a nil value return.

### Why the developer of DarkRP is responsible for this issue
This was a issue solved I think in 2013, but someone just notified me of it happening again, I redownloaded the newest version of DarkRP from github and this also caused the issue. I am using a vanilla GMOD with only DarkRP installed.

**Comment by 00875** [comment]
https://github.com/FPtje/DarkRP/blob/a20464ac789824b26df1aad2c9c3834d6f702b30/gamemode/modules/base/sv_purchasing.lua#L157
But hook uses price
https://github.com/FPtje/DarkRP/blob/a20464ac789824b26df1aad2c9c3834d6f702b30/gamemode/modules/base/sv_purchasing.lua#L188

**Comment by FPtje** [comment]
Blind fix, should do it.
