### ISSUE TITLE
Error in compatibility ulx and ulib

### ISSUE THREAD

**Issue by dok441** [FPtje/DarkRP#2436]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Error with work, work just an empty bug, choose this work and this error occurs, it is associated with the ulx and ulib remove them, no problems, set them, error will appear, will remove a job to the other, so same mistake is not visible on the TAB choose a profession through Fadmin, it is removed from Spika choice of professions, but in the f4 menu there.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
You need to install ulx and ulib, I have code like this in your work http://pastebin.com/Y9sK9SvY Better install my jobs and select job, empty the bug it turns out this error, if work removed, then the error to move to another job.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
This error occurs when the choice of profession and profession.
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua" on line 384.
The best help I can give you is this:

There is a player with an invalid team!

The player's name is dok441, their team number is "1001", which has the name "Unassigned"

Hints:
	- It is the server owner's responsibility to figure out why that player has no valid team.
	- This error is very likely to be caused by an earlier error. If you don't see any errors in your own console. Look at the server console.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 384
	2. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 373
	3. gamemodes/darkrp/gamemode/modules/money/sv_money.lua on line 25
	4. gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua on line 172
------- End of Simplerr error -------
)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Bo98** [comment]
This happens when you remove a group while you are assigned to the group.

https://github.com/TeamUlysses/ulx/issues/41

**Comment by FPtje** [comment]
Nice work bo

**Comment by Bo98** [comment]
This has now finally been fixed.

**Comment by Priorrr** [comment]
Can you tell me how you fixed it? I am getting the same thing and its pissing me off.

**Comment by Bo98** [comment]
Make sure ULX is up-to-date. If it is, you have a different issue than what was resolved here.
