### ISSUE TITLE
Babygod resets colors set on a model

### ISSUE THREAD

**Issue by RhapsodySL** [FPtje/DarkRP#2437]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When you set a model to have a custom color via a spawn function in jobs.lua, and Babygod is enabled, the color is applied while the player is transparent, but reverts after Babygod is revoked. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Adding the following code to a job reproduces this;

PlayerSpawn = function(ply) ply:SetColor( Color( 75, 75, 75, 255 ) ) end,

This is because to apply the transparency, Babygod sets the color and modifies the alpha instead of using a material. This could be solved by using a material instead, but the base issue would still exist; a base feature in DarkRP is overriding user changes from darkrpmodification. If a user wanted to edit a material on a job on spawn, they'd run into the same issue if Babygod was modified to do that.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
This is due to the way that Babygod is implemented, overriding the color set on a job if it's set through jobs.lua. The issue ceases to exist if Babygod is disabled, and I've personally confirmed it's Babygod's doing by looking at the code.

**Comment by Bo98** [comment]
Suppose you could hack it with render.SetBlend in the PrePlayerDraw and PostPlayerDraw hooks. It would affect anything drawn in the PostPlayerDraw hook however, though in some cases that could be a good thing (eg. hats would be semi-transparent). No idea what every addon uses the hook for so it might not be safe to assume you can impact everything, idk.

**Comment by Bo98** [comment]
It might be possible to draw the player in PrePlayerDraw and return true to prevent the default draw operation. Should not impact anything else but it might be overridden by other addons doing the same thing. I'm assuming this would be a regression through ply:DrawModel probably (not checked) listening to ply:SetColor and thus working fine previously.

**Comment by Shigbeard** [comment]
Can you not simply record the player's color /before/ babygod does its 
thing, and re-apply it after babygod has expired?

Inb4 24x24 png images of cardboard boxes.

**Comment by Bo98** [comment]
Possibly, but we would need to watch out for ply:SetColor draws during babygod (which currently breaks our colouring).

**Comment by Shigbeard** [comment]
then swap out ply:SetColor with a function that checks if babygod is active, and queues color changes for after babygod has expired?

I can think of only one thing that could cause havoc with that, and thats a script that basically cycles a player's color into rainbows...

**Comment by FPtje** [comment]
Color, material, weight, gravity, model and groin size are all properties of players/entities that conflict when two or more addons want them to be different for the same entity at the same time. After all, the state of the entity is shared among all addons. @Bo98 tries to avoid the problem with the Pre/Post PlayerDraw hooks, but that could create new conflicts, since the state of the players in those hooks and even the hooks themselves are still shared.

Storing colour changes could be a good idea, though unlike @Shigbeard suggests, one does not need a queue. Just storing the latest colour per player would be good enough. Another idea could be to demand that the colour is not set during babygod because of those conflicts. That would essentially be "*Babygod is DarkRP's time with the player. Do your thing some other time.*". This would be easy for me, but it might not be reasonable.

**Comment by MaDmaxwell311** [comment]
Could you not avoid the problem by having Playeraloadout occur after Babygod?

**Comment by FPtje** [comment]
That is no option because babygod can last quite a while. Running PlayerLoadOut after that would be insane.

Running PlayerLoadOut directly after babygod starts is also not an option, since the end of babygod will still reset the colour.
