### ISSUE TITLE
Weird weaponbugs

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2439]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The Fist-HoldType does not work the right way in DarkRP.
In Sandbox for example the Fistholdtype works perfectly fine, but in DarkRP it doesn't seem to work perfectly at all.
Sometimes it uses instead of the forced Fist Holdtype a different one like pistol, normal or camera.
It seems to have something to do with the "normal" Holdtype as the normal Holddtype is often overriden by the Fist Holdtype

However there is another bug with weapons shooting slower than in the sandbox gamemode with the same tickrate and fps. I do not know if this is supposed to be that way, but I do not think so.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
The Fistholdttype bug does not work in listen servers or singleplayer, only in dedicated ones as far as I can see.
In Sandbox for example everything works quite fine.

However the weapon shooting slower-bug can still be reproduced, but is not happening all the time either.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
In Sandbox these bugs did never appear and everything is working quite fine.
I run a DarkRP and a Sandbox server with nearly identical content, I do not think I caused this, as it does happen even with no modifications made at all, besides DarkRPmodification addon.

**Comment by MaDmaxwell311** [comment]
I too have noticed this is my time, I have also noticed that some wepons ( for example M9k ) will speed up in firing speed in sandbox and slow down in DarkRP and then another one will be reversed. Tested with a key macro that did one click per tick for 3 seconds, and each time the wepon fired, a message was printed in console.  

What is odd is that the amount of rounds fired was different. I have tried to explain it but have failed, I finally thought it was just the "lag" each gamemode causes and that some base functions had been overwritten.

**Comment by FPtje** [comment]
Despite your efforts, this isn't a valid bug report. I'm sorry.

The issue description is vague at best. 

- You do not specify the *when* holdtypes are changed, the only thing you say is "sometimes"
- The hold types can supposedly change to pistol, normal or camera. What, is it picked randomly???
- The "how to make bugs happen" section doesn't tell me **anything** about how to reproduce the bug. I need steps.
- The fact that you don't have this problem in sandbox does not prove that my code is at fault. 

On the last point, DarkRP does **nothing** with holdtypes outside of its own SWEPS and SWEPS based on `weapon_cs_base2`, which only exists in DarkRP. As such, DarkRP **cannot** directly be the cause of whatever holdtype problems you have.

Now about the "slower firing", I have no clue what you even mean. Yet again I lack steps to reproduce anything. By slower firing you could mean many things, ranging from seeing a delay between mouse click and gun shot to amount of bullets shot per second when holding the mouse down on automatic weapons. Yet again I see no proof that DarkRP's code is responsible for any of this.

**Comment by mcNuggets1** [comment]
I wrote how to reproduce it in the Description of the bug, sorry.

**Comment by mcNuggets1** [comment]
HoldTypes:
Happens randomly when changing Fists to another weapon and back, or after dying and changing back, or even after selecting another weapon which uses HoldType "normal" (overrides it).

Slower Shooting:
I did a rewrite of the whole m9k base, fixing every bug and redoing all that shitty base.
I firstly thought It was a M9k bug, but it was not!

In the SBox Gamemode you can shoot faster with the weapon, means more bullets per second.
In DarkRP it shoots slower. I dont know why.

**Comment by FPtje** [comment]
@Bo98 Tested it on a dedicated server and still can't reproduce the HoldType issue. I myself can't reproduce any "more bullets per second" issue.

**Comment by Bo98** [comment]
Feel free to test it out on:

```
connect 31.186.250.154; password issue2439
```

**Comment by mcNuggets1** [comment]
I tested it again and it works flawlessy on my listen server, but as soon as it comes to the dedi it begins to bug around.

**Comment by mcNuggets1** [comment]
http://puu.sh/oRYaz/32b392288e.jpg
Screenshot from my original server.

**Comment by mcNuggets1** [comment]
I was on another server today, happens there too.

**Comment by FPtje** [comment]
I'm not going to chase ghosts. I have no way of reproducing it and as such no way of fixing it.

**Comment by mcNuggets1** [comment]
The problem is, I don't know how to reproduce the issue, but I saw it happen on a vanilla DarkRP server either.
There has to be heavier lag as far as I know.

**Comment by mcNuggets1** [comment]
https://facepunch.com/showthread.php?t=1521278
It is still there.
