### ISSUE TITLE
If color is set by ply:SetColor in a job, it persists even when switiching to a job that doesn't use a custom color

### ISSUE THREAD

**Issue by RhapsodySL** [FPtje/DarkRP#2441]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
In relation to #2437, if you customize the color of a job during PlayerLoadout (and probably PlayerSpawn) with ply:SetColor, the color you set on that job will persist to other jobs indefinitely unless the color is reset in some other way.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Set the color with ply:SetColor during PlayerLoadout on one job. Switch to that job, and then switch to another job, and the color will persist. You may need to disable Babygod to reproduce this with the latest update, but I'm pretty sure you shouldn't.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Colors aren't reset upon spawn. I'm not sure if this is in general, or if it's only when the player respawns after selecting a new job, but the only way to fix this behavior from darkrpmodification would be to set a custom color for *every* job.

**Comment by Bo98** [comment]
This applies to most things, not just colors. I'm not sure if there's much that can be done.

**Comment by FPtje** [comment]
It means you're using the wrong hook to set the color.
