### ISSUE TITLE
Fadmin issue

### ISSUE THREAD

**Issue by xProlithium** [FPtje/DarkRP#2442]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Using any other tab menu, when attempting to modify the fadmin groups, an error appears and doesn't allow me to modify or add groups. EDIT: The issue no longer persists when Fadmin is disabled in the disable_defaults part of the darkrpmodifications.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Tab, Server Settings, Edit Groups, and then the error appears either when I click Add group or when it the list pops up.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
With the tab menu:
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:260: attempt to index field 'user' (a nil value)
  1. Click - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:260
   2. DoClick - addons/darkrp_tabmenu/lua/autorun/client/metrotab_commandbutton.lua:41
    3. unknown - lua/vgui/dlabel.lua:218

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Frankly, it could very well be me and I just don't know it. However, I've looked into it extensively and went to the tab menu creators first, I also went as far as to do a full Gmod wipe and the issue still happened. I'm at a dead end and would like to fix this issue once and for all.

**Comment by Bo98** [comment]
No idea why people seem to get that error. Out of interest, could you run `lua_run PrintTable(FAdmin.Access.Groups)` in the server console and tell me if anything gets outputted?

**Comment by xProlithium** [comment]
Nothing appears when I run the console command. When I switched Tab menus, the error changed but still points towards Fadmin.

That error states the following:
[ERROR] darkrp_tabmenu/lua/vliss/config/sh_config_gamemode_darkrp.lua:324: attempt to call global 'addGroupUI' (a nil value)
  1. DoClick - addons/darkrp_tabmenu/lua/vliss/config/sh_config_gamemode_darkrp.lua:324
   2. unknown - lua/vgui/dlabel.lua:218

**Comment by FPtje** [comment]
I've seen this kind of stuff happen when there are earlier errors that prevent FAdmin from loading.

**Comment by Bo98** [comment]
Looks more like in this case to be an error preventing FAdmin from sending the groups to clients.
