### ISSUE TITLE
[request] nore spawn on unarrest with stick

### ISSUE THREAD

**Issue by fruitwasp** [FPtje/DarkRP#2444]
Like I said in the title of the issue, add the option to choose whether to respawn at the spawn location or nore spawn whenever unarrested with the unarrest stick. Nothing more, nothing less.

**Comment by FPtje** [comment]
DIY with `playerUnArrested` hook. Check the actor's active weapon and trace. That should do.

**Comment by fruitwasp** [comment]
disabled `telefromjail`, copied the code inside to a `playerUnarrested` hook, and only made it run whenever the unarrester is invalid
