### ISSUE TITLE
Lua refresh errors

### ISSUE THREAD

**Issue by wick0302** [FPtje/DarkRP#2449]
Okay so you have probably met this alot and i appreciate this ut when i am currently making my darkrp server and whenever i update a file such as jobs.lua, (even with #nosimplerr#) my f4 breaks, my tab menu also breaks and basically my server/game decides it does not want to refresh everything???

**Comment by MarbellaRP** [comment]
You have to restart your server to have the change taking effect.

**Comment by wick0302** [comment]
okay, so is this the only way we can refresh our lua files now?

**Comment by MarbellaRP** [comment]
Mapchange work also if you want to save time.

**Comment by wick0302** [comment]
Nice, thanks for the help. just wondered if there was any quicker way of a fix. :)

**Comment by Bo98** [comment]
It's

```lua
-- #NoSimplerr#
```

(case matters IIRC)

**Comment by wick0302** [comment]
Have done that Bo98, my server decides it wants to disable the f4 and tab for players on the server unless they relog

**Comment by Bo98** [comment]
You likely have Lua errors then.

**Comment by wick0302** [comment]
Im getting none however when darkrp reloads. it doesnt reload in my custom f4 and tab
:/

**Comment by wick0302** [comment]
should it have something like

Reloaded Control: FAdminPanelList
Reloaded Control: FAdminPlayerCatagoryHeader
Reloaded Control: FAdminPlayerCatagory
Reloaded Control: FAdminActionButton
Reloaded Control: FAdmin_weaponPanel
Reloaded Control: F1MenuTitleLabel
Reloaded Control: F1SearchBox
Reloaded Control: F1HTML
Reloaded Control: F1HTMLControls
Reloaded Control: F1MenuPanel
Reloaded Control: F1ChatCommandPanel
Reloaded Control: F1ChatCommandLabel

**Comment by wick0302** [comment]
because it doesnt

**Comment by FPtje** [comment]
not a help forum.
