### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by RedTailedHawkSTM** [FPtje/DarkRP#2450]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
I press f4 to go into the jobs and it gives the error.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Error in hook ShowSpare2: gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
stack traceback:
	gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: in function <gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:20>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'
	lua/.dragondildos/rc1/../nul/30c2b9fc593e983633fe64297da3ce072cacffb2e5c9dd2558d438524589e786.lua:59: in function 'Call'
	gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62: in function <gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:57>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'
Error in hook PlayerBindPress: gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62: 
stack traceback:
	[C]: in function 'Call'
	gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62: in function <gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:57>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Not a help forum.
