### ISSUE TITLE
Duplicate entries (darkrp_player)

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2451]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # https://i.gyazo.com/34cb879e92cc920cc9ab421d1aacade2.png
Table darkrp_player receives duplicate entries and rare symbols. (€‹)

**Comment by FPtje** [comment]
Yes, desired behaviour for backwards compatibility.
