### ISSUE TITLE
Using F3/F4 create's Errors.

### ISSUE THREAD

**Issue by Vizikk** [FPtje/DarkRP#2452]
### Description of the bug
[//]: # (Describe the issue as accurately as possible)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Press F4 and/or F3.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:234: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:234

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The server is fresh and new. Nothing on it except the gamemode and the addon needed. Cannot be anything else.

**Comment by FPtje** [comment]
Try with the latest version.

**Comment by Vizikk** [comment]
I did, same thing happened. Also my server host has confirmed its not the server or my error, due to them offering the gamemode as a Quick Install and it being the up-to-date version.

**Comment by Bo98** [comment]
Check for errors on server startup rather than just when you press F3 or F4. The error you posted is likely caused by a previous error.

**Comment by Vizikk** [comment]
Okay last night when I posted this, I was still working on it. I didn't update the errors. My apologies, but the errors go in order from start-up to someone joining:

STARTUP
[ERROR] gamemodes/darkrp/gamemode/modules/chat/sh_chatcommands.lua:44: attempt to index a nil value
1. unknown - gamemodes/darkrp/gamemode/modules/chat/sh_chatcommands.lua:44
2. finish - gamemodes/darkrp/gamemode/libraries/interfaceloader.lua:163
3. unknown - gamemodes/darkrp/gamemode/init.lua:84

Couldn't Load Init Script: 'darkrp/gamemode/init.lua'

SOMEONE JOINED
[ERROR] gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:298: no such table: FAdmin_PlayerGroup (SELECT groupname FROM FAdmin_PlayerGroup WHERE steamid = 'STEAM_0:0:000000000';)
1. error - [C]:-1
2. queryValue - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:298
3. fn - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:382

SOMEONE PRESSING F4/F3
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241: attempt to index local 'jobTable' (a nil value)

        1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:234: attempt to index local 'jobTable' (a nil value)

        1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:234

**Comment by Bo98** [comment]
That definitely is fixed in the latest update. The update that fixed that was released today:

https://github.com/FPtje/DarkRP/pull/2453

**Comment by Vizikk** [comment]
Okay, that might be why I didn't get it. I slept late. I will download it and see if the problem continues. Thanks.

**Comment by Vizikk** [comment]
Nope it worked. Thank you :)
