### ISSUE TITLE
Recent chatCommandAlias addition erroring on startup

### ISSUE THREAD

**Issue by MStruntze** [FPtje/DarkRP#2455]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Updating one of my servers to the newest version of darkrp. Upon start this error is introduced:
```
[ERROR] gamemodes/darkrp/gamemode/modules/chat/sh_chatcommands.lua:48: attempt to index a nil value
  1. unknown - gamemodes/darkrp/gamemode/modules/chat/sh_chatcommands.lua:48
   2. finish - gamemodes/darkrp/gamemode/libraries/interfaceloader.lua:163
    3. unknown - gamemodes/darkrp/gamemode/init.lua:84
```
Adding the following code to the DarkRP.chatCommandAlias function:
```
function DarkRP.chatCommandAlias(command, ...)
	print('COMMAND ALIAS! - '..command)
    local name
    for k, v in pairs{...} do
        name = string.lower(v)
        print('Name for command: '..name)
        if not DarkRP.chatCommands[command] then
        	print('Command not registered yet.')
        end
        DarkRP.chatCommands[name] = table.Copy(DarkRP.chatCommands[command])
        DarkRP.chatCommands[name].command = name
    end
end
```
Prints this on startup:
```
COMMAND ALIAS! - unownalldoors
Name for command: sellalldoors
Command not registered yet.
```
Followed by the error posted above.
I started up a vanilla darkrp server to make sure, but didn't get the issue there. Looking through the entire console, no error is present before this one.
### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
-

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
included in description

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Occured after an update.

**Comment by Bo98** [comment]
This was fixed about 45 minutes ago.

**Comment by MStruntze** [comment]
Yep, that seems to do it. Thanks.
