### ISSUE TITLE
F4 not spawning entity

### ISSUE THREAD

**Issue by EmekArts** [FPtje/DarkRP#2456]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
i added an addon that i need to buy the entity in the f4 menu and its taking my money but not giving me the entity, is that any problem that you can fix?

i have and example for 1 of my entites.lua file

DarkRP.createEntity("Muriatic Acid", {
	ent = "eml_macid",
	model = "models/props_junk/garbage_plasticbottle001a.mdl",
	price = 400,
	max = 2,
	cmd = "buymacid",
	allowed = {TEAM_COOK},
})

thx for helping!

**Comment by FPtje** [comment]
Did you miss the fucking part when posting the issue that said "GITHUB ISSUES ARE **NOT** FOR HELP"

**Comment by EmekArts** [comment]
wow don't kill me i didn't saw it.
