### ISSUE TITLE
Foreign key constraint created on every database initialization

### ISSUE THREAD

**Issue by xxx0365** [FPtje/DarkRP#2460]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
A foreign key constraint will be created every time DarkRP.initDatabase() is called.

http://i.imgur.com/nK4ZMAo.png

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Call DarkRP.initDatabase()

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Happens with a clean newly download DarkRP and darkrpmodification (other than putting in the connection information of course) and no other addons

**Comment by FPtje** [comment]
holy shit that's fucking dumb.
