### ISSUE TITLE
DarkRP jobTable error

### ISSUE THREAD

**Issue by Scream145** [FPtje/DarkRP#2461]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
Uh.... cheese?

### How to make the bug happen
Get latest master DarkRP, load single-player, press F1/F3/F4.

### Lua errors
[*][ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:313: attempt to concatenate a nil value
[*]  1. createPlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:313
[*]   2. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:407
[*]    3. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:292
[*]     4. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:302
[*]      5. offlinePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:258
[*]       6. retrievePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:303
[*]        7. restorePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:390
[*]         8. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:587
[*]

[*]

[*][ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:606: attempt to index local 'jobTable' (a nil value)
[*]  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:606
[*]

[*]

[*][ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:713: attempt to index local 'jobTable' (a nil value)
[*]  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:713
[*]

[*]

[*][ERROR] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
[*]  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
[*]   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62
[*]

[*]

[*][ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241: attempt to index local 'jobTable' (a nil value)
[*]  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241
[*]

[*][ERROR] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:6: attempt to index local 'jobTable' (a nil value)
[*]  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:6
[*]   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62
[*]

[*]

[*][ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:234: attempt to index local 'jobTable' (a nil value)
[*]  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:234

### ADITIONAL INFORMATION:
1. A complete re-install of garry's mod has not fixed the problem either.
2. This is a brand new darkrp-master download, https://github.com/FPtje/DarkRP
3. The core file's have not been TOUCHED in any way / shape / form. I'm not that retarded.
4. The darkrpmodification-master has not been touched, this is just the DarkRP gamemode by itself.
5. There's no addon's currently enabled at the time of writing this message.

### Why the developer of DarkRP is responsible for this issue
More cheese.

**Comment by FPtje** [comment]
corrupt database.

**Comment by Bo98** [comment]
Looks more like an attempt to load the gamemode in singleplayer, which will produce errors as Player:SteamID64() returns no value serverside in singleplayer.
