### ISSUE TITLE
Random Lua Error from FPP

### ISSUE THREAD

**Issue by aStrandedBanana** [FPtje/DarkRP#2462]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

An error is being spammed in console that makes it literally impossible to play. I have tried reinstalling the darkrp gamemode again, and it is the latest version of DarkRP.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

It happens on startup

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/client/hud.lua:158: attempt to call field 'getPrivateSetting' (a nil value)
  1. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/client/hud.lua:158
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

FPtje has created the FPP module, which is what is creating the error.

**Comment by FPtje** [comment]
Cannot reproduce. Earlier errors must exist.  That or an addon is explicitly fucking your shit up. That addon could be an older version of FPP in your addons folder.
