### ISSUE TITLE
GM.Config.DarkRPSkin no longer works.

### ISSUE THREAD

**Issue by ruben-16** [FPtje/DarkRP#2464]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The following config option does not work correctly:
GM.Config.DarkRPSkin
It doesn't change the skin when set to default, if the word being default for the default derma theme was changed, then I'm unaware. If not changed, it's the whole option.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
There is no particular way to make this happen, the option simply doesn't work.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
There are no errors.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I went out of my way to completely overwrite all of my files in my modules folder of the gamemode to see if maybe I had done something for whatever reason, and there was still no change in output. I still have no idea why this is no longer working.

**Comment by FPtje** [comment]
I can set it to "default" and it works just fine.

**Comment by ruben-16** [comment]
Then my shits fucked, any evidence that can prove so?

**Comment by ruben-16** [comment]
I've reinstalled the latest version of DarkRP and the f4 menu and etc still doesn't change it's theme.
It looks nothing like [this](http://gyazo.com/8827a73bafa697f206744bc594801a39.png?1355633897).
Have you dropped support for this being possible with the f4 menu?

**Comment by FPtje** [comment]
Did you install motherfucking 2.4.3? What the fuck do you think you're doing?

**Comment by ruben-16** [comment]
> I've reinstalled the latest version of DarkRP
I'm trying to fucking use the default derma, is it no longer possible to achieve that look?

**Comment by FPtje** [comment]
That's not the latest motherfucking version of DarkRP you incompetent out of date back from the past time traveling PIECE OF SHIT

**Comment by ruben-16** [comment]
NO FUCK, but I thought it might still work

**Comment by FPtje** [comment]
You're wasting my god damn time.

**Comment by ruben-16** [comment]
Sorry, just asking a question and you're sperging out

**Comment by Shigbeard** [comment]
Wait, falco, why are you... oh... i see.

Ruben, let 2.4.3 die. Like seriously, take some of the bleach that people keep telling you to drink and pour it over the hard drive containing the files for 2.4.3
