### ISSUE TITLE
Error Console 

### ISSUE THREAD

**Issue by zamix13** [FPtje/DarkRP#2467]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

![20160604185147_1](https://cloud.githubusercontent.com/assets/18329164/15800866/cac9149c-2a85-11e6-9017-f8c7ff800f60.jpg)

**Comment by AMD-NICK** [comment]
facepalm
![image](https://cloud.githubusercontent.com/assets/9200174/15800968/1cb83062-2a90-11e6-8af5-6d395c3cdfb5.png)

**Comment by FPtje** [comment]
French people generally don't speak English. Maybe I should add language specific hints to DarkRP errors?

**Comment by AMD-NICK** [comment]
Then you should do this for all languages)

**Comment by AMD-NICK** [comment]
I can help with russian

**Comment by FPtje** [comment]
No, French fucks in particular. Those incompetent cunts are the worst English speakers in all of fucking Europe: http://www.ef.nl/epi/

Also I'm joking.

**Comment by FPtje** [comment]
French monolinguists don't deserve pandering. They are to learn English. They should not get the idea that their bullshit baguette filled frou frou je m'appelle ta guelle merde language is acceptable in the online community in any god damn way.

**Comment by Shigbeard** [comment]
Call me late to the party, but a lack of understanding of english is no excuse at this. You've made a gamemode that is written with english speaking users in mind provide detailed errors in english. It is the end-user's responsibility to either learn english or find someone who already knows it.

hon hon hon hon mon dieu

**Comment by roboderpy** [comment]
Ahahah. Falco, sometimes you are so funny, from my point of view.
05 Июн 2016 г. 0:19 пользователь "Falco Peijnenburg" <
notifications@github.com> написал:
