### ISSUE TITLE
VCMod

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2469]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
VCMod's passengers don't get kicked out, when the vehicle is battering ramed.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Use a battering ram on a vehicle with more then 2 passengers with VCMod (cur version) installed.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Compatibility with VCMod.

**Comment by MStruntze** [comment]
Use this hook:
http://wiki.darkrp.com/index.php/Hooks/Server/onDoorRamUsed
