### ISSUE TITLE
DarkRP not letting data save

### ISSUE THREAD

**Issue by TomTheDuck** [FPtje/DarkRP#2470]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

When restarting the server, darkrp seems to not save the ULX Groups. I have tested ULX without DarkRP and it was fine. When loading into DarkRP, the issue occurs. For that reason, I have brought the issue to DarkRP. I have tried a fresh install, but it did not help.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Unsure

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

As this error only occurs while running darkrp and not when running sandbox, and for that reason, I have brought the problem to DarkRP

**Comment by FPtje** [comment]
DarkRP doesn't do the saving for ULX. ULX does the saving for ULX.

**Comment by TomTheDuck** [comment]
Yes, while you are correct, it saved fine while in sandbox, but not with darkrp

**Comment by FPtje** [comment]
That does not definitively prove that I'm at fault. I've seen that argument countless times and every time it turned out to be something else. You should come up with some better proof that it's me specifically breaking ULX' saving things in text files and/or loading them.

**Comment by FPtje** [comment]
Or SQL, I don't know if they've changed that yet.
