### ISSUE TITLE
weapon_cs_base2 breaks CalcView

### ISSUE THREAD

**Issue by roboderpy** [FPtje/DarkRP#2471]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

As titile says, any stick on stick base fucks up calc view.
Any addon that uses CalcView will be fucked up when owner holding stunstick.
For example DHUD2.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Call GAMEMODE:CalcView when holding any stick, you would receive table without angle, origin and fov

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

Any addon related issues.
For example, DHUD2 errors there:
https://github.com/roboderpy/dhud2/blob/master/lua/dhud/cl_view.lua#L89
because newData.angles is nil

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

DarkRP related bug

**Comment by FPtje** [comment]
```
] lua_run_cl show(GAMEMODE.CalcView)
function: 0x45bd66b0	-- [gamemodes/base/gamemode/cl_init.lua]: 347-387
```

Don't complain to me about behaviour of standard gmod functions

**Comment by Bo98** [comment]
Is there a reason why weapon_cs_base2 has an empty SWEP:CalcView if it just breaks everything by returning nothing?

**Comment by roboderpy** [comment]
![2016-06-11_05-31_garry s mod](https://cloud.githubusercontent.com/assets/6339511/15980320/ea12558e-2f94-11e6-894c-d6fd63ceeccd.jpg)
![2016-06-11_05-31_garry s mod 2](https://cloud.githubusercontent.com/assets/6339511/15980321/ea182c2a-2f94-11e6-835b-448b156bc7aa.jpg)
Need something else?

**Comment by Bo98** [comment]
No idea what's happening for you in your SWEP:CalcView snippet but that exact code breaks GAMEMODE:CalcView for me.

**Comment by roboderpy** [comment]
Fuckup swep test was outside of DarkRP, on Sandbox. Is it just only in DarkRP SWEP with empty CalcView function breaks anything?

**Comment by Bo98** [comment]
If you added the SWEP:CalcView line after initially running the script, you will need to strip the weapon first and give it to yourself again. SWEP autorefreshing is broken when the weapon is already equipped.

**Comment by roboderpy** [comment]
![20160611063456_1](https://cloud.githubusercontent.com/assets/6339511/15981314/cef054dc-2f9d-11e6-8ec0-0f17b588b0ed.jpg)
Oh yea

**Comment by FPtje** [comment]
My bad
