### ISSUE TITLE
OOC, ADVERT, & ALL OTHER COMMANDS ARE GONE.

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/DarkRP#2472]
So i have a huge problem, the ooc, advert, & all other commands wont work either.
fadmin is still on the server & enabled
ulx is still on the server & enabled.

some ranks 'vip+' can remove doors and pick up players (since ftp doesnt allow them.. ) 

i have no hope anymore. pls give advise.

**Comment by BillyVenner** [comment]
http://forum.darkrp.com/

**Comment by Shigbeard** [comment]
You haven't used the template. You haven't provided us with any errors or steps to reproduce. All you've said is "X is broken, pls tell me how to fix it". Worse still, you have a rank called "vip+" which can target doors.

What this tells me is that you have difficulty reading and understanding instructions, you do not understand basic troubleshooting, your server is maintained and set up by a complete idiot (all offense intended) and your server is a cancerous whitewash of donator features.

This is a job for the forums, not for github.

/issue

**Comment by NLGBrian** [comment]
there are no errors. >.< you fucking dickhead :dancer:

**Comment by FPtje** [comment]
You should have read the issue template saying this is not a god damn help forum.

Take your illiteracy to the god damn DarkRP forums.

**Comment by Shigbeard** [comment]
Who the actual fuck are you calling a dickhead you fucking ignorant baboon. You didn't read shit, you didn't provide errors, you didn't even tell us there were no errors and worst of all you choose to take the fucking high road? Get the fuck out of my sight you god damn idiot.

Falco how do you even deal with these guys?

**Comment by FPtje** [comment]
It's not like I'm using some secret method, mate. My comments are right the there man.

**Comment by Shigbeard** [comment]
No I mean how do you stay sane? My secret is illicit substances.

**Comment by FPtje** [comment]
Something something writing songs n shit.
