### ISSUE TITLE
Arresting

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2473]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Suggestion:
Strip ammo when arresting a player, not just weapons

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
-

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
-

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
-

**Comment by FPtje** [comment]
Diy

**Comment by mcNuggets1** [comment]
Why would you keep ammo?

**Comment by BillyVenner** [comment]
DarkRP is not about realism

DarkRP is supposed to be about fun - meaning you should still have ammo

DIY

**Comment by thegrb93** [comment]
Getting arrested means you lose all of your valuables. That's a gameplay mechanic of DarkRP and ammo shouldn't be an exception.

**Comment by mcNuggets1** [comment]
I agree.
