### ISSUE TITLE
Error Lua

### ISSUE THREAD

**Issue by AntoineAngel** [FPtje/DarkRP#2474]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
?????

### How to make the bug happen
?????

### Lua errors

L 06/10/2016 - 20:25:53: Lua Error: 
[ERROR] gamemodes/darkrp/gamemode/modules/police/sv_init.lua:144: bad argument #1 to 'concat' (table expected, got string)
  1. concat - [C]:-1
   2. callback - gamemodes/darkrp/gamemode/modules/police/sv_init.lua:144
    3. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
     4. unknown - addons/ghostmode/lua/autorun/server/sv_ghostmode.lua:736
      5. unknown - lua/includes/modules/concommand.lua:54

### Why the developer of DarkRP is responsible for this issue
??????

**Comment by robinkooli** [comment]
Hmm

**Comment by FPtje** [comment]
caused by the ghostmode addon.
