### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by lord17** [FPtje/DarkRP#2475]
Hi, i have this error that sam my console of my server every time...

[ERROR] gamemodes/base/entities/entities/base_ai/schedules.lua:139: attempt to call method 'Run' (a nil value)
1. RunTask - gamemodes/base/entities/entities/base_ai/schedules.lua:139
2. DoSchedule - gamemodes/base/entities/entities/base_ai/schedules.lua:66
3. unknown - gamemodes/base/entities/entities/base_ai/schedules.lua:21

I tried to update darkrp file but same :/
Thanks!

**Comment by FPtje** [comment]
Not a help forum
