### ISSUE TITLE
Lua errors on fresh DarkRP Install

### ISSUE THREAD

**Issue by DootLord** [FPtje/DarkRP#2477]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
On starting a fresh install of DarkRP (gamemode + addon) I get several errors to do with "jobTables". I have not changed anything inside either folder and as such the game should work without changes by the user.

The bug appears to stop the player from moving around and loads them in with a hl1 gordon silhouette model. The player cannot access the F4 menu or utilize any aspect of the DarkRP gamemode. The DarkRP hud appears to work however.  

Errors do not clearly point to a single addon causing this, so I assume that this may to do with the default DarkRP setup.

An unusual aspect to this is that the player appears to be be spawned at the cords "0.000000 0.000000 64.000000" after loading into a map.

None of the issues occur on other game modes. (Tested on sandbox and TTT)

### How to make the bug happen
Drag the DarkRP gamemode and addons files in their appropriate directories. Start up a map and observe the lack of functionality and errors in console.

### Lua errors
On starting a new map:
http://i.imgur.com/JvKlt4S.png

On trying to access the F4 menu:
http://i.imgur.com/KTyB4EN.png

### Why the developer of DarkRP is responsible for this issue
I feel that this error has nothing to do with any changes made to my system or addons, due to the errors not giving any evidence to suggest it and that it may be due to a recent change of the gamemode.

If this is not the case, then I apologise for wasting your time.

**Comment by Bo98** [comment]
Are you trying this in singleplayer or a listen server?

**Comment by DootLord** [comment]
I'm trying to use this for Singleplayer. I've also tried the Github version and the Workshop version with the same results.

**Comment by Bo98** [comment]
DarkRP does not work in singleplayer. If you want to test locally, set it to at least "2 players" at the map choice menu.

**Comment by DootLord** [comment]
I was not aware of this. Thank you for your time.

**Comment by Bo98** [comment]
You're certainly not the first to come with this error. Perhaps the error should be suppressed or a clearer message be given as it seems quite a few people are loading up DarkRP in singleplayer.

**Comment by FPtje** [comment]
Why tell people not to play SP if you can fix the error?

BIIIIDDLY BIDLY BIDDLY BONG

**Comment by Bo98** [comment]
It was mentioned before without a fix so I assumed that it was unsupported.
