### ISSUE TITLE
Advert

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2482]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Could you please revert the changes made to the advert command?
Or atleast at a configoption for using the old version of the advert command.
It actually was ultra useful, to have the advert command to advert something to the server in rp.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
-

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
-

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
-

**Comment by Shigbeard** [comment]
Kill yourself and your github account please.

**Comment by mcNuggets1** [comment]
@Shigbeard My keyboard was freaking out, no reason to be rude.

**Comment by Shigbeard** [comment]
Well we all get emails when you create the issue. I literally see some random issue that isnt even filled in at all. My bad.

Even so, its not hard to revert to a previous commit. I hope it doesn't get undone though.

**Comment by mcNuggets1** [comment]
@Shigbeard 
I don't ask for it being undone, I ask for an alternative.
There is no modern way, to advert something to the whole server now.

I don't like to use an outdated version of DarkRP either.
Neither I am happy to override DarkRP's stuff, AGAIN.

**Comment by FPtje** [comment]
Config options are NOT for undoing developer decisions. Read further:
https://facepunch.com/showthread.php?t=1450721&p=47561840&viewfull=1#post47561840

The billboards are more natural to roleplay than a message in chat. The chat advertisements weren't being used for advertising anymore, they were only being used to log people's actions. I do not want to be associated with such abuse of a chat command. You can make your own "mug/raid/fuck log by chat command" addon. I don't want that shit to be in DarkRP by default.

**Comment by Shigbeard** [comment]
Be creative. Pretend OOC is advert and have people ((type in this way)) 
to signify ooc.

**Comment by magnus505** [comment]
fucking  you @FPtje

**Comment by kiruthekiller** [comment]
"How to make people want to kill you" - F. Peijnenburg

**Comment by magnus505** [comment]
http://theelectricdonkeys.info/darkrp.rar Download the one without the darkrp fucked.
