### ISSUE TITLE
YOU BROKE UR OWN FUCKING GAMEMODE! 

### ISSUE THREAD

**Issue by magnus505** [FPtje/DarkRP#2484]
Hey I have been playing on DarkRP for like 3 years now and now when u make they put a board out NOBODY WANT THAT CHANGE IT BACK!

**Comment by roboderpy** [comment]
Please shut up

**Comment by magnus505** [comment]
@roboderpy  you shut the fuck up

**Comment by magnus505** [comment]
@FPtje fix this fucking DARKRP Back or make that u can make it so it was as normal

**Comment by roboderpy** [comment]
https://github.com/FPtje/DarkRP/issues/2479 @Bo98 wrote:
```
It's supposed to spawn a billboard.
```

**Comment by FPtje** [comment]
Duplicate.
