### ISSUE TITLE
download old verison without the sign to spawn on  /advert

### ISSUE THREAD

**Issue by magnus505** [FPtje/DarkRP#2486]
Hello I find there the update didnt be maked and he can't report this on mega I'm hosting it on my own website. So now everybody can use without this dum fuck update.. 

http://theelectricdonkeys.info/darkrp.rar

//Owner of [teD]TheElectricDonkeys

**Comment by Bo98** [comment]
Can't wait for it to break in a future GMod update to leave you stranded.

**Comment by bedcorn** [comment]
Fucking DarkRP server owners that are half braindead when it comes to lua jesus christ it's so easy to remove
