### ISSUE TITLE
/advert?

### ISSUE THREAD

**Issue by cj2tech** [FPtje/DarkRP#2487]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
ok i know that that the new /advert system is suppose to spawn a billbored with text.
but considering its been used as a different system forever and community base their rules and game play around the old system why not keep the old system and make the new system a new commands? Like why not keep the old advert systen /advert and make the new one /billboard ? or make a option to put the old one back. I love the gm and the work you done is amazing, or even make a separate commands for actions like maybe /action based off the old system. i under stand you want to change the advert system back to advertisements. But to change a system completely and not make a way to use the old one is a little strange idea. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
update to the latest version of dark rp.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
n/a

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
No

**Comment by cj2tech** [comment]
may i ask why?

**Comment by cj2tech** [comment]
like not even a renaming of the old advert system.

**Comment by FPtje** [comment]
It would defeat the purpose of the change entirely. Moving it to a different command will have the same effect as reverting the change altogether, since people won't use it.

**Comment by cj2tech** [comment]
i think people would use both systems given the option to use it. i actually like the whole idea of a billboard system. just didnt see a reason to remove a system that work.

**Comment by cj2tech** [comment]
then maybe if you don't like that idea how about this one, restrictions to the new one. like the ablity to set how many billboards a person spawns and the ability to update their current billboard rather deleting and respawn... kinda like the law board system

**Comment by WilliamVenner** [comment]
YOU DO NOT TELL EVERYONE WHEN YOU COMMIT A CRIME

/advert was the most fucking stupid thing ever

Go away

**Comment by cj2tech** [comment]
whoa there friend no need for that, im not being rude to you, why are you being rude to me? And considering alot of people/servers use it in that way. and in some servers it works really well. But forcing all dark rp servers to be completely serious darkrp server, Instead if letting people make what they want to make of it. I'm all for change and actually like the new system just don't think that the old system should be just dropped completely.

**Comment by WilliamVenner** [comment]
I'm pretty sure lazy server owners who can't code a word of Lua shouldn't
get to have their own version of DarkRP catered for them.

Also, look at the closed issues.

On Wednesday, 22 June 2016, cj2tech <notifications@github.com> wrote:

> whoa there friend no need for that, im not being rude to you, why are you
> being rude to me? And considering alot of people/servers use it in that
> way. and in some servers it works really well. But forcing all dark rp
> servers to be completely serious darkrp server, Instead if letting people
> make what they want to make of it. I'm all for change and actually like the
> new system just don't think that the old system should be just dropped
> completely.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FPtje/DarkRP/issues/2487#issuecomment-227660855>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOLNf0adveQJSrNoEh2UA_TRgZSvQcj3ks5qON72gaJpZM4I7c17>
> .
>


-- 
William Venner
@ venner.io
@ procrastinator.io

**Comment by cj2tech** [comment]
so you say just because a percent of users cant make the game-mode them self means they can use it but don't even get the right to have a opinion? I guess i can understand why you feel that way. you never know i may be able to change his mind. And thanks for helping me see the little red box under my title.

**Comment by WilliamVenner** [comment]
your opinions shouldn't be expressed here because this is the GitHub
for development, not whining about the creator's descisions.

On Wednesday, 22 June 2016, cj2tech <notifications@github.com> wrote:

> so you say just because a percent of users cant make the game-mode them
> self means they can use it but don't even get the right to have a opinion?
> I guess i can understand why you feel that way. you never know i may be
> able to change his mind. And thanks for helping me see the little red box
> under my title.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FPtje/DarkRP/issues/2487#issuecomment-227662967>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOLNf8bVl6ajgSi5MWEDOClHB53M9bJWks5qOOHpgaJpZM4I7c17>
> .
>


-- 
William Venner
@ venner.io
@ procrastinator.io

**Comment by cj2tech** [comment]
i wasn't whining? how was that whining if that's what you took from my report im am sorry to confuse you it was merely a suggestion.

**Comment by Shigbeard** [comment]
I'm unsubscribing from this crap
