### ISSUE TITLE
FAdmin Got Corrupted.

### ISSUE THREAD

**Issue by SnappinBodhi** [FPtje/DarkRP#2490]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Fadmin ranks are all missing, when attempting to use the setroot command, it recognizes the console as Unknown. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
I messed around with ULX and all the fadmin ranks just disappeared

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None are outputted into the console.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because they made it.

**Comment by FPtje** [comment]
Unknown command you mean? Impossible unless either FAdmin was disabled or some Lua error is thrown.

**Comment by Hazbelll** [comment]
How exactly did you "mess around" with ULX? What did you do?

**Comment by Kefta** [comment]
If it happened after you messed around with an addon, then it's not the gamemode's fault.

**Comment by SnappinBodhi** [comment]
I was changing the custom ranks that I made, such as Owner, Co-Owner, and Superadmin, as well as changing the permissions in Admin and operator. Then after a server restart I couldn't do anything, I then had disabled the new scoreboard I put in and then I found that all of the FAdmin ranks were missing.

**Comment by SnappinBodhi** [comment]
Anything as in Edit door groups and set money.

**Comment by Hazbelll** [comment]
What changes did you make to the superadmin usergroup specifically? Just ULX permissions? You didn't rename it, delete it etc.?

**Comment by FPtje** [comment]
I don't think this is my fault.
