### ISSUE TITLE
Voice chat panel not displaying clientside, voice still being transmitted 

### ISSUE THREAD

**Issue by AfaaGames** [FPtje/DarkRP#2491]
### Description of the bug
[//]: I do not see the voice symbol "No-one can hear you" or "Everyone can hear you" when I made voice server-wide. So when other ppl voice chat, they may think their microphone isn't working.

### How to make the bug happen
[//]: Changing the /ooc, //, /a not to work + changing hear_noone to hear_everyone on cl_chatlisteners.lua
[//]: cl_chatlisteners.lua edits, even resetting the file back to its normal state does not show the voice panel, I messed with nothing else, just this and I only touched what I knew what to deal with.

### Lua errors
[//]: 0 Lua errors, voice functions fine, but the clientside left "something can hear you" does not show.

### Why the developer of DarkRP is responsible for this issue
[//]: They had no disableddefault.lua file function to make the text show "everyone hears you" only show when dynamic voice is disabled, 3d voice is disabled and sv_alltalk is 3, forcing me or someone else to tamper with the files that we shouldn't tamper with in an attempt to fix this problem, that or it confuses the heck out of any new player to the server.

**Comment by WilliamVenner** [comment]
I'm just curious - why do you have all talk on DarkRP anyway?

**Comment by AfaaGames** [comment]
Because some people prefer things differently. I need answers not questions.

**Comment by WilliamVenner** [comment]
I'm not the developer. This is a public repository, too. Am I not allowed to ask questions?

**Comment by AfaaGames** [comment]
It's an annoying and impolite thing to do to someone patiently  waiting for
a reply.

**Comment by WilliamVenner** [comment]
That's my problem is it? I just asked a question.

On Thursday, 23 June 2016, Ethorbit <notifications@github.com> wrote:

> It's an annoying and impolite thing to do to someone patiently waiting for
> a reply.
> On Jun 23, 2016 1:53 AM, "William Venner" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I'm not the developer. This is a public repository, too. Am I not allowed
> > to ask questions?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/FPtje/DarkRP/issues/2491#issuecomment-227988714>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ALW2HtNzkkMc2bLV9pYpByT05Gvdn-9eks5qOkl5gaJpZM4I8Zjf
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FPtje/DarkRP/issues/2491#issuecomment-227989013>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOLNf2Muy01HcHjdn73_jsGRkon7W9lWks5qOknLgaJpZM4I8Zjf>
> .
>


-- 
William Venner
@ venner.io
@ procrastinator.io

**Comment by FPtje** [comment]
When the entire server can hear you, it's useless to show "everyone can hear you". Instead, there should be a rotating speaker icon on the right.

Custom HUDs may fuck up and remove that rotating speaker icon (and have no replacement). I've seen that happen. It works for me, so if you don't see it, you have some bad HUD or something.

**Comment by FPtje** [comment]
When the entire server can hear you, it's useless to show "everyone can hear you". Instead, there should be a rotating speaker icon on the right.

Custom HUDs may fuck up and remove that rotating speaker icon (and have no replacement). I've seen that happen. It works for me, so if you don't see it, you have some bad HUD or something.
