### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Gamerpro2266** [FPtje/DarkRP#2493]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
when this lua happens you cant hit q and spawn anythink you got to rejoin the server for it to fix it self

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
open fpp and you got to have your tool gun out if you dont have your tool gun out it will cause the lua 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[DarkRP] gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:211: attempt to call global 'Label' (a userdata value)
  1. AdminMenu - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:211
   2. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:1120
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:110
     4. Call - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:224
      5. unknown - gamemodes/base/gamemode/cl_spawnmenu.lua:56
       6. unknown - lua/includes/modules/concommand.lua:54

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
they made the script so they will know how to fix it

**Comment by Bo98** [comment]
That error is caused by a bad addon.

**Comment by Gamerpro2266** [comment]
what addon could i be
