### ISSUE TITLE
Constant F4 Errors Make Me Want To Ingest Clorox

### ISSUE THREAD

**Issue by TomSStanley** [FPtje/DarkRP#2499]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (I Keep getting these errors saying that 'jobtable is a null value' or something like that everytime i try and use a custom f4 menu.)

### How to make the bug happen
[//]: # (Pressing f4)
[//]: # (That's what i'm here to find out)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Here's my lua error:

` [DarkRP] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62 `

This is where i got stuck, i look on these lines and theres litterally nothing there apart from 'end' on two lines.

`end`

Like litterally, that's line 23.

I've looked this issue up before and someone mentioned it being dodgy jobs,(Note, i haven't finished all of my jobs yet but these are the ones currently in) (job code below)

` TEAM_CIVILIAN = DarkRP.createJob("Civilian", {
   color = Color(30, 255, 0, 255),
   VIPonly = false,
   model = {"models/player/spike/bandy.mdl",
"models/player/spike/bjorngomes.mdl",
"models/player/spike/ciel.mdl",
"models/player/spike/crispycurds.mdl",
"models/player/spike/cry.mdl",
"models/player/spike/dauge.mdl",
"models/player/elder/elder.mdl",
"models/player/spike/epilotic.mdl",
"models/player/spike/its_ya_boi_dexyt.mdl",
"models/player/spike/gucci.mdl",
"models/player/johnny/johnny.mdl0",
"models/player/kanooki/kanooki.mdl",
"models/player/spike/letterv.mdl",
"models/player/spike/luciuskrein.mdl",
"models/player/mafiaschembo/mafiaschembo.mdl",
"models/player/spike/metropwn2.mdl",
"models/player/spike/mike.mdl",
"models/player/ness/ness.mdl",
"models/player/spike/noscopedjfk.mdl",
"models/player/spike/optagaming.mdl",
"models/snoopdogg.mdl",
"models/player/toddie/toddie.mdl",
"models/player/vin_diesel/slow.mdl",
"models/player/spike/wumbo.mdl"
},
   description = [[You're a civilian, you have no significant purpose in ropelay]],
   weapons = {},
   command = "civilian",
   max = 0,
   salary = 0,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civilian Jobs",
})

TEAM_GUNDEALER = DarkRP.createJob("Gun Dealer", {
   color = Color(255, 173, 0, 255),
   VIPonly = false,
   model = {"models/player/johnny/johnny.mdl"},
   description = [[- Can not self supply, only one gun for self defense.
- You must sell guns to the public, unless building a shop/store.
- Can not participate in raids​]],
   weapons = {},
   command = "gundealer",
   max = 1,
   salary = 120,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civilian Jobs",
})

TEAM_MEDIC = DarkRP.createJob("Medic", {
   color = Color(255, 255, 255, 255),
   model = {"models/bmscientistcits/p_male_09.mdl"},
   description = [[- You can be hired as a private medic for other players.
- You can only have a pistol as a weapon.​]],
   weapons = {"csgo_bayonet","med_kit"},
   command = "MEDIC",
   max = 2,
   salary = 120,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = true,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civilian Jobs",
})

TEAM_BANKER = DarkRP.createJob("Banker", {
   color = Color(0, 255, 168, 255),
   model = {"models/snoopdogg.mdl"},
   description = [[- Can build in bank
- Can not help bank robbers in raids on bank
- Only pistol for defense 
- Can not hire people to raid bank for them​]],
   weapons = {"csgo_bayonet"},
   command = "banker",
   max = 1,
   salary = 120,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civilian Jobs",
})

TEAM_BMD = DarkRP.createJob("Black Market Dealer", {
   color = Color(192, 0, 0, 255),
   model = {"models/humans/yuri.mdl","models/humans/soap.mdl"},
   description = [[- No self supplying except for giving 1 gun to your security and 1 gun for yourself, the one gun for yourself must be a pistol.
- No Mugging and Kidnaping and Carjacking
- [[No participating in raids]],
   weapons = {"csgo_bayonet"},
   command = "bmd",
   max = 2,
   salary = 300,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Civilian Jobs",
})

TEAM_HOMELESS = DarkRP.createJob("Homeless Man", {
   color = Color(123, 69, 0, 255),
   model = {"models/characters/fusemodel/fusemodel.mdl"},
   description = [[Homeless Man​
- Can beg for money
- Can build  shelters anywhere(Apart from on roads)​
-May Mug Only Using The Knife Given!]],
   weapons = {"csgo_gut_rustcoat"},
   command = "hobo",
   max = 0,
   salary = 0,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = true,
   cook = false,
   category = "Civilian Jobs",
})

TEAM_PRESIDENT = DarkRP.createJob("President", {
   color = Color(4, 0, 123, 255),
   model = {"models/player/dr_schwaiger.mdl"},
   description = [[- You may only have a pistol, for protection.
- You may be corrupt mayor, but not to the point that rulebreaking is sanctioned.
- You can not make random laws.]]
-- Can demote any government agent for not following orders]],
   weapons = {"m9k_luger","policebadgewallet"},
   command = "PRESIDENT",
   max = 1,
   salary = 3000,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = true,
   hobo = false,
   cook = false,
   category = "Government Jobs",
})

TEAM_SHERIFF = DarkRP.createJob("The Sheriff", {
   color = Color(0, 20, 255, 255),
   model = {"models/gta5/player/trooper.mdl"},
   description = [[- You may only use the guns given to you by default.
- You are the leader of the police officers, you may control them. If they do not respond to your commands, it can lead to demotion (Do not give random commands).
- Do not random search players and or bases.​]],
   weapons = {"fas2_ks23","policebadge","cw_deagle"},
   command = "sheriff",
   max = 1,
   salary = 3000,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = true,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Government Jobs",
})

TEAM_SecretService = DarkRP.createJob("Secret Service", {
   color = Color(255, 255, 255, 255),
   model = {"models/mfc_new.mdl"},
   description = [[-You Protect the highest rank of authority EG. Mayor/Dictator/President
-Can only use guns you've spawned with

-Cannot respond to normal calls, must be with the mayor at all times.]],
   weapons = {"policebadge","cw_extrema_ratio_official","cw_flash_grenade","fas2_p226","weapon_cuff_police",,"weapon_baton"},
   command = "secretservice",
   max = 4,
   salary = 1500,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Government Jobs",
})

TEAM_POLICEOFFICER = DarkRP.createJob("Police Officer", {
   color = Color(59, 98, 255, 255),
   model = {"models/taggart/police01/male_01.mdl","models/taggart/police01/male_02.mdl","models/taggart/police01/male_03.mdl","models/taggart/police01/male_04.mdl","models/taggart/police01/male_05.mdl","models/taggart/police01/male_06.mdl","models/taggart/police01/male_07.mdl","models/taggart/police01/male_08.mdl",models/taggart/police01/male_09.mdl"},
   description = [[- You must respond to calls and protect the people.
- You must follow orders of the Police Chief.
- Do not request for random warrants, unless you are stuck in a base.
- No random weapon checks, unless have a checkpoint set up.​]],
   weapons = {"fas2_glock20","m9k_mossberg590","arrest_stick","door_ram","weaponchecker","unarrest_stick","stunstick","weapon_baton","policebadge"},
   command = "policeofficer",
   max = 9,
   salary = 250,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Government Jobs",
})

TEAM_POLICESEARGANT = DarkRP.createJob("Police Seargant", {
   color = Color(59, 98, 255, 255),
   model = {"models/taggart/police01/male_01.mdl","models/taggart/police01/male_02.mdl","models/taggart/police01/male_03.mdl","models/taggart/police01/male_04.mdl","models/taggart/police01/male_05.mdl","models/taggart/police01/male_06.mdl","models/taggart/police01/male_07.mdl","models/taggart/police01/male_08.mdl",models/taggart/police01/male_09.mdl"},
   description = [[- You must respond to calls and protect the people.
- You must follow orders of the Police Chief.
- Do not request for random warrants, unless you are stuck in a base.
- No random weapon checks, unless have a checkpoint set up.​]],
   weapons = {"fas2_glock20","fas2_rem870","arrest_stick","door_ram","weaponchecker","unarrest_stick","stunstick","weapon_baton","policebadge"},
   command = "policeSEARGANT",
   max = 1,
   salary = 800,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Government Jobs",
}) `

Thankyou

-Tom

**Comment by FPtje** [comment]
You didn't read the bit that says that this is not  a help forum.
