### ISSUE TITLE
DarkRP Playerinfo on ents

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2507]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I want to disable the Playerinfo on entities.
There is no config option for it.
I would suggest to add one, because I already added playerinfo to entities with cam.3d2d texts.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
-

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
-

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
His mod.

**Comment by FPtje** [comment]
HUDShouldDraw

**Comment by mcNuggets1** [comment]
What exactly?

**Comment by FPtje** [comment]
DarkRP_EntityDisplay

**Comment by FPtje** [comment]
do you know where to find the DarkRP wiki?

**Comment by mcNuggets1** [comment]
Yes, I asked because the "Entity_Display" did actually never include entities, just players

**Comment by mcNuggets1** [comment]
When I disable "Entity_Display", then player info is not drawn anymore, but entitie infos are drawn.

**Comment by FPtje** [comment]
Ah and you call information drawn over entities "playerinfo"

**Comment by mcNuggets1** [comment]
http://puu.sh/pKm12/22db60c43d.jpg

**Comment by FPtje** [comment]
that's not DarkRP

**Comment by FPtje** [comment]
those are not DarkRP default printers

**Comment by mcNuggets1** [comment]
That happens with every entity.

**Comment by mcNuggets1** [comment]
Every entity which support the NWVar "owningent"

**Comment by FPtje** [comment]
I'm not doing it.

**Comment by mcNuggets1** [comment]
Was my limited knowledge about scripting. Sorry, guy.
