### ISSUE TITLE
Job problem 2.7

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#2510]
Hello,

I've installed the new DarkRP 2.7. And i've a problem now : 

07/01/2016 15:38:07: Lua Error 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:713: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:713
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:713: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:713

Can you help me please ?

**Comment by FPtje** [comment]
Not a help forum

**Comment by Sliverslider** [comment]
I'm having the same issue, so is there anything we can do to fix this?

**Comment by Bo98** [comment]
By not asking for help here but on the forum instead. The error is usually caused by an error in your config/jobs files. Look for the first error rather than this one as this error always follows a previous one.
