### ISSUE TITLE
CleanUp delete server entities

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#2514]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Since Darkrp 2.7 when you cleanup^with fadmin in TAB it delete server entities (cardealer, NPC...)

It doesn't make that with Darkrp 2.6.2

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Go TAB > Server Settings > CleanUP

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No error 

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Because it doesn't make it on Darkrp 2.6.2.

Thank you,

**Comment by Shigbeard** [comment]
Much better

**Comment by FPtje** [comment]
That's because the authors of these NPCs haven't made them resilient to `game.CleanUpMap`
