### ISSUE TITLE
DarkRP spawn points not saving.

### ISSUE THREAD

**Issue by gmanc2** [FPtje/DarkRP#2515]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
DarkRP spawn points don't save after restart

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No LUA errors except the spawn points never save to the sql database. 

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by WilliamVenner** [comment]
My Job Application

### Name
Billy

### Skills

### Previous Experience
I did the stuffs with LAUs

### Why are you joining our company?

**Comment by roboderpy** [comment]
What

**Comment by robinkooli** [comment]
the fuck

**Comment by WilliamVenner** [comment]
I hate you people, why should I have to explain jokes to you

**Comment by Shigbeard** [comment]
Maybe because your jokes are bad.

**Comment by WilliamVenner** [comment]
Maybe you're bad.

On Friday, 8 July 2016, Shigbeard <notifications@github.com> wrote:

> Maybe because your jokes are bad.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FPtje/DarkRP/issues/2515#issuecomment-231249979>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOLNf_dk3Nnj5GcWAnedgDSDj9U6nNiIks5qTaEjgaJpZM4JHlIC>
> .
>


-- 
William Venner
@ venner.io
@ procrastinator.io

**Comment by Shigbeard** [comment]
Says the 15 year old that posted an irrelevant "job application" into a legitimate bug report.

Fuck off. Also your website is shit and II like how you've listed jQuery as one of your abilities, because knowing jQuery is something to be proud of lol. #Sarcasm.

**Comment by FPtje** [comment]
Does save for me.

**Comment by WilliamVenner** [comment]
@Shigbeard, why are you suddenly so mad? I didn't think you were an angry person at all.

It was merely a joke, my apologies for commenting it. Thanks for your unnecessary insults from jokingly calling you "bad". I've removed jQuery from there as per your request.

I'm sorry my age offends you, too. Would you like me to cease use of the Internet or something? Apologies for being more successful than you ;v

**Comment by FPtje** [comment]
This issue and this github repo aren't places for you cunts to discuss why some website is shit. Fuck off.
