### ISSUE TITLE
Spawn Points Not Saving

### ISSUE THREAD

**Issue by FermentJoy** [FPtje/DarkRP#2516]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### I have 3 Dark  RP Servers. A WW1, A Star Wars and a Generic Dark RP. In all three spawns are not saving. They were working fine but when I upgraded to the new Dark RP, the 2.7 I believe, none of the spawns would save. They would be set, but after a reset or restart the server would lose all the spawn points.
[//]: # (Describe the issue as accurately as possible)

### The best I can say ithat broke the spawns was upgrading to the new Dark RP with the Dark RP Modification and that is about all we did. For all three servers. Now, the WW1 and Dark RP and Star Wars are hosted on different hosts. WW1 has its own host but Star Wars and Dark RP are combined onto one dedicated Server. 
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### No Lua Errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### The issue is not caused by an addon, or some external script. For one, all three servers have completely different addons. From the Workshop and the Custom Addons are all different. The only thing that all three servers have a combination of is the fact that they are all Dark RP and all the Same version of Dark RP. I tried deleting Dark RP putting a new one, still did not work. Thinking that the Dark RP could have been corrupted, but it was not. 
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Shigbeard** [comment]
Duplicate issue, which is a wide enough crack to have a go at you over your massive font and lack of template. See #2515

**Comment by WilliamVG** [comment]
@Shigbeard Okay, what. I have no idea what you are saying. Also, it is not a lack of Template I followed what it was asking. Sorry for Big Font you want me to rub your head so your pretty little brain can understand what you are reading. Or would it still be too hard for you?

**Comment by WilliamVG** [comment]
@FPTje Hey Retard here is another error. Happy? 
[ERROR] gamemodes/starwarsrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:260: attempt to index field 'user' (a nil value)
  1. DoClick - gamemodes/starwarsrp/gamemode/modules/fadmin/fadmin/access/cl_init.lua:260
   2. unknown - gamemodes/starwarsrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_controls.lua:301

**Comment by DrPooGas** [comment]
and the 2016 BALLS OF STEEL award goes to...

**Comment by FPtje** [comment]
Someone who modified core files. 
http://corefiles.darkrp.eu

No support is given to cunts who edit core files.

**Comment by FermentJoy** [comment]
@FTPje No Core files were edited literally was downloaded straight from GitHub and only the Config and TXT files were edited.

**Comment by FPtje** [comment]
That's still editing core files. No support.

**Comment by FermentJoy** [comment]
@FPtje Bro you are retarded. I edited the Config file in the Dark RP modification file. Setting something from True to false is not editing its CONFIGURING.

**Comment by FermentJoy** [comment]
@FPTje Based on what you are saying, editing the TXT and Config, if you do that you are a Cunt. Nice job you called out I don't know hundreds even thousands of servers.

**Comment by FPtje** [comment]
The error states you did more. Something about changing the gamemode's name to starwarsrp. The rule is very well specified: No support is given when it turns out you edited core files. By core files I mean any files in the DarkRP folder, including that text file.

**Comment by FermentJoy** [comment]
@Fptje It was not changed to Star Wars RP the game  when viewing game info still says DarkRP

**Comment by FermentJoy** [comment]
@FPTje And my Dark RP TXT file was never edited.

**Comment by FermentJoy** [comment]
@FPTje it was kept as base game mode. Still does not save on  a fresh new server with no addons still does not save.

**Comment by FPtje** [comment]
Even the my argument still holds: it works for me. Although I don't believe for a second that in this short amount of time you installed DarkRP on a clean server to test it. 

Also, I'm rigid with that rule, especially with people who rename the gamemode, because I've provided a way (see releases section) for you to do that suit without editing core files.

**Comment by FermentJoy** [comment]
I did not do it today. I tried it out about  a week ago. Plus I never edited the Dark RP files on my Dark RP server either. At all.

**Comment by FPtje** [comment]
Argument still holds.

**Comment by FermentJoy** [comment]
@FPTje Argument still holds.... Okay, so based on what you are saying cause it works for me should work for everyone. Hmm, guess what it does not work like that. It could be possible you done fucked up and could just be lying. Cause it is not only me that is reporting this.

**Comment by FPtje** [comment]
No, the argument is even simpler: I cannot fix bugs that I cannot
reproduce. When I (re)start my listen server, which I have a couple of
times yesterday, I spawn at the place I set with `/setspawn citizen`.

The burden of proof is upon you to prove that I'm responsible, because
you're the one making the claim. Also, this is typically the kind of
problem caused by some addon overriding PlayerSpawn. Historically people
have been shown to lie VERY often about the addons they have installed.

I can put hours of work reading code, trying to figure out what the fuck
could go wrong, but I absolutely refuse to do that with the huge
possibility that the fuck up is on your side.

**Comment by FermentJoy** [comment]
@Fptje Or you done fucked up and the Dark RP is fucked on your end and I have to waste hours trying to fix your mistake. So if you could actually look at it instead of say, "Can't reproduce closing thread" Maybe you wasting all your time arguing with me could have been better put to use to actually looking at the issue. Also if you could READ, all the addons are different in all THREE SERVERS. so your argument does not hold cause it is quite frankly and I say this with care, retarded.

**Comment by FermentJoy** [comment]
"The issue is not caused by an addon, or some external script. For one, all three servers have completely different addons. From the Workshop and the Custom Addons are all different. The only thing that all three servers have a combination of is the fact that they are all Dark RP and all the Same version of Dark RP."

**Comment by FPtje** [comment]
I'd like to see you defend the claim that DarkRP is so fucked up on my server that it actually works.

**Comment by FermentJoy** [comment]
@FPTje I did not say its so fucked up that it works, I said you fucked up some part of it that spawns are not working. Why is it working on your server, I have no fucking idea, it could be you never actually checked.

**Comment by FPtje** [comment]
Well for one I have no addons that return a value in PlayerSpawn, the most likely cause to your problem.

**Comment by FermentJoy** [comment]
@Fptje None of my addons have anything to do with Player Spawn. Like 0. The reason I know is cause I tested the server with no addons or anything and it still failed to set spawns.

**Comment by FPtje** [comment]
Hold on, failed to set spawns in the first place?

**Comment by FPtje** [comment]
![2016-07-09_08-28-48](https://cloud.githubusercontent.com/assets/1202014/16706486/2f2a8e36-45af-11e6-8b73-4b4a211cbf86.jpg)

Also, just to convince you that I tested it, I just started my listen server and spawned at the location I had set yesterday. I respawned myself and I still spawned inside the same shop. I have no problem that I can debug here.

**Comment by FermentJoy** [comment]
@FPtjje No, it set spawns, lets say I die I will spawn there. The moment I restart spawns are no longer there and we have to set the spawn process all over again. What dark RP version are you using?

**Comment by DrPooGas** [comment]
@FermentJoy i had a weird issue with this before. try /addspawn instead of /setspawn

**Comment by FermentJoy** [comment]
I tried add spawn still did not save.

**Comment by FPtje** [comment]
What DarkRP version am I using? Is this a fucking joke? I'm the developer of DarkRP. I always run the latest version.

**Comment by FermentJoy** [comment]
@FPTje You know Idk anymore cause you have some pretty retarded answers.

**Comment by FPtje** [comment]
From your perspective they may be retarded, yes, but that wouldn't be because of me.

**Comment by FPtje** [comment]
Also, if they work until a restart, something might prevent them from loading. I haven't seen any serverside errors yet. Do you know how to look for serverside errors?

**Comment by FermentJoy** [comment]
@FPtje Then because of who, 3 separate completely different servers are not working with spawns. 2 Different hosts, different addons both server and workshop. Different maps, different everything and yes their aren't any serverside errors. No Errors at all.

**Comment by FPtje** [comment]
Let me test using MySQL

**Comment by FPtje** [comment]
Looks like @DrPooGas was right with /addspawn. It seems that there is a specific bug with /setspawn and MySQL.

**Comment by FermentJoy** [comment]
@Fptje Just to confirm, will be restarting to make sure that addspawn does not work.

**Comment by FermentJoy** [comment]
@FPtje Well It did not work.

**Comment by FPtje** [comment]
Addspawn does work with MySQL for me.

**Comment by FPtje** [comment]
Right, here's the deal:

There was a bug in the [MySQLite](https://github.com/FPtje/MySQLite) library that caused a very specific thing issue that would **only** happen when the server is using MySQL. The /setspawn command happened to trigger that bug, causing it to remove all spawn positions, but not create the new one. 

It worked for me because I work with DarkRP on the default settings, which uses SQLite, not MySQL.

**Comment by FPtje** [comment]
Try the latest version.

**Comment by FermentJoy** [comment]
@Fptje Thank you, it seems we were both in the wrong. I appreciate the fix.

**Comment by anyome** [comment]
DUDE SAME PROBLEM...
