### ISSUE TITLE
SQL database not working

### ISSUE THREAD

**Issue by gmanc2** [FPtje/DarkRP#2517]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Won't save to database

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Its constant

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

L 07/09/2016 - 17:07:10: Lua Error: 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:241
 
 
 [ERROR] addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:980: table index is nil
  1. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:980
   2. doInclude - [C]:-1
    3. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:137
     4. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:148
      5. unknown - gamemodes/darkrp/gamemode/cl_init.lua:53

 [DarkRP] gamemodes/darkrp/gamemode/libraries/fn.lua:252: attempt to index local 'xs' (a nil value)
  1. isMayor - gamemodes/darkrp/gamemode/libraries/fn.lua:252
   2. Init - addons/ariviaf4menu/lua/arivia/cl/cl_tab_commands.lua:27
    3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
     4. UpdateCommands - addons/ariviaf4menu/lua/arivia/cl/cl_init.lua:773
      5. Init - addons/ariviaf4menu/lua/arivia/cl/cl_init.lua:434
       6. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
        7. openF4Menu - addons/ariviaf4menu/lua/arivia/cl/cl_init.lua:1109
         8. Call - addons/ariviaf4menu/lua/arivia/cl/cl_init.lua:1131
          9. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

 
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:382: attempt to index global 'MySQLite' (a nil value)
  1. fn - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:382
   2. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:110

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Last night a commit was made and I updated and now sql simply doesnt work... it worked before now it doesn't...

**Comment by gmanc2** [comment]
![b95808fd65e698d8735a1431539bbec5 1](https://cloud.githubusercontent.com/assets/4944080/16710356/4bddacc6-45f9-11e6-8c62-99fbeccf1c96.png)
![ef00993f3f35e009e27da722d831bc88 1](https://cloud.githubusercontent.com/assets/4944080/16710361/5dc09368-45f9-11e6-8720-dfb6a0f403fd.png)

As you can see all of the assests are in place for sql and

`RP_MySQLConfig = {} -- Ignore this line
--[[
Welcome to MySQL for DarkRP!
In this file you can find a manual for MySQL configuration and the MySQL config settings.
 ]]


RP_MySQLConfig.EnableMySQL = true -- Set to true if you want to use an external MySQL database, false if you want to use the built in SQLite database (garrysmod/sv.db) of Garry's mod.
RP_MySQLConfig.Host = "ip" -- This is the IP address of the MySQL host. Make sure the IP address is correct and in quotation marks (" ")
RP_MySQLConfig.Username = "obn" -- This is the username to log in on the MySQL server.
								-- contact the owner of the server about the username and password. Make sure it's in quotation marks! (" ")
RP_MySQLConfig.Password = "password" -- This is the Password to log in on the MySQL server,
									-- Everyone who has access to FTP on the server can read this password.
									-- Make sure you know who to trust. Make sure it's in quotation marks (" ")
RP_MySQLConfig.Database_name = "obn_ww" -- This is the name of the Database on the MySQL server. Contact the MySQL server host to find out what this is
RP_MySQLConfig.Database_port = 3306 -- This is the port of the MySQL server. Again, contact the MySQL server host if you don't know this.
RP_MySQLConfig.Preferred_module = "tmysql4" -- Preferred module, case sensitive, must be either "mysqloo" or "tmysql4". Only applies when both are installed.
RP_MySQLConfig.MultiStatements = false -- Only available in tmysql4: allow multiple SQL statements per query. Has no effect if no scripts use it.


--[[
MANUAL!
HOW TO USE MySQL FOR DARKRP!
Download andyvincent's/Drakehawke's/KingofBeast's gm_MySQL OO module and read the guide here:
http://facepunch.com/showthread.php?t=1357773


WHAT TO DO IF YOU CAN'T GET IT TO WORK!
	- There are always errors on the server, try if you can see those (with HLDS/server logs)
	- the same errors are also in the logs if you can't find the errors on the server.
		the logs are at garrysmod/data/DarkRP_logs/ on the SERVER!
		The MySQL lines in the log always precede with "MySQL Error:" (without the quotation marks)
	- make sure the settings in this file (mysql.lua) are correct
	- make sure the MySQL server is accessible from the servers IP
]]
 `

**Comment by Shigbeard** [comment]
Have you double checked to make sure you've correctly uploaded DarkRP to 
your server? If you are using Filezilla, you will likely find that some 
files were not uploaded or are corrupted.

Try using https://winscp.net/eng/docs/free_ftp_client_for_windows for an 
alternative FTP Client to Filezilla.

**Comment by gmanc2** [comment]
@Shigbeard All files were uploaded...

**Comment by Bo98** [comment]
Could you post the _first_ error you see? jobTable errors are usually caused by earlier errors.

**Comment by gmanc2** [comment]
```

[ERROR] addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:980: table index is nil
  1. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:980
   2. doInclude - [C]:-1
    3. loadCustomDarkRPItems - gamemodes/ww1/gamemode/libraries/modificationloader.lua:137
     4. Call - gamemodes/ww1/gamemode/libraries/modificationloader.lua:148
      5. unknown - gamemodes/ww1/gamemode/cl_init.lua:53
 
```

**Comment by Bo98** [comment]
Ah that is an error in your jobs file. Around line 980. It probably is that one of your teams listed under GAMEMODE.CivilProtection does not exist.

**Comment by gmanc2** [comment]
@Bo98  The last on my jobs file is 680

**Comment by gmanc2** [comment]
I also get this
```

SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
SQL Error: 
[PlayerSelectSpawn] Error! No spawn points!
```

**Comment by gmanc2** [comment]
Why did you close this @FPtje

**Comment by FPtje** [comment]
Not a help forum

**Comment by gmanc2** [comment]
But it's obviously and error with the update you just made as I've never had this error in the past @FPtje

**Comment by FPtje** [comment]
To me it obviously isn't because MySQL works fine for me. Everything loads, everything works just fine.

**Comment by thomas-pns** [comment]
Hello, @FPtje for me the SQL database is not working, I have the same error as @ gmanc2, I installed a libmysqlclient.so at the root of me ServerFiles and I will install in garrysmod / lua / bin ( I create the bin directory) gmsv_mysqloo_linux64.dll, do you have an answer to this problem?
![image](https://user-images.githubusercontent.com/48253434/103236071-14c52400-4944-11eb-9fd2-4b4a139c81ab.png)
![image](https://user-images.githubusercontent.com/48253434/103236099-2ad2e480-4944-11eb-83b2-2ab62bee1ceb.png)
![image](https://user-images.githubusercontent.com/48253434/103236121-39b99700-4944-11eb-9456-106a25df5a66.png)

**Comment by FPtje** [comment]
MySQLite itself should load with DarkRP, even when MySQL itself isn't installed or doesn't work. There must be an earlier error than the one in your last screenshot that would prevent MySQLite from loading.

I have to ask, did you happen to use FileZilla to copy over the DarkRP folder to your server?

**Comment by thomas-pns** [comment]
I use MobaXterm of connect to my VPS ovh

**Comment by FPtje** [comment]
Guessing FileZilla was a longshot. I think DarkRP is not installed correctly, or some addon breaks it. You should see some earlier errors while the server is starting up or loading a map.

**Comment by thomas-pns** [comment]
I have deactivated all the addons and I still have the same error, sorry to disturb you
![image](https://user-images.githubusercontent.com/48253434/103238124-05e17000-494a-11eb-918d-c15174dfe6e6.png)

**Comment by FPtje** [comment]
That error is much clearer: it fails to load the MySQLOO module, which means it's either the wrong version or not installed properly.

- There are several versions of MySQLOO around, this should be the right version: https://github.com/FredyH/MySQLOO
- This person looks like they have the same issue, the suggestion is made to install the 32 bits version of the DLL alongside the 64 bits one, try that: https://github.com/FredyH/MySQLOO/issues/74#issuecomment-738470591

**Comment by thomas-pns** [comment]
thanks
