### ISSUE TITLE
Duplicate a weapon

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#2518]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

You can duplicate a weapon with /drop and /sleep binded...

Take your weapon in your hand, press the /drop bind key, and very fast your /sleep bind key. And if the timing is good you duplicate the weapon.

Text come from MPGH :

"Solo Duping, For this dupe you will need a server that allows you to use the sleep command, also to make this much easier you will need these binds l bind (Any Letter) "say /drop" and bind (Any Letter) "say /sleep" l Once you have those what you need to do is pull out the gun that you want to dupe and just like the tazer dupe you need to drop the gun and right before its about to actually drop instead of getting someone to taze you just hit the button for the sleep bind and if you nailed the timing there should be one in your inventory and one on the ground."

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

/drop and /sleep very faster.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No lua error because it's a glitch

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Because he create the /drop and /sleep commands.

**Comment by FPtje** [comment]
Thanks!
