### ISSUE TITLE
FAdmin does not register any groups that was registered with CAMI before FAdmin gets initialized

### ISSUE THREAD

**Issue by roboderpy** [FPtje/DarkRP#2524]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If there is another Admin mod (or some mod that registeres it's own admin group) that registers a new group using CAMI before FAdmin gets intialized, server is marked for death.
Privilege does not appear in FAdmin menu, errors on trying to register privilege to created group.
FAdmin will always return false on CAMI.PlayerHasAccess() on registered privilege.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Register group with CAMI before FAdmin is initialized, then register privilege for that group

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Any errors related to CAMI privileges register
Startup:
![2016-07-20_15-29_dbot test server](https://cloud.githubusercontent.com/assets/6339511/16980369/d64fb144-4e8f-11e6-9244-97b74b199ca2.jpg)
Live Registering:
![2016-07-20_15-38_dbot test server](https://cloud.githubusercontent.com/assets/6339511/16980393/eeacf260-4e8f-11e6-8ada-d7eaa371a32e.jpg)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
You created FAdmin and CAMI :P

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When CAMI Privilege gets registered (or on server startup), FAdmin's code throws error:
Startup:
![2016-07-20_15-29_dbot test server](https://cloud.githubusercontent.com/assets/6339511/16980369/d64fb144-4e8f-11e6-9244-97b74b199ca2.jpg)
Live Registering:
![2016-07-20_15-38_dbot test server](https://cloud.githubusercontent.com/assets/6339511/16980393/eeacf260-4e8f-11e6-8ada-d7eaa371a32e.jpg)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
https://github.com/roboderpy/dpp/blob/master/lua/dpp/sh_access.lua#L29

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Above

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
You created FAdmin and CAMI :P

Found that bug when was going to report issue into ULX repo - CAMI Privilegies not showing in the menu, but registering and working good. In prove that's not my fault i gone to FAdmin. :(

**Comment by roboderpy** [comment]
Cannot reproduce anymore. Abnormal?

**Comment by roboderpy** [comment]
I think this issue comes from this
https://github.com/roboderpy/dpp/blob/master/lua/dpp/sh_access.lua#L26
When CAMI can have ```operator``` group because ULX registered it, FAdmin does not have it.

**Comment by Shigbeard** [comment]
ironically, operator is the first rank touched by anyone installing ULX, 
and its usually to delete it.

**Comment by roboderpy** [comment]
Can be reproduced again.

**Comment by roboderpy** [comment]
Yes. Removing "operator" from access rights in DPP solves the issue.

**Comment by Bo98** [comment]
`MinAccess` in the table passed to `CAMI.RegisterPrivilege` only supports user, admin and superadmin. This is documented:

https://github.com/glua/CAMI/blob/master/sh_cami.lua#L30

**Comment by roboderpy** [comment]
But still, FAdmin just simply ignores already registered groups

**Comment by Bo98** [comment]
MinAccess won't work with custom groups _regardless_ if they are registered or not. FAdmin will give the errors you posted if you set MinAccess to "operator".

**Comment by roboderpy** [comment]
*feels like a f2p player* You are right

**Comment by Bo98** [comment]
> But if custom group exists

So are you saying that FAdmin groups aren't syncing properly with CAMI usergroups?

**Comment by roboderpy** [comment]
```roboderpy changed the title from FAdmin fail when trying to register CAMI Privilege to FAdmin does not register any groups that was registered with CAMI before FAdmin gets initialized```
Operator group exists in CAMI table, because ULX registered it. But in FAdmin it doesn't because FAdmin initalized after ULX is initalized

**Comment by Bo98** [comment]
Ah, missed the title change. That indeed would be an issue.

**Comment by roboderpy** [comment]
I lied, FAdmin fails to register ANY privilege that have MinAccess set to custom usergroup. :(
![2016-07-21_21-27_dbot test server](https://cloud.githubusercontent.com/assets/6339511/17026415/2c3cc06a-4f8a-11e6-9fae-3bcd2131dd0d.jpg)
![2016-07-21_21-29_dbot test server](https://cloud.githubusercontent.com/assets/6339511/17026418/2e19f43e-4f8a-11e6-814f-4578a9f5ff60.jpg)

**Comment by Bo98** [comment]
There isn't anything in the spec afaik that tells how admin mods behave when you pass invalid values. Based on where FAdmin errors, it seems to assume that the value passed is valid and us encounters issues further down the line. Perhaps things could be clarified more around that issue.

**Comment by Bo98** [comment]
The usergroups syncing issue you mentioned though shouldn't happen but is completely separate from CAMI.RegisterPrivilege.

**Comment by FPtje** [comment]
FAdmin now uses a fallback after trying to get the root usergroup.

**Comment by roboderpy** [comment]
How about registering CAMI groups that was registered before FAdmin initialized?

**Comment by FPtje** [comment]
access/sv_init:55

**Comment by roboderpy** [comment]
But why ULX have operator group when FAdmin doesn't? Will test again when get to home

**Comment by FPtje** [comment]
Know, I not do
