### ISSUE TITLE
Please help me with a dedicated server issue

### ISSUE THREAD

**Issue by Ashtrolite** [FPtje/DarkRP#2526]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (basically i made a new darkrp server and i am super admin i am not sure why but it seems that even being a admin i cant set a group for a door. meaning i cant make the pd only available for the pd it says i don't have the right privileges)

### How to make the bug happen
[//]: # (I am not sure how or why this happend)
[//]: # (i am running ulx and ive seen somethings that can mess up my game with ulx but i ever messed with any)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (i ask you to help me fix this issue because i really want to make my server pupblic but cant because of this issue)
[//]: # (I cant open my server if the admin lounge is available to everyone and the pd is free for the taking)

**Comment by gspetrou** [comment]
Good try 👍🏼
