### ISSUE TITLE
Deploy animations for weapons/batons

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2528]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I would suggest adding deploy animations to the weapons/batons by simple setting the deploy speed via SWEP/SetDeploySpeed() to 1.4.
This would balance the gamemode a little bit.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
-

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
-

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
-

**Comment by FPtje** [comment]
The concept of balance to me does not entail nerfing the one of the least used things in DarkRP nowadays.

**Comment by mcNuggets1** [comment]
Arrest and Unarrest Batons are used frequently.
Deploy animtions would balance the spam usage of the batons.

**Comment by FPtje** [comment]
What spam usage

**Comment by EstevanTH** [comment]
I guess it is about the spammed switch from/to arrest/unarrest.

**Comment by FPtje** [comment]
Why would that ever be a problem?
