### ISSUE TITLE
lua error with FPP

### ISSUE THREAD

**Issue by Gamerpro2266** [FPtje/DarkRP#2529]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
so when i use FPP and i dont have my tool gun out but before i can open FPP i got to use the tool by removing nothing then open it then click somethink like remover and it remover on the floor again

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
i dont have my tool gun out but before i can open FPP i got to use the tool by removing nothing then open it then click somethink like remover and it remover on the floor again

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:57: attempt to call global 'Label' (a userdata value)
  1. AdminMenu - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:57
   2. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:1120
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:109
     4. Call - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:224
      5. unknown - gamemodes/base/gamemode/cl_spawnmenu.lua:56
       6. unknown - lua/includes/modules/concommand.lua:54

[this one happens on startup
[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:521: attempt to index field 'Access' (a nil value)
  1. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:521
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
]

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
iam not sure of the issue i had it for a bit now and i dont know what to do so i would like to ask the main people on how to fix it because it would help me alot and maybe the devs as well

**Comment by roboderpy** [comment]
You have bad addon installed that's author don't even know about "local" statement.
