### ISSUE TITLE
I dont know what to do help me if this is a error and what i did wrong

### ISSUE THREAD

**Issue by Justpyro** [FPtje/DarkRP#2531]
function GM:ShowSpare2(ply)
    local jobTable = ply:getJobTable()
    if jobTable.ShowSpare2 then
        return jobTable.ShowSpare2(ply)
    end

**Comment by Shigbeard** [comment]
Not a help forum. forum.darkrp.com

Also if you have a legitimate bug to report, use the template instead of deleting it.
