### ISSUE TITLE
Wanted notices do not print to console

### ISSUE THREAD

**Issue by 0tt** [FPtje/DarkRP#2532]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When the notification for someone being wanted appears, no text is printed to the console.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Make someone wanted.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
This has been a longstanding issue with DarkRP for many years. Generally, the wanted announcements dissapear much to fast to read and it makes determining if the claim is legitimate very painful. Usually, text that appears on the screen also appears in the console, and so should wanted announcements as well.

**Comment by FPtje** [comment]
![hl2_2016-08-13_15-29-23](https://cloud.githubusercontent.com/assets/1202014/17643443/bdba461a-616a-11e6-95f1-40d8d35ac566.png)

https://github.com/FPtje/DarkRP/commit/924014d7#diff-c3c4b0e29ef7c9229e2e271dac0ca4f0R23

It was added in may 2013. I can understand that you state that it has been an issue for years if you haven't updated since 2013.

**Comment by FPtje** [comment]
That said the `playerWarranted` can return a value that suppresses that message, but then it wouldn't be shown on screen either unless that functionality is recreated in the hook that returns the value.

**Comment by 0tt** [comment]
I'd prefer it if everyone got the message, not just admins.

**Comment by FPtje** [comment]
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/police/sv_init.lua#L24

https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/police/sv_init.lua#L66
