### ISSUE TITLE
lua

### ISSUE THREAD

**Issue by Gamerpro2266** [FPtje/DarkRP#2535]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
just makes error in console 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
dont know what it is or how to make it 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] lua/includes/extensions/table.lua:150: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Count - lua/includes/extensions/table.lua:150
    3. unknown - vcmod/client/language_main.lua:2

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
i posted on here to find out what it is and the devs might or will know what it is

**Comment by roboderpy** [comment]
VCMod issues. Also for me VCMod is worst thing
