### ISSUE TITLE
Arrested issue

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2538]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If you are unarrested while in vehicle or ragdolled, you are invisible.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
enter a vehicle and get unarrested
get ragdolled and then unarrested

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
his code

**Comment by mcNuggets1** [comment]
If you are arrested while afk and then get unarrested, you get respawned, but youre job title stays "AFK"

**Comment by FPtje** [comment]
Ragdolled players could get arrested, but I can't reproduce them going invisible.

With unarrest they were just teleported, making them invisible in the seat. That's fixed.

**Comment by mcNuggets1** [comment]
Still bugs with AFKing
