### ISSUE TITLE
New player hook

### ISSUE THREAD

**Issue by NullEnt1ty** [FPtje/DarkRP#2540]
Can we have a hook that gets called when a new player joins the server the first time (so when there's a new database record)?

**Comment by FPtje** [comment]
Why? You can code such system yourself.

**Comment by NullEnt1ty** [comment]
Yeah, you're right. I could try to query the database in a PlayerInitialSpawn hook, but there's a possible race condition as all (?) GLua MySQL modules send asynchronous requests (I know, there's a way to block the main thread, but I would try to avoid that).

So here's what I think **could** happen:

1. Query darkrp_player to see if there's a player record.
2. GAMEMODE.PlayerInitialSpawn get's called -> Gamemode inserts a new player record.
3. My query get's executed after that because it was delayed for whatever reason.

Correct me if I'm wrong.

**Comment by FPtje** [comment]
Why do you want this? Why don't you create your own "first join" script? Why do you need the DarkRP player row data specifically?

**Comment by NullEnt1ty** [comment]
I'm trying to create a "Choose your RP name" popup if the player does not have one. Creating my own table could lead to inconsistent data.

**Comment by Bo98** [comment]
While not directly answering your original request, I will say that you should watch out for the scenario of if the player quits/crashes before they set a RP name. DarkRP will queue a a player record to be created somewhat immediately on initial spawn (ie. before the player chooses an RP name) so joining for a 2nd time without choosing an RP name could end up with not showing the prompt.

I know this potentially complicates your idea a lot more if you were to care about that kind of scenario but it had to be noted.

**Comment by NullEnt1ty** [comment]
Argh, didn't think of that. Well, that sucks.
