### ISSUE TITLE
Spectate error

### ISSUE THREAD

**Issue by alotlikebirds** [FPtje/DarkRP#2542]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
Fadmin spectate error

### How to make the bug happen
Spectate a player.
Die while spectating.
Player that you're spectating leaves.

Do all three in order.

### Lua errors
 [ERROR] gamemodes/darkrp/gamemode/modules/fspectate/cl_init.lua:116: Tried to use a NULL entity!
  1. EyePos - [C]:-1
   2. findNearestObject - gamemodes/darkrp/gamemode/modules/fspectate/cl_init.lua:116
    3. fn - gamemodes/darkrp/gamemode/modules/fspectate/cl_init.lua:329

### Why the developer of DarkRP is responsible for this issue
Come on Falco... This template is taking it way to far -.- JK... Well, I'm sure you'll agree with everything that I previously stated. If it's not your fault then maybe ULX is conflicting.

**Comment by FPtje** [comment]
fixed

**Comment by Bo98** [comment]
*fixed in the FSpectate repo but hasn't been merged into DarkRP yet.
