### ISSUE TITLE
VIPs are registered like Admins

### ISSUE THREAD

**Issue by GrGrMichi** [FPtje/DarkRP#2544]
### Description of the bug
[//]: # VIPs are registered like Admins. I am using ULX and I have a problem.
My Groups are like this: User, Donator(Inherts from User),Donator+(Inherts from Donator) and so on.

### How to make the bug happen
[//]: # The problem is that all groups that are not directly inherting from user are registered as admin.
That means that e.g. a donator+ can physgun all blocked entities and models. At the moment i just blacklisted and restricted all things and ticked off the "Admins can physgun blocked entities/models" and thats not what i want. I want that an admin can physgun and spawn blocked entities and models. I locked 
at Fadmin and didnt find something, aswell as in FPP. I cant just let all groups inhert from user, because then my Donator jobs wouldnt work...

I dont have errors.

I hope someone can help me. I am searching for days but I cant find anything and decieded to give up and ask some other people.

And what i wanted to say is that i really appreciate your work FPtje and i was extremly surprised yesterday, where you answered so quick. Thank you and keep doing like this!

**Comment by NotSoSuper** [comment]
not @FPtje's problem, expect this to be closed.

**Comment by GrGrMichi** [comment]
The Problem is that i dont know if this is Problem from Ulx, Fadmin or FPP

**Comment by FPtje** [comment]
:IsAdmin is returning true. The question is which :IsAdmin override is doing it.

**Comment by EstevanTH** [comment]
You should check the file containing your ULX groups: `garrysmod/data/ulib/groups.txt`
Well, when I read this file I do not understand the inheritance well anyway.
Maybe your should uninstall ULX+ULib forever and prefer FAdmin? :mask: It is actually worth it!

**Comment by GrGrMichi** [comment]
@EstevanTH That doesnt help me. The garrysmod/data/ulib/groups.txt is only the file where are my ingame settings getting safed and I dont want to uninstall ULX because our Community is using ULX for 2 Years in TTT. Now i have set up my DarkRP Server and have this problem. I am searching every day for a solution, but i cant find anything.

**Comment by FPtje** [comment]
It was FAdmin.

**Comment by FPtje** [comment]
Also, @NotSoSuper was wrong.

**Comment by Shigbeard** [comment]
NSS being wrong? Shocking...

**Comment by FPtje** [comment]
It was an off by one error. I fucked up that admin numbering when I created it. Sometimes it's this:
```
0 = user
1 = admin
2 = superadmin
```

and sometimes it's this:
```
1 = user
2 = admin
3 = superadmin
```

It's terrible design in the first place, but I cba to fix it.

**Comment by GrGrMichi** [comment]
Thank you
