### ISSUE TITLE
DarkRPDBInitialized hook does not get called

### ISSUE THREAD

**Issue by MaZyGer** [FPtje/DarkRP#2545]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
my sv_init.lua has a hook
```
hook.Add("DarkRPDBInitialized", "rpname_dialog_loadnames", function()
	print("[CHECK] DarkRP Database initialized")
end)
print("[CHECK] DarkRPDBInitialized hook added")
```
This "[CHECK] DarkRPDBInitialized hook added" gets printed after the map is loaded but not the print in the hook. I even waited maybe for 2 minutes. Still no print.
I tried also with other hook which was "DarkRPFinishedLoading" and its working with it but yea database is not finished and I get error if I want to query.

I am currently using tmysql4 (and mysql with mariadb) and all tables and entries are there. Even if rpname is changed the entries are updated

I also have just darkrpmodification with mysql file and my addon in the addons folder. No any other addons or workshopfiles.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
I am not sure if this is a bug but create an autorun file and use this
```
if SERVER then
	hook.Add("DarkRPDBInitialized", "test1231231232", function()
		print("[CHECK] DarkRP Database initialized")
	end)
	print("[CHECK] DarkRPDBInitialized hook added")
end
```
### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No any errors

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because they did the hook and I need the hook :)

**EDIT**: If I change **RP_MySQLConfig.EnableMySQL** back to **false** then the hook get called. Seems like it does not get called if mysql is enabled.

**Comment by FPtje** [comment]
This is not how lua works. The idea of a hook is that it can be called after the Lua file is loaded. Of course the print is going to run when put on top level.

**Comment by Bo98** [comment]
@FPtje the migrateDB function does appear to not always call onFinish in all scenarios though:

https://github.com/FPtje/DarkRP/blob/0c0aaabd3cfaa0a6671af023667f13292f1a4045/gamemode/modules/base/sv_data.lua#L261

**Comment by Bo98** [comment]
Sorry, misread.
