### ISSUE TITLE
DarkRP money not removing

### ISSUE THREAD

**Issue by gmanc2** [FPtje/DarkRP#2546]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When a player joins the server they receive $20,000 when said player trys to /dropmoney or buy anything from the entities or weapons or shipment category in the f4 menu or trys to use a cardealer or anything to subtract money nothing occors. But, players ARE able to add money to there account via printers and /dropmoney and picking it up.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Buying anything from anywhere money is not subtracted.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No lua errors occur.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

I have looked everwhere this is no documentation on this issue and no one else can help me I have removed all addons and looked everwhere but still nothing!

**Comment by FPtje** [comment]
This is an addon.
