### ISSUE TITLE
Issue with adding co-owners to doors

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2548]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Sometimes you cannot add a co-owner to a door, only a reconnect fixes this.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
appears likely random

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
His code

**Comment by FPtje** [comment]
"sometimes"  won't do as a way of reproducing this issue.

**Comment by mcNuggets1** [comment]
I don't know how to reproduce the issue, as I said.

**Comment by FPtje** [comment]
Then I have no reason to believe it's not an addon fucking you up.

**Comment by roboderpy** [comment]
I belive this is networking issue. Because Source Engine is using UDP it is always possible that when DarkRP networks things, client might lose some pockets (especialy on client lag), and therefore, unexpected things. Falco, do you remember that bug with empty "Allowed to co-own"? This shit is still persist somehow, but no one gives a fuck because it's only client issue. If you would force server to re-send all vars, door will become unowned.

**Comment by FPtje** [comment]
Networking in Gmod can be assumed to be reliable. No udp shit there. I'll take a look, but "sometimes it just doesn't work"  gives me **very** little to work with.

**Comment by mcNuggets1** [comment]
It is not an issue with addons, I can ensure.
It seems to be a serverside issue, not a clientside.

**Comment by Bo98** [comment]
Does anything happen at all when you try adding a co-owner, such as a notification?

**Comment by mcNuggets1** [comment]
No, not even a Lua error.

**Comment by Bo98** [comment]
Not sure how it's a serverside issue then as pretty much every step which it could abort at displays a notification except the `onAllowedToOwnAdded` hook.

**Comment by Bo98** [comment]
How reconnecting fixes it sounds more like a corruption of state in the clientside. Next time it happens, you could try running `lua_run ply:sendDoorData()` serverside, replacing ply with your own player object, which should force a full update to be networked to you. That would confirm some sort of clientside corruption in door state.

**Comment by FPtje** [comment]
I can't find anything. The only issues I can imagine are when the `extraOwners` table is empty or contains UserIDs of disconnected people, but that table is set to `nil` when an extraOwner is added. It also nicely removes co-owners on disconnect, setting the thing to nil when the last one is removed.

**Comment by mcNuggets1** [comment]
I made some tests.
It is indeed clientside.

Everything works fine, but clientside the co-owners arent added.

**Comment by FPtje** [comment]
Give me some steps. I'm pretty sure this doesn't reproduce the issue:
1. have bot own door
1. have bot add you as co-owner
1. own the door

Untested though

**Comment by mcNuggets1** [comment]
This is actually still happening for people.
I did not found any cause yet.

I did test it out without addons, that escapes in the same issue.
