### ISSUE TITLE
Adding job and categories after the darkrp loaded

### ISSUE THREAD

**Issue by ExtReMLapin** [FPtje/DarkRP#2552]
### Description of the bug
I'm working a addon which will help DarkRP owners to add Jobs ingamethere is a part in this addon which add job categories, as you know categories are sent to the client via the lua cache. And in my addon it's sending it to the client using the net library, because the server owner can create categories in game at any time, so i can't really save it as a .lua file . Of course i'm not trying to add the categories everytime one is created, but only at the server start.
Seems to be working on the server but on the client it's more complicated because the gamemode is loaded and initialized before trying to receive any message from the net library.

After connecting and spawning, the client is sending a net message to the server and the server is going to send him few tables with categories and jobs in it, it will create the categories first and the jobs.

If the jobs are in already-existing categories, it will work ... but for the categories who were sent with the jobs, that's not working

### Lua errors (i know you don't need it)

> Hints:
	- Make sure the category is created with DarkRP.createCategory.
	- The category name is case sensitive!
	- Categories must be created before DarkRP finished loading.

### Why the developer of DarkRP is responsible for this issue
Well i guess it would be nice to change the GM structure a bit to allow that. I don't even know if there is some kind of way to add the categories and the jobs, and they rebuild the menu/the darkrp code on the client.

**Comment by FPtje** [comment]
Give me specific code to reproduce the Lua error you gave me. "*Restructure the gamemode to allow x*" is the vaguest possible demand.

**Comment by FPtje** [comment]
Also, if `DarkRP.createCategory` in a `timer.Simple` does the trick I'd like to know. That would make it easy for me.

**Comment by ExtReMLapin** [comment]
Nvm i'm just a fucking idiot, i was just reading two times the same table sent to the client.


fucking GG

wasted 4 hours trying to remake the dakrp structure because didn't swap two vars.
