### ISSUE TITLE
Unwanted

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2553]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Sometimes wanted doesnt get removed on death.
The "wanted removed" text appears also, when dying after the wanted time.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
get wanted.
die.
wait.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
police module

**Comment by FPtje** [comment]
It must be an addon  returning `true` in `PlayerDeath`, because there's nothing in the way of the code to unwant on death being executed. Unless of course there are errors you're not mentioning.

Also, you don't get unwanted when you commit suicide.

**Comment by mcNuggets1** [comment]
Why dont you get unwanted on suicide?
That sounds pretty stupid.

"Hey gotta fight the dead".

Oh and my server never has any error.
I literally hate errors.

**Comment by FPtje** [comment]
Because suicide is a really easy way to get unwanted.

**Comment by mcNuggets1** [comment]
Does it work properly for arresting?

**Comment by FPtje** [comment]
oh I meant returning any value.

**Comment by mcNuggets1** [comment]
I meant that too.
I actually am capable of running a stupid server without bugs or errors.
Sorry, if that sounded offensive, wasnt meant to be.

So does it work properly for arresting people?

**Comment by FPtje** [comment]
Yes. Someone would have noticed in all those years.

**Comment by mcNuggets1** [comment]
I am not so sure about that.
I will test it out later.

**Comment by FPtje** [comment]
The code to do it is there. Also, why are you asking **me** whether something works!? First you say it happens "*sometimes*" as if that's some kind of precise way of reproducing it and then you ask *me* questions about whether things work?

You're the one with the issue here. Not me. You're the one who's supposed to prove to me that there's something wrong in my code. I'm not going to start a damn research project to go bug hunting when someone says *sometimes*  something doesn't work. Your lack of effort to properly describe a bug will be matched with my lack of effort to look into it.

**Comment by mcNuggets1** [comment]
Relax, guy.

I never said, you should start a damn research.
I said I'll do that.

**Comment by FPtje** [comment]
The idea of asking a question is wanting an answer. You wanted me to test whether arresting works. You demanded me to put effort into testing it, even though I have no reason whatsoever to believe that it's broken.

**Comment by mcNuggets1** [comment]
Why do you have to test things?
Just look into the function, and you know if its there or not.

**Comment by FPtje** [comment]
Because the question "does x work" is best answered with a test.

**Comment by mcNuggets1** [comment]
Well, okaay.

Sorry, then.
