### ISSUE TITLE
Group error

### ISSUE THREAD

**Issue by Mika32150** [FPtje/DarkRP#2554]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

A group under superadmin (adminchief) can spawn vehicles and weapons with Q menu. I've created this group to be between admin and superadmin group. I've pout their immunity in ULX and in Fadmin.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Be adminchief, go to Q menu and spawn what you want like a superadmin

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No lua error

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

He is responsible because in settings.lua i've put all for superadmin or higher, and a group under superadmin can spawn vehicles and weapons !

**Comment by FPtje** [comment]
It uses the "based on" stuff, not the "immunity" stuff. Base a group on superadmin and players in it will be a superadmin. The solution is to base the group on admin.
