### ISSUE TITLE
Disabling default jobs but still there

### ISSUE THREAD

**Issue by PIERREZZZZ7** [FPtje/DarkRP#2555]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (New server...I went to Disabled_default to and i changed false to true on the default jobs it's been a couple of days now and they are not disabled i remember being able to disablel them easily threw there how can i do it now? There is no error message nothing just that they are there is the error.)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (I don't simply went to darkrpmodification > disableddefault changed ALL the default job to true to disable them but they are still there...)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (No errors.)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (Because they released the darkrp modification i think and that maybe they can help me threw this silly issue)

**Comment by FPtje** [comment]
not a help forum.

**Comment by EstevanTH** [comment]
Amazing troll issue with 0 description.
