### ISSUE TITLE
isMayor error

### ISSUE THREAD

**Issue by Sachha** [FPtje/DarkRP#2557]
### Description of the bug
My server have a HUD that display the mayor name . When a player join it, there is a "random" error in the console.
It didn't have any impact in game but could be nice to solve it :)

### How to make the bug happen
Join a server calling isMayor in his HUD probably

### Lua errors

[DarkRP] gamemodes/darkrp/gamemode/libraries/fn.lua:252: attempt to index local 'xs' (a nil value)
  1. isMayor - gamemodes/darkrp/gamemode/libraries/fn.lua:252
   2. fn - addons/darkrpmodification/lua/darkrp_modules/tcb_premium_hud/cl_main.lua:307
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

### Why the developer of DarkRP is responsible for this issue
I don't know, isMayor function is strange for me ... Using the fn librairie

PS; Sorry for previons issues

**Comment by FPtje** [comment]
Not a help forum. Please go to forum.darkrp.com
