### ISSUE TITLE
Request: ability to disable Simplerr

### ISSUE THREAD

**Issue by uRandomAlex** [FPtje/DarkRP#2560]
Request: ability to disable Simplerr.

Also, your fancy pattern just hides text.

**Comment by FPtje** [comment]
#NoSimplerr# in the file. Also, what text does it hide?

**Comment by uRandomAlex** [comment]
I mean globally, not just in one file - going through every file in DarkRP and adding this is not convenient at all.  I've tried to change text inside of (), but the text was not appearing.

**Comment by FPtje** [comment]
That will defeat the purpose of simplerr. I explicitly don't want to give you the ability to fuck up better error messages in people's jobs.lua because you can't deal with it when you're programming your DarkRP module.

**Comment by uRandomAlex** [comment]
Why can't you just add a config option for that? Is it that hard? I don't need Simplerr at all - and HUGE error messages it produce increases size of my logs and decreases console's history. Also, disabled autorefresh is just a pain for me - I need to restart map (and make players lose all their printers and other things) in order to apply one small change. You can simply print a big warning in console if some module is disabling Simplerr if it's enabled in config.

**Comment by FPtje** [comment]
The previous post says I don't want you to be able to fuck simplerr up. By asking for a config option you ask for the ability to fuck simplerr up. You're not getting it.

**Comment by uRandomAlex** [comment]
@FPtje 

> You can simply print a big warning in console if some module is disabling Simplerr if it's enabled in config.

**Comment by FPtje** [comment]
And those warnings will do literally nothing.

**Comment by uRandomAlex** [comment]
@FPtje Then reset config value to default alongside with warnings?

**Comment by FPtje** [comment]
Then the config option has no effect.

It's not happening. Deal with it.

**Comment by Shigbeard** [comment]
If you don't want Simplerr, try installing DarkRP 2.4.3

**Comment by FPtje** [comment]
I'm not having that bullshit @Shigbeard

**Comment by Shigbeard** [comment]
I have no idea what you are talking about FPtje.

**Comment by Kefta** [comment]
Just modify the core files if you don't want it. Or override _R[1] yourself and fuck around with other addons trying to use it.

**Comment by FPtje** [comment]
Create a single file that loads other lua files in a subfolder and put #NoSimplerr# in there
