### ISSUE TITLE
Group restriction problem 

### ISSUE THREAD

**Issue by GrGrMichi** [FPtje/DarkRP#2561]
Hey I'm back with a group restriction problem again :D

I am using both, ULX and FAdmin. I want to make a group that has not that much rights like an admin, but I want that this group can also e.g. remove other players props. It seems like this is only possible when the group inherts from admin or inherts from groups that are generelly above the group admin and thats exactly what I don't want.

There are no Lua problems ofc..

I hope you can add an option for this or fix this problem with another way.
If this already works, then I'm sorry for wasting your time and I hope you can tell me how to set this group correctly up.

**Comment by FPtje** [comment]
Check out the latest version of DarkRP on Github. I've just created a privilege for your admin mod. With ULX or FAdmin you can set your usergroup to have the new `FPP_TouchOtherPlayersProps` privilege. Once they do, they can touch other people's entities when the option `Privileged users can <something> all entities` is enabled.
