### ISSUE TITLE
job + name error

### ISSUE THREAD

**Issue by Zortex04** [FPtje/DarkRP#2563]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
 Everytime my friends server restarts it resets everyones rp names and puts everyones job as joining/connecting and f4 doesent work, after some time the f4 menu works agian

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
restart server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Clientside is this

[DarkRP] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Ive Seen this happend to multiple servers and the owners just give up on trying to fix it

i know this isent very detailed, and i dont know if this already has been answered so im sorry if this is too little detail or has already been answered

**Comment by EstevanTH** [comment]
Hmm, if you have an error then I think that there is another error somewhere else.
The server probably displays an error that should help solving the issue.

I am not sure though, but `attempt to index local 'jobTable' (a nil value)` is almost always related to a bad configuration file.

**Comment by FPtje** [comment]
Not a help forum

**Comment by Shigbeard** [comment]
Gee, your error references a "Job table" that is nil, I fucking wonder 
what that could mean? It couldn't possibly mean that the game thinks 
there are no jobs, meaning you fucked up the jobs file... that's just silly.

God, fucking read your errors you incompetent fuckfaces. I'm sick of 
seeing issues where people ignore every fucking all-caps message telling 
them where to post for help, don't at all bother searching for their 
error OR EVEN FUCKING READING IT, and just expect Falco or his fellow 
devs to fix it for them.

**Comment by Zortex04** [comment]
Engough, Listen This is a directly fresh install of both darkrpmodification and darkrp, i have no jobs, i havent edited ANY Files At all this just happend

**Comment by Shigbeard** [comment]
https://github.com/FPtje/DarkRP/issues?q=is%3Aissue+attempt+to+index+local+%27jobTable%27+%28a+nil+value%29+is%3Aclosed

Research. Do it.
