### ISSUE TITLE
FAdmin: Scoreboard VGUI part not hidden when closing at same time as clicking on a name

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2564]
### Description of the bug
[//]: # Hoi Falco. :heart:
I have been told about this bug and I have been able to reproduce it (not easy with high FPS).
But well, when you click on a player's line in the FAdmin scoreboard, details should load. But if you release `+score` exactly at the same time you clicked, it will not hide the VGUI part of the scoreboard properly.
![VGUI not hidden](https://puu.sh/rJVbG/688232601e.jpg)
And more problematic, the profile picture does not hide, ever.
![Persistent profile picture](https://puu.sh/rJVid/3a27ab5997.jpg)

### How to make the bug happen
[//]: # Try to run the game at the lowest FPS you can reach (the `fps_max` ConVar can help).
[//]: # Keep `+score` pressed.
[//]: # Click on a players line (can be yourself) and at the same time, release `+score`.
[//]: # Next time you open the scoreboard, the VGUI will hide properly on next `-score`, except the profile picture, which is now persistent.

### Lua errors
[//]: # I cannot see any error. :sweat_smile:

### Why the developer of DarkRP is responsible for this issue
[//]: # I do not feel powerful enough to fix this myself. Maybe it's a problem with multiple events, delays that should be there but are not, mis-referenced or mis-parented profile picture...
[//]: # It is not my work but I think that in cases of low FPS it can make the situation much more comfortable.

**Comment by Noname12345GER** [comment]
Jep.

**Comment by FPtje** [comment]
This was easier to reproduce and fix than I thought.

**Comment by EstevanTH** [comment]
Dank je! :smiley:
