### ISSUE TITLE
lockpickTime does not work

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2566]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # you can not set the time

` local endDelta = hook.Call("lockpickTime", nil, self:GetOwner(), ent) or util.SharedRandom("DarkRP_Lockpick" .. self:EntIndex() .. "_" .. self:GetTotalLockpicks(), 30, 40)`

**Comment by fruitwasp** [comment]
It does work. You should add a hook with [hook.Add](http://wiki.garrysmod.com/page/hook/Add) and return the lockpick time instead.

For further help, ask your question on the forums. Also, don't edit core files (which you probably did)
