### ISSUE TITLE
Customcheck problem

### ISSUE THREAD

**Issue by Spoderman12** [FPtje/DarkRP#2567]
### Description of the bug
CustomCheck issue I can buy shipment weapon in all jobs.
http://www.noelshack.com/2016-42-1476880561-capture.png
http://www.noelshack.com/2016-42-1476880564-capture1.png
Version: 2.7.0
GM.Config.hideTeamUnbuyable = true

### How to make the bug happen
I dont know it happens without doing anything.

### Lua errors
No darkrp lua errors: http://pastebin.com/j54k67Sm

### Why the developer of DarkRP is responsible for this issue
I cant solve it by myself already makes a ticket on scriptfodder support I was thinking it would be my f4 hud but it is not.

**Comment by FPtje** [comment]
Not a help forum.
