### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by EzGunzBlazzinn** [FPtje/DarkRP#2570]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The Camera can be used to basicly noclip.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
If you pull out your tool gun and go to camera you can sprint and jump while clicking rapidly with the camera to boost and make yourself fly if you time it just right. I believe this is a bug because it never occured in DarkRP 2.5

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
There is no Lua Errors, Its just a small error i believe.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
You made the stools within the camera i believe

**Comment by FPtje** [comment]
I didn't make the camera.
