### ISSUE TITLE
RP Name Issue

### ISSUE THREAD

**Issue by EzGunzBlazzinn** [FPtje/DarkRP#2571]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Name Changing is saying that there already is a name "Lucifer" but nobody is 'Lucifer"

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
My original name was "Lucifer" then i changed it to "Lucifers" because i was showing someone else how to change names, Then when i tried to change back to "Lucifer" it says "Sorry, Name already Taken" but nobodys Name is Lucifer. I also tried darkrp forcerpname command. Did the same thing.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
darkrp forcerpname is DarkRP's Command.

**Comment by FPtje** [comment]
It looks in the database, not in the server.
