### ISSUE TITLE
Arrest + Unarrest-Stick changes.

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2572]
### Description of the suggestion
Arrest + Unarreststicks should be more configurable.
I would like to add a deploy delay + animation.
So a player has some sort of delay, before it is available for usage.
It would balance the arresting/unarresting of players alot as you can not take it out, and instantly arrest a player.

Also I would like to change the NextPrimaryFire delay, after using one of the batons.
There is a convar called config.arrestspeed(or some sort) in darkrpmodification, but it does nothing at the currentstate.
Firstly I thought it would change the Fire delay, but it does not.

Just a simple SWEP.Primary.Delay, which actually come in use for the Fire delay and SWEP.DeployDelay for the sticks would make it configurable with the weaponsettings module.

**Comment by FPtje** [comment]
This is why you can base SWEPs on other SWEPs.

**Comment by mcNuggets1** [comment]
For changing like 2 simple things it is not worth it.

**Comment by FPtje** [comment]
Substitute your specific preference of your specific things that you specifically want to change for literally any other configuration that exists for SWEPs. I can make a fire and deploy delay for you, but by that logic I should also add reload delay, right click delay, hit distance, how wide the hits are, all that shit. They're all the same kind of config and there's the same solution for every single one of them: make your own derived SWEP.

**Comment by mcNuggets1** [comment]
I dont want a config.
I want a variable on the SWEP changeable by the weaponsettings module.

There is a reason GMod uses SWEP.Primary.Delay and SWEP.DeployDelay in the base weapon_base.

**Comment by FPtje** [comment]
The SWEP.Primary.Delay doesn't apply to sticks because sticks don't use an arbitrary delay. They use the animation time instead. That doesn't rhyme well with a SWEP setting.

As for deploy time, use this: http://wiki.garrysmod.com/page/WEAPON/SetDeploySpeed

Why do you want to nerf the least used SWEP anyway?

**Comment by mcNuggets1** [comment]
Haha, well, not in my realm.
It actually is one of the main weapons in my server.

Due to I don't have rules like FearRP, Battlearrest etc. I just think these ones are stupid and I am never gonna add these, just because of this issue.

Due to the lack of a deploy animation and primary delay, it doesnt work that well with balancing.
While weapons like shotguns need a whole magazine to kill a player, because else they are well overplayed, the arrest stick comes in handy.
Because of the incredible fast attack speed and the lack of a deploy animation, which actually should have every weapon, the cp job is too "overpowered".

I also don't like the idea of modifying DarkRP weapons, but rather having a nice configurable variable.

For the attack speed, there could be a multiplier actually.
For the deployanimation/delay is SetDeploySpeed even supported, I mean for the idle anims etc.

**Comment by FPtje** [comment]
So you don't just want the deploy to take longer, you want the animation to slow down too. Really, this is a derived weapon thing.

**Comment by mcNuggets1** [comment]
I actually meant the deploy and as SWEP.Primary.Delay does not exist, there could be added a functionality for actually modifying the attack speed.
But I did not mean that, I clearly meant a time multiplier.

**Comment by mcNuggets1** [comment]
If I would do alot of work for the weapon base n' stuff and would make a pull request, would you merge it, if it benefits your "style"?

**Comment by FPtje** [comment]
Possibly. Please have it lint without warnings.

**Comment by mcNuggets1** [comment]
I'll try.

**Comment by Bo98** [comment]
> alot of work

Does this really require a massive overhaul?

**Comment by mcNuggets1** [comment]
I got a few things on my list.

**Comment by Bo98** [comment]
A attack speed time multiplier should literally only affecting this part of the code (which line depends if you want to affect the animation speed):

https://github.com/FPtje/DarkRP/blob/master/entities/weapons/stick_base/shared.lua#L124-L126

But since you didn't detail what else is on your list, I'll wait and see what you're planning.
