### ISSUE TITLE
The value of GAMEMODE.Config.respawntime is clamped!

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2573]
### Description of the bug
Dag!
The DarkRP has a custom configuration field `GM.Config.respawntime`. That is amazing.
But if you clamp this value, it will just mislead the server's staff.
I really recommend to only use `math.max( GAMEMODE.Config.respawntime, 0 )` instead, so people will not strangely notice that the respawn timer does not behave as configured.
[sv_gamemode_functions.lua at line 422](https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/base/sv_gamemode_functions.lua#L422)

### How to make the bug happen
Simply configure `GM.Config.respawntime` to a value greater than 10.

### Lua errors
Hopefully no error here.

### Why the developer of DarkRP is responsible for this issue
I think that this unexpected behavior belongs to someone who worked on the DarkRP.

Thanks Falco!
Momo :heart:

**Comment by FPtje** [comment]
Server owners cannot make right decisions on various levels. Responsibilities time used to be a classic one. Back when I added this clamp, having a thirty second respawn time started becoming the norm. That's ridiculous! Having to wait idly for so long for something that happens so often! Some servers went up to 90 seconds!

This is where I decided that unreasonable config options should be impossible.

The criticism also applies to the 120 second default arrest time, by the way. I don't like that either. Luckily someone is working on a different system.

**Comment by EstevanTH** [comment]
Then please add a note somewhere in the darkrpmodification.
This thing has been conflicting with my friend's addon, which overrides the
respawn time!

Dank je Falco!

2016-10-28 23:59 GMT+02:00 Falco Peijnenburg <notifications@github.com>:
