### ISSUE TITLE
Single guns ignore allowed tag

### ISSUE THREAD

**Issue by sterrenman** [FPtje/DarkRP#2574]
### Description of the bug
When adding shipments, Separate guns do not follow the allowed setting. I can restrict shipments to specific jobs, But single variants can still be bought by anyone.

### How to make the bug happen
Make a shipment that also has a single gun variant.

`DarkRP.createShipment("Desert Eagle", {
    model = "models/weapons/w_tcom_deagle.mdl",
    entity = "m9k_deagle",
    price = 5000,
    amount = 10,
    separate = true,
    pricesep = 500,
    noship = false,
    allowed = {TEAM_GUN},
    shipmodel = "models/items/item_item_crate.mdl",
})`

### Lua errors
None.

### Why the developer of DarkRP is responsible for this issue
Shipment job restrictions should also work on single weapons. Its a bug because the intended behavior is that single guns also listen to this, According to http://wiki.darkrp.com/index.php/DarkRP:CustomShipmentFields

**Comment by FPtje** [comment]
It's admittedly shit, but `GM.Config.restrictbuypistol` has to be set to `true` in the DarkRP settings in the DarkRPMod.

The reason why this isn't being changed is because it would break everyone's shit, making everyone mad.

**Comment by sterrenman** [comment]
Ah Okay, Thank you.
