### ISSUE TITLE
DarkRP Jailset not working whatsoever

### ISSUE THREAD

**Issue by GiornoGiovanna** [FPtje/DarkRP#2580]
### Description of the bug
We cannot set the jailpos on our new server, We have tried all the /commands as normal and as chief (we are superadmins)  it doesnt even come up with the message that should come up saying "you have cleared the jail pos", we have tried everything and can't set the jail

### How to make the bug happen
attemping to do and of the /jail commands

### Lua errors
none

### Why the developer of DarkRP is responsible for this issue
I have searched all over online and done GM. commands and tried every solution but it never works and we cant RP properly

**Comment by EstevanTH** [comment]
Hi. As a rescue solution, if you use fixed jail positions, you can manually edit the database.
Open the `darkrp_position` database and insert each position manually. The type is `J` for jail positions.

**Comment by GiornoGiovanna** [comment]
Hi, thank you for your response, I would appreciate if you could inform me of how to determine the co-ordinates and where this table is located this would be awesome thanks!

**Comment by EstevanTH** [comment]
Open the `sv.db` database with an SQLite database editor, such as [DB Browser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser/releases).

**Comment by FPtje** [comment]
Cannot reproduce.
