### ISSUE TITLE
Hunger Mod

### ISSUE THREAD

**Issue by HerrAmmo** [FPtje/DarkRP#2582]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This "bug" can be found in the Hunger Mod. When you are in God Mode(ULX or FAdmin), you lose life by hunger.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Get hungry in God-Mode

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I need to forward it to you because you are the developer of this modification.

**Comment by FPtje** [comment]
Intended behaviour
