### ISSUE TITLE
Don't pickup a weapon if the weapon has no new ammo for the player

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2584]
### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The issue is, you can pickup weapons, even if they do not grant you any new ammo, making the weapon just disappear forever.

**Comment by EstevanTH** [comment]
My little finger tells me that this behavior is intended. :innocent:

**Comment by mcNuggets1** [comment]
It would be quite stupid if so.

**Comment by uRandomAlex** [comment]
I think that behaviour of dropped weapons should change to this: if you are trying to pickup it while you already have that weapon, only ammo from this weapon is given to you, but the weapon itself does not disappear, so players without this weapon can pickup it.

**Comment by FPtje** [comment]
Great idea and all, but what should happen to the weapons that remain when everyone has enough ammo? The only way to then get rid of those weapons is to *die*, respawn, pick up more weapons and repeat until everything is gone.

Especially with weapons that have a low maximum ammo this could be a serious problem.
