### ISSUE TITLE
Categories Error

### ISSUE THREAD

**Issue by BadWorksFun** [FPtje/DarkRP#2590]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Okay so one day I loaded up my server and all my categories was broken... I tried to fix in all ways till I was like you know what why not I copied all the categories from categories.lua to jobs.lua in my DarkRP modification addon and it fixed it. I have no clue why the categories stopped working... It was like the categories folder was deleted even tho I could see it in its same place. BTW thank you so much for making this addon you're amazing FPtje!

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
It just simply said.

[ERROR] A runtime error has occurred in "your jobs" on line -1.
The best help I can give you is this:

The category of "Meth Maker" ("Criminal") does not exist!

Hints:
	- Make sure the category is created with DarkRP.createCategory.
	- The category name is case sensitive!
	- Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
your jobs
------- End of Simplerr error -------

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I just want to know how to fix it if possible thank you, cause it gets annoying going into jobs.lua and seeing a ton of categories. Thank you.

**Comment by FPtje** [comment]
This is not a help forum. Go to Forum.darkrp.com

**Comment by Shigbeard** [comment]
You might want to try this for a fix.

https://www.amazon.com/Teaching-Kids-Read-Dummies-Tracey/dp/0764540432
