### ISSUE TITLE
Cannot stop lockdown

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2593]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Suiciding while lockdown as mayor prevents the lockdown from being able to be stopped.

Tested on vanilla DarkRP without any addons at all.

Function DarkRP.unLockdown's first check fails then.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Suicide as mayor while having a active lockdown.
Try to stop lockdown.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Police module.

**Comment by mcNuggets1** [comment]
So after a bit of testing, the issue seems to be "DarkRP_Lockdown" does not get networked properly to the player properly if a server is heavily under lag.

**Comment by FPtje** [comment]
That would have to be a GMod bug. I should not have to account for `SetGlobalBool` not literally doing the one thing it was designed to do.

**Comment by mcNuggets1** [comment]
The weird thing it has to be.
I searched along with notepad for "SetGlobalBool", "DarkRP_Lockdown" and "Lockdown" and there was no results, means it has to come from DarkRP.

I know very popular servers got the same bug too.

**Comment by FPtje** [comment]
You can't find any of those things in DarkRP code? I can find all of them. I don't understand where the conclusion that it has to come from DarkRP is coming from either.

**Comment by mcNuggets1** [comment]
I mean in addons/scripts etc.
I thought it would be a bug from my server at first and invested more than 10h searching through all fucking hooks to get this stupid bool not networking properly.
DarkRP uses it about 2 times. I also searched there.

**Comment by mcNuggets1** [comment]
Currently DarkRP has a bunch of unsolved bugs and I thought it could be a bug of DarkRP either...

**Comment by FPtje** [comment]
I just tested it and I can stop a lockdown after dying as a mayor.

**Comment by mcNuggets1** [comment]
Yeah, I know, described it bad.
Client thinking lockdown exists, but lockdown is dead actually.
Thats the issue.

Which only occurs very rarely however.

**Comment by Bo98** [comment]
This might be fixed whenever (if ever) GMod finally properly switches to NWVars2 instead of being behind temporary function names.

I guess you can test it out with `SetGlobalBool = SetGlobal2Bool` and similar for the getter.
