### ISSUE TITLE
Cant add "Co-Owners" at a door by F2 Menu

### ISSUE THREAD

**Issue by marv0702** [FPtje/DarkRP#2594]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (If i will add a "Co-Owner" at a Door, it just happens nothing.)

### How to make the bug happen
[//]: # (Just buy a door, dont know if its important but i'm a Moderator on the server so I have to use the F2 menu for buy.)
[//]: # (------)

### Lua errors
[//]: # (--------)
[//]: # (--------)

### Why the developer of DarkRP is responsible for this issue
[//]: # (The Scripter of my Server said, only you could fix this Problem)
[//]: # (No one else is able to work at the DarkRP mod without the fear to destroy like everything.)

**Comment by mcNuggets1** [comment]
I got this issue too, still, by the way.

The op didnt describe it at all, but it does exist, i can confirm that.

**Comment by FPtje** [comment]
![2016-12-06_18-56-31](https://cloud.githubusercontent.com/assets/1202014/20937111/c37c054a-bbe5-11e6-8baa-aa9a87ec161a.jpg)

I cannot fix bugs that I cannot reproduce.

**Comment by mcNuggets1** [comment]
Not always.
I already trying to hunt this bug.

As far as I know, you can't add co-owners rarely on the same door, it does not work with using "darkrp ao" either or some other command, even selling the door does not fix the bug.
You'll have to rejoin as far as I know or use another door.
I honestly have no idea, how this bug should work, but it does exist and I am trying, still trying to reproduce it.

**Comment by FPtje** [comment]
> can't add co-owners rarely on the same door

This is a malformed sentence. It's difficult to understand what you're saying here. Here's what I tried just now:

- buy door
- add owner bot
- have bot accept the invite and own the door
- sell door
- buy same door again
- add owner bot again
- have bot accept invite again

it works.

**Comment by mcNuggets1** [comment]
I'll record something, the next time I see this, mkay?

**Comment by FPtje** [comment]
That recording is going to be useless if it doesn't tell me how to reproduce it.

**Comment by mcNuggets1** [comment]
It can't be properly be reproduced with my current knowledge.
