### ISSUE TITLE
vgui File Fast Download Problem

### ISSUE THREAD

**Issue by forumapp28** [FPtje/DarkRP#2598]
Description of the bug:

Only darkrp and fadmin files are downloading. vgui file is not download.

Sorry for bad English.

**Comment by FPtje** [comment]
PEBCAK

**Comment by Shigbeard** [comment]
Pineapples Exist Because Chocolates Are Kewl?

**Comment by FPtje** [comment]
PEBCAK and PEBKAC are both valid and mean the same.

**Comment by Shigbeard** [comment]
I know, I was doing a meme from TFTS

**Comment by FPtje** [comment]
What is TFTS

On 13 Dec 2016 5:41 p.m., "Shigbeard" <notifications@github.com> wrote:

I know, I was doing a meme from TFTS

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/FPtje/DarkRP/issues/2598#issuecomment-266790559>, or mute
the thread

**Comment by Shigbeard** [comment]
Tales from Tech Support

**Comment by forumapp28** [comment]
What? Can you fix it?

**Comment by Kefta** [comment]
He's essentially saying the problem is on your end. Make sure you're FastDLing it

**Comment by forumapp28** [comment]
Is it fixed ? Sorry for bad English.

**Comment by Shigbeard** [comment]
No. It is not fixed. It will not be fixed. In order for it to be fix, you must start by learning how to fix. Look at not fixed code, read it, and then fix. Then code is fix.

I'm not sure what is worse, uploading 660mb at <100kb/s or seeing this retard post.

**Comment by forumapp28** [comment]
How am I going to fix it. Does not download required files.

**Comment by forumapp28** [comment]
Does not download required files. For http://prntscr.com/diyz5a

**Comment by Shigbeard** [comment]
How you ask? By thinking.

A difficult concept, I know, but if you try really really hard you might manage to figure out 2+2.

**Comment by EstevanTH** [comment]
Usually I use `resource.AddWorkshop( '248302805' )` to make it work fine.

2016-12-13 18:07 GMT+01:00 Shigbeard <notifications@github.com>:

**Comment by forumapp28** [comment]
Is there any other solution?

**Comment by FPtje** [comment]
For this thread, yes: closing it. I know no solution for your inability to read simple instructions that state that you are to go to the forums for help.
