### ISSUE TITLE
2 Lua Errors

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2599]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Fresh errors straight out of my console.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Errors.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
1.
[ERROR] gamemodes/darkrp/gamemode/modules/voting/cl_voting.lua:123: Tried to use a NULL entity!
  1. EmitSound - [C]:-1
   2. Function - gamemodes/darkrp/gamemode/modules/voting/cl_voting.lua:123
    3. unknown - lua/includes/modules/usermessage.lua:87

(LocalPlayer() ist invalid for some reason, maybe on joining game)

2.
[ERROR] gamemodes/darkrp/gamemode/modules/chat/cl_chat.lua:18: attempt to call method 'Nick' (a nil value)
  1. func - gamemodes/darkrp/gamemode/modules/chat/cl_chat.lua:18
   2. unknown - lua/includes/extensions/net.lua:32

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
His lines.

**Comment by FPtje** [comment]
When do these errors happen? Both errors indicate `LocalPlayer` is `NULL`, which should never happen.

**Comment by FPtje** [comment]
Except for the very start of the game.

**Comment by mcNuggets1** [comment]
You got it.

**Comment by FPtje** [comment]
fixed in latest
