### ISSUE TITLE
DarkRP Content Download Problem

### ISSUE THREAD

**Issue by forumapp28** [FPtje/DarkRP#2600]
Darkrp content that need to be transferred from the server to the client:

- sound/earthquake.mp3
- materials/darkrp/...
- materials/fadmin/...
- materials/vgui/...

But "materials/vgui/..." not transferred from the server to the client.

For this reason the give weapon menu on the client is faulty. (http://prntscr.com/dj0cmk)

Can you fix this?

Thanks.. I am waiting for your help.

**Comment by Shigbeard** [comment]
PEBKAC

http://forums.darkrp.com/

**Comment by forumapp28** [comment]
I can not register.

http://prntscr.com/dj0k5l

**Comment by Bo98** [comment]
Ah, so only materials/vgui/* is affected? Everything else works fine?

**Comment by Shigbeard** [comment]
Your problem still exists between keyboard and chair.

**Comment by Bo98** [comment]
Also, what browser are you using to sign up to the forum?

**Comment by forumapp28** [comment]
Google Chrome

**Comment by Kefta** [comment]
@Shigbeard So just fuck him because he can't register on the site you linked him, right?

**Comment by Kefta** [comment]
Can you link your FastDL/WorkshopDL code?

**Comment by Bo98** [comment]
Shouldn't be necessary since it should be DarkRP's responsibility to use `resource.Add*`.

**Comment by Kefta** [comment]
I had no idea that was in the gamemode by default. Looking at the code, it doesn't look like https://github.com/FPtje/DarkRP/tree/master/content/materials/vgui/entities is ever AddFile'd

**Comment by forumapp28** [comment]
`HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/access.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/access.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/access.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/access.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ban.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ban.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ban.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ban.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/changeteam.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/changeteam.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/changeteam.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/changeteam.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/chatmute.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/chatmute.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/chatmute.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/chatmute.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cleanup.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cleanup.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cleanup.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cleanup.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cloak.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cloak.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cloak.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/cloak.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/disable.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/disable.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/disable.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/disable.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/freeze.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/freeze.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/freeze.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/freeze.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/god.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/god.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/god.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/god.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ignite.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ignite.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ignite.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ignite.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/jail.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/jail.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/jail.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/jail.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/kick.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/kick.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/kick.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/kick.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/message.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/message.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/message.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/message.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/motd.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/motd.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/motd.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/motd.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/noclip.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/noclip.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/noclip.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/noclip.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/pickup.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/pickup.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/pickup.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/pickup.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ragdoll.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ragdoll.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ragdoll.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/ragdoll.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/rcon.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/rcon.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/rcon.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/rcon.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/serversetting.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/serversetting.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/serversetting.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/serversetting.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slap.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slap.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slap.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slap.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slay.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slay.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slay.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/slay.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/spectate.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/spectate.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/spectate.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/spectate.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/teleport.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/teleport.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/teleport.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/teleport.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/voicemute.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/voicemute.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/voicemute.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/voicemute.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/weapon.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/weapon.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/weapon.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/icons/weapon.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/back.vtf.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/back.vtf
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/back.vmt.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/fadmin/back.vmt
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/sound/earthquake.mp3.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/sound/earthquake.mp3
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/darkrp/darkrpderma.png.bz2
HTTP ERROR 8 downloading http://52.59.xxx.xx/fastdl/materials/darkrp/darkrpderma.png`

I deleted fastdl and client files for test.

Where "materials/vgui" ? Is this PEBKAC ? Are you seriously ? @Shigbeard

**Comment by Bo98** [comment]
Yes, that indeed looks like materials/vgui/* is not added by DarkRP, which suggests it's DarkRP's problem.

**Comment by Kefta** [comment]
Not sure what "ERROR 8" is supposed to mean, but if it refers to 408, then the request timed out.

**Comment by forumapp28** [comment]
I deleted fastdl and client files for test. @Kefta

**Comment by Kefta** [comment]
@forumapp28 Oh, you mean your files on your FastDL server.

**Comment by Bo98** [comment]
He did that to prove what GMod is attempting to download, and thus show what is being `resource.AddFile`'d.

**Comment by forumapp28** [comment]
I deleted the FastDL files to show http requests. @Kefta 

Sorry my bad English.

**Comment by forumapp28** [comment]
They need to fix it

**Comment by FPtje** [comment]
This is a fastdl problem, not a DarkRP one. I have no influence over your fastdl setup. I can do **nothing** to solve your problem.

**Comment by Kefta** [comment]
@FPtje But you resource.AddFile everything except the materials/vgui/ folder for DarkRP. That is DarkRP's fault.

**Comment by FPtje** [comment]
oh, jesus, I totally misunderstood the issue. Sorry about that.

Must've been broken for fucking *years*.

**Comment by Bo98** [comment]
Yup, over 3 years.

It's ok, we can blame @Shigbeard.

**Comment by FPtje** [comment]
Really? What commit?

**Comment by Bo98** [comment]
Well he added the VGUI materials and neglected to `resource.AddFile` them.

Very easy to miss though since we all have the files stored locally.

**Comment by FPtje** [comment]
@forumapp28 Sorry for misunderstanding you. It should be fixed in latest.
@Kefta Thanks for talking straight. Your post made me realise what was really going on.

@Bo98 Are you sure they weren't added at first and somehow removed in some kind of regression? I mean I'm all in for calling @Shigbeard a massive cunt, but he may still be innocent in this.

**Comment by FPtje** [comment]
Workshop is updated too.

**Comment by Bo98** [comment]
@FPtje #1014

His earlier PRs did include the `resource.AddFile` to be fair to him, before it all turned into a complete mess after trying to remove the copyright stuff.

**Comment by FPtje** [comment]
September 2013, fuck me post mortem

**Comment by Kefta** [comment]
"I DIDNT ADD THEM TO FAST-DL BY DEFAULT"

I guess he gave a fair warning.

**Comment by forumapp28** [comment]
Thanks. @FPtje

**Comment by forumapp28** [comment]
Thanks. @FPtje @Kefta @Bo98

**Comment by FPtje** [comment]
@Kefta I'll have to wait for another day to call him names. I also carry responsibility because I accepted and merged the pr. 

Three years though. The other bug posted today too must have been God damn ancient. How the fuck did you guys find two in one day!? 

The DarkRP issues page is pretty much dead in regards to actual bugs in DarkRP. I had come to the conclusion that DarkRP had become super stable software. Then these ancient as nekkid grandma bugs show up. Weird as an assfuck.

**Comment by Kefta** [comment]
@FPtje They're either extreme edge cases or just unnoticeable from how popular DarkRP is. Most people have the materials from downloading them from servers who manually FastDL or have the workshop content.

**Comment by Bo98** [comment]
Well if you download it from one server, it carries over to other servers. It's something we faced when making the big derma skin change in 2.5.0. So you just need to find one server that manually does resource.AddFile.

The issue is also only obvious if you are an admin of a server, since it is the give weapons panel that would display checkerboard textures. But it would also do the same for some other weapon addons so was probably largely ignored. Some addons would probably have the materials downloaded locally from somewhere anyway, be that from another server or from downloading the gamemode. I'm not sure what happens for the weapon switch menu HUD but the fact I don't remember probably means it wasn't obvious/noticeable.

**Comment by Bo98** [comment]
Though on the grandma bugs note, DarkRP issues has built a bit of a pattern of either being swarmed by a hundred people because something broke recently, otherwise nobody bothers to mention for the next 20 years. I remember crawling back through the old SVN a few times.

**Comment by Shigbeard** [comment]
Yo, bit late but yeah, my fault.

When I made the VGUI i didn't think to resource.AddFile them because we were talking about adding DarkRP to the workshop at the time. Hindsight, its 20 20

**Comment by Shigbeard** [comment]
Well actually its all a bit of a blur tbh. I remember there being some drama with an icon taken from HL2 that was a big no no, but eh.

**Comment by FPtje** [comment]
Even if `resource.AddFile`d files unnecessarily get re-downloaded on workshop DarkRP, that would still be better than players not getting the files at all on the non-workshop version.

We all should have realised that at the time.

**Comment by Shigbeard** [comment]
It's aight, I take full responsibility.

TBH the icons are pretty trash, although they are better than nothing.

**Comment by Bo98** [comment]
Well if they are trash, now's the time to fix them before we force everyone to download them. Though even then it's probably too late.

**Comment by FPtje** [comment]
The icons are fine.
