### ISSUE TITLE
DarkRP ignores spare ammo of weapons

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2604]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Weapon bug...

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
You got a weapon with 1 ammo and 1 reserve.
In front of you 10 stacked weapons are on the ground all with 1 ammo and 1 spare ammo.
Shoot 1 bullet away, however NOT the spare ammo.
Drop it onto the stacked weapons.
Now all weapons have 0 ammo and 0 spare ammo.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP Entity spawned_weapon

**Comment by FPtje** [comment]
Yup, they average it out amongst the weapons. Rounding can make ammo disappear.

**Comment by mcNuggets1** [comment]
Yeah, but spare ammo is still 1.
And it is gone completly.

**Comment by FPtje** [comment]
Rounding can make ammo disappear. 

for ALL weapons.

**Comment by mcNuggets1** [comment]
Ok, again.
We have 1 ammo shot away.
But still have 1 spare ammo FOR ALL weapons.
But all weapons have then 0 spare ammo.
That is indeed for no reason.

**Comment by mcNuggets1** [comment]
Even after all, if we pickup a weapon when we already got a weapon, which has clip1 full, we don't get the clip1.
You said sometime ago, weapons should be picked up to get ammo.

**Comment by FPtje** [comment]
> 1 spare ammo FOR ALL weapons.


> all weapons have then 0 spare ammo.

Do they have 1 spare ammo or 0 spare ammo? You're literally saying they have both 1 spare ammo and 0 spare ammo.

**Comment by mcNuggets1** [comment]
They have Clip 1 set to 0, but Clip2 aka spare ammo is still 1 on all weapons.

**Comment by FPtje** [comment]
here's the formula that calculates the ammos two (piles of) spawned weapons have when they merge:

```lua
local selfAmount, entAmount = self:Getamount(), ent:Getamount()
    local totalAmount = selfAmount + entAmount
    self.ammoadd, ent.ammoadd = self.ammoadd or 0, ent.ammoadd or 0

    -- ammoAdd will be the floored average of both weapons' ammoadd
    -- Some ammo might get lost there.
    self.ammoadd = math.floor((self.ammoadd * selfAmount + ent.ammoadd * entAmount) / totalAmount)

    -- If neither have a clip, use default clip, otherwise merge the two
    if self.clip1 or ent.clip1 then
        self.clip1 = math.floor(((self.clip1 or 0) * selfAmount + (ent.clip1 or 0) * entAmount) / totalAmount)
    end

    if self.clip2 or ent.clip2 then
        self.clip2 = math.floor(((self.clip2 or 0) * selfAmount + (ent.clip2 or 0) * entAmount) / totalAmount)
    end
```

What's wrong with this formula?

**Comment by mcNuggets1** [comment]
Ok follow my steps.

Take like an RPG from an shipment with 1 ammo and 1 spare ammo.
Shoot the shipment down.
Take one weapon.
Shoot the weapon, reload and put it back in there.

Means 10 clip1 and 9 clip2 should be in the weapons.
clip2 getting round means 0 per weapon.
clip1 however should have still 1 round in it.
But it hasnt.

Returning in 0 clip1 + clip2

**Comment by FPtje** [comment]
so you have a pile of 9 RPGs and one in your inventory. The 9 RPGs each have 1 bullet in Clip1, and 1 bullet of spare ammo (clip2 is the loaded *secondary* ammo, which normal RPGs don't have, so let's just call it spare ammo)

You shoot one rocket, reload, causing the one RPG in your hands to have 1 in clip1 and 0 in spare ammo.

You drop the RPG and merge it with the pile. The pile with have `floor((1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1) / 10) = 1` in Clip1, since every RPG in the pile, including the one you held in your hands, had 1 bullet in the clip.

The spare ammo of the clip looks as follows: `floor((1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1+ 0) / 10) = 0`. After all, you reloaded the one bullet of the RPG you had in your hands into clip1. `floor(9 / 10) = 0`. This makes perfect sense.

**Comment by mcNuggets1** [comment]
Why the player does not just get the clip1 which should be 1.
Why 0?
That does not make sense at all.

**Comment by FPtje** [comment]
I want every weapon in a stack of weapons to have the same amount of ammo and clip. Shit has to be averaged for that to work. Shit has to be rounded down to prevent ammo being created from nowhere.

**Comment by mcNuggets1** [comment]
I understand this, but making a weapon having 0 ammo, which apparently has 1 ammo is the wrong way to do this.
Atleast give the clip1-ammo.

Wouldnt make it that bit of a shitstorm.

**Comment by FPtje** [comment]
> making a weapon having 0 ammo, which apparently has 1 ammo

I fail to understand the meaning of this sentence. *Please* work on your English.

**Comment by mcNuggets1** [comment]
I meant every RPG for example have 1 ammo in clip1.
Why then remove the clip1-ammo.

That does not make sense and only create trouble.

**Comment by FPtje** [comment]
Where are you from anyway?

**Comment by mcNuggets1** [comment]
Germany. 
I am very sorry for my english, though.

I did not enjoy good education, but I try to improve myself.

**Comment by FPtje** [comment]
If you have trouble explaining something in English, you can try putting a German translation under it. The two texts under each other might make things easier to understand, as I speak some German.

You don't have to put entire posts in two languages, just the difficult bits. 

Thanks for trying to improve, by the way. Never stop learning.

**Comment by Shigbeard** [comment]
After skimming through some of this, may I suggest alternative, if not 
slightly heavier weapon stack behavior? Store ammo as arrays, with the 
last value in the arrays representing the first weapon you can take (so 
new guns added to the stack are added at the end of the arrays)

This way, when you dump a gun with no ammo into a stack of 9 weapons 
(that have 9 ammo all up), you would not be throwing 9 rounds into the 
void, however the unlucky player to take the first weapon would have no 
ammo to begin with.

This is just something to keep in mind, I'm not sure of how viable this 
would be when dealing with stacks that go beyond 100 (which sometimes 
happens on darkrp servers with questionable economies, where players 
that want a giant fuck-off base will often drag the server's gun dealer 
over to their base to buy several shipments of each gun, thinking "we 
will never have to buy another weapon again look how rich we are rofl 
lmao bbq").

**Comment by FPtje** [comment]
I have seriously considered exactly that, but like I said earlier, I want
ammo to be averaged out over the weapons.
