### ISSUE TITLE
Admintellall command

### ISSUE THREAD

**Issue by Srlion** [FPtje/DarkRP#2605]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
Admintellall command is not working and i don't get any errors or anything in console when i run the command.

### How to make the bug happen
When you run the command

### Lua errors
No errors are found in the console.

### Why the developer of DarkRP is responsible for this issue
Because it's not working?

[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
![2016-12-26_22-14-10](https://cloud.githubusercontent.com/assets/1202014/21486663/ad6dfe60-cbb8-11e6-8eb1-574f98e78b0c.jpg)
Cannot reproduce.

**Comment by Srlion** [comment]
It's not working for and i'm not getting any errors?

**Comment by FPtje** [comment]
I don't get any errors either.

**Comment by Srlion** [comment]
Any reason that can make it doesn't work for me?

**Comment by FPtje** [comment]
Unless you're lying, yes, there must necessarily be a reason. Check for conflicting addons, like HUDs n shit that prevent the `admintellall` thing from happening.

For further help, please see forum.darkrp.com, other server owners are more likely to have seen this problem before.

**Comment by Srlion** [comment]
Okay thanks, i'm gonna try to search in the files.
