### ISSUE TITLE
Wiremod forcers

### ISSUE THREAD

**Issue by ilm9001** [FPtje/DarkRP#2607]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Wiremod Forcers dont work.
This is not a fault with wiremod, its with darkrp.
This is a very old bug.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Get wiremod (If you dont already)
Spawn a forcer
Try and use it how it works.
(Like using a constant value to put the velocity or force to some number and try being infront of the forcer. it doesnt push you)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because Forcer works as intended in sandbox.
Its glitched in darkrp.

**Comment by FPtje** [comment]
You can only gravgun (and wire force) your own shit.

**Comment by ilm9001** [comment]
I am doing that.

**Comment by ilm9001** [comment]
Also wiremod forcers are intended to work with players too, they dont work even with your own props
because of darkrp

**Comment by FPtje** [comment]
You mean FPP?

**Comment by ilm9001** [comment]
Hmm. disabling FPP does remove the bug, How can i have FPP installed but without removing forcers abilities

**Comment by ilm9001** [comment]
nvm, i searched some other "issues" and disabling "People cant punt props" works.
