### ISSUE TITLE
Suggestion: ParentToHUD() on F1 Panel and F4 Menu

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2609]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Making the panel invisible when having the ESCAPE menu opened.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Not a bug, actually.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
f1 + f4 menu module

**Comment by FPtje** [comment]
Why?

**Comment by mcNuggets1** [comment]
Because F1 locks the whole screen.
So when you want to go to menu, you have to close f1 before.
