### ISSUE TITLE
Disconnecting in jail

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2610]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When disconnecting while in jail, and reconnecting, then there is a slight change you don't get teleported back to spawn.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Same as above.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None so far.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
police-module

**Comment by FPtje** [comment]
Well yes, you get re-arrested.

**Comment by mcNuggets1** [comment]
Yea, but after the timer has ran out, you don't get back to spawn.

**Comment by FPtje** [comment]
I'll check it out.

**Comment by FPtje** [comment]
Can they get out of jail by killing themselves?
