### ISSUE TITLE
Noclip when dead

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2611]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
You can noclip when dead.
Means the player changes position after death.
Makes things invisible when going through walls etc.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Die, press V.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP

**Comment by FPtje** [comment]
Noclip isn't a DarkRP thing.

**Comment by mcNuggets1** [comment]
There has been made a github commit to sandbox, which did fix this behaviour.
However not in DarkRP.

**Comment by FPtje** [comment]
DarkRP is based on sandbox. Link to commit.

**Comment by mcNuggets1** [comment]
Just tested, it is fixed in sandbox.
https://github.com/garrynewman/garrysmod/commit/c3b9ee16f01a99c9e51cd4732054f8497637a71f
