### ISSUE TITLE
Translationstrings missing

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2612]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Just some Translations problems.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
1. "any lab" can not be translated in "/setprice".
(Actually alot of things cannot be translated, like "argument" for example)
In sv_gamemode_functions line 30 to 36 none of these things are translateable.
2. (You cannot afford "INSERT HERE")-text lowercases "INSERT HERE" always for no real reason.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP-language strings missing

**Comment by mcNuggets1** [comment]
What about the can not buy-strings lowering case sensitive names

**Comment by Bo98** [comment]
Where specifically? That has nothing to do with the langauge string itself, but rather how names are used with it.

e.g. /buymoneyprinter should work fine.

**Comment by mcNuggets1** [comment]
Ah I see

**Comment by Bo98** [comment]
What part of "Dieser shipment ist nicht verfügbar!" is a lowercasing of the name? "SEXY UTE" doesn't even appear in that.

Or are you meaning /buyshipment only works if it is the proper case?

**Comment by mcNuggets1** [comment]
Shipment is actually written "Shipment".
That message just means "This shipment is not available."

**Comment by Bo98** [comment]
Ah, what you are seeing there is that DarkRP isn't using a translated string for "shipment": https://github.com/FPtje/DarkRP/blob/bff6c4d90eae6a640e83187d08c8b4c6f80f5d75/gamemode/modules/base/sv_purchasing.lua#L149

**Comment by mcNuggets1** [comment]
Could've known that.

**Comment by mcNuggets1** [comment]
In hungermod, when using /buyfood and failing for whatever reason the message does turn "Essen" to "essen", means "Food" to "food".

**Comment by Bo98** [comment]
Yes there is a few cases of the food string being lowercased. Microwave is the same.

**Comment by mcNuggets1** [comment]
Yeah I meant that actually :D

**Comment by Bo98** [comment]
Drugs is another one.

**Comment by FPtje** [comment]
Fucking Germans.

**Comment by Kefta** [comment]
First the world wars, now this

**Comment by mcNuggets1** [comment]
The first was not our fault, that were the austrians!

**Comment by FPtje** [comment]
I'm talking about nouns starting with a capital letter in German. That's fucking bullshit.

**Comment by mcNuggets1** [comment]
That is not just us. Alot of other countries actually have it the same way.

**Comment by Kefta** [comment]
@mcNuggets1 Maybe on an immediate level, but the agressive politique erected by Otto Von Bismarck played a significant role in the war

**Comment by FPtje** [comment]
@mcNuggets1 **Bullshit**

> The various languages and dialects in the High German family, including Standard German and Luxembourgish, are the only major languages using the Latin alphabet in which all nouns are generally capitalized.

https://en.wikipedia.org/wiki/Capitalization#Nouns

**Comment by FPtje** [comment]
![](https://i.ytimg.com/vi/H23Dsi--o4s/maxresdefault.jpg)

**Comment by mcNuggets1** [comment]
Well, yeah I guess, I don't really care and want to blame others rather than taking a thought about that.

**Comment by FPtje** [comment]
I'm not sure what criticism exactly you're giving me.

**Comment by mcNuggets1** [comment]
I did not want to critize anyone, I just wanted to say, that I actually did not google for it.

**Comment by FPtje** [comment]
Ah, that's okay. It gave me an excuse to post a picture of Karl Pilkington.

**Comment by MrBrax** [comment]
you really are the embodiment of the bullshit man aren't you? all these years of rubbish issue reports really tears one apart

**Comment by mcNuggets1** [comment]
Im not proud of it, atleast.

**Comment by FPtje** [comment]
@MrBrax Bullshit man has a real super power (besides super hearing and flying)

When he says it's bullshit, you know it's bullshit.

**Comment by MrBrax** [comment]
@FPtje True, and i guess i'm half a bullshit man.
![148354859426845](https://cloud.githubusercontent.com/assets/1517911/21650726/37e08db2-d2a6-11e6-995d-f03356236eb6.png)
![148354851695800](https://cloud.githubusercontent.com/assets/1517911/21650707/25ddadac-d2a6-11e6-8ec5-e2402dc03ff8.png)

**Comment by mcNuggets1** [comment]
What about the nonsense right here?

https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/hungermod/sv_hungermod.lua#L67

Also sorry for disturbing.

**Comment by FPtje** [comment]
You're not going to give me these shit nuggets one at a time are you?

**Comment by mcNuggets1** [comment]
I hate to be me

**Comment by FPtje** [comment]
Just asking, are there any more?

**Comment by mcNuggets1** [comment]
I don't think so.
Maybe there are.
I could not find anything in the last 3 minutes.
