### ISSUE TITLE
ParentToHUD broke F1-menu

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2613]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I don't know why it broke it, but it broke the functionality to scroll down in some situations.

Maybe keyboardinput or mouseinput needs to be set to enabled or somewhat.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Bo98** [comment]
Did you check if scrolling's broken on the F4 menu too?

**Comment by FPtje** [comment]
I reckon it isn't, because the input is only broken on the HTML part of the F1 menu. The command part can scroll fine
