### ISSUE TITLE
Tip jar for hobos

### ISSUE THREAD

**Issue by FPtje** [FPtje/DarkRP#2615]
A simple fucking tip jar. You can have like two or three. Press E on it to tip the owner. Money goes directly to the owner. No collecting bullshit. Pressing E on the jar as owner opens a menu to set the default amount.

Free to spawn. Obvious to have for hobo, but might make sense for citizen or even medic too.

Some usability things:

- [x] Press enter to confirm
- [x] It must be possible to immediately type a number after pressing E.
- [x] List of previous donations? One that updates live as people donate and maybe even type donated amounts.

**Comment by EstevanTH** [comment]
Hoi Falco!
I guess that this is a great idea, as I think that the part of roleplaying where citizens are meant to give a small amount of money to help them live is often forgotten.

Momo :heart:

**Comment by MrBrax** [comment]
is this a community request or something?

**Comment by FPtje** [comment]
My own idea, why?

**Comment by MrBrax** [comment]
just felt weird having it being posted here in issues publically

**Comment by FPtje** [comment]
It's so people can criticise the idea

**Comment by Shigbeard** [comment]
I certainly like the idea. It's much better than the current 
alternative, which involves using the money pot addon along with unusual 
invisible prop designs to create secure donation tins.

Honestly it could be suitable for any class.

**Comment by Codingale** [comment]
Of course there's the MoneyRequest feature which reminds me of this, and it'd save me from having to explain how to write an E2 to new people.

I like the idea, it'd be better than wiremod + moneypot pulse constantly trying collect money.

**Comment by Aka7tsu4** [comment]
yes, yes yes yes and yes! :)

**Comment by matiasg90** [comment]
Nice

**Comment by FPtje** [comment]
Some progress:

https://streamable.com/w6ky5

Still a lot to do

**Comment by FPtje** [comment]
I put a branch up with the beta version:

https://github.com/FPtje/DarkRP/tree/tipjar

Could you guys please test it and report any bugs? I'm sure you'll find some.

To @mcNuggets1 @Kefta @Shigbeard @Bo98: check it out! Thanks!

**Comment by mcNuggets1** [comment]
1. When dragging it around with the physgun the model stays behind, while the entity is moved to the defined position.
2. The way it spins around itself is fps-determinant. (It spins sometimes faster, sometimes slower)

**Comment by FPtje** [comment]
1. Shouldn't be happening, but try HEAD
2. It isn't, I tested it with a stopwatch. It does one turn in about 2.75 seconds, tested on 260, 20 and 10FPS
3. Maybe it shouldn't. Citizens at least can also benefit from it.
4. Yeah, I know. It gets filled up as more people donate, though.

**Comment by mcNuggets1** [comment]
1. It did happen the first time I spawned one on vanilla DarkRP.
2. I just looked in different directions and the thing became faster, I don't know actually.
3. Mkay. Drugs are bad.
4. It would look alot cooler if the empty space gets removed until it is actually needed.

**Comment by Bo98** [comment]
I have noticed that at certain angles, the draw function is called twice in a frame, thus causing variations in rotation speed. This double-draw is not limited to the tip jar entity, so it seems that using `FrameTime()` in an entity draw is currently unreliable.

**Comment by FPtje** [comment]
I've replaced FrameTime with SysTime.

**Comment by FPtje** [comment]
Merged with master. I'll leave it for a couple of days before workshipping it.

**Comment by MrBrax** [comment]
is really keeping generic entity names without prefixes a good idea anymore with the massive addon culture?

**Comment by FPtje** [comment]
eh

**Comment by fruitwasp** [comment]
I suggest `darkrp_tip_jar` just like the lawboard and cheque entities.

**Comment by FPtje** [comment]
Thank you for suggesting that which I honestly could have figured out from @MrBrax' comment.

**Comment by pab14567** [comment]
Not sure if you updated it or not the UI but why is the Menu so big ? Are there anymore features? 
Say being able to steal the money ?

**Comment by FPtje** [comment]
The UI shows all the past donations to the tip jar. Just have some people donate and see.

**Comment by pab14567** [comment]
Ah thank you :).

**Comment by Codingale** [comment]
Uh, our server seemingly doesn't remove the tipjars when people disconnect there are a lot of "Unknown" tip jars everywhere.

**Comment by FPtje** [comment]
That means there's a hook conflict. Check your addons.

**Comment by Codingale** [comment]
Hum, any ideas where to start? We recently upgraded DarkRP from a very old version.

**Comment by Kefta** [comment]
Try on fully vanilla. Then add back addons in groups.

**Comment by businessman-droid** [comment]
How do I make this a physgunable entities instead of just grav gun?
