### ISSUE TITLE
Darkrp Arrest stick will not work

### ISSUE THREAD

**Issue by russianmtf** [FPtje/DarkRP#2616]
### Description of the bug
Everytime someone on the server, trys to use the arrest stick, even when their is a Jailpos. It will never arrest anyone. 

### How to make the bug happen
unknown

### Lua errors: only get one error on the server
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file models/cire992/props4/chair_comfortable_02.mdl
mdlkeyvalue, 

### Why the developer of DarkRP is responsible for this issue
As the script sees to have a bug, and it is a script that I have no changed Darkrp it self, I feel like the bug was not caused by me, but the script it self or some other 3rd party

**Comment by Kefta** [comment]
Just want to note that the error you provided is unrelated

**Comment by FPtje** [comment]
Works for me.
