### ISSUE TITLE
Arrest Stick not working *repost*edited*

### ISSUE THREAD

**Issue by russianmtf** [FPtje/DarkRP#2617]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
Everytime someone on the server, trys to use the arrest stick, even when their is a Jailpos. It will never arrest anyone.

### How to make the bug happen
Unknown

### Lua errors
Everytime I or someone else hits a other play with the arrest stick, It gives them this in logs: 

Warning: Unhandled usermessage '_Notify'

That is the only message we get.

**Comment by Bo98** [comment]
That warning is just because you disabled the HUD module. Nothing to do with the arrest stick.

**Comment by russianmtf** [comment]
then why would I get the message when I arrest someone, Because it worked fine before.

**Comment by russianmtf** [comment]
Because when I force arrest someone, the Arrest message and everything works

**Comment by russianmtf** [comment]
if you want anymore info or logs, I can try my best to get it

**Comment by FPtje** [comment]
Go to Forum.darkrp.com.

**Comment by Bo98** [comment]
You get the message because it's trying to send you a notification why you can't arrest someone, but it can't since you disabled the HUD module.

**Comment by russianmtf** [comment]
I have fixed the problem
