### ISSUE TITLE
Gun license and weapon checker issue

### ISSUE THREAD

**Issue by Srlion** [FPtje/DarkRP#2619]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Gun licenses are only working when you spawn with gun license and weapons.
If you spawn with a gun license and get a weapon then someone weapon check you, they will get in chat you have illegal weapons.
I tested it on 3 servers.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Get a gun license then get a weapon then make someone weapon check you.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No Lua errrors.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Weapon checker is not working.

**Comment by EstevanTH** [comment]
Hi.
So you say that despite having a gun license (that comes with the job or not), you can be detected as having illegal weapons, that should be legal with your license.
But is it a bug? Is there a way to check if the checked player has a gun license?

**Comment by Srlion** [comment]
No, if you are a police officer or the mayor or any job and you have a license then you got a weapon then someone weapon check you, they will see in chat you have illegal weapons.

**Comment by FPtje** [comment]
The weapon checker doesn't check for *illegal* weapons, it checks for non-job weapons.

**Comment by Nocty1501** [comment]
> The weapon checker doesn't check for _illegal_ weapons, it checks for non-job weapons.

The weapon checker specifically uses language like "Has illegal weapons"/"Has no illegal weapons", and the config file specifically states "All weapons not exempt through `GM.NoLicense` or `GM.Config.noStripWeapons` will require a license".

Intentional or not, this is very bad phrasing. The weapon checker should either phrase this as "<target> has the following unlicensed weapons" or simply not display licensed weapons on targets with a license.

**Comment by FPtje** [comment]
That's a good point, though the weaponchecker does not check if sonroje has a license. I've changed the wording to remove the word "illegal". That should prevent the confusion.

**Comment by Nocty1501** [comment]
> That's a good point, though the weaponchecker does not check if sonroje has a license. I've changed the wording to remove the word "illegal". That should prevent the confusion.

Consider reworking `GM.Config.noStripWeapons` into something like `GM.Config.licensedWeapons` to allow for 3 categories of weapons:
1. `GM.NoLicense` weapons do not require a license
2. `GM.Config.licensedWeapons` are considered illegal unless owner has a license
3. All other weapons are considered illegal always, license or not

This would give the default weapon checker more helpful behavior and allow for the vanilla DarkRP gun license to be used in a more flexible manner (also clear up the weird ambiguity between `GM.NoLicense` and `GM.Config.noStripWeapons`).

**Comment by FPtje** [comment]
I don't think I should make such breaking changes at this point of DarkRP's age to be honest.
