### ISSUE TITLE
playerWalletChanged not called every time player's wallet changing

### ISSUE THREAD

**Issue by UAVXP** [FPtje/DarkRP#2627]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
"DarkRP setmoney" command doesn't call "playerWalletChanged" hook.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Type "DarkRP setmoney nick amount" in console.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No errors, just annoying behavior.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because playerWalletChanged should be called every time player's wallet is changing.

**Comment by FeelTheLemon** [comment]
Yep, that's not good.
