### ISSUE TITLE
Errors When Switching to 2.7.0

### ISSUE THREAD

**Issue by NebulaGraphics** [FPtje/DarkRP#2631]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
(Background information: I am a developer on a new MilitaryRP server, and we switched over to DarkRP version 2.7.0) Everytime anyone joins the server, the job is stuck at "Joining/Connecting", but frankly that's not the only thing wrong. After fixing some issues with the job from moving over, a LUA error appeared about the jobTable being a nil value every time I would press the binds associated with 'gm_showspare1 / 2', but the problem goes away when I switch back to the old version (2.6.0), but I need the newer version (2.7.0) for all the new fixes. And I have tried looking for the solution and nothing had come up. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
When I move over to the new version, All the errors arise. 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[ERROR] gamemodes/militaryrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)

  1. Call - gamemodes/militaryrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/militaryrp/gamemode/modules/base/cl_gamemode_functions.lua:62

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)   Clearly if moving over to the new version breaks the whole game, it has to be something conflicting with the code with the newer version, because issues like this have not arouse in the older version. 

[cl_gamemode_functions.lua.zip](https://github.com/FPtje/DarkRP/files/759899/cl_gamemode_functions.lua.zip)
[sv.dbfile.zip](https://github.com/FPtje/DarkRP/files/759895/sv.dbfile.zip)

**Comment by FPtje** [comment]
The only thing obvious to me is http://corefiles.darkrp.eu

**Comment by FPtje** [comment]
DarkRP is kept backwards compatible with older versions of itself and its API. Not with all possible edits people could have made to it. This is why I don't like people editing core files: they break it and then expect me to solve it.

**Comment by Kefta** [comment]
@FPtje Pretty interesting chord progression there

**Comment by FPtje** [comment]
Thank you!

**Comment by NebulaGraphics** [comment]
Unless the workshop version from the wiki is an un official version of DarkRP, but I have kept DarkRP as is and hadn't tampered with the name as I did just in case, instead I used the DerivedRP gamemode file that you provided to have a custom named gamemode. AND...........................same error, different place. 

`addons/darkrp/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)`

(the DarkRP addon is now located in the addons folder of the server)

So....like I said unless the workshop version is unofficial somehow, I think we can all see the problem isn't tampering with the base files. 

What now bb ;)?

**Comment by FPtje** [comment]
Now you're in a much better bargaining position. Still, that error seems to be the result of the gamemode or the player not loading properly. If it did load properly, an error would be thrown at `gamemode/modules/base/sh_createitems.lua` line 388.

I reckon there should be earlier errors.

**Comment by NebulaGraphics** [comment]
No such errors, but new errors popped up, about V92 Base not being loaded 
then a bunch of "missing textures" errors from the map
and then a few things will load, followed by errors from SCars
but hey THE ERROR STOPPED! Only because the DarkRP gamemode wouldn't launch all together, no errors in console either (strange)

Ok, strangely enough, the github version of DarkRP utterly broke everything. I made sure it was installed right and that the right version was installed, but the gamemode just became Sandbox with the  "MilitaryRP" name. So definitely something conflicting with the github version. 

After further research, turns out DarkRP would just delete for no reason out of the directory. 

340 Files left and I'll tell you if it does the same thing with the workshop version

**Comment by FPtje** [comment]
I'm willing to bet you're looking at the client console rather than the server console.

**Comment by NebulaGraphics** [comment]
Crisis semi-averted. DarkRP is back with the workshop version (strange :\ ) Same errors as before with the map

`Attemped to precache unknown particle system "impact_dirt_d"!
Attemped to precache unknown particle system "blood_impact_antlion_worker"!
Attemped to precache unknown particle system "Waterfall_base_01"!
Attemped to precache unknown particle system "rock_splash_02"!
Requesting 3 lua files from the server
Map file wasn't found, copying it from addon..
PREP OK
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_hanging_rugsa.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_inferno/fencewooden01.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_inferno/fencewooden03.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_inferno/fencewooden02.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_inferno/fencewooden03.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_hanging_rugsa.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_inferno/fencewooden02.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_canal/canalmap001.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_train/handrail_singlespan_128.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/de_dust/du_palm_tree01_skybx.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/cs_militia/light_outdoor_glass.mdl)
clientside lua startup!
Particles: Missing 'particles/impact_fx_fas.pcf'
Attemped to precache unknown particle system "impact_dirt_d"!
Attemped to precache unknown particle system "impact_dirt_d"!
`

Some successful loading of ULX and then more map errors 
`env_cubemap used on world geometry without rebuilding map. . ignoring: de_nuke/nukfloorb
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/prodventa
env_cubemap used on world geometry without rebuilding map. . ignoring: concrete/concretefloor019a_c17
env_cubemap used on world geometry without rebuilding map. . ignoring: de_chateau/wall04pnl
env_cubemap used on world geometry without rebuilding map. . ignoring: de_chateau/wall04pnl01
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/woodfloor01
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/drtrimb
env_cubemap used on world geometry without rebuilding map. . ignoring: de_chateau/floor01
env_cubemap used on world geometry without rebuilding map. . ignoring: de_nuke/nukfloora
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/marblefloor10
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/marblefloor08
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/marblefloor01
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/stairmarble01
env_cubemap used on world geometry without rebuilding map. . ignoring: de_chateau/chatcolumn01
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/metalwall076a
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/marblefloor14
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/marblefloor13
env_cubemap used on world geometry without rebuilding map. . ignoring: glass/glasswindowbreak070a
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/metalwall001a
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/metaldoor018a
env_cubemap used on world geometry without rebuilding map. . ignoring: props/metalduct001a
env_cubemap used on world geometry without rebuilding map. . ignoring: de_cbble/woodfloor01
env_cubemap used on world geometry without rebuilding map. . ignoring: props/mailboxwood01a
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/woodstair02
env_cubemap used on world geometry without rebuilding map. . ignoring: cs_assault/pavement001a
env_cubemap used on world geometry without rebuilding map. . ignoring: concrete/concretefloor028a
env_cubemap used on world geometry without rebuilding map. . ignoring: vehicle/metaltrain001a
env_cubemap used on world geometry without rebuilding map. . ignoring: cs_assault/pavement001
env_cubemap used on world geometry without rebuilding map. . ignoring: vehicle/metaltrain001d
env_cubemap used on world geometry without rebuilding map. . ignoring: vehicle/metaltrainglass001a
env_cubemap used on world geometry without rebuilding map. . ignoring: vehicle/rubbertrainfloor002a
env_cubemap used on world geometry without rebuilding map. . ignoring: tile/prodflra
env_cubemap used on world geometry without rebuilding map. . ignoring: de_piranesi/woodfloor02
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/metalwall001c
env_cubemap used on world geometry without rebuilding map. . ignoring: metal/metaldoor059a
env_cubemap used on world geometry without rebuilding map. . ignoring: concrete/concretefloor005a
`

Boots up to "Joining/Connecting" job just like last time , and everyone that joined did experience this shit. F4 menu still doesn't work, F3 as well, spitting the same errors.

```
[ERROR] addons/darkrp/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - addons/darkrp/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - addons/darkrp/gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62
```
RIGHT BACK WHERE WE STARTED. But if you have something to add, please do, I'll post any striking errors in the server console tomorrow.  I'll get a friend to copy and paste me the whole console because they all went to sleep. (don't ask why I have access to the FTP and not the console, it's the owner's logic and sometimes i feel like I'm the only logical one)If nothing shows up, I'll make sure to inform you.

Speaking of which ... just making sure, what titles can we change to change the name in the DerivedRP folder? Just for safety reasons

Sorry for the long post the map errors took up the most space

**Comment by Bo98** [comment]
The errors you are looking for are probably serverside, so looking for errors there is important.

**Comment by Bo98** [comment]
Something you could do without console access, is to add `lua_log_sv 1` to server.cfg, and then do what ever you did to reload (changelevel, restart etc.). The file `garrysmod/lua_errors_server.txt` should be created when a serverside error happens.

This theoretically should work but I haven't tried it. Or you can just wait until you get the console output, but many server hosts limit the number of lines shown, so you may need to be looking at the console when the server restarts/changes level.

**Comment by NebulaGraphics** [comment]
I'll add that then. Thanks

**Comment by NebulaGraphics** [comment]
Alright, on the server console, I found only one huge ass Darkrp error. 

`[ERROR] addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:102: attempt to call field 'ForAllSettings' (a nil value)
1. SendSettings - addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:102
2. onFinished - addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:298
3. commit - addons/darkrp/gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
4. RetrieveSettings - addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:297
5. onFinished - addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:937
6. commit - addons/darkrp/gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
7. Init - addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:931
8. fn - addons/darkrp/gamemodes/darkrp/gamemode/modules/fpp/sv_fpp.lua:41
9. Call - addons/ulib/lua/ulib/shared/hook.lua:179
10. callback - addons/darkrp/gamemodesTimer Failed! [Simple][@addons/darkrp/gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua (line 161)]`

Biggest error I've seen. Anyway, what now?

**Comment by NebulaGraphics** [comment]
```

[ERROR] addons/darkrpmodification-master_gmchosting/lua/darkrp_modules/tcb_hud_2/cl_main.lua:366: attempt to concatenate a nil value
  1. DrawPlayerInfo - addons/darkrpmodification-master_gmchosting/lua/darkrp_modules/tcb_hud_2/cl_main.lua:366
   2. DrawEntityDisplay - addons/darkrpmodification-master_gmchosting/lua/darkrp_modules/tcb_hud_2/cl_main.lua:424
    3. fn - addons/darkrpmodification-master_gmchosting/lua/darkrp_modules/tcb_hud_2/cl_main.lua:475
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

```

NEW ERROR WHEN COLLIDING WITH PLAYERS

**Comment by Shigbeard** [comment]
This error has nothing to do with darkrp, something called tcb_hud_2 is 
your culprit, looks as if its happening when it tries to draw the info  
for another player

**Comment by NebulaGraphics** [comment]
Yeah, I didn't pay much attention to the file path other than the "darkrp..." part, just gonna...delete that. But anyway I uninstalled all the add-ons, and it's working fine, so I guess one of my addons in not working with DarkRP, I'll figure out which and post it.
