### ISSUE TITLE
Tip Jars are not removed on player disconnect

### ISSUE THREAD

**Issue by roboderpy** [FPtje/DarkRP#2634]
### Description of the bug
[//]: # (Describe the issue as accurately as possible)
As title says.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Spawn a tip jar and disconnect.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
FPtje added tip jars

**Comment by FPtje** [comment]
I spawned a bot, had him get a tip jar and then kicked him. The bot and tip jar disappeared simultaneously.
