### ISSUE TITLE
Something has went horribly wrong.exe

### ISSUE THREAD

**Issue by russianmtf** [FPtje/DarkRP#2636]
### Description of the bug
It creates a Job called Joining/Connecting. It disables the use of chat and spawning in Items. 

### Lua errors
I think this is what the server is trying to tell me - 
[ERROR] gamemodes/starwarsrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
1. Call - gamemodes/starwarsrp/gamemode/modules/base/cl_gamemode_functions.lua:23
2. unknown - gamemodes/starwarsrp/gamemode/modules/base/cl_gamemode_functions.lua:62

### Why the developer of DarkRP is responsible for this issue
The Server is now having huge problems with this and I do not think I caused anything since my server has been fine for the past 2 months.

**Comment by roboderpy** [comment]
forum.darkrp.com

**Comment by Shigbeard** [comment]
/KindlyLearnToReadTheError.rar/

**Comment by russianmtf** [comment]
I fixed it myself, sometimes I feel like somedays I am dumb others I am not. Thanks for the support as a Indian scammer.
