### ISSUE TITLE
Weapon nil files

### ISSUE THREAD

**Issue by Duck17** [FPtje/DarkRP#2637]
So I came back today to find out the owner of the server was trying to contact me cause he messed something up. I have no idea what these lua errors are can you please help.  This is what pops up and I looked through the files and couldn't find anything

[ERROR] gamemodes/starwarsrp/entities/weapons/weapon_cs_base2/shared.lua:98: attempt to index global 'fn' (a nil value)
  1. SetupDataTables - gamemodes/starwarsrp/entities/weapons/weapon_cs_base2/shared.lua:98
   2. SetupDataTables - gamemodes/starwarsrp/entities/weapons/stick_base/shared.lua:56
    3. unknown - gamemodes/starwarsrp/entities/weapons/stunstick/shared.lua:44

**Comment by andreblue** [comment]
That is an issue with a addon, not darkrp.

**Comment by Kefta** [comment]
Reinstall the gamemode

**Comment by Duck17** [comment]
Ok thanks but the owner decided to redo the whole server without me knowing. So this isn't an issue anymore.
