### ISSUE TITLE
Food Table Network String Full

### ISSUE THREAD

**Issue by killerrichard** [FPtje/DarkRP#2639]
Hello, 
Sorry for disturbing you,
The darkrp seem to add.networkstring all the food and make a table nearly full,

### Description of the bug
I know i have too many addon but the table is full with the food added to darkrp
340: 'DarkRP_UpdateDoorData'
341: 'DarkRP_RemoveDoorData'
342: 'DarkRP_RemoveDoorVar'
343: 'DarkRP_AllDoorData'
344: 'DarkRP_simplerrError'
345: 'player_darkrp'
346: 'DarkRP_Chat'
347: 'DarkRP_preferredjobmodels'
348: 'DarkRP_preferredjobmodel'
349: 'DarkRP_InitializeVars'
350: 'DarkRP_PlayerVar'
351: 'DarkRP_PlayerVarRemoval'
352: 'DarkRP_DarkRPVarDisconnect'
1061: 'Bread'
1062: 'bread1'
1063: 'Ice Cream (Neapolitan)'
1064: 'icecream1b'
1065: 'Ladder (Small - Attached)'
1066: 'ladder_small2'
1067: 'Cookies'
1068: 'McDonalds Meal (Large)'
1069: 'mcdmeal'
1070: 'Soda (Mountain Dew)'
1087: 'Chips - Lays - Fight for your Flavour'
1088: 'chipslays8'
1089: 'Cooked Meat'
1090: 'meat8'
1091: 'Monster Khaos'
1092: 'sent_monsterorange'
1093: 'Chips - Fritos BarBQ Hoops'
1094: 'chipsfritoshoops'
1128: 'Chips - Doritos'
1129: 'chipsdoritos2'
1130: 'Orange Juice'
1131: 'orangejuice2'
1132: 'Chips - Cheez It'
1133: 'chipscheezit'
1134: 'Champagne (on plate)'
1135: 'champagne2'
1136: 'Marabou'
1137: 'marabou4'
1138: 'Banana (Bunch)'
1139: 'fruitbananabunch'

etc ....

### How to make the bug happen
Add food items to darkrp and check with **dumpstringtables_new networkstring**

### Lua errors
**Warning:  Table networkstring is full, can't add**

### Why the developer of DarkRP is responsible for this issue
I have checked the food addon and the addon have no code to make it add to networkstring table

Sorry for my english

Thanks

**Comment by Bo98** [comment]
I'm not aware of DarkRP adding network strings for food so it'll be some addon that is doing that.

The ordering of what gets added is suspicious: it looks like the display name of an entity is added followed by the class name. [This is something Assmod does.](https://github.com/slayer3032/assmod/blob/375ab15015ee0437528b4933939fd2c76d5ed604/lua/plugins/ass_sandbox_toollimit.lua#L72-L73)

So you'll either need to:
* Use a different admin mod.
* Try complain to the developer that this behaviour just breaks things for minimal benefit.
* Use less addons.

**Comment by killerrichard** [comment]
Assmod hmm possible, i check and i come back
Thanks you for your response :+1:

**Comment by killerrichard** [comment]
without assmod = 556
with assmod = 1794

test on server start

So you win Bo98

Thanks !!!!
