### ISSUE TITLE
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:218

### ISSUE THREAD

**Issue by brocc0li** [FPtje/DarkRP#2641]
### Description of the bug)

When i start the server i get errors spammed. There is no addons installed. 
I have also tried to reinstall garrys mod from steamcmd to another folder + reinstalled / validated gmod.

I have CSS and TF2 Mounted.
### How to make the bug happen

Starting the server with DarkRP Loaded.

### Lua errors

(full logg from start up)
http://pastebin.com/KYm1LZdi ( to much to put in this post)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Plain DarkRP installation. No Errors while using only Sandbox. Also tried google but sometimes google cant help.. There was allot of suggestions, but all of them sendt me back to here.

I am also running on a windows server 2016 if that can be the issue.

**Comment by Kefta** [comment]
Did you delete the base gamemode or parts of Sandbox?

**Comment by brocc0li** [comment]
Sandbox is not deleted. I have tried to rename sandbox to Sandbox as that was a suggestion from a forum. That did not fix it. Also it is a plain install, only thing added is darkrp. Nothing else is tutched.

**Comment by Kefta** [comment]
It seems your install is corrupted then. I just updated my local server and threw DarkRP on there with nothing else and no errors.

**Comment by FPtje** [comment]
Not a help forum
