### ISSUE TITLE
Multiple vehicles can't be registered under same entity

### ISSUE THREAD

**Issue by DerekSM** [FPtje/DarkRP#2642]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

If you try creating say two vehicles named "Jeep", only one will register.
However I need to do this as I am hooking into the onBought function callback to create seats for the jeep. One is a two seated Jeep the other is a four seater. Only the first registered will work.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

DarkRP.createVehicle( {
	name = "Jeep",
	model = "models/buggy.mdl",
	price = 7000,
	label = "Jeep - 2 Door",
	distance = 85,
        onBought = function( pl, tblEnt, ent )
        end
} )

DarkRP.createVehicle( {
	name = "Jeep",
	model = "models/buggy.mdl",
	price = 9000,
	label = "Jeep - 4 Door",
	distance = 85,
        onBought = function( pl, tblEnt, ent )
        end
} )

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Developers aren't meant to touch DarkRP core files. I can't add a new jeep without editing core files.

**Comment by FPtje** [comment]
![hl2_2017-03-01_20-18-19](https://cloud.githubusercontent.com/assets/1202014/23476843/53bfe87e-febc-11e6-936c-bc451b7e0228.png)

Looks like an issue of your F4 menu. Both vehicles show up for me.

**Comment by DerekSM** [comment]
They both show up but only one vehicle is affected by changes in the onBought function.

**Comment by FPtje** [comment]
In the next update you can enter a command for vehicles like so:

```lua

DarkRP.createVehicle({
    name = "Jeep",
    command = "jeep1",
    model = "models/buggy.mdl",
    price = 7000,
    label = "Jeep - 2 Door",
    distance = 85,
    onBought = function(pl, tblEnt, ent) end
})

DarkRP.createVehicle({
    name = "Jeep",
    command = "jeep2",
    model = "models/buggy.mdl",
    price = 9000,
    label = "Jeep - 4 Door",
    distance = 85,
    onBought = function(pl, tblEnt, ent) end
})
```

They'll be different.

**Comment by DerekSM** [comment]
Thank you this is exactly what I had in mind!
