### ISSUE TITLE
Separate spelled wrong in sh_createitems.lua :(

### ISSUE THREAD

**Issue by Hackcraft** [FPtje/DarkRP#2645]
### Description of the bug
[//]: My shipment code doesn't work, turns out it's a spelling mistake in the source. (511, 516, 518)

### How to make the bug happen
[//]: Create a shipment with separate spelled right.

### Lua errors
[//]: Shipment unavailable.

### Why the developer of DarkRP is responsible for this issue
[//]: It's spelled wrong which in turn caused a small headache for me as my shipment code wouldn't work :(

*EDIT*
I didn't see the part where it was fixed, guess there's another problem with the shipments then.

**Comment by Bo98** [comment]
Both "seperate" and "separate" should work: https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/base/sh_createitems.lua#L514-518
