### ISSUE TITLE
DarkRP setmoney broken: getDarkRPVar nil value

### ISSUE THREAD

**Issue by del-sys32** [FPtje/DarkRP#2646]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Title.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Attempt to set a players money using the command: DarkRP setmoney name amount in console.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/money/sv_money.lua:247: attempt to call method 'getDarkRPVar' (a nil value)
  1. callback - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:247
   2. fn - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/access/sh_shared.lua:194
    3. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
     4. PlayerHasAccess - addons/ulib-master/lua/ulib/shared/cami_global.lua:370
      5. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:43
       6. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:255
        7. unknown - lua/includes/modules/concommand.lua:54

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Brand new server, only has ulx and TDM cars. Server uses MySQL if thats important.

**Comment by roboderpy** [comment]
http://forum.darkrp.com

**Comment by FPtje** [comment]
I'm pretty sure some other error must be occurring. Please head to the forums.
