### ISSUE TITLE
Put a cap on how much food a player can spawn.

### ISSUE THREAD

**Issue by DerekSM** [FPtje/DarkRP#2648]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Players that spawn a bunch of food (like watermelons) will cause the net_graph to spike. There is no cap on how much food can be spawned. If a player spams this in an enclosed area the end result is lots of server lag with no reliable way to trace back to the player.

While some server owners can code and fix this behavior, I think it should be in base DarkRP as there's never a reason for a player to have 50 spawned foods at any given point.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Become cook job.
Spawn melons until you drop.

Fixes include either merging the same foods together like you do with money and shipments, or putting a hard cap on foods spawned.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Many server owners can't code, and this is a common sense sort of thing.

EDIT: Also when a player leaves the server they are no longer referenced anywhere to have owned the spawned food. A player could theoretically spawn a crapload of food, leave and have the server suffer with nobody knowing who did it.

**Comment by mcNuggets1** [comment]
There isn't a weapon/shipment limit either.
So I guess a food limit would be unnecessary.

**Comment by DerekSM** [comment]
True but weapons and shipments merge together.
