### ISSUE TITLE
Add third argument "order" to DarkRP.addF4MenuTab

### ISSUE THREAD

**Issue by DerekSM** [FPtje/DarkRP#2651]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

When creating a new F4 tab you can grab the index of the returned panel and switch it's order with another panel, but sometimes you don't want that and you instead just want to place the newly created panel into a certain spot.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

In modules/f4menu/cl_init.lua add third argument "order" to DarkRP.addF4MenuTab function.

In modules/f4menu/cl_frame.lua add 7th argument "order" to PANEL:AddSheet function

in the same function add a check if the "order" argument is supplied, if so do
   
               table.insert(self.Items, order, sheet)

In the call to self.tabScroller:AddPanel( sheet.Tab ), have a check for order, if so use this code:
		
                table.insert( self.tabScroller.Panels, order, sheet.Tab )
		sheet.Tab:SetParent( self.tabScroller.pnlCanvas )
		self.tabScroller:InvalidateLayout( true )

 lines 169 through 172 with

               function PANEL:createTab(name, panel, order)
                     local sheet, index = self:AddSheet(name, panel, nil, nil, nil, nil, order)
                     return index, sheet
               end

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

I'm sure a lot of developers would love to see this implemented.

**Comment by FPtje** [comment]
Can you make a pull request out of this?
