### ISSUE TITLE
Wont remove ammos after changed job?

### ISSUE THREAD

**Issue by takaqiao** [FPtje/DarkRP#2653]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # After players changed cps to another job,they still got cps' spawn ammo

### How to make the bug happen
[//]: # Become a job with free ammos then switch to another

### Lua errors
[//]: # No Lua errors

### Why the developer of DarkRP is responsible for this issue
[//]: # It should be remove after changing the job :)

**Comment by FPtje** [comment]
It shouldn't. It's hard to keep track of which ammo was spawned with and which ammo was bought. Even then it's even more difficult to program this in a way that can be understood.
