### ISSUE TITLE
Fadmin and FPP causing errors

### ISSUE THREAD

**Issue by chxrlie** [FPtje/DarkRP#2655]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Disabling Fadmin and enabling fpp through the darkrp modification prevents certain entities such as custom printers from being able to be damaged.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Disable Fadmin and enable fpp through the darkrp modification addon.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

> [ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:526: attempt to index field 'Access' (a nil value)
>   1. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:526
>    2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The error seems to come from within the darkrp gamemode itself.
> [ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:526

**Comment by FPtje** [comment]
I've disabled FAdmin, spawned a printer and shot it a few times. It exploded and I had no errors. 

I think some addon is defining `FAdmin` to be an empty table. DarkRP isn't doing it.
