### ISSUE TITLE
DarkRP Base Modules > jobTable Nil

### ISSUE THREAD

**Issue by blizzard2023** [FPtje/DarkRP#2656]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
So when you join the server, you spawn in as unassigned. At first, I did not see any errors. However, as I peeked into console, I saw the following error:

[ERROR] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

^ The above error also gets flipped around in the middle of the server running to sv_gamemode_functions.lua as well.

I have asked several lua-knowing friends to take a look, and they cannot figure out what is wrong with it. Although, one friend said that jobTable was returning as nil.... yet I have no idea as to how or why.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Just start up the server.... I put a fresh installation of DarkRP and DarkRP Modification Master, yet it is still doing it. 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I believe that the developer of DarkRP may be responsible for this issue due to how it is produced. I have completely replaced both the darkrpmodification-master and darkrp folders entirely, yet it still gives me the error.

ALSO: I would like to note that I am NOT the only one who has had this issue: 
https://github.com/FPtje/DarkRP/issues/2641
https://github.com/FPtje/DarkRP/issues/2510
https://github.com/FPtje/DarkRP/issues/2461
https://github.com/FPtje/DarkRP/issues/2331

Pre-Answered Questions:

Q: Who is my host?
A: SoYouStart (OVH) > Linux Game Server Managers

Q: Operating System?
A: Ubuntu Linux - 16.10

**Comment by roboderpy** [comment]
Lets play a game named `Look for earlier errors`. @FPtje you should just block server from start when owner fuckup configs. It would block stupid reports i think

**Comment by blizzard2023** [comment]
I am doing that now, it has something to do with ULX... closing the issue now.
