### ISSUE TITLE
SeizeReward (Suggestion)

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2657]
I would suggest adding a possibility to return the SeizeReward as function instead of a var.

**Comment by FPtje** [comment]
Why

**Comment by mcNuggets1** [comment]
I simply want to change the seize reward likely every second of an entity.
With a function I wouldnt need to override SeizeReward every second.

**Comment by FPtje** [comment]
Can you think of a reason why this should be a function, but not any of the other variables? Think of `StickColor`, fire delay, all that shit.

**Comment by fruitwasp** [comment]
Hook call like `lockpickTime` perhaps?

**Comment by mcNuggets1** [comment]
SeizeReward is called only one time and can easily function as var and function at the same time.

When the SeizeReward needs to change for example very often, because someone wants to make a more complex entity it would be useful not to change the seizereward every milisecond in a think hook, rather just creating a function which does all the checks when they are needed to be called.

**Comment by FPtje** [comment]
Why would you change it in a think hook every millisecond? Can't you set it when it changes? Can't you override `DoAttack` and set it there before calling the original?

**Comment by mcNuggets1** [comment]
That would require me to literally reinitialize the SeizeReward in every function it changes.
That would make my code just unclean.

**Comment by FPtje** [comment]
I understand that you want this thing specifically, but your question is more generic than `SeizeReward` alone. `SeizeReward` is just some SWEP variable, like *many*, *many* others. I hope you see that creating a hook or function for every single one of them would be insanity. I could provide a hook or function for this, but how would I know someone else wouldn't ask for stick colour next week?

Also, your code isn't unclean when you override DoAttack or roll your own sticks.

**Comment by mcNuggets1** [comment]
SeizeReward is quite often used and a main core element of the gamemode.
Well, on my server atleast. It literally forces cps to destroy illegal entities, rather than keeping them or gifting them back to their owners.

SeizeReward usually does not exist for entities without the var on it.

The code just checks if it exists and then give the cp who destroyed the entity the specified money.
A quick check if Entity.SeizeReward would exist as function, rather than als var would be very easy to implement and would not hurt anyone.
It actually might come in handy for a few more people besides me.
I guess more people wanna influence the SeizeReward than people trying to change the color of a stick,

**Comment by Shigbeard** [comment]
I actually agree with nugget here, it makes sense to have SeizeReward as 
a function, if only to better manipulate the SeizeReward in certain 
circumstances, for instance if you want to alter the reward for seizing 
a wanted player's illegal goods over someone who isnt wanted, or give 
the police chief a greater reward, or you want to alter the reward based 
on the contents of the entity (think a money printer with $500,000 in it 
as opposed to a money printer with $500 in it).

I can see the desire to leave it as is based on the fact that some 
people may see this as justification for any old variable to become a 
function, but you need to look at them as they come, and not deny them 
based off of what could happen if you accept them, because that's like 
saying I won't go to the beach because I might drown.

**Comment by Kefta** [comment]
What happened to the good 'ol accessor? Just leave SeizeReward as a variabl, and make a GetSeizeReward function that returns the variable by default.

**Comment by andreblue** [comment]
Why not simply have it also register the SeizeReward thru a system simalir to the way teams, ammos, and other such are added. Simply passing the entity class. Such as:
DarkRP.registerSeizeReward("wire_espression2", 2)

Then when seizing, it can be a simple look up on a table. Would not having too much more overhead.

**Comment by FPtje** [comment]
Wire expression 2?

**Comment by Kefta** [comment]
Maybe he means the entity class for the first arg

**Comment by andreblue** [comment]
Yes. It was the first entity name to pop into my head.

**Comment by FPtje** [comment]
Your arguments are valid, though I much prefer the `SeizeReward` being a function.

**Comment by Kefta** [comment]
The problem with that solution is now there's no documentation showing it can be a function. Which variables are functions and which aren't?
