### ISSUE TITLE
SetModel global problem (Pointshop and Custom functions)

### ISSUE THREAD

**Issue by McVipeR** [FPtje/DarkRP#2660]
Pointshop (SetModel trouble) conflict with lastest DarkRP version and my custom functions for setModel not working. (On DarkRP 2.4.3 all working perfect).

Example: If i use any playermodel in pointshop and rejoin to server then my custom playermodel not set. Gamemode set default job model or models. If i die or respawn Pointshop set my model to Custom.

And i have this problem with my custom functions.

Example 2:

function TestSetModel( ply )
timer.Simple(5, function()
ply:SetModel( "models/player/kleiner.mdl" )
end)
end
hook.Add( "PlayerSpawn", "TestSetModel", TestSetModel)

All troubles tested on clean server without addons, i use only clear DarkRP and Pointshop and Test lua with example 2, i trying use GM.Config.enforceplayermodel = false and this not helped.

**Comment by Kefta** [comment]
None of the recent DarkRP commits are related to this; are you sure this is not a Pointshop issue?

**Comment by Bo98** [comment]
Well recent in this case appears to be anything since 2013, considering it was 2.4.3 that was tested as working.

**Comment by FPtje** [comment]
DarkRP sets the model in `GM:PlayerSetModel`. Anyone who would use the hook would override DarkRP's decision for the player's model.

Try setting `GM.Config.enforceplayermodel = false` in settings.lua of the DarkRPMod and see what happens.

**Comment by FPtje** [comment]
I tested your script, I spawn as kleiner on initial spawn.
