### ISSUE TITLE
Using CreateMaterial() more than once in sticks (performance)

### ISSUE THREAD

**Issue by EstevanTH** [FPtje/DarkRP#2664]
### Description of the bug
Hoi Falco,
I just thought it would be a good idea to warn about the use of `CreateMaterial()` in `SWEP:Initialize` instead of once only at the top of the file. Checking if the material has already been created can be a good idea.

Maybe there's a good purpose for it though. Maybe it will not produce any lag either (possibly checked internally).

[entities/weapons/stick_base/shared.lua:45](https://github.com/FPtje/DarkRP/blob/master/entities/weapons/stick_base/shared.lua#L45)
```lua
    CreateMaterial("darkrp/" .. self:GetClass(), "VertexLitGeneric", {
        ["$basetexture"] = "models/debug/debugwhite",
        ["$surfaceprop"] = "metal",
        ["$envmap"] = "env_cubemap",
        ["$envmaptint"] = "[ .5 .5 .5 ]",
        ["$selfillum"] = 0,
        ["$model"] = 1
    }):SetVector("$color2", self.StickColor:ToVector())
```
[entities/weapons/stunstick/shared.lua:37](https://github.com/FPtje/DarkRP/blob/master/entities/weapons/stunstick/shared.lua#L37)
```lua
    CreateMaterial("darkrp/stunstick_beam", "UnlitGeneric", {
        ["$basetexture"] = "sprites/lgtning",
        ["$additive"] = 1
    })
```

### How to make the bug happen
No bug, just supposed tiny performance drop.

### Lua errors
No error.

### Why the developer of DarkRP is responsible for this issue
I believe that optimization belongs to the developer of the DarkRP sticks.

Good luck! :smile:

**Comment by Kefta** [comment]
The stunstick's can obviously just be thrown at the top of the file, but the batons' should be left to maintain compatibility with custom weapons that inherit from stick_base. The material can still be created only once, though, if a static table were to be used for weapon classes. Ex.

```
local sm_tPrecachedClasses = {}

function SWEP:Initialize()
   local sClass = self:GetClass()

   if (not sm_tPrecachedClasses[sClass]) then
      sm_tPrecachedClasses[sClass] = true
      -- Create the material here
   end
end
```

That will only create the material once per weapon class

**Comment by EstevanTH** [comment]
That is exactly what I would suggest. :smile:
