### ISSUE TITLE
F4 Key unbound out of nowhere.

### ISSUE THREAD

**Issue by MrEASlol** [FPtje/DarkRP#2666]
So i recently came across an issue with the gamemode thats made me unable to play on servers running it. Ive been playing gmod on Mac OSX with no real issues, especially on darkrp running servers. But out of the blue about a few days ago the key to open the job menu, which is F4 just unbound itself. Ive tried everything i can think to fix it, from the console command, to resetting keys in the keybinds to even reinstalling gmod. No luck, any ideas?

**Comment by FPtje** [comment]
I don't do key bindings. Gmod does.

**Comment by uRandomAlex** [comment]
@MrEASlol Try to enter "bind f4 gm_showspare2" in console.
