### ISSUE TITLE
getPrivateSetting (a nil value)

### ISSUE THREAD

**Issue by Hackcraft** [FPtje/DarkRP#2668]
This bug happened when it took ages to join a DarkRP server but upon re-joining the error went away.

### Lua errors
Error in hook HUDPaint: gamemodes/darkrp/gamemode/modules/fpp/pp/client/hud.lua:158: attempt to call field 'getPrivateSetting' (a nil value)
stack traceback:
	gamemodes/darkrp/gamemode/modules/fpp/pp/client/hud.lua:158: in function 'fn'
	addons/ulib-master/lua/ulib/shared/hook.lua:109: in function <addons/ulib-master/lua/ulib/shared/hook.lua:92>
	[C]: in function '‌⁪‎⁭​‬⁯‪‭'

[ERROR] 
  1. unknown - [C]:-1

### Why the developer of DarkRP is responsible for this issue
It's probably really rare and insignificant but I thought I'd post it anyway.

**Comment by FPtje** [comment]
Some files weren't loaded when you joined. That or the file that defines `FPP.getPrivateSetting` (which is `menu.lua` errored before the function was defined. Since the latter is *extremely* unlikely I'll assume the former explanation.
