### ISSUE TITLE
Spawning Glitch

### ISSUE THREAD

**Issue by emckinnoniv** [FPtje/DarkRP#2670]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: )

### Description of the bug
[//]: # This is a bug that is happening recently on my server. Randomly, when people die they will spawn in the wrong location and be completely stuck. The only way to get out is through FAdmin noclip (ULX noclip doesnt even work for it). There are no console errors at all, but it keeps happening at random points to players. This post shows someone else with the same issue:
https://facepunch.com/showthread.php?t=1547807&p=52151239#post52151239

### How to make the bug happen
[//]: # Dying or re spawning
[//]: # I can not find a fix, person has to rejoin the server in order to "fix"

### Lua errors
[//]: # There are no errors in console, which is the confusing part
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # Since there are no lua errors associated with my addons, and I have no idea what the problem is i am trying to see if DarkRP is the issue. I think it may have to do with the darkrp respawn mechanic and possibly spawnpoints. 
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by emckinnoniv** [comment]
An update to this issue, I decided to go to an older version of darkrp (2.6.1) and I have had no issues with this. So it is definitely a DarkRP 2.7 issue

**Comment by FPtje** [comment]
Do players have weapons when they're in this spawned stuck position?

**Comment by emckinnoniv** [comment]
they have weapons but they cant move and i dont think they can use them, i have been testing some things since getting the old version, and they broke again. We realized it was the arrest system. They broke right after setting the positions, and as soon as i removed them from the MySQL, the spawns fixed. I think there is a bug with the arrest points and spawning

**Comment by emckinnoniv** [comment]
And now they broke again, and this time once 1 person broke everyone started to. I am not sure what is causing it now, and yes you could use weapons while frozen

**Comment by FPtje** [comment]
Are the players spawn stuck inside something? Like a part of the world or a prop? Being able to use weapons but not being able to move sounds like a player getting stuck in some entity.

Are you sure it's not some minge placing invisible props in spawn?

**Comment by emckinnoniv** [comment]
it is as if they are stuck in something but nothing is there, and ulx noclip says that it cant be used at this time. It spawns them in a random previous location that they were at. and its not a minge the server hasnt been opened yet. we are currently testing it on my server and it breaks after killing each other for a while, and once it breaks it is broken until they retry

**Comment by emckinnoniv** [comment]
also it seems like if you die near someone that was broken your spawn breaks as well

**Comment by FPtje** [comment]
It's way, *way* more likely that some rogue addon is doing this than that DarkRP has had this problem since 2.6.1 and no one else noticed it. Sorry.

**Comment by Bo98** [comment]
> it is as if they are stuck in something but nothing is there, and ulx noclip says that it cant be used at this time.

Sounds like their move type is set to an odd state (e.g. `MOVETYPE_NONE`).

**Comment by emckinnoniv** [comment]
@Bo98 how would i fix that?

**Comment by josethe2nd** [comment]
any answers? @Bo98

**Comment by Bo98** [comment]
If it is exactly the same issue, then it is likely caused by a rogue addon.
