### ISSUE TITLE
Warning: Unhandled usermessage 'DRP_AddLaw'

### ISSUE THREAD

**Issue by speeeedy** [FPtje/DarkRP#2673]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

everytime I type /addlaw its make this error
Warning: Unhandled usermessage 'DRP_AddLaw'

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Did you disable the darkrp_laws module?

Do you have any Lua errors?

**Comment by speeeedy** [comment]
I dont have any lua errors, how can I check if I disable the darkrp_laws module? always when I type /addlaw its give a message that the law is added but its not, and give me instead a message in console 
Warning: Unhandled usermessage 'DRP_AddLaw'

**Comment by FPtje** [comment]
Oh wait, it's not a module. Derp.

Anyway, the code that handles the usermessage `DRP_AddLaw` is right there in entities/entities/darkrp_laws/cl_init.lua. I'm guessing you don't have that file for some vague reason. Please head to forum.darkrp.com.
