### ISSUE TITLE
Money is not awarded for killing Nextbot NPCS

### ISSUE THREAD

**Issue by glen7** [FPtje/DarkRP#2676]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When killing a Nextbot 2.0 NPC, money is not awarded to the player.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Kill a Nextbot 2.0 NPC.
Note: An example of Nextbot 2.0 NPCs http://steamcommunity.com/sharedfiles/filedetails/?id=380225333
Example: Nextbot 2.0 NPCs automatically spawn at the park, for example, on darkrp.republic.community | password: "g" (you can see that killing them there does not award money)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None that I see! Gamemode is not attempting to reward money because it perhaps does not recognize the entity of these types of NPCs.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Money being awarded for killing NPCs is a standard feature of DarkRP.

**Comment by Bo98** [comment]
Sounds like the addon doesn't call the `OnNPCKilled` hook. If it overrides `ENT:OnKilled` then it needs to either call the base method (`base_nextbot` already has the code to call the hook) or run the hook itself. The engine does not automatically call the hook on Nextbots.

I'm not sure if there's much that DarkRP can do about addons that don't do this.

**Comment by glen7** [comment]
Add code to DarkRP that recognizes that type of NPC getting killed?

**Comment by Kefta** [comment]
There is no way with default functionality to tell when a nextbot has been killed -- it is up to the addon creator to call the proper hook for it to be registered.

**Comment by FPtje** [comment]
I could check whether the classname is part of the NPC list, but that feels like a hack. Seems like the right choice is indeed to hand over responsibility for this to the addon authors.
