### ISSUE TITLE
TargetID still draws on known existent players or dead players in some cases

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2678]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Using player.GetAll() to draw the TargetID's of players is pretty unreliable.
Returns in drawing TargetID's of players, which are already dead/respawned or the drawing of TargetID's on places where a player previously was.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Have a server.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP HUD

**Comment by FPtje** [comment]
Should I make TargetID draw for known *non*-existent players?

**Comment by FPtje** [comment]
Oh, now I see what you mean. That happens when a client doesn't know where a certain player is. It has nothing to do with using `player.GetAll()`, and everything to do with the Potentially Visible Set, or PVS. At a certain distance players just don't get networked.

**Comment by Kefta** [comment]
Maybe only draw it for players in the local player's PVS?

**Comment by FPtje** [comment]
Is there a function to find out whether a player is in pvs? I looked for
pvs and networked on the wiki, but couldn't find anything.

**Comment by mcNuggets1** [comment]
Maybe to a traceline.

**Comment by roboderpy** [comment]
Do you **really** that care about this?

**Comment by Kefta** [comment]
http://wiki.garrysmod.com/page/ents/FindInPVS or you can test each player on the client with IsDormant.

@mcnuggets1 PVS is tested in five dimensions, a traceline won't work

**Comment by roboderpy** [comment]
This function is serverside only and using it will cause useless network load and unwanted server CPU usage. why

**Comment by FPtje** [comment]
IsDormant exists clientside

**Comment by roboderpy** [comment]
A thing - players are always networked, but when they are outside of PVS their data is sent every ~3 seconds instead of every frame

**Comment by Kefta** [comment]
No, dormant players aren't networked at all.

**Comment by roboderpy** [comment]
When i was making DMaps i found that players outside of PVS are updated very slowly. Updates includes health/mah health/armor/position and other stuff

**Comment by Kefta** [comment]
Then that's a bug -- no updates should ever be sent.

**Comment by mcNuggets1** [comment]
Theoretically if player positions are not updated (or updated every 3 seconds) there is still a invisible player having a TargetID above their head.

If there is no REAL player body, a trace line would work.

**Comment by roboderpy** [comment]
If player would not update, player's "ghost" that is described by this issue would stay forever. Alive() function updates instantly, despite of PVS.

**Comment by mcNuggets1** [comment]
Is there a function preventing networking of players?

I could test a few things if it would exist.

**Comment by Kefta** [comment]
http://wiki.garrysmod.com/page/Entity/SetPreventTransmit
