### ISSUE TITLE
DarkRP gamemode error, jobtable and other things.

### ISSUE THREAD

**Issue by Rannddy** [FPtje/DarkRP#2679]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # Alright, so I'm getting a bug with the game mode. My server host (GMCHosting) has the option to install your game mode for you. Except, it installs DarkRP 2.6.0. I want the latest version, so when I install the latest game mode, I get these errors.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[ERROR] addons/rubidium/lua/rubidium/task_manager/main.lua:10: attempt to index a string value with bad key ('action' is not part of the string library)
1. error - [C]:-1
2. __index - lua/includes/extensions/string.lua:297
3. callback - addons/rubidium/lua/rubidium/task_manager/main.lua:10
4. unknown - addons/rubidium/lua/rubidium/storage_drivers/api.lua:49

[Rubidium] Processing task: status

[ERROR] addons/rubidium/lua/rubidium/task_manager/main.lua:10: attempt to index a string value with bad key ('action' is not part of the string library)
1. error - [C]:-1
2. __index - lua/includes/extensions/string.lua:297
3. callback - addons/rubidium/lua/rubidium/task_manager/main.lua:10
4. unknown - addons/rubidium/lua/rubidium/storage_drivers/api.lua:49

ServerLog: [FAdmin] Randy (STEAM_0:1:109705481) is Authed

[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:102: attempt to call field 'ForAllSettings' (a nil value)
1. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:102
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:606: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:606

ServerLog: [FAdmin] Randy (STEAM_0:1:109705481) Spawned

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:729: attempt to index local 'jobTable' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:729

[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:228: attempt to call field 'calculatePlayerPrivilege' (a nil value)
1. recalculateCanTouch - gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:228
2. unknown - gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua:500

Timer Failed! [FPP_recalculate_cantouch_3][@gamemodes/darkrp/gamemode/modules/fpp/pp/server/ownability.lua (line 499)]
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Rannddy** [comment]
Also getting this error: 
[DarkRP] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

**Comment by Rannddy** [comment]
When I open the F4 menu^^^

**Comment by Kefta** [comment]
Your rubidium addon is causing all of those errors

**Comment by roboderpy** [comment]
Someone is still trying to get help on bug tracker.
## (How big should be this link?)[http://forum.darkrp.com]

**Comment by Rannddy** [comment]
I have my jobs, categories, entities, and ammo all working. Just I start as unassigned.

**Comment by Rannddy** [comment]
I deleted my rubidium addon, testing if that was the cause.

**Comment by Rannddy** [comment]
It was not the cause, it's still happening.

**Comment by Kefta** [comment]
This does not happen with a fully vanilla DarkRP server, which means one of your addons or code modifications is causing the issue.

**Comment by FroztbiteKing** [comment]
Oh you are so wrong. I have a fully vanilla DarkRP server, attempted to reinstall clearly everything possible with no addons, only DarkRp and Darkrpmodification.
I have an error gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:112 and also jobTable issues. Players spawn with no job and in a weird spawnpoint stuck in the floor.

**Comment by Kefta** [comment]
Then you must have errors with your custom jobs or a similar file, even from DRP modification.

**Comment by Bo98** [comment]
Look for the first error, not the last.

**Comment by FroztbiteKing** [comment]
False alarm.. Fixed this error disabling "fadmin" in disabled_defaults with ULX installed.-

**Comment by Kefta** [comment]
So it wasn't fully vanilla..
