### ISSUE TITLE
DarkRP Sticks

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2682]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
You can hit not solid players with the sticks from DarkRP.
There is no working solution for doing it otherwise.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
I don't think the lack of solidity makes players immune to bullets either.

**Comment by mcNuggets1** [comment]
Eh actually it does.

**Comment by FPtje** [comment]
I don't know what problem you have, but I'm sure as anus it's not you
running `ply:SetSolid(SOLID_NONE)` on a player just to try the damn
stunstick on them. Explain your problem properly. Give me some context.
What is happening and why is the current behaviour a problem? I don't want
to guess that shit from this bad a description.

**Comment by mcNuggets1** [comment]
I am sorry, I don't know how to explain my situation properly.

When using SetNotSolid on players, they can still be arrested etc. but not getting shot.

I am ragdolling players and keep their player entities frozen.
But unfortunately they can be arrested.

**Comment by FPtje** [comment]
That's precisely the information I need, though. By telling me that you're trying to ragdoll players you show that this is a practical problem. By mentioning `SetNotSolid`, you give me a precise means to reproduce. There are, after all, [several](https://wiki.garrysmod.com/page/Special:Search?search=Solid&fulltext=Search) solid related functions and enumerations, not all of which have the same effect.

This I can work with. Thank you.
