### ISSUE TITLE
DarkRPFinishedLoading Hook Not Running

### ISSUE THREAD

**Issue by andreblue** [FPtje/DarkRP#2684]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The [DarkRPFinishedLoading](http://wiki.darkrp.com/index.php/Hooks/Shared/DarkRPFinishedLoading) hook does not run. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
```lua
print "Adding Hook For Loading"
hook.Add( "DarkRPFinishedLoading", "Test DarkRP Loaded Hook", function()
    MsgN("DarkRPFinishedLoading: ")
end)
print "After Hook For Loading"
```

Using the above code, I get the "Adding Hook For Loading" and "After Hook For Loading" in the console. It was in a shared autorun file. 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
You are supposed to run the hook, but something is making it hide. I think it is shy.

**Comment by Kefta** [comment]
It's because addon lua code is ran after gamemode initialisation PostGamemodeLoaded also won't be called before your code begins running.
