### ISSUE TITLE
Crash client Since the last update of gmod

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2686]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # Since the last update of gmod, users have complained that they close the game when opening the hitman menu. (Open 2 times fast)

### How to make the bug happen
[//]: # Force client to use gmod_mcore_test 1
With many people online, open more than 2 times the menu of a hitman
Crash client

**Comment by Kefta** [comment]
This is not a DarkRP issue, nor should you be forcing players to use gmod_mcore_test. That's why its convar help text says: "- if you find this, don't go around enabling it and then complaining about issues"

**Comment by matiasg90** [comment]
If I know perfectly, I have other servers with other gamemode and there are no problems. Anyway thanks for the clarification.
I'm going to collect my clients' logs

**Comment by Kefta** [comment]
DarkRP may be using an element that is an issue for some multicore clients that you wouldn't see on other gamemodes, but again, the problem is multicore, not DarkRP.
