### ISSUE TITLE
Make entities spawnable

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2687]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

Suggestion:
Add the gun lab, drug lab, buyable food, microwave available for spawning in the entities tab of the spawn menu.

It would come in handy as you cannot spawn any healing entities as admin otherwise.

**Comment by FPtje** [comment]
Fuck no. Start roleplaying instead of administrating your way out of every situation.

**Comment by mcNuggets1** [comment]
Wait, what?
We can spawn weapons already. So should we remove that, just because it could be abused?
It does not make sense forbidding admins to spawn entities.
I never said, I am administrating me out of anything, I want to spawn them, because of fun, when the server is empty for example.

You can restrict spawning of entities in config, there is no reason to not include main entities of darkrp in the spawnmenu, besides admins abusing it, what they already can by just spawning them via ulx.

**Comment by mcNuggets1** [comment]
For the modifying part:
it is not possible to include the entities in the spawnmenu without overriding the wohle entitiy, which is ridicolous stupid in my opinion. (For future updates etc.)

**Comment by FPtje** [comment]
Actual, removing the weapons from the spawn menu is a good idea. They don't belong there.

**Comment by mcNuggets1** [comment]
I shouldn't give you bad ideas.

There is a config option for spawning weapons/entities, there is no sense in keeping them, when there is no weapon or entity.

**Comment by FPtje** [comment]
Naturally then the config option would go too

**Comment by Kefta** [comment]
You can just add them to the spawnmenu yourself..

**Comment by mcNuggets1** [comment]
HOW?

**Comment by Kefta** [comment]
You can use weapons/scripted_ents.GetStored and change the Spawnable key to true. You might have to re-call the PopulateEntities hook.

**Comment by mcNuggets1** [comment]
I actually am doing this right now, but I don't like the way it's done.
