### ISSUE TITLE
Index local 'jobTable' (a nil value)

### ISSUE THREAD

**Issue by LynxYT** [FPtje/DarkRP#2689]
### Description of the bug
You spawn as a Gray manikin, can't use ULX, can't buy anything.

### How to make the bug happen
Running a new version of DarkRP... and using serenity servers

### Lua errors
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:715: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:715

### Why the developer of DarkRP is responsible for this issue
It's a complete new version.

**Comment by roboderpy** [comment]
https://github.com/FPtje/DarkRP/issues?q=is%3Aissue+jobTable+is%3Aclosed

**Comment by Shigbeard** [comment]
Its as if reading isn't a requirement for DarkRP installation!

**Comment by FPtje** [comment]
It's not even the latest DarkRP.
