### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by masterdoom1001** [FPtje/DarkRP#2690]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Everytime I start the server, there's a LUA problem.
Also reinstalled the gamemode two times.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/cl_init.lua" on line 54.
The best help I can give you is this:

Invalid DarkRP method stub! Field "parameters" is invalid!

Hints:
	- No hints, sorry.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/gamemode/cl_init.lua on line 54
------- End of Simplerr error -------

### Why the developer of DarkRP is responsible for this issue
Because it's in the gamemode itself, not the darkrpmodification
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Verusae** [comment]
I got the same issue been looking online and over the files I cant find a fix

**Comment by jazzar1** [comment]
I have the same issue just this morning. I replicated the above issue by creating a new Garry's Mod server with SRCDS, then using the GitHub version of DarkRP with no other addons installed. I receive the exact same error described as well.

**Comment by Verusae** [comment]
Yeah it seems to just be darkrp

**Comment by FPtje** [comment]
My bad, try the latest version. It's untested, though, will test later

**Comment by Verusae** [comment]
I'' give it a test for you now

**Comment by Verusae** [comment]
Works fine now thanks so much :D
