### ISSUE TITLE
Lockdown Start and End Hooks

### ISSUE THREAD

**Issue by 51italian** [FPtje/DarkRP#2691]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
While DarkRP has hooks for commands like lottery with the lotteryStarted and lotteryEnded hooks, it doesn't have any for lockdown and unlockdown which makes it difficult to use the lockdown as a trigger for certain events without messy solutions.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
[Check the DarkRP wiki](http://wiki.darkrp.com/index.php/Category:Hooks) and watch a lockdown hook not appear.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I don't mean to be rude or presumptuous and I hope I'm not completely wrong, but it would be nice to use hooks rather than attempt to override the functions and chat commands of a core darkrp module (police module).

**Comment by FPtje** [comment]
A hook can be made for every chat command. Lockdowns start and end with chat commands, so it's best to override the commands. That way you have the freedom to do stuff right before the lockdown starts, right after the lockdown starts or likewise with the lockdown ending.
