### ISSUE TITLE
Doors Don't save.

### ISSUE THREAD

**Issue by Afronaut1** [FPtje/DarkRP#2694]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # I've seen so many threads about this but i have the LATEST version of darkrp, to clarify, ive spammed the update button numerous times just to be sure but when i set a door to unownable or to cops and mayor only they reset upon restart of the server. I've tried everything and i'm fresh out of ideas.

**Comment by strideynet** [comment]
Please use the following template when reporting issues:

Description of the bug
How to make the bug happen
Lua errors
Why the developer of DarkRP is responsible for this issue

**Comment by FPtje** [comment]
Not a help forum
