### ISSUE TITLE
Sometimes weapons are not thrown away

### ISSUE THREAD

**Issue by Anteik** [FPtje/DarkRP#2695]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Periodically, when you enter / drop the weapon is not thrown away and gives out to the user that he can not throw it away, but sometimes everything is fine. Works on all weapons
This problem occurs for all players at the same time.
I reinstalled the gamemode, but it did not help
### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Take the weapon in your hand and enter / drop and then as lucky

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Logs are clean

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The problem is even with the weapon from DarkRP

**Comment by FPtje** [comment]
The dropping of some weapons is restricted

**Comment by Anteik** [comment]
But they can be thrown out, and sometimes not. I checked the configuration and everything is correctly configured there.
The problem in this test:
`    local canDrop = hook.Call("canDropWeapon", GAMEMODE, ply, ent)
    if not canDrop then
        DarkRP.notify(ply, 1, 4, DarkRP.getPhrase("cannot_drop_weapon"))
        return ""
    end`

**Comment by FPtje** [comment]
Well then clearly some hook is doing it.

**Comment by FPtje** [comment]
Check your addons
