### ISSUE TITLE
Add a canBuyFood hook

### ISSUE THREAD

**Issue by MelonShooter** [FPtje/DarkRP#2697]
### Description of the bug
canBuyFood hook
### How to make the bug happen
Not a bug, but would like this.
### Lua errors
None
### Why the developer of DarkRP is responsible for this issue
Because the developer of DarkRP is the only person to add it for everyone to use

**Comment by Gyaviste** [comment]
But you can add it by yourself and make PR

**Comment by FPtje** [comment]
Sorry for responding this late. 

One can justify adding hooks for *any* chat/DarkRP command, whether it be `pm`, `canBuyFood`, `afk` or `lottery`. One can imagine having genuine reasons for having hooks before and after those commands.

I just decided to implement this when I found that it was already there:

http://wiki.darkrp.com/index.php/Hooks/Server/canChatCommand

You can use that. Return `false` there to deny the player from buying food.
