### ISSUE TITLE
Cant see who can reach in chat.

### ISSUE THREAD

**Issue by Gpatch** [FPtje/DarkRP#2698]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

![capture](https://user-images.githubusercontent.com/31012520/29283218-60dac200-812e-11e7-9236-f241ce6c04a0.PNG)

 Description of the bug
 So when i open chat box on my darkrp server i cant see green or red sentence above the chat box saying like "Nobody can hear you talk ". And there are no errors. Any ideas what causes this problem?

**Comment by FPtje** [comment]
Not a help forum
