### ISSUE TITLE
remove module calls

### ISSUE THREAD

**Issue by meepdarknessmeep** [FPtje/DarkRP#2702]
remove module

module is BAD and DEPRECATED

**Comment by meepdarknessmeep** [comment]
for instance https://github.com/FPtje/DarkRP/blob/353dc3286092cdb2efade2cc0f2145db5a6c2e69/gamemode/libraries/simplerr.lua#L344

**Comment by FPtje** [comment]
I'll consider not using it again

**Comment by Kefta** [comment]
nice
