### ISSUE TITLE
Make PlayerNoClip shared

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2706]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The PlayerNoClip hook is serverside, which it shouldnt be.
playeractions/noclip/sv_init.lua line 71.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
It's not really a bug, just a anomaly.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
%

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
%

**Comment by Bo98** [comment]
also in jail/sv_init.lua

**Comment by mcNuggets1** [comment]
Hey, thanks falco :D
