### ISSUE TITLE
No entities ownable

### ISSUE THREAD

**Issue by Quantum2707** [FPtje/DarkRP#2708]
Dear FPtje,

I have a "huge" problem :
Since I installed DarkRP seats weren't ownable and cars arent after i bought some addons so I think something at the darkrpmodification or darkrp itself is broken can you give me a advice how to fix this issue?

Best regards,

**Comment by mcNuggets1** [comment]
You bought addons.
Then DarkRP broke.
Please, find the solution yourself, rather than searching for help.

**Comment by Quantum2707** [comment]
This happened from the beggining! So it was broke while I had no addons on it.

**Comment by mcNuggets1** [comment]
Then why is it working for me?

**Comment by Quantum2707** [comment]
I dont know, I saw this in every video from beginning but I haven't had it. Even with no addons.

**Comment by Quantum2707** [comment]
Could you just give me the file path and function line number i will program something for myself If you are not willed to help me otherwise.

**Comment by mcNuggets1** [comment]
What video?
What are you talking about?
Remove all your addons and redownload DarkRP.
Then you will see, magically it will work.

**Comment by Quantum2707** [comment]
I watched setup videos for proofing it for me that I've done all correctly.

**Comment by mcNuggets1** [comment]
But you didnt do it correctly, apparently.

**Comment by Quantum2707** [comment]
Ya I think I should do that but if it doesn't I will text you again ._.

**Comment by mcNuggets1** [comment]
I am not your mentor, just go on and close the issue as it is not an issue with DarkRP.

**Comment by Quantum2707** [comment]
After reinstall its not working.. but the darkrp folder should be in full lower case, shouldn't it?
