### ISSUE TITLE
Distance checks not implemented in entities, or even a canDarkRPUse

### ISSUE THREAD

**Issue by Codingale** [FPtje/DarkRP#2709]
### Description of the bug
Spawned_money calls canDarkRPUse however not every class does this, I only mention this as I need to add in a distance check before merging WireMod onto our server after https://github.com/wiremod/wire/commit/eb7f92623f5e17d08fc58e8a73642633f06f924e

### How to make the bug happen
Try to add a hook for canDarkRPUse (or just look at the code for the entities)

### Lua errors
None

### Why the developer of DarkRP is responsible for this ~issue~ feature request
It'd be helpful for most if not all entities to call the hook allowing perhaps a new level of code, for example perhaps a locked `spawned_shipment` that needs to be cracked/lockpicked etc

or a simple distance check

I'll perhaps make a PR soon just thought I'd ask for input however first, but as you have your own style of coding I'm sure you'd prefer to write it... ~besides why not touch the core files on my local server!!~

**Comment by FPtje** [comment]
I actually talked to Divran about this. I decided that I don't want distance checks in e.g. shipments, since people often make contraptions with them.

I've added some `canDarkRPUse` hooks, though. That'll do.
