### ISSUE TITLE
Cache Material() calls

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2712]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I don't know everything about it, but shouldn't Material, Model and Sound calls be cached.
I just saw in a lot of weapons they are getting called multiple times, without getting cached.
Example: stunstick

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Kefta** [comment]
Model and Sound just pass through strings, Material is the only function that creates an object. Could you point to specific locations you noticed this at?

**Comment by mcNuggets1** [comment]
https://github.com/FPtje/DarkRP/blob/master/entities/weapons/stunstick/shared.lua#L75
