### ISSUE TITLE
/drop weapons doesn't work lastest version of darkrp

### ISSUE THREAD

**Issue by x7SooN** [FPtje/DarkRP#2714]
there is problem in /drop weapons doesn't work i tried other verisons

**Comment by mcNuggets1** [comment]
How is this from 19 Nov 2017?

**Comment by FlorianLeChat** [comment]
Better late than never ⌚

**Comment by FPtje** [comment]
Huh, that's odd

**Comment by FPtje** [comment]
The issue number is old, so I suppose it doesn't apply anymore
