### ISSUE TITLE
Restrict drop.

### ISSUE THREAD

**Issue by Aka7tsu4** [FPtje/DarkRP#2715]
hi, the restrict drop is bugged.

my restrict drop is on FALSE, but player can't drop spawned weapons and shipments.

please take a look

i'am not the only one
http://forum.darkrp.com/threads/drop-weapons-doesnt-work.10394/#post-39437

**Comment by strideynet** [comment]
Please use the template for issue reporting.

Does this occur on a vanilla DarkRP install?

**Comment by Aka7tsu4** [comment]
Yes of course.

**Comment by Aka7tsu4** [comment]
so..?

**Comment by Bo98** [comment]
Is there any message (notification or console message) when attempting to drop a weapon or shipment?

**Comment by FPtje** [comment]
The config option `GM.Config.DisallowDrop` applies even when `GM.Config.restrictdrop` is set to `false`.

Otherwise I just tested dropping an ak47 that spawned from a shipment with `GM.Config.restrictdrop` set to `false`. The weapon dropped.

**Comment by Aka7tsu4** [comment]
but when disallowdrop is set to true, we can't drop spawned by shipment weapons.

**Comment by FPtje** [comment]
`GM.Config.DisallowDrop` is a table, don't set it to `true`.
