### ISSUE TITLE
issue with /advert not working

### ISSUE THREAD

**Issue by cactusadmin** [FPtje/DarkRP#2718]
so when my players /advert its now spawning the billboards instead of using chat. I had a module installed to remove that billboard prop and use chat instead but now it seems darkRP is reversing that modules action.

**Comment by FPtje** [comment]
That's a user error.

**Comment by cactusadmin** [comment]
how would it be a user error? its a issue with darkRP spawning a prop :/

**Comment by FPtje** [comment]
User in this case being the author of the module. I'm not willingly breaking modules that implement chat adverts.
