### ISSUE TITLE
fadmin 'GetCount' (a nil value)

### ISSUE THREAD

**Issue by slaVACo** [FPtje/DarkRP#2720]
[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/sv_fadmin.lua:91: attempt to call field 'GetCount' (a nil value)
  1. fn - gamemodes/darkrp/gamemode/modules/fadmin/sv_fadmin.lua:91
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by Kefta** [comment]
Either your server is very outdated (to before player.GetCount was added) or one of your addons is defining "player" as a new global table.
