### ISSUE TITLE
Can`t add admins/superusers to Fadmin

### ISSUE THREAD

**Issue by TheDenVx** [FPtje/DarkRP#2721]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When i write in a console "fadmin setroot thedenvx", in a game i see the massage that "unknown" set me to usergroup "superadmin", but i didn`t get afmin in Fadmin, only in ULX, and every time i restarting server or doing anything else it still not working, i just want to update my DarkRP, but when i instaling new one, i can`t get admin. One the old one i can be an admin or superadmin, but when i write in a console "fadmin setroot thedenvx" i can spawn cars and other stuff, but i can`t use admin commands...

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Add self to superadmin by the Rcon, server console.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
There is no any Lua errors

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I can`t find somebody who knows what is it, and how to fix this, also in fadmin is no any groups..

**Comment by FPtje** [comment]
No groups in FAdmin means a lua error on start or a messed up database. Go to forum.darkrp.com for help.

**Comment by TheDenVx** [comment]
Let me add u in steam to i give u acces to console of server. I didn't see any errors from darkrp or fadmin. Or add me on steam, i rly need to fix this problem..
https://steamcommunity.com/id/denvx/

**Comment by FPtje** [comment]
I don't have time for personal support. Please head to the forums.
