### ISSUE TITLE
FPP toolgun problem

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2725]
For some time now, it stopped working.
I can not set the permissions of the work tools, I have to do it manually from the database.

https://i.gyazo.com/124a6cb58661f05b4ff5280ca8f3799e.png

I tried to create a database to get rid of doubts, but it did not work either.
simply by pressing the edit button, nothing happens.

Version: Github
Mysqloo v9

**Comment by FPtje** [comment]
Fixed in https://github.com/FPtje/Falcos-Prop-protection/commit/8c241a7d2bb6b58aae3d36893e69eca2accf6c12

Also fixed in workshop versions of FPP and DarkRP

@mcNuggets1
