### ISSUE TITLE
DarkRP broke

### ISSUE THREAD

**Issue by chrisheeley2** [FPtje/DarkRP#2727]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Spawn as the job connecting/joining spawn point is under the map money is always at 0

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
It just randomly happened

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] A runtime error has occurred in "[C]" on line -1.
The best help I can give you is this:

DarkRP was unable to introduce player "chrisheeley" to the game. Expect further errors and shit generally being fucked!

Hints:
	- This error most likely does not stand on its own, and previous serverside errors have a very good chance of telling you the cause.
	- Note that errors from another addon could cause this. Specifically when they're thrown during 'PlayerInitialSpawn'.
	- This error can also be caused by some other addon returning a value in 'PlayerInitialSpawn', though that is less likely.
	- Errors in your DarkRP configuration (jobs, shipments, etc.) could also cause this. Earlier errors should tell you when this is the case.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. function 'Spawn'
	2. gamemodes/base/gamemode/player.lua on line 115
------- End of Simplerr error -------

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I have done nothing to the server (No addons etc)

**Comment by FPtje** [comment]
Heed the hints.

**Comment by chrisheeley2** [comment]
I removed darkrp mod and it still is broke and there are no other errors or addons

**Comment by FPtje** [comment]
Check the installation. For further help go to forum.darkrp.com, this is
not a help forum.

**Comment by chrisheeley2** [comment]
The forum is 502 Bad Gateway

**Comment by Kefta** [comment]
Yeah, forums are currently down
