### ISSUE TITLE
Issue, appeared very tough exploid in garrys mod fashion

### ISSUE THREAD

**Issue by slaVACo** [FPtje/DarkRP#2730]
1way : netchannel unknown net message (15) from 'ip'
2way : https://i.imgur.com/AqOHI99.png
3way : CCommand::Tokenize: Encountered command which overflows the tokenizer buffer.. Skipping!
Help pls

**Comment by slaVACo** [comment]
http://steamcommunity.com/id/qewqewqeqweqwe/
add me, to I showed that Yes as

**Comment by FPtje** [comment]
Doesn't look like DarkRP is causing this
