### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2731]
[ERROR] A runtime error has occurred in 
       "gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua" on line 105.

         The best help I can give you is this
         Attempt to call Name/Nick/GetName on a non-existing player!
     
         Hints:
         <TAB>- No hints, sorry.
         
         The responsibility for the error above lies with (the authors of) one (or more) of these files:
         <TAB>1. gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua on line 105
         <TAB>2. RunString on line 156
         ------- End of Simplerr error -------
         
           1. error - [C]:-1
            2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:530
             3. Nick - gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua:105
              4. unknown - RunString:156

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:64: Tried to use a NULL entity!
           1. __newindex - [C]:-1
            2. getDarkRPVar - gamemodes/darkrp/gamemode/modules/base/sv_entityvars.lua:64
             3. unknown - addons/blogs/lua/blogs/modules/connections.lua:47

[ERROR] RunString:143: Tried to use a NULL entity!
           1. SteamID64 - [C]:-1
            2. unknown - RunString:143

I really do not know where it comes from, but they are random
Version: github

**Comment by Kefta** [comment]
One of your addons is calling getDarkRPVar on a NULL player through RunString-executed code.
