### ISSUE TITLE
lab_base should draw translucent.

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2733]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The lab_base's rendergroup should be set to RENDERGROUP_TRANSLUCENT and the hook Draw used in cl_init should be changed to DrawTranslucent to fix the issues with the floating sign render bugs.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Renderissues appear with rendering not exactly on the prop when the normal rendergroup is used

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Part of DarkRP

**Comment by Bo98** [comment]
Should it not be `RENDERGROUP_BOTH` with the model drawn in `ENT:Draw` and the text drawn in `ENT:DrawTranslucent`?

**Comment by mcNuggets1** [comment]
Draw the model in DrawTranslucent.

**Comment by FPtje** [comment]
PR it

**Comment by mcNuggets1** [comment]
I hate PR's, but yeah, I'll do it.

**Comment by Bo98** [comment]
> Draw the model in DrawTranslucent.

Yes, I know it's technically possible, but that doesn't mean it's correct.
