### ISSUE TITLE
NOTIFY_ Enumerations do not work with DarkRP.notify

### ISSUE THREAD

**Issue by yupi2** [FPtje/DarkRP#2740]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Passing a `NOTIFY_*` value to `DarkRP.notify` causes a `NOTIFY_GENERIC` (0) to be read clientside.

`NOTIFY_ERROR`, `NOTIFY_UNDO`, `NOTIFY_HINT`, `NOTIFY_CLEANUP` should all be affected by this.

This might already be known since a lot of `DarkRP.notify` calls in the gamemode use number-constants instead of the `NOTIFY` values. If using the `NOTIFY` values isn't something that is going to be fixed then there's a few places where they are still used in DarkRP and should be replaced with number-constants.

Probably affects `DarkRP.notifyAll` too.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
`DarkRP.notify(ply, NOTIFY_ERROR, 7, "message")`

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP handles the networking of notifications through DarkRP.notify[All]

**Comment by FPtje** [comment]
The `NOTIFY_` enum doesn't work serverside full stop:

http://wiki.garrysmod.com/page/Enums/NOTIFY

**Comment by yupi2** [comment]
Missed that, thanks. The results in these searches should be fixed btw.
https://github.com/FPtje/DarkRP/search?utf8=%E2%9C%93&q=NOTIFY_ERROR&type=
https://github.com/FPtje/DarkRP/search?utf8=%E2%9C%93&q=NOTIFY_HINT&type=
