### ISSUE TITLE
Add convars for chat receiver distances

### ISSUE THREAD

**Issue by 54** [FPtje/DarkRP#2743]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This is not so much of a bug as much as it is a feature request. 

Wasn't sure what terminology to use. But, by chat receiver, I'm on about both the clientside chat receiver and the actual serverside check.

It would be nice to be able to change the default values for the chat/voice distance checks without modifying the core. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
N/A; not a bug.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A; not a bug.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
It would be nice as it involves modifying local functions in the DarkRP core.

**Comment by FPtje** [comment]
```lua
DarkRP.addChatReceiver("", DarkRP.getPhrase("talk"), function(ply)
    if GAMEMODE.Config.alltalk then return nil end
    return LocalPlayer():GetPos():DistToSqr(ply:GetPos()) < 62500
end)
DarkRP.addChatReceiver("/ooc", DarkRP.getPhrase("speak_in_ooc"), function(ply) return true end)
DarkRP.addChatReceiver("//", DarkRP.getPhrase("speak_in_ooc"), function(ply) return true end)
DarkRP.addChatReceiver("/a", DarkRP.getPhrase("speak_in_ooc"), function(ply) return true end)
DarkRP.addChatReceiver("/w", DarkRP.getPhrase("whisper"), function(ply) return LocalPlayer():GetPos():DistToSqr(ply:GetPos()) < 8100 end)
DarkRP.addChatReceiver("/y", DarkRP.getPhrase("yell"), function(ply) return LocalPlayer():GetPos():DistToSqr(ply:GetPos()) < 302500 end)
DarkRP.addChatReceiver("/me", DarkRP.getPhrase("perform_your_action"), function(ply) return LocalPlayer():GetPos():DistToSqr(ply:GetPos()) < 62500 end)
```

You can make a custom clientside DarkRP module where you paste the above lines and fill in your own implementation.

**Comment by 54** [comment]
As far as I know, that only changes the clientside aspect of this. There is still the serverside distance check which I don't believe you can easily override like that. For example:

## sv_chatcommands.lua ##

**Full excerpt:**

```lua
local function Yell(ply, args)
    local DoSay = function(text)
        if text == "" then
            DarkRP.notify(ply, 1, 4, DarkRP.getPhrase("invalid_x", "argument", ""))
            return ""
        end
        DarkRP.talkToRange(ply, "(" .. DarkRP.getPhrase("yell") .. ") " .. ply:Nick(), text, 550)
    end
    return args, DoSay
end
DarkRP.defineChatCommand("y", Yell, 1.5)
```

**line 53:**

```lua
DarkRP.talkToRange(ply, "(" .. DarkRP.getPhrase("yell") .. ") " .. ply:Nick(), text, 550)
```

## sv_gamemode_functions.lua ##

**Full excerpt:**

```lua
local function calcPlyCanHearPlayerVoice(listener)
    if not IsValid(listener) then return end
    listener.DrpCanHear = listener.DrpCanHear or {}
    local shootPos = listener:GetShootPos()
    for _, talker in ipairs(player.GetAll()) do
        local talkerShootPos = talker:GetShootPos()
        listener.DrpCanHear[talker] = not vrad or -- Voiceradius is off, everyone can hear everyone
            (shootPos:DistToSqr(talkerShootPos) < 302500 and -- voiceradius is on and the two are within hearing distance
                (not dynv or IsInRoom(shootPos, talkerShootPos))) -- Dynamic voice is on and players are in the same room
    end
end
```

**line 296:**

```lua
(shootPos:DistToSqr(talkerShootPos) < 302500 and -- voiceradius is on and the two are within hearing distance
```

**Comment by FPtje** [comment]
Oh yeah, whoops.

**Comment by mcNuggets1** [comment]
There are a lot of things right here.
You can't disable the display of how far away people are and if you are currently talking to them.
I overrid the whole module to prevent players from abusing the voice com to find out, if there are players behind a wall.

**Comment by 54** [comment]
Thanks a ton for dealing with this, @FPtje!
