### ISSUE TITLE
Multirun ply:SteamDI64() errors

### ISSUE THREAD

**Issue by yupi2** [FPtje/DarkRP#2744]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
A `-multirun` account causes `ply:SteamID64()` to return nil which causes everything ever to break.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
- Load DarkRP on an `sv_lan 1` server (so we can actually join without Steam blocking us).
- Disable `antimultirun` in darkrp_modification
- Create an `hl2.exe` shortcut that includes `-multirun`
- Connect the multirun account to the server (preferably after your main has connected)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
```
Client "(1)asdf" connected (192.168.1.21:27008).
ServerLog: [FAdmin] (1)asdf (STEAM_0:0:0) is Authed
ServerLog: [FAdmin] (1)asdf (STEAM_0:0:0) Spawned for the first time

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:354: attempt to concatenate a nil value
  1. createPlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:354
   2. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:449
    3. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:333
     4. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:305
      5. offlinePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:305
       6. retrievePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:344
        7. restorePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:431
         8. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:593


[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:612: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:612

ServerLog: [FAdmin] (1)asdf (STEAM_0:0:0) Spawned

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:737: attempt to index local 'jobTable' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:737
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The developer is not responsible, but this can be worked around / fixed with what's currently used to fix `ply:SteamID64()` in singleplayer https://github.com/FPtje/DarkRP/blob/11c2f3b70021600a4b5bd19db90f12e3091d7d32/gamemode/modules/workarounds/sh_workarounds.lua#L89

**Comment by Kefta** [comment]
Whoops, I removed it in https://github.com/FPtje/DarkRP/pull/2723/files since sv_lan by itself didn't seem to make a difference; didn't realise it was multirun related. Maybe a comment should be added to make it clear to anyone looking over the code?
