### ISSUE TITLE
Re-Spawn glitch

### ISSUE THREAD

**Issue by saya1337** [FPtje/DarkRP#2745]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # Randomly, when people die they will spawn in the wrong location and be stuck. The only way to get out is through the noclip from fadmin(ulx noclip wont work). There are no console errors at all, but it keeps happening at random points to players.

### How to make the bug happen
[//]: # Dying or respawning
[//]: #  I cant find a fix, the person whos bugged has to rejoin the server in order to "fix"
### Lua errors
[//]: # There arent any Errors in the logs of the server.

### Why the developer of DarkRP is responsible for this issue
[//]: # There are no lua errors associated with my addons, and I have no idea what the problem is i am trying to see if DarkRP is the issue. I think it may have to do with the darkrp respawn mechanic and possibly spawnpoints.

**Comment by mcNuggets1** [comment]
Disable all addons.

**Comment by sayaloli1** [comment]
How you mean it exactly?

**Comment by FPtje** [comment]
Cannot reproduce
