### ISSUE TITLE
AFK Module Error.

### ISSUE THREAD

**Issue by Toxic10101** [FPtje/DarkRP#2747]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Pops up in the console frequently with a players name and steamid before hand.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Nothing seems to "trigger" it, it just pops up.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/afk/cl_afk.lua:1: attempt to index a nil value
1. unknown - gamemodes/darkrp/gamemode/modules/afk/cl_afk.lua:1
2. include - [C]:-1
3. LoadModules - gamemodes/darkrp/gamemode/cl_init.lua:26
4. unknown - gamemodes/darkrp/gamemode/cl_init.lua:44

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
I'm guessing a hud addon that isn't compatible with afk.

**Comment by Toxic10101** [comment]
What does this mean? How do you know this? How does one make a HUD compatible with it?

**Comment by FPtje** [comment]
Define the HUD color convars

**Comment by Bo98** [comment]
Or alternatively, don't disable the entire HUD module and make sure the replacement HUD uses `HUDShouldDraw`. There is very few cases where HUDs replace _everything_ that's in that module - most commonly not replacing DarkRP's notification networking.
