### ISSUE TITLE
Door data truncation after 1024 players

### ISSUE THREAD

**Issue by TheFreezebug** [FPtje/DarkRP#2748]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

I noticed that after 1024 players join without a restart that the userid in the network info for the doors gets truncated. 

What ends up happening, is the network information broadcasted for getDoorData() gets partially truncated.

See data

![Bad Data](http://xayr.ga/share/2018-04/notepad_2018-04-12_20-15-267dc70a74-4ef2-496b-ad87-3913fb72db07.png)

You're sending / receiving a 10 bit integer, which will truncate after 1024(-1) players

This is likely the cause of #2594 , #2548  , (others?) 

Players cannot co-own doors after this, because they're referencing a null user-id. This leaving 

Allowed to co-own:
(nothing)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Have 1024 players join a server without a restart, or simply add bots to your server until your userid index is above 1024.  -- Then own a door,  add a co-owner, and check the :getDoorData() on the server and the client. 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No lua errors, it causes visual and interface errors by the client, leaving them unable to co-own doors.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

You have some sort of code standard that i don't want to break, i'm perfectly capable of making a pull request, but don't want to do anything "out of standard"

**Comment by mcNuggets1** [comment]
Good catch.

**Comment by FPtje** [comment]
This is the kind of bug that is extremely hard to find. I don't know what you did to find the cause of it, but well done.
