### ISSUE TITLE
Change payday message and weapons.

### ISSUE THREAD

**Issue by Cocobor** [FPtje/DarkRP#2751]
Tried to change the message: "Payday! You received $10!" but did not find this parameter.
How to change this message?
And one more question. How to allow everyone to spawn weapons?
In the settings there is only this option:
-- adminweapons - Who can spawn weapons: 0: admins only, 1: supadmins only, 2: no one

**Comment by Kefta** [comment]
https://github.com/FPtje/DarkRP/blob/3cd9964e122388edc53a16a46dad813f44ef86fb/gamemode/modules/language/sh_english.lua#L57-L59

**Comment by FPtje** [comment]
Thanks @Kefta
Also, there is no option to allow everyone to spawn sweps.
