### ISSUE TITLE
Allow everyone to spawn weapons.

### ISSUE THREAD

**Issue by Cocobor** [FPtje/DarkRP#2752]
And one more question. How to allow everyone to spawn weapons?
In the settings there is only this option:
-- adminweapons - Who can spawn weapons: 0: admins only, 1: supadmins only, 2: no one
But I need everyone to be able to do this.

**Comment by Kefta** [comment]
https://github.com/FPtje/DarkRP/pull/2753

**Comment by Cocobor** [comment]
Thank you very much! Everything works!
