### ISSUE TITLE
Spawns Don't Save

### ISSUE THREAD

**Issue by Nacoles** [FPtje/DarkRP#2758]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # When I try to set the spawn for a certain job, it resets after a server restart.
[//]: # I have never seen an error like this online so I'm kinda clueless on who to ask. 😢 

### How to make the bug happen
[//]: # I used a fresh copy of darkrpmodificationmaster and overwrote the saved jobs/entities/shipments/doorgroups I have saved to the lua files in the modificationmaster.
[//]: # I may have accidently changed it first to zombierp following the darkrp based gamemode instructions but I'm not sure.

### Lua errors
[//]: # I don't recall any in regards to this issue.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Cannot reproduce.
