### ISSUE TITLE
weapon drop bug

### ISSUE THREAD

**Issue by icedartz** [FPtje/DarkRP#2766]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
when i /drop then it only launches the animation but it dont drop the weapon

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
/drop

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
there are no errors

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
because i think its because of darkrp

**Comment by Kefta** [comment]
Update your DarkRP - this was fixed in https://github.com/FPtje/DarkRP/commit/f18165d4cadbb55f168ed5a887133ac4d564a70a
