### ISSUE TITLE
New clientside chat indicators create errors when another player tries to talk

### ISSUE THREAD

**Issue by Tenrys** [FPtje/DarkRP#2767]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
087677dd0de0c068c41506ff3ffb7534978fc57a seems to break chat indicators whenever someone is talking, I doubt this is an addon on my end

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Just have someone type in the chat and you'll get the error

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

```
[ERROR] gamemodes/darkrp/gamemode/modules/chatindicator/cl_init.lua:15: attempt to index local 'ragdoll' (a nil value)
  1. v - gamemodes/darkrp/gamemode/modules/chatindicator/cl_init.lua:15
   2. unknown - lua/includes/modules/hook.lua:84
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Only started happening after updating DarkRP to the latest revision

**Comment by Kefta** [comment]
Could you post a full error? You're missing the header.

**Comment by Tenrys** [comment]
uh whoops

**Comment by Tenrys** [comment]
there

**Comment by Tenrys** [comment]
I'm on chromium branch

**Comment by Kefta** [comment]
I believe it's outdated, try testing on main.

**Comment by Bo98** [comment]
The relevant change was in the May 29th update:

> Return type consistency for Player.TraceHullAttack, Player.GetObserverTarget, Player.GetRagdollEntity, NPC.GetBlockingEntity, NPC.GIve, Entity.GetRagdollOwner, they now return NULL entity where they used to return nil

I've never really thought about backwards compatibility for GMod versions before. I suppose there's a few using the chromium branch and we don't know if it will be updated anytime soon?

**Comment by Kefta** [comment]
It's supposed to only be there to test chromium and not for general use, but GMod's net compatibility allows you to join any server with it. This will change next update unless the branch is updated again
