### ISSUE TITLE
Error when open changelevel panel

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#2771]
### Description of the bug

An error appears when opening the changelevel panel by the scoreboard. I have no addon installed on my Gmod and i use the lastest github version of DarkRP.

### How to make the bug happen

Open the changelevel panel by the scoreboard.

### Lua errors

[Florian #|2|STEAM_0:1:46606686] Lua Error:

[ERROR] lua/includes/extensions/table.lua:94: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. HasValue - lua/includes/extensions/table.lua:94
    3. rpFirstSortedPairs - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/changelevel/cl_changelevelgui.lua:58
     4. Refresh - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/changelevel/cl_changelevelgui.lua:65
      5. DoClick - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/changelevel/cl_init.lua:40
       6. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_controls.lua:305

### Why the developer of DarkRP is responsible for this issue

Because changelevel panel is integrated by default in FAdmin on the DarkRP gamemode.

**Comment by Bo98** [comment]
Looks like there has been a GMod change in the structure of the table returned by `SortedPairs`.
