### ISSUE TITLE
The problem with permanent bans.

### ISSUE THREAD

**Issue by WJJJ1337** [FPtje/DarkRP#2772]
Good day, the problem is that when you use the command /ban a 1 1-goes ban all for 1 minute, / ban a 0 - permanent ban.

**Comment by FPtje** [comment]
It's hard to see what you mean, but 0 generally means permanent. That's the way it's supposed to work.

**Comment by WJJJ1337** [comment]
https://i.imgur.com/uhis3CG.gifv
