### ISSUE TITLE
Problem with permanent bans (corrected text, sorry)

### ISSUE THREAD

**Issue by WJJJ1337** [FPtje/DarkRP#2773]
https://imgur.com/uhis3CG

**Comment by del-sys32** [comment]
That is the expected outcome though. 0 means permanent.

Are you suggesting that it shouldn't ban all bots, and simply focus on a single bot at a time?

**Comment by Bo98** [comment]
I'm guessing you're worried about typos or maybe the case where someone has the name "a 0 ..." to trick an admin?

**Comment by WJJJ1337** [comment]
yes Bo98

**Comment by FPtje** [comment]
Spaces are new arguments. That's how it works. Sorry.
