### ISSUE TITLE
DarkRP commands not working

### ISSUE THREAD

**Issue by oiNFLiCTioNX** [FPtje/DarkRP#2776]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### DarkRP commmands dont work, i cant pick the job, but the F4 is working. There is no lua errors or etc.
[//]: # (Describe the issue as accurately as possible)

Sorry that i writing here, the forum is dont work for me

**Comment by FPtje** [comment]
The forums are being worked on. Sorry.
