### ISSUE TITLE
There Is Something Wrong With The Weapons

### ISSUE THREAD

**Issue by Fireball12me** [FPtje/DarkRP#2782]
So, I own a DarkRP server and I use this folder to help run the server, originally there was nothing wrong but I came across something rather odd. 

Everyone adds custom jobs to their DarkRP servers because the Gamemode folder that you get doesnt have all the jobs in it right away, so I added in one job, a Hitman job, and it is working great, the only problem I have with it is that when I switch to it and become a Hitman, for some reason I have all the police batons on me, for my Hitman job, I set him to only have the Colt Python from one of the M9k addons so I do not get why I spawn in with all the Police Batons and it seriously is annoying.

**Comment by Bo98** [comment]
It's because you're an admin.

`GM.Config.AdminsCopWeapons`

**Comment by Fireball12me** [comment]
Yeah I found that out in a video lmfao thank you though.
