### ISSUE TITLE
Arrest stick not teleporting players

### ISSUE THREAD

**Issue by clwebsites** [FPtje/DarkRP#2786]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # Arrest stick not teleporting player to jail positions. Nothings blocking the position.

### How to make the bug happen
[//]: # Arresting a player causes this issue.
[//]: # Nothing I've discovered fixes this issue.

### Lua errors
[//]: # None
[//]: # ^

### Why the developer of DarkRP is responsible for this issue
[//]: # You have the most experience with DarkRP itself.
[//]: # You are the right people to look at this issue because you developed this gamemode and have experience with the lua code. You also have fixed many bugs, so you have experience with that as well.

**Comment by mikkelbiz** [comment]
Make sure you use /setjailpos and /addjailpos in the chat to set your positions, otherwise they will be arrested on the spot.

**Comment by clwebsites** [comment]
I know this. I does not work.

**Comment by mikkelbiz** [comment]
Must be an addon then. Last commit was 11 days ago, and I tested this with both sqlite and MySQL a few days ago in #2784 

Ask on the forums.

**Comment by Bo98** [comment]
Make sure GM.Config.teletojail is set to true as well.

**Comment by clwebsites** [comment]
Its enabled, nothing is working. I asked on the forums but know one answers me because they dont know. You guys do know and wont help. So cut the, try this try that NOTHING WORKS.

**Comment by strideynet** [comment]
How can you expect people giving up their time to help you with an issue, when you lack the common decency to try what they are suggesting and cooperate with them trying to yelp you.

There's no magic way for anyone here to reach into your installation and fix this issue that is solely specific to you. If don't want to put effort into finding a solution, pay someone to deal with it for you.

**Comment by mikkelbiz** [comment]
Rename the addons folder to addons2 and see if it works then. If it does, its an addon.

I have tested the base gamemode by itself, the function works so its out of the developers hands.

**Comment by Bo98** [comment]
Well if "nothing works" then it looks like you don't want any help as anything we say will be useless.

Stop your childish accusation that we "do know" and are just messing with you. You certainly won't be receiving any response in that thread from me.

**Comment by clwebsites** [comment]
Listen, I'm sorry for that I have had a long morning. Nothing people have suggested works. I've tried the suggestions. If there are any more, I would be happy to try them. I'm just irradiated that I haven't fixed it yet. So I apologize for being rude. It was a dick move.
