### ISSUE TITLE
Missing version string for FAdmin

### ISSUE THREAD

**Issue by Lexicality** [FPtje/DarkRP#2787]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I'm writing an error tracking system, but there's no way for me to find out what version of FAdmin is installed on the server, like there is with ULX.
I want this information to give the greatest context available to errors, for instance if an error starts happening after a DarkRP upgrade, showing that version change helps track down what happened.
(Also, the `GM.Version` string doesn't seem to have changed in two years, despite active development?)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
?

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Proper versioning of a released product is essential when others are integrating with it - it lets you know when you are out of date and what kind of a change to expect when updating.

**Comment by FPtje** [comment]
The best version ing would be the git commit, but I cba to make a system that automatically updates it.

**Comment by Lexicality** [comment]
I guess you could do something similar to git flow and work on a `develop` branch and have a bot that monthly merges to `master` and updates the version to be the current date?
Hashes aren't great for version numbers because they're not linear.

**Comment by FPtje** [comment]
That's not worth the effort, given the plans I don't have for DarkRP
