### ISSUE TITLE
Players are not being teleported to jail positions.

### ISSUE THREAD

**Issue by gabeeeboii** [FPtje/DarkRP#2788]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: http://forum.darkrp.com/ )

### Description of the bug
[//]: # I've been having an issue where if I use /setjailpos and /addjailpos I can add the positions right? So when I arrest someone they teleport to spawn?!?! (But Arrested). Why don't they spawn at the positions I've set? I checked if anything was in the way of the position, I opened settings.lua and checked teletojail and telefromjail both are enabled. No addons are causing this issue "I think, I checked". So, what should I do from here? I tried a lot of troubleshooting but nothings seems to work. I even set the server on a new map and still get the same results. If anyone could help in my debug process that would be great!

### How to make the bug happen
[//]: # Arresting a player on my server.
[//]: # No fixes yet ;/

### Lua errors
[//]: # No lua errors appear
[//]: # Console is empty when player is arrested, other that the notification "player" has been arrested!

### Why the developer of DarkRP is responsible for this issue
[//]: # You guys know the gamemode and have the most time around it :)
[//]: # I would like you guys and gals to look at my bug/issue because I have confidence you have the experience needed to find the fix!

**Comment by mikkelbiz** [comment]
Maybe you could try the fixes posted here #2786 as again, I tested this a few days back and it worked perfectly with the base gamemode and no addons.

**Comment by gabeeeboii** [comment]
Ok, I will look into these fixes! Why is the "ghost" being a jerk?

**Comment by gabeeeboii** [comment]
Ok, I disabled my addons again and it finally worked! So, how do I find the addon thats causing it?

**Comment by gabeeeboii** [comment]
Here is my server's ip if you want to join and take a look: 142.44.176.88:27015

**Comment by gabeeeboii** [comment]
![helpwithmods](https://user-images.githubusercontent.com/42156342/43750684-5df604b6-99ae-11e8-90b5-f2b902265cdf.PNG)
Found a fix! Sorry for the inconvenience, you guys are doing some amazing work with DarkRP :)

**Comment by gabeeeboii** [comment]
The sit anywhere causes the issues!
