### ISSUE TITLE
Blacklist Wipe

### ISSUE THREAD

**Issue by OGLnetwork** [FPtje/DarkRP#2798]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If the server were to crash or be restarted, the blacklist would reset. However our settings are still there and our tool restriction are still there. So its just the blacklist resets.
When we go to add a new thing to the blacklist its not saving to the database. And this is from the past 2 days for months its been fine before

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Restarting The Server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
https://pastebin.com/raw/iDUkeRxb
However on start-up cant spot any out of the ordinary errors.

**Comment by FPtje** [comment]
I'm sick of problems like this. I've updated DarkRP with a console command. Update your server to make it available. Then, after the server has been restarted, join and run the following command:

`darkrp_check_db_sv`

Post results here.

**Comment by mikkelbiz** [comment]
I booted up a server with the latest darkrp and mysql enabled. It works fine for me, both changelevel, closing srcds directly, closing the app from task manager and crashing it with wire.

Besides, @OGLnetwork you said it yourself. This started 2 days ago, what was added 2 days ago, something like this doesn't just break by itself. Its usually some addon interfering.

Follow FPtje anyway tho.

**Comment by OGLnetwork** [comment]
Unknown Command

**Comment by FPtje** [comment]
Yes, that means you didn't update DarkRP on your server.

**Comment by OGLnetwork** [comment]
I did 100% 
sorry if this annoying. But I did update darkrp not sure why its saying unknown command

**Comment by FPtje** [comment]
Please check to make sure the update went correctly. Restart the server after replacing the files

**Comment by FPtje** [comment]
How are you updating DarkRP anyway?
