### ISSUE TITLE
MySQL error with darkrp_position

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2799]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Jail positions are bugged for some reason. I didn't modify anything about the table in mysql.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Unknown

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
Lua Error: gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:265: Unknown column 'T' in 'where clause' (DELETE FROM darkrp_position WHERE type = 'J' AND map = "rp_retribution_v2";)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
darkrp_position table

**Comment by FPtje** [comment]
Head to the forums: forum.darkrp.com

**Comment by mcNuggets1** [comment]
I did most of my addons myself.
Nowhere I fuck with the darkrp mysql tables.

I will try to reproduce, this issue is ancient btw, I had it happen over years, I just cleared the columns all the table.

**Comment by mcNuggets1** [comment]
I have reset the entire table now, let's see if it occurs again, will report back sooner or later.

**Comment by FPtje** [comment]
Does the Lua error have a stack trace by the way?

**Comment by mcNuggets1** [comment]
No.
It's a mysql error from.

**Comment by FPtje** [comment]
It should be re-thrown as a Lua error, which should give a stack trace

**Comment by FPtje** [comment]
That may be your log file being inaccurate. Turn on `lua_log_sv 1` and see if that shows the entire stack trace.

**Comment by Kefta** [comment]
Stack traces aren't displayed for callbacks since it's called from C.

**Comment by FPtje** [comment]
Ah that's true. I'm still mystified by the error itself though. Column `T`, What column `T`?

**Comment by mcNuggets1** [comment]
It's back.

Lua Error: gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:265: Unknown column 'T' in 'where clause' (DELETE FROM darkrp_position WHERE type = 'J' AND map = "rp_bangclaw";)

I didn't do anything.
