### ISSUE TITLE
Changing order of jobs messes with SQL jobspawns

### ISSUE THREAD

**Issue by Thepenguin9** [FPtje/DarkRP#2800]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

When using SQL to store DarkRP information, there are weird interactions with the jobspawns, specifically when you change the order of custom jobs, the SQL table does not realise this and gives the wrong jobs the wrong spawn

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

1. Enable SQL storage, and configure correctly
2. Add some custom jobs, there's nothing special about them in this step
3. Run /addspawn <JOBNAME> for each job
4. Confirm each job now has a unique spawn, and keep track of where
5. Change the order of the custom jobs in the file, and/or remove one
6. Restart the server, test each spawn again
7. The spawns should be mixed up

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

There are no lua errors due to the nature of the bug

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

This looks to be something I cannot solve without editing core files which is where you guys come in, a potential fix is storing the spawns using the team name rather than team ID. That way it's independent of order and dependant on the actual jobs

**Comment by FPtje** [comment]
It will always be dependent on something, be it job cmd, name or the team number. DarkRP uses the team number, which is decided by the order.

Using the cmd may be slightly better, but I'm not going to bother with a database migration.

**Comment by Kefta** [comment]
You should at least document this behavior or leave the issue open so people are aware of ordering restrictions.

**Comment by Thepenguin9** [comment]
I also want to add, changing the behaviour will result in server owners having to re-set spawns afterwards, but that will be a one-off, rather than having to redo __all__ of the job spawns should you add or remove a job

**Comment by FPtje** [comment]
Issues aren't documentation.

@Thepenguin9 a migration can be written, such that people don't notice unless they read from the database. I don't know if there are any addons that do.

**Comment by FPtje** [comment]
God damnit, I'm starting to get a distaste for updating DarkRP. The only reason I have not to do this is because I don't want to. That's a shitty reason.

**Comment by Thepenguin9** [comment]
I also want to add, the /setspawn command doesn't seem to work either, though that could be related to this issue

**Comment by FPtje** [comment]
Commit pushed to master, tested with both MySQL and SQLite, making sure the migration goes well in both cases. 

Please test, changes like this tend to have tricky corner cases.

I won't push this to workshop for a few weeks or so to make sure people don't have funny problems with it.
