### ISSUE TITLE
spawn jobs and doorgroups reset after restart 

### ISSUE THREAD

**Issue by nasheitanamouk** [FPtje/DarkRP#2810]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
After putting a spawn and the doorgroups I restart the server but the spawn jobs reset and the same for the doorgroups really need help really (I presume it's the latest version of the darkrp) and I've already scanned everything almost everything the topics that talk about that

### Lua errors
Nothing

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Make sure you have the latest DarkRP. Then run `darkrp_check_db_sv`. What does the output say?

**Comment by nasheitanamouk** [comment]
Where in the console ?

**Comment by FPtje** [comment]
The server's console, though it should work if you put it in your client's console if you're superadmin.

**Comment by nasheitanamouk** [comment]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_util.lua:267: attempt to call
method 'IsSuperAdmin' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sh_util.lua:267
   2. unknown - lua/includes/modules/concommand.lua:54

**Comment by FPtje** [comment]
I should fix that, try joining the server and running from your own console.

**Comment by nasheitanamouk** [comment]
How do I start it from my own console? (and thank you answer very quickly)

**Comment by FPtje** [comment]
You start gmod
join your server
press the console key
and then enter the command

**Comment by nasheitanamouk** [comment]
] darkrp_check_db_sv
Your sv.db database file is good.

**Comment by FPtje** [comment]
Alright, so that means that your database file is not corrupt, so that's not the problem.

Damnit, many people seem to be having this problem. Could you give me a list of the addons you have installed?

**Comment by nasheitanamouk** [comment]
addon on workshop : https://steamcommunity.com/sharedfiles/filedetails/?id=829302315

addon on my ftp : Craftingmod
                             Advanced survival
                             farmingmod
                            farm_system
                             darkrpmodification
                           handcuff
                            npc_base
                           meth 
                            npc_guide
                           the_backpack
                          npcstore
                          ulib and ulx 
                          vcmod
                          wiliamshopsystem
                          wiliamcardealer

**Comment by nasheitanamouk** [comment]
Is ok ????

**Comment by nasheitanamouk** [comment]
in logs i have that : 
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:223: attempt to index a nil value
  1. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:223
   2. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:305
    3. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:206
     4. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
      5. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:203
       6. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
        7. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:106
         8. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:90
          9. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:163

**Comment by FPtje** [comment]
Could you try updating to the latest DarkRP to see if it still happens?

**Comment by FPtje** [comment]
@nasheitanamouk I just took a closer look at the error. It looks like the error isn't from the latest version of DarkRP. Could you try updating DarkRP? The least it should do is update the line numbers of the error, which should give me some more information as to what's going on.

**Comment by FPtje** [comment]
Closing for now, since this doesn't seem to apply to the latest DarkRP. Please comment in this issue if you have news.

**Comment by mcNuggets1** [comment]
You still could fix the NULL error when using the db check concommand.

**Comment by FPtje** [comment]
Oh yeah

**Comment by FPtje** [comment]
done
