### ISSUE TITLE
MySQL Error Comeback

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2811]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Lua Error: gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:265: Unknown column 'T' in 'where clause' (DELETE FROM darkrp_position WHERE type = 'J' AND map = "rp_bangclaw";)

I resetted my database to test if this error ever occurs again and yeah, it came back like 2 weeks ago.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
unknown

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
unknown

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP

**Comment by FPtje** [comment]
I cannot solve this without debugging. You know Lua. PLEASE debug this. It might be related to #2810

**Comment by mcNuggets1** [comment]
I'll try to figure it out then.

**Comment by mcNuggets1** [comment]
I can't find any mistakes.
I checked my MySQL database and the DarkRP create schemes.
It's not happening in SQLite I can say so far, but that's it.

**Comment by FPtje** [comment]
Wait, can you list the triggers in MySQL?

**Comment by mcNuggets1** [comment]
https://i.imgur.com/AB7uhrp.png

**Comment by FPtje** [comment]
Try deleting that trigger, see if the error still happens.

**Comment by mcNuggets1** [comment]
It's the trigger.
It works now.

The trigger does search for "T"

**Comment by FPtje** [comment]
Glad it's solved. I should remove that trigger by default. Maybe that's the cause for #2810?
