### ISSUE TITLE
Doorsystem error

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2814]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
There is a error in my console after the doors update.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:155: Calling updateDoorData on a door that has no data!
  1. error - [C]:-1
   2. updateDoorData - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:155
    3. removeKeysDoorOwner - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:105
     4. keysUnOwn - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:101
      5. taxesUnOwnAll - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:136
       6. doPropertyTax - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:187
        7. unknown - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:79

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by mcNuggets1** [comment]
You forgot to call IsValid on the door entity, I think.
You have to remove it from the table too if invalid.

**Comment by mcNuggets1** [comment]
In a lot of places the table Player.Ownedz isnt getting cleaned off invalid entities or unowned entities.

**Comment by mcNuggets1** [comment]
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:111: attempt to call method 'IsMasterOwner' (a nil value)
  1. keysUnOwnAll - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:111
   2. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:892
Here the isvalid check is missing again.

**Comment by Bo98** [comment]
That second error is not a missing IsValid check. There never was one before either. The real cause is a typo - it should be a lowercase i.

As for the first error, we got away without an IsValid check in the previous implementation - how could this have suddenly changed with the new hook?

**Comment by mcNuggets1** [comment]
We didnt use a isvalid check before?
I thought we used one.

I didn't really investigate in the issue.

**Comment by Bo98** [comment]
Ah, because we used `isKeysOwnable` before - this takes place of `IsValid`:

```lua
if not ent:isKeysOwnable() then self.Ownedz[entIndex] = nil continue end
```

This would go before the first hook call - the second is already covered.

**Comment by Bo98** [comment]
Just realised the door update was already on Workshop. Surprised nobody noticed the error.
