### ISSUE TITLE
SQL issues with Fresh Car Dealer

### ISSUE THREAD

**Issue by EagleChan99** [FPtje/DarkRP#2817]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
So as of today, issues with Fresh Car Dealer have been noticed, A lua error with the SQL. The problem that is occurring is that the Blocked Models list is not loading due to this SQL issue. I would fix this issue myself but my lua knowledge is fairly limited and would probably end up breaking other shit. Anyway, this issue has only occurred overnight, As I logged in this morning I noticed the issue and checked the server console and found that it was Fresh Car Dealer V3. I tried uninstalling Fresh Car Dealer V3 from the server and with success the Blocked Models list was fully loaded and working as expected. After that I tried re-downloading a copy of Fresh Car Dealer V3 from the gmodstore, and with the same result upon installation and restart of server, the issue occurred once more. I am about to test by adding a car dealer to the map and restarting to see if the issue is that there is no dealer etc etc... if this is the issue I will close this thread and contact the Author of Fresh Car Dealer and bring to their attention that there is an issue with their addon.

### How to make the bug happen
This bug occurs simply by having Fresh Car Dealer V3 installed.

### Lua errors
Here is the complete lua error found in the server console upon server loading.

[ERROR] RunString:1: bad argument #1 to 'find' (string expected, got nil)
  1. find - [C]:-1
   2. Write - RunString:1
    3. fn - addons/freshcardealer-v3/lua/fcd/modules/base/sv_database.lua:21
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:109
      5. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:126
       6. onFinish - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:140
        7. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:209
         8. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
          9. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:208
           10. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
            11. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:106
             12. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:90
              13. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:163
 
 
 
[ERROR] RunString:1: bad argument #1 to 'find' (string expected, got nil)
  1. find - [C]:-1
   2. Write - RunString:1
    3. fn - addons/freshcardealer-v3/lua/fcd/modules/base/sv_database.lua:21
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:109
      5. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:126
       6. onFinish - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:140
        7. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:209
         8. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
          9. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:208
           10. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
            11. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:106
             12. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:90
              13. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:163

### Why the developer of DarkRP is responsible for this issue
I don't blame anyone for this issue, I am more seeking help than pointing fingers at people.
As I said, it has only happened overnight and nothing was edited to the server overnight.

**Comment by EagleChan99** [comment]
So upon creating a car dealer and restarting the server, there is no SQL issue. With that said, I will attempt to contact the Author and let them know the issue.

**Comment by Bo98** [comment]
>  I am more seeking help

As mentioned at the top of the issue template, help should be requested from the DarkRP forums and not here.

However, this error does seem specific to this addon so no one will be able to tell what the cause is without seeing the addon's code. Therefore, it is perhaps best to seek support from the author since it is a paid addon.

The DarkRP side of this is limited to it telling the addon that the database has been initialised and is ready. What the addon then does I cannot tell from this alone.

**Comment by FPtje** [comment]
The cause definitely lies with the author. The use of `RunString` in a database hook sounds like a good way to have hard to solve bugs. Do they store Lua code in the database? Man that would be messed up.
