### ISSUE TITLE
My player can drop weapons

### ISSUE THREAD

**Issue by nasheitanamouk** [FPtje/DarkRP#2821]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # Players can throw their weapons of jobs then that I disabled the function; We can do in the console and mark "drop" with the weapon in his hand ( the sv_cheats in on 0)

**Comment by nasheitanamouk** [comment]
even the physicgun

**Comment by FPtje** [comment]
Your `GM.Config.DisallowDrop` isn't set properly.

**Comment by nasheitanamouk** [comment]
?????? I have set properly because player can do /drop but in console player can

**Comment by nasheitanamouk** [comment]
-- The list of weapons that players are not allowed to drop. Items set to true are not allowed to be dropped.
GM.Config.DisallowDrop = {
    ["arrest_stick"] = true,
    ["door_ram"] = true,
    ["gmod_camera"] = true,
    ["gmod_tool"] = true,
    ["keys"] = true,
    ["lockpick"] = true,
    ["med_kit"] = true,
    ["pocket"] = false,
    ["stunstick"] = true,
    ["unarrest_stick"] = true,
    ["weapon_keypadchecker"] = true,
    ["weapon_physcannon"] = true,
    ["weapon_physgun"] = true,
    ["weaponchecker"] = true,
}

**Comment by nasheitanamouk** [comment]
and player can drop all

**Comment by nasheitanamouk** [comment]
need help..

**Comment by FPtje** [comment]
Not a help forum, see forum.darkrp.com
