### ISSUE TITLE
Feature Enhancement : OnPlayerChangedTeam

### ISSUE THREAD

**Issue by Shigbeard** [FPtje/DarkRP#2824]
Forgive me from deviating from format, but this isn't so much a bug by traditional sense as it is a bug from design. No error is produced.

For Jobs, when creating a custom job one can specify a function on a field called `OnPlayerChangedTeam`. This function appears to run every time a player changes to that team. However, this introduces a small issue when this function is used to manipulate bone positions or other persisting changes.

You see, if something were done to the player or server that persists between respawns, such as manipulating bone positions, these changes would continue to persist across model changes, respawns, job changes even. The only way to revert these changes on a job change would be to add a function to *EVERY* job that determines if the job the player is changing from is the one that manipulated these things in the first place, and then un-manipulate them. This process is extremely redundant and counter-productive, and it would be far more efficient if a function could be added to jobs that would be ran whenever the player changes away from that job.

Of course, one could add a local function above the job table that is called on every job but again, you'd be specifying an `OnPlayerChangedTeam` function on every job, and this could potentially include default jobs, meaning server operators would have to create duplicates of the original set of jobs just to add maybe 1 or 2 lines of code over and over (or do a naughty and edit the core files).

To bring it back to a **TL;DR**: I'm suggesting a feature enhancement to CustomJobs fields, to allow the server operator to define a function that would be ran every time a player leaves that job. The alternative would be to call `OnPlayerChangedTeam` for both leaving and joining a job (which seems to be an implied functionality by its arguments (oldTeam, newTeam, implying that newTeam could possibly not be the current job)).

*Addendum*: After looking through old requests (specifically #933 ), I noticed that the function is actually a core Garry's Mod function, and it may not be something you wish to modify. So perhaps the go here is to add a new field specifically for this alteration maybe? I'm not sure, I've been out of the game for a while.

**Comment by Shigbeard** [comment]
To clarify, the current behavior of `OnPlayerChangedTeam` results in it only being called when changing *TO* the job in question, not *FROM*.

**Comment by Bo98** [comment]
> The only way to revert these changes on a job change would be to add a function to EVERY job that determines if the job the player is changing from is the one that manipulated these things in the first place, and then un-manipulate them.

This is not necessary. OnPlayerChangedTeam is a hook so you can use it like this:

```lua
hook.Add("OnPlayerChangedTeam", "BoneManipulationChanger", function(ply, oldTeam, newTeam)
    -- do whatever here, this is called for ALL job changes so do comparison checks with oldTeam and newTeam.
end)
```

I know the GMod wiki says you can't use it as a hook but that's more of a bug than anything IMO. DarkRP corrects this behaviour.

> The alternative would be to call OnPlayerChangedTeam for both leaving and joining a job

Fair point, but not something that can easily be done without breaking backwards compatibility.

> I'm suggesting a feature enhancement to CustomJobs fields, to allow the server operator to define a function that would be ran every time a player leaves that job.

That could make sense. I imagine there would be quite a few use cases for this.
