### ISSUE TITLE
Stuff not Saving

### ISSUE THREAD

**Issue by gabrielcruel123** [FPtje/DarkRP#2826]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This started to happen when I updated my DarkRP
Everytime I restart my server, some stuff (Job spawns and saved doors) do not save, so I have to set everything up again with every restart

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Update DarkRP and restart the server, idk

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
It only happened when I upgraded DarkRP

**Comment by djtb2924** [comment]
Do you have DarkRPModification ?

**Comment by gabrielcruel123** [comment]
Yeah

**Comment by Bo98** [comment]
Is there not any Lua errors in the server console on startup? I have one theory but it would result in an error.

**Comment by FPtje** [comment]
I'll leave it as a forum issue. I  see you've already created the thread.
