### ISSUE TITLE
Storm collision error

### ISSUE THREAD

**Issue by PolSpock** [FPtje/DarkRP#2832]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When meteor storm are enabled and when a meteor hit the ground, a game error is printed to the console for each meteor collision.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
With no addon & workshop addon :
Enable the meteor storm, wait for the meteor to fall the ground.

By my investigation, when meteor touch a solid thing, PhysicsCollide() of meteor ent is called. So self:Destruct() is called. And when serv hit the 'self:Remove()' line, the error appear.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
meteor[320]: Changing collision rules within a callback is likely to cause crashes!

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The meteor system is developed by DarkRP developers 😃 

Regards,

**Comment by Bo98** [comment]
Nice spot.

I can't believe there's _still_ not a proper API for this (https://github.com/Facepunch/garrysmod-requests/issues/894) so a hack using timers may be the only way to avoid this.

**Comment by FPtje** [comment]
I can imagine the ones who do are among the best ones
