### ISSUE TITLE
NoClip issues

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2833]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
NoClip can still be activated when dead and is active while dead.
Also there are prediction errors using NoClip in DarkRP.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Use NoClip

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
DarkRP main addon

**Comment by FPtje** [comment]
When I try to noclip while dead, I just keep spectating the dead body. To make sure the player object isn't moving around without me seeing it, I tried pressing WSAD and printing my position serverside. The position remained unchanged.

I'm guessing it's not "DarkRP main addon", but another addon that you have installed. If not, please clarify how I'm responsible for this issue.

**Comment by mcNuggets1** [comment]
Still there are prediction errors, also I dont have any addon installed which might cause this.
Because i tested with no addons.
You can change noclip state while dead, i checked with GetMoveType, also your position then changes if you begin to move.
You still spectate yourself however.
