### ISSUE TITLE
Question about door system

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2840]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/doorsystem/cl_doors.lua#L65

Why is there a loop through the whole player table when you can just use GetDriver?
It's slower this way, does this serve any purpose?

**Comment by FPtje** [comment]
`GetDriver` is serverside.

https://wiki.garrysmod.com/page/Vehicle/GetDriver

**Comment by mcNuggets1** [comment]
Makes sense then.
However it doesn't make sense, that it's serverside in the first place.

**Comment by FPtje** [comment]
Yeah

**Comment by mcNuggets1** [comment]
By the way there still are bugs with the door system showing a door unownable while it is, i'm still investigating in the issue itself.

**Comment by Bo98** [comment]
Yeah, there’s little chance of it being clientside soon without some vehicle changes: 
https://github.com/Facepunch/garrysmod-requests/issues/451
