### ISSUE TITLE
Issues with NoClip

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2841]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If FAdmin is disabled, you still can noclip while dead, also there are prediction errors within the FAdmin hook of noclip, making noclip "lag."

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
not a bug

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
FAdmin belongs to FPtje.

**Comment by FPtje** [comment]
DarkRP doesn't reason about NoClip, so when FAdmin is disabled, reasoning about noclip is deferred to Sandbox/the base gamemode. As such I regard noclipping while dead when FAdmin is disabled as a sandbox/base bug. 

Also, I'm not sure what you mean by prediction errors. The noclip hook is shared, and all the called functions (`FAdmin_GetGlobal`, `sbox_noclip:GetBool()`, `FAdmin.Access.PlayerHasPrivilege`) should consistently give the same results both clientside and serverside. The only cause of prediction errors I can imagine is in this piece of code:

```
-- Disallow if other hooks say no
for k, v in pairs(hook.GetTable().PlayerNoClip) do
    if k == "FAdmin_noclip" then continue end
    if v(ply) == false then return false end
end
```
Meaning that _other_ addons can be responsible for prediction errors, returning one value on the server and another on the client.
