### ISSUE TITLE
onChatCommand works odd.

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2850]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I was expecting onChatCommand to trigger when a command has successfully ran, but even when it does not, it still runs.
Even when it returns a error message, the command runs, which makes it hard to work with.

I would suggest changing the behaviour to work only when the command sucessfully ran.

**Comment by FPtje** [comment]
I'm not changing an API because one user doesn't expect what it's doing. That will break addons, not worth it.

**Comment by mcNuggets1** [comment]
Then add an extra argument for "sucess" atleast.
Otherwise logging systems aren't able to document anything regarding this.

**Comment by Bo98** [comment]
It depends what you mean by "success".

Consider return paths for the PM command:

https://github.com/FPtje/DarkRP/blob/d0ba38cf96e606378a5c7e22deae8c123250d2ef/gamemode/modules/chat/sv_chatcommands.lua#L4-L33

`onChatCommand` runs after this callback. The return values for when the arguments are invalid and when the PM is successfully sent are identical. So currently, there is no way to detect what actually happened within the callback. This would require modifying all the chat commands to use a boolean or something as a return value. And even then, you'll need to get third-party addons to do so too.

Maybe it's still worth doing (still accepting `""` for backwards compatibility of course), but you should be aware of the above.

**Comment by mcNuggets1** [comment]
The hook currently has no real usage.
The only benefit from using it, is the command is ran after canChatCommand.

The benefit from adding a success argument, would make the hook useful for logging or extending the command, while this is currently not possible, sadly.

**Comment by FPtje** [comment]
The string indicates the replacement text to be shown in chat. returning `""` causes nothing to be said at all. Adding the "success" thing would be a lot of work to change in my own code, but addons probably won't change at all, so you'll have an untrustworthy `success` value in your hook, which gives nil for commands that may or may not have succeeded.

If you want to extend the functionality of chat commands, just recreate them and provide your own implementation. The hook was never meant for extending chat commands.

**Comment by mcNuggets1** [comment]
How about adding a second hook for success?
Like "onChatCommandSucceeded"

**Comment by FPtje** [comment]
The point of the extra `success` argument to the hook call isn't the argument to the hook call. It's that you have to change every chat command to include it.

If it was easily implemented, I'd be fine with adding the argument to the hook call. That won't break anything.

**Comment by mcNuggets1** [comment]
It shouldn't be that much work, I could do that after my pull request got merged.
I still don't know how to do multiple pull requests and I don't use github frequently so I ain't learning it for the moment.

**Comment by FPtje** [comment]
You're adding commits to the master branch of your repo clone. That's gonna be super annoying if your PR ever gets denied. Use feature branches for PRs. Then you can create multiple PRs, rebase one branch on another and do way more.

**Comment by FPtje** [comment]
Also, this point would still hold:

> but addons probably won't change at all, so you'll have an untrustworthy success value in your hook, which gives nil for commands that may or may not have succeeded.

**Comment by mcNuggets1** [comment]
The success argument will only be used in the future by developers who can be made aware about this in the wiki.

**Comment by FPtje** [comment]
Exactly, meaning you can't rely on it to decide whether to log the use of a chat command.

**Comment by mcNuggets1** [comment]
These commands can be changed to support the success value by developers, the same developers using the hook.

**Comment by FPtje** [comment]
Keywords **can** be, as opposed to **must** be. For developers writing chat commands, not including the `success` return value has **no** consequences __whatsoever__. They will not add them. Even if some do, you **fundamentally** cannot **ever** trust the hypothetical `success` argument in the hook to reliably indicate whether the chat command was a success.

Your use case, logging chat command use, would specifically not log use of chat commands created by third party addons. Even if there's one addon that doesn't update, that makes your logging system unreliable.

**Comment by mcNuggets1** [comment]
I wrote all of my chatcommands by my own, so I won't have the problems you speak of.
Nearly no dedicated developer will have those, because they have the power to change code.
In order to update things, there has to be little sacrifices.

A sacrifice like this is not even important, nor does break anything currently.
Developers should just be made aware of the case it can return '""' by older addons.

**Comment by FPtje** [comment]
I find the unreliability of it a fundamental design flaw. If it were added in the beginning, one could throw an error when success is not returned, or have success be the first return argument. Now it can be forgotten, and the consequences will be for someone else.

That's a design flaw.

**Comment by mcNuggets1** [comment]
You are right.
It is.

But now we are at a point, we have a hook which is not even useful and has major flaws and there is the way to enhance the hook usage, but if we go on and do that, only DarkRP by default will have the success argument boolean set to something.

Not doing anything isn't the right solution, I think.

**Comment by FPtje** [comment]
There are more options between not doing anything and the success return value implementation.

**Comment by mcNuggets1** [comment]
I only guess adding a second hook for this functionality.
