### ISSUE TITLE
Cleanup_advert_billboards missing

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2851]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The translation got replaced in #2844 while it is used

**Comment by FPtje** [comment]
Damnit, I forgot to push again
