### ISSUE TITLE
GetWeapons shouldn't use ipairs to loop through

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2854]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
It's in the DarkRP code a few times.
https://github.com/Facepunch/garrysmod-issues/issues/3052

**Comment by Kefta** [comment]
There's an instance in FAdmin too.

**Comment by FPtje** [comment]
This is one of the reasons I hate micro-optimisations. They don't add any value and they can break things if you apply them en masse without *very* careful consideration.

**Comment by Kefta** [comment]
Knowing an API is just as important as knowing an API's bugs /s
