### ISSUE TITLE
FFP ERROR

### ISSUE THREAD

**Issue by ikTray** [FPtje/DarkRP#2855]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
FFP ERROR

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Maybe wiremod cause this which is no longer on my server. I was banning models and tools in the FFP menu. Can this be an addon causing this?

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:541: attempt to index field 'Access' (a nil value)
1. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:541
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Falco's Prop Protection

**Comment by FPtje** [comment]
The error means something is messed up with FAdmin. Almost as if it didn't load properly. Look for earlier errors.

Also, did you disable FAdmin? If so, how?

**Comment by ikTray** [comment]
Yes, I have disabled FAdmin in darkrp modification.

**Comment by Bo98** [comment]
Something, god knows what, is setting the FAdmin variable.

I suppose FPP could be use CAMI more instead, where feasible.

**Comment by ikTray** [comment]
I have enable Fadmin and this error is now fixed

**Comment by FPtje** [comment]
Referring to CAMI is indeed a good idea. There's no need to be FAdmin specific here. Also, FPP already includes CAMI.
