### ISSUE TITLE
Door Ram "canRam" hook

### ISSUE THREAD

**Issue by djtb2924** [FPtje/DarkRP#2856]
### Description of the bug
There currently is no a hook, for the canRam function, used to know if an object of a player can be rammed.
I would like it to exist because I have an addon that opens all doors in a defined period of time.
I could have put GAMEMODE.Config.doorwarrants to false temporarily but it does not work for fading doors

### How to make the bug happen
not a bug

### Lua errors
none

### Why the developer of DarkRP is responsible for this issue
Because it's in DarkRP

**Comment by Bo98** [comment]
https://wiki.darkrp.com/index.php/Hooks/Shared/canDoorRam

**Comment by djtb2924** [comment]
How fp{} works ?

Théo

Le 9 mars 2019 à 02:39, Bo Anderson <notifications@github.com<mailto:notifications@github.com>> a écrit :


https://wiki.darkrp.com/index.php/Hooks/Shared/canDoorRam

**Comment by Bo98** [comment]
It creates a "partial function" so if you have something like this

```lua
function multiply(a,b)
    return a * b
end
```

You can do something like this: 

```lua
local scaler = fp{multiply, 3}
```

which creates a new function with the same behaviour as `multiply` but the first argument is always set to 3. Then you can use it like `scaler(2)` and you'll get the value `6` returned. 

In short, don't worry about it. It is not necessary that you know about it nor do you need to use it at all in your own addons. It was just used as a shorthand in some places of DarkRP's codebase.
