### ISSUE TITLE
Hitman bug

### ISSUE THREAD

**Issue by djtb2924** [FPtje/DarkRP#2859]
### Description of the bug
When a hit is accepeted but the buyer of the hit disconnect, it throws an error

### How to make the bug happen
Be hitmen, take a hit, kick the customer, see the bug

### Lua errors
```[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua" on line 105.
The best help I can give you is this:

Attempt to call Name/Nick/GetName on a non-existing player!

Hints:
	- No hints, sorry.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/gamemode/modules/base/sh_entityvars.lua on line 105
	2. gamemodes/darkrp/gamemode/modules/hitmenu/sv_init.lua on line 181
	3. gamemodes/darkrp/gamemode/modules/hitmenu/sv_init.lua on line 206
------- End of Simplerr error -------```

**Comment by mcNuggets1** [comment]
The hit should be aborted.

**Comment by FPtje** [comment]
As it is, in the `PlayerDisconnected` hook called `Hitman system`, unless the `PlayerDisconnected` hook is prevented from running.

The error is gone now. Good luck with that addon that's breaking random other player disconnected related stuff in the server.
