### ISSUE TITLE
spawned_weapon invalid phys error

### ISSUE THREAD

**Issue by FPtje** [FPtje/DarkRP#2861]
The following error was sent to me:

![spawned_weapon error](https://user-images.githubusercontent.com/1202014/54786586-8a597780-4c29-11e9-8b89-d7bdb1939003.png)

Looks like there is a fallback in `spawned_weapon` that isn't firing. It's probably better to provide a hint as to which weapon is doing it. Then the fallback code can be removed.

**Comment by Kefta** [comment]
It's failing because spawned_weapon is trying to create physics for a viewmodel and not a worldmodel. I've clarified this in https://github.com/FPtje/DarkRP/pull/2862.

**Comment by Bo98** [comment]
Indeed it is, but the problem is that it doesn’t say which weapon class spawned_weapon is internally using.

**Comment by Kefta** [comment]
You should do the model physics checks on class registration instead of at spawn then.

**Comment by Bo98** [comment]
spawned_weapon covers any SWEP due to weapon dropping functionality, unless you are suggesting to iterate through them on load?

**Comment by Kefta** [comment]
That is exactly what I'm suggesting, or when a new SWEP is registered.
