### ISSUE TITLE
Error from weapon checker

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2866]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
[ERROR] gamemodes/darkrp/entities/weapons/weaponchecker/shared.lua:228: attempt to call method 'SetClip1' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/weaponchecker/shared.lua:228

Unknown how this is caused.

**Comment by Bo98** [comment]
This might happen if a weapon was confiscated and the player obtained the same weapon through other means before their confiscated weapons are returned.

**Comment by FPtje** [comment]
Can confirm. I would have expected `:Give` to return the weapon owned by the player, but apparently it's another function that can put a knife in your back when you're not watching.

**Comment by mcNuggets1** [comment]
It returns the weapon given to the player, not the weapon already holding.

**Comment by FPtje** [comment]
NULL makes me angry. I see NULL, I get angry. I saw NULL, so I got angry.

**Comment by mcNuggets1** [comment]
I know you've had your history with NULL, you already stated that a lot.

**Comment by FPtje** [comment]
Yes, I do. I hate NULLS. There is a promised land where NULL does not exist. I have seen the light, and it is beautiful.

**Comment by Kefta** [comment]
I'm still living in my object oriented/NULL reference haven and loving it.

**Comment by FPtje** [comment]
Blasphemy
