### ISSUE TITLE
TipJar Frozen In Air

### ISSUE THREAD

**Issue by Potatosayno** [FPtje/DarkRP#2867]
### Description of the bug
[//]: Sometimes, out of nowhere, Tipjars would be frozen mid-air, no-colided and unscripted, they would stay there frozen, cleaning decals would do nothing and this happened multiple times, Imagine placing down an entity which is walkable through and isn't apart of anyone, not moveable or removeable.
**IMAGE:** https://i.imgur.com/b8RJImj.jpg

### How to make the bug happen
[//]: I'm not 100% sure on what causes it, but by guess I'm pretty sure the Tipjars are from disconnected players, where their model wouldn't get removed properly.

### Lua errors
[//]: No errors.

### Why the developer of DarkRP is responsible for this issue
[//]: Tipjars come with DarkRP.

**Comment by Bo98** [comment]
Hmm, tip jars are a bit different due to their use of clientside models, though it should be removed: https://github.com/FPtje/DarkRP/blame/master/entities/entities/darkrp_tip_jar/cl_init.lua#L27 (dev side note: why not use `ENT:OnRemove`?).

How often is this happening?

**Comment by Bo98** [comment]
Or maybe it’s PVS related. What if the serverside entity leaves PVS and stops drawing? Maybe the CSEnt is sticking at the last drawing position?

https://github.com/Facepunch/garrysmod-issues/issues/861

**Comment by Potatosayno** [comment]
This doesn't happen too often but it did happen alot of times, I would put it as 1-2 a day.
I'm not sure if it is PVS related.

**Comment by FPtje** [comment]
Tipjars freeze in the air when I `SetPos` them to some crazy position, but when I TP them back the clientside model is re-attached. When I remove the tipjar while in a crazy position, the clientside model is removed too.

**Comment by Potatosayno** [comment]
Are you sure though?, I mean this problem clearly would have to do with something in the code, there must be a flaw somewhere.

**Comment by FPtje** [comment]
Yeah, I'm not sure what it is, but so far I'm unable to reproduce it.

**Comment by Kefta** [comment]
I have a hunch - try disabling automatic rendering on the csmodel and drawing it manually in the ENT:Draw hook when self:IsDormant() is false.

**Comment by Bo98** [comment]
I agree to that approach, but I’ll ask whether the IsDormant check is necessary: is ENT:Draw called when not in the PVS?

**Comment by Kefta** [comment]
That's what I'm unsure of - I'm unable to test for a few days, but as having a dormant entity that is still somehow in the render bounds is extremely unlikely, I doubt it.

**Comment by mcNuggets1** [comment]
Draw is only called when something is actually drawn and within the PVS.
I wish there were functions to determine when Draw is called, but I made a extremely ugly hack to determine it, so I know it's basically only called within render bounds in PVS.

Just add an extra SafeRemoveEntity to the OnRemove ENT hook.
It should do the trick.

**Comment by FPtje** [comment]
I vaguely remember trying to draw the clientside model manually, and that it was an extreme pain to get it stable, resized and rotating.

**Comment by FPtje** [comment]
I guess I did something wrong last time. The commit above seems to fix it.
