### ISSUE TITLE
/wanted /warrant etc. like commands

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2868]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If you for example write /wanted it says, you have to specify a reason, while you have to specify a name.
This is the same for /warrant and maybe even more commands.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
above

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
their addon

**Comment by mcNuggets1** [comment]
Maybe put everything TARGET related in front of reason related.
Because reason is a second argument and if something is wrong with the first argument, it should say so.

**Comment by FPtje** [comment]
Isn't that what I did?

**Comment by mcNuggets1** [comment]
Only with one check.

**Comment by mcNuggets1** [comment]
Actor doesnt exist, Must be alive etc. is still behind.

**Comment by FPtje** [comment]
That doesn't matter much imo, the actor is the one calling the command

**Comment by mcNuggets1** [comment]
The alive status, correct job does matter still.

**Comment by FPtje** [comment]
No it doesn't. It means that when you both get the reason wrong AND you're dead, that you'll get the reason error rather than the alive error. Same with the wrong job. Both are problems you need to fix.

**Comment by mcNuggets1** [comment]
So a new player for example enters the whole command in chat.
Fixes the invalid receiver, the invalid reason just to get to know, they are in the wrong job.
Doesn't sound right to me.
