### ISSUE TITLE
Length limits for reasons

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2869]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Currently there are no lenght limits for reasons, but there should be.
Players can specify absurdly long reasons for wanteds etc. which go across the whole screen which shouldn't be working.

**Comment by RomnDeveloper** [comment]
Thanks
