### ISSUE TITLE
Small issue with the ban system

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#2870]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

What I'm going to describe is a small problem that seems insignificant but I've already seen topics (like [this](https://mtxserv.com/forums/threads/bug-ban-du-serv.55527/), it's a french forum) on some forums that complained about it.

If an administrator wants to ban a player but does not have time to validate the action due to a crash or disconnection, the player who was targeted will not be able to reconnect until the server restarts. If it connects without restarting the server, it will always be expelled when it connects for the "Getting banned" reason.

In one case, this cannot be considered a problem because if the administrator wanted to ban a player but didn't have time to do so, the player should still be banned (except that this is not the case, as he can join again after a server restart). But in another case, since the administrator cannot do his action until the end, then it should be cancelled in a certain logic.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

- An administrator clicks on the "Ban" button on a player.
- _The player sees the ban screen._
- The administrator crashes or disconnects from the server.
- _The player still sees the ban message._
- _If the player reconnects, he will be kicked for the reason "Getting banned"._

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None, but I have some tracks related to this issue.

https://github.com/FPtje/DarkRP/blob/fd95cf68e6a01a1b0522c4a989d4512fc0fb202d/gamemode/modules/fadmin/fadmin/playeractions/kickban/sv_init.lua#L54-L58
https://github.com/FPtje/DarkRP/blob/fd95cf68e6a01a1b0522c4a989d4512fc0fb202d/gamemode/modules/fadmin/fadmin/playeractions/kickban/sv_init.lua#L148-L152

It seems that when the administrator presses the ban button, the player's steamID is saved in a table. But if the administrator crashes/disconnects while doing this action, the steamID will never be removed from the table and the menu will never be removed. The only way for the player to reconnect without being kicked is after a server restart.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

The FAdmin is an administrator tool provided with the DarkRP.

**Thank you for taking the time to read this. Have a good day!**

**Comment by FPtje** [comment]
Fixed
