### ISSUE TITLE
Invalid fonts in DarkRP

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2871]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Fonts like Default and ChatFont doesn't exist but is used in DarkRP.
They are defaulted to "Tahoma" for Windows and "Verdana" for everything else.

So basically everything is just defaulted to those 2 fonts which isn't currently working.
Trebuchet18, Trebuchet24 also doesn't exist, but don' know if it is used in DRP.

**Comment by FPtje** [comment]
Were they removed or something?

**Comment by mcNuggets1** [comment]
They never existed. They just default to the fallback font.

https://wiki.garrysmod.com/page/Default_Fonts

First few lines explains it.

**Comment by Bo98** [comment]
Trebuchet doesn't apply here - DarkRP creates them with it set to "Trebuchet MS" which should be correct: https://github.com/FPtje/DarkRP/blob/fd95cf68e6a01a1b0522c4a989d4512fc0fb202d/gamemode/modules/base/cl_fonts.lua#L22-L48

**Comment by Bo98** [comment]
To clarify the issue here: the font attribute in the FontData structure you pass specifies the font family to load from the system or local file. Default and ChatFont should be thought of as font definitions ready-created by a surface.CreateFont-like system. They’re not font families from a font file. Inheritance also does not exist for surface.CreateFont.

The behaviour of “Default” using the fallback font probably happens to match the intended behaviour, even though it’s technically incorrect.

**Comment by mcNuggets1** [comment]
Trebuchet MS is correct, yes

**Comment by mcNuggets1** [comment]
Trebuchet MS is correct, yes

**Comment by mcNuggets1** [comment]
Default is Tahoma or Verdana.
Not VERDANA only.

**Comment by FPtje** [comment]
Verdana looks fine in my tests.

**Comment by mcNuggets1** [comment]
But it's Tahoma for Windows and Verdana for Linux and MacOS.

**Comment by mcNuggets1** [comment]
https://i.imgur.com/4e7ctC5.png

**Comment by FPtje** [comment]
I acknowledge that I'm changing the look of things in Windows by setting it to Verdana. I've tried both Tahoma and Verdana and decided that Verdana looks better. For a consistent experience among all OSes and because I'm lazy I decided that everyone's going to stare at Verdana fonts from now on.

**Comment by Bo98** [comment]
Tahoma and Verdana is very similar anyway. Character width is the main difference.

I do ask though, is Verdana installed by default on Ubuntu? I know Tahoma isn't. If not, the DejaVu Sans fallback will suffice. It is already used as a Tahoma fallback (line 5).

**Comment by mcNuggets1** [comment]
Verdana is the fallback font for every OS besides Windows it seems.

**Comment by Bo98** [comment]
Well, considering Linux came later that could well be an oversight.

I suppose the game will still fallback to whatever on Linux if it's not installed and it's just a question of which font it chooses.
