### ISSUE TITLE
Can't see items you cant afford.

### ISSUE THREAD

**Issue by Monstrocity** [FPtje/DarkRP#2872]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
No one can see entities they can't afford.

### How to make the bug happen
GM.Config.hideNonBuyable = true
GM.Config.hideTeamUnbuyable = true
This is what i have it set to in my darkrpmodification folder

### Why the developer of DarkRP is responsible for this issue
I have no idea how to fix this, and doesn't seem like anything else would cause it other than a bug within DarkRP.

**Comment by mcNuggets1** [comment]
Do you use a custom F4 menu?

**Comment by Monstrocity** [comment]
It's supposed to be true but yea I don't know why I didn't check my f4 menu addon thanks
