### ISSUE TITLE
Dynamic voice doesn't seem to work

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#2875]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Some time ago, I tried to fix a recurring DarkRP problem on my server: hearing players behind walls or if they are not in the same room. I then searched the DarkRP settings and found the parameter :

`-- dynamicvoice - Enable/disable whether only people in the same room as you can hear your mic.
GM.Config.dynamicvoice                  = true`

Although the setting is already enabled by default, I have tested many times on different maps but it seems that players can hear other players while they are behind a wall, a door, or not in the same room.

On the workshop, there are some addons like [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=1165131683), which allows to fix this problem with more or less success.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

A player **A** stands behind a wall, a player **B** stands on the other side. Player **A** hears player **B** while they are not in the same room.

Tested on [rp_city24_v2](https://steamcommunity.com/sharedfiles/filedetails/?id=1542655022) with the latest version of DarkRP with the default settings (no addon installed).

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None but I have some tracks concerning the code that detects if the players are in the same room.

https://github.com/FPtje/DarkRP/blob/690877fa93bf86c188211382da10b81701831a44/gamemode/modules/base/sv_gamemode_functions.lua#L289-L296
https://github.com/FPtje/DarkRP/blob/690877fa93bf86c188211382da10b81701831a44/gamemode/modules/base/sv_gamemode_functions.lua#L305-L315

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

The modification of the voice system is included by default in the DarkRP gamemode.

**Thank you for reading this. Have a good day!**

**Comment by FPtje** [comment]
Nice find!
