### ISSUE TITLE
Range for creating shipments

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2877]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Range for creating and splitting shipments is way too low.
I would recommend 40000 as range, because right now, you have to nearly kiss the weapon to make it a shipment.

**Comment by FPtje** [comment]
1 source unit is said to be about 1 inch. 40000 inch is 1016m, that's more than a kilometer. Current max distance is 130 units.  That's 3 meters. Most actions accept only a shorter distance (locking doors, ramming vehicles, checking weapons, etc.)

**Comment by mcNuggets1** [comment]
40000 in DistToSqr.

**Comment by mcNuggets1** [comment]
I was talking about weapons with crazy origin positions.

**Comment by FPtje** [comment]
That's 200 units, still way more than necessary. Surely weapons aren't too big to have origin positions matter significantly?

**Comment by mcNuggets1** [comment]
Some do, M9K weapons for example.

**Comment by FPtje** [comment]
So where exactly do the M9K weapons you speak of have their origin positions? Surely not outside the actual model?

**Comment by mcNuggets1** [comment]
ive tested with a dragunov svu, it had me crouching too actually get it to a shipment.

**Comment by FPtje** [comment]
So where exactly does this dragunov svu you speak of have its origin position? Surely not outside the actual model? And if it does, surely that's a serious bug in M9K?

**Comment by mcNuggets1** [comment]
Seems it's outside of the model.
But highering the range and performing a trace check wouldn't hurt.

**Comment by Bo98** [comment]
> performing a trace check

This is already done in the form of `Vector:isInSight`, but maybe instead we could get the trace, incorporate the distance check into `endpos`, and ensure we are hitting the correct entity?
