### ISSUE TITLE
attempt to index global 'DarkRP' (a nil value) on all entities

### ISSUE THREAD

**Issue by Lukyrouge3** [FPtje/DarkRP#2878]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
The server starts correctly and when I go in game I got these errors

### How to make the bug happen
Just created a clean server without addons and install darkrp on it

### Lua errors
[DarkRP] gamemodes/darkrp/entities/weapons/arrest_stick/shared.lua:21: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/arrest_stick/shared.lua:21

[DarkRP] gamemodes/darkrp/entities/weapons/door_ram/shared.lua:251: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/door_ram/shared.lua:251

[DarkRP] gamemodes/darkrp/entities/weapons/keys/cl_menu.lua:13: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/keys/cl_menu.lua:13
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/weapons/keys/shared.lua:14

[DarkRP] gamemodes/darkrp/entities/weapons/lockpick/shared.lua:196: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/lockpick/shared.lua:196

[DarkRP] gamemodes/darkrp/entities/weapons/pocket/cl_menu.lua:9: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/pocket/cl_menu.lua:9
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/weapons/pocket/shared.lua:9

[DarkRP] gamemodes/darkrp/entities/weapons/pocket/shared.lua:110: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/pocket/shared.lua:110

[DarkRP] gamemodes/darkrp/entities/weapons/unarrest_stick/shared.lua:19: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/unarrest_stick/shared.lua:19

[DarkRP] gamemodes/darkrp/entities/weapons/weaponchecker/shared.lua:37: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/weapons/weaponchecker/shared.lua:37

[DarkRP] gamemodes/darkrp/entities/entities/darkrp_billboard/shared.lua:55: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/darkrp_billboard/shared.lua:55
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/darkrp_billboard/cl_init.lua:1

[DarkRP] gamemodes/darkrp/entities/entities/darkrp_laws/shared.lua:10: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/shared.lua:10
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:1

[DarkRP] gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:61: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/darkrp_laws/cl_init.lua:61

[DarkRP] gamemodes/darkrp/entities/entities/letter/shared.lua:12: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/letter/shared.lua:12
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/letter/cl_init.lua:1

[DarkRP] gamemodes/darkrp/entities/entities/money_printer/shared.lua:26: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/money_printer/shared.lua:26
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/money_printer/cl_init.lua:1

[DarkRP] gamemodes/darkrp/entities/entities/spawned_shipment/shared.lua:16: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/spawned_shipment/shared.lua:16
   2. include - [C]:-1
    3. unknown - gamemodes/darkrp/entities/entities/spawned_shipment/cl_init.lua:1

[DarkRP] gamemodes/darkrp/entities/entities/spawned_shipment/cl_init.lua:145: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/spawned_shipment/cl_init.lua:145

[DarkRP] gamemodes/darkrp/entities/entities/spawned_weapon/cl_init.lua:36: attempt to index global 'DarkRP' (a nil value)
  1. unknown - gamemodes/darkrp/entities/entities/spawned_weapon/cl_init.lua:36

**Comment by Kefta** [comment]
Try using a clean install with -noaddons -noworkshop in your command-line. The gamemode must be failing to load somewhere if the DarkRP table isn't even defined.

**Comment by FPtje** [comment]
Please head to forum.darkrp.com.

**Comment by KyberNetworks** [comment]
i have this issue when i reload my server its just loading before darkrp
