### ISSUE TITLE
Ability to stop FPP readding default blocked

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2881]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This is it.
I dont want default blocked entities.

**Comment by Bo98** [comment]
Block _entities_ yes? It should already be covered by this in theory unless you think it's bugged: https://github.com/FPtje/Falcos-Prop-protection/commit/7ad1e6dd5a858392c935e2f782130dbaf870f1fa

**Comment by mcNuggets1** [comment]
Makes sense then.
