### ISSUE TITLE
Lua lockpick errors

### ISSUE THREAD

**Issue by djtb2924** [FPtje/DarkRP#2887]
### Description of the bug
Lua errors

### How to make the bug happen
I just connected to the server

### Lua errors
![image](https://user-images.githubusercontent.com/26027040/57087155-bcb5c480-6cff-11e9-9538-220dc8047082.png)

### Why the developer of DarkRP is responsible for this issue
I don't know if is it related to new update of GMod or DarkRP

**Comment by FPtje** [comment]
It's a bad install

**Comment by djtb2924** [comment]
Of GMod or Darkrp ?

**Comment by roboderpy** [comment]
gmod

**Comment by djtb2924** [comment]
Thanks
