### ISSUE TITLE
 lua/includes/extensions/table.lua:100: bad argument #1 to 'pairs' (table expected, got number)

### ISSUE THREAD

**Issue by ghost** [FPtje/DarkRP#289]
I recently made a post on git about a bad bad bad no good error. And now, I have its evil twin.

I had this error before the bad bad bad no good error, but could not fix.
The error is the following:
[ERROR] lua/includes/extensions/table.lua:100: bad argument #1 to 'pairs' (table expected, got number)
 I did some research, and wasn't this error supposed to be patched? I am running the latest version of darkrp from svn.
And I get this error when pressing F4:

[ERROR] lua/includes/extensions/table.lua:100: bad argument #1 to 'pairs' (table expected, got number)
1. pairs - [C]:-1
   1. HasValue - lua/includes/extensions/table.lua:100
   2. Update - gamemodes/darkrp/gamemode/client/showteamtabs.lua:626
      1. EntitiesTab - gamemodes/darkrp/gamemode/client/showteamtabs.lua:674
      2. Function - gamemodes/darkrp/gamemode/client/vgui.lua:258
      3. unknown - lua/includes/modules/usermessage.lua:87

The addons I have installed are:
rp_downtown_v4c
Evolve
Durgz

Also, here is a video that shows the error. I made it for this post.
http://youtu.be/Te81iiB_n5o

**Comment by Gamerpro2266** [comment]
i got it as well
