### ISSUE TITLE
duplication of ammunition

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2890]
With the latest changes, by throwing a weapon and re-grabbing it, the ammunition doubles and accumulates (m9k)

SWEP.Primary.ClipSize			= 8		-- Size of a clip
SWEP.Primary.DefaultClip		= 45		-- Bullets you start with

this occurs when ammunition default is greater than that of the clip

**Comment by FPtje** [comment]
@mcNuggets1

**Comment by mcNuggets1** [comment]
I'll take a look at it.

**Comment by mcNuggets1** [comment]
Oh yeah, we need to use ClipSize for Clip1, not DefaultClip.
DefaultClip is the spare ammo.
I misunderstood.

**Comment by mcNuggets1** [comment]
For clarifcation:
There once was some sort of bug for me with whoever picking up a weapon, getting additional ammo.
I then went on to make my own gun base and set DefaultClip to be the same as ClipSize for every weapon.

That's where my thinking comes from, that DefaultClip has to be equivalent to ClipSize.
In the end it was a misunderstanding and related to some sort of bug, I wasn't able to fix or locate.

I think it was related to the DropWeapon function giving you addtional ammo whenever you pickup a weapon you just dropped.

I've submitted a pull request.

**Comment by matiasg90** [comment]
I've tried your last update, and the same thing keeps happening.

SWEP.Primary.ClipSize			= 100		-- Size of a clip
SWEP.Primary.DefaultClip		= 200		-- Bullets you start with

Each time I release and grab the weapon, this adds 100 bullets

**Comment by mcNuggets1** [comment]
Oh, yeah.
I see.

This wasn't the only issue.

The function Give actually gives you ammunation on spawn.
I also found a few other instances, where ammo could be lost or gained.

I'll fix all of these.

**Comment by mcNuggets1** [comment]
I've tested myself.
Everything is working for me now.

I wish the ammo system were consistent and C++ weapons would work with DarkRP though, but that ain't possible with the current implementation.

**Comment by FPtje** [comment]
Should be fixed now then.
