### ISSUE TITLE
DarkRP.createEntity suggestion

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2892]
A long time ago, when this function was updated. This problem arose that although it helps other things, others are not benefited.
The problem is that when a person buys an entity, it stays on the server until the user disconnects or changes jobs.

This precludes a job such as the doctor, who sells medicine packs, or armored vests, etc.

My idea would be that a bypass can be added for certain entities that do not have to be eliminated when changing jobs or disconnecting from the game.

If this goes on the forum, I'm sorry.

**Comment by FPtje** [comment]
There's a config option `preventClassItemRemoval`, you can put the entity's class in there.

**Comment by matiasg90** [comment]
oh what a fool I am, it's true
