### ISSUE TITLE
Model Scale issue

### ISSUE THREAD

**Issue by Dinnerspy** [FPtje/DarkRP#2895]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
modelScale in dark rp job creation is not working.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
since may 3 could of been longer did not notice until then. i have the model scale implement like so.   modelScale = 0.7,

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none that i could see in regards to dark rp.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

its a base dark rp function.

**Comment by LarryTheBoss** [comment]
I am currently experiencing the same issue. I fixed it by adding this to my job code. `PlayerSpawn = function(ply) timer.Simple(0.1, function() ply:SetModelScale(0.5, 1) end) end,`

**Comment by Bo98** [comment]
It currently gets set in `PlayerLoadout` which is perhaps too early (it is before the model is actually set). Though I'm not sure what change in GMod could caused the behaviour to change.

**Comment by FPtje** [comment]
![hl2_2019-05-11_11-42-27](https://user-images.githubusercontent.com/1202014/57568026-e0ed6180-73e1-11e9-8382-a661c1fc3be1.jpg)
It works for me on a listen server, even after several respawns. I'm gonna go on a limb and say the hook is probably not being called because of a bad addon.

**Comment by KyberNetworks** [comment]
been having this issue to in jobs.lua i have a job set as modelScale = 0.66, but when they spawn they are normal size

**Comment by koppcsi** [comment]
Putting modelScale after the spawning function made it work for me again. So like:

"PlayerSpawn = function(ply)
        ply:SetMaxHealth(300)
        ply:SetHealth(300)
        ply:SetArmor(150)
    end,
    modelScale = 0.6,"

**Comment by Kefta** [comment]
That has absolutely no effect. Hash tables aren't ordered.

**Comment by koppcsi** [comment]
That's what made it work for me, what's suppose to work or how it's suppose to work never bothered gmod anyway. Because nothing else made it work for me but this, I thought I'd share it. If it works for someone else cool if it doesn't then soz.

**Comment by Kefta** [comment]
There's no way that works, something else must have changed.
