### ISSUE TITLE
Weaponchecker should check for pocket items using the "getPocketItems" function

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2896]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Currently pocket hides weapons from the weapon checker. (Also it should be able to strip those)
It doesn't make sense, because the weapon checker should check for weapons in your pocket and on your body.

Currently there are no developer functions to add support for this either.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
not a bug

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
no lua error

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
their weapon

**Comment by FPtje** [comment]
That's not in the scope of the weapon checker. You can create a derived SWEP and override `GetStrippableWeapons`.
