### ISSUE TITLE
FAdmin problems

### ISSUE THREAD

**Issue by Crazynator04** [FPtje/DarkRP#2904]
I tried to add myself to superadmin in FAdmin, but it doesn't work. I tried it with the Tab-Menu and also with the console. I isn't working and I don't know why.
So first I tried: 

] rcon FAdmin setroot Kyle
ServerLog: FAdmin: User set to superadmin!
FAdmin: User set to superadmin!
ServerLog: [FAdmin] unknown set the usergroup of IT ST Kyle van Bom to superadmin
[FAdmin] unknown set the usergroup of you to superadmin

I tried to do anything, but it just says: "No access!"

After that i tried:
] rcon fadmin setaccess "STEAM_0:1:171120086" superadmin

[ERROR] gamemodes/militaryrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:328: attempt to index a nil value
  1. callback - gamemodes/militaryrp/gamemode/modules/fadmin/fadmin/access/sv_init.lua:328
   2. unknown - gamemodes/militaryrp/gamemode/modules/fadmin/fadmin/commands/sv_concommands.lua:19
    3. unknown - lua/includes/modules/concommand.lua:54

Now I don't know what to do, so please help me fix this.

**Comment by FPtje** [comment]
Looks like a problem with the default groups. I reckon there's a Lua error on startup. Always look for errors on startup when weird stuff happens.

Also, this is not a help forum. Please continue this line of in inquiry on forum.darkrp.com.
