### ISSUE TITLE
idek

### ISSUE THREAD

**Issue by KenWa51** [FPtje/DarkRP#2908]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Can't get the gamemode to work.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Just download ig?

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/libraries/tablecheck.lua:157: attempt to call field 'IsEmpty' (a nil value)
  1. f - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:157
   2. f - gamemodes/darkrp/gamemode/libraries/fn.lua:185
    3. v - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:67
     4. f - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:85
      5. validateJob - gamemodes/darkrp/gamemode/libraries/fn.lua:174
       6. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:416
        7. unknown - gamemodes/darkrp/gamemode/config/jobrelated.lua:8
         8. include - [C]:-1
          9. unknown - gamemodes/darkrp/gamemode/init.lua:104

[ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua" on line 30.
The best help I can give you is this:

A table is being indexed by something that does not exist (table index is nil).

Hints:
        - The thing between square brackets does not exist (is nil).

The responsibility for the error above lies with (the authors of) one (or more) of these files:
        1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 30
        2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
        3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
        4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 138
        5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 149
        6. gamemodes/darkrp/gamemode/init.lua on line 111
------- End of Simplerr error -------

  1. error - [C]:-1
   2. doInclude - gamemodes/darkrp/gamemode/libraries/simplerr.lua:530
    3. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.luCouldn't Load Init Script: 'darkrp/gamemode/init.lua'

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

I couldn't find a solution to this error.

**Comment by KenWa51** [comment]
Oddly enough when I re-downloaded the gmod server from steam cmd it started working again.

**Comment by KenWa51** [comment]
Never mind not the same error but now there are no errors on start up and i get the following:

https://pastebin.com/raw/akDB2uH6

**Comment by Kefta** [comment]
Your first error was from having an outdated GMod server (see https://github.com/FPtje/DarkRP/pull/2899#issuecomment-493464263), your new errors are from not having ULib installed. This isn't the place for help though, see https://forum.darkrp.com

**Comment by KenWa51** [comment]
Since when was ulib required for darkrp?

**Comment by Kefta** [comment]
It's not, but it is required for your sv_utime script you have installed causing errors.

**Comment by KenWa51** [comment]
Oh okay thanks for the help :)
