### ISSUE TITLE
DarkRP oofing its self?

### ISSUE THREAD

**Issue by LukeboticAndDelixto** [FPtje/DarkRP#2910]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I start up my server and I see this (I removed all addons and darkrp mod and put it back and it did not fix it): 
[DarkRP] gamemodes/darkrp/gamemode/libraries/tablecheck.lua:157: attempt to call
 field 'IsEmpty' (a nil value)
  1. f - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:157
   2. f - gamemodes/darkrp/gamemode/libraries/fn.lua:185
    3. v - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:67
     4. f - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:85
      5. validateJob - gamemodes/darkrp/gamemode/libraries/fn.lua:174
       6. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:
416
        7. unknown - gamemodes/darkrp/gamemode/config/jobrelated.lua:8
         8. include - [C]:-1
          9. unknown - gamemodes/darkrp/gamemode/init.lua:104

[DarkRP] A runtime error has occurred in "gamemodes/darkrp/gamemode/libraries/ta
blecheck.lua" on line 157.
The best help I can give you is this:

'IsEmpty' is being called like it is a function, but in reality it does not exis
t (is nil).

Hints:
        - You are doing either stuff.something(<otherstuff>) or stuff:something(
<otherstuff>). The 'something' here does not exist.

The responsibility for the error above lies with (the authors of) one (or more)
of these files:
        1. gamemodes/darkrp/gamemode/libraries/tablecheck.lua on line 157
        2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 185
        3. gamemodes/darkrp/gamemode/libraries/tablecheck.lua on line 67
        4. gamemodes/darkrp/gamemode/libraries/tablecheck.lua on line 85
        5. gamemodes/darkrp/gamemode/libraries/fn.lua on line 174
        6. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 416

        7. addons/darkrpmodification/lua/darkrp_customthings/jobs.lua on line 19

        8. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
        9. gamemodes/darkrp/gamemode/lCouldn't Load Init Script: 'darkrp/gamemod
e/init.lua'

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Bo98** [comment]
Update your GMod server. It is outdated.

**Comment by LukeboticAndDelixto** [comment]
Ok Thanks
Wait, how do I upgrade it?

**Comment by Bo98** [comment]
It depends on your host. Most have an option in the control panel.

If you are hosting it yourself, then it's the same way as you installed it.
