### ISSUE TITLE
Some vehicles return a script error when spawning

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#2911]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

When some vehicles are spawn, a script error is created. The vehicles concerned are essentially from the workshop and not from Half-Life 2.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

For the test I downloaded a pretty old but popular addon on the HL2RP servers : https://steamcommunity.com/sharedfiles/filedetails/?id=118997241

When you spawn the vehicle, a script error is created.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

```
[DarkRP] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:210: attempt to call method 'GetVehicleClass' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:210
   2. MakeVehicle - gamemodes/sandbox/gamemode/commands.lua:907
    3. Spawn_Vehicle - gamemodes/sandbox/gamemode/commands.lua:947
     4. unknown - gamemodes/sandbox/gamemode/commands.lua:964
      5. unknown - lua/includes/modules/concommand.lua:54
```

When `ent:GetClass()` is called, it returns correctly `prop_vehicle_zapc` but `ent:GetVehicleClass()` does not work.
https://github.com/FPtje/DarkRP/blob/92195cef39d559fb13145f3c873ff0a66f3bda40/gamemode/modules/base/sv_gamemode_functions.lua#L208-L211

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Because a modification of the vehicle spawn logs was made on March 3rd by FPtje : https://github.com/FPtje/DarkRP/commit/9e5600011f9d603d4d81f04b22c979a56967b28e#diff-83bcce15642562f9a0a8436b17fce01f

**Comment by Bo98** [comment]
This will be because some custom vehicles don't use the Vehicle metatable and are just spawned as regular entities.

**Comment by mcNuggets1** [comment]
(ent.GetVehicleClass and ent:GetVehicleClass() or "Unknown")

**Comment by Kefta** [comment]
Just fallback to GetClass instead of "Unknown"

**Comment by mcNuggets1** [comment]
GetClass is used already.
