### ISSUE TITLE
Lua problem

### ISSUE THREAD

**Issue by Heliclaster** [FPtje/DarkRP#2915]
I changed /lua/darkrp_config/settings.lua
------- End of Simplerr error -------

[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua" on line 714.
The best help I can give you is this:

DarkRP was unable to introduce player "Heliclaster" to the game. Expect further errors and shit generally being fucked!

Hints:
	- This error most likely does not stand on its own, and previous serverside errors have a very good chance of telling you the cause.
	- Note that errors from another addon could cause this. Specifically when they're thrown during 'PlayerInitialSpawn'.
	- This error can also be caused by some other addon returning a value in 'PlayerInitialSpawn', though that is less likely.
	- Errors in your DarkRP configuration (jobs, shipments, etc.) could also cause this. Earlier errors should tell you when this is the case.

The responsibility for the error above lies with (the authors of) one (or more) of these files:

------- End of Simplerr error -------

**Comment by FPtje** [comment]
Read the error and help can be found on the forum.darkrp.com

**Comment by FPtje** [comment]
Specifically read the very first hint.
