### ISSUE TITLE
The F1 menu default page is no longer displayed

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#2917]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

It's not really but a bug but a problem. Due to the age of the Garry's Mod browser (thanks Awesomium), it is impossible to display the default page of the F1 menu.

I suggest that while waiting for Garry's Mod to switch to Chromium, to change the default page to the DarkRP forum page.

[The page is displayed correctly and allows you to navigate without any problems](https://imgur.com/a/OY0ij1q), see #2916.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Press key F1.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None but the page displays a blank page with a message saying that the [browser is no longer supported](https://imgur.com/a/wYjuDCR).

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

Because it is the default page even if it can be modified by servers owners.

**Comment by mcNuggets1** [comment]
Probably Awesomium related.

**Comment by FPtje** [comment]
Fixed in #2916
