### ISSUE TITLE
Disable chatlisteners

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2918]
This is more of a suggestion.

I just wanna disable chatlisteners, without the whole chatsystem.

**Comment by FPtje** [comment]
Do you mean local chat, the little text you see when opening the chat box, the chatlisteners system embedded in many chat commands (yell, whisper, etc.) or the people actually listening to chat?

**Comment by mcNuggets1** [comment]
Just the little text box which says, who can hear you.
It's all included in cl_chatlisteners.lua in the chat module.

**Comment by mcNuggets1** [comment]
The code is still running.
Disabling the whole load of the file using the disabled modules would be a better fit for this issue.

**Comment by mcNuggets1** [comment]
The new implementation isn't any better.
It should now only work with chat and not with disabling the voice indicator.
I meant, I wanted to disable the general load of the whole file, so I can do my own chatlisteners module.
