### ISSUE TITLE
FAdmin "No Access"

### ISSUE THREAD

**Issue by Heiser1** [FPtje/DarkRP#2919]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible) Fadmin says me "No access"

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it) idk, i did nothing

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!) 

[ERROR] A runtime error has occurred in "your custom entities" on line -1.
The best help I can give you is this:

The category of "Gitara" ("Towar") does not exist!

Hints:
	- Make sure the category is created with DarkRP.createCategory.
	- The category name is case sensitive!
	- Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
your custom entities
------- End of Simplerr error -------

There is 1 Lua problem!
	Please check your console for more information!
[ERROR] A runtime error has occurred in "your custom entities" on line -1.
The best help I can give you is this:

The category of "Alkochol" ("Towar") does not exist!

Hints:
	- Make sure the category is created with DarkRP.createCategory.
	- The category name is case sensitive!
	- Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
your custom entities
------- End of Simplerr error -------

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it) cause propably he did FAdmin

I set me as superadmin, and as fadmin root.
I reinstalled darkrpmodification (i paste settings, disabled deafults, entities, categories and jobs), reinstalled darkrp gamemode, nothing works :(

When i want to change server restrictions from FAdmin from TAB it says "No access" same thing with cleanup

**Comment by FPtje** [comment]
Not a help forum

**Comment by Heiser1** [comment]
what forum???

**Comment by FPtje** [comment]
Forum.darkrp.com

**Comment by Heiser1** [comment]
omfg
