### ISSUE TITLE
Letters don't have a spawn delay

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2928]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Since nearly every entity in DarkRP has a 1 second spawn delay, I question myself, why doesn't the letter have one?
I didn't want to include this change in my pull request, because it wouldn't match the description.

**Comment by FPtje** [comment]
Because the (chat) command has a delay

**Comment by mcNuggets1** [comment]
Yeah, I see that too.
But it doesn't match with the other implementations.

It's like the only thing which spawns without a delay.
Nvm, I just thought it's weird.
