### ISSUE TITLE
Untranslated line

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2932]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

police/sv_chatcommands line 121 "You have to be mayor"

also the check in the same line can be changed with a simple isMayor() check.

Also same file line 113.

**Comment by Bo98** [comment]
> police/sv_chatcommands line 121

No, you mean chat/sv_chatcommands.lua.

> Also same file line 113.

No, you mean police/sv_commands.lua.

**Comment by mcNuggets1** [comment]
Yeah, sorry.
I was extremely tired.
