### ISSUE TITLE
Printers

### ISSUE THREAD

**Issue by JinxSEG** [FPtje/DarkRP#2933]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # When adding rprinter to entities.lua it shows the printer in the f4 menu but when i buy them in game they dont spawn anything and no error is cause just nothing spawns

### How to make the bug happen
DarkRP.createEntity("bronzeprinter", {
   ent = "rprint_bronzeprinter",
   model = "models/props_c17/consolebox01a.mdl",
   price = 1000,
   max = 1,
   cmd = "/buybronzeprinter",
   allowed = {TEAM_CITIZEN},
   spawn = function(ply, tr, tblEnt) return ents.Create("models/props_c17/consolebox01a.mdl") end, -- function to override spawning mechanics. MUST return an entity!
})

DarkRP.createEntity("diamondprinter", {
    ent = "rPrint_Base",
    model = "models/props_c17/consolebox01a.mdl",
    price = 1000,
    max = 1,
    cmd = "/buydiamondprinter",
    allowed = {TEAM_CITIZEN},
    spawn = function(ply, tr, tblEnt) return ents.Create("models/props_c17/consolebox01a.mdl") end, -- function to override spawning mechanics. MUST return an entity!
 })

That is the code I am currently using 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by Kefta** [comment]
This is not the place for script help, and you are using models instead of entity classes in ents.Create.

**Comment by JinxSEG** [comment]
Sorry bout that didnt really know where else to go and what do you mean im a bit new to all this.

**Comment by FPtje** [comment]
Forum.darkrp.com
