### ISSUE TITLE
Can't switch jobs, when both player job teams are full

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2934]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
You should be able to switch jobs using the switchjob command, but when one of the teams are full, it cancels.

Expected behaviour, both players switch jobs.

**Comment by FPtje** [comment]
I'm not bothered doing the refactoring work to fix this in a clean manner.
