### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by Alphaputin** [FPtje/DarkRP#2935]
Lua Error: gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:343: Connection failed! Can't connect to MySQL server on '192.168.178.58' (111)
Trying again in 5 seconds.

**Comment by Alphaputin** [comment]
es zeigt auch nichts in der Datenbank an, aber es funktioniert im Spiel

**Comment by Alphaputin** [comment]
it also does not show anything in the database, but it works in the game

**Comment by FPtje** [comment]
Not a help forum. Go to forum.darkrp.com
