### ISSUE TITLE
RequiresVote Issue

### ISSUE THREAD

**Issue by Potatosayno** [FPtje/DarkRP#2940]
### Description of the bug
[//]: # When this function returns false while vote = true, on the Job it will not allow you to become that job, RequiresVote is supposed to override as stated [here](https://wiki.darkrp.com/index.php/DarkRP:CustomJobFields)

### How to make the bug happen
[//]: # Simply make vote = true, on a certain job in jobs.lua and apply a RequiresVote check for it, when the check returns false you will not be able to become that job, unless vote = false,
Here's my code:
`RequiresVote = function(ply, job) return !GAMEMODE.CivilProtection[ply:Team()] end,`

### Lua errors
[//]: # None

### Why the developer of DarkRP is responsible for this issue
[//]: # This is DarkRP code, and DarkRP wiki states it should override as well, this could be confusing for people on why it does not override and the message could make it even more confusing as when this happens it prints out "This job doesn't require a vote at the moment"

Edit:
Okay I've just tested it on another server with vote = false, and RequiresVote function and now it claims I need to make a vote in order to become the job, even though I am clicking on the Job from the F4 menu?

**Comment by FPtje** [comment]
The fix is in the F4 menu. That means it won't work if you have a custom F4 menu, though it would also mean the same bug is in that custom F4 menu.

**Comment by Potatosayno** [comment]
> The fix is in the F4 menu. That means it won't work if you have a custom F4 menu, though it would also mean the same bug is in that custom F4 menu.

Weird issue, it happens for me on the default F4 menu too.

**Comment by FPtje** [comment]
This was fixed @Potatosayno 
Update DarkRP
