### ISSUE TITLE
Error When Buying Doors And Door Groups Not Working

### ISSUE THREAD

**Issue by RadiantMin3** [FPtje/DarkRP#2943]
whenever anyone buys a door it give this error
[ERROR] RunString:2: attempt to call field 'AddNetworkString' (a nil value)
1. unknown - RunString:2
2. RunString - [C]:-1
3. onsuccess - RunString:2
4. unknown - lua/includes/modules/http.lua:29

i thought it was from when i tried to add a door group which i still can't get to work, this is my door group code:
AddDoorGroup("CP And Mayor", TEAM_POLICE, TEAM_SWAT, TEAM_MAYOR)
also i don't get the option to assign a door group to a door in game, it just buys the door
--- Double Post Merged, 14 minutes ago ---
I just reinstalled DarkRP and darkrpmodification and it still gives me erorrs when i buy a door

but then i completly reinstalled the darkrp gamemode and darkrpmodification

**Comment by RadiantMin3** [comment]
i think it only gives that error now when i player logs on to the server but the door groups still don't work

**Comment by FPtje** [comment]
That's an addon

**Comment by RadiantMin3** [comment]
ok thanks
