### ISSUE TITLE
I Have A Problem And I Think Its The Darkrp Gamemode?

### ISSUE THREAD

**Issue by DarkyV1** [FPtje/DarkRP#2945]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

[ERROR] addons/ulx/lua/ulx/xgui/server/sv_bans.lua:186: bad argument #1 to 'lower' (string expected, got nil)
  1. lower - [C]:-1
   2. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:186
    3. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:72
     4. unknown - lua/includes/modules/concommand.lua:54

This pops up in console, you may class this as needing help but every forum has said it may be the darkrp gamemode conflicting with the ulx menu...

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

when i go to edit the group permissions, it says the usage rather than me being able to tick and untick the boxes for what each group can do?

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

As many forums have said the darkrp gamemode might have a bit of code in it that conflicts with this usage...

**Comment by FPtje** [comment]
Link to those forums?

**Comment by DarkyV1** [comment]
https://forums.ulyssesmod.net/index.php/topic,9131.0.html

The Response From Megiddo
4th one down

**Comment by FPtje** [comment]
That's a thread from 2015, a lot has changed since then. Surely that's not you still having the same problem since 2015?

**Comment by DarkyV1** [comment]
i think it is the problem
any idea on a fix or?

**Comment by FPtje** [comment]
To figure out what's going on I'd have to download ULX, ULib and the lot and look at the code. I can pretty safely say, though, that DarkRP is very unlikely to have anything to do with it. It appears nowhere in the given stack trace.

**Comment by DarkyV1** [comment]
so what do i do from here, the main problem is i cant change permissions through !menu

**Comment by Bo98** [comment]
Sounds to me like an addon overriding, and breaking, `RunConsoleCommand`.

I seem to recall reports of [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=297111172) but I haven’t checked the code to see if it was for your problem or something similar.

**Comment by DarkyV1** [comment]
the annoying thing is i have no idea about this stuff so i dont know what to look at haha

**Comment by DarkyV1** [comment]
do you guys have any codes i could put in to fix or?

**Comment by Bo98** [comment]
Maybe try enter `lua_run PrintTable(debug.getinfo(RunConsoleCommand))` into the server console and tell us what gets outputted.

**Comment by DarkyV1** [comment]
lua_run PrintTable(debug.getinfo(RunConsoleCommand))
> PrintTable(debug.getinfo(RunConsoleCommand))...
currentline     =       -1
func    =       function: 0x1fd368d8
isvararg        =       true
lastlinedefined =       -1
linedefined     =       -1
namewhat        =
nparams =       0
nups    =       0
short_src       =       [C]
source  =       =[C]
what    =       C

**Comment by Bo98** [comment]
Ok that's okay. So RunConsoleCommand isn't the issue. I'll see if there's anything else I missed.

**Comment by DarkyV1** [comment]
oke thanks :D

**Comment by DarkyV1** [comment]
![helpgmod](https://user-images.githubusercontent.com/54838932/64171110-c2581e00-ce49-11e9-978f-02a3a55175b3.PNG)
hey guys do i need to add something here?

**Comment by Bo98** [comment]
The issue is that it expects 6 pieces of data but it isn't receiving that. I would blame more on the whatever is sending it rather than the receiving side which is erroring.

Do other features of the menu work? Specifically, what about creating adverts? Compare this to some of the commands in the commands tab - do they work?

**Comment by DarkyV1** [comment]
ill check now

**Comment by DarkyV1** [comment]
i cant change people to other groups, adverts dont work, i also cant change the stuff in fadmin scoreboard so i just disabled it, but cant change the tool restrictions in fpp

**Comment by Bo98** [comment]
By "can't", do you mean that it it errors, does nothing, or is the option just not there? I had a theory that adding adverts might also error.

**Comment by DarkyV1** [comment]
by cant i mean it doesnt do it but in chat it says the usage of it to do it in the console: "Usage: ulx adduserid <SteamID, IP, or UniqueID> <group> - Add a user by ID to specified group." it just says that

**Comment by Bo98** [comment]
Thanks, that's useful. It means that basically everything trying `RunConsoleCommand` doesn't work properly, though I'm not entirely sure where exactly it breaks.

At this stage it's probably going to be quicker to just see whether you still have the issues without any other addons except ULX & DarkRP. If not, then add back the addons one-by-one until you find the one that breaks things.

**Comment by DarkyV1** [comment]
i tried on my previous server, it didnt change anything

**Comment by Bo98** [comment]
So it's broken with just DarkRP and ULX/ULib installed? That's bizarre.

**Comment by DarkyV1** [comment]
yeah, ive got a friend who knows lua im gonna see if he can change anything for me but i genuinely have no idea how this happened

**Comment by Bo98** [comment]
Just to rule out something else, can you try something similar to what I posted before but instead do this in the _clientside_ console when you are connected to the server - not the server console.

`lua_run_cl PrintTable(debug.getinfo(RunConsoleCommand))`

You'll need sv_allowcslua enabled for this in case you disabled that.

**Comment by DarkyV1** [comment]
] lua_run_cl PrintTable(debug.getinfo(RunConsoleCommand))
currentline	=	-1
func	=	function: 0x2c6ab1a8
isvararg	=	false
lastlinedefined	=	-1
linedefined	=	-1
namewhat	=	
nparams	=	3
nups	=	5
short_src	=	[C]
source	=	=[C]
what	=	Lua

**Comment by Bo98** [comment]
Nothing unusual there. Thanks for trying it.

**Comment by DarkyV1** [comment]
no worries

**Comment by DarkyV1** [comment]
is there a way i can add you on discord so this can be a bit quicker?

**Comment by DarkyV1** [comment]
i also get this under fpp settings
FPP_setting: Third argument (the value of the setting) not given

**Comment by Bo98** [comment]
Yeah console commands in general seem to be screwed.

You can find be via the [DarkRP Discord](https://discordapp.com/invite/h6YQtA), but I'll not be around for 2-3 hours unfortunately. I need to go out shortly.

**Comment by DarkyV1** [comment]
no worries i just need this fixed haha

**Comment by DarkyV1** [comment]
is it maybe because of a previous ulx installed thats deleted but kept some data somewhere and the server is using that rather than the new one???

**Comment by DarkyV1** [comment]
hello guys im really sorry if i wasted your time but i did the server.cfg thing and changed everything from there and somehow its fixed everything. i am really sorry if it wasted your time

**Comment by Bo98** [comment]
What server.cfg thing? I'm not sure how that broke console commands.

**Comment by DarkyV1** [comment]
i did the premade thing and restarted my whole pc im not sure how

**Comment by DarkyV1** [comment]
// Network Configuration
sv_loadingurl "https://live.gmod-lsm.com/?u=5d66af40488cd&steamid=%s"
sv_downloadurl ""
sv_allowdownload 1
sv_allowupload 0
net_maxfilesize 64

// Logging Configuration
log on
sv_logbans 1
sv_logecho 1
sv_logfile 1
sv_log_onefile 1

// Sandbox Configuration
sbox_noclip 0
sbox_godmode 0
sbox_playershurtplayers 1
sbox_maxprops 200
sbox_maxragdolls 0
sbox_maxnpcs 0
sbox_maxballoons 0
sbox_maxeffects 0
sbox_maxdynamite 0
sbox_maxlamps 0
sbox_maxthrusters 0
sbox_maxwheels 0
sbox_maxhoverballs 0
sbox_maxvehicles 0
sbox_maxbuttons 10
sbox_maxemitters 0

// Exec Bans
exec banned_user.cfg
exec banned_ip.cfg

**Comment by DarkyV1** [comment]
thank you so much for the help though

**Comment by Bo98** [comment]
And previously there was nothing in it? That makes no sense how it fixed the problem but I'm glad it's working anyhow

**Comment by DarkyV1** [comment]
it is very weird, i think maybe exec banned_user.cfg is something?

**Comment by Bo98** [comment]
I can't imagine that breaking so much from not just ULX but FPP too, but it doesn't matter now.

**Comment by DarkyV1** [comment]
yep all fixed, sorry for wasting your time and thanks :D
