### ISSUE TITLE
Demote menu doesn't properly cut off text in new line

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2946]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The question is not properly cut off.
I would use a different function for cutting/newlining off text in a new line like SetWrap(true) with adjusting the labels' size.
The problem with the current solution is, it cuts of the text after a certain amount of letters, but not every letter has the same size, thus making it cut off too early or too late.

https://i.imgur.com/oXI3xqD.png

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Make a demote with a question, which takes up a lot of space.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
their mod.

**Comment by FPtje** [comment]
I'm going to blame GMod on this one. This is the code that creates the label:

```
local label = vgui.Create("DLabel")
label:SetParent(panel)
label:SetPos(5, 25)
label:SetText(DarkRP.deLocalise(question))
label:SizeToContents()
label:SetVisible(true)
```

I'm telling it to size to contents. It works fine for most strings, but not the one given in the post above:
![hl2_2019-09-07_20-32-39](https://user-images.githubusercontent.com/1202014/64478908-e69c5d80-d1af-11e9-839b-4ce96e4e6754.png)
![hl2_2019-09-07_20-33-07](https://user-images.githubusercontent.com/1202014/64478910-e7cd8a80-d1af-11e9-930f-0b2fcc5a6777.png)
![hl2_2019-09-07_20-34-40](https://user-images.githubusercontent.com/1202014/64478911-e9974e00-d1af-11e9-9d5d-96c3a8ba18cd.png)

GMod just doesn't like the German language I suppose.

Code to reproduce if someone wants to take a look at it anyway:
```lua
lua_run DarkRP.createVote("Mika von Chernavsky:\nGrund:\ninhaftiert Leute mit schlechte redenierung", "1", Player(3), 20, show, {}, show)
```

**Comment by mcNuggets1** [comment]
That actually has nothing to so with the language.
Your system newlines after a specific amount of letters, but letters all have a different size, therefore it newlines too das or too late.
I can fix this in a pull request properly, if you like, but it's not a gmod issue.

**Comment by FPtje** [comment]
The only string modification on question is DarkRP.delocalise. I'm not adding the newlines, gmod is with :SizeToContents

**Comment by FPtje** [comment]
Oh wait for damnit I am

**Comment by FPtje** [comment]
![hl2_2019-09-08_12-15-09](https://user-images.githubusercontent.com/1202014/64486811-53583c00-d232-11e9-8fe3-e764c04a7a99.png)
`DarkRP.textWrap` proves useful once again.
