### ISSUE TITLE
DarkRP doesn't assign door groups in the newest update

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2948]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
It seems, door groups are not being set.
Nor in my local game, nor in my dedicated server.
In my dedicated server however they are with the first start of the map, but after a mapchange, they don't.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Save a door, restart map.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
I looked over the `onFinish` function when changing the migration system. Because onFinish wasn't really when the migration was finished. It was called only when a *part* of the migration was finished.
