### ISSUE TITLE
Spawnpoint bug

### ISSUE THREAD

**Issue by Benjamin47222** [FPtje/DarkRP#2951]
### Description of the bug
Hello, when i custom spawn jobs, i do :
/removespawn job ( it's works )
/setspawn job ( it's work and i spawn at the new spawnpoint)
I restarted the server and this spawnpoints are now deleted and i spawn at the default spawn map

And when i did :
] darkrp_check_db_sv
Your sv.db database file is good.

### How to make the bug happen
I don't how it's happen, i try on a server why the same version and the same config of darkrp modification master and i doesn't had the same bug.

### Lua errors
ANY LUA ERROR

**Comment by Bo98** [comment]
Not sure what you mean by "ANY LUA ERROR". Are there any Lua errors or are there none?

Chances are it's an addon causing the issues. If there's no errors, you can try removing addons to see what's causing it. If you find out, let us know.

**Comment by FPtje** [comment]
I hear this often, but it's never DarkRP itself. I'd like to know at some point what addon is causing this though.

**Comment by Benjamin47222** [comment]
I try without addon, and no collection, no data etc.. and the bug is always here, i fix that with a script fox spawn but the command still doesn't work, thanks you anyway
