### ISSUE TITLE
Bad local orgin

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [FPtje/DarkRP#2952]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
Bad SetLocalOrigin(-17240.257812,12599.048828,865.523193) on gmod_hands

### How to make the bug happen
Just randomly happens

### Lua errors
Bad SetLocalOrigin(-17240.257812,12599.048828,865.523193) on gmod_hands

### Why the developer of DarkRP is responsible for this issue
robotboy said you are

**Comment by Kefta** [comment]
This is a problem with gmod_hands that I've noticed on a number of servers, probably due to parenting. The error should have no side effects other than an occasionally flickering hand model while the error is printing. I don't think there's anything to be done to DarkRP about this.

**Comment by FPtje** [comment]
@robotboy655 A claim is made of you having said something here. Do you think I'm responsible? If so, how?

I'll re-open the issue if RB (or anyone else) makes a good case.

**Comment by robotboy655** [comment]
I have not (talked about this issue or to this person in recent months), it is definitely related to unparenting though.

Fairly certain there's an open issue on gmod-issues repo for this.

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1184

**Comment by CLEVELANDMAN99** [comment]
I was looking at an older thread about this issue. And robotboy had commented saying darkrp was at fault. So I took that into context.
