### ISSUE TITLE
Banned by myself

### ISSUE THREAD

**Issue by PhillTV** [FPtje/DarkRP#2953]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible) 
Banned by Myself Permantently in the DarkRP-Application

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
i tapped on the Button "Ban" i selected 1second and Then i got Kicked out Permanent.
how to Unban in the Console? 

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No LUA Errors

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because the i want to "Upgrade" the Server and Play with my Friends.

**Comment by FPtje** [comment]
`FAdmin unban "SteamID"`
I think, good luck lol
