### ISSUE TITLE
Abort hit issue

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [FPtje/DarkRP#2954]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
Place a hit on someone, if they die the hit doesn't abort.

### How to make the bug happen
[//]: # Place a hit on someone
[//]: # None that I know of

### Lua errors
[//]: # No errors on startup, only when the hit abort is supposed to happen
[//]: # [ERROR] lua/includes/util.lua:206: attempt to index a string value with bad key ('IsValid' is not part of the string library)
1. error - [C]:-1
2. __index - lua/includes/extensions/string.lua:297
3. IsValid - lua/includes/util.lua:206
4. fn - addons/mlogs2/lua/mlogs/logger/loggers/darkrp/hits.lua:31
5. Call - addons/ulib/lua/ulib/shared/hook.lua:109
6. abortHit - gamemodes/darkrp/gamemode/modules/hitmenu/sv_init.lua:86
7. fn - gamemodes/darkrp/gamemode/modules/hitmenu/sv_init.lua:213
8. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

### Why the developer of DarkRP is responsible for this issue
[//]: # I know that the first part of the error seems to come from string.lua But there is some lua errors involving DarkRP in there.
[//]: # I'm just really looking to get help on how to fix this/ what has caused the error.

**Comment by CLEVELANDMAN99** [comment]
Seems like my logs were causing this to happen. Don't know why, but pretty disappointing.

**Comment by FPtje** [comment]
Returning values in hooks, the most common reason why good code doesn't work.
