### ISSUE TITLE
FAdmin Issues

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [FPtje/DarkRP#2955]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # I disabled my DarkRP connection to mySQL database. My owner group has no CAMI permissions even though in ULX I have them set. If I set myself to superadmin via fadmin I then have those permissions but, it also puts me in the superadmin group on ULX.

### How to make the bug happen
[//]: # Disabling mySQL connection?
[//]: # Disabling mySQL connection?

### Lua errors
[//]: #None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
You made FAdmin

**Comment by Potatosayno** [comment]
If I understand correctly, for FAdmin CAMI permissions to work with ULX you must do the following:
- Type `+FAdmin_Menu ` in console
- At the top right, click on **"Server Settings"**
- Under **"Player Actions"** click on **"Edit Groups"**, and then you can adjust CAMI permissions for ULX through FAdmin.

**Comment by FPtje** [comment]
This doesn't look like a bug, but a problem with your specific install. Check for errors on startup and go to forum.darkrp.com.

**Comment by CLEVELANDMAN99** [comment]
Hmm, well I have tried a fresh install of the game mode. There are no errors on startup. The forums are dead
