### ISSUE TITLE
Batons don't have colors

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [FPtje/DarkRP#2961]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Arrest Batons and Stun stick missing colors

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
I don't know how to make the bug happen. Nor the cause. But, they seem to be normal sometimes but most of the time they're just white.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it) I've tried multiple things to make sure it wasn't on my side including reinstalling GMOD, unsubbing from the workshop addon and resubbing.

**Comment by Kefta** [comment]
Have you tested with -noaddons -noworkshop enabled?

**Comment by CLEVELANDMAN99** [comment]
> Have you tested with -noaddons -noworkshop enabled?

I have not. I'll test that out tomorrow.

**Comment by CLEVELANDMAN99** [comment]
That did nothing

**Comment by Kefta** [comment]
Could you provide exact reproduction steps?

**Comment by FPtje** [comment]
Given the high visibility and low reported incidence of this problem, I'm going to assume this is caused by a conflicting addon, or misconfiguration.

The forums (forum.darkrp.com) are the best way to get help here, as other people might have faced the problem before you.

When evidence is found that DarkRP itself is at fault for this problem, please post it as a reply to this issue.
