### ISSUE TITLE
Custom groups don't work even if inheriting from admin

### ISSUE THREAD

**Issue by FBFezz** [FPtje/DarkRP#2962]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

I use ulx on darkrp (with modification master and derrived rp) and i have custom groups as i have a ranking structure for the server. I have the fadmin disabled as i heard that can cause issues with this aswell but when (using manager as an example) inherits from admin or another rank that inherits from admin, the manager rank is not able to physgun world entities unless the players can physgun world entities setting is enabled.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Not sure if its a bug or not but its when you have a custom user group and i can provide some video  if needed or show you using discord or something

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None that i can see

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

As its fpp related and that's integrated into the gamemode

**Comment by FPtje** [comment]
Give the usergroup the `FPP_TouchOtherPlayersProps` CAMI privilege.
