### ISSUE TITLE
Some Chat Sounds do not get called

### ISSUE THREAD

**Issue by Potatosayno** [FPtje/DarkRP#2964]
### Description of the bug
[//]: # In the code of darkrp/gamemode/modules/chatsounds.lua 
**You've put chatsounds such as "no" and "oh no".** Now, "oh no" will never get called as you're using string.find, and it finds a "no" in "oh no" thus calling "no".
What I suggest is maybe try to find a way to make it possible to both have "oh no" and "no" as originally intended by you, as this is still in code.
(I would also suggest just using `string.Replace(text, "'", "")` to avoid having to have both it's and its)

### How to make the bug happen
[//]: # Simply type in game "Oh no" and you will hear sounds from "no" and not from "Oh no", also works when it's supposed to be "Please no".

### Lua errors
[//]: # none

### Why the developer of DarkRP is responsible for this issue
[//]: # The code is in DarkRP itself, and obviously is intended to be that way, either this gets fixed or there is no use in that set-up there. (as it will never work)

**Comment by mcNuggets1** [comment]
The best and most optimised solution would be to just call the sounds if the user actually types "no" or "oh no" and not a whole sentence.
Would also make key indexing a possibility.

**Comment by Potatosayno** [comment]
> The best and most optimised solution would be to just call the sounds if the user actually types "no" or "oh no" and not a whole sentence.
> Would also make key indexing a possibility.

I get what you mean but that would remove a lot, as "no , stop" wouldn't be called as it wouldn't just be "no" by then, it would be a whole sentence, this would remove a bunch from role-play in my opinion.
But if we'd stick with my idea we'd also have to call the first string that is found as "no please no" should call just a normal no and not both etc..
A way to know the differences between "Please no" and "no" is pretty much what we need for with my idea.
Maybe checking for all the words in a sentence that are possible to be called and then using the one with the bigger number of letters in it?

**Comment by FPtje** [comment]
What's wrong with longest string match? That can be done efficiently, or just `O(n)`, which isn't too bad.

**Comment by Kefta** [comment]
Depth first string search

**Comment by FPtje** [comment]
The decision was made to go for a simple longest match search. More
efficient algorithms are available, but are effort to implement, and
most likely require keeping track of separate data structures, making
the code harder to maintain.
