### ISSUE TITLE
Jail unarrest does not tp people out of jail

### ISSUE THREAD

**Issue by RareHyperIon** [FPtje/DarkRP#2967]
### Description of the bug
[//]: # (when i arrest people it teleports them into jail but when i unarrest people they just get unarrested but they dont get teleported outside the jail)

### How to make the bug happen
[//]: # (download the addon and hope that it will not work)

### Lua errors
[//]: # ([ERROR] lua/autorun/server/damage.lua:1: attempt to index global 'GAMEMODE' (a nil value)
  1. unknown - lua/autorun/server/damage.lua:1

Couldn't include file 'autorun\server\resource.lua' (File not found) (<nowhere>)
Couldn't include file 'autorun\server\workshop.lua' (File not found) (<nowhere>))

### Why the developer of DarkRP is responsible for this issue

[//]: # (i downloaded the darkrp addon and it had the unarrest baton and the arrest baton i did not edit the config for it at all)

**Comment by FPtje** [comment]
Issue not filled in completely
