### ISSUE TITLE
Jail unarrest does not tp people out of jail

### ISSUE THREAD

**Issue by RareHyperIon** [FPtje/DarkRP#2968]
### Description of the bug
[//]: # (When i arrest people they get sent to jail but when i unarrest people they get unarrested but they dont get teleported out of jail or respawned)

### How to make the bug happen
[//]: # (download all the DarkRP addons and hope it will somehow break itself like it did to me)
[//]: # (idk if its a setting. im using DarkRP-modification. idk much about it im new to DarkRP)

### Lua errors
[//]: # ([ERROR] lua/autorun/server/damage.lua:1: attempt to index global 'GAMEMODE' (a nil value)
  1. unknown - lua/autorun/server/damage.lua:1)
[//]: # (i checked the startup log and thats the only error) ok i need help im typing this here because the other questions ARE NOT SHOWING THE TEXT SO I CANT EVEN USE THIS. this is the worlds stupidest thing ever i can only type here please help then close it

### Why the developer of DarkRP is responsible for this issue
[//]: # (I downloaded there addon and darkrp-modification and thats it and i only edit the jobs in stuff i have not touched any of the DarkRP files)
[//]: # (if theres an issue it would have said lua error or something but theres not a single CRITICAL ERROR for that so idk)

**Comment by RareHyperIon** [comment]
why do i bother?

**Comment by RareHyperIon** [comment]
i might as well close this

**Comment by RareHyperIon** [comment]
its not showing the rest of the help text

**Comment by Kefta** [comment]
The error is from a script not related to the gamemode. Check your addons.

**Comment by RareHyperIon** [comment]
ok thanks

**Comment by RareHyperIon** [comment]
do you think you can tell me what script its from so i can fix it?

**Comment by RareHyperIon** [comment]
oh btw i merged all the DarkRP addons

**Comment by RareHyperIon** [comment]
so just tell the .lua scripts name and ill fix it

**Comment by Kefta** [comment]
Read the error you posted, it already tells you.
