### ISSUE TITLE
suggestion cancel hit

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2971]
Hello, I come to bring this suggestion.
Basically it would be that a murderer (hitman) can cancel his current hit (with a command) Example: / cancelhit

in this way, the client receives the money and the hit disappears

As a rule of thumb, when you cancel a hit, the money is returned to the customer automatically.
I think it is very necessary for those of us who use the original hitmans system

**Comment by FPtje** [comment]
See https://github.com/FPtje/DarkRP/commit/4fd2c3c315427e79bb7624702cfaefe9ad26ac7e
