### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2972]
I really don't know how to reproduce it.
I use the most updated version of github.

[ERROR] gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:177: attempt to index local `cvar` (a nil value)
  1. AddControl - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:177
   2. func - lua/autorun/utilities_menu.lua:62
    3. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
     4. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
      5. ActivateTool - lua/includes/modules/spawnmenu.lua:287
       6. DoClick - gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:118
        7. unknown - lua/vgui/dlabel.lua:234

**Comment by FPtje** [comment]
DarkRP is no part of the error, so it's not the cause.

**Comment by Kefta** [comment]
This is fixed in the dev branch: https://github.com/Facepunch/garrysmod/commit/a1a5a6422d7d22002504ddb02cf983e351b32d29
