### ISSUE TITLE
/setspawn Stop Working after Restart

### ISSUE THREAD

**Issue by anyome** [FPtje/DarkRP#2974]
Hello !

When i try to add a new Spawn for jobs it does Works ! (/setspawn citizen , /addspawn citizen)

But when i restart the Server, Spawnpoints get reset, and i need to do it at Every restart !

It's like not saving in the database!

Can you fix this issue please? maybe make spawn pos in a : data.txt file instead of sv.db

**Comment by anyome** [comment]
PLEASE FIX IT ! man my darkrp server is 100 players and now i'm loosing players bcz of this bug !!! man please

**Comment by FPtje** [comment]
I don't think it's me who broke it. Check forum.darkrp.com.
