### ISSUE TITLE
!noclip Problem

### ISSUE THREAD

**Issue by anyome** [FPtje/DarkRP#2975]
Hey!

I deleted the "noclip" folder from FAdmin and still when i do: !noclip i get Cloaked from FAdmin

How can i disable the command : !noclip from darkrp? because it Breaks with ULX

So i need to use : "ulx noclip" everytime to bypass the !noclip issue

**Comment by FPtje** [comment]
https://corefiles.darkrp.eu/
Also not a help forum.
