### ISSUE TITLE
gun license is removed by getting jailed even with hasLicense job var set

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2976]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
If a job has the hasLicense var set, they should always have a license, but after getting arrested, the license is revoked.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Arrest a player with a license by default

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
their mod

**Comment by anyome** [comment]
The developer of darkrp don't give support anymore.

The main issue with darkrp is that the FPS are super low and that's need to be fixed right before anything

**Comment by Kefta** [comment]
This is an issue report for something wrong with the gamemode, not a support request. Go whine somewhere else.

**Comment by FPtje** [comment]
@anyome That's *your* main issue, not that of DarkRP itself. I've told you in your own issue that you've insufficiently argued that DarkRP is the actual cause of the problem. I'm running GMod to provide support for this and two other issues created the past 24 hours. This entire day I have found no FPS issues whatsoever.
