### ISSUE TITLE
LOW FPS WHEN THERE IS PLAYERS

### ISSUE THREAD

**Issue by anyome** [FPtje/DarkRP#2977]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
My servers get a huge LOW FPS (10 FPS) when there is players on the server

### How to make the bug happen
Having player playing on your server with this map: 
https://steamcommunity.com/sharedfiles/filedetails/?id=328735094

### Lua errors
None

### Why the developer of DarkRP is responsible for this issue
Their Mod man

**Comment by FPtje** [comment]
That map isn't my mod. You're not making well enough a case that DarkRP is causing it, and not some other mod.
