### ISSUE TITLE
[Bug] sv_util.lua tried to concat a nil value from cssmount.lua

### ISSUE THREAD

**Issue by Junnnneee** [FPtje/DarkRP#2979]
**Description of the bug**
a lua error caused by a commit

**How to make the bug happen**
Launch darkrp and join.

**Lua errors**
```lua
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_util.lua:79: attempt to concatenate local 'text2' (a nil value)
  1. talkToPerson - gamemodes/darkrp/gamemode/modules/base/sv_util.lua:79
   2. unknown - gamemodes/darkrp/gamemode/modules/cssmount.lua:16
```

**Why the developer of DarkRP is responsible for this issue**

This commit: https://github.com/FPtje/DarkRP/commit/4eecc5aa49d2d7602888134d12a9e49672176cfd

Commit did not account for this usage:
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/cssmount.lua#L16

Line Fault:
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/base/sv_util.lua#L79

**Fix**
add `text2 = text2 or ""` below DarkRP.talkToPerson
```lua
function DarkRP.talkToPerson(receiver, col1, text1, col2, text2, sender)
	text2 = text2 or ""
	if IsValid(receiver) and not receiver:IsBot() and (sender == receiver or hook.Run("PlayerCanSeePlayersChat", text1 .. ": " .. text2, false, receiver, sender) ~= false) then
        net.Start("DarkRP_Chat")
            net.WriteUInt(col1.r, 8)
            net.WriteUInt(col1.g, 8)
            net.WriteUInt(col1.b, 8)
            net.WriteString(text1)

            sender = sender or Entity(0)
            net.WriteEntity(sender)

            col2 = col2 or Color(0, 0, 0)
            net.WriteUInt(col2.r, 8)
            net.WriteUInt(col2.g, 8)
            net.WriteUInt(col2.b, 8)
            net.WriteString(text2)
        net.Send(receiver)
    end
end
```

**Comment by FPtje** [comment]
Man do I love bug reports from programmers. You've gone out of your way to explain what's wrong.

**Comment by FPtje** [comment]
Fixed. Thanks for the report!

CC @WilliamVenner
