### ISSUE TITLE
How Do I Fix This Error?

### ISSUE THREAD

**Issue by wtf-mrpotato** [FPtje/DarkRP#2980]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
It's Like I'm Not A Job When I Login

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
1. error - [C]:-1
2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:530
3. getJobTable - gamemodes/darkrp/gamemode/modules/b
[DarkRP] gamemodes/darkrp/gamemode/libraries/simplerr.lua:530: [ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua" on line 392.
The best help I can give you is this:
There is a player with an invalid team!
The player's name is MrPotato, their team number is "1001", which has the name "Unassigned"
Hints:
- It is the server owner's responsibility to figure out why that player has no valid team.
- This error is very likely to be caused by an earlier error. If you don't see any errors in your own console, look at the server console.
The responsibility for the error above lies with (the authors of) one (or more) of these files:
1. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 392
2. gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua on line 756

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
1. error - [C]:-1
2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:530
3. getJobTable - gamemodes/darkrp/gamemode/modules/b
[DarkRP] gamemodes/darkrp/gamemode/libraries/simplerr.lua:530: [ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua" on line 392.
The best help I can give you is this:
There is a player with an invalid team!
The player's name is MrPotato, their team number is "1001", which has the name "Unassigned"
Hints:
- It is the server owner's responsibility to figure out why that player has no valid team.
- This error is very likely to be caused by an earlier error. If you don't see any errors in your own console, look at the server console.
The responsibility for the error above lies with (the authors of) one (or more) of these files:
1. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 392
2. gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua on line 756

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
They know the errors for their mod (i think)

**Comment by FPtje** [comment]
Not a help forum
