### ISSUE TITLE
Race condition in antimultirun

### ISSUE THREAD

**Issue by roboderpy** [FPtje/DarkRP#2982]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
When using antimultirun, it rely on `DarkRPDBInitialized` hook, which can be called before or after public IP resolve, thus procuding different `DarkRP.serverId`
Worst case scenario - server full of players with one `DarkRP.serverId` crashes, restarts, and get different `DarkRP.serverId` players who was online would not be able to join.
Database admin would be forced to manually do `TRUNCATE darkrp_serverplayer` on DarkRP database

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
* Bogus conditions

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
* None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Antimultirun is a DarkRP default module

Solution is either:
 * Using something more reliable than `game.GetIPAddress()`
 * Wait until `game.GetIPAddress()` return something different than `0.0.0.0:27015` etc

**Comment by mcNuggets1** [comment]
I fixed this by using a convar on my server.
But I guess this is something else.
