### ISSUE TITLE
Ability to spawn ents & props while dead

### ISSUE THREAD

**Issue by djtb2924** [FPtje/DarkRP#2985]
### Description of the bug
When you're dead, you can walk backwards, spawn props & entities from `DarkRP.createEntity`

### How to make the bug happen
Kill yourself, open spawnmenu or F4 menu

### Lua errors
No

### Why the developer of DarkRP is responsible for this issue
DarkRP.createEntity is a function of DarkRP

**Comment by FPtje** [comment]
I'm sort of worried that there might be some valid use case for entities that you can spawn while being dead. Something like a ghost pass or tombstone or something. Should it be an option?

**Comment by djtb2924** [comment]
Yes I think an option actived by default
