### ISSUE TITLE
Can't use any DarkRP command

### ISSUE THREAD

**Issue by Viv1r** [FPtje/DarkRP#2986]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
Some commands don't work

### How to make the bug happen
Type in chat "/addmoney (name) (amount)"
or "/setspawn (team cmd)"
or "/setjailpos" or anything else

### Lua errors
[ERROR] ::100: attempt to index global 'ply' (a nil value)
  1. v - ::100
   2. unknown - addons/darkrp/gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:139

### Why the developer of DarkRP is responsible for this issue
Because even my server where is nothing except DarkRP gamemode has this problem

**Comment by Viv1r** [comment]
*I haven't edited any DarkRP files

**Comment by FPtje** [comment]
Are you using the workshop version or the GitHub version?

**Comment by Viv1r** [comment]
Both of them have this bug

**Comment by FPtje** [comment]
I cannot reproduce the issue. Looks like something is off on your end. Here's the result of a command you described as broken:
![hl2_2020-01-25_20-26-23](https://user-images.githubusercontent.com/1202014/73126314-4f467400-3fb1-11ea-8476-3e99ff62d082.png)

All the commands you gave work for me.
