### ISSUE TITLE
Lockpicks not working on doors!

### ISSUE THREAD

**Issue by Matt12312333** [FPtje/DarkRP#2987]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
i tried to lockpick a door on my server and it seems that the darkrp lockpicks dont work if you guys know how to fix this please let me know ASAP.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
No CLUE HONESTLY IT JUST HAPPENED ALL OVER A SUDDEN

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
NO LUA ERRORS

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by TomDotBat** [comment]
> Why the developer of DarkRP is responsible for this issue:
> *emptiness*

https://forum.darkrp.com/forums/darkrp-modding-questions-help.5/

**Comment by FPtje** [comment]
Works for me.
