### ISSUE TITLE
Help. After add new jobs, I get error

### ISSUE THREAD

**Issue by ZipFox189** [FPtje/DarkRP#2990]
I just want to add admin jobs, but when i add it, i get problem

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_data.lua:303: attempt to index a nil value
  1. retrieveSalary - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:303
   2. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:328
    3. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:302
     4. retrievePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:254
      5. restorePlayerData - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:319
       6. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:585

**Comment by FPtje** [comment]
Not a help forum. Go to forum.darkrp.com.

The new issue template tells you that, you removed that comment to post this issue.
