### ISSUE TITLE
FAdmin remembers usergroups added to CAMI by other mods.

### ISSUE THREAD

**Issue by bbblitz** [FPtje/DarkRP#2991]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
FAdmin registers usergroups that were registered by other CAMI mods, but claims FAdmin as "src".

I'm working on a CAMI-compliant admin mod, and I recently found that if I delete the user groups off-line (i.e. I don't call UnregisterUsergroup()), FAdmin will helpfully remember and re-add them for me, except it will pass "FAdmin" as the "src" parameter instead of whatever "src" I originally added the group with. This is a problem because I depend on "src" to decide whether my admin mod should allow users to change permissions or delete a particular usergroup. The result is "orphaned" usergroups that my mod does not think belong to it, but FAdmin remembered and re-added. I intend to prevent users of my mod from deleting usergroups that were not added through my mod.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Add usergroups with CAMI.RegisterUsergroup() in a mod after FAdmin has been started (maybe before too, haven't tested), shut down the server, remove usergroups from being added by the mod next start up, then start the server again. Hooking CAMI.OnUsergroupRegistered before FAdmin starts will show that the usergroups are still added, and "FAdmin" is passed as the "src" parameter.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

FAdmin should only save/load usergroups that have been made through FAdmin. By saving and loading usergroups from other admin mods, you require other admin mods to call UnregisterUsergroup(), which requires other admin mods to keep track of changes that have been made offline and apply them the next time the server is started.

Which, if that's what expected of CAMI mods that's fine, but maybe this issue should be on the CAMI tracker to clarify what's expected of compliant mods. The way the it's worded now, I expect each admin mod to remember it's own custom usergroups, and add them during startup.

Searching through issues I see this may run contrary to #963 , but I'm not concerned if FAdmin wants to **save** the usergroups, I'm only concerned that FAdmin re-**adds** them.

**Comment by nahboi** [comment]
### _*"Also they are devs not bugbots..**_

**Comment by bbblitz** [comment]
I don't mind digging in and fixing this myself, but can I get a yay/nay on if this is a bug in FAdmin?

**Comment by FPtje** [comment]
You could take a look, but if FAdmin has to remember where usergroups came from, a database migration might be needed.

**Comment by bbblitz** [comment]
I think I could do it without a migration if that's important, I could make a new table (FADMIN_GROUPS_SRC ?) with a foreign key to FADMIN_GROUPS, which saves the 'src', if it can. I'll send a pull in a minute.
