### ISSUE TITLE
DarkRP.formatMoney doesn't fix decimal width

### ISSUE THREAD

**Issue by WilliamVenner** [FPtje/DarkRP#2994]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
```lua
print(DarkRP.formatMoney(1.5))
>"$1.5"
```

![image](https://user-images.githubusercontent.com/14863743/75477464-4b34ba00-5994-11ea-8632-b8fd1b13e390.png)

Should be

```lua
print(DarkRP.formatMoney(1.5))
>"$1.50"
```

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
```lua
print(DarkRP.formatMoney(1.5))
```

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I would probably end up breaking DarkRP.formatMoney if I fixed this with a PR because the code for it is weird 🥴

**Comment by FPtje** [comment]
The thing is, though, DarkRP doesn't really support decimals in money. How did this become an issue?

**Comment by FPtje** [comment]
I've fixed the formatting, but I strongly recommend against using decimals in money. You're gonna have to deal with floating point imprecision in many places of the DarkRP code base. DarkRP conveniently avoids all of that by simply not allowing decimals.
