### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2995]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
RPname => /rpname in
base/sv_entityvars line 172, line 179, line 208

**Comment by FPtje** [comment]
Sub phrase translating was a mistake
