### ISSUE TITLE
battering ram

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#2996]
As can be shown in the video, it can be used from a long distance
https://i.gyazo.com/dd96ea3d9a84437bbcf4e5bfd37d24cf.mp4

I use the updated gitbub version

**Comment by mcNuggets1** [comment]
true, distances is 10k for everything except doors for some reason.

**Comment by MStruntze** [comment]
> true, distances is 10k for everything except doors for some reason.

It's DistToSqr so it's not that far.

**Comment by MStruntze** [comment]
It's a vcmod bug, not DarkRP.
You can test it by running
`lua_run hook.Remove('onDoorRamUsed', 'VC_onDoorRamUsed')`
on your server - though it will **break** ramming passengers.

I have messaged freeman on Steam to let him know.

**Comment by MStruntze** [comment]
Running this on your server should fix the issue until VCmod pushes an update:
```
hook.Add('onDoorRamUsed', 'VC_onDoorRamUsed', function(success, ply, tr)
    if success and IsValid(tr.Entity) and tr.Entity:IsVehicle() then
        for k, v in ipairs(tr.Entity.VC_SeatTable) do
            if IsValid(v) and IsValid(v:GetDriver()) then
                v:GetDriver():ExitVehicle()
            end
        end
    end
end)
```

**Comment by MStruntze** [comment]
The issue has been resolved in vcmod
https://vcmod.org/changelog/main/
