### ISSUE TITLE
Swear filter for /rpname is a localised table

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2998]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
There is some sort of swear filter for the /rpname command.
It's in form of a localised table and if a forbidden name is tried to be taken, it returns false, saying "Forbidden name".
I want ot ask, if it can be made something else.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
not a bug

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
base module

**Comment by FPtje** [comment]
I wouldn't describe it as a "swear" filter, as it filters for the following words, none of which are swear words:
- ooc
- shared
- world
- world prop

I don't think it should be made "something else", as the code is already in a hook (`CanChangeRPName`) that can be overridden.

Of course this depends on what you mean by "something else". What exactly are you proposing here?

**Comment by mcNuggets1** [comment]
Just make it global or a hook.
It's there so it should be able to be modified in some way, even if it is just deactivating it.

**Comment by FPtje** [comment]
This filter is very minimal, and protects against abuse with e.g. prop protections, naming yourself "world" makes it appear like your props are owned by the world.

I don't think this should be made too easy to modify. This is not the kind of thing where it seems plausible that people would actually want to disable it. Why would people want to disable or modify this?

**Comment by mcNuggets1** [comment]
To include more words, it can be useful, if made accessable.
Also naming yourself shared isn't really something bad.
And why should naming yourself world break anything regarding your prop protection?

**Comment by FPtje** [comment]
```lua
local moreBadWords = {["bad"] = true, ["words"] = true, ["blocked"] = true, ["restrained"] = true}
hook.Add("CanChangeRPName", "MyOwnBadWords", function(ply, RPname)
  if disallowedNames[string.lower(RPname)] then return false, DarkRP.getPhrase("forbidden_name") end
end)
```
