### ISSUE TITLE
Looking at a player while another player is in the front disables drawing of 3d head info

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#2999]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/hud/cl_hud.lua#L347
This line breaks the loop, while it would be more beneficial to only continue.
When standing in front of 2 players right behind each other and looking at them, it removes all 3d world displays above their head.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Your suggestion would always run a trace multiple times. In rendering that's expensive. Instead, this simple check to see if the trace entity is a player. In a test it draws the player info for the player directly in front. 

That might actually be better than drawing both, since the texts would otherwise overlap.
