### ISSUE TITLE
Scripterrors in the F1 menu

### ISSUE THREAD

**Issue by Mekrip** [FPtje/DarkRP#3002]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Scripterrors in the F1 Menu

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Typing "%", "(" or ")" in the searchbar

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[DarkRP] gamemodes/darkrp/gamemode/libraries/fn.lua:221: unfinished capture
  1. f - [C]:-1
   2. b - gamemodes/darkrp/gamemode/libraries/fn.lua:221
    3. searchAlg - gamemodes/darkrp/gamemode/libraries/fn.lua:84
     4. OnChange - gamemodes/darkrp/gamemode/modules/f1menu/cl_f1menupanel.lua:78
      5. OnTextChanged - lua/vgui/dtextentry.lua:206
       6. unknown - gamemodes/darkrp/gamemode/modules/f1menu/cl_searchbox.lua:45

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
To make sure that it wasnt up to me, i tested it on a fresh server without any addons

**Comment by FPtje** [comment]
That's a pretty old bug you found there. It's fixed now. Thanks!
