### ISSUE TITLE
Door system error-sh_doors.lua

### ISSUE THREAD

**Issue by pizzadox11** [FPtje/DarkRP#3004]
### Description of the bug
[//]: # Sometimes when player disconnects i get a error
It seems to start at GM:PlayerDisconnected https://github.com/FPtje/DarkRP/blob/6be930b01b75c2f0220b99eaf6dd5ab6bf4d7df8/gamemode/modules/base/sv_gamemode_functions.lua#L911
and goes on to local class = **self:GetClass**() https://github.com/FPtje/DarkRP/blob/6be930b01b75c2f0220b99eaf6dd5ab6bf4d7df8/gamemode/modules/doorsystem/sh_doors.lua#L17
It happened after the latest door system update :(

### How to make the bug happen
[//]: # I dont sure if it happens without it or with but usually like 80% of it happens when i leave the server and not when a random player leaves. Try to restrict some doors for job only and then disconnect

### Lua errors
```
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sh_doors.lua:17: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. isKeysOwnable - gamemodes/darkrp/gamemode/modules/doorsystem/sh_doors.lua:17
    3. keysUnOwnAll - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doors.lua:110
     4. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:911
 
Dropped Redogg from server (Disconnect by user.)
```

### Why the developer of DarkRP is responsible for this issue
[//]: # I dont have any conflicting addons or any door addons. GM:PlayerDisconnected isnt over written and isKeysOwnable or keysUnOwnAll isnt used at all except for
```
	if IsValid(tr.Entity) and tr.Entity:isKeysOwnable() and tr.Entity:GetPos():Distance(LocalPlayer():GetPos()) < 200 then
		tr.Entity:drawOwnableInfo()
	end
```
 It started to do it after i updated darkrp to newest version

**Comment by FPtje** [comment]
You're absolutely right. This regression was recently introduced. The latest version now includes a fix. Thanks for reporting!
