### ISSUE TITLE
The old usermessage library is bad for optimization.

### ISSUE THREAD

**Issue by AlternativeGM** [FPtje/DarkRP#3005]
Sorry no form (phone).
Create a separate DarkRP release with the replacement of the usermessages library with the net library or make a choice between methods in the config. Usermessages break down optimization on weak computers.

P.S. Kind of like you are forbidden to edit the source files in DarkRP. Sorry for using a translator.

**Comment by Kefta** [comment]
This has already been discussed ad nauseum in https://github.com/FPtje/DarkRP/pull/1988 and many other issues. Garry's Mod will eventually change the implementation of umsg to net internally, but you can just use a umsg->net Lua script.

**Comment by Bo98** [comment]
> Usermessages break down optimization on weak computers.

If there is a particular case which is having such a serious impact on people, let us know.

umsg isn't even used in the most heavily invoked parts of DarkRP networking - like DarkRPVars or weapons.

**Comment by AlternativeGM** [comment]
> > Usermessages break down optimization on weak computers.
> 
> If there is a particular case which is having such a serious impact on people, let us know.
> 
> umsg isn't even used in the most heavily invoked parts of DarkRP networking - like DarkRPVars or weapons.

Notification... 
Yep...
*censored* notifications!

**Comment by Bo98** [comment]
Notifications are the hardest to change without breaking backwards compatibility. Because the implementation is in the HUD module, many custom HUDs copy-pasted it because people just disable the HUD module entirely rather than using `HUDShouldDraw`. (Actual customisation of how it looks is typically done via overriding the GMod's own documented functions & hooks.)

**Comment by matiasg90** [comment]
I am using the github version and my server never stops laging.
https://i.gyazo.com/0ef04afae758964adabf1a0de3aa9520.png

when installing the workshop version January 22, magically the error went away, I suppose we are talking about the same

**Comment by FPtje** [comment]
At one point I did change notifications to net. I swiftly reverted it when I got tons of complaints of addons breaking.

It's not going to happen, unless gmod changes the implemention to net, maybe.

**Comment by AlternativeGM** [comment]
> At one point I did change notifications to net. I swiftly reverted it when I got tons of complaints of addons breaking.
> 
> It's not going to happen, unless gmod changes the implemention to net, maybe.

I can edit core files? I need a net libraly.

**Comment by FPtje** [comment]
Why do think you need that?
You can disable modules and recreate them in the darkrp mod.

**Comment by AlternativeGM** [comment]
Synchronization of addon and game mode.
It will also help clear darkrp of extra code that I don’t use.

**Comment by FPtje** [comment]
You can override DarkRP's notification functions in an addon as well. In any way you don't have to edit core files.

**Comment by Bo98** [comment]
> when installing the workshop version January 22, magically the error went away

DarkRP was still using usermessages on January 22. The problem will be that something on your server is invoking usermessages a lot rather than the fact that usermessages are being used.
