### ISSUE TITLE
missing food sounds

### ISSUE THREAD

**Issue by fortnitewarrior** [FPtje/DarkRP#3006]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )
P.S if i shouldn't have posted it here I'm really sorry that wasn't my intention I know you don't like posting things wrongly but I think it fits here

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I enabled hunger mode and the sounds for food are missing

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Press E on a food item, to fix add the sounds content for it but idk where is it

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
vo\sandwicheat09.mp3 has 0 samples, refusing to load
Failed to load sound "vo\sandwicheat09.mp3", file probably missing from disk/repository

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I mounted DarkRP counted obviously so...

**Comment by FPtje** [comment]
That's a tf2 sound. Mount tf2
