### ISSUE TITLE
Update FPP

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#3009]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
The last FPP update fixed seeing entities through wall.
People begin abusing it, as of now.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Wait do you want me to merge FPP or are you saying that people are abusing the fact that you now can't see ownership through walls?

**Comment by mcNuggets1** [comment]
I mean, update it, people can still see through walls and abuse it.

**Comment by Brouskat** [comment]
Oh I didn't saw that before, damn.
https://i.gyazo.com/40c2e6da5b939c6f845ddf6a1455c5d9.mp4

**Comment by FPtje** [comment]
Done
