### ISSUE TITLE
Random errors 

### ISSUE THREAD

**Issue by matiasg90** [FPtje/DarkRP#3013]
### Lua errors
[ERROR] gamemodes/darkrp/entities/entities/spawned_weapon/init.lua:47: Tried to use a NULL entity!
  1. SetPos - [C]:-1
   2. unknown - gamemodes/darkrp/entities/entities/spawned_weapon/init.lua:47

### How to make the bug happen
I really don't know how to reproduce it

### DarkRP Version
Github

**Comment by Kefta** [comment]
You have a weapon with an invalid entity class. There should probably be a better error output about this.
