### ISSUE TITLE
Remove Refresh Things

### ISSUE THREAD

**Issue by AupItsChad** [FPtje/DarkRP#3016]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
So when a lua refresh occurs there is a spam of messages in console. Anyway i can get rid of these?

### Console Prints
Reloaded Control: DarkRP_TipJar_DONATE_ENTRY
Reloaded Control: DarkRP_TipJar_DONATE_BUTTON
Reloaded Control: DarkRP_TipJar_DONATE_LIST_ITEM
Reloaded Control: DarkRP_TipJar_DONATE_LIST
Reloaded Control: DarkRP_TipJar_FRAME
Reloaded Control: FAdminPanelList
Reloaded Control: FAdminPlayerCatagoryHeader
Reloaded Control: FAdminPlayerCatagory
Reloaded Control: FAdminActionButton
Reloaded Control: FAdmin_weaponPanel
Reloaded Control: F4MenuItemButton
Reloaded Control: F4MenuJobButton
Reloaded Control: F4MenuEntityButton
Reloaded Control: F4MenuPistolButton
Reloaded Control: F4MenuJobBecomeButton
Reloaded Control: F4MenuChooseJobModelIcon
Reloaded Control: F4MenuChooseJobModel
Reloaded Control: F4EmptyPanel
Reloaded Control: F4JobsPanelRight
Reloaded Control: F4MenuJobs
Reloaded Control: F4MenuTab
Reloaded Control: F4EditablePropertySheet
Reloaded Control: F4MenuFrame
Reloaded Control: F4MenuEntitiesBase
Reloaded Control: F4MenuEntities
Reloaded Control: F4MenuShipments
Reloaded Control: F4MenuGuns
Reloaded Control: F4MenuAmmo
Reloaded Control: F4MenuVehicles
Reloaded Control: F4MenuCategoryHeader
Reloaded Control: F4MenuCategoryContents
Reloaded Control: F4MenuCategory

**Comment by TomDotBat** [comment]
That occurs when you redefine a derma control with derma.DefineControl(), not part of DarkRP.
Don't use lua refresh on a live production server, simple.

**Comment by AupItsChad** [comment]
Fair enough i made this suggestion/issue for someone in the SWRP Dev discord so ill let him know.
**Cheers**
