### ISSUE TITLE
sv_chat.lua local chat lua error

### ISSUE THREAD

**Issue by physios** [FPtje/DarkRP#3018]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
Type something on local chat
P.S.: The server runs ulx, when you type locally if there is the normal chat it will still send the message through, and server side creates an error, if using atlaschat the error will be different but the top of the error trace will be the same and the same error cause, it will not print to chat in that case.

### How to make the bug happen
Use latest darkrp version of github

### Lua errors
```
[ERROR] gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:130: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. callHooks - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:130
3. callPlayerSayHooks - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:166
4. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:241
```

### Why the developer of DarkRP is responsible for this issue
Commit https://github.com/FPtje/DarkRP/commit/dd70b0ef5b57d392f54be4925abf3725eade690f
breaks that, reverting to old sv_chat.lua fixes the issue

**Comment by Kefta** [comment]
Do you mean https://github.com/FPtje/DarkRP/commit/dd70b0ef5b57d392f54be4925abf3725eade690f?

**Comment by physios** [comment]
> Do you mean [dd70b0e](https://github.com/FPtje/DarkRP/commit/dd70b0ef5b57d392f54be4925abf3725eade690f)?

Yeah, I linked the wrong commit

**Comment by mcNuggets1** [comment]
I don't have problems with the new chat system.
I just had to fix stupid addons overriding behaviour etc.
But that's their fault.

In fact it's much better than the old one.

Yet there should be a check for if ULibGetTable even exists, before calling all the ulib functions.

**Comment by physios** [comment]
> I don't have problems with the new chat system.
> I just had to fix stupid addons overriding behaviour etc.
> But that's their fault.
> 
> In fact it's much better than the old one.
> 
> Yet there should be a check for if ULibGetTable even exists, before calling all the ulib functions.

I thought about that, I didn't disable every addon but I disabled all chat related add-ons and it didn't work for me, I am going to test darkrp alone and see if the issue is reproduceable.

**Comment by Kefta** [comment]
I've written up a PR to fix hook priority support, just need to test it.

**Comment by Kefta** [comment]
jk, dbot's PR minimally fixed it. Not worth reworking code that functions I guess.

**Comment by physios** [comment]
I searched my addons for implementations of PlayerSay hook, one of which would remove it and "update it" like so:
```

if SERVER then
	local function updateHook()
		if not serverguard then return end
		hook.Remove("PlayerSay", "reports.PlayerSay")
		hook.Add("PlayerSay", "reports.PlayerSay",function(ply,txt,team)
			if txt[1] ~= "@" then return end
			
			txt = txt:sub(2)
			
			if #txt < 1 then return end
			
			serverguard.Notify(ply, SGPF("report_received", ply:Name(), txt))		
			
			if hasAccess(ply) then
				if cfg.debug then
					sendPopup(ply,txt)
					return not cfg.preventchat
				end
			else
				sendPopup(ply,txt)
				return not cfg.preventchat
			end
		end)
	end
	updateHook()
	hook.Add("InitPostEntity","adminpopups.serverguard",function()
		timer.Simple(5,updateHook)
	end)
end
```
Not sure if hook.Remove("PlayerSay", "reports.PlayerSay") is useful but could the darkrp hook handler be missing a hook ~= nil check?

**Comment by FPtje** [comment]
Closing as it is fixed.
