### ISSUE TITLE
Compatability with SAM Admin

### ISSUE THREAD

**Issue by MrCottonWooL** [FPtje/DarkRP#3020]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE FORUMS INSTEAD: https://forum.darkrp.com/ )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Hello, so I am using SAM admin which is an addon found on gmodstore: **https://www.gmodstore.com/market/view/sam** which is working perfectly fine. Today I uninstalled the old version of my darkrp gamemode, and updated to the latest one, and for some reason, things starts to break. 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
These are the issues I found so far:
1. Chat box stops working. No matter what you type in game, it doesn't let you or show up in game. However it does show up in console what you are typing. No errors what so ever
2. Arresting seems to be messed up. When you are arrested, and unarrested, normally it would teleport you back to spawn. However after for some reason it doesn't. And yes, the settings of darkrp where it teleports you is already set for teleportation

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No Lua errors as far as I see in console.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The issue happened after updating the darkrp gamemode.. I am not sure why it is causing this.

**Comment by Kefta** [comment]
You should make a ticket with the SAM developer. Unless you can pinpoint what change DarkRP made to break it, this is not DarkRP's responsibility.

**Comment by MrCottonWooL** [comment]
Sad face.. SAM developer refuses to help at this point but thank you for the fast response.
