### ISSUE TITLE
createMoneyBag doesn’t work

### ISSUE THREAD

**Issue by feelingnothing** [FPtje/DarkRP#3021]
### Description of the bug
[//]: # DarkRP.createMoneyBag doesn’t work

### How to make the bug happen
[//]: # Send position of the entity(self:GetPos()) as position of the money bag

### Lua errors
[//]: # [DarkRP] gamemodes/darkrp/gamemode/modules/money/sv_money.lua:42: bad argument #1 to ‘SetPos’ (Vector expected, got table)

**Comment by Kefta** [comment]
That's because you're passing a table as the first arg to ``DarkRP.createMoneyBag``, not a Vector. If you're truly passing ``self:GetPos()`` directly into the function, then check your addons for anything that might be overriding ``GetPos``.
