### ISSUE TITLE
/demote fix table

### ISSUE THREAD

**Issue by FalseGM** [FPtje/DarkRP#3023]
### Description of the bug
/demote - [DarkRP] Could not find table: 0x26f97150 (clearly version) (Use /demote without any additions)

### Lua errors
Nope, only notify.

**Comment by FPtje** [comment]
I don't understand a word of what you're saying

**Comment by FalseGM** [comment]
Sorry, I don't know English. Just write the command /demote in the chat, without any additional words. I understand that this is a lack of a table or translation.

**Comment by FalseGM** [comment]
Look at the notification on the bottom left of the screen.

**Comment by FoksVHox** [comment]
The issue is caused by you, cause you'd never just type `/demote` with no arguments. This means that there is no table called "".

**Comment by FPtje** [comment]
@FoksVHox The error is not with the user, as the message given is unhelpful.

@FalseGM Thanks for reporting the bug. I've changed the message to a slightly better one.

**Comment by FoksVHox** [comment]
@FPtje hmm I'd say it is

**Comment by FPtje** [comment]
And why would it be right for DarkRP to `tostring` a table and show that in a notification to the user?

How is that behavior the user's fault?

I mean ideally the user should get some message telling them that the `/demote` command requires a player and a reason argument. With the translation business, that's annoying to do. But one should never blame bad error messages on the user.

**Comment by FoksVHox** [comment]
I agree with most of the things. I just think that you would never use `/demote` without a player as argument.
