### ISSUE TITLE
attempt to call method 'getDarkRPVar' (a nil value)

### ISSUE THREAD

**Issue by Peascalate** [FPtje/DarkRP#3024]
https://github.com/FPtje/DarkRP/issues/787#issue-16611444
Related to the same issue, I took the code directly from the DarkRP hud code
Works when I save my files

**Comment by Kefta** [comment]
Check for earlier errors in your console that would halt loading.

**Comment by Peascalate** [comment]
All I see is the CSS Not Loaded error

**Comment by FPtje** [comment]
I'm going to close this issue until reasonable evidence is presented stating that DarkRP is responsible for this issue.
