### ISSUE TITLE
Ingame vocal problem

### ISSUE THREAD

**Issue by FireWolf-kPanel** [FPtje/DarkRP#3025]
### Description of the bug
[//]: # Hello, i've recently played the DarkRP mode and SCPRP mode an noticed something.

On every servers i played, i hear everyone everywhere on the map (not normal for darkrp mode)

On my server too there is the problem, i've tried to change sv_alltalk, but nothing to do...

Is this a bug from gmod or a misconfigured thing due to gmod update ?.

### How to make the bug happen
[//]: # Just run a darkrp based server, and you will notice vocal chat is messed up.

### Lua errors
[//]: # Not a single error

### Why the developer of DarkRP is responsible for this issue
[//]: # This is happening on every darkrp based server, is the a bug from gmod or a misconfigured thing due to gmod update ?

**Comment by FPtje** [comment]
No, I don't think so. Last GMod update was in April, and I know voice has worked reasonably fine with that update. Other than the voice quality update and sometimes not hearing any voices I haven't noticed much of a difference.

**Comment by FireWolf-kPanel** [comment]
Any idea of how to fix this ?

**Comment by FPtje** [comment]
Just asked around, my mate Gizmo said it could be an addon messing things up. Also, there's some options in the darkrp settings about 3d voice and voice radius. You should check those out.
