### ISSUE TITLE
[REQUEST] Hook for FAdmin Kick

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3028]
### Description of the bug
Currently, there is no hook that runs after a player has been kicked like `FAdmin_StoreBan` for a ban or `FAdmin_UnBan` for a unban. It could be called `FAdmin_OnKick`, `FAdmin_Kick` or whatever you want.

### How to make the bug happen
This is not a bug

### Lua errors
None

### Why the developer of DarkRP is responsible for this issue
FAdmin is in DarkRP

**Comment by jackson11** [comment]
Not developer of DarkRP, but what purpose would this serve?

**Comment by FlorianLeChat** [comment]
Mostly for logging systems. By the way, this request is made because I'm developing an Discord alert system that sends me notifications when a ban/kick or unban happens. 

I use the `FAdmin_StoreBan` hook to log bans, `FAdmin_UnBan` for unban and for now I use `FAdmin_OnCommandExecuted` for kick but it's not very easy for everyone.
