### ISSUE TITLE
Unable to get the PlayerSay hooks table

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3029]
### Description of the bug
(Recently?) It's now not possible to get hooks table for "PlayerSay" using `hook.GetTable().PlayerSay` or `hook.GetTable()["PlayerSay"]`.
This problem only affects DarkRP because it works very well in Sandbox or in TTT.
I tested this with the launch parameters `-noaddons -noworkshop`.

### How to make the bug happen
- Go in singleplayer or create a LAN server in DarkRP.
- Type `lua_run hook.Add("PlayerSay", "test", function(ply, text, teamChat) end)` or create a script with a "PlayerSay" hook.
- Type `lua_run PrintTable(hook.GetTable()["PlayerSay"])`.
- Nothing's happens...

I'm not sure, but I think the problem started since #3011.

### Lua errors
None.

### Why the developer of DarkRP is responsible for this issue
I may be an idiot, but this only affects the DarkRP gamemode.

**Comment by noaccessl** [comment]
https://github.com/FPtje/DarkRP/blob/df9e7275aba0b3383523f4a6b4de5b4715a55358/gamemode/modules/chat/sv_chat.lua#L294
This, hook which delete other Player Say hooks. You can stop this, if you create lua file in lua/autorun/Server and write there
hook.Remove( 'InitPostEntity', 'RemoveChatHooks' )

**Comment by mcNuggets1** [comment]
This is intended for DarkRP.

**Comment by FlorianLeChat** [comment]
In my memories, I thought it was still possible of that not long ago, but I have seen that it was already the case after testing with an old version.

Thanks for your suggestion @noaccessl but I will use `GAMEMODE.OldChatHooks` which gives the same result as `hook.GetTable() ["PlayerSay"]`.
