### ISSUE TITLE
How Do you permanently  up the amount of NPCs 

### ISSUE THREAD

**Issue by r3azy** [FPtje/DarkRP#3030]
I want my server to have a Cap of 500 NPCs. How do I do that because it never stays that high?

**Comment by Kefta** [comment]
sbox_maxnpcs or something like that.

**Comment by r3azy** [comment]
Thanks

**Comment by FoksVHox** [comment]
This isn't for support, but for bug reports.....

**Comment by FPtje** [comment]
Yeah, darkrp forums shut down. Head to the discord instead.
