### ISSUE TITLE
How do you disable the Context Menu, the q menu for everyone but staff

### ISSUE THREAD

**Issue by r3azy** [FPtje/DarkRP#3031]
Me and my staff have been trying to disable the context menu and the q menu but we can't fix it. How would I go about doing this

**Comment by r3azy** [comment]
Also, how do you make it where staff spawn without the Admin weapons

**Comment by FoksVHox** [comment]
This isn't for support, but for bug reports.....

**Comment by r3azy** [comment]
Where do I get help then the Fourms are shut down

**Comment by FoksVHox** [comment]
On the Discord.

**Comment by r3azy** [comment]
What is the discord

**Comment by FoksVHox** [comment]
If you read the [post](https://forum.darkrp.com/threads/darkrp-websites-and-forums-are-shutting-down-read-more.7547/), you'd find the Discord.
