### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mark27205** [FPtje/DarkRP#3035]
Hello,

the old documentation seems to be down? Is there a new version of it, and if so I would appreciate a link to it. I already found a link to the forums, but it seems that the forums are down aswell.

Greetings,
mark272

**Comment by FlorianLeChat** [comment]
Old DarkRP Wiki/Forum have been shutdown on July 31st.

This is the new wiki link: https://darkrp.miraheze.org/wiki/Main_Page
And the forum has been replaced by a Discord server: https://discord.com/invite/DYxVExH

**Comment by mark27205** [comment]
Thanks for the quick reply.
