### ISSUE TITLE
Lua error with implementation of door updating

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/DarkRP#3038]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://discord.com/invite/DYxVExH )

### Description of the bug
You probably forgot about LocalPlayer being invalid, the first few seconds.
Hook into InitPostEntity and then add your timer (doing this via a 3 second timer is stupid anyways imo)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Join

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[//]: # (Describe the issue as accurately as possible)
[_ulib] addons/_ulib/lua/ulib/shared/sh_ucl.lua:47: attempt to call method 'SteamID' (a nil value)
1. query - addons/_ulib/lua/ulib/shared/sh_ucl.lua:47
2. real_fn - addons/_ulib/lua/ulib/shared/cami_ulib.lua:18
3. unknown - addons/_ulib/lua/autorun/_ulib_hooks.lua:176
4. Call - addons/_ulib/lua/autorun/_ulib_hooks.lua:282
5. PlayerHasAccess - addons/_ulib/lua/ulib/shared/cami_global.lua:360
6. unknown - gamemodes/darkrp/gamemode/modules/doorsystem/cl_doors.lua:8

Timer Failed! [Door changeDoorAccess checker][@gamemodes/darkrp/gamemode/modules/doorsystem/cl_doors.lua (line 13)]

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Their addition

**Comment by FPtje** [comment]
>  this via a 3 second timer is stupid anyways imo

What's your alternative?
