### ISSUE TITLE
Error attempt to call field 'IsEmpty' (a nil value) (Default files no other addons)

### ISSUE THREAD

**Issue by kulcris** [FPtje/DarkRP#3045]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://discord.com/invite/DYxVExH )

### Description of the bug
[//]: # (Describe the issue as accurately as possible 
All addons disabled, no edits made

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Clean install start server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[ERROR] gamemodes/darkrp/gamemode/libraries/tablecheck.lua:157: attempt to call field 'IsEmpty' (a nil value)
  1. f - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:157
   2. f - gamemodes/darkrp/gamemode/libraries/fn.lua:185
    3. v - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:67
     4. f - gamemodes/darkrp/gamemode/libraries/tablecheck.lua:85
      5. validateJob - gamemodes/darkrp/gamemode/libraries/fn.lua:174
       6. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:426
        7. unknown - gamemodes/darkrp/gamemode/config/jobrelated.lua:8
         8. include - [C]:-1
          9. unknown - gamemodes/darkrp/gamemode/init.lua:104

[ERROR] gamemodes/darkrp/gamemode/libraries/simplerr.lua:530: [ERROR] A runtime error has occurred in "lua/darkrp_customthings/jobs.lua" on line -1.
The best help I can give you is this:

GAMEMODE.DefaultTeam is not set to an existing job.

Hints:
        - This may happen when you disable the default citizen job. Make sure you update GAMEMODE.DefaultTeam to the new default team.
        - GAMEMODE.DefaultTeam may be set to a job that does not exist anymore. Did you remove the job you had set to default?
        - The error being in jobs.lua is a guess. This is usually right, but the problem might lie somewhere else.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
        jobs.lua, settings.lua, disabled_defaults.lua or any of your other custom files.
------- End of Simplerr error -------

  1. error - [C]:-1
   2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:530
    3. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:1001
     4. Call - gamemodes/darkCouldn't Load Init Script: 'darkrp/gamemode/init.lua'

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
No other addons installed no scripts running as far as i can tell. 
srcds.exe -console -game garrysmod +map gm_construct +gamemode darkrp +maxplayers 4 -condebug

### Other Info
My startup log
[startuplog.txt](https://github.com/FPtje/DarkRP/files/5087866/startuplog.txt)
![image](https://user-images.githubusercontent.com/2667394/90464242-7fcb3800-e0d2-11ea-939f-26d07ee7b1de.png)
![image](https://user-images.githubusercontent.com/2667394/90464291-95406200-e0d2-11ea-841d-09753c2b27e8.png)
I have reinstalled darkrp

**Comment by kulcris** [comment]
Complete fresh install of server fixed issue, no idea what was causing it.

**Comment by FPtje** [comment]
Resetting your config fixed it. Look at this part of the error:
```
GAMEMODE.DefaultTeam is not set to an existing job.


Hints:
- This may happen when you disable the default citizen job. Make sure you update GAMEMODE.DefaultTeam to the new default team.
- GAMEMODE.DefaultTeam may be set to a job that does not exist anymore. Did you remove the job you had set to default?
- The error being in jobs.lua is a guess. This is usually right, but the problem might lie somewhere else.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
jobs.lua, settings.lua, disabled_defaults.lua or any of your other custom files.
```

**Comment by kulcris** [comment]
No I full reinstalled darkrp and modifications multiple times.
I copied over the "broken files" to the fresh install and they worked fine
so it was something with my install

**Comment by FPtje** [comment]
Do you uses FileZilla by any chance?

**Comment by kulcris** [comment]
Not for this. It is a local server

**Comment by Kapppa** [comment]
It was broken because the server was out of date. It was missing table.IsEmpty function which was added in the past year or so.

**Comment by kulcris** [comment]
Nope. fully up to date. But no worries fresh install fixed must have been
currpt install
