### ISSUE TITLE
Error when opening tab

### ISSUE THREAD

**Issue by Yoshi-OOF** [FPtje/DarkRP#3052]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
I try to open my tab and to put order by kill but this error appear : 
https://pastebin.com/58ujREAS
Since, when i want to open my tab it's like that :
http://prntscr.com/ug5a43

### How to make the bug happen
The bug appear when i try to put sort by kills

### Lua errors
```
[sam-133] lua/includes/extensions/table.lua:515: attempt to compare number with string
  1. unknown - lua/includes/extensions/table.lua:515
   2. sort - [C]:-1
    3. SortedPairs - lua/includes/extensions/table.lua:515
     4. SortedPairsByFunction - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_playerlists.lua:20
      5. PlayerListView - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_playerlists.lua:36
       6. Show - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_scoreboardmain.lua:66
        7. func - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/cl_interface/cl_scoreboard.lua:108
         8. unknown - addons/sam-133/lua/includes/modules/hook.lua:198 (x4)
```

### Why the developer of DarkRP is responsible for this issue
Because i didn't see why that do that

**Comment by Yoshi-OOF** [comment]
resolved sorry

**Comment by FPtje** [comment]
The error looks like you've edited DarkRP core files. Next time you get an error, know that I don't provide any support whatsoever if you edit DarkRP core files. I'm not fixing your errors.
