### ISSUE TITLE
Problem with scoreboards/f4 menus

### ISSUE THREAD

**Issue by VacAndCheese** [FPtje/DarkRP#3055]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
First time using Github, so please excuse me as I am probably doing this completely incorrectly. I am using Starwarsrp, but it should probably be about the same, and theres not really a place to put it so i guess im doing it here. So basically im stupid. I have been trying to apply a f4 menu for weeks, but no matter what i do it either keeps the default f4 menu or just outputs an error in console rather than actually opening it. I feel like im doing a simple mistake and ive tried looking up how to do it but none of the ways i have seen have worked. Im using Vliss scoreboard: https://www.gmodstore.com/market/view/vliss-scoreboard-keep-tabs-with-style-plaxus-collection and it says to put it into the addons folder but that doesnt work: it just uses the default one instead. So this time i tried deleting it from the gamemode and putting in vliss, then renaming it "f4menu" thinking maybe i had to do that. Nope. Just lua errors every time i try to 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Delete the f4 menu from the darkrp/swrp gamemode in modules

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[ERROR] gamemodes/starwarsrp/gamemode/modules/base/cl_gamemode_functions.lua:27: attempt to call field 'toggleF4Menu' (a nil value)
  1. Call - gamemodes/starwarsrp/gamemode/modules/base/cl_gamemode_functions.lua:27
   2. unknown - gamemodes/starwarsrp/gamemode/modules/base/cl_gamemode_functions.lua:62

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Not gonna lie, I have no clue who to report this to. just thought maybe you could help, understand if you dont

**Comment by VacAndCheese** [comment]
Oh my fucking god im an idiot vliss isnt the right addon... it doesnt have a f4 menu...

**Comment by FPtje** [comment]
So the website went down a while ago, but hey, here's a video of that website that brings you the exact same message:
https://www.youtube.com/watch?v=AJsBkR5QvuE
