### ISSUE TITLE
Sleep module problem with moved bodies

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3056]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

**With the reporting of this issue, I know that I'm partly responsible because the body is already protected against the use of the physgun or toolgun (probably because of problems that can occur)**. But after all these years that this module exists, maybe it would be so good to improve it a little bit?
___

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
A while ago, I created a small script which allows to carry the bodies of the players being in sleep. But I found a small problem when using it with the `sleep` module.

Let's take the example of **2** players :
- **Player 1** is the one who is carrying the body.
- **Player 2** is the one sleeping.

When **Player 2**'s body hasn't moved yet and tries to use /me to make actions or just talk, **Player 1** can hear correctly.
However if **Player 2**'s body is moved a little too far from its original position then it is no longer possible to communicate between them.

This problem is clearly due to the fact that the position of **Player 2** (not the body) is **NEVER** updated and so if the body is moved too far then logically the two cannot talk to each other.

For the moment, this problem is solved on my side using this dirty workaround, but it might be a good idea to make a better fix to the gamemode.

```lua
local string_lower = string.lower

hook.Add("onChatCommand", "Raven.Gamemode.DarkRP_Sleep", function(ply, command, args)

    command = string_lower(command)

    if command == "sleep" or command == "wake" or command == "wakeup" then

        local timerName = "Raven.UpdateSleepPosition." .. ply:SteamID64()

        if ply.Sleeping then

            timer.Remove(timerName)

        else

            local ragdoll = ply.SleepRagdoll

            timer.Create(timerName, 2, 0, function()

                if ply:IsValid() and ragdoll:IsValid() then

                    ply:SetPos(ragdoll:GetPos())

                else

                    timer.Remove(timerName)

                end

            end)

        end

    end

end)
```

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
- Create a server (dedicated or LAN)
- Invite a player (or use a bot).
- One of both players use the `/sleep` command.
- Move the player's body quite far away.
- Try to communicate.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because the `sleep` module is included by default in the gamemode.

**Comment by mcNuggets1** [comment]
PlayerTick to kill all performance.

**Comment by FlorianLeChat** [comment]
You're right, I updated my workaround a few days ago for something more efficient (see above).

**Comment by FPtje** [comment]
Setting move type and parenting seems like the cleanest solution to me. The move type has to be set because otherwise the player teleports between 0,0,0 and the ragdoll's position many times per second clientside.

Tell me if there are any problems with this solution.
