### ISSUE TITLE
Serverside darkrp modules can't be reloaded by auto-refresh.

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3057]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Everything is in the title. Serverside or (**partially**) shared files cannot be refreshed when they are included in a module of the darkrpmodification addon. This is quite annoying because I make a lot of modifications and I have to restart the server or the singleplayer instance each time, I finally decided to create an addon next to it to avoid this issue. However, it would be nice if this problem could be fixed.

**I use the latest Workshop version of the gamemode and I don't use any beta version of Garry's Mod.**

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
- Create a folder with whatever name you want in the `darkrp_modules` folder.
- Put inside a file with the name `sv_<what you want>.lua`.
- Write something inside to make it load properly (ex: `print(1)`).
- Start a singleplayer instance, LAN or try this on a dedicated server.
- Modify the file with `print(2)` for example.
- Look at the console: `Unhandled Lua Refresh: [NAME:darkrp_modules/<module name>/sv_<file name>.lua]`.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
No Lua error, just a message saying that the file could not be handled.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because the DarkRPModification addon is internally linked to the DarkRP gamemode.

**Comment by FPtje** [comment]
It's been happening since I introduced simpler I think. It's a limitation int he mechanism. Since there are no hooks to it, it is impossible for me to fix it. You can try adding a no simpler comment (not sure what the exact syntax was) in files you want to actively work on. Other than that there's nothing I can do. 

https://wiki.facepunch.com/gmod/Auto_Refresh

**Comment by FlorianLeChat** [comment]
Okay, thank you for your quick answer!
