### ISSUE TITLE
[Request] Add hooks when a player interacts with default DarkRP entities.

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3063]
### Description of the request
It would be nice for new modders to add hooks when a player interacts with a DarkRP entity (detouring the `Use` function in entity tables is not easy). It would typically be called after the hook `canDarkRPUse`. The [money entity](https://github.com/FPtje/DarkRP/blob/aa0dc11eb1a9018be17f7fb262180e386d28861e/entities/entities/spawned_money/init.lua#L35) already has that and could be extended to other `spawned_*` entities or all default entities if possible.

I could have made a pull request to make these changes but I wouldn't have my laptop to do and test this for a while.

**Comment by mcNuggets1** [comment]
Use PlayerUse or detour DarkRP entities.

**Comment by FlorianLeChat** [comment]
`PlayerUse` is called before `canDarkRPUse`, so it's still not right. And as for the detour, it's to prevent the new modders from doing that, I want to make it easier for them which is the purpose of my request.

I know this reason is a bit stupid but a lot of people are starting to take their first steps in modding on DarkRP, some of them are not very familiar with this kind of things, so I think it might help some people, it's my point of view.

**Comment by mcNuggets1** [comment]
Detouring is encouraged by DarkRP via the entitysettings module for example which is perfectly capable of doing so.
Just do a pull request once you're home, I guess.
