### ISSUE TITLE
Pysgun Twirl bug

### ISSUE THREAD

**Issue by KennyHarrer** [FPtje/DarkRP#3065]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
physgun_check works while in a chair (finger twirl thing)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
pull out your physgun, sit in a chair. Aim at a player and left click.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
n/a

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
because you missed a check

I would make a pull request but I can't be fucked to do it right now.

**Comment by mcNuggets1** [comment]
Dafuq

Get fucked to do it please, we don't understand.

**Comment by KennyHarrer** [comment]
> 
> 
> Dafuq
> 
> Get fucked to do it please, we don't understand.

Done :)

**Comment by FPtje** [comment]
Fixed by #3066
