### ISSUE TITLE
Stunstick does too much damage to entities

### ISSUE THREAD

**Issue by WilliamVenner** [FPtje/DarkRP#3070]
https://github.com/FPtje/DarkRP/blob/bb531405cf82120de7cedc54b5cda5cc6a7a550f/entities/weapons/stunstick/shared.lua#L163

The stunstick should not assume all entities are illegal and immediately 1 tap them. If you've created an entity that players need to gradually destroy one guy could just come in with a stunstick and destroy it instantly regardless of if it's illegal or not.

**Comment by FPtje** [comment]
One tapping those entities was the point of the stunstick. I see no way to change it without pissing a lot of people off.

**Comment by Kefta** [comment]
Add a configuration variable to the stunstick instead of hardcoding the damage. It should also scale to the entity's health since it will not instant kill an entity with more than 1000 damage.

**Comment by FPtje** [comment]
That I can do I suppose

**Comment by WilliamVenner** [comment]
Config options?

0 = Normal damage
1 = Maximum damage
2 = Maximum damage if ent.SeizeReward

**Comment by FPtje** [comment]
Just a number for the damage will do I suppose

**Comment by Kefta** [comment]
A negative number should indicate the entity's total health, and perhaps function keys should be allowed. Ex.
```
SWEP.Damage = function(ent) return ent:Health() / 2 end
```

**Comment by mcNuggets1** [comment]
if SeizeReward exists, do bad damage, if not, do normal damage, easy solution.
