### ISSUE TITLE
DarkRP stunstick doesn't show the props scraps on destruction

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3071]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I think this was a long time ago but I noticed recently a small issue with the stunstick when used on destructible props. Of all the DarkRP weapons that can do damage to something, this is the only one that doesn't display the destruction scraps of a prop. When a prop is broken, the prop is just removed but there are no traces of the usual scraps (especially on **wooden props**).
I consider this as a "**bug**" since I don't understand why a stunstick could do that.

I looked at the source code of the stunstick as well as the `stick_base` to see something that could prevent this, but honestly, I have no idea.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
- Start a singleplayer game (or join a dedicated server).
- Take the DarkRP stunstick.
- Spawn a breakable prop (like `models/props_junk/wood_crate001a.mdl`).
- Use left or right click on it (prop is removed but nothing appears).
- Take now a random DarkRP weapon (`weapon_ak472` for example).
- Shoot on it.
- See the wood scraps.

![image](https://user-images.githubusercontent.com/26360935/101616811-1e77fd80-3a10-11eb-885e-0b5dd7a915b8.png)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
There is no Lua error.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The stunstick is in the gamemode.

**Comment by LuaFan2** [comment]
Try to replace ent:TakeDamage with ent:TakePhysicsDamage in SWEP:DoAttack function in stunstick code and see what will happen

**Comment by FlorianLeChat** [comment]
I don't think it comes from here because I have a script that uses TakeDamage on props and there is no issue. But, I'll give it a try.

**Comment by FPtje** [comment]
Looks like it's some bug in SWEPs:

Write the following function:

```lua
function damageEntityFalco(ent, Owner)
    local damage = DamageInfo()
    damage:SetAttacker(Owner)
    damage:SetInflictor(Owner:GetActiveWeapon())
    damage:SetDamage(1000)
    ent:TakeDamageInfo(damage)
end
```

In a local listen server, spawn a box, look at it with the host player, run the following console command:

```lua
lua_run damageEntityFalco(Player(2):GetEyeTrace().Entity, Player(2))
```

The prop will gib.

Then replace the `PrimaryAttack` function with the following code:

```lua
function SWEP:PrimaryAttack()
    if CLIENT then return end
    local ent = self:GetOwner():GetEyeTrace().Entity
    if IsValid(ent) then damageEntityFalco(ent, self:GetOwner()) end
end
```

Hit a prop. Find that the prop does not create gibs. Exact same function call, exact same entity, exact same player. This is a GMod bug.

**Comment by Kefta** [comment]
It's probably something to do with prediction/SuppressHostEvents skipping damage effects.
