### ISSUE TITLE
Cant /wake when i use /sleep

### ISSUE THREAD

**Issue by Hache288** [FPtje/DarkRP#3075]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # Cant use the command /wake when i use /sleep

### How to make the bug happen
[//]: # Use /sleep

### Lua errors
[//]: # [DarkRP] gamemodes/darkrp/gamemode/modules/sleep/sv_sleep.lua:174: attempt to index global 'ply' (a nil value)
  1. callback - gamemodes/darkrp/gamemode/modules/sleep/sv_sleep.lua:174
   2. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
    3. RP_PlayerChat - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:78
     4. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:244

[https://youtu.be/hytLBmgaLRw](https://youtu.be/hytLBmgaLRw)

**Comment by FlorianLeChat** [comment]
The bug was introduced starting this commit: https://github.com/FPtje/DarkRP/commit/aca6a007a254a168dbd3ece005abe9868a339f25. There is an inconsistency issue in the code, if you want to make a temporary workaround, just replace `ply` by `player`.

**Comment by FPtje** [comment]
CC @mcNuggets1
