### ISSUE TITLE
F4 Menu ammo buying issue

### ISSUE THREAD

**Issue by Loganniere** [FPtje/DarkRP#3079]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (When I try to buy Ammo in the f4 menu it doesnt spawn anything but withdraw my money and the message)

### How to make the bug happen
[//]: # (I don't relly know I think I added an addon and it make it happen)
[//]: # (I think its an addon)

### Lua errors
[//]: # ([ERROR] gamemodes/darkrp/gamemode/modules/base/sv_purchasing.lua:419: Tried to use a NULentity!
1. SetModel - [C]:-1
2. callback - gamemodes/darkrp/gamemode/modules/base/sv_purchasing.lua:419
3. callback - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
4. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:325
5. unknown - lua/includes/modules/concommand.lua:54)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

pls thx

**Comment by FoksVHox** [comment]
This isn't an issue with DarkRP, this is an issue with your config.

**Comment by Loganniere** [comment]
so what I need to do?
what files or what folder?

**Comment by Loganniere** [comment]
ok I reinstalled the entire gamemode folder od darkrp and now works

**Comment by FoksVHox** [comment]
Then close the issue
