### ISSUE TITLE
Changed name too many times.

### ISSUE THREAD

**Issue by alexistb2904** [FPtje/DarkRP#3081]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

When I connect to the server I get kicked for "Changed name too many times." while i change rpname only once i have to reconnect a second time so that i can play

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
To log in

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by TomDotBat** [comment]
Are you using ULX? I'm pretty sure ULX has nickname spam prevention that kicks you.

**Comment by FPtje** [comment]
DarkRP is not kicking people for changing names. Mostly because that's a dumb way of dealing with it. 

Never forbid by rule that which can be prevented by design. You can make it so people *cannot* change their names often with a simple timer. No need to kick anyone.
