### ISSUE TITLE
Gamemode bug

### ISSUE THREAD

**Issue by Lexa013** [FPtje/DarkRP#3083]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Spam console error logs, see screen below, im not the only one with this issue, i've freshly reinstalled DarkRP 2 times

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
When the first player join

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
![image](https://user-images.githubusercontent.com/48451588/104368072-e5094500-551b-11eb-9631-32c2eb711223.png)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because it's the developer thx captains obvious

**Comment by FPtje** [comment]
That error doesn't happen unless you seriously break things. The message that `Http.Fetch` is not available on the server might be a hint, that function should be in gmod [by default](https://wiki.facepunch.com/gmod/http.Fetch).

Look for errors that happen during server startup, way before the first player joins.

> ### Why the developer of DarkRP is responsible for this issue
> Because it's the developer thx captains obvious

Guess what, the answer to this question is most likely that I'm not. That's why I want people to seriously think about this question.

**Comment by FPtje** [comment]
You can continue posting in this issue, despite it being closed. Please do not create new issues.

**Comment by MrBrax** [comment]
could it be a server host disabling it because of abuse?

**Comment by FoksVHox** [comment]
@FPtje & @MrBrax the `Http.Fetch` error is due to that it's getting used before it is available. The best way to prevent this is by using a hook to detect a player joining or wait for the first `Think` hook.

**Comment by FPtje** [comment]
Ugh, gmod shenanigans. Either way, it was merely a hint. I still suspect earlier things are broken.
