### ISSUE TITLE
Expose maxEntities

### ISSUE THREAD

**Issue by someoneyouspite** [FPtje/DarkRP#3084]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I was wanting to restrict access to cop jobs if players already had money printers spawned.
Exposing the maxEntities table as a global would solve my issue.
https://github.com/FPtje/DarkRP/blob/35ca64069be4e090604544d9fe8a4b41aafeba87/gamemode/modules/base/sv_entityvars.lua#L223

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
This is a feature request.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
It's not possible to achieve what I want without editing the core files, which the developer of DarkRP strongly suggests against.

**Comment by FPtje** [comment]
That `maxEntities` table is used to keep track of whether players have reached their maximums of bought entities. It is not used for other purposes. There are other ways to check whether a player has money printers spawned.


You can already loop through entities:
```lua
local function playerHasMoneyPrinters(ply)
    for _, ent in pairs(ents.FindByClass("your_money_printer_class")) do
        if ent.SID == ply.SID then
            return true
        end
    end
end
```

If you want to be efficient, you can register who owns what:

```lua
hook.Add("playerBoughtCustomEntity", "cop jobs no money printers", function(ply, entTable, ent)
    if ent:GetClass() ~= "your_money_printer_class" then return end
    ply.registered_money_printers = ply.registered_money_printers or {}

    for k, printer in pairs(ply.registered_money_printers) do
        if not IsValid(printer) then
            ply.registered_money_printers[k] = nil
        end
    end

    table.insert(ply.registered_money_printers, ent)
end)
```

You can then check whether the player has money printers as follows:

```lua
local function playerHasMoneyPrinters(ply)
    ply.registered_money_printers = ply.registered_money_printers or {}

    for k, printer in pairs(ply.registered_money_printers) do
        if not IsValid(printer) then
            ply.registered_money_printers[k] = nil
            continue
        end
        return true
    end
end
```

**Comment by someoneyouspite** [comment]
I solved my issue by forking DarkRP and using a simple, more efficient method.
```lua
function meta:customEntityCount(entTable)
	local entities = maxEntities[self]
	return (entTable and entities) and entities[entTable.cmd] or 0
end
```
Naming the table `maxEntities` doesn't change the fact it's a table with the count of the entities per player. It's used internally for the same reason I want to use it externally, **to get the current count of the entities a player has**.
Feel free to use my snippet if you want, it's more efficient and an overall better solution.

**Comment by FPtje** [comment]
That use case is fair.

**Comment by someoneyouspite** [comment]
I created a pull request if you would like to use that.
https://github.com/FPtje/DarkRP/pull/3085
