### ISSUE TITLE
unable to make lottery

### ISSUE THREAD

**Issue by Loganniere** [FPtje/DarkRP#3089]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
as mayor I can't start a lottery it says: unable to start a lottery

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
is not a bug its an error

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
none

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
because I don't touch anything about lotteries

**Comment by FlorianLeChat** [comment]
In code, this is the only case where the error message you quoted appears: https://github.com/FPtje/DarkRP/blob/db0babac196623366f520a358a56ce9f436c6854/gamemode/modules/police/sv_commands.lua#L101-L104. You need at least 3 players and a lottery has not already started.

**Comment by TomDotBat** [comment]
It probably isn't a bug, but a more descriptive error message would be helpful as "unable to start lottery" suggests a problem occurred internally.

**Comment by Loganniere** [comment]
> In code, this is the only case where the error message you quoted appears:
> 
> https://github.com/FPtje/DarkRP/blob/db0babac196623366f520a358a56ce9f436c6854/gamemode/modules/police/sv_commands.lua#L101-L104
> 
> 
> You need at least 3 players and a lottery has not already started.
> You should ask for help on the DarkRP Discord or help forums as I don't think this is a bug.

THANK YOU SO MUCH
(fast help, nice!)
