### ISSUE TITLE
[BUG] Players can Kill Npcs After the NEW GMOD UPDATE!

### ISSUE THREAD

**Issue by anyome** [FPtje/DarkRP#3091]
issue fixed thanks !

**Comment by FlorianLeChat** [comment]
This is not a DarkRP bug. You must use https://wiki.facepunch.com/gmod/ENTITY:OnTakeDamage to block the damage to your NPC.

**Comment by anyome** [comment]
> 
> 
> This is not a Gmod/DarkRP bug. You must use https://wiki.facepunch.com/gmod/ENTITY:OnTakeDamage to block the damage to your NPC. This is a change introduced in the last update: https://gmod.facepunch.com/blog/january-2021-update.

Hey thanks for the reply!

So i should Edit all my Npcs on my server to Block the damage?!

I can't do it with just One Script?

Because i have too many Npcs like +50 Npcs on my server...

Having to edit all of the single ones will take an Eternity !

**Comment by FlorianLeChat** [comment]
Someone on Gmod Discord has made a script to fix this on all concerned entities: https://discord.com/channels/565105920414318602/567617926991970306/804698356202995732 (serverside only).
