### ISSUE TITLE
[FAdmin] can't use console commands to spectate

### ISSUE THREAD

**Issue by Kapsulon** [FPtje/DarkRP#3092]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I can't use console commands to spectate with FAdmin.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
if i type "fadmin god %name%" in my console the player gets put in god mode, but if i type "fadmin spectate" in it, i get "Command does not exist!", i find this really strange. (same result if i put a player after the command).

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
(not really a lua error but it is the only one i get)
```lua
"Command does not exist!"
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I am trying to use a command that is created by this gamemode, all the other commands seems to work but not this one.

**Comment by Kapsulon** [comment]
After reading some of the gamemode's core files, i found that the command is actually fspectate for a strange reason, even tho it isn't "autofilled" in the console, sorry for bothering.

**Comment by DBotThePony** [comment]
Because FSpectate is separate from FAdmin for ages now, you can see it [on steam workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=559017762) and on [github repo](https://github.com/FPtje/FSpectate)
