### ISSUE TITLE
Error DarkRp

### ISSUE THREAD

**Issue by DydyGames** [FPtje/DarkRP#3107]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

Error spam in my console server

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

when i connect in my server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:348: attempt to index a nil value
1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:348

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

I have nothing to modify in the darkrp, it is surely a problem in the files?

**Comment by WilliamVenner** [comment]
> I have nothing to modify in the darkrp, it is surely a problem in the files?

If you have literally any addon installed on your server that isn't DarkRP or darkrp-modification, then it could be any of those addons...??

**Comment by DydyGames** [comment]
Wouldn't darkrp gamemode be compatible with 1 of my addons?

**Comment by FoksVHox** [comment]
It depends if the addon is broken lol

**Comment by DydyGames** [comment]
yes, the gamemode darkrp was not compatible with one of my addons, i found them, thank's :)
