### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Alaneczek123123851** [FPtje/DarkRP#3109]
When i place law board it says in console

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. function 'Spawn'
	2. gamemodes/darkrp/entities/entities/darkrp_laws/init.lua on line 163
	3. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 17
	4. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 78
	5. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 244
------- End of Simplerr error -------

**Comment by FoksVHox** [comment]
Use the template...

**Comment by FPtje** [comment]
Cannot reproduce. The error looks like it might come from hitting the entity limit.
