### ISSUE TITLE
settings.lua half working

### ISSUE THREAD

**Issue by Baseyoyoyo** [FPtje/DarkRP#3110]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

I was told on the darkrpmodification page to post this here

https://github.com/FPtje/darkrpmodification/issues/158

I've been using the most recent version of darkrpmodification on my server and I've got around to changing the settings.

Changing the spawn limitations work perfectly fine e.g.: NPC limit, Ragdoll limit, Thruster limit, Who can spawn weapons etc... They all work perfectly fine however the true/false toggle settings don't work at all.

Below are some of the settings I've changed and none of them have actually change in-game:

GM.Config.AdminsCopWeapons = false
GM.Config.allowsprays = false
GM.Config.dropspawnedweapons = false
GM.Config.norespawn = false

I'm running a fresh install of the server with bare essential addons

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Install the latest version of darkrp and darkrpmodification. Change file details

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No errors

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

The basic function of the darkrp game mode doesn't work

**Comment by Baseyoyoyo** [comment]
Update: After hours of testing different things I've discovered that if I overwrite the file while the server is running, so replace the default settings.lua with my custom one then the toggle rules actually work. So I respawn when I change job, people cant use sprays etc.

Now the issue is that when I restart the server after uploading it doesn't work. The custom file is still there but none of the toggle rules work.

I will attach a video to better show this because im terrible at explaining

**Comment by FPtje** [comment]
Are you sure there isn't a settings file that is loaded after your own settings file? That would explain why saving while server is running does work.

**Comment by Baseyoyoyo** [comment]
I don't believe so. I freshly installed both modules yesterday. If there was an additional settings file running wouldn't that remove the spawn limitations I changed too?

**Comment by FPtje** [comment]
I just started a local game, and set the following options in `settings.lua`

```
GM.Config.AdminsCopWeapons = false
GM.Config.allowsprays = false
GM.Config.dropweapondeath               = true
GM.Config.dropspawnedweapons = false
GM.Config.norespawn = false
``` 

When running `/medic`, I respawned, without cop weapons. The spray command did show a `ServerLog` entry, but no spray was created. Also, I dropped weapons on death, but only the weapons that I gave myself through Q menu.

> I don't believe so. I freshly installed both modules yesterday. If there was an additional settings file running wouldn't that remove the spawn limitations I changed too?

Not if it's an addon that only forces certain settings. Perhaps there's some addon that doesn't work if players can change jobs without respawning.

Either way, I cannot reproduce the issue.
