### ISSUE TITLE
sometimes unable to switch to custome jobs

### ISSUE THREAD

**Issue by gibiis12** [FPtje/DarkRP#3111]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible) wile in the server im sometimes unable to switch between my costume jobs

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out) enter f4 menu and try switching between costume jobs, Note my job switch cool down is at 1 second
[//]: # (what the cause of the problem is and whether a certain fix solves it)
when i switch to citizen im sometimes able to switch to that job.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones) there no lua errors in console
[//]: # (because they can cause other errors. Always look in the startup log of the server!) a few startup problems nothing about
darkrp thoe

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)  yes
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it) i have tried to troubleshoot it multiple times i have changed my f4 menu as well as edited unneeded parts of my costume jobs

Did i do something wrong:
here my template.

TEAM_Citizen1 = DarkRP.createJob("Citizen", {
    color = Color(0, 0, 0, 255),
    model = {"models/player/barney.mdl"},
    description = [[you are big boi]],
    weapons = {},
    command = "Citizen1",
    max = 0,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = ""Citizens "",
    PlayerSpawn = function(ply)
        ply:SetMaxHealth(100)
        ply:SetHealth(100)
        ply:SetArmor(100)
    end
})

**Comment by FPtje** [comment]
Besides the job switch delay, there's also a delay for entering commands. That might also play a role in why you can't switch job when you try too fast.

For more help please see the DarkRP discord.
