### ISSUE TITLE
Hobo right button is broken. It's not playing sound and spamming errors in server console.

### ISSUE THREAD

**Issue by Hardeh** [FPtje/DarkRP#3115]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
No right button sound on hobo, lua errors

Shouldn't it be "RPExtraTeams" instead of "RPExtrateams"? Seems like typo for me.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Press right button on bugbait when playing hobo

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
[ERROR] gamemodes/darkrp/gamemode/modules/hobo/sv_hobo.lua:26: attempt to index global 'RPExtrateams' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/hobo/sv_hobo.lua:26
   2. unknown - lua/includes/modules/concommand.lua:54

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Cause it's a bug in stock gamemode

**Comment by FPtje** [comment]
Looks like this was caused by #3078. Sorry.
