### ISSUE TITLE
DarkRP.log Bottleneck

### ISSUE THREAD

**Issue by Kapppa** [FPtje/DarkRP#3123]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

`DarkRP.log` causes large impact to performance when a large amount of people are connected to a server if a color is provided. This is because the function will calculate who can see the message every time. This is amplified on servers with a large amount of players as it takes longer to check all of the players and as there are more players more logs are likely to be made. The problem is that I cannot for the life for me figure out a better method for checking if the person has access to the function.

I am opening this issue with a solution to the lag at the cost of some accuracy. I propose that we use `PlayerConnect`, `PlayerDisconnect`, `CAMI.PlayerUsergroupChanged` and a 60 second timer to update who can see the logs. This means that when some Connects/UserGroup changes the list will update. However, if the permission is given to Rank/User they will not automatically have access to the logs for at most 60 seconds. This solves the lag issue as it only runs a couple of times a minute unless a lot of people connect. 

Now either I can create a commit to the Git with changes preposed or I can just override it on my servers. But I would rather have all server perform better. The reason I made this an issue rather that a PR is that this is a change that changes a large functionality of the logging feature and creates some 'security' issues.

Also if someone smarter than me could think of a way of creating a method of always having an up to date of getting perms that would be great.

**Comment by FPtje** [comment]
> `DarkRP.log` causes large impact to performance

How large is this impact? Do you have some measurements?

**Comment by Kapppa** [comment]
I will get some Later today.

**Comment by FPtje** [comment]
If possible please also demonstrate that it is an actual bottleneck. I find it hard to imagine that `DarkRP.log` of all functions is the most expensive one in any server tick. I may be wrong of course, but it _looks_ relatively innocuous, especially compared to e.g. FPP's touch data calculations.

**Comment by Kapppa** [comment]
That was going to be next target.

**Comment by mcNuggets1** [comment]
I think he has logging to file activated.

**Comment by Kapppa** [comment]
I had took some steps to reduce the impact of the function before creating this issue. First thing I tried was the file logging as syscalls will obviously cause lag. But it only reduced it by a small margin so it had to be the perm checking. So what I spent the last few days doing was changing the admin system the server was using, we were using ULib and ULX which are both outdated and laggy. ULib was modified to use sv.DB (it use to use .txt files to store all data so it had to write 80kb of data every time someone was banned/rank was changed) and ETC but this was a bandage solution. So we changed admin system and it has reduced the impact of the function.

I believe it should still be looked into as most servers can't just change admin systems as addons/mods might not support other admin systems and they cannot invest time into changing them/ don't know how. I personally had to change 5 - 7 addons to support CAMI. This isn't a DarkRP problem but steps can be made to reduce the impact.

**Comment by FlorianLeChat** [comment]
Considering the state of ULX and ULib, all server owners should abandon this old, bloated and laggy system and use FAdmin or other solutions like SAM instead. For years I used the FAdmin and despite some flaws, it worked perfectly well and without any problems. However, if you want an addon like ULX but created by a competent programmer, you should look at [SAM](https://www.gmodstore.com/market/view/6650), it's not free but well worth the cost.

**Comment by Kapppa** [comment]
> Considering the state of ULX and ULib, all server owners should abandon this old, bloated and laggy system and use FAdmin or other solutions like SAM instead. For years I used the FAdmin and despite some flaws, it worked perfectly well and without any problems. However, if you want an addon like ULX but created by a competent programmer, you should look at [SAM](https://www.gmodstore.com/market/view/6650), it's not free but well worth the cost.

We did change to SAM :)

**Comment by mcNuggets1** [comment]
Or just turn of logging to file and it works a charm.
I actually redid a lot of ULX's code and it tends to work perfectly without any issues.
