### ISSUE TITLE
spawn jobs and doorgroups reset after restart

### ISSUE THREAD

**Issue by RLanTa** [FPtje/DarkRP#3133]
### Description of the bug

After putting a spawn and the doorgroups I restart the server but the spawn jobs reset and the same for the doorgroups really need help really (I presume it's the latest version of the darkrp) and I've already scanned everything almost everything the topics that talk about that

### How to make the bug happen

When i set job spawnpoints

### Lua errors

[darkrpmodification] gamemodes/darkrp/gamemode/libraries/simplerr.lua:528: [ERROR] A runtime error has occurred in "addons/darkrpmodification/lua/darkrp_customthings/jobs.lua" on line 8.
The best help I can give you is this:

Corrupt team: Kursiyer!
This job does not have a unique command.

Hints:
            - There must be some other job that has the same command.
            - Fix this by changing the 'command' of your job to something else.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
            1. addons/darkrpmodification/lua/darkrp_customthings/jobs.lua on line 8
            2. function 'doInclude'
            3. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 138
            4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 149
            5. gamemodes/darkrp/gamemode/cl_init.lua on line 56
------- End of Simplerr error -------

    1. error - [C]:-1
        2. error - gamemodes/darkrp/gamemode/libraries/simplerr.lua:528
            3. createJob - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:427
                4. unknown - addons/darkrpmodification/lua/darkrp_customthings/jobs.lua:8
                    5. doInclude - [C]:-1
                        6. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:138
                            7. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:149
                                8. unknown - gamemodes/darkrp/gamemode/cl_init.lua:56

### Why the developer of DarkRP is responsible for this issue

**Comment by mcNuggets1** [comment]
[darkrpmodification] gamemodes/darkrp/gamemode/libraries/simplerr.lua:528: [ERROR] A runtime error has occurred in "addons/darkrpmodification/lua/darkrp_customthings/jobs.lua" on line 8.
The best help I can give you is this:

Corrupt team: Kursiyer!
This job does not have a unique command.

**Comment by FPtje** [comment]
It's interesting that the first thing many people appear to notice is the door groups. I think we can help a lot of people if we catch this in DarkRP and give some tips on what to do :thinking:

**Comment by FPtje** [comment]
Added a hint: `Note: This error likely breaks your server. Make sure to solve the error!`

I hope people look at it.
