### ISSUE TITLE
DarkRP Job bug/ Main Weapons Bug pls help

### ISSUE THREAD

**Issue by nutellabrot2** [FPtje/DarkRP#3138]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Hello im Currently working on a Garrys mod Server, and i have the Bug that all the Jobs spawn with the Arrest/Unarrest/Weapon checker/Stun stick and Battering ram tools. I Already looked in the Settings folder (/garrysmod/addons/darkrpmodification-master/lua/darkrp_config) and nothing was there.

my Second Problem is that i cant change the Default jobs or Categories pls help)

### How to make the bug happen
[//]: # (dont know)
[//]: # (dont know)

### Lua errors
[//]: # ([darkrpmodification-master] addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:640: 'end' expected (to close 'if' at line 606) near '<eof>'
    1. loadCustomDarkRPItems - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:138
        2. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:149
            3. unknown - gamemodes/darkrp/gamemode/cl_init.lua:56)
[//]: # (The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 406
	2. function 'xpcall'
	3. gamemodes/darkrp/gamemode/libraries/simplerr.lua on line 475
	4. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	5. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
	6. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 138
	7. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 149
	8. gamemodes/darkrp/gamemode/init.lua on line 112
------- End of Simplerr error -------
)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
The first one is the setting that admins spawn with cop weapons. The second one is a configuration errror in your `jobs.lua`.

> Why the developer of DarkRP is responsible for this issue

I'm not.
