### ISSUE TITLE
cannot pickup money with darkrp gamemode

### ISSUE THREAD

**Issue by FreeGoProCodes** [FPtje/DarkRP#3140]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
Cannot pickup money in darkrp gamemode

### How to make the bug happen
Since i made the server

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I'm not sure if its the developer or the game.

**Comment by FlorianLeChat** [comment]
Does your server have CSS installed?

**Comment by FPtje** [comment]
> Does your server have CSS installed?

I made a song about this years ago. Haven't been able to post it in years! I actually had to upload it again because it was nowhere to be found.

Enjoy the solution in the lyrics of the custom made song here: https://voca.ro/1hzIXJgYfn1c
