### ISSUE TITLE
AFK module and /demote incompatibility

### ISSUE THREAD

**Issue by ReliableSolus** [FPtje/DarkRP#3144]
### Description of the bug
The problem occurs if the person himself stood in AFK through the command. If at this point, fire the person via /demote, then nothing will change. But when he leaves AFK state, he will have an incorrect darkrpvar(job) set.

### How to make the bug happen
1. Use AFK.
2. Other player demote you.
3. You use AFK.
4. Check job var.

### Lua errors
No one.

**Comment by ReliableSolus** [comment]
If possible, it is desirable to make the dismissal take place immediately.

**Comment by Hardeh** [comment]
Also it seems like that demoted AFK players still count as job player limit, thus making impossible to free job slot until player comes back from AFK.

**Comment by FPtje** [comment]
They do, they get demoted when they come back. I've fixed the issue described in the OP.
