### ISSUE TITLE
Discord server link (ON THE WIKI) invalid

### ISSUE THREAD

**Issue by StupidRepo** [FPtje/DarkRP#3149]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
Ok look, this isn't a bug but I thought I'd report it here since it's something to look at

### How to make the bug happen
Delete the discord invite from Server Settings > Invites :rofl: 

### Lua errors
[Discord.LUA] Server invalid! :rofl:

### Why the developer of DarkRP is responsible for this issue
Because they're the ones who made the discord server (I think)

**Comment by FlorianLeChat** [comment]
I just updated the links, however anyone can edit the wiki (including you) so there's no need to create an issue for that, as it's mainly reserved for technical problems and bugs experienced with the gamemode.

**Comment by StupidRepo** [comment]
Yep sorry I just noticed you could edit.

**Comment by FPtje** [comment]
Thanks for keeping an eye on it!
