### ISSUE TITLE
FPtje you broke darkrp

### ISSUE THREAD

**Issue by Hokaz** [FPtje/DarkRP#3165]
Hello, FPtje. I noticed today that your darkrp does not remove the prop and the entity, and I tried everything reinstalled darkrp reinstalled the local server, even reinstalled gmod, but nothing helped, so it seems to me that you broke something in darkrp that now it does not delete anything when you exit the server.

**Comment by FPtje** [comment]
This is an issue that many people have had over the years, and every time I looked, it's some other addon that actively breaks it. Until you remove that shitty addon, reinstalling darkrp won't do shit.

There's  enough precedence with this specific issue for me to dismiss it out of hand. You'll need some evidence for the particular claim that I'm the one who caused it.
