### ISSUE TITLE
Why isnt it just made with table.merge(....)

### ISSUE THREAD

**Issue by Pdzly** [FPtje/DarkRP#3168]
https://github.com/FPtje/DarkRP/blob/aa4f873ba4c4e34a73f4bfcc9f83eff7a8931a9a/gamemode/modules/base/sh_createitems.lua#L412

**Comment by mcNuggets1** [comment]
tf

**Comment by Kefta** [comment]
🧐

**Comment by FPtje** [comment]
Because the function does more than just merging tables.
