### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lucascenseur** [FPtje/DarkRP#3180]
Hi, I’m French, sorry if the translator says nonsense.

I wanted to make a suggestion:

Add an order, 
Which would allow you to give money to an offline player by going through the console and using the steamid.

Thank you for your time and for all you have already done!

**Comment by FPtje** [comment]
This could technically be implemented in darkrp, but it's an extremely rare use case, and many servers might not want it to be possible. I'd say it's best to create an addon for this feature.
