### ISSUE TITLE
Money breakdown on the server

### ISSUE THREAD

**Issue by BazZziliuS** [FPtje/DarkRP#3207]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
Money breakdown on the server
This problem appeared when I installed DarkRP from the master branch and occurs in different places, but in all errors there is a reference to "sv_money.lua:8" and "sv_jobs.lua:204"
I don't know how to reproduce the bug, it occurs by itself

### How to make the bug happen
Unfortunately there is no information on how to fix it

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
```
[job_slawer_mayor] gamemodes/darkrp/gamemode/modules/money/sv_money.lua:8: attempt to perform arithmetic on a nil value
  1. addMoney - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:8
   2. fn - addons/job_slawer_mayor/lua/slawer_mayor/modules/taxs/sv.lua:64
    3. Call - addons/admin_ulib/lua/ulib/shared/hook.lua:109
     4. callback - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:26
      5. retrieveSalary - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:442
       6. payDay - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:24
        7. unknown - gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua:204
```
```
[DarkRP] gamemodes/darkrp/gamemode/modules/money/sv_money.lua:8: attempt to perform arithmetic on a nil value
  1. addMoney - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:8
   2. fn - addons/job_slawer_mayor/lua/slawer_mayor/modules/taxs/sv.lua:64
    3. Call - addons/admin_ulib/lua/ulib/shared/hook.lua:109
     4. callback - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:26
      5. retrieveSalary - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:408
       6. payDay - gamemodes/darkrp/gamemode/modules/money/sv_money.lua:24
        7. unknown - gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua:198
Timer Failed! [76561198280234533jobtimer][@gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua (line 193)]
```

**Comment by FPtje** [comment]
Judging purely from the error, it looks like an addon named job_slawer_mayor is trying to do something with taxes on the payday, and that this is going wrong.

A payday happens every couple of minutes or so for every player. That would explain why you see the error in the console without explicitly triggering it.

The error would be with that addon, as it most likely asks darkrp to change someone's money, without saying how much (that is the nil value). Your next step would be to contact the author with that information. That's all the help I can give.

**Comment by BazZziliuS** [comment]
Oh there was no such error before and I thought that the problem was in drp because I updated it and this problem appeared
Well thank you I will try to fix it

**Comment by BazZziliuS** [comment]
I found a pattern when you update sv_events.lua then the money breaks

**Comment by FPtje** [comment]
Yeah, the traditional advice is not to edit darkrp's core files.
