### ISSUE TITLE
Update DarkRP Workshop Addon

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/DarkRP#3215]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Not a bug, however I noticed the [DarkRP Workshop addon](https://steamcommunity.com/workshop/filedetails/?id=248302805) has not been updated since 2021. Not sure if there's any particular reason for such ([Database engine migration perhaps?](https://github.com/FPtje/DarkRP/issues/3157#issuecomment-1002127024)), but if not, perhaps it would be time for an update? Would be much appreciated.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
N/A

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
N/A

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The official Workshop addon can only be updated by the DarkRP developer.

**Comment by FPtje** [comment]
Huh, has it been that long? I would wear I had run the update somewhere in 2022

**Comment by FPtje** [comment]
I just uploaded the latest version. Thanks for bringing it up!
