### ISSUE TITLE
btw stupid question

### ISSUE THREAD

**Issue by fanidamn** [FPtje/DarkRP#3216]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
sorry for disturbing, i have a stupid question, how to make my lua overrides yours?
e.g. my custom hud =)

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
-

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
-

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
-

**Comment by FPtje** [comment]
See the darkrpmod, you can disable the hud there.

**Comment by fanidamn** [comment]
btw i can't find a default hud disable function, it isn't in config.

**Comment by FlorianLeChat** [comment]
> btw i can't find a default hud disable function, it isn't in config.

https://github.com/FPtje/darkrpmodification/blob/675473fe34a4703045659145d71bb060e031c38c/lua/darkrp_config/disabled_defaults.lua#L33
