### ISSUE TITLE
cpcanarrestcp setting broken 

### ISSUE THREAD

**Issue by JellyPies** [FPtje/DarkRP#3219]
### Description of the bug
**Config Description of Setting**
`cpcanarrestcp - Allow/Disallow CPs to arrest other CPs.`

**CASE:** `GM.Config.cpcanarrestcp = true`

**Expected Result & Actual Result**
```
If true then civil protection jobs are allowed to arrest players as well as other civil protection.
```

**CASE:** `GM.Config.cpcanarrestcp = false`
**Expected Result**
```
If false then civil protection jobs are allowed to arrest players, not NOT other civil protection.
```

**Actual Result**
```
When false, civil protection can't arrest players or other civil protection teams
```

### How to make the bug happen
Change the setting to false in your darkrp modification, observe how no civil protection jobs can arrest anyone.

### Lua errors
No errors occur as a result of this bug, as it's more of a logical error.

### Why the developer of DarkRP is responsible for this issue
Bug was tested on a fresh server in an isolated docker environment with just the darkrp gamemode, and darkrp modification addon installed. It's has no conflicts with other addons, and originates from the core gamemode itself.

**Comment by FPtje** [comment]
This looks like a good bug report. Why was it closed?

**Comment by JellyPies** [comment]
@FPtje In the end my game panel decompression extension was decompressing the jobs.lua file but cutting it off short so the end was missing. It was just perfect enough that the Civil Protection table was missing. DarkRP assumed all jobs were civil protection because of it.

**Comment by FPtje** [comment]
Thanks for the answer!
