### ISSUE TITLE
Darkrp jobs reset after server restart.

### ISSUE THREAD

**Issue by kazz708** [FPtje/DarkRP#3224]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I make custom jobs and when i restart my server they are all gone.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
start the game, add custom jobs with dconfig2 and then restart the server, none of the jobs save.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
Because my custom jobs never save

**Comment by FPtje** [comment]
I'm not responsible for issues like that, that's a result of something you did to your server.

**Comment by kazz708** [comment]
:(
