### ISSUE TITLE
getJobTable doesn't update to reflect the new changes on the server, only client

### ISSUE THREAD

**Issue by Norway174** [FPtje/DarkRP#3225]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)

When you update the jobs table. The [getJobTable()](https://darkrp.miraheze.org/wiki/Functions/Player/Shared/getJobTable) function on the client is update accordingly to show the new values.
However, on the server, it's still showing the old values for the job.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)

Create a DarkRP server. With at least 1 job. Make sure LUA Refresh is enabled. (Should be by default.)

Play on the job.

Run this in your local player console:
`lua_run_cl PrintTable( Entity( 1 ):getJobTable() )`
And this in the server console:
`lua_run PrintTable( Entity( 1 ):getJobTable() )`

Update the Job. Either the models, or the weapons, or both. (Those are what I've tested.)

Run the same commands again.
Compare the tables.

What you should see is that the table on the client has indeed been updated and reflects the new changes.

Meanwhile, the server table. Still remains as the same old table.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

No errors caused by DarkRP.

-

I try and stand by the philosophy of never trusting the client. So I use the getJobTable function to see if a player does have access to a certain weapon for his or her job, before giving it to them.

However, if the jobs table on the server is outdated. I have no way of verifying if a player has access to a new weapon. If I were to update the job. Without a server restart.

Maybe there is an alternative function to get the weapons of a job table that I'm not aware of, that is updated?

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

The issue is related to a DarkRP function:
https://darkrp.miraheze.org/wiki/Functions/Player/Shared/getJobTable

**Comment by FlorianLeChat** [comment]
> Update the Job. Either the models, or the weapons, or both. (Those are what I've tested.)

How did you "update" this job? In which realm?

**Comment by Norway174** [comment]
> How did you "update" this job? In which realm?

I would've thought it's supposed to be shared?
I'm using the [darkrpmodification ](https://github.com/FPtje/darkrpmodification) addon that's suggested to use.

With the jobs defined in this file: `darkrpmodification\lua\darkrp_customthings\jobs.lua`

I change the jobs in that file. And upload it to the server with FTP.

After I upload it, the client hangs for a bit as it's reloading everything.
Not sure about the server. As it's hard to tell through the console.

But it does say Unhandled Lua Refresh, so it should have loaded the new file.

**Comment by Kefta** [comment]
Unhandled Lua Refresh usually means the Lua refresh was unsuccessful, probably because you're doing it thru FTP which can be finicky. This is not a problem with DarkRP.

**Comment by FPtje** [comment]
Thanks for the explanations. I know very little about the Lua refresh details

**Comment by joeyjumper94** [comment]
> > How did you "update" this job? In which realm?
> 
> I would've thought it's supposed to be shared? I'm using the [darkrpmodification ](https://github.com/FPtje/darkrpmodification) addon that's suggested to use.
> 
> With the jobs defined in this file: `darkrpmodification\lua\darkrp_customthings\jobs.lua`
> 
> I change the jobs in that file. And upload it to the server with FTP.
> 
> After I upload it, the client hangs for a bit as it's reloading everything. Not sure about the server. As it's hard to tell through the console.
> 
> But it does say Unhandled Lua Refresh, so it should have loaded the new file.

i think your problem is SimplErr.
it is a module that is used to check for errors and provide a detailed explanation of why it errored, but it breaks autorefresh on the serverside
