### ISSUE TITLE
Feature Request: New Setting for Gunlab Weapon Price

### ISSUE THREAD

**Issue by Rumsfield** [FPtje/DarkRP#3226]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
This is a feature request to make the purchase price of weapons from the gun lab into a new setting, instead of hard-coded as 200.
https://github.com/FPtje/DarkRP/blob/master/entities/entities/gunlab/shared.lua#L6

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
1. Purchase a gun lab
2. Buy a gun from it by pressing E on the gunlab
3. Observe a fixed cost of $200 be withdrawn from the player's money

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
It would be beneficial to everyone to have this extra setting. It allows server owners to have more control over economy prices.

[empty.txt](https://github.com/FPtje/DarkRP/files/11715943/empty.txt)

**Comment by FPtje** [comment]
Done, thanks!

Added gunlabguncost and druglabdrugcost
