### ISSUE TITLE
[Request] Add automatic Workshop addon updates through GitHub Actions

### ISSUE THREAD

**Issue by FlorianLeChat** [FPtje/DarkRP#3228]
Currently, the DarkRP Workshop addon is updated manually and only by Falco's willingness. Despite this method providing a degree of code stability by giving those using the GitHub version time to test the latest features and bug fixes, this delay can be extremely annoying, because important bug fixes take a long time to reach the majority of servers using the Workshop version, resulting in complaints or bug reports (already fixed) on some Discord support servers.

To solve this issue, I propose to use GitHub Actions to automatically update the addon on **each commit**, or **periodically** (every 1 month, for example) so changes can be deployed more quickly on all community servers.

I've compiled a **non-exhaustive** list of open-source tools which could be used:
- https://github.com/Earu/GSW-action
- https://github.com/Vurv78/gmod-upload
- https://github.com/Weilbyte/steam-workshop-upload

If you have any ideas or feedback, please go ahead! 👍

**Comment by FPtje** [comment]
That would certainly make things easier for me 🤔

**Comment by FPtje** [comment]
Wait, hold on. Do all those methods rely on putting my steam username, password _AND_ 2fa secret in Github secrets store? I can't just generate an API for it?

That account has all my games 😅
Maybe I can create a dummy account, give it upload access to just DarkRP, and use that for workshop uploading.

**Comment by FlorianLeChat** [comment]
> Wait, hold on. Do all those methods rely on putting my steam username, password _AND_ 2fa secret in Github secrets store? I can't just generate an API key for it?

I think the tools are limited to what Steam provides as authentication methods so unfortunately yes, otherwise a secondary account just like you suggest can do the trick too

**Comment by FPtje** [comment]
Ugh, looks like the `gm_publish `shipped with gmosh silently fails. I tried to run it, and it says it all went well, but in reality the DarkRP page was not updated. Running the `gm_publish` from gmod's bin dir manually worked. That's annoying, as it makes my usual way of updating DarkRP on the workshop harder.

**Comment by FPtje** [comment]
So essentially to do this, the following steps will be needed:

- Create an alt account for specifically updating DarkRP
- Make this account a contributor to the DarkRP addon
- Have some program create a GMA file. Gmosh has traditionally been my program of choice, but it's also old and kinda broken. It still makes GMAs just fine though. I might be able to go back to that old beast and fix it up, but I reckon that this is where the most effort is at.
- Write a metadata file with `.vdf` extension. [example](https://github.com/Vurv78/gmod-upload/blob/master/action.yml#L43-L53)
- Run steamcmd to do the upload. [example](https://github.com/Vurv78/gmod-upload/blob/master/action.yml#L55-L58)

**Comment by FPtje** [comment]
Another thing to take into account is that DarkRP has a special branch named workshop, because the folder structure is entirely different between gamemode in the gamemodes fir and in the gma file.

**Comment by FlorianLeChat** [comment]
Sounds like it's harder than I expected 😭

**Comment by FPtje** [comment]
I used to have this alias to update the workshop:

```
alias darkrpmosh='git checkout workshop && git pull && git merge master --no-edit && git push && gmosh && git checkout master'
```

I tried to use this again yesterday when I found out that the publishing didn't actually work.

It's all possible, just some effort. I wonder if DarkRP will get frequent enough updates to warrant the effort 🤔

**Comment by FlorianLeChat** [comment]
It's evident now the DarkRP is unlikely to receive any major changes in the near future (unless some crazy guy still wants again to drastically optimize some parts of the gamemode). The whole idea of this request was to get rid of this handwork once for all to ensure all major bug fixes/improvements are rolled out quickly. If this request requires too much work in the short term, let's just say it can be considered as "long-term work" if one day you feel like automating the process 👍

**Comment by FPtje** [comment]
I managed to pack the cli part of gmosh in a Nix flake. If I can get it to work with steamcmd, then I could use that in a Github action. So far I've been getting weird errors with steamcmd though. There might be something off with my install.

**Comment by FPtje** [comment]
Turns out it's not reasonably possible: https://github.com/FPtje/Falcos-Prop-protection/pull/317

Closing issue, as the sacrifice to make it possible is unreasonable.

**Comment by FlorianLeChat** [comment]
I noticed your comment, it's very frustrating but we can only blame Steam for being so shitty about that. Thanks Falco for your time and effort, I hope one day your work will be used!
