### ISSUE TITLE
Unable to PM players with spaces after first character in their name

### ISSUE THREAD

**Issue by jacobianb** [FPtje/DarkRP#3230]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
I am unable to PM players with spaces after first character in their name on a large server with many players.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
Attempt to PM a player like "J A K E" on a server with other people named Jason, Jakob, etc. Good luck. The coding on GitHub currently explodes out parameters by the first space in the command, instead of allowing things like /pm "J A K E" Hello... this does not work as intended.

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
None.

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
The PM command is a core DarkRP features necessary for private communications on a server. This private communication cannot be used between 2 players who both have spaces after the first character in their name and it is very annoying and very difficult to workaround when there are no PM alternatives on the server that I choose to play on. I believe the DarkRP developers are responsible for this oversight and that it could and should be remedied by the DarkRP developers.

**Comment by FPtje** [comment]
The given solution for this is actually to use console commands. The chat system is inherently limited. Not just with the space problem, but more so with the amount of characters it supports. The traditional solution is to run `darkrp pm "J A K E" message`.

I'm not sure, but you might also be able to use their user id: `/pm 63 message`

I understand the request, but I really don't feel like writing a fancy argument parser.

**Comment by SirGinshi** [comment]
> The given solution for this is actually to use console commands. The chat system is inherently limited. Not just with the space problem, but more so with the amount of characters it supports. The traditional solution is to run `darkrp pm "J A K E" message`.
> 
> I'm not sure, but you might also be able to use their user id: `/pm 63 message`
> 
> I understand the request, but I really don't feel like writing a fancy argument parser.

Shouldn't it be possible to simply use string.match for this? I haven't worked with Lua for a long time, but since I've been working a lot with re from python lately, I wrote a small example code for the PM function (smaller code = fancy code, lol)

```lua
local function PM(ply, args)
    local name, msg = string.match(args, '"(.-)"%s*(.+)')

    if not name or not msg then
        DarkRP.notify(ply, 1, 4, DarkRP.getPhrase("invalid_x", DarkRP.getPhrase("arguments"), ""))
        return ""
    end

    local target = DarkRP.findPlayer(name)
    if not target then
        DarkRP.notify(ply, 1, 4, DarkRP.getPhrase("could_not_find", tostring(name)))
        return ""
    end

    local col = team.GetColor(ply:Team())
    local pname = ply:Nick()
    local col2 = color_white

    DarkRP.talkToPerson(target, col, "(PM) " .. pname, col2, msg, ply)
    DarkRP.talkToPerson(ply, col, "(PM) " .. pname, col2, msg, ply)

    return ""
end
DarkRP.defineChatCommand("pm", PM, 1.5)
```

**Comment by FPtje** [comment]
That solution wouldn't be ideal, because it forces using quotes in _every_ situation, even if the name does not have spaces. Perhaps something along the lines of  `("(.-)"|([^\s]+))%s*(.+)` would work, but that requires regex finagling and testing against Lua's specific interpretation of regex.
