### ISSUE TITLE
Vanilla Drug Lab entity fails to set its model

### ISSUE THREAD

**Issue by Nocty1501** [FPtje/DarkRP#3232]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Spawning the vanilla DarkRP Drug Lab causes a runtime error.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
1. Change jobs to either TEAM_GANG or TEAM_MOB
2. Purchase a Drug Lab from the F4 menu

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)
```
There is 1 Lua problem!
	Please check your console for more information!
	Note: This error likely breaks your server. Make sure to solve the error!
[ERROR] A runtime error has occurred in "gamemodes/darkrp/entities/entities/drug_lab/init.lua" on line 11.
The best help I can give you is this:

drug_lab has model "models/error.mdl" with no physics and will be motionless

Hints:
	- Does this model have an associated physics model (modelname.phy)?
	- Is this model supposed to have physics? Many models, like effects and view models aren't made to have physics

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/entities/entities/drug_lab/init.lua on line 11
	2. function 'Spawn'
	3. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 308
	4. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 366
	5. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 17
	6. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 327
	7. lua/includes/modules/concommand.lua on line 54
------- End of Simplerr error -------
```

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)
I am using the Workshop installation of DarkRP, and this is the built-in vanilla Drug Lab. Disabling the default Drug Lab and re-making the entry in `entities.lua` in `darkrpmodification` doesn't help.
I have Counter-Strike: Source, Half-Life 2: Episode 1, Half-Life 2: Episode 2, and Half-Life 2: Lost Coast mounted on my server.

**Comment by FPtje** [comment]
The drug lab model is the zombie trap from HL2. Besides the episodes and lost cost, it looks like you need to mount HL2 itself

**Comment by Nocty1501** [comment]
> The drug lab model is the zombie trap from HL2. Besides the episodes and lost cost, it looks like you need to mount HL2 itself

The drug lab is actually a `models/props_lab/crematorcase.mdl`... I'm not sure what you mean by "zombie trap", are you talking about the motors under the spinning blades in Ravenholm?
Regardless, I am able to spawn the model itself as a prop just fine, and I just tested it in singleplayer and the Drug Lab also fails to spawn there. I have all of the aforementioned games mounted as well as Half-Life 2. Can you confirm this is not happening on your end?

**Comment by FPtje** [comment]
Ah yes, I confused it with th6e gun5lab. The drug lab and its model haven't changed for pretty much a decade, it's extremely unlikely that this is actually a problem in darkrp itself. 

Perhaps a different, earlier error causes this one. When you have errors, it's important to always look at the earliest one, even if from another addon. Often, errors cause the whole game to get in some wacky state, causing all sorts of other problems and errors that make no sense on their own.

**Comment by Nocty1501** [comment]
There are no other errors. It happens only when the Drug Lab is bought. The lab spawns as a floating ERROR with no physics and prints the message in OP to console.

Can you please verify this doesn't happen on your end?

**Comment by FPtje** [comment]
![druglab working](https://github.com/FPtje/DarkRP/assets/1202014/c58ca5dd-856b-43b6-9bf7-9e1ec9979b74)

Cannot reproduce. This is a user issue.

**Comment by Nocty1501** [comment]
> ![druglab working](https://user-images.githubusercontent.com/1202014/258579257-c58ca5dd-856b-43b6-9bf7-9e1ec9979b74.png)
> 
> Cannot reproduce. This is a user issue.

Huh. Odd. I wonder why it fails on my end, this is a clean DarkRP install... Well, thanks for confirming, will try to figure this one out on my own!

**Comment by sel1001** [comment]
I think the reason is that the issue only appears in the workshop version
