### ISSUE TITLE
Voting menu causes error, SetCommand was removed

### ISSUE THREAD

**Issue by Aws0mee** [FPtje/DarkRP#3237]
### Description of the bug
The vote menu is broken and triggers an error after the newest gmod update. As Rubat stated [here](https://wiki.facepunch.com/gmod/Panel:SetCommand%7Ehistory), the function was removed for some reason.

![image](https://github.com/FPtje/DarkRP/assets/51889746/19fa1112-fb92-4464-a955-b0338ce343cc)

### How to make the bug happen
Whenever somebody tries to become a vote job this bug will occur.

### Lua errors
```lua
[DarkRP] gamemodes/darkrp/gamemode/modules/voting/cl_voting.lua:74: attempt to call method 'SetCommand' (a nil value)
  1. Function - gamemodes/darkrp/gamemode/modules/voting/cl_voting.lua:74
   2. unknown - lua/includes/modules/usermessage.lua:80
   ```

### Why the developer of DarkRP is responsible for this issue
He is not. I am simply posting this here for the sake of documenting this bug. I will be fixing it in a PR.

**Comment by Aws0mee** [comment]
Hopefully any other server owners having this problem will find this issue so they know to update.

**Comment by Penrolz** [comment]
> Hopefully any other server owners having this problem will find this issue so they know to update.

i dont have lua knowledge removing
SetCommand
disables vote page that appears when someone selects a job
requires voting
