### ISSUE TITLE
Workshop Gone

### ISSUE THREAD

**Issue by multiaudacity** [FPtje/DarkRP#3241]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible) DarkRP no longer on the workshop, that's it 

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out) visit the link
[//]: # (what the cause of the problem is and whether a certain fix solves it)

### Lua errors
[//]: # (Note that errors on server startup are more important than other ones)
[//]: # (because they can cause other errors. Always look in the startup log of the server!)

### Why the developer of DarkRP is responsible for this issue
[//]: # (By posting on Github, you ask the developers of DarkRP to solve the problem)
[//]: # (It may seem obvious to you, but you have to make clear why they are the right people to look at it)

**Comment by FPtje** [comment]
Thanks for the heads up! Steam demanded I agree to an update to their damn agreement. I get no notification of this whatsoever. The upload to workshop just succeeds, no warnings, emails or anything. I need to go to the actual page to see it.

And until I agree to the new one, they just hide it on the workshop. Anyway, it's fixed now.
