### ISSUE TITLE
Error money

### ISSUE THREAD

**Issue by MathewG7** [FPtje/DarkRP#3246]
**### I think it occurs when using /dropmoney and indicating a higher value of the user's available money.**

There is 1 Lua problem!
	Please check your console for more information!
	Note: This error likely breaks your server. Make sure to solve the error!
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/money/sv_money.lua" on line 14.
The best help I can give you is this:
Some addon attempted to store a invalid money amount -100 for Player Iso (STEAM_0:0:23064325)
Hints:
	- This money amount will not be stored in the database, but it may be set in the game.
	- The database simply stores the last valid, non-negative amount of money.
	- Please try to find the very first time this error happened for this player. Then look at the files mentioned in this error.
	- That will tell you which addon is causing this.
	- IMPORTANT: This is NOT a DarkRP bug!
	- Note: The player can simply rejoin to fix their negative money, until whatever causes this happens again.
The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. gamemodes/darkrp/gamemode/modules/money/sv_money.lua on line 14
	2. addons/mayor-system117/lua/slawer_mayor/modules/taxs/sv.lua on line 41
	3. lua/includes/modules/hook.lua on line 247
	4. gamemodes/darkrp/gamemode/modules/money/sv_money.lua on line 26
	5. gamemodes/darkrp/gamemode/modules/base/sv_data.lua on line 462
	6. gamemodes/darkrp/gamemode/modules/money/sv_money.lua on line 24
	7. gamemodes/darkrp/gamemode/modules/jobs/sv_jobs.lua on line 204
------- End of Simplerr error -------

**Comment by FPtje** [comment]
This is a new feature, added in #3240 by @lionbryce. It looks like the work is paying off.

The feature is that DarkRP will now tell you when an addon is trying to set someone's money to a negative amount. It will even take a shot at telling you which one!

Wallet debt is something that nothing in or around DarkRP is built to work with, so it's considered very bad, and a bug in whatever causes it.

So the most likely culprit here is your mayor-system117 addon, and of it, specifically the taxes part. You can see it as responsibility nr 2 in the error. What you need to do, is report this error to that addon's author. They can fix this.
