### ISSUE TITLE
Porting weapons to sandbox

### ISSUE THREAD

**Issue by Psaurin** [FPtje/DarkRP#3247]
[//]: # (DO NOT REMOVE THIS TEMPLATE.)
[//]: # (GITHUB ISSUES ARE **NOT** FOR HELP)
[//]: # (GO TO THE DISCORD INSTEAD: https://darkrp.page.link/discord )

### Description of the bug
[//]: # (Describe the issue as accurately as possible)
Unable to port weapon to sandbox, weapon appears in menu but does not fire, reload, nor aim in. The hands are also missing when ported.

### How to make the bug happen
[//]: # (Knowing how to make a bug happen allows the developers to figure out)
[//]: # (what the cause of the problem is and whether a certain fix solves it)
poorly port to sandbox

**Comment by Kefta** [comment]
The weapon base relies on gamemode features, you cannot merely expect them to work in sandbox without modifying them.

**Comment by Psaurin** [comment]
I understand that but for personal use I'd like to use them in a separate gamemode, How (if possible) could I do it?

**Comment by Kefta** [comment]
You'll have to do manual debugging and see what's missing/what needs to be changed for them to function. There's a lot of code and no explicit tutorial on how to de-DarkRP-ify them.

**Comment by FPtje** [comment]
I'm afraid I can't help. Porting indeed comes with some challenges, because I never expected them to be separate from DarkRP.
