### ISSUE TITLE
server crashing after i enter changes in gamemode/darkrp/ files in this any folder lua file

### ISSUE THREAD

**Issue by Bacring** [FPtje/DarkRP#3251]
server crashing after i enter changes in gamemode/darkrp/ files in this any folder lua file
i start gmod start.bat and after i change something for example jobs.lua  then i got server shutting down and console don't accept commands and after i try reconnect to then server then i have error connection closed or timeout

**Comment by FPtje** [comment]
That sounds like a Lua refresh issue. I'm afraid I don't have any control over that, that's a Gmod issue.
