### ISSUE TITLE
Law Board

### ISSUE THREAD

**Issue by awesomeguy36** [FPtje/DarkRP#3267]
### Problem

I am unable to physically interact with the law board when I do /placelaws 

I have not modified the darkrp gamemode in any way and strictly use darkpmodification-master in the addons for any edits. 

### Errors

[ERROR] A runtime error has occurred in "[C]" on line -1.
The best help I can give you is this:

darkrp_laws has missing model "models/props/cs_assault/billboard.mdl" and will be invisible and motionless

Hints:
	- Is the model path correct?
	- Is the model from an addon that is not installed?
	- Is the model from a game that isn't (properly) mounted? E.g. Counter Strike: Source

The responsibility for the error above lies with (the authors of) one (or more) of these files:
	1. function 'Spawn'
	2. gamemodes/darkrp/entities/entities/darkrp_laws/init.lua on line 163
	3. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 17
	4. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 80
	5. gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua on line 140
------- End of Simplerr error -------

**Comment by FPtje** [comment]
There used to be a song about this, because it happened so often. DarkRP uses some stuff from the game Counter Strike: Source. You need to mount the content of it in your game server. If you don't, you get floating money, guns and law boards.

**Comment by awesomeguy36** [comment]
Ahhh yes, the good ole' CS missing textures song... 

I set up my server, thought everything was fine,
Loaded up Garry’s Mod, ready for a good ol' time.
But then came the errors, red text everywhere,
Lua freakin' out, man, it’s more than I can bear.

Weapons are invisible, textures all gone,
Props won't spawn, my server’s all wrong!

CS, where you at, my friend?
Mounting’s a must, or my DarkRP’s the end!
Gmod's cryin’, Lua’s goin’ mad,
Without you, CS, it's all just bad.

I tried restarting, and I verified files,
Checked my config twice, but still no smiles.
That missing texture, it haunts my dreams,
Pink and black squares, it’s worse than it seems.

Spawning in the map, players start to groan,
It’s like building a house with no cornerstone.

CS, where you at, my friend?
Mounting’s a must, or my DarkRP’s the end!
Gmod's cryin’, Lua’s goin’ mad,
Without you, CS, it's all just bad.

Gotta get to steamcmd, download those files,
Change the mount.cfg, hope it’s worth the while.
Oh please, CS, make my DarkRP bright,
Fix these errors, let us play tonight!

CS, where you at, my friend?
Mounting’s a must, or my DarkRP’s the end!
Gmod's cryin’, Lua’s goin’ mad,
Without you, CS, it's all just bad.

So here’s to fixing configs and mounting right,
Let’s banish Lua errors, get back to the fight.
DarkRP’s broken, but we’ll mend the rift,
With CS mounted, we’ll finally uplift!

Thanks for the help lol

**Comment by FPtje** [comment]
That's amazing, haha.

The song I'm referring to is one I recorded a long while ago. I can't seem to find it on YouTube or Google, unlike the other song called core files.

It was an act of frustration that people kept asking every single week about the same problem. It also contains some strong profanity.

**Comment by awesomeguy36** [comment]
Well, I’m glad to have contributed to some nostalgia for you, lol. Time sure does fly.

Again, thanks for the help!
