### ISSUE TITLE
<bug> report cant change godmod

### ISSUE THREAD

**Issue by dracoluci** [FPtje/DarkRP#3268]
### Problem

https://www.flexclip.com/fr/share/5640299563879331ad24210d6d7d013342723bd.html
you can see with this link the bug I reported

**Comment by FPtje** [comment]
Thanks for the report! It's odd, when I try it myself, I see god mode switching between 0 and 1, which is intended. In your video I only ever see it being set to 0. What more can you tell me about your situation. Does it work if you run `sbox_godmode 1` in the server console? What kind of game are you running?

**Comment by dracoluci** [comment]
I have to go through the console directly manually with this command sbox_godmode 0 and these go to zero

**Comment by dracoluci** [comment]
mais autrement si tu l'acive et desacitive il  il prend la variable  sbox_godmode  1

**Comment by FPtje** [comment]
When I try this on my computer, it switches 1, 0, 1, 0, 1, 0, etc.
Something on your setup is different. I'm not sure what, but it looks like it's not DarkRP itself only that is broken.
