### ISSUE TITLE
Can't Edit/Delete FAdmin Groups

### ISSUE THREAD

**Issue by mleonhard38** [FPtje/DarkRP#363]
Hey, I can't edit/delete the Standard FAdmin Groups (eg superadmin and admin)
Is this normal? Could you please change this?

**Comment by 1146nanolight** [comment]
help i messed around with the settings and for some reason i can not edit or remove groups like admin superadmin and esc...  it allways says no access help me sorry for late posting.

**Comment by FPtje** [comment]
not a help forum.

**Comment by HDG-MrDeeJay** [comment]
Not to mention the mindless necroposting
