### ISSUE TITLE
Admins not able to spawn weapons?

### ISSUE THREAD

**Issue by Jongunner** [FPtje/DarkRP#536]
I could have swarn in config.lua is where we decide admins to spawn weapons or not? I only see these for admin control...

-- adminnpcs - Whether or not NPCs should be admin only.
GM.Config.adminnpcs                     = true
-- AdminsCopWeapons - Enable/disable admins spawning with cop weapons
GM.Config.AdminsCopWeapons              = true
-- adminsents - Whether or not SENTs should be admin only.
GM.Config.adminsents                    = true
-- adminvehicles - Whether or not Vehicles should be admin only.
GM.Config.adminvehicles                 = true
-- advertisements - Enable/Disable chatprint advertisements.

Where can I make it so admins can spawn weapons?

**Comment by philxyz** [comment]
This seems a bit inconsistent with other options.

Also, when set to 1, superadmins can't spawn them. (Current workshop version as of Sat 01 Aug 2015)

**Comment by FPtje** [comment]
http://i.imgur.com/ntIt31J.jpg

Cannot reproduce.
