### ISSUE TITLE
F4 Menu Creating Script Error.

### ISSUE THREAD

**Issue by masonticehurst** [FPtje/DarkRP#557]
Hello, I am new to DarkRP servers but, I found that everytime I hit F4 to change jobs I got these errors:
[ERROR] gamemodes/darkrp/gamemode/client/showteamtabs.lua:660: attempt to concatenate field 'price' (a table value)
1. Update - gamemodes/darkrp/gamemode/client/showteamtabs.lua:660
   1. EntitiesTab - gamemodes/darkrp/gamemode/client/showteamtabs.lua:674
   2. Function - gamemodes/darkrp/gamemode/client/vgui.lua:258
      1. unknown - lua/includes/modules/usermessage.lua:87

**Comment by namekh** [comment]
Hey, I got a similiar problem:

This thing pops up in the console:
!! ERROR: bad input/output link:
!! logic_timer(horsetimer,RefireTime) doesn't match type from logic_relay(horseracerelay)

and this thing:

Failed creating font 'Dotum'!
Failed creating font 'Dotum'!
Failed creating font 'Dotum'!
Failed creating font 'Dotum'!
Failed creating font 'OCR A Extended'!
Failed creating font 'Eras Demi ITC'!
Failed creating font 'Dotum'!
Failed creating font 'csgok'!
Failed creating font 'defaultbold'!
Failed creating font 'Default'!
Failed creating font 'Default'!
Failed creating font 'Default'!
Failed creating font 'Default'!
Failed creating font 'Default'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet'!
Failed creating font 'ChatFont'!
Failed creating font 'DermaLarge'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
 and my playermodel is completely scuffed and i'm spawning in the ground and i cant do anything, i have no weapons and just everything is pretty buggy. i am also running on a darkrp server. Is there any way to fix this shit??

**Comment by Bo98** [comment]
Look for the first Lua error in the console, not the last. If you need help go to https://forum.darkrp.com
