### ISSUE TITLE
Joining/Connecting FUCK YEAH!

### ISSUE THREAD

**Issue by mleonhard38** [FPtje/DarkRP#658]
So, I figured it out.

Please try it yourself.

Arrest someone. He leaves while arrested, then Joins again. He is now Joining/Connecting and bugged. Thats how my Users got Joining/Connecting! Dont think thats my fault...
btw, no Errors in the Console, as those shown in the last Issue.

Edit:
If I am wrong again, and it my fault. I should just kill myself I know. But I don't know how this could happen, I also dont think a addon did this. Running Clean Install of DarkRP without addons.

**Comment by BigBrainAFK** [comment]
I still have the problem with one of my players.

> for _, pl in pairs ( player.GetAll ( ) ) do print ( team.GetName ( pl : Team ( ) ) , GAMEMODE : PlayerInitialSpawn ( pl ) , 25 ) end...
Bürger	nil	25
Bürger	nil	25
Bürger	nil	25
Bürger	nil	25
Bürger	nil	25
[DarkRP] Justin HaschCookie (STEAM_0:0:61853172) has joined the game
[DarkRP] Mados Denson (STEAM_0:0:29883024) has joined the game
[DarkRP] eeeeeeee eeeeeeee (STEAM_0:0:84994160) has joined the game
[DarkRP] Max Mustermann (STEAM_0:0:33366467) has joined the game
[DarkRP] Green Ivies (STEAM_0:0:39224780) has joined the game

**Comment by DivineSouls83** [comment]
I'm getting the same error I don't know how to fix it. Can someone tell me how?
