### ISSUE TITLE
Enforce Playermodels Broken

### ISSUE THREAD

**Issue by Reidmaster** [FPtje/DarkRP#791]
I am getting no errors or anything, but when you change jobs it doesn't switch the model and you can select a model from the context menu.

It works when I test it in singleplayer, but when I test it on the server it doesn't work.

-- enforceplayermodel - Whether or not to force players to use their role-defined character models.
GM.Config.enforceplayermodel            = true

**Comment by XyePie** [comment]
I'm also having the same issue, anyone know if these conflict with darkrp at all? 
 http://steamcommunity.com/sharedfiles/filedetails/?id=502328317

**Comment by bedcorn** [comment]
what?
